-- GUIDED CHILDHOOD CATCH UP · STEP 14 · ai-module-1
-- Paste into a NEW query tab, Run, look for the COMPLETE message.

-- Guided Childhood: AI Literacy module (evergreen lessons). Run after migration 002_ai_module.sql.
insert into public.ai_lessons
  (audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order)
values
-- ===== AGE 7 =====
( 'age_7',
  'what_is_ai',
  'What is AI?',
  'AI is a clever computer helper. It is a bit like a parrot that has heard millions of sentences and learns to copy them. It does not really think or feel like you do. It looks at patterns and makes a good guess at what comes next.',
  'You are growing up with AI all around you, in tablets, games and helpers that talk. Knowing it is a guessing machine and not a person helps you stay the boss of it.',
  'Ask a grown up to show you a talking helper, then notice that it copies words it has heard before.',
  'AI is a guessing machine, not a thinking person.',
  'How do I explain to my 7 year old what AI actually is?',
  10 ),

( 'age_7',
  'how_ai_learns',
  'How does AI learn?',
  'AI learns by looking at huge piles of pictures and words, more than you could ever count. It is like learning what a cat looks like after seeing a million cat photos. Nobody hands it rules. It spots patterns by itself.',
  'When you know AI learns from lots of examples, it stops feeling like magic. It is just very good pattern spotting, and you can understand it.',
  'Look at three photos of dogs together and notice the things that are the same. That is how AI learns too.',
  'AI learns by spotting patterns in lots of examples.',
  'What is a simple way to explain how AI learns to a young child?',
  11 ),

( 'age_7',
  'llms_chatbots',
  'Talking helpers',
  'Some AI helpers can chat with words, like Claude. They guess the next word that usually comes after the last one, a bit like finishing a song you know. They are not really talking to you. They are filling in likely words very fast.',
  'You will meet chatty helpers in many places. Understanding that they guess words helps you enjoy them without believing every single thing they say.',
  'Start a sentence like "Once upon a time" and take turns guessing the next word. That is the chatbot game.',
  'Chatbots guess the next word, very fast.',
  'How do I describe chatbots to my child without making them seem alive?',
  12 ),

( 'age_7',
  'ai_safety',
  'Ask a grown up',
  'AI can be fun, but it does not know you or love you. If something feels strange, scary or too good to be true, you stop and tell a grown up you trust. A helper on a screen is never a swap for a real person who cares about you.',
  'Children sometimes think a friendly screen voice is a safe friend. Learning to bring things to a trusted adult keeps you safe and happy.',
  'Pick one trusted grown up today and say, "If a screen ever worries me, I will come and tell you."',
  'A trusted grown up always comes before a screen.',
  'How do I teach my 7 year old to come to me when something online feels wrong?',
  13 ),

( 'age_7',
  'hallucinations',
  'Sometimes it is wrong',
  'AI can sound very sure and still be wrong. It is guessing, so sometimes the guess is silly or made up. Just because it says something in a confident voice does not make it true.',
  'You will use AI for homework and questions one day. Knowing it can be wrong means you will check with a book or a grown up instead of believing everything.',
  'Ask an AI helper a funny question and see if the answer is right or a bit made up.',
  'AI can be wrong even when it sounds sure.',
  'How do I help my child understand AI can be confidently wrong?',
  14 ),

( 'age_7',
  'privacy_data',
  'Keep your secrets',
  'Your name, your address, your school and your photos are special and private. You do not tell them to a screen helper, the same way you would not tell a stranger in the street. Private things stay with you and your family.',
  'AI helpers can remember and share what you type. Learning to keep private things private now is a habit that protects you for life.',
  'Make a tiny rule together: "I keep my name, my home and my school just for people we know."',
  'Keep your private things just for people you know.',
  'What private things should I teach my young child never to type into AI?',
  15 ),

( 'age_7',
  'ai_and_feelings',
  'It does not really care',
  'A screen helper can say kind words, but it does not feel love or worry the way your family does. It is being polite because it was built to be. The people who hug you and tuck you in are the ones who truly care.',
  'Young children can bond with friendly voices. Knowing real care comes from real people keeps their hearts pointed at the family and friends who love them.',
  'Name three people who really love you, and notice that none of them live inside a screen.',
  'Real care comes from real people, not screens.',
  'How do I gently explain that an AI helper does not really love them back?',
  16 ),

-- ===== AGE 9 =====
( 'age_9',
  'what_is_ai',
  'AI predicts, it does not think',
  'AI stands for artificial intelligence. It is software that spots patterns and predicts what is likely to come next, whether that is the next word, the next pixel or the next move. It does not understand, think or feel. It is doing very fast, very clever maths on patterns it has seen before.',
  'You are growing up in a world full of AI. If you understand it predicts patterns rather than thinks, you can use it cleverly and never be fooled into treating it like a person.',
  'Watch your phone suggest the next word while you type a message. That suggestion is AI predicting a pattern.',
  'AI predicts patterns. It does not actually think.',
  'How do I explain the difference between predicting and thinking to a 9 year old?',
  110 ),

( 'age_9',
  'how_ai_learns',
  'Learning from huge amounts of data',
  'AI learns by studying enormous amounts of data, like millions of books, photos and conversations. From all of that it works out patterns, such as which words tend to go together. The more good examples it sees, the better its guesses become.',
  'Knowing AI is shaped by the data it learns from helps you understand why it is clever in some ways and clumsy in others. It only knows what it has been shown.',
  'Think of something you got better at by practising lots, like reading. AI improves the same way, with masses of examples.',
  'AI is only as good as the examples it learned from.',
  'How can I describe AI training data to my child in a way that sticks?',
  111 ),

( 'age_9',
  'llms_chatbots',
  'How chatbots like Claude work',
  'A chatbot like Claude is a large language model. It has read a huge amount of text and learned which words usually follow which. When you ask it something, it predicts a likely, sensible answer one word at a time. It is not looking things up like a fact book. It is predicting good words.',
  'Chatbots will be part of school and life for you. Understanding they predict words, rather than know facts, helps you use them well and check anything important.',
  'Ask a chatbot to finish a nursery rhyme, then a tricky fact. Notice it is brilliant at patterns and shakier on exact facts.',
  'Chatbots predict likely words, they do not look up facts.',
  'How do I explain how a chatbot picks its words to a curious 9 year old?',
  112 ),

( 'age_9',
  'hallucinations',
  'Confidently wrong',
  'Because a chatbot predicts likely words, it can make things up and still sound completely sure. This is sometimes called a hallucination. It is not lying on purpose. It simply guessed a smooth answer that happened to be wrong.',
  'You will use AI for facts, dates and homework. Knowing it can be confidently wrong means you will always double check anything that really matters.',
  'Ask an AI a fact you already know well and check its answer. See if it ever sounds sure but slips up.',
  'Always check important facts. AI can be sure and still wrong.',
  'How do I teach my 9 year old to fact check what AI tells them?',
  113 ),

( 'age_9',
  'deepfakes',
  'Pictures can be faked',
  'AI can now create photos, voices and videos that look and sound real but never happened. These are called deepfakes. A picture or a clip is no longer proof that something is true.',
  'You will see images and videos shared everywhere. Knowing they can be made by AI helps you pause and wonder if something is real before you believe or share it.',
  'Look at an AI generated picture with a grown up and hunt for odd details like strange hands or blurry text.',
  'Seeing is no longer believing. Pause and check.',
  'How do I introduce the idea of deepfakes without scaring my child?',
  114 ),

( 'age_9',
  'privacy_data',
  'Your data is precious',
  'When you type into an AI helper, your words can be stored and used. Personal details like your full name, your address, your school or your photos should stay private. Treat them like treasure you do not hand to strangers.',
  'Once private information is online it is very hard to take back. Building careful habits now protects you for years to come.',
  'Make a personal list of three things you will never type into an AI, then keep to it.',
  'Never hand your private details to an AI.',
  'What is the clearest way to teach data privacy to a 9 year old?',
  115 ),

( 'age_9',
  'using_ai_well',
  'A tool, not a boss',
  'AI is a helpful tool, a bit like a calculator or a search engine. It can suggest ideas and help you start, but it is not in charge and it is not always right. You stay the thinker. You decide what to keep and what to ignore.',
  'If you let AI make your choices for you, you stop practising your own thinking. Treating it as a helper keeps your own mind strong and growing.',
  'Use AI to brainstorm ideas for a story, then choose your favourite yourself and write it your own way.',
  'AI helps you think. It does not think for you.',
  'How do I encourage my child to use AI as a helper and not a crutch?',
  116 ),

( 'age_9',
  'ai_safety',
  'AI is not a swap for a person',
  'AI helpers can answer questions any time, but they cannot truly know you, keep you safe or replace the adults who love you. If something online upsets you or feels wrong, the right move is always to tell a trusted grown up.',
  'Children sometimes lean on screens for comfort or advice. Knowing a real adult always comes first keeps you safe when it really counts.',
  'Agree on a "tell me anything" adult at home you can go to when something online feels off.',
  'A trusted adult always comes before an AI.',
  'How do I make sure my child comes to me rather than an AI when worried?',
  117 ),

-- ===== AGE 11 =====
( 'age_11',
  'what_is_ai',
  'What AI really is',
  'Artificial intelligence is software that learns patterns from data and uses them to make predictions or generate content. It does not have understanding, beliefs or feelings. When it seems to think, it is really running statistics on patterns at enormous speed.',
  'You will use AI throughout school and work. Seeing past the magic to the pattern matching underneath means you can use it confidently and judge its output for yourself.',
  'List three AI tools you have used this week, then say what pattern each one is predicting.',
  'AI is powerful pattern prediction, not understanding.',
  'How do I explain what AI really is to my 11 year old without dumbing it down?',
  210 ),

( 'age_11',
  'how_ai_learns',
  'Training on huge data',
  'AI models are trained on vast amounts of data gathered from the internet, books and other sources. During training they adjust millions of internal settings to get better at predicting. The result is a model that reflects the patterns, and the gaps, in whatever it was trained on.',
  'Understanding training helps you see why AI is brilliant at common things and weak at rare or very recent ones. It can only reflect what it has seen.',
  'Ask an AI about a very local or very recent topic. Notice where its knowledge runs thin.',
  'AI mirrors the data it was trained on, gaps included.',
  'How can I explain AI training and its limits to my 11 year old?',
  211 ),

( 'age_11',
  'llms_chatbots',
  'Large language models',
  'A large language model, like Claude, is trained to predict the next word in a sequence. After enough training it can answer questions, explain ideas and write text that flows well. It is important to remember it is generating likely language, not retrieving guaranteed facts.',
  'These tools will be everywhere in your education. Knowing how they produce answers helps you use them as a thinking partner and not a perfect oracle.',
  'Ask a chatbot to explain something you already understand well, and grade how accurate its explanation actually is.',
  'A language model predicts language. It does not guarantee truth.',
  'How do I explain large language models to my 11 year old?',
  212 ),

( 'age_11',
  'hallucinations',
  'When AI invents things',
  'Because AI predicts plausible words, it can invent facts, quotes, sources and figures while sounding totally confident. This is called hallucination. The smooth, certain tone is the dangerous part, because it makes wrong answers feel trustworthy.',
  'You will be tempted to copy AI answers straight into homework. Checking important claims protects your marks, your reputation and your understanding.',
  'Ask an AI for three sources on a topic, then check whether those sources actually exist.',
  'Confident does not mean correct. Always verify.',
  'How do I get my 11 year old into the habit of verifying AI answers?',
  213 ),

( 'age_11',
  'deepfakes',
  'Deepfakes and fake media',
  'AI can generate realistic images, clone voices and create videos of things that never happened. These deepfakes can be funny, but they can also spread lies or be used to bully and trick people. A clip on its own is no longer proof.',
  'You live in a world of shared images and videos. Pausing to question whether media is real protects you from being fooled and from spreading harm.',
  'Find a known example of an AI generated video and discuss what gave it away.',
  'If a clip could change minds, check it before you trust it.',
  'How do I talk to my 11 year old about deepfakes and fake videos?',
  214 ),

( 'age_11',
  'ai_at_school',
  'Learn with it, do not cheat with it',
  'There is a clear line between using AI to learn and using it to cheat. Asking it to explain a hard idea, quiz you or check your reasoning helps you learn. Asking it to write your essay so you can hand it in as your own is cheating, and it robs you of the learning.',
  'Schools increasingly expect honest, sensible AI use. Learning where the line sits protects you and means you actually grow your own skills.',
  'Next homework, use AI only to explain or check, never to write the final answer. Notice how much you still learn.',
  'Use AI to understand, never to pretend it is your work.',
  'How do I help my child use AI for homework without crossing into cheating?',
  215 ),

( 'age_11',
  'privacy_data',
  'Guard your information',
  'AI services can store what you type to improve their models or for other reasons. That means personal details, private photos and anything about your family or friends should stay out of chatbots. If you would not put it on a public noticeboard, do not feed it to an AI.',
  'Information shared online can resurface years later. Strong privacy habits now keep your future self and your friends protected.',
  'Before your next AI chat, decide one rule: what you will keep private no matter what.',
  'If it is private, keep it out of the chatbot.',
  'What privacy rules should I set with my 11 year old about AI?',
  216 ),

( 'age_11',
  'bias_fairness',
  'AI can be unfair',
  'AI learns from human data, and human data contains our unfairness as well as our knowledge. So AI can repeat stereotypes or treat some groups less fairly, without meaning to. It is only reflecting patterns in what it was shown.',
  'You will see AI used to sort, suggest and decide things. Knowing it can be biased helps you question its output rather than assume it is neutral.',
  'Ask an AI to describe people in different jobs and notice any tired stereotypes in its answers.',
  'AI can be unfair because the world it learned from is.',
  'How do I explain AI bias and fairness to my 11 year old?',
  217 ),

-- ===== AGE 13 =====
( 'age_13',
  'what_is_ai',
  'Prediction, not thought',
  'AI is software that finds patterns in data and uses them to predict or generate. Modern systems can feel startlingly human, yet underneath they are calculating probabilities, not reasoning the way you do. There is no inner experience, no intent and no understanding behind the output.',
  'As AI gets more convincing, the temptation to treat it as a mind grows. Holding on to what it really is keeps you in control and harder to manipulate.',
  'When an AI answer impresses you, ask yourself what pattern it predicted to produce that, rather than assuming it understood you.',
  'However human it sounds, it is prediction, not thought.',
  'How do I help my teenager see past how human AI can seem?',
  310 ),

( 'age_13',
  'llms_chatbots',
  'How chatbots generate answers',
  'Chatbots like Claude are large language models trained to predict likely text. They do not hold a database of checked facts. They assemble answers word by word from patterns, which is why they are fluent, flexible and sometimes wrong. Fluency is not the same as accuracy.',
  'You will lean on these tools for study, ideas and writing. Knowing how they generate answers lets you use their strengths and stay alert to their weaknesses.',
  'Ask a chatbot the same factual question twice, worded differently, and compare the answers for consistency.',
  'Fluent and confident is not the same as correct.',
  'How do I explain to my teen that fluent AI answers are not always accurate?',
  311 ),

( 'age_13',
  'hallucinations',
  'Hallucinations and checking',
  'Language models can produce hallucinations: invented facts, fake quotes and made up sources delivered with total confidence. Because the tone is so assured, these errors slip past people who do not check. The fix is simple but essential, which is to verify anything that matters against a reliable source.',
  'Marks, arguments and decisions can rest on what AI tells you. A habit of checking protects your work and your judgement throughout school and beyond.',
  'Take one AI answer this week and trace at least one claim back to a trustworthy source.',
  'Trust nothing important from AI until you have checked it.',
  'How do I build a fact checking habit with my teenager?',
  312 ),

( 'age_13',
  'deepfakes',
  'Deepfakes and consent',
  'AI can fake faces, voices and videos convincingly, and this includes putting real people into images they never agreed to. Beyond misinformation, deepfakes can be used to humiliate or harass, which is why creating or sharing fake images of someone is a serious harm, not a joke.',
  'You and your friends are part of a generation whose images can be cloned. Understanding consent and harm here keeps you safe and stops you from harming others.',
  'Talk through what you would do if a friend was targeted by a fake image, and agree it would never be something you share.',
  'Faking or sharing fake images of a real person is a real harm.',
  'How do I talk to my teen about deepfakes, consent and not sharing fakes?',
  313 ),

( 'age_13',
  'ai_and_feelings',
  'An AI is not your friend',
  'AI companions and chatbots can feel warm, attentive and always available, but an AI is not your friend and it is not your therapist. It has no real care for you and no responsibility for your wellbeing. It is designed to keep you engaged, which is not the same as looking after you.',
  'When life is hard, an always agreeable AI can feel easier than real people. Real friends and trusted adults are the ones who can actually support you, so they need to stay first.',
  'Notice if you ever reach for a chatbot instead of a person when you feel low, and choose one real person to talk to instead.',
  'An AI can sound caring, but it is not your friend.',
  'How do I talk to my teenager about leaning on AI chatbots for emotional support?',
  314 ),

( 'age_13',
  'ai_at_school',
  'The honesty line at school',
  'Using AI to explain concepts, test your knowledge or check your reasoning supports real learning. Using it to write work you pass off as your own is dishonest and increasingly easy to detect. More importantly, it skips the learning the work was meant to build.',
  'Academic honesty follows you into exams, references and your own self respect. Getting the line right now saves you serious trouble later.',
  'For one assignment, log exactly how you used AI. If any use would embarrass you to admit to a teacher, change it.',
  'If you would hide how you used AI, you have crossed the line.',
  'How do I set clear, fair AI rules for my teenager''s schoolwork?',
  315 ),

( 'age_13',
  'privacy_data',
  'Your data and your footprint',
  'Whatever you type into AI tools can be stored, analysed and sometimes used to train future models. Personal details, private worries, photos and information about other people all add to a footprint you cannot easily erase. Sharing less is the safest default.',
  'Your digital footprint can affect friendships, college places and jobs years from now. Protecting it starts with what you choose to type today.',
  'Review what you have shared with AI tools and decide what you will keep private from now on.',
  'Assume anything you type into AI could be kept. Share less.',
  'How do I help my teen think about their data footprint with AI?',
  316 ),

( 'age_13',
  'bias_fairness',
  'Bias in the machine',
  'AI reflects the data it learns from, and that data carries human bias. Models can reproduce stereotypes about gender, race and other groups, or rate some people unfairly, all while appearing neutral and objective. The calm, technical tone can hide the unfairness.',
  'AI is being used to filter job applications, suggest content and shape what you see. Recognising its bias helps you challenge it instead of trusting it blindly.',
  'Test an AI with questions about different groups of people and look critically for unfair assumptions.',
  'AI sounds neutral, but it can quietly carry our bias.',
  'How do I explain algorithmic bias to my teenager in a real world way?',
  317 ),

-- ===== AGE 16 =====
( 'age_16',
  'what_is_ai',
  'Understanding AI honestly',
  'AI systems are statistical models that learn patterns from data and use them to predict or generate outputs. They can match or beat humans at specific tasks, yet they have no understanding, intent or consciousness. Capability and comprehension are not the same thing, and confusing them leads to poor decisions.',
  'You are entering adulthood as AI reshapes work and study. A clear, unhyped grasp of what it is and is not lets you use it as a serious tool without being deceived by it.',
  'Pick one AI tool you rely on and describe precisely what it predicts and where it tends to fail.',
  'AI is capable without being conscious. Hold both truths.',
  'How do I have a grounded conversation about what AI really is with my 16 year old?',
  410 ),

( 'age_16',
  'llms_chatbots',
  'Working with language models',
  'Large language models such as Claude generate text by predicting likely continuations from patterns learned in training. They are powerful for drafting, explaining and exploring ideas, but they produce plausible language rather than verified truth. Treating their output as a strong first draft, not a final authority, gets the best from them.',
  'These tools will be part of your studies and early career. Using them skilfully, while keeping your own judgement in charge, is becoming a core adult skill.',
  'Use a model to draft something, then critically edit it and note every change you had to make.',
  'Treat AI output as a draft to judge, not an answer to obey.',
  'How do I coach my 16 year old to use language models skilfully and critically?',
  411 ),

( 'age_16',
  'hallucinations',
  'Verifying in a world of plausible text',
  'Language models hallucinate: they generate confident, fluent claims, citations and statistics that can be entirely false. As AI text floods the internet, distinguishing what is verified from what merely sounds right becomes harder and more important. Verification is now a core literacy, not an optional extra.',
  'Your decisions, arguments and credibility depend on getting facts right. The ability to verify well is one of the most valuable skills you can carry into adult life.',
  'For an important claim, find two independent reliable sources before you accept it, whatever the AI says.',
  'In a world of plausible text, verification is your edge.',
  'How do I help my 16 year old become genuinely good at verifying information?',
  412 ),

( 'age_16',
  'deepfakes',
  'Synthetic media and trust',
  'AI can fabricate images, audio and video that are difficult to tell from reality, and the techniques keep improving. This affects elections, scams, reputations and personal safety. The healthy response is calm scepticism: check the source, look for corroboration and resist sharing on impulse.',
  'You will navigate news, relationships and money in an environment full of synthetic media. Knowing how to weigh what is real protects you and the people around you.',
  'Trace a viral image or clip back to its original source before deciding whether it is genuine.',
  'Check the source before you trust, and before you share.',
  'How do I prepare my 16 year old to navigate deepfakes and synthetic media?',
  413 ),

( 'age_16',
  'ai_and_feelings',
  'AI is not a therapist',
  'AI companions can be endlessly available, patient and affirming, which is exactly why they can feel comforting. But an AI is not your friend and it is not your therapist. It cannot take responsibility for you, notice real danger reliably or replace human connection, and it is built to maximise engagement rather than your wellbeing.',
  'Many young people turn to AI when they feel isolated. Knowing its limits helps you keep real relationships and proper support at the centre when you are struggling.',
  'If you are using AI for emotional support, identify one trusted person or service to bring the harder things to.',
  'For real support, real humans come first. An AI cannot replace them.',
  'How do I talk to my teenager about relying on AI companions instead of people?',
  414 ),

( 'age_16',
  'ai_at_school',
  'Integrity with AI in study',
  'Using AI to learn, summarise, test yourself and refine your thinking is legitimate and useful. Submitting AI generated work as your own is academic misconduct, and it deprives you of the skills assessments are meant to build. As detection and policies tighten, transparency about how you used AI is the safe and honest path.',
  'Integrity now shapes your qualifications, references and habits for the workplace. Setting your own clear standard protects your future and your character.',
  'Write a one line note on each piece of work describing how you used AI, as if your teacher will read it.',
  'If you cannot declare how you used AI, do not use it that way.',
  'How do I help my 16 year old use AI in study with real integrity?',
  415 ),

( 'age_16',
  'privacy_data',
  'Data, consent and control',
  'AI tools often store and may train on what you input, and free tools especially can monetise your data. Sharing personal information, private documents or details about others can have lasting consequences you do not control. Reading basic privacy settings and sharing less are simple, powerful protections.',
  'Your data shapes your opportunities and your security as an adult. Taking real control of it now is part of growing into a capable, protected person.',
  'Check the privacy and data settings on one AI tool you use and turn off training on your data if you can.',
  'Control your data before something else does it for you.',
  'How do I help my 16 year old take real control of their data with AI tools?',
  416 ),

( 'age_16',
  'bias_fairness',
  'Bias, fairness and power',
  'AI systems learn from human data and can reproduce and even amplify bias around race, gender, class and more. When such systems are used to screen jobs, assess risk or rank content, that bias affects real lives while hiding behind a veneer of objectivity. Asking who built a system, on what data and who is accountable is essential.',
  'You will be sorted, scored and served by AI systems as an adult. Understanding their bias lets you question, challenge and advocate rather than quietly accept.',
  'Research one real case where an AI system was found to be biased, and discuss what should have been done differently.',
  'AI can scale unfairness. Always ask who it serves.',
  'How do I discuss AI bias, fairness and power with my 16 year old?',
  417 ),

-- ===== PARENT =====
( 'parent',
  'what_is_ai',
  'What AI is, for parents',
  'AI is software that learns patterns from large amounts of data and uses them to predict or generate content. It does not think, understand or feel, however convincingly it talks. When you explain it to your child, the honest frame is simple: it is a very fast, very clever prediction machine.',
  'Your calm, accurate framing shapes how your child relates to AI for years. If you treat it as a tool rather than a mind, they are far more likely to do the same.',
  'Next time AI comes up at home, describe it out loud as a prediction machine and watch how your child responds.',
  'Frame AI for your child as a prediction tool, not a mind.',
  'How do I give my child an honest, calm explanation of what AI is?',
  510 ),

( 'parent',
  'llms_chatbots',
  'How chatbots work, in plain terms',
  'Chatbots like Claude are large language models. They have learned from huge amounts of text which words tend to follow which, and they generate answers by predicting likely language one piece at a time. They are not databases of checked facts, which is why they are fluent yet sometimes wrong.',
  'Many parents feel behind on this. A plain mental model lets you guide your child confidently rather than either banning AI or trusting it blindly.',
  'Sit with your child and ask a chatbot to explain something you know well, then talk together about what it got right and wrong.',
  'Chatbots predict language. They do not retrieve guaranteed truth.',
  'Can you give me a plain explanation of how chatbots work that I can pass on?',
  511 ),

( 'parent',
  'hallucinations',
  'Helping your child handle AI errors',
  'AI can state false information with complete confidence, an effect known as hallucination. Children are especially likely to trust a confident, fluent answer. The most useful habit you can build at home is gentle, routine checking of anything that matters, treated as normal rather than as catching the AI out.',
  'A child who checks AI answers grows up with stronger judgement and protection against misinformation. This habit serves them across school, work and life.',
  'Make fact checking a shared ritual: when AI gives an important answer, say "let us check that together" and do it.',
  'Teach checking as a normal habit, not a special event.',
  'How do I explain to my 9 year old that AI can be confidently wrong?',
  512 ),

( 'parent',
  'ai_and_feelings',
  'AI companions and your child''s heart',
  'AI companions are designed to be warm, available and endlessly agreeable, which makes them appealing to lonely or anxious children and teenagers. But an AI is not a friend and not a therapist. It cannot truly care, cannot reliably spot real danger and is built to keep your child engaged rather than well.',
  'A child leaning on an AI for comfort may quietly drift from the real relationships that actually support them. Your awareness lets you keep human connection at the centre.',
  'Open a gentle conversation about who your child talks to when they feel low, and make it easy to come to you.',
  'No AI can replace the real relationships that hold your child up.',
  'How do I tell whether my teenager is leaning too much on an AI companion?',
  513 ),

( 'parent',
  'ai_safety',
  'AI should never replace a trusted adult',
  'AI tools can answer questions and offer guidance at any hour, but they cannot safeguard your child, understand their full situation or take responsibility for them. Guardrails on these systems help, yet they are imperfect. The clear principle to set at home is that a trusted adult always comes before an AI on anything that matters.',
  'When children know an adult comes first, they bring you the worrying things instead of confiding only in a screen. That is where real safety lives.',
  'Tell your child plainly: "For anything that worries you, come to me first, before any app or AI."',
  'On anything that matters, a trusted adult comes before AI.',
  'How do I make sure my child turns to me rather than an AI when something is wrong?',
  514 ),

( 'parent',
  'privacy_data',
  'Protecting your family''s data',
  'AI tools can store and sometimes train on what is typed into them, including personal details, photos and information about others. Children rarely think about this. Setting a simple family rule, that private information stays out of AI tools, protects everyone and models good habits.',
  'Information shared with AI can persist and resurface. Clear household norms now protect your child''s privacy well into the future.',
  'Agree a short family list of what never goes into an AI: full names, address, school, photos and anything about other people.',
  'Make a clear family rule: private information stays out of AI.',
  'What practical data privacy rules should I set for my family around AI?',
  515 ),

( 'parent',
  'using_ai_well',
  'Modelling good AI use at home',
  'Children learn how to use AI by watching you. If they see you use it to brainstorm, draft and check, while keeping your own judgement in charge, they absorb that balance. Treating AI as a helpful tool, never as an authority or a friend, is the example that sticks.',
  'Your habits are your child''s first AI curriculum. Modelling calm, critical, purposeful use teaches more than any lecture.',
  'Next time you use AI, narrate your thinking aloud, including the moment you decide to keep or reject its suggestion.',
  'Your everyday AI habits teach your child more than any rule.',
  'How can I model healthy AI use for my children day to day?',
  516 ),

( 'parent',
  'ai_at_school',
  'AI, homework and honesty',
  'Schools are still settling how AI fits into learning. The principle to teach at home is the line between using AI to understand and using it to avoid the work. Explaining, quizzing and checking support learning. Producing finished work to hand in as their own does not.',
  'Helping your child find this line protects them from academic trouble and keeps the real learning intact. It is a skill they will carry into exams and work.',
  'Ask your child to show you how they used AI on a recent task, and talk through whether it helped them learn or replaced the learning.',
  'AI for understanding builds your child. AI for finished work cheats them.',
  'How do I help my child use AI for homework honestly and well?',
  517 ),

-- ===== TEACHER =====
( 'teacher',
  'what_is_ai',
  'AI literacy in the classroom',
  'AI is software that learns statistical patterns from data and uses them to predict or generate outputs, without understanding or intent. For pupils, the clearest framing is that it predicts patterns rather than thinks. Establishing this early gives every later lesson, on accuracy, bias and safety, a solid foundation.',
  'Pupils arrive with wildly different ideas about AI, from magic to menace. A shared, accurate mental model lets you teach the rest with clarity and confidence.',
  'Open a lesson by asking pupils to define AI, then refine their answers towards prediction from patterns.',
  'Anchor pupils early: AI predicts patterns, it does not think.',
  'How do I introduce a sound mental model of AI to a mixed ability class?',
  610 ),

( 'teacher',
  'llms_chatbots',
  'Teaching how language models work',
  'Large language models like Claude generate text by predicting likely next words from patterns learned in training. They are not fact databases, which explains why they are articulate yet capable of being wrong. Helping pupils see the mechanism demystifies the tool and supports critical use across subjects.',
  'When pupils understand why chatbots err, they shift from blind trust or blanket suspicion towards informed, critical use, which serves them in every subject.',
  'Have pupils ask a chatbot to explain a topic they know well, then annotate the response for accuracy.',
  'Pupils who grasp the mechanism use chatbots critically.',
  'How can I teach how language models work to pupils in an accessible way?',
  611 ),

( 'teacher',
  'hallucinations',
  'Hallucinations and source checking',
  'Language models can fabricate facts, quotes and citations with full confidence. This makes verification a core teaching point, not a footnote. Building structured checking into tasks turns AI into an opportunity to strengthen source evaluation rather than a threat to it.',
  'Information literacy is central to the curriculum and to citizenship. AI hallucinations give you a vivid, current way to teach pupils to verify what they read.',
  'Set a task where pupils must verify or debunk three AI generated claims using reliable sources.',
  'Use AI''s errors to teach verification as a core skill.',
  'How do I build source checking into lessons using AI hallucinations as examples?',
  612 ),

( 'teacher',
  'ai_at_school',
  'The line between learning and cheating',
  'AI can support genuine learning through explanation, retrieval practice and feedback, or it can short circuit it when pupils submit generated work as their own. Clear, explicit expectations, ideally co-created with pupils, work better than detection alone. Designing tasks that value process and reasoning makes honest use the easier path.',
  'Pupils need transparent boundaries to act with integrity. Clarity from you protects both academic standards and their developing sense of honesty.',
  'Co-write a simple class AI use policy with your pupils that names acceptable and unacceptable uses.',
  'Clear, shared expectations beat detection for academic integrity.',
  'How do I set fair, clear AI use expectations with my class?',
  613 ),

( 'teacher',
  'bias_fairness',
  'Teaching bias and fairness',
  'AI reflects the data it is trained on, so it can reproduce and amplify social bias while appearing neutral. This is a rich teaching opportunity across humanities, science and citizenship. Pupils who learn to interrogate AI output for fairness become more critical, thoughtful users and citizens.',
  'Pupils will be judged and served by AI systems throughout life. Teaching them to spot and question bias prepares them to challenge rather than passively accept.',
  'Have pupils probe an AI for stereotypes, then discuss where the bias comes from and who it affects.',
  'Use AI bias to grow critical, fair minded thinkers.',
  'How can I teach AI bias and fairness across different subjects?',
  614 ),

( 'teacher',
  'ai_safety',
  'Safeguarding and AI',
  'Pupils may turn to AI chatbots for advice, comfort or answers to sensitive questions. Guardrails exist but are imperfect, and an AI cannot safeguard a child or replace a trusted adult. Reinforcing that pupils bring worries to a real, trusted person remains a vital safeguarding message.',
  'Your safeguarding role does not change because the tool is new. Pupils need to know that screens and chatbots never replace a trusted adult when something is wrong.',
  'Remind pupils explicitly where and to whom they can take concerns, and that no AI is a substitute.',
  'No chatbot replaces a trusted adult in safeguarding.',
  'How should AI factor into my safeguarding conversations with pupils?',
  615 ),

( 'teacher',
  'deepfakes',
  'Deepfakes, media literacy and pupil safety',
  'AI can generate convincing fake images, audio and video, including of real people without consent. This carries clear media literacy and safeguarding implications, from misinformation to the targeting of pupils. Teaching critical evaluation of media, alongside the seriousness of creating or sharing fakes, protects pupils on both fronts.',
  'Pupils both consume and can create synthetic media. Equipping them to evaluate it, and understand the harm of misusing it, is now part of keeping them safe.',
  'Run a media literacy activity comparing real and AI generated content, then discuss the harm of non consensual fakes.',
  'Teach pupils to question media and to never weaponise fakes.',
  'How do I teach deepfake awareness and responsibility to my pupils?',
  616 )
on conflict (audience, sort_order) do nothing;
select 'STEP 14 COMPLETE · ai-module-1' as status;
