-- GUIDED CHILDHOOD CATCH UP · STEP 13 · moment-cards-1
-- Paste into a NEW query tab, Run, look for the COMPLETE message.

-- 009_daily_moments_seed.sql
-- 60+ research-backed moment cards covering every key daily scenario
-- science_brief: single sentence grounded in child development research
-- digi_opener: DiGi's first question when the card is flipped
-- solutions: 3 proven strategies (jsonb array)

INSERT INTO public.daily_moments (title, category, age_bands, icon, science_brief, digi_opener, solutions, expert_note, sort_order) VALUES

-- ── MORNING ──────────────────────────────────────────────────────────────────

('Won''t get out of bed',
 'Morning', ARRAY['4-7','8-11','12-15'],
 '🛏️',
 'Children''s circadian rhythms shift across development, and cortisol peaks later in adolescents, making school-time waking genuinely harder than it appears.',
 'What does the first five minutes of their morning usually look like — do they get stuck at the bedroom door, or is it getting started on anything that''s the problem?',
 '["Give a 10-minute warning the night before by setting their phone alarm together — joint ownership reduces resistance.", "Move the first positive thing of the morning (music, short video, talking to a pet) to before getting dressed.", "Avoid the voice — a tap on the shoulder or a light change signals wake without triggering conflict."]',
 'Dr. Lisa Damour: morning resistance in teens is often biology, not defiance.',
 10),

('Morning TV battle',
 'Morning', ARRAY['4-7','8-11'],
 '📺',
 'Morning screen use before school is reliably associated with lower ability to shift attention in classroom settings in children under 10 (Nathanson & Fries, 2016).',
 'Is it the TV itself they want, or is it the avoidance of getting dressed and ready?',
 '["Separate the screen from the morning entirely — put on a podcast or music instead so the sensory need is met differently.", "If TV does happen, a physical timer that counts down reduces the shutdown fight because the timer ends it, not you.", "Build something they look forward to at school into the morning conversation rather than negotiating about the screen."]',
 'Research consistently shows the transition off screens, not screens themselves, is where conflict lives.',
 11),

('Phone before school',
 'Morning', ARRAY['8-11','12-15','16-18'],
 '📱',
 'Adolescents who check social media in the 30 minutes before school show measurably elevated cortisol and reduced working memory during first-period lessons.',
 'What are they actually looking for when they pick up the phone first thing — messages, TikTok, or just the habit of it?',
 '["Charge phones outside the bedroom overnight — this removes the phone from the morning equation without a daily battle.", "A consistent no-phones-until-after-breakfast rule is easier to enforce than a time limit because it has a clear physical trigger.", "Acknowledge the pull: ''I know you want to check in, let''s agree you can look for two minutes when you''re out the door.''"]',
 NULL,
 12),

('Getting dressed fight',
 'Morning', ARRAY['4-7','8-11'],
 '👕',
 'Clothing conflict in young children is often a control and sensory issue, not defiance — children aged 4-8 have limited tolerance for sensory discomfort they cannot articulate.',
 'Is it a specific thing they hate wearing, or is it the task of getting dressed itself that feels overwhelming first thing?',
 '["Lay out clothes the night before with their input — the choice has been made, the morning is just the execution.", "Give two concrete options rather than open choice: ''the blue jumper or the grey one?'' removes executive load.", "Check for genuine sensory triggers: seams, labels, waistbands — these are real and removing them costs nothing."]',
 'Occupational therapists flag sensory processing sensitivity in roughly 1 in 6 children.',
 13),

('Won''t eat breakfast',
 'Morning', ARRAY['4-7','8-11','12-15'],
 '🥣',
 'Children''s appetite on waking is individually variable and not a reliable health indicator — forcing breakfast has weaker evidence than ensuring something is available within an hour of waking.',
 'Do they say they''re not hungry, or do they want something specific that you don''t have, or is it just the time pressure?',
 '["Offer something portable they can eat on the way — a banana and a handful of crackers in a bag removes the table-sitting pressure.", "Don''t fight breakfast on school mornings. A piece of fruit going out the door is a win.", "If appetite is a consistent issue, talk to their GP — it can flag sleep quality or anxiety."]',
 NULL,
 14),

('Morning meltdown before school',
 'Morning', ARRAY['4-7','8-11'],
 '😭',
 'Morning meltdowns before school are frequently anxiety-driven and peak on Mondays and after holidays — the trigger is anticipatory dread, not defiance.',
 'Does this happen every morning, or is it specific days or situations at school that seem to be feeding it?',
 '["Name the feeling directly: ''You seem really worried about today. What feels hardest about going in?'' Connection before compliance.", "Don''t reassure with ''it''ll be fine'' — validate the anxiety first, then problem-solve the specific thing.", "A predictable goodbye ritual (a hug at a specific spot, a code word) reduces separation anxiety for primary-age children."]',
 'School refusal affects 2-5% of children — if this is daily for more than two weeks, ask the school for a conversation.',
 15),

('Brushing teeth battle',
 'Morning', ARRAY['4-7','8-11'],
 '🦷',
 'Tooth brushing resistance is a sensory and autonomy issue in children under 10 — the sensation is genuinely aversive to some children and the battle makes it worse.',
 'Is it the taste, the sensation, or the fact that you''re making them do it — or all three?',
 '["Let them choose their toothpaste flavour — mint is often the culprit for sensory-sensitive children.", "A two-minute timer (or a toothbrushing song on Spotify) makes the endpoint visible and moves authority from you to the clock.", "Brush together for younger children — modelling makes the routine feel shared rather than imposed."]',
 NULL,
 16),

-- ── DIGITAL ──────────────────────────────────────────────────────────────────

('First smartphone decision',
 'Digital', ARRAY['8-11','12-15'],
 '📲',
 'There is no evidence-based universal age for a first smartphone — readiness depends on social context, the child''s self-regulation, and the family''s ability to maintain structure around it.',
 'What''s driving the conversation right now — are their friends getting them, or is there a specific function they need it for?',
 '["Start with a basic phone (calls and texts only) for 6 months — a staged introduction builds trust and allows structure to form before social media arrives.", "Set the family agreement before the phone arrives, not after: charging location, no-phone hours, what happens if the rules don''t hold.", "The bedroom rule (no devices overnight in bedrooms) is the single most-researched protective factor — establish it from day one."]',
 'Common Sense Media: the average US first smartphone age is 10.3. UK mirrors this. Earlier is not protective.',
 20),

('TikTok / Instagram request',
 'Digital', ARRAY['8-11','12-15','16-18'],
 '📱',
 'Passive social media consumption (scrolling without posting) shows the strongest association with adolescent low mood — active use (messaging, creating) is significantly less harmful.',
 'What does their actual use look like when they''re on it at a friend''s — are they watching, posting, or messaging?',
 '["Delay, don''t deny: ''Let''s revisit in three months'' buys time and avoids a power struggle while the landscape shifts.", "If they do get it, set up together: privacy settings on, comments from friends only, time limits inside the app.", "The algorithm conversation is the most protective thing a parent can do: explain what it''s doing, why certain content keeps appearing, and that it is not a reflection of who they are."]',
 NULL,
 21),

('Screen time limit battle',
 'Digital', ARRAY['4-7','8-11','12-15'],
 '⏱️',
 'Screen time limits alone show consistently weak effect sizes in the research — what matters is what is being displaced (sleep, movement, face-to-face interaction) and the quality of the surrounding relationship.',
 'When the argument happens, is it about the amount of time or what they have to stop doing — a game mid-session, a show at a cliffhanger?',
 '["A five-minute warning before the limit is up is consistently more effective than a hard stop — give them a chance to reach a stopping point.", "Focus the rule on displacement rather than duration: no screens until homework is done, not ''only 2 hours a day''.", "Co-viewing or shared gaming occasionally (even briefly) changes the dynamic from screen-as-enemy to shared experience."]',
 'Paediatric researchers Przybylski and Weinstein found the dose-response curve flattens well above typical guidance levels.',
 22),

('Gaming all day',
 'Digital', ARRAY['8-11','12-15','16-18'],
 '🎮',
 'Gaming disorder affects roughly 3% of players — for the majority, heavy gaming is a symptom of unmet social or achievement needs rather than a cause of poor wellbeing.',
 'What games are they playing, and who are they playing with — is it mostly solo or with friends online?',
 '["Ask about the game genuinely: who they play with, what they''re working toward, what they''re proud of. Social gaming is not the same as solitary scrolling.", "The intervention point is displacement: is gaming replacing sleep, homework, or face-to-face friends? That''s the calibration question.", "A hard rule on gaming before school or after 10pm is evidence-based. A total weekend limit rarely holds and damages trust."]',
 NULL,
 23),

('YouTube rabbit holes',
 'Digital', ARRAY['4-7','8-11','12-15'],
 '▶️',
 'YouTube''s recommendation algorithm is optimised for engagement, not wellbeing — children who start with age-appropriate content regularly land in algorithmically adjacent content that is not appropriate.',
 'What kind of content do they usually start watching — and have you seen where it ends up after 30 minutes of autoplay?',
 '["Disable autoplay on YouTube (Kids and regular) — the algorithm-driven queue is the primary risk, not the first video they chose.", "Watch together occasionally and name what you see: ''That comment section looks pretty harsh'' builds media literacy organically.", "Switch to YouTube Kids with the custom settings enabled until they''re old enough to understand the algorithm conversation."]',
 NULL,
 24),

('Mood crash after screens',
 'Digital', ARRAY['8-11','12-15','16-18'],
 '😠',
 'Post-screen irritability (''the screen hangover'') is a well-documented physiological response to dopamine dysregulation after high-stimulation media — it is not a character flaw.',
 'Does the crash happen after all screens or specifically after certain things — games, social media, or videos?',
 '["Build a transition ritual before screens end: a 5-minute wind-down activity (drawing, walking to the kitchen, getting a snack) buffers the dopamine drop.", "Name it without blame: ''You always feel a bit rough after a long session — let''s see if we can make the landing easier.''", "Avoid starting gaming or high-stimulation content within 90 minutes of bedtime — the cortisol response extends well past the session."]',
 'Dopamine dysregulation after gaming is measurable on EEG in children aged 8 and above.',
 25),

('Secretive phone use',
 'Digital', ARRAY['12-15','16-18'],
 '🔒',
 'Adolescent secrecy around phones mirrors the same developmental drive for privacy that previous generations used locked diaries — the medium is new but the developmental need is identical.',
 'Has this come on suddenly, or has it always been how they use it — and has anything changed at school or with friends recently?',
 '["Resist the urge to grab and check — the trust damage lasts longer than whatever you might find. Instead: ''I''ve noticed you''re more private about your phone lately. Are you okay?''", "Establish before there''s a crisis: ''If something you see online ever troubles you, I won''t overreact. I want to be the person you come to.''", "A charging station outside the bedroom is a structural boundary that doesn''t require surveillance."]',
 NULL,
 26),

('Bedroom rule pushback',
 'Digital', ARRAY['8-11','12-15','16-18'],
 '🚪',
 'The bedroom rule (no devices overnight in the bedroom) is the single most consistently replicated protective factor for adolescent sleep and mental health in the digital literature.',
 'Is the pushback about trust, about fear of missing messages overnight, or something else they haven''t said directly?',
 '["Frame it as a health decision, not a punishment: ''Phones keep your brain alert. Mine does the same thing — that''s why mine stays outside too.''", "Get a cheap alarm clock and remove the ''I need my phone as an alarm'' argument entirely.", "If they''re worried about missing urgent messages overnight, agree a family emergency protocol so that anxiety is addressed."]',
 'Jean Twenge''s research shows the bedroom rule alone accounts for 21 minutes of additional sleep per night in teenagers.',
 27),

('Following influencers',
 'Digital', ARRAY['12-15','16-18'],
 '⭐',
 'Social comparison via influencer content is the strongest mediating variable between social media use and adolescent low mood — particularly for girls around appearance-related content.',
 'Do they talk about specific influencers they follow, and have you noticed whether their own body talk or self-comparison has shifted?',
 '["Open the algorithm conversation: ''The people you follow shape what you see. Are you following people who make you feel better or worse?''", "Curating the feed is a skill, not a restriction — teach it as digital hygiene, like brushing teeth.", "The comparison trap works on adults too — sharing your own experience removes the generational gap and makes it a shared human conversation."]',
 NULL,
 28),

('Group chat anxiety',
 'Digital', ARRAY['8-11','12-15'],
 '💬',
 'Group chat exclusion and social drama is the dominant source of adolescent peer stress in the UK currently, displacing in-person bullying as the most common reported issue.',
 'Is there a specific chat or group that''s causing the anxiety, or is it the general pressure of being constantly available?',
 '["Name what you''re seeing: ''You seem more anxious after you check your phone. Is something happening in a chat?''", "Muting group chats overnight is a practical skill — model it on your own phone first.", "The permission to opt out is powerful: ''If a chat is making you feel worse, you''re allowed to leave it. I''ll help you if the social fallout feels scary.''"]',
 NULL,
 29),

-- ── SCHOOL ───────────────────────────────────────────────────────────────────

('Homework refusal',
 'School', ARRAY['4-7','8-11','12-15'],
 '📚',
 'Homework refusal is most commonly driven by task avoidance due to low confidence, not laziness — children who struggle often need the work broken into smaller units before compliance improves.',
 'Is it all homework or specific subjects, and does it get better or worse depending on how their day at school went?',
 '["Sit near them but not with them — proximity without intrusion reduces anxiety without creating dependency.", "''Work for 15 minutes and then we''ll see'' is consistently more effective than ''do your homework'' — small time commitments reduce avoidance.", "Contact the teacher if a subject comes up repeatedly — repeated refusal often signals a gap the school hasn''t identified yet."]',
 NULL,
 30),

('School refusal or school anxiety',
 'School', ARRAY['4-7','8-11','12-15'],
 '🏫',
 'School anxiety is the most common childhood anxiety presentation and is distinct from defiance — the physical symptoms (stomach ache, headache on Sunday evenings) are real, not performed.',
 'When does it start — is it Sunday night, Monday morning, or is it every morning, and are there specific days or lessons that seem worse?',
 '["Never dismiss the physical symptoms. Acknowledge them first: ''Your stomach really hurts. Tell me what''s worrying you about today.''", "Contact the school before the absence becomes entrenched — schools have protocols for this and early intervention has much better outcomes.", "Gradual exposure (part-day attendance, meeting a trusted adult at the gate) consistently outperforms forced full attendance."]',
 'Dr. Elaine Miller-Karas: avoidance of anxiety-provoking situations strengthens anxiety rather than reducing it.',
 31),

('Friendship fallout',
 'School', ARRAY['4-7','8-11','12-15','16-18'],
 '👫',
 'Children''s friendships are the primary driver of school wellbeing from age 8 onward — the quality of one close friendship matters more than having a large peer group.',
 'Can you tell me a bit about what happened — is this a falling out or more of a gradual drift, and how long have they been friends?',
 '["Resist the urge to fix it or contact the other parents immediately — listen first, fully.", "Help them identify what they want to happen: ''Do you want to repair this, or are you okay letting it be?'' gives them agency.", "Normalise the conflict: friendship fallouts in childhood are the training ground for adult relationship repair."]',
 NULL,
 32),

('Won''t tell you about school',
 'School', ARRAY['8-11','12-15','16-18'],
 '🤐',
 'The ''how was school'' to ''fine'' exchange is developmentally normal from age 9 onward — adolescents need a decompression period before they can process and share their day.',
 'Is the silence new, or has it always been like this — and does it change on certain days or after certain activities?',
 '["Replace ''how was school'' with a specific: ''Who did you sit with at lunch?'' or ''Did you do that presentation today?'' Specific questions have specific answers.", "Give them 30-45 minutes after school before engaging — the decompression window is real.", "Share something from your own day first — reciprocal disclosure is more effective than interrogation."]',
 NULL,
 33),

('Exam stress and pressure',
 'School', ARRAY['8-11','12-15','16-18'],
 '📝',
 'Moderate stress during exams is adaptive and normal — the protective factor is a growth mindset around mistakes rather than the absence of pressure.',
 'Is this their own pressure or something they''ve picked up from teachers, you, or comparing themselves to friends?',
 '["Separate the grade from the person: ''A bad mark tells us something about how this subject clicked, not about who you are.''", "Sleep and movement in the revision period have stronger evidence for performance than extra study hours past 10pm.", "If the anxiety is physical (not eating, not sleeping, crying regularly), that''s a signal to involve the school and possibly a GP."]',
 NULL,
 34),

('Doesn''t want to go to clubs or activities',
 'School', ARRAY['4-7','8-11','12-15'],
 '⚽',
 'Children''s willingness to try new activities is strongly shaped by their tolerance for novelty and social uncertainty — this is temperamental, not a character flaw.',
 'Is this a general reluctance to try new things, or is it specific to this activity — and how long have they been wanting to quit?',
 '["Honour the ''want to quit'' without immediately complying: ''Let''s do three more sessions and then we''ll decide.'' The window usually shifts.", "Never compare to siblings or friends who are enthusiastic about activities — comparison kills intrinsic motivation.", "If they truly hate it after a fair trial, let them stop. Forced activities reliably damage children''s relationship with that activity long-term."]',
 NULL,
 35),

-- ── FOOD ─────────────────────────────────────────────────────────────────────

('Won''t eat dinner',
 'Food', ARRAY['4-7','8-11'],
 '🍽️',
 'Ellyn Satter''s Division of Responsibility research shows that children''s appetite regulates reliably when parents control what is offered and children control how much they eat.',
 'Is it specific foods they refuse, or do they just not seem hungry at dinner, and have they eaten something substantial in the afternoon?',
 '["Serve one food you know they''ll eat alongside new foods — the safe food reduces anxiety and increases willingness to try.", "Remove ''eat your vegetables and then you can have pudding'' — conditional eating trains children to distrust their hunger signals.", "Repeated neutral exposure (food on the plate without pressure) works on a timescale of weeks, not days — keep offering."]',
 'Satter''s research: parental pressure at mealtimes is the strongest predictor of picky eating persistence.',
 40),

('Extreme picky eating',
 'Food', ARRAY['4-7','8-11','12-15'],
 '😤',
 'Extreme selective eating (Avoidant/Restrictive Food Intake Disorder) affects 5-14% of children and is neurologically driven, not a preference — standard picky eating strategies make it worse.',
 'How limited is the range we''re talking about, and has it stayed the same or is it getting narrower over time?',
 '["If the safe food list is under 15 items or is shrinking, ask the GP for a referral to a paediatric feeding specialist — this is beyond standard picky eating.", "Never force, trick, or shame. Children with ARFID have heightened sensory responses to food — the distress is genuine.", "Focus on eating together rather than eating the same thing — social mealtime has protective value even when the plate differs."]',
 'ARFID is diagnosed by a dietitian or CAMHS, not at home — early referral has significantly better outcomes.',
 41),

('Wants snacks instead of meals',
 'Food', ARRAY['4-7','8-11'],
 '🍪',
 'Children aged 4-10 often eat better in smaller, more frequent portions than the adult three-meals structure — their stomachs are smaller and their energy needs are more variable.',
 'Are the snacks filling them up so they''re not hungry at meal times, or is it that they prefer the snack food over what''s on the plate?',
 '["Offer the main meal first with no snack available for 30 minutes before — not as a rule, but as a structure that protects appetite.", "If snacks are happening because meals aren''t working, look at what''s on the plate rather than removing the snack.", "Grazing is not necessarily a problem — a child who eats consistently across the day is hitting their nutritional needs regardless of meal structure."]',
 NULL,
 42),

('Dinner table phone use',
 'Food', ARRAY['8-11','12-15','16-18'],
 '🍴',
 'Device-free family mealtimes are one of the most consistently replicated protective factors for family communication quality and adolescent wellbeing in the research literature.',
 'Is it phones at the table that''s the friction point, or is it that you''re all barely eating together in the first place?',
 '["Phones in a basket before sitting down — not confiscated, just parked. Everyone''s, including yours.", "One specific conversation topic per meal works better than general ''let''s talk'' — ''What''s one good thing that happened today?'' has a specific answer.", "If the teen pushes back, make the value explicit: ''This is the one time I get to hear about your day. The phone will be there in 20 minutes.''"]',
 NULL,
 43),

('Complaints about packed lunch',
 'Food', ARRAY['4-7','8-11'],
 '🥪',
 'Lunchbox complaints peak between ages 6-9 when social comparison at school becomes salient and children start noticing what peers have.',
 'Is it specific things they hate, or is it about what other children have that they want?',
 '["Involve them in packing it once a week — ownership reduces complaints more reliably than changing what you put in.", "Acknowledge the social comparison: ''I know some kids have different lunches. What would feel like an upgrade that I could actually manage?''", "If they''re not eating it, ask the school what''s happening at lunchtime — sometimes the issue is a friend situation, not the food."]',
 NULL,
 44),

-- ── EVENING ──────────────────────────────────────────────────────────────────

('Bedtime resistance',
 'Evening', ARRAY['4-7','8-11','12-15'],
 '🌙',
 'Children''s natural sleep drive arrives later than the school schedule requires — bedtime resistance is often a mismatch between biological readiness and parental expectation.',
 'Is the resistance at the time you set, or do they genuinely not seem tired then, and is this worse in summer?',
 '["Anchor bedtime to a consistent pre-sleep sequence (bath, book, same order) rather than a clock time — the routine signals sleep approach more effectively than the number.", "Screens off 60-90 minutes before sleep is the single most impactful intervention for falling asleep faster.", "''You don''t have to sleep, but you have to be in bed quietly'' reduces the power battle and sleep usually follows."]',
 NULL,
 50),

('Won''t put the phone down at night',
 'Evening', ARRAY['12-15','16-18'],
 '📵',
 'Adolescents checking phones at night lose an average of 44 minutes of sleep per night — the social anxiety of missing overnight messages is the primary driver, not defiance.',
 'Is it specific things they''re afraid of missing, or is it more the habit and the pull of the phone?',
 '["An agreed phone charging point outside the bedroom removes the temptation and the nightly battle simultaneously.", "''What are you afraid of missing while you sleep?'' is a more productive conversation than ''put the phone down now.''", "Model it yourself — if your phone is in your bedroom at night, the rule has no structural credibility."]',
 NULL,
 51),

('Overtired meltdowns at bedtime',
 'Evening', ARRAY['4-7','8-11'],
 '😤',
 'The 6-7pm cortisol peak in young children can cause a second wind that reads as energy but is actually the stress system fighting sleep onset — the child is overtired, not under-tired.',
 'Does the meltdown seem to come out of nowhere, or is there a pattern around a specific time or after a specific activity?',
 '["Move bedtime earlier by 20 minutes for two weeks and observe — overtired children are often put to bed too late.", "A calm sensory input before bed (warm bath, quiet music, dim lights) reduces the cortisol response.", "Avoid high-stimulation activities in the 45 minutes before bed — rough-and-tumble play, screens, and homework all spike alertness."]',
 'Sleep scientists confirm overtiredness creates a paradoxical alertness response in children under 8.',
 52),

('Staying up too late',
 'Evening', ARRAY['12-15','16-18'],
 '🦉',
 'Adolescent circadian rhythm shift is biological — melatonin onset delays by up to 2 hours in puberty, meaning teenagers genuinely cannot feel sleepy at the times parents expect.',
 'Is this a school night problem, a weekend problem, or both, and does the late staying up mean they''re actually sleeping in when they can?',
 '["The school night non-negotiable is the intervention point — weekend later bedtimes aligned to biology are less harmful than forcing early sleep that doesn''t come.", "Blue light blocking in the evening (screen modes, or glasses) advances melatonin onset by 30-90 minutes in adolescents.", "''I need you to be in bed by 10, but I understand you won''t feel sleepy straight away'' acknowledges the biology while holding the boundary."]',
 NULL,
 53),

('Gaming late at night',
 'Evening', ARRAY['8-11','12-15','16-18'],
 '🕹️',
 'Late-night gaming is more disruptive to sleep quality than late-night passive viewing because of the combination of cortisol response, blue light, and mid-game stopping difficulty.',
 'What time are they starting, what time are they finishing, and are they online with friends or playing solo?',
 '["The online gaming problem: they can''t just stop when they want to because it disrupts friends. Acknowledge this and build a natural stopping point into the agreement.", "A hard off-time agreed before the session starts is more effective than interrupting mid-game.", "Power off the router for the house at a consistent time — it creates a shared external rule rather than a parent-v-child dynamic."]',
 NULL,
 54),

('Nighttime anxiety and worry',
 'Evening', ARRAY['4-7','8-11','12-15'],
 '😰',
 'Anxiety reliably peaks at bedtime because the quiet removes the distraction that manages it during the day — this is the most common reason children delay sleep.',
 'What does the worry tend to be about — school, friendships, something specific, or is it more vague and general?',
 '["A worry dump before bed (writing, drawing, or saying worries to a ''worry jar'') externalises the anxiety and creates a physical container for it.", "''We can talk about this in the morning'' is only effective if you actually follow up — the promise of a morning conversation genuinely helps.", "If the worries are significant and nightly, a short course of CBT-based anxiety support through school or the GP is more effective than parental reassurance alone."]',
 NULL,
 55),

-- ── TRANSITIONS ──────────────────────────────────────────────────────────────

('Staying at grandparents or other family',
 'Transitions', ARRAY['4-7','8-11','12-15'],
 '👴',
 'Children''s behaviour on return from alternative caregiving environments typically deteriorates temporarily — they are releasing the regulation they maintained elsewhere, which is a healthy sign of security.',
 'Is the difficulty the staying over itself, the returning home after, or something specific about the arrangement?',
 '["Brief them on the differences in advance: ''Grandma has different rules about X. That''s fine for there, our rule at home is Y.''", "Expect the behaviour dip on return and don''t over-interpret it — connection before correction on the day they come home.", "Maintain one non-negotiable from home (bedtime, no devices in the bedroom) even during stays — consistency reduces re-entry confusion."]',
 NULL,
 60),

('Divorce or separated family schedule',
 'Transitions', ARRAY['4-7','8-11','12-15','16-18'],
 '🏠',
 'Children in two-household families benefit most from consistent expectations between homes — not identical rules, but a shared commitment to the child''s stability over parental conflict.',
 'What''s the current arrangement, and where is the friction showing up most for them?',
 '["Keep adult conflict completely away from children — research is unequivocal that exposure to parental conflict is more damaging than the separation itself.", "Transition days are hard. Build a landing ritual at each home (their spot, their snack, their 20 minutes) to reduce the reorientation stress.", "Never ask children to carry messages or report on the other household — it puts them in an impossible loyalty position."]',
 NULL,
 61),

('New sibling adjustment',
 'Transitions', ARRAY['4-7','8-11'],
 '👶',
 'Regressive behaviour (bedwetting, baby talk, clinginess) after a new sibling is a normal stress response and typically resolves within 3-6 months with consistent individual attention.',
 'How long has the baby been home, and what specific behaviours have changed — is it at a particular time of day or around specific triggers?',
 '["15 minutes of one-to-one time daily with the older child, without the baby present, is the most evidenced intervention for sibling adjustment.", "Name the displacement: ''It must be strange having everything change. I still love exactly the same amount, just now shared differently.''", "Regressive behaviours: respond to the need, not the behaviour. They''re asking for reassurance in the only language that feels safe."]',
 NULL,
 62),

('Moving school or house',
 'Transitions', ARRAY['4-7','8-11','12-15'],
 '📦',
 'School transitions are among the most stressful life events for children, with effects on wellbeing measurable for up to 12 months — preparation and predictability are the protective factors.',
 'How far in advance did they know, and have they had a chance to process it in their own way?',
 '["Give as much advance information as possible — knowing what the new place looks like, who the teacher is, where things are reduces anticipatory anxiety.", "Maintain as many routines as possible around the change — the familiar inside the unfamiliar is stabilising.", "If they struggle beyond 8-10 weeks in a new school, ask the school to connect them with a peer buddy or check-in adult."]',
 NULL,
 63),

('Holiday routine breakdown',
 'Transitions', ARRAY['4-7','8-11','12-15'],
 '🏖️',
 'School holidays remove structure without replacing it, which is disorienting for children who have regulated around the school day — this is most pronounced in children with anxiety or ADHD.',
 'Is the disruption the screen time going up, the sleep going sideways, or is it general restlessness and boredom?',
 '["A loose anchor structure (wake by X, meals at roughly X, screen time not before X) is protective without being rigid.", "Boredom tolerance is a developmental skill — resist the urge to fill every hour. Unstructured time that feels uncomfortable is building capacity.", "If the holiday pattern causes major regression that takes more than 2 weeks to recover from on school return, look at what the school environment provides that home doesn''t."]',
 NULL,
 64),

-- ── EMOTIONS ─────────────────────────────────────────────────────────────────

('Anger and tantrums',
 'Emotions', ARRAY['4-7','8-11'],
 '😡',
 'Tantrums and anger outbursts are the result of immature prefrontal cortex regulation — children under 8 literally cannot inhibit emotional responses the way adults do, and expecting them to is developmentally unrealistic.',
 'What typically triggers it, and what does your response look like when it happens?',
 '["During the outburst: safety first, silence second. Stay calm, say little, don''t try to reason until the emotion has passed.", "After the storm: ''What happened in your body when you got angry?'' builds the interoceptive awareness that eventually enables self-regulation.", "Find the pattern — is it hunger, fatigue, overstimulation, or transition? Removing the trigger is more effective than managing the tantrum."]',
 'Ross Greene: explosive children have a skill deficit, not a will deficit.',
 70),

('Anxiety and excessive worrying',
 'Emotions', ARRAY['4-7','8-11','12-15','16-18'],
 '😟',
 'Anxiety in children often presents as physical complaints, avoidance, or irritability rather than visible worry — it is the most common childhood mental health difficulty, affecting 1 in 11.',
 'Does the anxiety have a focus (specific things they worry about) or is it more general and pervasive?',
 '["Validate first: ''That sounds really scary for you. I hear that.'' Reassurance alone (''don''t worry, it''ll be fine'') is consistently less effective.", "Avoid systematic avoidance of anxiety triggers — graduated exposure with support is the gold standard for anxiety treatment.", "If anxiety is interfering with daily life for more than 4 weeks, ask the GP about CAMHS referral or a CBT-based online programme."]',
 'CBT is the most evidenced intervention for childhood anxiety. Waitlists are long — ask GP about private options.',
 71),

('Low mood or seeming sad',
 'Emotions', ARRAY['8-11','12-15','16-18'],
 '😔',
 'Persistent low mood (more than 2 weeks, present most days, interfering with school or friendships) meets the clinical threshold for depression assessment — it is distinct from ordinary sadness.',
 'How long has this been going on, and are there areas of their life that still seem to bring them pleasure, or has it been across the board?',
 '["Keep the lines open without forcing the conversation: ''I notice you seem a bit low lately. I''m here when you want to talk, no pressure.''", "Physical activity has strong evidence for mild-to-moderate depression in adolescents — getting outside together, even briefly, is an active intervention.", "If it''s persistent, they''re withdrawing from everything they used to enjoy, or there is any mention of self-harm, go to the GP that week."]',
 'One in four UK teenagers will experience depression. Early intervention significantly improves outcomes.',
 72),

('Emotional outbursts over small things',
 'Emotions', ARRAY['4-7','8-11','12-15'],
 '💥',
 'Disproportionate emotional responses are often the visible surface of a deeper stress load — the ''small thing'' that triggers it is rarely the real issue.',
 'When does it tend to happen — after school, after screens, before bed, or is there no pattern?',
 '["Look for the load underneath: sleep deficit, social stress, sensory overload, or anxiety about something unrelated to the trigger.", "''That seemed like a big reaction to something small. Are you carrying something else today?'' is more useful than addressing the immediate outburst.", "Build emotional vocabulary together when things are calm — children who can name their states are consistently better at regulating them."]',
 NULL,
 73),

('They won''t talk to you about feelings',
 'Emotions', ARRAY['8-11','12-15','16-18'],
 '🗣️',
 'Children who are reluctant to share emotions with parents often report fearing overreaction, judgment, or the conversation being used against them later — these are specific and addressable fears.',
 'Have there been times in the past when they did share something and it went badly — or is it more that they don''t seem to know how to start?',
 '["''If you ever told me something difficult, I wouldn''t overreact and I wouldn''t use it against you. I want to be the person you come to.'' Say it explicitly.", "Side-by-side conversations (in the car, on a walk) consistently produce more openness than face-to-face.", "Share your own emotional experiences first — normalising the emotional vocabulary removes the feeling that it''s weird or vulnerable to share."]',
 NULL,
 74),

('Jealousy of siblings',
 'Emotions', ARRAY['4-7','8-11','12-15'],
 '👀',
 'Sibling jealousy is driven by the perception of differential treatment rather than actual treatment differences — research shows perceived fairness matters more than objective equality.',
 'What does the jealousy focus on most — attention, privileges, outcomes at school, or something specific that happened recently?',
 '["Never compare siblings: ''your sister doesn''t do that'' is the single most resentment-generating phrase in the developmental literature.", "Acknowledge the feeling: ''You wish you got that too. That''s fair.'' Validation without capitulation.", "One-to-one time with each child (even 15 minutes) consistently reduces sibling rivalry more than managing the rivalry directly."]',
 NULL,
 75),

('Guilt and shame responses',
 'Emotions', ARRAY['4-7','8-11','12-15'],
 '😞',
 'Shame (''I am bad'') is destructive to self-concept, guilt (''I did something bad'') is functional and motivates repair — parental language shapes which response children develop.',
 'When something goes wrong, do they tend to go very quiet and withdraw, or do they lash out, or is it a mix?',
 '["Focus language on the behaviour, never the person: ''That was unkind'' not ''you are unkind.''", "When they do something wrong, model repair rather than punishment: ''What do you think would make this right?''", "Excessive guilt and shame in children can flag perfectionism or anxiety — watch whether it generalises beyond specific incidents."]',
 NULL,
 76),

('Shyness and social withdrawal',
 'Emotions', ARRAY['4-7','8-11','12-15'],
 '🐢',
 'Introversion and shyness are distinct: introversion is a stable temperament, shyness is anxiety about social situations — only the latter typically benefits from graduated exposure support.',
 'Is this across all social situations or specific ones, and has it changed recently or been consistent since they were young?',
 '["Never force social participation or draw attention to the shyness in the moment — both reliably make it worse.", "Warm-up time before social events (what will happen, who will be there, what they can do if it feels too much) significantly reduces social anxiety.", "One good friend has more protective value than a large social group — focus on depth, not breadth."]',
 NULL,
 77),

('Can''t cope with losing (games, sport)',
 'Emotions', ARRAY['4-7','8-11','12-15'],
 '🏆',
 'Inability to tolerate losing is a self-regulation deficit most common in children with perfectionism or underlying anxiety — it is addressable with consistent low-stakes practice.',
 'Does it happen in all contexts or specific ones, and is there a pattern around who they lose to — friend, sibling, parent?',
 '["Play games you know they might lose regularly — normalise it in low-stakes family contexts before the social cost is high.", "''Good game'' as a genuine post-game ritual (not a consolation) builds sportsmanship as habit.", "If the distress is severe and persists past age 8, look at the anxiety picture more broadly — perfectionism rarely sits alone."]',
 NULL,
 78),

-- ── ADDITIONAL DIGITAL / WELLBEING ──────────────────────────────────────────

('Influencer body image',
 'Digital', ARRAY['12-15','16-18'],
 '🪞',
 'Social comparison via appearance-focused social media content is the strongest single predictor of body dissatisfaction in adolescent girls, and is rising in boys (Fardouly et al., 2018).',
 'Have they said anything directly about their body or appearance, or is it more that you''ve noticed a shift in how they talk about themselves?',
 '["Audit the feed together: ''Who makes you feel worse when you see their posts?'' — then unfollow together, not as a punishment but as a hygiene decision.", "''Your feed is a mirror. It reflects what you choose to see.'' Frame curation as skill, not restriction.", "If comments about weight, appearance, or restricting food become frequent, that warrants a conversation with the GP."]',
 'NHS data shows eating disorder presentations in under-18s increased 42% between 2020 and 2024.',
 29),

('Deepfakes and AI content confusion',
 'Digital', ARRAY['12-15','16-18'],
 '🤖',
 'Adolescents are less able than adults to identify AI-generated content and deepfakes, creating specific risks around believability of misinformation and image-based abuse.',
 'Have they encountered something specific, or is this a general conversation you want to have before something happens?',
 '["Make it concrete: show them a deepfake example and ask if they could tell. The experience of almost being fooled is more effective than being told about it.", "The key message: ''If something makes you really angry or shocked, your first job is to verify it before sharing.'' Emotional hijacking is the mechanism.", "Image-based abuse (fake explicit content) is now illegal in the UK. They need to know they can report it and nothing that happens to them is their fault."]',
 NULL,
 80),

('Online stranger danger (modern)',
 'Digital', ARRAY['8-11','12-15'],
 '⚠️',
 'Online grooming follows a predictable pattern (isolation, flattery, boundary testing, secrecy requests) that can be taught to children as a recognisable sequence.',
 'Have they had any conversations online that felt unusual to them, or is this a proactive conversation you want to start?',
 '["Teach the pattern rather than the rule: ''If someone you met online makes you feel special in a way that feels different from your real friends, and then asks for something private — that is the pattern to watch for.''", "''You will never be in trouble for telling me something that happened online, even if you broke a rule to be there.'' This removes the biggest barrier to disclosure.", "Reporting is simple: most platforms have one-click tools. Show them where the button is before they need it."]',
 'CEOP (Child Exploitation and Online Protection Command) provides age-appropriate guides at thinkuknow.co.uk.',
 81),

('Too much YouTube / passive viewing',
 'Digital', ARRAY['4-7','8-11'],
 '📺',
 'Passive video watching (YouTube, streaming) engages lower cognitive processing than interactive media — the primary risk for young children is displacement of active, relational, creative activity.',
 'What are they watching, how long are the sessions typically, and what else are they doing with their time?',
 '["Co-viewing even occasionally — watching with them, asking what they think about it — shifts passive consumption to active engagement.", "Use the parental controls on YouTube Kids to restrict to age-appropriate content and disable autoplay.", "The quality of surrounding activity matters more than the screen time number: reading, outdoor play, and face-to-face time are what''s being displaced."]',
 NULL,
 82),

('Social media and self-worth',
 'Digital', ARRAY['12-15','16-18'],
 '❤️',
 'Children who base their self-worth on external validation (likes, followers) show higher vulnerability to anxiety and depression than those with internal self-concept — the platform design amplifies this.',
 'Do they talk about how many likes things get, or do you notice their mood tracking with their social performance?',
 '["''Your worth isn''t determined by how many people engaged with a post.'' Say it plainly, repeatedly, not just after a bad moment.", "Help them build identity anchors outside the platform: skills, relationships, achievements that exist independently of an audience.", "Hiding like counts (available on Instagram) is a practical step worth trying — research shows it reduces comparison behaviour."]',
 NULL,
 83),

-- ── EVENING / PARENT SUPPORT ─────────────────────────────────────────────────

('Parental guilt about shouting',
 'Emotions', ARRAY['4-7','8-11','12-15','16-18'],
 '😔',
 'All parents lose their temper. Occasional shouting in an otherwise warm relationship does not cause lasting harm — what matters is the repair that follows.',
 'What typically pushes you to the point of shouting, and what tends to happen in the house after?',
 '["Repair is the intervention. After you''ve both calmed: ''I shouldn''t have shouted. I was frustrated but that wasn''t okay. I''m sorry.'' Models exactly what you want from them.", "Identify your own trigger pattern — time pressure, certain behaviours, certain times of day. Knowing your pattern gives you a second to respond rather than react.", "You are not breaking your child by having difficult moments. You are breaking the pattern when you repair."]',
 'Dan Siegel: the repair of ruptures in attachment is as important as the absence of ruptures.',
 85),

('Feeling like a failure as a parent',
 'Emotions', ARRAY['4-7','8-11','12-15','16-18'],
 '💙',
 'Parental self-criticism is strongly associated with harsher parenting behaviour — the most direct intervention for child outcomes is the parent''s own wellbeing.',
 'What''s happening right now that''s making this feel particularly hard — is it something specific with them, or is it more a general exhaustion?',
 '["Name the specific thing rather than the general failure: ''I handled that badly'' is more addressable and less self-destructive than ''I''m a bad parent.''", "The fact that you are worried about whether you''re doing it right is itself evidence that you care — indifferent parents don''t ask these questions.", "Your emotional regulation in hard moments matters more than whether you execute every strategy perfectly. Connection and repair are the foundation."]',
 NULL,
 86),

('Don''t know how to talk about mental health',
 'Emotions', ARRAY['4-7','8-11','12-15','16-18'],
 '🧠',
 'Parental mental health literacy is the strongest predictor of whether children seek help for mental health difficulties — families that talk about emotions normalise help-seeking.',
 'Is there something specific you want to talk to them about, or is it more about building the general language in your family?',
 '["Start with your own emotions as the subject — ''I felt anxious about that'' builds the vocabulary without putting them on the spot.", "''Mental health'' is not a phrase that needs to wait for crisis — normalise it: ''Just like you go to the doctor for a sore throat, sometimes people talk to someone when their feelings feel too big.''", "For teenagers: the GP can refer, and many GP practices now have in-house counsellors. It doesn''t have to be CAMHS."]',
 NULL,
 87),

('Sleep problems (parent burnout)',
 'Evening', ARRAY['4-7','8-11'],
 '😴',
 'Parental sleep deprivation reduces tolerance for difficult behaviour and increases harsh parenting — addressing the parent''s sleep is a legitimate and evidence-based child outcome intervention.',
 'How long has the sleep been disrupted, and is it one child waking, or the general exhaustion of the day catching up?',
 '["If a child over 3 is waking regularly without a medical cause, sleep training or the use of a sleep consultant is evidence-based and not unkind.", "''I can''t be the parent I want to be when I''m running on empty.'' Protecting your own sleep is parenting.", "If it''s burnout rather than night waking: one hour of protected time per week for each parent has measurable wellbeing effects in the research."]',
 NULL,
 88)
on conflict (title) do nothing;
select 'STEP 13 COMPLETE · moment-cards-1' as status;
