insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'mood-confidence', 'I am rubbish at this', 'They give up on something hard and turn it on themselves.', 'You are not rubbish at it. You cannot do it YET. Those are really different things and the second one is just true.', 'Of course you are not rubbish, you are brilliant at everything!', 'Blanket reassurance is easy to disprove and a child knows when it is not true, which quietly makes your praise worth less. Naming the gap as a matter of time rather than of capacity is both more honest and more useful, because it points at the one thing they control, which is practice. It also stops a hard afternoon from becoming a fact about who they are.', 'Catch one yet moment today and say the word out loud. It only works if they hear it in the moment, not as a lecture.', 'If they insist they will never be able to, do not argue them out of it. Say, ''You might feel like that today. I have watched you learn hard things before.'' Then name one, specifically.', 'Two weeks later, point at something they can now do that they could not before. Concrete evidence beats encouragement every single time.', true, 3007, 'none'
where not exists (select 1 from public.scripts where title = 'I am rubbish at this');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'mood-confidence', 'They will not let you leave', 'Nursery, school or a babysitter, and the goodbye has become a scene at the door.', 'It is hard to say goodbye. I always come back. I am going now and I will see you at three.', 'Look, I will just stay five more minutes.', 'A long, guilty, drawn out goodbye tells a child there is something here worth being frightened of, because you clearly cannot bear to go either. Short, warm and certain does the opposite. The five more minutes teaches that distress extends your stay, which makes the next goodbye longer rather than shorter.', 'Say the same words every time and then go. The consistency is what builds the confidence.', 'If they cling harder, hand over to the adult who is staying and leave. Nearly every child settles within minutes of the parent being gone. Ask the staff to text you if it helps.', 'After a week, ask the teacher how long the tears last. It is usually far shorter than the parent imagines, and knowing that makes the next morning easier for you as well as them.', false, 3008, 'none'
where not exists (select 1 from public.scripts where title = 'They will not let you leave');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'everyday-routines', 'Whining that will not stop', 'The voice. It has been going for twenty minutes and you can feel yourself about to snap.', 'I want to hear you and I am finding that voice hard. Can you ask me again in your ordinary voice?', 'I cannot understand you when you talk like that.', 'Whining is usually a bid for connection made in the only register that has previously worked. It persists when it intermittently succeeds, which is the pattern hardest to shift, so consistency matters more than severity here. Naming your own difficulty rather than mocking theirs keeps it about the sound and not about them.', 'Respond to the ordinary voice quickly and warmly the moment it arrives. The reward has to be immediate to teach anything.', 'If they carry on, do not engage with the content while the whine is running. Stay friendly, stay nearby, and wait. Arguing with it counts as answering it.', 'Notice within the week whether it is dropping. If it is worse, look at what else is going on. Whining often spikes when a child is short of your attention in bigger ways.', false, 3009, 'none'
where not exists (select 1 from public.scripts where title = 'Whining that will not stop');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'everyday-routines', 'Accidents after being dry', 'They were reliably dry and now they are not, and you are washing sheets again.', 'Bodies do this sometimes. It is not naughty and I am not cross. Let us get you clean.', 'You are too old for this. You did this on purpose.', 'Regression in toileting is common and is usually about something else: a new sibling, a change at school, a house move, anything that has cost a child a sense of control. Shame reliably makes it worse, because anxiety about wetting is itself a cause of wetting. Removing the stakes is treatment, not indulgence. If it persists, or comes with pain or thirst, it is a GP visit rather than a parenting problem.', 'Handle it matter of factly, with no lecture and no audience. Then look at what changed in their world about a month ago.', 'If they are mortified, keep it brief and private. The less of an event you make it, the faster it passes.', 'If it is still happening after a few weeks, or there is any pain, blood or unusual thirst, book the GP. Some regressions are medical and no amount of patience fixes those.', false, 3010, 'none'
where not exists (select 1 from public.scripts where title = 'Accidents after being dry');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'everyday-routines', 'Getting out of the house', 'Shoes, coat, door. Every single morning is a fight and you are always late.', 'Shoes on by the time I count to ten, or I will help you. You choose.', 'Why do you do this to me every single morning?', 'Morning conflict is nearly always a demand for speed made on a child who has no sense of time. A choice with a clear boundary gives them the autonomy they are fighting for while keeping the outcome fixed. The why do you do this question invites a child to explain their character, which no child can do, and starts the day with them cast as the problem.', 'Move one thing to the night before. Bags packed, clothes out, shoes by the door. The morning is not where this gets fixed.', 'If they dawdle deliberately, follow through calmly and help them. Doing what you said you would do is the whole mechanism. Repeating the warning is what teaches them the count means nothing.', 'After a week, tell them you noticed the mornings are easier. Give them the credit even if the change was mostly your own preparation.', true, 3011, 'none'
where not exists (select 1 from public.scripts where title = 'Getting out of the house');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'family-rules', 'After you lost your temper', 'You shouted. They are quiet now and you feel sick about it.', 'I shouted and that was not okay. It was not your fault. I am working on it. I love you.', 'I am sorry I shouted, but you would not listen to me.', 'Repair is the single most useful thing in this whole library, because no parent avoids the rupture and every parent can do the repair. The word but deletes the apology and hands the blame back, which is why the version without it lands so differently. Naming it as yours also teaches a child that a person can own a mistake without falling apart, which is the exact skill you want them to have.', 'Do the repair today, before bed if you can. It does not expire, but sooner is better and shorter is better.', 'If they say it is fine, do not press them into a bigger conversation. The apology is for them to receive however they want, not a scene for you to feel better in.', 'A few days later, if you catch yourself before shouting, notice it privately. Repair works on you as well as on them.', true, 3012, 'none'
where not exists (select 1 from public.scripts where title = 'After you lost your temper');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'family-rules', 'They told a lie', 'They have said something you know is not true, about something small.', 'I think that might not be quite what happened. You are not in trouble for telling me the real version.', 'Do not lie to me! I know exactly what you did.', 'Most lying at this age is wish thinking or fear of your reaction rather than deception. Interrogation teaches a child to lie better, because it demonstrates that being caught is dangerous. Making honesty the safer option is the only thing that produces an honest child, and it costs you the satisfaction of the confrontation.', 'Give them a way back that does not require humiliation. An off ramp is not the same as letting it go.', 'If they stick to the story, do not force a confession. Say, ''Okay. If it turns out differently you can always come and tell me.'' Then leave it. Many children come back within the hour.', 'When they do tell you a hard truth, however small, say thank you for it out loud. That is the moment that builds the teenager who tells you things.', true, 3013, 'none'
where not exists (select 1 from public.scripts where title = 'They told a lie');
