insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'family-rules', 'They will not share', 'Another child wants the toy and yours is not letting go.', 'You are still using it. You can tell them, I am not finished yet. When you are done it is their turn.', 'Do not be selfish, give it to her now.', 'Forced sharing teaches that possession is decided by whoever complains loudest, and that a bigger person can take your things if they judge you have had them long enough. Turn taking based on being finished teaches the actual skill, which is noticing somebody else is waiting and choosing to stop. It looks slower and it is the version that generalises.', 'Try it once with a timer nobody controls, so it is the clock ending the turn and not you.', 'If the waiting child melts down, that is theirs to be helped with, not something the first child has to fix. Say, ''Waiting is really hard. It is nearly your turn.''', 'Watch for the first time they hand something over unprompted. Name it. That is generosity arriving on its own, which is worth far more than compliance.', false, 3014, 'none'
where not exists (select 1 from public.scripts where title = 'They will not share');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'family-rules', 'A new baby and the jealousy', 'The older one has gone backwards, or turned on the baby, since the birth.', 'You had me all to yourself and now you have to share me. That is genuinely hard. You have not lost your place.', 'You should be happy, you are a big brother now!', 'Being told to feel a feeling you do not have does not produce the feeling, it produces concealment. Naming the loss honestly is what lets a child stop defending against it. The regression and the aggression are both bids for the certainty they used to have, and they fade fastest when the certainty is restored rather than demanded.', 'Ten minutes alone with them, with the baby elsewhere, doing something they choose. Protected time beats reassurance.', 'If they say they hate the baby, do not correct it. Say, ''Right now you do. That is allowed. You are still allowed to love them later.'' Corrected feelings go underground.', 'After a few weeks of protected time, see whether the behaviour has settled. If it has, you have your answer about what it was for.', false, 3015, 'none'
where not exists (select 1 from public.scripts where title = 'A new baby and the jealousy');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'school-and-ai', 'Starting school', 'The first weeks, and they are exhausted, tearful or clinging.', 'School uses up all your energy right now. You are not doing it wrong. It gets easier and I will be here every day when you come out.', 'Did you have a good day? Who did you play with? What did you learn?', 'A child who has held themselves together for six hours has nothing left at the door, which is why the meltdown so often lands on the person they feel safest with. Three questions on the walk home is an interview they do not have the resources for. Food, quiet and presence first, conversation later or not at all.', 'Snack in the car or at the gate, no questions for the first twenty minutes. Watch what happens.', 'If they say school is horrible and they are never going back, do not solve it or panic. Say, ''That sounds like a hard day.'' Most of these pass. If it persists for weeks, talk to the teacher.', 'At half term, ask them what the best bit of school is. By then there usually is one, and hearing themselves say it matters.', true, 3016, 'none'
where not exists (select 1 from public.scripts where title = 'Starting school');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'school-and-ai', 'Reading is a battle', 'The reading book comes out and so do the tears, theirs or yours.', 'We are going to read for five minutes and then we are going to stop, whatever happens. I am not going to make you fight through it.', 'We are not stopping until you have finished the page.', 'A child who associates reading with conflict reads less, which is the one thing that reliably makes reading harder. Protecting the relationship with books is worth more over ten years than any single page. A short, guaranteed end point lowers the resistance enough that the five minutes actually happen, which is more reading than a forty minute standoff produces.', 'Set a timer for five minutes. Stop when it goes, even mid sentence, especially if it is going well.', 'If they refuse entirely, read it to them. Being read to is not cheating and it builds the same vocabulary and love of story. Decoding will come.', 'If they are still well behind after a term of this, ask school for a proper assessment. Persistent difficulty is worth investigating rather than practising harder at.', false, 3017, 'none'
where not exists (select 1 from public.scripts where title = 'Reading is a battle');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'school-and-ai', 'Nobody played with me', 'They come out of school and tell you they had nobody at playtime.', 'That sounds lonely. I am sorry today was like that. Tell me what happened.', 'Just go and ask them if you can join in! It is easy.', 'Advice arrives before comfort in most parent responses, and it lands as a correction: you had this problem because you did the wrong thing. A child who feels blamed for their own loneliness stops reporting it. Comfort first buys you the standing to problem solve later, if they even want that.', 'Listen and sympathise. Offer no strategy at all today unless they ask for one.', 'If they say nobody likes them, resist the urge to list their friends. Say, ''Today felt like that. That is a horrible feeling.'' Contradiction feels like not being heard.', 'If it is the same story for more than a week or two, speak to the teacher. Playground dynamics are visible to staff and invisible to you.', true, 3018, 'none'
where not exists (select 1 from public.scripts where title = 'Nobody played with me');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'staying-safe', 'Private parts and body rules', 'You want them to have the language and the rules before they need them.', 'These parts are private. They have proper names. No grown up should ever ask to see or touch them, and if anyone does, you tell me and you will never be in trouble.', 'We do not talk about that.', 'Correct anatomical language and an explicit never in trouble clause are both associated with children being able to disclose. Nicknames and embarrassment make a child unable to describe what happened, and the fear of being blamed is the single most common reason disclosure is delayed. This conversation is protective and it is ordinary. It should sound ordinary.', 'Say it once, calmly, in the bath or getting dressed. It should be as unremarkable as road safety.', 'If they giggle, let them. Say it anyway and move on. The giggling does not mean it did not land.', 'Repeat it every few months in passing. Once is a conversation, repeated is a rule they actually hold. The NSPCC PANTS guidance is a good script if you want a fuller version.', true, 3019, 'none'
where not exists (select 1 from public.scripts where title = 'Private parts and body rules');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'staying-safe', 'If you get lost', 'A busy shop, a park, a station, and you want them to know what to do before it happens.', 'If you cannot find me, stay exactly where you are and look for a grown up with a name badge, or another grown up with children. I will always come and find you.', 'Do not talk to strangers.', 'Do not talk to strangers is the advice most likely to leave a lost child standing silently, because the person who can help them is by definition a stranger. Naming the safe categories gives them a plan they can act on. Staying put also makes them findable, since two moving people in a crowd rarely meet.', 'Practise it once out loud next time you are somewhere busy. Point at who counts as a helper.', 'If they find it frightening, keep it short and confident. Frame it as a plan, like knowing where the fire exit is, rather than as a warning about the world.', 'Ask them a month later what the plan is. If they can tell you, it has landed.', false, 3020, 'none'
where not exists (select 1 from public.scripts where title = 'If you get lost');
