insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'mood-confidence', 'A feeling they cannot name', 'Something is clearly wrong and every question gets I do not know.', 'You do not have to know what it is. Sit with me for a bit. You do not have to talk.', 'I cannot help you if you will not tell me what is wrong.', 'I do not know is often literally true at this age. The feeling arrived without a label and being pressed for one adds the failure to answer on top of the original distress. Company without demand is the offer that works, and it is also the offer that makes them more likely to talk in ten minutes, or tomorrow.', 'Sit near them doing something else. Side by side beats face to face for this age, every time.', 'If they tell you to go away, go, but say where you will be. Say, ''I will be in the kitchen. Come and find me whenever.'' Then actually be there.', 'Later that week, if they open up about anything at all, do not make it a big moment. Underreacting is what keeps the door open.', true, 3100, 'none'
where not exists (select 1 from public.scripts where title = 'A feeling they cannot name');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'mood-confidence', 'Anxious about school', 'Sunday nights, stomach aches, and a child who does not want to go in.', 'Your tummy really does hurt. Worry does that. We are still going in, and I think you can do this.', 'There is nothing wrong with you, you are fine.', 'School related anxiety usually produces genuine physical symptoms, so telling a child nothing is wrong contradicts what their body is telling them. Believing the symptom while holding the boundary is the combination that works. Avoidance reliably makes anxiety worse over time, because the relief of not going is the thing that trains it, which is why the going in matters even when it is hard.', 'Believe the symptom out loud, then go anyway. Both halves are the treatment.', 'If it becomes a daily battle, get school involved early. A phased morning or a named adult at the gate is standard practice and schools are used to arranging it.', 'If it lasts more than a few weeks, or they are missing days, talk to the GP and the school together. Persistent school anxiety responds well to early help and badly to waiting.', true, 3101, 'none'
where not exists (select 1 from public.scripts where title = 'Anxious about school');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'mood-confidence', 'They tore up their own work', 'It was not good enough for them, so they destroyed it.', 'You wanted it to be better than it came out. That is a horrible feeling. It does not mean the work was bad.', 'Do not be ridiculous, it was really good!', 'Perfectionism is not the same as high standards. It is the belief that anything short of the picture in their head is worthless, and praise aimed at the object does not touch it because the object was never the point. Naming the gap between intention and result is what a perfectionist actually experiences, and hearing it described accurately is a relief.', 'Talk about the feeling, not the drawing. Do not rescue the paper.', 'If they refuse to try again, do not push. Say, ''You can come back to it or not. Either is fine.'' Pressure to retry confirms that the output was what mattered.', 'Model it yourself within the week. Say out loud, ''This did not come out how I wanted, and I am going to leave it as it is.'' Children copy what they see far more than what they are told.', false, 3102, 'none'
where not exists (select 1 from public.scripts where title = 'They tore up their own work');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'mood-confidence', 'Left out of the friendship group', 'The group they were part of has closed and they are on the outside.', 'That is genuinely painful and you have not done anything wrong. Friendship groups shift at your age, and it is horrible while it is happening.', 'They are not worth it, find some new friends.', 'Telling a child to find new friends dismisses the loss and skips to a solution they cannot execute. Being excluded at this age is a real social injury and it deserves to be treated as one. Naming the shifting as normal separates the pain from the conclusion that something is wrong with them, which is the thought that does the lasting damage.', 'Grieve it with them before you strategise. Today is for the feeling.', 'If they blame themselves, do not simply contradict it. Ask what they think happened, listen, and then offer your read. Being argued out of a belief entrenches it.', 'Over the next month, help them widen the field: a club, a cousin, a different set. One group being closed hurts far less when it is not the only one.', true, 3103, 'none'
where not exists (select 1 from public.scripts where title = 'Left out of the friendship group');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'mood-confidence', 'They said they hate themselves', 'It came out in the middle of an argument or a bad evening and it has frightened you.', 'That is a really heavy thing to be carrying. I want to hear about it, and I am not going to tell you off for it.', 'Do not say that! You are wonderful.', 'A fast contradiction closes the conversation, because the child learns the statement was too much for you. Staying calm and curious is what keeps it open. Most of the time this is a big sentence for a bad day, and it should still be taken seriously enough to be talked about rather than corrected.', 'Stay in it for a few minutes. Ask when they feel like that, and listen to the answer.', 'If they shut down, leave the door open explicitly. Say, ''You can tell me that any time and I will not panic.'' Keeping that promise is what makes the next disclosure possible.', 'If it comes up repeatedly, or with any talk of not wanting to be here, that is a GP appointment rather than a parenting conversation. In the UK you can also call Childline on 0800 1111 or the NSPCC helpline on 0808 800 5000 for advice.', true, 3104, 'none'
where not exists (select 1 from public.scripts where title = 'They said they hate themselves');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'family-rules', 'A lie that got bigger', 'A small untruth has grown and they are now defending it hard.', 'I think this has got bigger than you meant it to. There is a way out of this and it is telling me the whole thing now. Then it is over.', 'I am going to keep asking until you admit it.', 'A child defending a lie is usually trapped rather than defiant, and each round of questioning raises the cost of admitting it. Offering a clean exit with a stated end point makes the truth cheaper than the defence, which is the only way this resolves without a war. The over has to be real or it will not work next time.', 'Offer the exit, then keep your word about it being finished.', 'If they still hold the line, stop. Say, ''Okay. The offer stands today.'' Going again immediately just proves the exit was not real.', 'When the truth arrives, thank them for it before you deal with the thing itself. The order matters more than anything else here.', false, 3105, 'none'
where not exists (select 1 from public.scripts where title = 'A lie that got bigger');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'family-rules', 'Rudeness and answering back', 'The tone has turned and you are being spoken to in a way you will not accept.', 'I am not going to talk to you while you speak to me like that. I will be here when you are ready.', 'Do not you dare speak to me like that, who do you think you are?', 'Matching their escalation gives them a bigger fight and teaches that volume wins. Withdrawing from the exchange while staying available holds the boundary without a battle. It also gives you somewhere to go that is not a punishment you will later regret setting.', 'Leave the room rather than raising your voice. Come back when it has passed.', 'If they follow you and keep going, say the line once more and do not engage with the content. Answering any part of it restarts the exchange.', 'Once calm, do the repair from both sides. Say what was not okay, and ask what was going on underneath. Rudeness at this age is often a feeling arriving badly.', true, 3106, 'none'
where not exists (select 1 from public.scripts where title = 'Rudeness and answering back');
