insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'family-rules', 'It is not fair, they get more', 'The fairness accounting between siblings has become a full time job.', 'I do not give everybody the same. I give everybody what they need. Right now you need something different from your sister.', 'Life is not fair, get used to it.', 'Chasing exact equality is unwinnable and it teaches children to audit each other rather than to ask for what they need. Naming a different principle, needs rather than portions, gives them something they can actually use, and it lets you respond to the real request underneath, which is almost always about your attention rather than the object.', 'Ask what they actually want, not what their sibling got. The answers are usually different.', 'If they keep score, do not defend each individual decision. Say the principle again. Litigating cases confirms that the ledger is the right frame.', 'Give each of them something that is theirs alone that week, however small. Sibling fairness fights ease when each child has something not divided.', false, 3107, 'none'
where not exists (select 1 from public.scripts where title = 'It is not fair, they get more');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'everyday-routines', 'The nagging about jobs', 'You have asked four times and it still is not done.', 'I am not asking again. It needs doing before tea. I will not remind you.', 'Why do I have to ask you five times to do anything in this house?', 'Repeated reminders teach a child that your first ask is not the real one, so waiting is rational. Stating the deadline once and then not reminding transfers the responsibility to them, which is the whole point of a job. It only works if you genuinely do not remind, which is harder for the parent than for the child.', 'Say it once. Then stop. Let the consequence be the natural one.', 'If it is not done, do not rescue it or rage about it. Apply whatever you agreed beforehand, calmly, and say nothing else.', 'After a fortnight, notice out loud the first time something is done without asking. That moment is the whole return on the discomfort.', false, 3108, 'none'
where not exists (select 1 from public.scripts where title = 'The nagging about jobs');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'everyday-routines', 'They lose everything', 'Another jumper, another water bottle, another PE bag gone.', 'Things go missing at your age because your brain is busy. Let us build a system so it is not down to remembering.', 'You would lose your head if it was not screwed on.', 'Organisation is a developing skill, not a character trait, and it develops at very different rates. Character framing makes it permanent in a child''s mind and does nothing to improve it. Systems, a named place, a checklist on the door, a photograph of the packed bag, are the actual intervention.', 'Build one system together tonight. Let them design it so it is theirs to use.', 'If they resist the system as babyish, point out that adults use them constantly. Show them your own list.', 'If losses are constant and paired with other difficulties around focus and organisation, it is worth raising with school. Some children need more than a better hook by the door.', false, 3109, 'none'
where not exists (select 1 from public.scripts where title = 'They lose everything');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'school-and-ai', 'Falling behind at school', 'The report, or the teacher, has said they are behind and you are worried.', 'This tells us what you need help with. It does not tell us anything about how clever you are.', 'You are going to have to work much harder from now on.', 'A child who hears behind as a verdict on their ability disengages, because effort feels pointless against a fixed fact. Framing it as information about what to teach next keeps the door open. Work harder is also rarely the actual answer, since most children who are behind are already working as hard as they know how to.', 'Ask the school one specific question: what exactly is the gap, and what would help most at home.', 'If they say they are thick, do not simply deny it. Say, ''You are finding this bit hard. That is different.'' Then point at something they learned that was once hard.', 'Ask school for a review date rather than waiting for the next report. Six weeks of targeted help changes a great deal at this age.', true, 3110, 'none'
where not exists (select 1 from public.scripts where title = 'Falling behind at school');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'school-and-ai', 'Being bullied at school', 'It is happening in the playground or the classroom and they have finally told you.', 'Thank you for telling me. This is not your fault and it is not something you have to sort out on your own. We are going to deal with it together.', 'Just stand up to them and they will leave you alone.', 'Telling a bullied child to handle it themselves is the message they already fear, that this is theirs to fix and adults will not act. Bullying is a safeguarding matter and schools have a legal duty to have a policy on it. Thanking them for telling you also directly counters the shame that keeps most children silent for months.', 'Write down what they have told you, with dates. It is what makes the school conversation concrete rather than a general worry.', 'If they beg you not to tell school, take it seriously and do not promise silence. Say, ''I will not do anything without telling you first.'' Then involve school anyway, with them in the loop.', 'Ask school for a specific plan and a date to review it. If nothing changes, escalate in writing to the head teacher. A written record changes how these are handled.', true, 3111, 'none'
where not exists (select 1 from public.scripts where title = 'Being bullied at school');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'staying-safe', 'A grown up made them uncomfortable', 'They have told you something about an adult that has made your stomach drop.', 'I am really glad you told me. You have done nothing wrong. Tell me what happened and I am not going to be angry with you.', 'Are you sure? That does not sound like him.', 'Doubting the first account is the single most common reason a child stops talking, and once stopped it can take years to restart. Your job in this moment is to receive it, not to investigate it. Repeated questioning can also compromise a later formal interview, which is why professionals ask parents to listen and record rather than to probe.', 'Listen. Write down what they said in their words, as close to exactly as you can, with the date. Do not cross examine.', 'If they backtrack because you looked upset, stay calm and say, ''You can tell me anything and I will not be angry.'' Your face is doing more work here than your words.', 'If you have any concern that a child is at risk, contact the NSPCC helpline on 0808 800 5000, or the police on 101, or 999 if it is urgent. Your local council children''s services can also be called directly. This is not a card that ends with a script; it ends with a professional.', true, 3112, 'none'
where not exists (select 1 from public.scripts where title = 'A grown up made them uncomfortable');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'mood-confidence', 'Someone they love has died', 'A grandparent, or a pet, and you do not know what to say.', 'They died. That means their body stopped working and they will not be coming back. It is alright to be sad, and it is alright to be fine sometimes too.', 'We lost Grandad. He has gone to sleep.', 'Euphemisms confuse young children and can create new fears, since a child told somebody went to sleep may become frightened of sleeping. Plain words are kinder than they feel. Naming that grief comes and goes also prevents a child from thinking there is something wrong with them when they are happily playing an hour later, which is entirely normal at this age.', 'Use the real words. Answer the questions they actually ask, and stop there rather than explaining more than was asked.', 'If they ask whether you will die, do not promise you will not. Say, ''Most people live a very long time, and I plan to be here for a very long time.'' Honesty with reassurance beats a promise they may one day remember.', 'Expect the questions to come back in waves for months. That is normal. Winston''s Wish and Child Bereavement UK both have free guidance and helplines for families.', true, 3113, 'none'
where not exists (select 1 from public.scripts where title = 'Someone they love has died');
