insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'mood-confidence', 'Puberty and the mood swings', 'They are furious, then fine, then in tears, and none of it is about what it is about.', 'Your body is doing a lot right now and it makes feelings arrive much bigger than usual. You are not going mad and I am not going anywhere.', 'Are you hormonal? Is this that time?', 'Naming the mechanism separates the child from the mood, which is a relief to somebody who is frightened by the size of their own reactions. Teasing about hormones does the opposite: it makes every genuine feeling dismissible and teaches them not to bring you any of it.', 'Do not take the content of the outburst literally. Respond to the state, not the sentence.', 'If they insist you do not understand, agree. Say, ''You are probably right. Tell me and I will listen.'' Claiming to understand is what ends the conversation.', 'Notice out loud, once, when they handle a big feeling well. At this age they are watching for evidence that they are normal.', true, 3200, 'none'
where not exists (select 1 from public.scripts where title = 'Puberty and the mood swings');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'mood-confidence', 'They have stopped talking to you', 'Answers have become one word and the door is shut more than it is open.', 'I am around. You do not have to talk. I am going to keep offering and you can keep saying no.', 'You never tell me anything any more.', 'Withdrawal at this age is developmental rather than a verdict on you, and guilt is the least effective way to reopen a door. Persistent low pressure availability is what works: driving somewhere, cooking together, walking the dog. Side by side, with no eye contact and an easy exit, is where teenagers talk.', 'Offer one thing that involves being next to each other with something else to look at.', 'If they say leave me alone, do it, and come back tomorrow. The repeated returning is the message, not any individual conversation.', 'Count over a fortnight how many times they started a conversation. It is usually more than it feels like, and it usually rises when the pressure comes off.', true, 3201, 'none'
where not exists (select 1 from public.scripts where title = 'They have stopped talking to you');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'mood-confidence', 'Their body is changing and they hate it', 'Mirrors, baggy clothes, and comments about how they look.', 'Bodies change at really different speeds and yours is doing exactly what it should. I know it does not feel that way.', 'You look lovely, do not be daft.', 'Appearance reassurance keeps the conversation on the topic of how they look, which is the frame doing the damage. Normalising the timing addresses the actual fear, which is almost always about being different rather than about being unattractive. What you say about your own body in front of them matters more than either.', 'Say nothing about anyone''s body, including your own, for a week. Notice how often you nearly did.', 'If they fish for reassurance, give it once and briefly, then change the subject to something they did rather than something they are.', 'If eating changes, or exercise becomes rigid or secretive, take it seriously early. Beat, the UK eating disorder charity, has a helpline on 0808 801 0677 and early help matters enormously here.', false, 3202, 'none'
where not exists (select 1 from public.scripts where title = 'Their body is changing and they hate it');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'mood-confidence', 'The friendship group turned on them', 'They have been dropped, and it may be playing out at school and online at once.', 'This is one of the worst things that happens at your age. I am not going to tell you it does not matter, because it does.', 'In ten years you will not even remember their names.', 'Perspective offered too early reads as dismissal, and it is also not true to their experience: at this age the peer group is the primary social world. Sitting in it with them is what makes you somebody they will tell next time. The perspective can come later, from them, once the wound has closed.', 'Do not fix it, do not ring the other parents, unless there is bullying. Sit with them.', 'If they want to retaliate online, slow it down without lecturing. Say, ''Write it and do not send it tonight.'' Almost nothing survives the morning.', 'Within a couple of weeks, help them get one thing outside school: a club, a team, a cousin. A second social world is the real protection.', true, 3203, 'none'
where not exists (select 1 from public.scripts where title = 'The friendship group turned on them');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'family-rules', 'Telling them about a separation', 'You and their other parent are splitting up and you have to say it out loud.', 'We have decided to live apart. This is a grown up decision and it is not because of anything you did. We both love you and that is not changing.', 'We are separating because your dad has decided he does not want to be here.', 'Children at this age routinely construct a version where they caused it, so the explicit denial has to be said even though it sounds obvious. Keeping the other parent out of the firing line is the single strongest predictor in the separation literature of how well children do, and it is also the hardest thing to manage when you are hurt.', 'Tell them together if you possibly can, and answer only the questions they ask.', 'If they get angry at you, take it without defending yourself. They need somewhere safe to put it, and the safest parent usually gets it first.', 'Expect the questions to come back for months, usually about logistics rather than feelings. Answer the practical ones plainly. Relate has free guidance for families going through this.', true, 3204, 'none'
where not exists (select 1 from public.scripts where title = 'Telling them about a separation');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'family-rules', 'Someone has died', 'A grandparent, a friend, or worse, and they are old enough to understand it fully.', 'I do not have anything that makes this better. I am here and I am not going to rush you through it.', 'They would want you to be strong.', 'Being told what the dead person would want is a demand for a performance at the exact moment a child has nothing to perform with. Grief at this age often comes out as anger, or as apparent indifference, and both are normal. Company without a timetable is the whole offer.', 'Let them grieve their way, including not talking about it and including laughing.', 'If they seem completely unaffected, do not force it. Say, ''Whenever you want to talk about him, I am here.'' Delayed grief is common and pressing rarely brings it forward.', 'Winston''s Wish (08088 020 021) and Child Bereavement UK (0800 02 888 40) both support children and parents directly, and both are free.', true, 3205, 'none'
where not exists (select 1 from public.scripts where title = 'Someone has died');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'school-and-ai', 'Exam and test anxiety', 'SATs, entrance tests, or the first exams that feel like they count.', 'I care how you feel about this a lot more than I care what you get. That is true, and I will still think it when the results come.', 'Just do your best. No pressure!', 'No pressure delivered by a visibly tense parent is heard as pressure with a denial attached. Saying the thing plainly, and then behaving consistently with it when results arrive, is what makes it credible. Children calibrate to what parents do on results day far more than to what they say in the run up.', 'Ask what would make revision easier rather than telling them how to revise.', 'If they refuse to revise at all, look for avoidance rather than laziness. A child convinced they will fail often stops trying to protect themselves from proof.', 'On results day, react the way you promised you would. That is the moment the whole message is either confirmed or destroyed.', false, 3206, 'none'
where not exists (select 1 from public.scripts where title = 'Exam and test anxiety');
