insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'school-and-ai', 'A new diagnosis', 'ADHD, autism, dyslexia, or an assessment that has named something.', 'This explains some things that have been hard. It does not change who you are, and it means we can finally get you the right kind of help.', 'It is just a label, you are perfectly normal.', 'Dismissing the diagnosis to reassure them also dismisses the difficulty they have actually been living with, which many children experience as a relief to have named. Framing it as an explanation and a route to support is both accurate and useful. Explaining it as a deficit is neither.', 'Ask them what they think it means. Correct any frightening misunderstandings, and leave the rest.', 'If they are upset at being different, do not minimise it. Say, ''It is a lot to take in. You are the same person you were last week.''', 'Make sure school has it and that something concrete changes as a result. A diagnosis with no adjustments attached is a piece of paper.', false, 3207, 'none'
where not exists (select 1 from public.scripts where title = 'A new diagnosis');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'everyday-routines', 'Going out on their own', 'They want to walk into town with a friend and you are not sure.', 'I think you are ready for this. Here is the deal: I need to know where, who with, and a message when you get there.', 'Fine, but if anything happens it is on you.', 'Independence granted with clear conditions builds judgement, and independence granted with a threat attached teaches only that you are waiting for them to fail. The conditions are also the thing that lets you say yes to the next, bigger ask, because you have evidence rather than hope.', 'Agree the conditions before the first trip, not after something goes wrong.', 'If they say nobody else has to check in, hold it lightly and firmly. Say, ''This is how we build up to more.'' Framing it as a route to freedom rather than a restriction changes how it lands.', 'When they keep to it, say so and widen it slightly. Trust that visibly grows is what makes the rules worth keeping.', false, 3208, 'none'
where not exists (select 1 from public.scripts where title = 'Going out on their own');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'staying-safe', 'Vapes, alcohol and the first offers', 'It has come up, at a party or from a friend, and you want to get ahead of it.', 'You will get offered this. I would rather you knew what it does than found out at a party. And whatever happens, if you need picking up, I will come, no questions that night.', 'If I ever catch you vaping you are grounded for a month.', 'A threat makes concealment the rational choice, and the child most at risk is the one who cannot ring you. An explicit no questions tonight rescue clause is the single most protective sentence a parent of a teenager can offer, and it costs nothing to give. The conversation about what happened comes the next day.', 'Say the rescue clause out loud and mean it. Then keep it, the first time it is used.', 'If they say everyone does it, do not argue the statistic. Ask what they think about it. Their own reasoning holds better than yours.', 'If they do call, honour it completely. What you do that night decides whether they ever call again.', true, 3209, 'none'
where not exists (select 1 from public.scripts where title = 'Vapes, alcohol and the first offers');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'shaper', 'mood-confidence', 'They are self harming', 'You have seen marks, or they have told you, and you are frightened.', 'Thank you for letting me see this. I am not angry and I am not going to panic. I want to understand what it does for you.', 'Promise me you will never do this again.', 'Self harm is usually a way of managing unbearable feeling rather than an attempt to end life, and demanding a promise to stop removes the coping strategy without replacing it, which tends to drive it underground rather than away. Calm curiosity keeps the young person talking, and talking is what makes treatment possible. This card is the first ten minutes, not the answer.', 'Stay calm, keep the conversation open, and make a GP appointment. Do not make it conditional on them agreeing.', 'If they beg you not to tell anyone, do not promise secrecy. Say, ''I will not go behind your back, and I am going to get us both some help.'' Broken confidence here is worse than a difficult conversation now.', 'GP first. Childline is 0800 1111, the Samaritans are 116 123, and YoungMinds has a parents helpline on 0808 802 5544. If there is any risk to life, A and E or 999. Keep this card, and use the numbers.', true, 3300, 'none'
where not exists (select 1 from public.scripts where title = 'They are self harming');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'shaper', 'mood-confidence', 'A low mood that will not lift', 'Weeks of flatness, not days. They have stopped doing things they used to like.', 'I have noticed you have not been yourself for a while. I am not going to make you talk about it, and I am going to get you somebody to talk to.', 'You have got nothing to be depressed about.', 'Duration is the signal that matters. A bad fortnight is adolescence; six weeks of anhedonia and withdrawal is worth assessing. Telling a young person they have no reason to feel it adds guilt to depression, which is already one of its features. Acting rather than waiting is the useful parental move.', 'Name what you have observed, specifically, without a diagnosis attached.', 'If they refuse help, go to the GP yourself first and ask for advice. Parents can be seen alone and it is a normal route in.', 'If there is ever talk of not wanting to be here, treat it as urgent. Samaritans 116 123, or 999. Do not wait to see if it passes.', true, 3301, 'none'
where not exists (select 1 from public.scripts where title = 'A low mood that will not lift');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'shaper', 'mood-confidence', 'Their first break up', 'It has ended and the grief is completely out of proportion to how long it lasted.', 'This really hurts. First ones do. I am not going to tell you how long it lasted or how young you are.', 'You are fifteen, there will be hundreds more.', 'Minimising by counting the weeks tells them their feelings are wrong sized, which is the fastest way to make sure you do not hear about the next relationship. The intensity is genuine, and it is often their first experience of loss of this kind. Treat it as one.', 'Feed them, sit near them, say very little.', 'If they want to talk about it repeatedly, let them. Repetition is how the story gets processed.', 'Watch the phone for a fortnight. Break ups at this age often continue online long after they ended in person, which is what turns grief into something worse.', false, 3302, 'none'
where not exists (select 1 from public.scripts where title = 'Their first break up');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'shaper', 'mood-confidence', 'They have told you they are gay, bi or trans', 'They have said it, or half said it, and how you respond in the next thirty seconds matters enormously.', 'Thank you for telling me. I love you exactly the same as I did five minutes ago. Tell me what you need from me.', 'Are you sure? You are very young to know that.', 'Family acceptance is one of the most consistently protective factors we have for LGBT young people, and rejection one of the strongest risks. Are you sure is heard as a rejection whatever it was meant as, because it questions the one thing they have just found the courage to state. Questions can come later; the first response should be acceptance.', 'Get the first thirty seconds right. Everything else can be worked out afterwards.', 'If you are struggling privately, that is allowed, and it is not theirs to carry. Take it to another adult, not to them.', 'Ask who else knows and follow their lead on who is told. Outing them, even accidentally to family, is a serious breach. FFLAG and Stonewall both support parents directly.', true, 3303, 'none'
where not exists (select 1 from public.scripts where title = 'They have told you they are gay, bi or trans');
