insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'shaper', 'family-rules', 'They came home hours late', 'Curfew was eleven and they walked in at one, and you have spent two hours imagining the worst.', 'I am relieved you are home. I was frightened. We are going to talk about this tomorrow, not now.', 'Do you have any idea what time it is? You are grounded for a month.', 'Consequences set in the middle of fear and relief are almost always too big to enforce, and an unenforceable consequence teaches that your sanctions are theatre. Delaying the conversation to a point where you are calm produces a proportionate outcome and models exactly the emotional regulation you want from them.', 'Say those three sentences and go to bed. Do not negotiate at one in the morning.', 'If they are drunk or unwell, that is a care matter tonight and a conversation matter tomorrow. Deal with the body first.', 'Have the conversation the next day, agree what happens next time, and make it something you will actually apply.', true, 3304, 'none'
where not exists (select 1 from public.scripts where title = 'They came home hours late');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'shaper', 'family-rules', 'They want a part time job', 'They have asked, and you are weighing money and independence against school.', 'I think work is good for you. Let us look at the hours together, because school still has to come first.', 'Absolutely not, you need to concentrate on your exams.', 'A first job at this age builds competence and money sense that nothing at home replicates, and a flat refusal removes the chance to shape it. Setting the boundary at hours rather than at the principle keeps you in the negotiation and gives them a real say. In England, there are legal limits on hours for under sixteens, and it is worth checking your council''s rules.', 'Agree a maximum number of hours in writing before they accept anything.', 'If they want more hours than you agreed, tie it to how school is going rather than to your authority. It keeps the argument about evidence.', 'Review it after a month. If grades or sleep have gone, cut the hours as agreed rather than as a punishment.', false, 3305, 'none'
where not exists (select 1 from public.scripts where title = 'They want a part time job');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'independent', 'everyday-routines', 'They cannot cook, wash or manage a bill', 'They are about to leave and you realise nobody has taught them any of it.', 'I want to teach you the boring stuff before you go, because I would rather you learned it here than at midnight in a flat on your own.', 'You are going to struggle when you have to look after yourself.', 'Warning about a future failure produces anxiety without competence. Teaching produces competence. The window before leaving home is short and the list is genuinely small: five meals, a washing machine, a doctor registration, a bank app and how to challenge a bill.', 'Pick one thing and do it together this week. One a week is plenty between now and September.', 'If they say they will work it out, agree that they probably will, and do it anyway. Frame it as saving money rather than as being cared for.', 'Before they go, have them cook a whole meal and do a whole wash unaided. That is the test, not the lesson.', true, 3400, 'none'
where not exists (select 1 from public.scripts where title = 'They cannot cook, wash or manage a bill');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'independent', 'everyday-routines', 'Learning to drive', 'Lessons have started and you are quietly terrified about the first year alone.', 'The riskiest time is the first year after you pass, with friends in the car at night. That is not me not trusting you, it is what the numbers say.', 'If I ever hear you have been speeding, the car goes.', 'Young drivers are at their highest risk in the months immediately after passing, and peer passengers at night are a well documented factor. Giving the reason rather than the rule lets a young adult own the decision, which is the only enforcement that survives the moment you are not there.', 'Agree the first six months together: passengers, night driving, and the rescue clause if they have been drinking.', 'If they say their friends all drive people about straight away, do not argue about their friends. Ask what they would do if a passenger distracted them at seventy.', 'Revisit it after six months. Loosening it because they earned it works. Loosening it because you gave up does not.', false, 3401, 'none'
where not exists (select 1 from public.scripts where title = 'Learning to drive');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'independent', 'everyday-routines', 'Money of their own', 'Wages, an overdraft, or a first credit offer, and no habits yet.', 'Let me show you the two things that cause most of the trouble: paying interest, and not knowing what leaves your account each month.', 'Do not waste it all like I did at your age.', 'Regret framed as a warning teaches nothing operational. Two concrete mechanisms do. Buy now pay later and gambling adverts both target this age group hard, and naming the mechanism is more protective than naming the danger.', 'Sit down and list their monthly outgoings together, on paper. Most young adults have never seen the total.', 'If they get defensive about their spending, do not audit it. Show them yours instead. Modelling beats inspection.', 'MoneyHelper is the free government backed service and it is genuinely good. Send them the link rather than the lecture.', false, 3402, 'none'
where not exists (select 1 from public.scripts where title = 'Money of their own');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'independent', 'mood-confidence', 'They are anxious about leaving', 'University, work or moving out, and the closer it gets the worse they are.', 'Being nervous about this does not mean it is the wrong decision. You can be ready and frightened at the same time.', 'You will be fine! It is the best time of your life.', 'Cheerful certainty leaves a frightened young adult alone with the fear, and it sets a standard they then feel they are failing. Holding both, ready and frightened, is more accurate and lets them stop treating the nerves as evidence they cannot do it.', 'Ask what specifically they are dreading. It is usually smaller and more solvable than the general dread.', 'If they want to pull out entirely, slow it down rather than arguing. Say, ''Let us look at deferring rather than cancelling.'' Options reduce panic.', 'Ring them in the first fortnight rather than waiting for them to ring you. The first two weeks are the hardest and pride stops most of them calling.', true, 3403, 'none'
where not exists (select 1 from public.scripts where title = 'They are anxious about leaving');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'independent', 'mood-confidence', 'They failed something that mattered', 'Results, an audition, an application, and it has not gone their way.', 'This is genuinely disappointing and I am sorry. It closes one door. It does not tell us anything about what you are capable of.', 'Everything happens for a reason.', 'Silver linings offered on the day ask a person to skip the disappointment, and the skipped feeling tends to come back later as something harder. Naming the loss and separating it from a verdict on their ability is what lets them come back to it. The routes forward are a conversation for next week.', 'Let it be a bad day. Do not plan anything.', 'If they spiral into never being good enough, do not argue. Ask what they would say to a friend in the same position.', 'A week later, look at options together. By then it is problem solving rather than consolation, and they will be able to hear it.', false, 3404, 'none'
where not exists (select 1 from public.scripts where title = 'They failed something that mattered');
