insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'independent', 'family-rules', 'Living at home as an adult', 'They are eighteen or over, still at home, and the old rules do not fit any more.', 'The rules that worked when you were fifteen do not fit now. Let us agree what living here as an adult actually looks like.', 'My house, my rules, while you are under my roof.', 'My house my rules is true and it is also the fastest way to keep a twenty year old behaving like a fifteen year old, because it removes any adult stake in the arrangement. Renegotiating explicitly gives them responsibilities rather than restrictions, which is what actually changes the behaviour you are frustrated by.', 'Write down four things: money, meals, mess, and letting each other know where you are.', 'If they refuse to engage, do not impose it unilaterally. Say, ''I am not doing this to control you, I am doing it so we can live together.'' Then wait.', 'Review it every few months. An agreement that never changes stops being an agreement.', true, 3405, 'none'
where not exists (select 1 from public.scripts where title = 'Living at home as an adult');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'independent', 'family-rules', 'A choice you strongly disagree with', 'A course, a partner, a job, a plan you think is a mistake.', 'I think this is the wrong call and I have told you why once. It is your decision and I am not going to withdraw from you over it.', 'Do not come running to me when it goes wrong.', 'Said once and then held is the version that preserves the relationship and leaves the door open for them to come back. Repeating it converts you into an opponent and makes changing course an admission of defeat, which is the thing most likely to keep them in a bad decision.', 'Say it once, properly, and then stop saying it.', 'If they push for approval you cannot give, be honest without repeating the argument. Say, ''I am not going to pretend to agree, and I am still here.''', 'If it does go wrong, do not say you were right. Not saying it is what makes you the person they ring.', true, 3406, 'none'
where not exists (select 1 from public.scripts where title = 'A choice you strongly disagree with');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'independent', 'staying-safe', 'Consent, in relationships, properly', 'They are old enough for this to be a real conversation about their own relationships.', 'Consent is not just a no. It is somebody actively wanting to, every time, and being free to change their mind at any point without it costing them anything.', 'No means no, that is all you need to know.', 'No means no describes the floor and leaves out everything above it, including pressure, drink, and the difference between compliance and enthusiasm. Framing it as an active yes that can be withdrawn is both the legal position and the useful one, and it is a conversation to have with sons and daughters equally.', 'Have it once, plainly, without linking it to anything they have done.', 'If they are mortified, keep it short and say it anyway. Awkward and said beats comfortable and unsaid.', 'Come back to it once more in a different context, for instance about a storyline or a news story. Twice makes it a value rather than a lecture.', true, 3407, 'none'
where not exists (select 1 from public.scripts where title = 'Consent, in relationships, properly');
insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'independent', 'school-and-ai', 'University, or not', 'The decision is live and your hopes and theirs may not match.', 'I will back you either way. Let us look at what each route actually costs and leads to, rather than which one sounds better.', 'You will regret it for the rest of your life if you do not go.', 'A decision made to satisfy a parent is the one most likely to be abandoned in the first year. Backing either route removes the need to rebel against the preferred one, and comparing real costs and outcomes gives them something to reason with rather than a verdict to accept.', 'Look at apprenticeships and degrees side by side, with actual numbers.', 'If they choose the one you did not want, say you will back them and then behave like it. Visible disappointment does the damage, not the words.', 'Whatever they choose, check in properly at the three month mark. Both routes have a wobble, and both are survivable.', false, 3408, 'none'
where not exists (select 1 from public.scripts where title = 'University, or not');
