# Verdicts for the coverage matrix. Each entry is
#   (requirement_id, strand_key, item_no, coverage, modules, evidence, gap)
# strand_key indexes rshe/requirements.json so the requirement text is
# taken verbatim from the statutory guidance rather than retyped.

V = [
 # ---- PRIMARY Relationships education: Online safety and awareness
 ("RSHE-P-OSA-1", ("primary","Online safety and awareness"), 1, "PARTIAL",
  "ks1-02-kind-screens-calm-bodies; ks2-07-privacy-reputation; ks2-08-kind-safe-online",
  "ks1-02 s9 teaches 'On screens we use the same kind words we use in the classroom. Screen words are still real words and they can still hurt.' ks2-07 s12 runs a group chat scenario that applies direct pressure to send a photo ('nearly everyone has done it, just waiting on YOU'). ks2-08 teaches bystander behaviour in a pile on.",
  "Anonymity is never named. The guidance requires pupils to know the same principles apply 'including where people are anonymous'. The word anonymous does not appear in any primary module."),
 ("RSHE-P-OSA-2", ("primary","Online safety and awareness"), 2, "PARTIAL",
  "ks1-03-real-pretend-computer; ks2-07-privacy-reputation; ks2-08-kind-safe-online",
  "ks1-03 teaches sorting pictures into real, pretend and computer made, with a detective question said aloud before believing a picture. ks2-07 s12 shows a group chat with '2 you have never met'. ks2-08 teaches recognising harmful contact and the three moves ending in tell someone who can help.",
  "The specific worked example in the guidance, that adults sometimes pretend to be children online and that this can lead to dangerous situations, is not taught anywhere at primary."),
 ("RSHE-P-OSA-3", ("primary","Online safety and awareness"), 3, "NONE",
  "",
  "No evidence found. A word boundary search of all 732 production slides for 'age restrict', 'age rating', 'age limit', 'age verif', 'minimum age', 'thirteen', 'aged 13' and 'age of 13' returns zero hits in EYFS, KS1 and KS2.",
  "The minimum age of 13 for social media, and why it protects children, is not taught at primary at all. This is a named statutory requirement with a specific figure in it."),
 ("RSHE-P-OSA-4", ("primary","Online safety and awareness"), 4, "PARTIAL",
  "ks2-07-privacy-reputation",
  "ks2-07 is a full module on the judgement: the private list, the share test, three questions including 'does it give away where I am?', and 'Privacy is not hiding everything, it is choosing.' s16 teaches that location leaks hide in the corners of photos (uniform, street signs, school name).",
  "The second sentence of the requirement, privacy and location settings, is not taught. A search for 'privacy setting', 'location setting', 'turn off location' or 'change the setting' returns zero hits across EYFS, KS1 and KS2."),
 ("RSHE-P-OSA-5", ("primary","Online safety and awareness"), 5, "FULL",
  "ks2-07-privacy-reputation",
  "ks2-07 s11 'The internet remembers', s13 'The journey of one shared photo', s15 'Your footprint grows either way', and a prove phase that tests the judgement on real cases.",
  ""),
 ("RSHE-P-OSA-6", ("primary","Online safety and awareness"), 6, "FULL",
  "eyfs-01-screens-kindness; ks1-02-kind-screens-calm-bodies; ks2-08-kind-safe-online",
  "eyfs-01 teaches 'Ask a grown up: is this real?' and has every child name a trusted grown up at home and at school. ks1-02 teaches 'feel it, name it, tell a grown up' with the line 'You are never in trouble for telling.' ks2-08 move three is tell someone who can help.",
  ""),

 # ---- PRIMARY Health and wellbeing: Wellbeing online
 ("RSHE-P-WO-1", ("primary","Wellbeing online"), 1, "PARTIAL",
  "eyfs-01-screens-kindness; ks2-04-screen-routines",
  "The positive pathway register runs through every module: screens are treated as ordinary and the lessons teach judgement rather than prohibition.",
  "Not taught as an explicit objective. No primary slide asks pupils to weigh the positive and negative aspects of the internet as such."),
 ("RSHE-P-WO-2", ("primary","Wellbeing online"), 2, "INDIRECT",
  "ks2-23-when-a-machine-talks-like-a-friend",
  "ks2-23 teaches that a machine that talks like a friend is not a friend, which is adjacent to the requirement.",
  "The requirement is about human online relationships versus in person ones, and why online is unlikely to be a good substitute. That comparison is not taught at primary. A search for 'in person', 'face to face', 'real life friend' and 'substitute' returns one hit, and it is about a pile on, not about substitution."),
 ("RSHE-P-WO-3", ("primary","Wellbeing online"), 3, "FULL",
  "ks1-02-kind-screens-calm-bodies; ks2-04-screen-routines",
  "ks1-02 objective is 'Notice what my body is telling me after screen time' and teaches feeling words for wiggly, grumpy and tired. ks2-04 is a full module on routines, with the four moments (after school, bedtime, mealtimes, homework) named on the slide.",
  ""),
 ("RSHE-P-WO-4", ("primary","Wellbeing online"), 4, "FULL",
  "ks1-02-kind-screens-calm-bodies; ks2-08-kind-safe-online",
  "ks1-02 s9 'WE never send messages like this.' ks2-08 s11 teaches the gap 'between how it feels to send and how it feels to receive'.",
  ""),
 ("RSHE-P-WO-5", ("primary","Wellbeing online"), 5, "NONE",
  "",
  "No evidence found. Zero hits across all 732 slides for 'age restrict', 'age rating', 'age limit', 'age verif' or 'PEGI'.",
  "Why social media, apps, games and gambling sites are age restricted is not taught anywhere in the scheme, at any key stage."),
 ("RSHE-P-WO-6", ("primary","Wellbeing online"), 6, "FULL",
  "ks2-05-gaming-time-spend",
  "ks2-05 teaches loot boxes directly, including s19 'Paying money for a random chance is how gambling machines work, which is why some countries have banned loot boxes for children', the countdown chest scenario with fake scarcity, and a spend spotters sort with the verdicts Fine to enjoy, Ask first, Walk away. Its statutory hook is Citizenship financial literacy (fraud and scam prevention).",
  ""),
 ("RSHE-P-WO-7", ("primary","Wellbeing online"), 7, "FULL",
  "eyfs-01-screens-kindness; ks1-03-real-pretend-computer; ks2-06-how-algorithms-work",
  "eyfs-01 teaches Look and Ask, with the feedback line 'It is on the screen, but that does not make it real.' ks1-03 is a picture detectives module. ks2-06 teaches what the recipe is watching.",
  ""),
 ("RSHE-P-WO-8", ("primary","Wellbeing online"), 8, "FULL",
  "ks2-08-kind-safe-online",
  "ks2-08 carries 12 slides using the words bully, harass, abuse or pile on. Objectives include telling the difference between one unkind moment and real bullying, spotting a pile on forming, and the three moves.",
  ""),
 ("RSHE-P-WO-9", ("primary","Wellbeing online"), 9, "PARTIAL",
  "ks2-06-how-algorithms-work",
  "ks2-06 teaches how information is selected and targeted: an algorithm is a recipe, what the app is really watching, and why the feed shows what it shows.",
  "Search engines are not taught. A search for 'search engine', 'search result' or 'Google' returns one hit in the whole scheme and it is at KS5, about being searchable by an employer."),
 ("RSHE-P-WO-10", ("primary","Wellbeing online"), 10, "PARTIAL",
  "ks2-07-privacy-reputation; ks2-09-copyright-ownership",
  "ks2-07 teaches privacy as choosing. ks2-09 teaches ownership, permission and credit.",
  "Rights in relation to personal data are not taught as rights at primary. The lessons teach a judgement, not an entitlement."),
 ("RSHE-P-WO-11", ("primary","Wellbeing online"), 11, "PARTIAL",
  "eyfs-01-screens-kindness; ks1-02-kind-screens-calm-bodies; ks2-08-kind-safe-online",
  "The trusted adult route is taught thoroughly and repeatedly from Reception, including that the child is never in trouble for telling.",
  "The in platform route is absent: no primary lesson teaches how to use a report or block control, which is the 'how' half of the requirement."),

 # ---- SECONDARY RSE: Online safety and awareness
 ("RSHE-S-OSA-1", ("secondary","Online safety and awareness"), 1, "PARTIAL",
  "ks4-16-consent-images-law",
  "ks4-16 s7 makes the link explicitly for images: 'with images the same rules apply, except the stakes are far higher because a shared image can be copied.' The general principle is taught at KS1 and KS2.",
  "Only one secondary slide states the principle, and only about images. Rights and responsibilities online are not taught as a topic at secondary."),
 ("RSHE-S-OSA-2", ("secondary","Online safety and awareness"), 2, "PARTIAL",
  "ks3-11-social-workarounds; ks4-19-readiness-at-16",
  "ks3-11 s23 teaches that the real age keeps every wired protection on and the privacy setting adds another on top, and that settings can work for you. ks4-19 s19 teaches choosing defaults on day one: notifications off, private account first, a time cap chosen in advance.",
  "The difference between public and private online spaces, which the requirement names, is not taught. Caution about sharing personal information is taught at KS2 and not revisited at secondary."),
 ("RSHE-S-OSA-3", ("secondary","Online safety and awareness"), 3, "PARTIAL",
  "ks3-14-bodies-image-pressure; ks4-15-manipulation-persuasion; ks4-17-sextortion; ks3-12-misinfo-deepfakes",
  "ks3-14 teaches idealised and edited images. ks4-15 teaches parasocial pull and why an influencer feels like a friend. ks4-17 teaches accounts that exist to run a script. ks3-12 teaches AI generated content.",
  "Two named elements are missing: that some social media accounts are fake, taught as a characteristic of the medium, and that users say things in more extreme ways online than face to face."),
 ("RSHE-S-OSA-4", ("secondary","Online safety and awareness"), 4, "FULL",
  "ks4-16-consent-images-law",
  "ks4-16 is a 32 slide module on images and the law, with 38 slides across the scheme matching 'a crime', 'illegal', 'the law' or 'under 18'. Objectives include stating what UK law says about images of anyone under 18, including images of yourself.",
  ""),
 ("RSHE-S-OSA-5", ("secondary","Online safety and awareness"), 5, "PARTIAL",
  "ks4-16-consent-images-law",
  "ks4-16 teaches that the law applies to any image of a person under 18, teaches Report Remove, and teaches that a pupil will not be in trouble for asking for help.",
  "Two clauses the July 2025 guidance adds are CONFIRMED ABSENT by query: that the offence applies to imagery created using AI, and that sharing indecent images of people over 18 without consent is also a crime. A search for an AI generated image linked to a crime or the law returns zero hits, and a search for over 18 with consent returns zero hits. KCSIE 2026 names the same point twice (para 165 conduct, explicit images including those generated using AI; and the definitions section on deepfakes and deep nudes), so this is the cheapest high value addition in the scheme: two slides inside a module that already teaches the law well."),
 ("RSHE-S-OSA-6", ("secondary","Online safety and awareness"), 6, "FULL",
  "ks4-16-consent-images-law",
  "18 slides teach the reporting route by name: Report Remove, run by Childline and the Internet Watch Foundation, described as free, confidential and available to anyone under 18.",
  ""),
 ("RSHE-S-OSA-7", ("secondary","Online safety and awareness"), 7, "FULL",
  "ks3-12-misinfo-deepfakes",
  "ks3-12 is the 33 slide pilot module. It defines deepfake, teaches identification, and carries a sourced detection statistic (iProov deepfake detection study, 2025).",
  ""),
 ("RSHE-S-OSA-8", ("secondary","Online safety and awareness"), 8, "PARTIAL",
  "ks4-18-radicalisation-misogyny",
  "ks4-18 teaches the pipeline that carries misogynistic content, including isolate, flatter, escalate, and how to run a check on anything in a feed.",
  "Content that encourages violence or the use of weapons is not taught: a word boundary search for knife, weapon or violent content returns zero secondary hits. Where to go for advice about something seen online is not taught at secondary."),
 ("RSHE-S-OSA-9", ("secondary","Online safety and awareness"), 9, "INDIRECT",
  "ks4-17-sextortion; ks4-18-radicalisation-misogyny",
  "Escalation is taught, but as a stage in a criminal or radicalisation script rather than as conflict between peers.",
  "The requirement is about social media escalating conflicts and how to avoid them. That is taught at KS2 in ks2-08 (the pile on) and not carried into secondary."),
 ("RSHE-S-OSA-10", ("secondary","Online safety and awareness"), 10, "NONE",
  "",
  "No evidence found. A word boundary search of all secondary slides for bully, harass, abuse, stalk, coercive or controlling returns zero hits.",
  "Technology used in bullying, harassment, stalking, coercive and controlling behaviour is taught nowhere at KS3 to KS5. The scheme teaches this at KS2 and stops."),
 ("RSHE-S-OSA-11", ("secondary","Online safety and awareness"), 11, "PARTIAL",
  "ks3-14-bodies-image-pressure",
  "ks3-14 names it calmly: 'One more kind of made content needs naming, calmly and briefly: pornography.' It teaches that made content including pornography is not a guide to real bodies or real relationships, that seeing it is not unusual and not a punishable thing, and carries a sourced figure on average age of first exposure.",
  "The requirement's second half, that pornography can negatively affect how people behave towards sexual partners and can portray misogynistic behaviours, is not taught. Four slides in the whole scheme mention pornography, all in one KS3 module."),
 ("RSHE-S-OSA-12", ("secondary","Online safety and awareness"), 12, "PARTIAL",
  "ks5-20-ai-mastery-data-rights; ks3-10-mood-and-screens",
  "ks5-20 defines profiling as building a picture of who you are from your data, usually to predict and shape what you buy, watch and believe. ks3-10 uses 'your feed, your data' as its close.",
  "How data is generated, collected and shared is not taught as a mechanism at KS3 or KS4. Cookies, the example the DfE guidance uses, appear nowhere in the scheme."),
 ("RSHE-S-OSA-13", ("secondary","Online safety and awareness"), 13, "PARTIAL",
  "ks4-15-manipulation-persuasion; ks4-19-readiness-at-16",
  "ks4-15 teaches the attention business model and who profits from a feeling.",
  "One slide in the scheme matches 'advertisers', 'sold to' or 'sells your'. That websites share personal data with third parties for commercial purposes is asserted rather than taught."),
 ("RSHE-S-OSA-14", ("secondary","Online safety and awareness"), 14, "FULL",
  "ks3-13-scams-fraud-money; ks4-17-sextortion",
  "ks3-13 is a 31 slide module on scams and fraud, teaching that 'Pretending to be someone else to take money or an account is fraud, and fraud is a criminal offence rather than bad luck.' ks4-17 is a 30 slide module on sextortion, teaching the opener, the escalation, the threat with a countdown, and three lifelines.",
  ""),
 ("RSHE-S-OSA-15", ("secondary","Online safety and awareness"), 15, "FULL",
  "ks3-22-when-an-ai-acts-like-a-friend; ks5-20-ai-mastery-data-rights; ks3-24-is-it-doing-my-thinking",
  "ks3-22 is a 31 slide module on AI companionship. ks5-20 teaches the difference between a chatbot and an agent: 'With a chatbot you ask, is this answer right? With an agent you must ask, what is it allowed to do without me.' ks3-24 teaches offloading and cognitive cost.",
  ""),

 # ---- SECONDARY Health and wellbeing: Wellbeing online
 ("RSHE-S-WO-1", ("secondary","Wellbeing online"), 1, "FULL",
  "ks3-10-mood-and-screens",
  "ks3-10 teaches the mood audit (better, worse or nothing) and the research position honestly: the link between raw hours and wellbeing is real but tiny, and what matters is what the time is made of.",
  ""),
 ("RSHE-S-WO-2", ("secondary","Wellbeing online"), 2, "PARTIAL",
  "ks3-10-mood-and-screens; ks3-14-bodies-image-pressure",
  "ks3-10 defines comparing as 'Measuring your real, unedited life against someone else's chosen highlights' and sets it against connecting. ks3-14 covers body image and edited content.",
  "Over reliance on relationships formed through social media is not taught. ks3-22 covers over reliance on an AI, which is a different thing."),
 ("RSHE-S-WO-3", ("secondary","Wellbeing online"), 3, "NONE",
  "",
  "No evidence found. Zero secondary hits for bully, harass or abuse on a word boundary search.",
  "Identifying harmful behaviours online and how to report them or find support is not taught at KS3 to KS5."),
 ("RSHE-S-WO-4", ("secondary","Wellbeing online"), 4, "NONE",
  "",
  "No evidence found. Zero secondary hits for gambl, loot box, lootbox or debt. The only gambling teaching in the scheme is one KS2 slide.",
  "Online gambling, gambling like content within gaming, and the accumulation of debt are not taught at secondary. The Hub currently lists online gambling as a covered topic."),
 ("RSHE-S-WO-5", ("secondary","Wellbeing online"), 5, "PARTIAL",
  "ks3-12-misinfo-deepfakes; ks4-15-manipulation-persuasion",
  "ks3-12 teaches misinformation and disinformation with distinct definitions. ks4-15 teaches targeting and the persuasion industry.",
  "Conspiracy theories are not taught. The word appears twice in the scheme and both uses are figures of speech ('follow the evidence, not the conspiracy'; 'this is not a conspiracy, it is a business model'). Neither is in a module the Hub names for it."),
 ("RSHE-S-WO-6", ("secondary","Wellbeing online"), 6, "NONE",
  "",
  "No evidence found. Zero hits anywhere for knife, county lines, illicit or drug supply.",
  "The risks of illegal behaviours online, including drug and knife supply, are not taught at any key stage."),
 ("RSHE-S-WO-7", ("secondary","Wellbeing online"), 7, "NONE",
  "",
  "No evidence found. Zero hits anywhere in 732 slides for self harm or suicide.",
  "Content promoting self harm, suicide or violence is not taught, nor is how to report it or get support after seeing it. The schools pricing page currently tells buyers that scripts mean a teacher is 'not improvising about consent or self harm at nine on a Monday'."),

 # ---- Digital relevant items inside other statutory strands
 ("RSHE-P-RKR-9", ("primary","Respectful, kind relationships"), 9, "FULL",
  "ks2-08-kind-safe-online",
  "ks2-08 teaches the difference between one unkind moment and real bullying, the bystander's position in a pile on, and the three moves ending in telling an adult.",
  ""),
 ("RSHE-P-BS-2", ("primary","Being Safe"), 2, "FULL",
  "ks1-02-kind-screens-calm-bodies; ks2-07-privacy-reputation",
  "ks1-02 teaches that telling a grown up about a feeling is always brave and never naughty, with the wrong answer 'Nobody, I keep it a secret' answered directly. ks2-07 teaches privacy as choosing rather than hiding.",
  ""),
 ("RSHE-P-BS-4", ("primary","Being Safe"), 4, "PARTIAL",
  "ks2-07-privacy-reputation",
  "ks2-07 s12 puts pupils in a group chat containing people they have never met and asks what to do.",
  "How to respond safely to adults encountered online, known and unknown, is not taught as its own content at primary."),
 ("RSHE-P-BS-6", ("primary","Being Safe"), 6, "FULL",
  "eyfs-01-screens-kindness; ks1-02-kind-screens-calm-bodies; ks2-08-kind-safe-online",
  "The reporting vocabulary is built from Reception: feel it, name it, tell a grown up, and never in trouble for telling. ks2-08 adds save the evidence and tell someone who can help.",
  ""),
 ("RSHE-P-GW-7", ("primary","General wellbeing"), 7, "FULL",
  "ks2-08-kind-safe-online",
  "ks2-08 teaches the lasting impact of a pile on and how to get help.",
  ""),
 ("RSHE-P-GW-9", ("primary","General wellbeing"), 9, "PARTIAL",
  "eyfs-01-screens-kindness; ks1-02-kind-screens-calm-bodies; ks2-08-kind-safe-online",
  "Every child names a trusted grown up at home and at school in eyfs-01. Issues arising online are covered by the same route.",
  "Who in school specifically is left to the teacher to fill in. The lessons say a teacher, a parent, a trusted adult, and do not name a role."),
 ("RSHE-S-RR-6", ("secondary","Respectful relationships"), 6, "NONE",
  "",
  "No evidence found. Zero secondary hits for bully, harass or abuse.",
  "Types of bullying including online bullying, its impact, bystander responsibility and where to get help are not taught at secondary."),
 ("RSHE-S-RR-9", ("secondary","Respectful relationships"), 9, "PARTIAL",
  "ks4-18-radicalisation-misogyny",
  "ks4-18 teaches recognising misogyny and the pipeline that delivers it.",
  "Stereotypes based on race, religion, sexual orientation, disability or gender reassignment, which the requirement names alongside sex, are not taught."),
 ("RSHE-S-RR-11", ("secondary","Respectful relationships"), 11, "PARTIAL",
  "ks3-14-bodies-image-pressure",
  "ks3-14 teaches that made content including pornography is not a guide to real bodies or real relationships.",
  "How pornography disempowers and creates a sense of sexual entitlement, which is what this requirement asks for, is not taught."),
 ("RSHE-S-RR-12", ("secondary","Respectful relationships"), 12, "PARTIAL",
  "ks4-18-radicalisation-misogyny; ks4-15-manipulation-persuasion",
  "ks4-18 covers incel and influencer communities as a recruitment pipeline. ks4-15 covers influencers as a commercial mechanism.",
  "The requirement frames this as a discussion of sexual ethics and the sexual norms these sub cultures endorse. The module teaches the recruitment mechanism instead."),
 ("RSHE-S-BS-1", ("secondary","Being Safe"), 1, "PARTIAL",
  "ks4-16-consent-images-law",
  "ks4-16 teaches consent as freely given, specific, ongoing and revocable, and applies it to images.",
  "Consent in early romantic and early sexual relationships, which is the body of this requirement, is outside this scheme by design and belongs to the school's wider RSE provision."),
 ("RSHE-S-BS-2", ("secondary","Being Safe"), 2, "PARTIAL",
  "ks4-16-consent-images-law; ks4-17-sextortion; ks4-15-manipulation-persuasion",
  "ks4-15 teaches naming the technique as the defence. ks4-17 teaches the pressure script and the lifelines that end it.",
  "Resisting sexual pressure in a relationship is not taught, by design."),
 ("RSHE-S-BS-6", ("secondary","Being Safe"), 6, "PARTIAL",
  "ks4-16-consent-images-law",
  "Taking and sharing intimate images without consent is taught in full at ks4-16.",
  "The rest of the requirement is absent: a definition of sexual harassment, unsolicited sexual language or attention, public sexual harassment and upskirting all return zero hits across the scheme."),
 ("RSHE-S-BS-11", ("secondary","Being Safe"), 11, "PARTIAL",
  "ks4-17-sextortion; ks4-15-manipulation-persuasion",
  "ks4-17 teaches financial and sexual exploitation through the sextortion script. Grooming language appears in seven slides.",
  "Criminal exploitation and the laws relating to these harms are not taught."),
 ("RSHE-S-BS-16", ("secondary","Being Safe"), 16, "PARTIAL",
  "ks4-17-sextortion; ks4-16-consent-images-law",
  "ks4-17 teaches three lifelines and that the people running it depend on panic and silence. ks4-16 teaches Report Remove and that a pupil will not be in trouble for asking for help.",
  "Seeking support for a pupil's own worrying or abusive behaviour is not taught."),
 ("RSHE-S-PS-2", ("secondary","Personal safety"), 2, "FULL",
  "ks3-12-misinfo-deepfakes; ks4-15-manipulation-persuasion; ks3-11-social-workarounds",
  "ks3-12 answers 'whether everyone else is doing it' with 'Everyone else doing it changes nothing about what it exposes you to.' ks4-15 teaches FOMO as an engineered worry. ks3-11 teaches the workaround as a social pressure.",
  ""),
 ("RSHE-S-PS-6", ("secondary","Personal safety"), 6, "PARTIAL",
  "ks4-17-sextortion; ks4-18-radicalisation-misogyny; ks3-22-when-an-ai-acts-like-a-friend",
  "ks4-17 teaches the grooming shape of a sextortion approach. ks4-18 teaches isolate, flatter, escalate.",
  "Grooming is taught as a script rather than as signs a pupil might notice in their own life, and exploitation outside the online context is not covered."),
 ("RSHE-S-MW-8", ("secondary","Mental wellbeing"), 8, "NONE",
  "",
  "No evidence found. Zero secondary hits for gambl on a word boundary search.",
  "That gambling can lead to serious mental health harms including anxiety, depression and suicide, and that some products are more harmful than others, is not taught."),
]

# Duties that cannot be discharged by teaching pupils. Rows for the matrix so
# a school can see what the scheme does not and cannot do.
NOT_LESSON = [
 ("KCSIE-1","Keeping Children Safe in Education (statutory safeguarding)","Every member of staff reads Part one and knows the school's safeguarding systems, the DSL and deputy, and the referral routes.",
  "NOT A LESSON REQUIREMENT","", "The Hub carries a DSL page, a CPD page and 10 minute staff briefings for the safeguarding flagged modules.","Staff reading, training and the school's own systems. No scheme of work discharges this."),
 ("KCSIE-2","Keeping Children Safe in Education (statutory safeguarding)","Concerns are reported to the DSL without delay, recorded with a summary, actions, decisions, rationale and outcomes, and information is shared where necessary to protect a child.",
  "NOT A LESSON REQUIREMENT","","Every flagged module carries a DSL note and disclosure handling written into the script, so a disclosure during a lesson lands in the school's own process.","Recording and referral happen in the school's own systems. This platform holds no pupil data and cannot hold a record."),
 ("KCSIE-3","Keeping Children Safe in Education (statutory safeguarding)","Allegations about staff, including supply staff, trainees, volunteers and contractors, are managed under the school's procedure, and whistleblowing routes are known.",
  "NOT A LESSON REQUIREMENT","","None. Out of scope.","Entirely the school's. The NSPCC whistleblowing line is 0800 028 0285."),
 ("FILT-1","Filtering and monitoring (technical standards, referenced by KCSIE)","The school has appropriate filtering and monitoring in place, reviewed at least annually, with roles assigned.",
  "NOT A LESSON REQUIREMENT","","None.","A technical and governance duty. Teaching pupils about online safety does not touch it, and no claim on any Guided Childhood page should imply otherwise."),
 ("POL-1","RSHE statutory guidance, Developing a policy","The school has a written RSE policy, consults parents on it, publishes it and makes it available free of charge.",
  "NOT A LESSON REQUIREMENT","","The Hub policy page supplies model text a school can adapt, and the parent pack supplies consultation material.","The policy is the school's, adopted by its governing body. Supplying text is not the same as having a policy."),
 ("POL-2","RSHE statutory guidance, Openness with parents","Parents can see the materials used to teach RSHE, and the school sets out its withdrawal process for sex education.",
  "NOT A LESSON REQUIREMENT","","The licence explicitly permits showing any lesson to a parent, and per lesson parent notes and a parent pack are provided. This scheme teaches no sex education, so the withdrawal right does not bite on it.","The school still runs the viewing route and the withdrawal process."),
 ("POL-3","Data protection (UK GDPR, DPIA)","The school completes a DPIA where required and records its lawful basis and retention.",
  "NOT A LESSON REQUIREMENT","","The Hub data protection page supplies the processing description and consultation evidence. The platform holds no pupil names, logins or profiling, which keeps the assessment small.","The DPIA is the school's to complete and sign."),
 ("GOV-1","RSHE statutory guidance, Governors and Trustees","Governors assure themselves that RSHE is taught and hold leaders to account for the quality of provision.",
  "NOT A LESSON REQUIREMENT","","The mapping matrix, year plan and printed learning record are the paper a governor can read.","Assurance and the judgement of quality are the governing body's."),
]
