# Verdicts for the coverage matrix. Each entry is
#   (requirement_id, strand_key, item_no, coverage, modules, evidence, gap)
# strand_key indexes rshe/requirements.json so the requirement text is
# taken verbatim from the statutory guidance rather than retyped.

V = [
 # ---- PRIMARY Relationships education: Online safety and awareness
 ("RSHE-P-OSA-1", ("primary","Online safety and awareness"), 1, "FULL",
  "ks1-02-kind-screens-calm-bodies; ks2-07-privacy-reputation; ks2-08-kind-safe-online",
  "ks1-02 s9 teaches 'On screens we use the same kind words we use in the classroom. Screen words are still real words and they can still hurt.' ks2-07 s12 runs a group chat scenario that applies direct pressure to send a photo ('nearly everyone has done it, just waiting on YOU'). ks2-08 teaches bystander behaviour in a pile on.",
  "Closed by migration 310. The ks1-02 keywords slide now teaches, in fifteen seconds, that sometimes you cannot see who is talking to you, that it changes nothing about using kind words, and that not knowing who it is makes telling a grown up more important rather than less."),
 ("RSHE-P-OSA-2", ("primary","Online safety and awareness"), 2, "FULL",
  "ks1-03-real-pretend-computer; ks2-07-privacy-reputation; ks2-08-kind-safe-online",
  "ks1-03 teaches sorting pictures into real, pretend and computer made, with a detective question said aloud before believing a picture. ks2-07 s12 shows a group chat with '2 you have never met'. ks2-08 teaches recognising harmful contact and the three moves ending in tell someone who can help.",
  "Closed by migration 310. ks2-07 now teaches that online anybody can say they are anybody, that a grown up can make an account saying they are eleven, and the one rule that follows: if someone you have not met asks about you, asks for a photo, or asks you to keep the chat secret, you stop and tell a grown up."),
 ("RSHE-P-OSA-3", ("primary","Online safety and awareness"), 3, "NONE",
  "",
  "No evidence found. A word boundary search of all 732 production slides for 'age restrict', 'age rating', 'age limit', 'age verif', 'minimum age', 'thirteen', 'aged 13' and 'age of 13' returns zero hits in EYFS, KS1 and KS2.",
  "The minimum age of 13 for social media, and why it protects children, is not taught at primary at all. This is a named statutory requirement with a specific figure in it."),
 ("RSHE-P-OSA-4", ("primary","Online safety and awareness"), 4, "FULL",
  "ks2-07-privacy-reputation",
  "ks2-07 is a full module on the judgement: the private list, the share test, three questions including 'does it give away where I am?', and 'Privacy is not hiding everything, it is choosing.' s16 teaches that location leaks hide in the corners of photos (uniform, street signs, school name).",
  "Closed by migration 310. The share test now ends on the settings, the one thing on the slide a child can act on that night: apps have a settings page, two of its switches are privacy and location, and location off means the photo stops carrying a map."),
 ("RSHE-P-OSA-5", ("primary","Online safety and awareness"), 5, "FULL",
  "ks2-07-privacy-reputation",
  "ks2-07 s11 'The internet remembers', s13 'The journey of one shared photo', s15 'Your footprint grows either way', and a prove phase that tests the judgement on real cases.",
  ""),
 ("RSHE-P-OSA-6", ("primary","Online safety and awareness"), 6, "FULL",
  "eyfs-01-screens-kindness; ks1-02-kind-screens-calm-bodies; ks2-08-kind-safe-online",
  "eyfs-01 teaches 'Ask a grown up: is this real?' and has every child name a trusted grown up at home and at school. ks1-02 teaches 'feel it, name it, tell a grown up' with the line 'You are never in trouble for telling.' ks2-08 move three is tell someone who can help.",
  ""),

 # ---- PRIMARY Health and wellbeing: Wellbeing online
 ("RSHE-P-WO-1", ("primary","Wellbeing online"), 1, "FULL",
  "ks2-04-screen-routines; eyfs-01-screens-kindness",
  "The positive pathway register runs through every module: screens are treated as ordinary and the lessons teach judgement rather than prohibition.",
  "Closed by migration 310. ks2-04 now closes on the question the scheme's register always implied and never asked: the internet is neither the enemy nor a treat, it has brilliant things and rubbish things in it, often on the same screen, and being good at it means knowing which is which."),
 ("RSHE-P-WO-2", ("primary","Wellbeing online"), 2, "FULL",
  "ks2-08-kind-safe-online; ks2-23-when-a-machine-talks-like-a-friend",
  "ks2-23 teaches that a machine that talks like a friend is not a friend, which is adjacent to the requirement.",
  "Closed by migration 310. ks2-08 now teaches that talking to friends online is real talking and thinner than being with them, because a screen carries your words and drops your face and your voice."),
 ("RSHE-P-WO-3", ("primary","Wellbeing online"), 3, "FULL",
  "ks1-02-kind-screens-calm-bodies; ks2-04-screen-routines",
  "ks1-02 objective is 'Notice what my body is telling me after screen time' and teaches feeling words for wiggly, grumpy and tired. ks2-04 is a full module on routines, with the four moments (after school, bedtime, mealtimes, homework) named on the slide.",
  ""),
 ("RSHE-P-WO-4", ("primary","Wellbeing online"), 4, "FULL",
  "ks1-02-kind-screens-calm-bodies; ks2-08-kind-safe-online",
  "ks1-02 s9 'WE never send messages like this.' ks2-08 s11 teaches the gap 'between how it feels to send and how it feels to receive'.",
  ""),
 ("RSHE-P-WO-5", ("primary","Wellbeing online"), 5, "NONE",
  "",
  "No evidence found. Zero hits across all 732 slides for 'age restrict', 'age rating', 'age limit', 'age verif' or 'PEGI'.",
  "Why social media, apps, games and gambling sites are age restricted is not taught anywhere in the scheme, at any key stage."),
 ("RSHE-P-WO-6", ("primary","Wellbeing online"), 6, "FULL",
  "ks2-05-gaming-time-spend",
  "ks2-05 teaches loot boxes directly, including s19 'Paying money for a random chance is how gambling machines work, which is why some countries have banned loot boxes for children', the countdown chest scenario with fake scarcity, and a spend spotters sort with the verdicts Fine to enjoy, Ask first, Walk away. Its statutory hook is Citizenship financial literacy (fraud and scam prevention).",
  ""),
 ("RSHE-P-WO-7", ("primary","Wellbeing online"), 7, "FULL",
  "eyfs-01-screens-kindness; ks1-03-real-pretend-computer; ks2-06-how-algorithms-work",
  "eyfs-01 teaches Look and Ask, with the feedback line 'It is on the screen, but that does not make it real.' ks1-03 is a picture detectives module. ks2-06 teaches what the recipe is watching.",
  ""),
 ("RSHE-P-WO-8", ("primary","Wellbeing online"), 8, "FULL",
  "ks2-08-kind-safe-online",
  "ks2-08 carries 12 slides using the words bully, harass, abuse or pile on. Objectives include telling the difference between one unkind moment and real bullying, spotting a pile on forming, and the three moves.",
  ""),
 ("RSHE-P-WO-9", ("primary","Wellbeing online"), 9, "FULL",
  "ks2-06-how-algorithms-work",
  "ks2-06 teaches how information is selected and targeted: an algorithm is a recipe, what the app is really watching, and why the feed shows what it shows.",
  "Closed by migration 310. ks2-06 now teaches the search box as the same recipe idea in the place children trust most: something chose the order, the top results are sometimes paid for, and first does not mean truest."),
 ("RSHE-P-WO-10", ("primary","Wellbeing online"), 10, "FULL",
  "ks2-07-privacy-reputation; ks2-09-copyright-ownership",
  "ks2-07 teaches privacy as choosing. ks2-09 teaches ownership, permission and credit.",
  "Closed by migration 310. ks2-09 now turns ownership around to point at the child: your name, face, birthday and address belong to you the way your drawing does, asking means a real yes and not a pre ticked box, and you can change your mind later."),
 ("RSHE-P-WO-11", ("primary","Wellbeing online"), 11, "FULL",
  "eyfs-01-screens-kindness; ks1-02-kind-screens-calm-bodies; ks2-08-kind-safe-online",
  "The trusted adult route is taught thoroughly and repeatedly from Reception, including that the child is never in trouble for telling.",
  "Closed by migration 310. ks2-08 now teaches the in platform route alongside the trusted adult one: report tells the app, block stops that person reaching you, and neither replaces telling a grown up."),

 # ---- SECONDARY RSE: Online safety and awareness
 ("RSHE-S-OSA-1", ("secondary","Online safety and awareness"), 1, "FULL",
  "ks4-16-consent-images-law; ks3-11-social-workarounds",
  "ks4-16 s7 makes the link explicitly for images: 'with images the same rules apply, except the stakes are far higher because a shared image can be copied.' The general principle is taught at KS1 and KS2.",
  "Closed by migration 309. ks3-11 now states the standard at secondary: what you say online is held to the same standard as what you say out loud in a corridor, because the screen changes who can see you, never what is decent."),
 ("RSHE-S-OSA-2", ("secondary","Online safety and awareness"), 2, "FULL",
  "ks3-11-social-workarounds; ks4-19-readiness-at-16",
  "ks3-11 s23 teaches that the real age keeps every wired protection on and the privacy setting adds another on top, and that settings can work for you. ks4-19 s19 teaches choosing defaults on day one: notifications off, private account first, a time cap chosen in advance.",
  "Closed by migration 309. ks3-11 now gives the room two words worth having: a private space is one where you could name everyone, and everything else is public, whatever the app calls it."),
 ("RSHE-S-OSA-3", ("secondary","Online safety and awareness"), 3, "FULL",
  "ks3-12-misinfo-deepfakes; ks3-14-bodies-image-pressure; ks4-15-manipulation-persuasion; ks4-17-sextortion",
  "ks3-14 teaches idealised and edited images. ks4-15 teaches parasocial pull and why an influencer feels like a friend. ks4-17 teaches accounts that exist to run a script. ks3-12 teaches AI generated content.",
  "Closed by migration 309. ks3-12 now teaches that accounts can be manufactured as well as content, run by somebody who is nobody they claim to be or by no person at all, and that people go further online than they would in a room because the screen hides the face that would normally stop them."),
 ("RSHE-S-OSA-4", ("secondary","Online safety and awareness"), 4, "FULL",
  "ks4-16-consent-images-law",
  "ks4-16 is a 32 slide module on images and the law, with 38 slides across the scheme matching 'a crime', 'illegal', 'the law' or 'under 18'. Objectives include stating what UK law says about images of anyone under 18, including images of yourself.",
  ""),
 ("RSHE-S-OSA-5", ("secondary","Online safety and awareness"), 5, "FULL",
  "ks4-16-consent-images-law",
  "ks4-16 teaches that the law applies to any image of a person under 18, teaches Report Remove, and teaches that a pupil will not be in trouble for asking for help.",
  "Closed by migration 309. The law diagram gained a fourth thing it covers, generating: an image a computer made or edited onto someone under 18 is treated exactly like a photograph. The slide before it now adds that past eighteen the rule changes shape rather than disappearing, because sharing an intimate image of an adult without consent is also a crime."),
 ("RSHE-S-OSA-6", ("secondary","Online safety and awareness"), 6, "FULL",
  "ks4-16-consent-images-law",
  "18 slides teach the reporting route by name: Report Remove, run by Childline and the Internet Watch Foundation, described as free, confidential and available to anyone under 18.",
  ""),
 ("RSHE-S-OSA-7", ("secondary","Online safety and awareness"), 7, "FULL",
  "ks3-12-misinfo-deepfakes",
  "ks3-12 is the 33 slide pilot module. It defines deepfake, teaches identification, and carries a sourced detection statistic (iProov deepfake detection study, 2025).",
  ""),
 ("RSHE-S-OSA-8", ("secondary","Online safety and awareness"), 8, "PARTIAL",
  "ks4-18-radicalisation-misogyny",
  "ks4-18 teaches the pipeline that carries misogynistic content, including isolate, flatter, escalate, and how to run a check on anything in a feed.",
  "Content that encourages violence or the use of weapons is not taught: a word boundary search for knife, weapon or violent content returns zero secondary hits. Where to go for advice about something seen online is not taught at secondary."),
 ("RSHE-S-OSA-9", ("secondary","Online safety and awareness"), 9, "INDIRECT",
  "ks4-17-sextortion; ks4-18-radicalisation-misogyny",
  "Escalation is taught, but as a stage in a criminal or radicalisation script rather than as conflict between peers.",
  "The requirement is about social media escalating conflicts and how to avoid them. That is taught at KS2 in ks2-08 (the pile on) and not carried into secondary."),
 ("RSHE-S-OSA-10", ("secondary","Online safety and awareness"), 10, "NONE",
  "",
  "No evidence found. A word boundary search of all secondary slides for bully, harass, abuse, stalk, coercive or controlling returns zero hits.",
  "Technology used in bullying, harassment, stalking, coercive and controlling behaviour is taught nowhere at KS3 to KS5. The scheme teaches this at KS2 and stops."),
 ("RSHE-S-OSA-11", ("secondary","Online safety and awareness"), 11, "FULL",
  "ks3-14-bodies-image-pressure",
  "ks3-14 names it calmly: 'One more kind of made content needs naming, calmly and briefly: pornography.' It teaches that made content including pornography is not a guide to real bodies or real relationships, that seeing it is not unusual and not a punishable thing, and carries a sourced figure on average age of first exposure.",
  "Closed by migration 309. The module now teaches the half that reaches other people: watching a lot of it can change what someone expects of a partner, and the damage is that expectation travelling into a real relationship."),
 ("RSHE-S-OSA-12", ("secondary","Online safety and awareness"), 12, "FULL",
  "ks4-15-manipulation-persuasion; ks5-20-ai-mastery-data-rights; ks3-10-mood-and-screens",
  "ks5-20 defines profiling as building a picture of who you are from your data, usually to predict and shape what you buy, watch and believe. ks3-10 uses 'your feed, your data' as its close.",
  "Closed by migration 311. ks4-15 now opens the machine: every scroll, pause, search and like is collected, behaviour rather than posts, and the profile built from it is what is actually for sale."),
 ("RSHE-S-OSA-13", ("secondary","Online safety and awareness"), 13, "FULL",
  "ks4-15-manipulation-persuasion; ks4-19-readiness-at-16",
  "ks4-15 teaches the attention business model and who profits from a feeling.",
  "Closed by migration 311. Advertisers do not buy your name, they buy the right to reach the kind of person you have been measured to be, which is why the advert feels like it read your mind and why the free app was never free."),
 ("RSHE-S-OSA-14", ("secondary","Online safety and awareness"), 14, "FULL",
  "ks3-13-scams-fraud-money; ks4-17-sextortion",
  "ks3-13 is a 31 slide module on scams and fraud, teaching that 'Pretending to be someone else to take money or an account is fraud, and fraud is a criminal offence rather than bad luck.' ks4-17 is a 30 slide module on sextortion, teaching the opener, the escalation, the threat with a countdown, and three lifelines.",
  ""),
 ("RSHE-S-OSA-15", ("secondary","Online safety and awareness"), 15, "FULL",
  "ks3-22-when-an-ai-acts-like-a-friend; ks5-20-ai-mastery-data-rights; ks3-24-is-it-doing-my-thinking",
  "ks3-22 is a 31 slide module on AI companionship. ks5-20 teaches the difference between a chatbot and an agent: 'With a chatbot you ask, is this answer right? With an agent you must ask, what is it allowed to do without me.' ks3-24 teaches offloading and cognitive cost.",
  ""),

 # ---- SECONDARY Health and wellbeing: Wellbeing online
 ("RSHE-S-WO-1", ("secondary","Wellbeing online"), 1, "FULL",
  "ks3-10-mood-and-screens",
  "ks3-10 teaches the mood audit (better, worse or nothing) and the research position honestly: the link between raw hours and wellbeing is real but tiny, and what matters is what the time is made of.",
  ""),
 ("RSHE-S-WO-2", ("secondary","Wellbeing online"), 2, "FULL",
  "ks3-10-mood-and-screens; ks3-14-bodies-image-pressure",
  "ks3-10 defines comparing as 'Measuring your real, unedited life against someone else's chosen highlights' and sets it against connecting. ks3-14 covers body image and edited content.",
  "Closed by migration 309. ks3-10 now asks the class which of their connections would survive the app closing, which is the over reliance question in the form a fourteen year old will actually answer."),
 ("RSHE-S-WO-3", ("secondary","Wellbeing online"), 3, "NONE",
  "",
  "No evidence found. Zero secondary hits for bully, harass or abuse on a word boundary search.",
  "Identifying harmful behaviours online and how to report them or find support is not taught at KS3 to KS5."),
 ("RSHE-S-WO-4", ("secondary","Wellbeing online"), 4, "NONE",
  "",
  "No evidence found. Zero secondary hits for gambl, loot box, lootbox or debt. The only gambling teaching in the scheme is one KS2 slide.",
  "Online gambling, gambling like content within gaming, and the accumulation of debt are not taught at secondary. The Hub currently lists online gambling as a covered topic."),
 ("RSHE-S-WO-5", ("secondary","Wellbeing online"), 5, "FULL",
  "ks3-12-misinfo-deepfakes; ks4-15-manipulation-persuasion",
  "ks3-12 teaches misinformation and disinformation with distinct definitions. ks4-15 teaches targeting and the persuasion industry.",
  "Closed by migration 309. ks3-12 now teaches the conspiracy theory as a third shape with a tell: it is built so that evidence against it counts as proof of the cover up, and a claim nothing can disprove is unfalsifiable rather than strong. Deliberately no worked example, because naming a live theory in a classroom hands it an audience."),
 ("RSHE-S-WO-6", ("secondary","Wellbeing online"), 6, "NONE",
  "",
  "No evidence found. Zero hits anywhere for knife, county lines, illicit or drug supply.",
  "The risks of illegal behaviours online, including drug and knife supply, are not taught at any key stage."),
 ("RSHE-S-WO-7", ("secondary","Wellbeing online"), 7, "NONE",
  "",
  "No evidence found. Zero hits anywhere in 732 slides for self harm or suicide.",
  "Content promoting self harm, suicide or violence is not taught, nor is how to report it or get support after seeing it. The schools pricing page currently tells buyers that scripts mean a teacher is 'not improvising about consent or self harm at nine on a Monday'."),

 # ---- Digital relevant items inside other statutory strands
 ("RSHE-P-RKR-9", ("primary","Respectful, kind relationships"), 9, "FULL",
  "ks2-08-kind-safe-online",
  "ks2-08 teaches the difference between one unkind moment and real bullying, the bystander's position in a pile on, and the three moves ending in telling an adult.",
  ""),
 ("RSHE-P-BS-2", ("primary","Being Safe"), 2, "FULL",
  "ks1-02-kind-screens-calm-bodies; ks2-07-privacy-reputation",
  "ks1-02 teaches that telling a grown up about a feeling is always brave and never naughty, with the wrong answer 'Nobody, I keep it a secret' answered directly. ks2-07 teaches privacy as choosing rather than hiding.",
  ""),
 ("RSHE-P-BS-4", ("primary","Being Safe"), 4, "FULL",
  "ks2-07-privacy-reputation",
  "ks2-07 s12 puts pupils in a group chat containing people they have never met and asks what to do.",
  "Closed by migration 310, by the same lines that closed RSHE-P-OSA-2. The rule is about what a child does when an adult they have not met asks for something, rather than about spotting a dangerous person."),
 ("RSHE-P-BS-6", ("primary","Being Safe"), 6, "FULL",
  "eyfs-01-screens-kindness; ks1-02-kind-screens-calm-bodies; ks2-08-kind-safe-online",
  "The reporting vocabulary is built from Reception: feel it, name it, tell a grown up, and never in trouble for telling. ks2-08 adds save the evidence and tell someone who can help.",
  ""),
 ("RSHE-P-GW-7", ("primary","General wellbeing"), 7, "FULL",
  "ks2-08-kind-safe-online",
  "ks2-08 teaches the lasting impact of a pile on and how to get help.",
  ""),
 ("RSHE-P-GW-9", ("primary","General wellbeing"), 9, "PARTIAL",
  "eyfs-01-screens-kindness; ks1-02-kind-screens-calm-bodies; ks2-08-kind-safe-online",
  "Every child names a trusted grown up at home and at school in eyfs-01. Issues arising online are covered by the same route.",
  "Who in school specifically is left to the teacher to fill in. The lessons say a teacher, a parent, a trusted adult, and do not name a role."),
 ("RSHE-S-RR-6", ("secondary","Respectful relationships"), 6, "NONE",
  "",
  "No evidence found. Zero secondary hits for bully, harass or abuse.",
  "Types of bullying including online bullying, its impact, bystander responsibility and where to get help are not taught at secondary."),
 ("RSHE-S-RR-9", ("secondary","Respectful relationships"), 9, "PARTIAL",
  "ks4-18-radicalisation-misogyny",
  "ks4-18 teaches recognising misogyny and the pipeline that delivers it.",
  "Stereotypes based on race, religion, sexual orientation, disability or gender reassignment, which the requirement names alongside sex, are not taught."),
 ("RSHE-S-RR-11", ("secondary","Respectful relationships"), 11, "FULL",
  "ks3-14-bodies-image-pressure",
  "ks3-14 teaches that made content including pornography is not a guide to real bodies or real relationships.",
  "Closed by migration 309, by the same lines that closed RSHE-S-OSA-11. The entitlement clause lands as the expectation that another person owes them something."),
 ("RSHE-S-RR-12", ("secondary","Respectful relationships"), 12, "FULL",
  "ks4-18-radicalisation-misogyny; ks4-15-manipulation-persuasion",
  "ks4-18 covers incel and influencer communities as a recruitment pipeline. ks4-15 covers influencers as a commercial mechanism.",
  "Closed by migration 311. ks4-18 now names what is being sold underneath the pipeline: that attraction is a ranking, that women owe men something, and that anyone struggling has been cheated rather than is simply young."),
 ("RSHE-S-BS-1", ("secondary","Being Safe"), 1, "PARTIAL",
  "ks4-16-consent-images-law",
  "ks4-16 teaches consent as freely given, specific, ongoing and revocable, and applies it to images.",
  "Consent in early romantic and early sexual relationships, which is the body of this requirement, is outside this scheme by design and belongs to the school's wider RSE provision."),
 ("RSHE-S-BS-2", ("secondary","Being Safe"), 2, "PARTIAL",
  "ks4-16-consent-images-law; ks4-17-sextortion; ks4-15-manipulation-persuasion",
  "ks4-15 teaches naming the technique as the defence. ks4-17 teaches the pressure script and the lifelines that end it.",
  "Resisting sexual pressure in a relationship is not taught, by design."),
 ("RSHE-S-BS-6", ("secondary","Being Safe"), 6, "FULL",
  "ks4-16-consent-images-law",
  "Taking and sharing intimate images without consent is taught in full at ks4-16.",
  "Closed by migration 309. The module now names the category: sharing an image without consent sits inside sexual harassment, which also covers unwanted sexual messages or attention, pressuring someone into anything sexual, and upskirting. The non digital examples in the requirement belong to your wider RSE."),
 ("RSHE-S-BS-11", ("secondary","Being Safe"), 11, "PARTIAL",
  "ks4-17-sextortion; ks4-15-manipulation-persuasion",
  "ks4-17 teaches financial and sexual exploitation through the sextortion script. Grooming language appears in seven slides.",
  "Criminal exploitation and the laws relating to these harms are not taught."),
 ("RSHE-S-BS-16", ("secondary","Being Safe"), 16, "PARTIAL",
  "ks4-17-sextortion; ks4-16-consent-images-law",
  "ks4-17 teaches three lifelines and that the people running it depend on panic and silence. ks4-16 teaches Report Remove and that a pupil will not be in trouble for asking for help.",
  "Seeking support for a pupil's own worrying or abusive behaviour is not taught."),
 ("RSHE-S-PS-2", ("secondary","Personal safety"), 2, "FULL",
  "ks3-12-misinfo-deepfakes; ks4-15-manipulation-persuasion; ks3-11-social-workarounds",
  "ks3-12 answers 'whether everyone else is doing it' with 'Everyone else doing it changes nothing about what it exposes you to.' ks4-15 teaches FOMO as an engineered worry. ks3-11 teaches the workaround as a social pressure.",
  ""),
 ("RSHE-S-PS-6", ("secondary","Personal safety"), 6, "FULL",
  "ks4-17-sextortion; ks4-18-radicalisation-misogyny; ks3-22-when-an-ai-acts-like-a-friend",
  "ks4-17 teaches the grooming shape of a sextortion approach. ks4-18 teaches isolate, flatter, escalate.",
  "Closed by migration 311. ks4-17 now teaches the shape from the inside, where it feels like being noticed rather than like a script: it moves fast, it moves private, it flatters harder than anyone in your actual life, and at some point it asks you to keep it from everyone."),
 ("RSHE-S-MW-8", ("secondary","Mental wellbeing"), 8, "NONE",
  "",
  "No evidence found. Zero secondary hits for gambl on a word boundary search.",
  "That gambling can lead to serious mental health harms including anxiety, depression and suicide, and that some products are more harmful than others, is not taught."),
]

# Duties that cannot be discharged by teaching pupils. Rows for the matrix so
# a school can see what the scheme does not and cannot do.
NOT_LESSON = [
 ("KCSIE-1","Keeping Children Safe in Education (statutory safeguarding)","Every member of staff reads Part one and knows the school's safeguarding systems, the DSL and deputy, and the referral routes.",
  "NOT A LESSON REQUIREMENT","", "The Hub carries a DSL page, a CPD page and 10 minute staff briefings for the safeguarding flagged modules.","Staff reading, training and the school's own systems. No scheme of work discharges this."),
 ("KCSIE-2","Keeping Children Safe in Education (statutory safeguarding)","Concerns are reported to the DSL without delay, recorded with a summary, actions, decisions, rationale and outcomes, and information is shared where necessary to protect a child.",
  "NOT A LESSON REQUIREMENT","","Every flagged module carries a DSL note and disclosure handling written into the script, so a disclosure during a lesson lands in the school's own process.","Recording and referral happen in the school's own systems. This platform holds no pupil data and cannot hold a record."),
 ("KCSIE-3","Keeping Children Safe in Education (statutory safeguarding)","Allegations about staff, including supply staff, trainees, volunteers and contractors, are managed under the school's procedure, and whistleblowing routes are known.",
  "NOT A LESSON REQUIREMENT","","None. Out of scope.","Entirely the school's. The NSPCC whistleblowing line is 0800 028 0285."),
 ("FILT-1","Filtering and monitoring (technical standards, referenced by KCSIE)","The school has appropriate filtering and monitoring in place, reviewed at least annually, with roles assigned.",
  "NOT A LESSON REQUIREMENT","","None.","A technical and governance duty. Teaching pupils about online safety does not touch it, and no claim on any Guided Childhood page should imply otherwise."),
 ("POL-1","RSHE statutory guidance, Developing a policy","The school has a written RSE policy, consults parents on it, publishes it and makes it available free of charge.",
  "NOT A LESSON REQUIREMENT","","The Hub policy page supplies model text a school can adapt, and the parent pack supplies consultation material.","The policy is the school's, adopted by its governing body. Supplying text is not the same as having a policy."),
 ("POL-2","RSHE statutory guidance, Openness with parents","Parents can see the materials used to teach RSHE, and the school sets out its withdrawal process for sex education.",
  "NOT A LESSON REQUIREMENT","","The licence explicitly permits showing any lesson to a parent, and per lesson parent notes and a parent pack are provided. This scheme teaches no sex education, so the withdrawal right does not bite on it.","The school still runs the viewing route and the withdrawal process."),
 ("POL-3","Data protection (UK GDPR, DPIA)","The school completes a DPIA where required and records its lawful basis and retention.",
  "NOT A LESSON REQUIREMENT","","The Hub data protection page supplies the processing description and consultation evidence. The platform holds no pupil names, logins or profiling, which keeps the assessment small.","The DPIA is the school's to complete and sign."),
 ("GOV-1","RSHE statutory guidance, Governors and Trustees","Governors assure themselves that RSHE is taught and hold leaders to account for the quality of provision.",
  "NOT A LESSON REQUIREMENT","","The mapping matrix, year plan and printed learning record are the paper a governor can read.","Assurance and the judgement of quality are the governing body's."),
]
