// THE SEPTEMBER 2026 STATUTORY REQUIREMENTS, AS DATA.
//
// Every digital and online requirement of the DfE Relationships Education,
// Relationships and Sex Education (RSE) and Health Education statutory
// guidance, July 2025, in force 1 September 2026. Fifty seven rows: the
// thirty nine items in the four online strands, plus the eighteen items in
// other strands with a substantial digital element.
//
// WHY THIS FILE EXISTS. Until 19 September 2026 the whole compliance story
// rendered from RSHE_2025_TOPICS in schools-curriculum.ts, a list of ten
// themes someone wrote. The guidance has twenty eight strands and one hundred
// and ninety five numbered items. Nothing downstream could be more accurate
// than that list, and the list had never been checked against the document.
// The audit (GDC_SCHOOLS_2026_COMPLIANCE_AUDIT.md) checked it, and this file
// is what replaced it.
//
// `text` is quoted verbatim from the guidance and carries its hyphens. Leave
// them: the house rule about dashes governs our copy, not a quotation from a
// statutory document, and editing quoted text breaks the audit trail.
//
// `kcsie` records where Keeping Children Safe in Education 2026 names the same
// harm, by paragraph. Thirty six of the fifty seven have one. A requirement
// named by the curriculum guidance AND the safeguarding guidance is the kind a
// DSL asks about, which is why the column exists.
//
// `evidence` is the contract: short phrases that must appear in the named
// modules' live slide text. scripts/check-rshe-coverage.mjs holds the file to
// it, so a lesson edit that quietly drops a requirement fails CI rather than
// being discovered by a customer.
//
// GENERATED. Edit scripts/gen-rshe-2026.py and regenerate; do not hand edit.

export type Rshe2026Verdict = 'FULL' | 'PARTIAL' | 'GAP' | 'BY_DESIGN'

export type Rshe2026Requirement = {
  /** Stable id, e.g. RSHE-S-OSA-15. Phase, strand, item. */
  id: string
  phase: 'primary' | 'secondary'
  block: 'Relationships education' | 'Relationships and sex education' | 'Health and wellbeing'
  strand: string
  /** The item number inside its strand, as the guidance numbers it. */
  item: number
  /** Verbatim from the guidance. Hyphens are the document's own. */
  text: string
  /** Where KCSIE 2026 names the same harm, by paragraph. Empty if it does not. */
  kcsie: string
  verdict: Rshe2026Verdict
  /** Module ids that teach it. Empty for GAP, by rule. */
  modules: string[]
  /** Phrases that must appear in those modules' slide text. */
  evidence: string[]
  /** For BY_DESIGN, where it belongs and what we teach towards it. For
   *  PARTIAL and GAP, the named clause that is missing. */
  note: string
}

export const RSHE_2026_SOURCE = {
  title: 'Relationships Education, Relationships and Sex Education (RSE) and Health Education',
  publisher: 'Department for Education',
  published: 'July 2025',
  inForce: '1 September 2026',
  /** The RSHE document body carries no commencement date. This is the citation
   *  that does, and it is a second statutory document. */
  inForceCitation: 'Keeping Children Safe in Education 2026, paragraph 159: the guidance is "revised for introduction September 2026"',
  /** The whole subject, for the denominator. This scheme is a digital literacy
   *  and online safety spine and covers the online part of it, never all 195. */
  itemsInGuidance: 195,
  strandsInGuidance: 28,
  reviewed: '2026-09-20',
  reviewedBy: 'Full coverage audit against the live schools.school_lessons rows on 19 September 2026, re-run on 20 September after migrations 312 to 316 closed every gap it found',
} as const


export const RSHE_2026: Rshe2026Requirement[] = [
  {
    id: 'RSHE-P-OSA-1', phase: 'primary', item: 1,
    block: 'Relationships education',
    strand: 'Online safety and awareness',
    text: 'That people should be respectful in online interactions, and that the same principles apply to online relationships as to face-to-face relationships, including where people are anonymous. For example, the importance of avoiding putting pressure on others to share information and images online, and strategies for resisting peer pressure.',
    kcsie: 'para 165 contact: peer-to-peer pressure',
    verdict: 'FULL',
    modules: ['ks1-02-kind-screens-calm-bodies', 'ks2-07-privacy-reputation', 'ks2-08-kind-safe-online'],
    evidence: ['same kind words', 'screen words are still real words', 'cannot see who is talking to you'],
    note: '',
  },
  {
    id: 'RSHE-P-OSA-2', phase: 'primary', item: 2,
    block: 'Relationships education',
    strand: 'Online safety and awareness',
    text: 'How to critically evaluate their online relationships and sources of information, including awareness of the risks associated with people they have never met. For example, that people sometimes behave differently online, including pretending to be someone else, or pretending to be a child, and that this can lead to dangerous situations. How to recognise harmful content or harmful contact, and how to report this.',
    kcsie: 'para 165 contact: adults posing as children or young adults with the intention to groom or exploit them',
    verdict: 'FULL',
    modules: ['ks1-03-real-pretend-computer', 'ks2-07-privacy-reputation', 'ks2-08-kind-safe-online'],
    evidence: ['real, pretend', 'never met', 'anybody can say they are anybody'],
    note: '',
  },
  {
    id: 'RSHE-P-OSA-3', phase: 'primary', item: 3,
    block: 'Relationships education',
    strand: 'Online safety and awareness',
    text: 'That there is a minimum age for joining social media sites (currently 13), which protects children from inappropriate content or unsafe contact with older social media users, who may be strangers, including other children and adults.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['ks2-26-why-thirteen'],
    evidence: ['thirteen is a real rule', 'the protections are wired to the number', 'who can reach you'],
    note: '',
  },
  {
    id: 'RSHE-P-OSA-4', phase: 'primary', item: 4,
    block: 'Relationships education',
    strand: 'Online safety and awareness',
    text: 'The importance of exercising caution about sharing any information about themselves online. Understanding the importance of privacy and location settings to protect information online.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['ks2-07-privacy-reputation'],
    evidence: ['location leaks', 'privacy is not hiding everything', 'privacy settings, which choose who sees your posts', 'the camera setting that saves where each photo was taken'],
    note: '',
  },
  {
    id: 'RSHE-P-OSA-5', phase: 'primary', item: 5,
    block: 'Relationships education',
    strand: 'Online safety and awareness',
    text: 'Online risks, including that any material provided online might be circulated, and that once a picture or words has been circulated there is no way of deleting it everywhere and no control over where it ends up.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['ks2-07-privacy-reputation'],
    evidence: ['the internet remembers', 'journey of one shared photo'],
    note: '',
  },
  {
    id: 'RSHE-P-OSA-6', phase: 'primary', item: 6,
    block: 'Relationships education',
    strand: 'Online safety and awareness',
    text: 'That the internet contains a lot of content that can be inappropriate and upsetting for children, and where to go for advice and support when they feel worried or concerned about something they have seen or engaged with online.',
    kcsie: 'para 165 content: being exposed to illegal, inappropriate, or harmful content',
    verdict: 'FULL',
    modules: ['eyfs-01-screens-kindness', 'ks1-02-kind-screens-calm-bodies', 'ks2-08-kind-safe-online'],
    evidence: ['is this real', 'never in trouble for telling'],
    note: '',
  },
  {
    id: 'RSHE-P-WO-1', phase: 'primary', item: 1,
    block: 'Health and wellbeing',
    strand: 'Wellbeing online',
    text: 'That for almost everyone the internet is an integral part of life. Pupils should be supported to think about positive and negative aspects of the internet.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['ks2-04-screen-routines', 'eyfs-01-screens-kindness'],
    evidence: ['brilliant things in it and rubbish things in it'],
    note: '',
  },
  {
    id: 'RSHE-P-WO-2', phase: 'primary', item: 2,
    block: 'Health and wellbeing',
    strand: 'Wellbeing online',
    text: 'Pupils should be supported to discuss how online relationships can complement and support meaningful in-person relationships, but also how they might be in tension, and the reasons why online relationships are unlikely to be a good substitute for high quality in-person relationships, looking at the pros and cons of different ways of using online connection.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['ks2-08-kind-safe-online', 'ks2-23-when-a-machine-talks-like-a-friend'],
    evidence: ['thinner than being with them'],
    note: '',
  },
  {
    id: 'RSHE-P-WO-3', phase: 'primary', item: 3,
    block: 'Health and wellbeing',
    strand: 'Wellbeing online',
    text: 'The benefits of limiting time spent online, the risks of excessive time spent on electronic devices and the impact of positive and negative content online on their own and others’ mental and physical wellbeing.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['ks1-02-kind-screens-calm-bodies', 'ks2-04-screen-routines'],
    evidence: ['screen time', 'bedtime'],
    note: '',
  },
  {
    id: 'RSHE-P-WO-4', phase: 'primary', item: 4,
    block: 'Health and wellbeing',
    strand: 'Wellbeing online',
    text: 'How to consider the impact of their online behaviour on others, and how to recognise and display respectful behaviour online.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['ks1-02-kind-screens-calm-bodies', 'ks2-08-kind-safe-online'],
    evidence: ['how it feels to send', 'kind words'],
    note: '',
  },
  {
    id: 'RSHE-P-WO-5', phase: 'primary', item: 5,
    block: 'Health and wellbeing',
    strand: 'Wellbeing online',
    text: 'Why social media, some apps, computer games and online gaming, including gambling sites, are age restricted.',
    kcsie: 'para 165 commerce: risks such as online gambling, inappropriate advertising, phishing and or financial scams',
    verdict: 'FULL',
    modules: ['ks2-26-why-thirteen', 'ks2-05-gaming-time-spend'],
    evidence: ['games carry numbers too', 'gambling sites', 'find the number, ask what it is for'],
    note: '',
  },
  {
    id: 'RSHE-P-WO-6', phase: 'primary', item: 6,
    block: 'Health and wellbeing',
    strand: 'Wellbeing online',
    text: 'The risks relating to online gaming, video game monetisation, scams, fraud and other financial harms, and that gaming can become addictive.',
    kcsie: 'para 165 commerce: online gambling, phishing and or financial scams',
    verdict: 'FULL',
    modules: ['ks2-05-gaming-time-spend'],
    evidence: ['loot box', 'gambling machines work'],
    note: '',
  },
  {
    id: 'RSHE-P-WO-7', phase: 'primary', item: 7,
    block: 'Health and wellbeing',
    strand: 'Wellbeing online',
    text: 'How to take a critical approach to what they see and read online and make responsible decisions about which content, including content on social media and apps, is appropriate for them.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['eyfs-01-screens-kindness', 'ks1-03-real-pretend-computer', 'ks2-06-how-algorithms-work'],
    evidence: ['does not make it real', 'detective'],
    note: '',
  },
  {
    id: 'RSHE-P-WO-8', phase: 'primary', item: 8,
    block: 'Health and wellbeing',
    strand: 'Wellbeing online',
    text: 'That abuse, bullying and harassment can take place online and that this can impact wellbeing. How to seek support from trusted adults.',
    kcsie: 'para 165 conduct: online bullying',
    verdict: 'FULL',
    modules: ['ks2-08-kind-safe-online'],
    evidence: ['pile on', 'bullying'],
    note: '',
  },
  {
    id: 'RSHE-P-WO-9', phase: 'primary', item: 9,
    block: 'Health and wellbeing',
    strand: 'Wellbeing online',
    text: 'How to understand the information they find online, including from search engines, and know how information is selected and targeted.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['ks2-06-how-algorithms-work'],
    evidence: ['algorithm', 'search boxes follow a recipe', 'first does not mean truest'],
    note: '',
  },
  {
    id: 'RSHE-P-WO-10', phase: 'primary', item: 10,
    block: 'Health and wellbeing',
    strand: 'Wellbeing online',
    text: 'That they have rights in relation to sharing personal data, privacy and consent.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['ks2-07-privacy-reputation', 'ks2-09-copyright-ownership'],
    evidence: ['credit', 'permission', 'belong to you in exactly the way your drawing does'],
    note: '',
  },
  {
    id: 'RSHE-P-WO-11', phase: 'primary', item: 11,
    block: 'Health and wellbeing',
    strand: 'Wellbeing online',
    text: 'Where and how to report concerns and get support with issues online.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['eyfs-01-screens-kindness', 'ks1-02-kind-screens-calm-bodies', 'ks2-08-kind-safe-online'],
    evidence: ['tell a grown up', 'report button and a block button'],
    note: '',
  },
  {
    id: 'RSHE-S-OSA-1', phase: 'secondary', item: 1,
    block: 'Relationships and sex education',
    strand: 'Online safety and awareness',
    text: 'Rights, responsibilities and opportunities online, including that the same expectations of behaviour apply in all contexts, including online.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['ks4-16-consent-images-law', 'ks3-11-social-workarounds'],
    evidence: ['the same rules apply', 'never what is decent'],
    note: '',
  },
  {
    id: 'RSHE-S-OSA-2', phase: 'secondary', item: 2,
    block: 'Relationships and sex education',
    strand: 'Online safety and awareness',
    text: 'Online risks, including the importance of being cautious about sharing personal information online and of using privacy and location settings appropriately to protect information online. Pupils should also understand the difference between public and private online spaces and related safety issues.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['ks3-11-social-workarounds', 'ks4-19-readiness-at-16'],
    evidence: ['privacy setting', 'private account', 'private space is one where you could name everyone'],
    note: '',
  },
  {
    id: 'RSHE-S-OSA-3', phase: 'secondary', item: 3,
    block: 'Relationships and sex education',
    strand: 'Online safety and awareness',
    text: 'The characteristics of social media, including that some social media accounts are fake, and / or may post things which aren’t real / have been created with AI. That social media users may say things in more extreme ways than they might in face-to-face situations, and that some users present highly exaggerated or idealised profiles of themselves online.',
    kcsie: 'para 165 content: misinformation, disinformation (including fake news)',
    verdict: 'FULL',
    modules: ['ks3-12-misinfo-deepfakes', 'ks3-14-bodies-image-pressure', 'ks4-15-manipulation-persuasion', 'ks4-17-sextortion'],
    evidence: ['idealis', 'accounts can be too', 'go further online than they would in a room'],
    note: '',
  },
  {
    id: 'RSHE-S-OSA-4', phase: 'secondary', item: 4,
    block: 'Relationships and sex education',
    strand: 'Online safety and awareness',
    text: 'Not to provide material to others that they would not want to be distributed further and not to pass on personal material which is sent to them. Pupils should understand that any material provided online might be circulated, and that once this has happened there is no way of controlling where it ends up. Pupils should understand the serious risks of sending material to others, including the law concerning the sharing of images.',
    kcsie: 'para 165 conduct: making, sending and receiving explicit images, including those generated using AI',
    verdict: 'FULL',
    modules: ['ks4-16-consent-images-law'],
    evidence: ['under 18', 'the law'],
    note: '',
  },
  {
    id: 'RSHE-S-OSA-5', phase: 'secondary', item: 5,
    block: 'Relationships and sex education',
    strand: 'Online safety and awareness',
    text: 'That keeping or forwarding indecent or sexual images of someone under 18 is a crime, even if the photo is of themselves or of someone who has consented, and even if the image was created by the child and/or using AI generated imagery. Pupils should understand the potentially serious consequences of acquiring or generating indecent or sexual images of someone under 18, including the potential for criminal charges and severe penalties including imprisonment. Pupils should know how to seek support and should understand that they will not be in trouble for asking for help, either at school or with the police, if an image of themselves has been shared. Pupils should also understand that sharing indecent images of people over 18 without consent is a crime.',
    kcsie: 'para 165 conduct: explicit images, including those generated using AI; and the definition section, which states images may be digitally altered or wholly generated using artificial intelligence, including what are sometimes described as deepfakes or deep nudes',
    verdict: 'FULL',
    modules: ['ks4-16-consent-images-law'],
    evidence: ['nude or sexual image of a person under 18', 'agreeing is no defence', 'the law treats it exactly like a photograph', 'intimate image of an adult without their consent'],
    note: '',
  },
  {
    id: 'RSHE-S-OSA-6', phase: 'secondary', item: 6,
    block: 'Relationships and sex education',
    strand: 'Online safety and awareness',
    text: 'What to do and how to report when they are concerned about material that has been circulated, including personal information, images or videos, and how to manage issues online.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['ks4-16-consent-images-law'],
    evidence: ['Report Remove', 'Internet Watch Foundation'],
    note: '',
  },
  {
    id: 'RSHE-S-OSA-7', phase: 'secondary', item: 7,
    block: 'Relationships and sex education',
    strand: 'Online safety and awareness',
    text: 'About the prevalence of deepfakes including videos and photos, how deepfakes can be used maliciously as well as for entertainment, the harms that can be caused by deepfakes and how to identify them.',
    kcsie: 'para 160: understanding online harms such as sharing images, the prevalence of deepfakes, pornography and misogynistic influencers and when and where to seek help',
    verdict: 'FULL',
    modules: ['ks3-12-misinfo-deepfakes'],
    evidence: ['deepfake'],
    note: '',
  },
  {
    id: 'RSHE-S-OSA-8', phase: 'secondary', item: 8,
    block: 'Relationships and sex education',
    strand: 'Online safety and awareness',
    text: 'That the internet contains inappropriate and upsetting content, some of which is illegal, including unacceptable content that encourages misogyny, violence or use of weapons. Pupils should be taught where to go for advice and support about something they have seen online. Pupils should understand that online content can present a distorted picture of the world and normalise or glamorise behaviours which are unhealthy and wrong.',
    kcsie: 'para 165 content: racism, misogyny, antisemitism, radicalisation, extremism, extreme sexual or physical violence',
    verdict: 'FULL',
    modules: ['ks4-18-radicalisation-misogyny', 'ks4-29-did-not-go-looking'],
    evidence: ['misogyn', 'violent video', 'report harmful content', 'more ordinary than it is'],
    note: '',
  },
  {
    id: 'RSHE-S-OSA-9', phase: 'secondary', item: 9,
    block: 'Relationships and sex education',
    strand: 'Online safety and awareness',
    text: 'That social media can lead to escalations in conflicts, how to avoid these escalations and where to go for help and advice.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['ks3-27-when-it-turns-on-you'],
    evidence: ['three brakes', 'why it gets bigger online', 'name it, save it, say it'],
    note: '',
  },
  {
    id: 'RSHE-S-OSA-10', phase: 'secondary', item: 10,
    block: 'Relationships and sex education',
    strand: 'Online safety and awareness',
    text: 'How to identify when technology and social media is used as part of bullying, harassment, stalking, coercive and controlling behaviour, and other forms of abusive and/or illegal behaviour and how to seek support about concerns.',
    kcsie: 'para 165 conduct: online bullying; para 160: how to recognise and report concerns about an abusive relationship, including coercive and controlling behaviour',
    verdict: 'FULL',
    modules: ['ks3-27-when-it-turns-on-you'],
    evidence: ['harassment', 'coercive control', 'stalking is being followed', 'four things with real names'],
    note: '',
  },
  {
    id: 'RSHE-S-OSA-11', phase: 'secondary', item: 11,
    block: 'Relationships and sex education',
    strand: 'Online safety and awareness',
    text: 'That pornography, and other online content, often presents a distorted picture of people and their sexual behaviours and can negatively affect how people behave towards sexual partners. This can affect pupils who see pornographic content accidentally as well as those who see it deliberately. Pornography can also portray misogynistic behaviours and attitudes which can negatively influence those who see it.',
    kcsie: 'para 160: pornography and misogynistic influencers; para 165 content: pornography',
    verdict: 'FULL',
    modules: ['ks3-14-bodies-image-pressure'],
    evidence: ['pornography', 'carrying that expectation into a real relationship'],
    note: '',
  },
  {
    id: 'RSHE-S-OSA-12', phase: 'secondary', item: 12,
    block: 'Relationships and sex education',
    strand: 'Online safety and awareness',
    text: 'How information and data is generated, collected, shared and used online.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['ks4-15-manipulation-persuasion', 'ks5-20-ai-mastery-data-rights', 'ks3-10-mood-and-screens'],
    evidence: ['profiling', 'the profile is what is actually for sale'],
    note: '',
  },
  {
    id: 'RSHE-S-OSA-13', phase: 'secondary', item: 13,
    block: 'Relationships and sex education',
    strand: 'Online safety and awareness',
    text: 'That websites may share personal data about their users, and information collected on their internet use, for commercial purposes (e.g. to enable targeted advertising).',
    kcsie: 'para 165 contact: commercial advertising; commerce: inappropriate advertising',
    verdict: 'FULL',
    modules: ['ks4-15-manipulation-persuasion', 'ks4-19-readiness-at-16'],
    evidence: ['advertis', 'buy the right to reach the kind of person'],
    note: '',
  },
  {
    id: 'RSHE-S-OSA-14', phase: 'secondary', item: 14,
    block: 'Relationships and sex education',
    strand: 'Online safety and awareness',
    text: 'That criminals can operate online scams, for example using fake websites or emails to extort money or valuable personal information. This information can be used to the detriment of the person or wider society. About risks of sextortion, how to identify online scams relating to sex, and how to seek support if they have been scammed or involved in sextortion.',
    kcsie: 'para 165 commerce: phishing and or financial scams',
    verdict: 'FULL',
    modules: ['ks3-13-scams-fraud-money', 'ks4-17-sextortion'],
    evidence: ['fraud is a criminal offence', 'sextortion'],
    note: '',
  },
  {
    id: 'RSHE-S-OSA-15', phase: 'secondary', item: 15,
    block: 'Relationships and sex education',
    strand: 'Online safety and awareness',
    text: 'That AI chatbots are an example of how AI is rapidly developing, and that these can pose risks by creating fake intimacy or offering harmful advice. It is important to be able to critically think about new types of technology as they appear online and how they might pose a risk.',
    kcsie: 'para 165 contact: harmful online interaction with other users or generative AI applications that simulate this',
    verdict: 'FULL',
    modules: ['ks3-22-when-an-ai-acts-like-a-friend', 'ks5-20-ai-mastery-data-rights', 'ks3-24-is-it-doing-my-thinking'],
    evidence: ['chatbot'],
    note: '',
  },
  {
    id: 'RSHE-S-WO-1', phase: 'secondary', item: 1,
    block: 'Health and wellbeing',
    strand: 'Wellbeing online',
    text: 'About the benefits of limiting time spent online, the risks of excessive time spent on electronic devices and the impact of positive and negative content online on their own and others’ mental and physical wellbeing.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['ks3-10-mood-and-screens'],
    evidence: ['mood audit', 'raw hours'],
    note: '',
  },
  {
    id: 'RSHE-S-WO-2', phase: 'secondary', item: 2,
    block: 'Health and wellbeing',
    strand: 'Wellbeing online',
    text: 'The similarities and differences between the online world and the physical world, including: the impact of unhealthy or obsessive comparison with others online (including through setting unrealistic expectations for body image); how people may curate a specific image of their life online; the impact that an over-reliance on online relationships, including relationships formed through social media, can have.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['ks3-10-mood-and-screens', 'ks3-14-bodies-image-pressure'],
    evidence: ['comparing', 'connecting', 'survive the app closing'],
    note: '',
  },
  {
    id: 'RSHE-S-WO-3', phase: 'secondary', item: 3,
    block: 'Health and wellbeing',
    strand: 'Wellbeing online',
    text: 'How to identify harmful behaviours online (including bullying, abuse or harassment) and how to report, or find support, if they have been affected by those behaviours.',
    kcsie: 'para 165 conduct: online bullying; para 160: the concepts of, and laws relating to all forms of sexual harassment, and abuse, and how to access support',
    verdict: 'FULL',
    modules: ['ks3-27-when-it-turns-on-you', 'ks4-29-did-not-go-looking'],
    evidence: ['name it, save it, say it', 'report and block', 'childline on 0800 1111', 'what helps afterwards'],
    note: '',
  },
  {
    id: 'RSHE-S-WO-4', phase: 'secondary', item: 4,
    block: 'Health and wellbeing',
    strand: 'Wellbeing online',
    text: 'The risks related to online gambling and gambling-like content within gaming, including the accumulation of debt.',
    kcsie: 'para 165 commerce: risks such as online gambling',
    verdict: 'FULL',
    modules: ['ks4-28-the-money-and-the-odds', 'ks2-05-gaming-time-spend'],
    evidence: ['loot box', 'house edge', 'how fast is the loop', 'borrowing'],
    note: '',
  },
  {
    id: 'RSHE-S-WO-5', phase: 'secondary', item: 5,
    block: 'Health and wellbeing',
    strand: 'Wellbeing online',
    text: 'How advertising and information is targeted at them and how to be a discerning consumer of information online, understanding the prevalence of misinformation and disinformation online, including conspiracy theories.',
    kcsie: 'para 165 content: misinformation, disinformation (including fake news) and conspiracy theories',
    verdict: 'FULL',
    modules: ['ks3-12-misinfo-deepfakes', 'ks4-15-manipulation-persuasion'],
    evidence: ['misinformation', 'disinformation', 'conspiracy theory', 'unfalsifiable'],
    note: '',
  },
  {
    id: 'RSHE-S-WO-6', phase: 'secondary', item: 6,
    block: 'Health and wellbeing',
    strand: 'Wellbeing online',
    text: 'The risks of illegal behaviours online, including drug and knife supply or the sale or purchasing of illicit drugs online.',
    kcsie: 'para 165 contact: adults posing as children or young adults with the intention to groom or exploit them for sexual, criminal, financial or other purposes',
    verdict: 'FULL',
    modules: ['ks4-29-did-not-go-looking'],
    evidence: ['county lines', 'supplying drugs is a serious criminal offence', 'knives', 'money out of proportion to the task'],
    note: '',
  },
  {
    id: 'RSHE-S-WO-7', phase: 'secondary', item: 7,
    block: 'Health and wellbeing',
    strand: 'Wellbeing online',
    text: 'The serious risks of viewing online content that promotes self-harm, suicide or violence, including how to safely report this material and how to access support after viewing it.',
    kcsie: 'para 165 content: self-harm, suicide, extreme sexual or physical violence',
    verdict: 'FULL',
    modules: ['ks4-29-did-not-go-looking'],
    evidence: ['self harm content', 'you are not in trouble', 'samaritans on 116 123', 'stop it, report it, say it'],
    note: '',
  },
  {
    id: 'RSHE-P-RKR-9', phase: 'primary', item: 9,
    block: 'Relationships education',
    strand: 'Respectful, kind relationships',
    text: 'The different types of bullying (including online bullying), the impact of bullying, responsibilities of bystanders (primarily reporting bullying to an adult), and how to get help.',
    kcsie: 'para 165 conduct: online bullying',
    verdict: 'FULL',
    modules: ['ks2-08-kind-safe-online'],
    evidence: ['pile on', 'one unkind moment'],
    note: '',
  },
  {
    id: 'RSHE-P-BS-2', phase: 'primary', item: 2,
    block: 'Relationships education',
    strand: 'Being Safe',
    text: 'The concept of privacy and its implications for both children and adults; including that it is not always right to keep secrets if they relate to being safe.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['ks1-02-kind-screens-calm-bodies', 'ks2-07-privacy-reputation'],
    evidence: ['secret'],
    note: '',
  },
  {
    id: 'RSHE-P-BS-4', phase: 'primary', item: 4,
    block: 'Relationships education',
    strand: 'Being Safe',
    text: 'How to respond safely and appropriately to adults they may encounter (in all contexts, including online), including those they do and do not know.',
    kcsie: 'para 165 contact: adults posing as children or young adults with the intention to groom or exploit them',
    verdict: 'FULL',
    modules: ['ks2-07-privacy-reputation'],
    evidence: ['never met', 'asks you to keep the chat secret'],
    note: '',
  },
  {
    id: 'RSHE-P-BS-6', phase: 'primary', item: 6,
    block: 'Relationships education',
    strand: 'Being Safe',
    text: 'How to report abuse, concerns about something seen online or experienced in real life, or feelings of being unsafe or feeling bad about any adult and the vocabulary and confidence needed to do so.',
    kcsie: 'para 160: when and where to seek help',
    verdict: 'FULL',
    modules: ['eyfs-01-screens-kindness', 'ks1-02-kind-screens-calm-bodies', 'ks2-08-kind-safe-online'],
    evidence: ['feel it, name it', 'tell someone who can help'],
    note: '',
  },
  {
    id: 'RSHE-P-GW-7', phase: 'primary', item: 7,
    block: 'Health and wellbeing',
    strand: 'General wellbeing',
    text: 'That bullying (including cyberbullying) has a negative and often lasting impact on mental wellbeing and how to seek help for themselves or others.',
    kcsie: 'para 165 conduct: online bullying',
    verdict: 'FULL',
    modules: ['ks2-08-kind-safe-online'],
    evidence: ['bullying'],
    note: '',
  },
  {
    id: 'RSHE-P-GW-9', phase: 'primary', item: 9,
    block: 'Health and wellbeing',
    strand: 'General wellbeing',
    text: 'Where and how to seek support (including recognising the triggers for seeking support), including who in school they should speak to if they are worried about their own or someone else’s mental wellbeing or ability to control their emotions (including issues arising online).',
    kcsie: 'para 160: when and where to seek help',
    verdict: 'FULL',
    modules: ['eyfs-01-screens-kindness', 'ks1-02-kind-screens-calm-bodies', 'ks2-08-kind-safe-online'],
    evidence: ['trusted grown up', 'will not go away by itself', 'keep it secret', 'whose actual job is this'],
    note: '',
  },
  {
    id: 'RSHE-S-RR-6', phase: 'secondary', item: 6,
    block: 'Relationships and sex education',
    strand: 'Respectful relationships',
    text: 'The different types of bullying (including online bullying), the impact of bullying, the responsibilities of bystanders to report bullying and how and where to get help.',
    kcsie: 'para 165 conduct: online bullying',
    verdict: 'FULL',
    modules: ['ks3-27-when-it-turns-on-you', 'ks2-08-kind-safe-online'],
    evidence: ['bystander', 'the quiet majority is the whole audience', 'bullying is repeated, aimed at one person'],
    note: '',
  },
  {
    id: 'RSHE-S-RR-9', phase: 'secondary', item: 9,
    block: 'Relationships and sex education',
    strand: 'Respectful relationships',
    text: 'How stereotypes, in particular stereotypes based on sex, gender reassignment, race, religion, sexual orientation or disability, can cause damage (e.g. how they might normalise non-consensual behaviour or encourage prejudice). Pupils should be equipped to recognise misogyny and other forms of prejudice.',
    kcsie: 'para 160: stereotyping, prejudice and equality; Annex C records further references to misogyny added in 2026',
    verdict: 'FULL',
    modules: ['ks4-18-radicalisation-misogyny'],
    evidence: ['misogyn', 'runs on race, on religion, on disability', 'a stereotype repeated often enough'],
    note: '',
  },
  {
    id: 'RSHE-S-RR-11', phase: 'secondary', item: 11,
    block: 'Relationships and sex education',
    strand: 'Respectful relationships',
    text: 'How pornography can negatively influence sexual attitudes and behaviours, including by normalising harmful sexual behaviours and by disempowering some people, especially women, to feel a sense of autonomy over their own body and providing some people with a sense of sexual entitlement to the bodies of others.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['ks3-14-bodies-image-pressure'],
    evidence: ['pornography', 'as though another person owes them something'],
    note: '',
  },
  {
    id: 'RSHE-S-RR-12', phase: 'secondary', item: 12,
    block: 'Relationships and sex education',
    strand: 'Respectful relationships',
    text: 'Pupils should have an opportunity to discuss how some sub-cultures might influence our understanding of sexual ethics, including the sexual norms endorsed by so-called “involuntary celibates” (incels) or online influencers.',
    kcsie: 'para 160: misogynistic influencers',
    verdict: 'FULL',
    modules: ['ks4-18-radicalisation-misogyny', 'ks4-15-manipulation-persuasion'],
    evidence: ['incel', 'attraction is a ranking'],
    note: '',
  },
  {
    id: 'RSHE-S-BS-1', phase: 'secondary', item: 1,
    block: 'Relationships and sex education',
    strand: 'Being Safe',
    text: 'How to recognise, respect and communicate consent and boundaries in relationships, including in early romantic relationships (in all contexts, including online) and early sexual relationships that might involve kissing or touching. That kindness and care for others requires more than just consent.',
    kcsie: 'para 160: boundaries, consent and kindness in relationships',
    verdict: 'FULL',
    modules: ['ks4-16-consent-images-law'],
    evidence: ['freely given, specific, ongoing', 'never only about images', 'exactly the same in a room and on a phone'],
    note: '',
  },
  {
    id: 'RSHE-S-BS-2', phase: 'secondary', item: 2,
    block: 'Relationships and sex education',
    strand: 'Being Safe',
    text: 'That there are a range of strategies for identifying, resisting and understanding pressure in relationships from peers or others, including sexual pressure, and how to avoid putting pressure on others.',
    kcsie: '',
    verdict: 'FULL',
    modules: ['ks4-17-sextortion', 'ks4-15-manipulation-persuasion'],
    evidence: ['naming the technique', 'pressure is asking again after a no', 'read your own messages'],
    note: '',
  },
  {
    id: 'RSHE-S-BS-6', phase: 'secondary', item: 6,
    block: 'Relationships and sex education',
    strand: 'Being Safe',
    text: 'That sexual harassment includes unsolicited sexual language / attention / touching, taking and/or sharing intimate or sexual images without consent, public sexual harassment, pressuring other people to do sexual things, and upskirting.',
    kcsie: 'para 160: what constitutes sexual harassment and sexual violence and why these are always unacceptable, emphasising that it is never the fault of the person experiencing it',
    verdict: 'FULL',
    modules: ['ks4-16-consent-images-law'],
    evidence: ['under 18', 'upskirting', 'sexual harassment'],
    note: '',
  },
  {
    id: 'RSHE-S-BS-11', phase: 'secondary', item: 11,
    block: 'Relationships and sex education',
    strand: 'Being Safe',
    text: 'The concepts and laws relating to harms which are exploitative, including sexual exploitation, criminal exploitation and abuse, grooming, and financial exploitation.',
    kcsie: 'para 165 contact: adults posing as children or young adults with the intention to groom or exploit them for sexual, criminal, financial or other purposes',
    verdict: 'FULL',
    modules: ['ks4-17-sextortion', 'ks4-29-did-not-go-looking'],
    evidence: ['sextortion', 'exploitation is somebody getting something out of you', 'grooming is the part that comes first', 'the law calls that exploitation'],
    note: '',
  },
  {
    id: 'RSHE-S-BS-16', phase: 'secondary', item: 16,
    block: 'Relationships and sex education',
    strand: 'Being Safe',
    text: 'How to seek support for their own worrying or abusive behaviour or for worrying or abusive behaviour they have experienced from others, including information on where to report abuse, and where to seek medical attention when required, for example after an assault.',
    kcsie: 'para 160: how to access support; and when and where to seek help',
    verdict: 'FULL',
    modules: ['ks4-16-consent-images-law', 'ks4-17-sextortion'],
    evidence: ['not my fault', 'Report Remove', 'the same door opens the other way round', 'if it is your own behaviour worrying you', 'a gp, or 111, or a and e'],
    note: '',
  },
  {
    id: 'RSHE-S-PS-2', phase: 'secondary', item: 2,
    block: 'Health and wellbeing',
    strand: 'Personal safety',
    text: 'How to recognise and manage peer influence in relation to risk-taking behaviour and personal safety, including peer influence online and on social media.',
    kcsie: 'para 165 contact: peer-to-peer pressure',
    verdict: 'FULL',
    modules: ['ks3-12-misinfo-deepfakes', 'ks4-15-manipulation-persuasion', 'ks3-11-social-workarounds'],
    evidence: ['everyone else'],
    note: '',
  },
  {
    id: 'RSHE-S-PS-6', phase: 'secondary', item: 6,
    block: 'Health and wellbeing',
    strand: 'Personal safety',
    text: 'The risks and signs that they may be at risk of grooming or exploitation, and how to seek help where there is a concern.',
    kcsie: 'para 165 contact: adults posing as children or young adults with the intention to groom or exploit them',
    verdict: 'FULL',
    modules: ['ks4-17-sextortion', 'ks4-18-radicalisation-misogyny', 'ks3-22-when-an-ai-acts-like-a-friend'],
    evidence: ['groom', 'it moves fast, it moves private'],
    note: '',
  },
  {
    id: 'RSHE-S-MW-8', phase: 'secondary', item: 8,
    block: 'Health and wellbeing',
    strand: 'Mental wellbeing',
    text: 'That gambling can lead to serious mental health harms, including anxiety, depression, and suicide, and that some gambling products are more likely to cause these harms than others.',
    kcsie: 'para 165 commerce: risks such as online gambling',
    verdict: 'FULL',
    modules: ['ks4-28-the-money-and-the-odds'],
    evidence: ['linked with anxiety and with depression', 'what it does to a person', '0808 8020 133', 'speed is what the law acts on'],
    note: '',
  },
]

/** Counts, computed rather than written down, so a page cannot print a number
 *  the array does not support. */
export const RSHE_2026_COUNTS = {
  full: RSHE_2026.filter(r => r.verdict === 'FULL').length,
  partial: RSHE_2026.filter(r => r.verdict === 'PARTIAL').length,
  gap: RSHE_2026.filter(r => r.verdict === 'GAP').length,
  byDesign: RSHE_2026.filter(r => r.verdict === 'BY_DESIGN').length,
  total: RSHE_2026.length,
}

/** The requirements still to close. The ratchet in
 *  scripts/check-rshe-coverage.mjs holds this number down and never lets it
 *  rise, which is the whole point of writing the audit as a guard. */
export const RSHE_2026_OUTSTANDING = RSHE_2026.filter(
  r => r.verdict === 'PARTIAL' || r.verdict === 'GAP',
)

export function requirementsFor(moduleId: string): Rshe2026Requirement[] {
  return RSHE_2026.filter(r => r.modules.includes(moduleId))
}
