-- Guided Childhood: the curriculum matrix
-- Run AFTER 017_lesson_slides.sql.
-- Nine strands (the eight UKCIS Education for a Connected World strands plus
-- AI safety) by five stages, seeded as titled stubs in both audiences. Stubs
-- carry status 'stub' and are hidden from the hub until their slides land on
-- Days 4 and 5; existing lessons stay 'live'. The Explorer information strand
-- slot is already covered by the live algorithm lesson from 017, so it is
-- tagged rather than duplicated. The 013 placeholder seeds keep a null strand
-- until they are absorbed or replaced during the writing days.

alter table public.lessons add column if not exists strand text;
alter table public.lessons add column if not exists status text not null default 'live'
  check (status in ('live', 'stub'));
alter table public.ai_lessons add column if not exists strand text;

update public.lessons
  set strand = 'information'
  where title = 'How the algorithm decides what your child sees';

insert into public.lessons (stage_id, audience, strand, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, category) 
select v.stage_id, v.audience, v.strand, v.title, v.the_idea, v.why_it_matters, v.try_this, v.key_message, v.digi_prompt, v.sort_order, v.status, v.strand
from (values
('foundation', 'parent', 'identity', 'Me on a screen and me in real life', 'Knowing the difference between a picture of a thing and the thing itself.',
 'How children see themselves is shaped by what screens reflect back. This strand keeps the real self in charge of the online one.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Knowing the difference between a picture of a thing and the thing itself.', 'My child is 4 to 7. Help me with the lesson topic: Me on a screen and me in real life.', 500, 'stub'),
('builder', 'parent', 'identity', 'Your first avatar', 'Choosing what we show about ourselves in games and apps, and what we keep back.',
 'How children see themselves is shaped by what screens reflect back. This strand keeps the real self in charge of the online one.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Choosing what we show about ourselves in games and apps, and what we keep back.', 'My child is 8 to 10. Help me with the lesson topic: Your first avatar.', 500, 'stub'),
('explorer', 'parent', 'identity', 'Filters are not faces', 'Seeing how edited images work so they stop setting the standard for real ones.',
 'How children see themselves is shaped by what screens reflect back. This strand keeps the real self in charge of the online one.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Seeing how edited images work so they stop setting the standard for real ones.', 'My child is 11 to 13. Help me with the lesson topic: Filters are not faces.', 500, 'stub'),
('shaper', 'parent', 'identity', 'Who are you online?', 'Running different accounts while staying one honest person.',
 'How children see themselves is shaped by what screens reflect back. This strand keeps the real self in charge of the online one.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Running different accounts while staying one honest person.', 'My child is 13 to 15. Help me with the lesson topic: Who are you online?.', 500, 'stub'),
('independent', 'parent', 'identity', 'Your identity is yours to write', 'Presenting yourself for adult life, from group chats to first job applications.',
 'How children see themselves is shaped by what screens reflect back. This strand keeps the real self in charge of the online one.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Presenting yourself for adult life, from group chats to first job applications.', 'My child is 16 plus. Help me with the lesson topic: Your identity is yours to write.', 500, 'stub'),
('foundation', 'parent', 'relationships', 'Kind words on screens', 'Speaking to people through a screen the way you would face to face.',
 'Connection is the strongest protective factor in all the research. This strand teaches warmth, boundaries and judgement with people through screens.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Speaking to people through a screen the way you would face to face.', 'My child is 4 to 7. Help me with the lesson topic: Kind words on screens.', 500, 'stub'),
('builder', 'parent', 'relationships', 'Friends you know and friends you do not', 'Telling the difference between a real friend online and a stranger who plays one.',
 'Connection is the strongest protective factor in all the research. This strand teaches warmth, boundaries and judgement with people through screens.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Telling the difference between a real friend online and a stranger who plays one.', 'My child is 8 to 10. Help me with the lesson topic: Friends you know and friends you do not.', 500, 'stub'),
('explorer', 'parent', 'relationships', 'Group chats without the drama', 'Muting, leaving and standing up for someone kindly.',
 'Connection is the strongest protective factor in all the research. This strand teaches warmth, boundaries and judgement with people through screens.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Muting, leaving and standing up for someone kindly.', 'My child is 11 to 13. Help me with the lesson topic: Group chats without the drama.', 500, 'stub'),
('shaper', 'parent', 'relationships', 'Relationships, pressure and phones', 'Recognising pressure in private messages and knowing consent applies online.',
 'Connection is the strongest protective factor in all the research. This strand teaches warmth, boundaries and judgement with people through screens.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Recognising pressure in private messages and knowing consent applies online.', 'My child is 13 to 15. Help me with the lesson topic: Relationships, pressure and phones.', 500, 'stub'),
('independent', 'parent', 'relationships', 'Meeting people from the internet', 'Moving an online connection into real life safely, like an adult.',
 'Connection is the strongest protective factor in all the research. This strand teaches warmth, boundaries and judgement with people through screens.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Moving an online connection into real life safely, like an adult.', 'My child is 16 plus. Help me with the lesson topic: Meeting people from the internet.', 500, 'stub'),
('foundation', 'parent', 'reputation', 'The internet remembers', 'Understanding that what goes on a screen can stay there.',
 'What goes online stays reachable. This strand builds the habit of thinking in years, not minutes.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Understanding that what goes on a screen can stay there.', 'My child is 4 to 7. Help me with the lesson topic: The internet remembers.', 500, 'stub'),
('builder', 'parent', 'reputation', 'Think before you post', 'The five second check before anything is sent or shared.',
 'What goes online stays reachable. This strand builds the habit of thinking in years, not minutes.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'The five second check before anything is sent or shared.', 'My child is 8 to 10. Help me with the lesson topic: Think before you post.', 500, 'stub'),
('explorer', 'parent', 'reputation', 'Your digital footprint is already real', 'Searching yourself and understanding what is already out there.',
 'What goes online stays reachable. This strand builds the habit of thinking in years, not minutes.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Searching yourself and understanding what is already out there.', 'My child is 11 to 13. Help me with the lesson topic: Your digital footprint is already real.', 500, 'stub'),
('shaper', 'parent', 'reputation', 'Reputation and the long game', 'Reading your own posts the way a sixth form, a coach or an employer will.',
 'What goes online stays reachable. This strand builds the habit of thinking in years, not minutes.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Reading your own posts the way a sixth form, a coach or an employer will.', 'My child is 13 to 15. Help me with the lesson topic: Reputation and the long game.', 500, 'stub'),
('independent', 'parent', 'reputation', 'Owning your online record', 'Auditing, cleaning up and deliberately building the record you want found.',
 'What goes online stays reachable. This strand builds the habit of thinking in years, not minutes.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Auditing, cleaning up and deliberately building the record you want found.', 'My child is 16 plus. Help me with the lesson topic: Owning your online record.', 500, 'stub'),
('foundation', 'parent', 'bullying', 'When screens make you sad', 'Telling a grown up every time something on a screen feels bad.',
 'Every child will see unkindness online. This strand makes sure they know what to do, whether it lands on them or someone else.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Telling a grown up every time something on a screen feels bad.', 'My child is 4 to 7. Help me with the lesson topic: When screens make you sad.', 500, 'stub'),
('builder', 'parent', 'bullying', 'Mean messages', 'What to do, what not to do, and who to tell when messages turn unkind.',
 'Every child will see unkindness online. This strand makes sure they know what to do, whether it lands on them or someone else.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'What to do, what not to do, and who to tell when messages turn unkind.', 'My child is 8 to 10. Help me with the lesson topic: Mean messages.', 500, 'stub'),
('explorer', 'parent', 'bullying', 'Bystander or upstander', 'Breaking a group chat pile on instead of feeding it.',
 'Every child will see unkindness online. This strand makes sure they know what to do, whether it lands on them or someone else.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Breaking a group chat pile on instead of feeding it.', 'My child is 11 to 13. Help me with the lesson topic: Bystander or upstander.', 500, 'stub'),
('shaper', 'parent', 'bullying', 'Screenshots, shame and standing firm', 'Surviving public embarrassment online and helping someone else survive theirs.',
 'Every child will see unkindness online. This strand makes sure they know what to do, whether it lands on them or someone else.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Surviving public embarrassment online and helping someone else survive theirs.', 'My child is 13 to 15. Help me with the lesson topic: Screenshots, shame and standing firm.', 500, 'stub'),
('independent', 'parent', 'bullying', 'Calling it out safely', 'Supporting a target without becoming one, and knowing when to report instead.',
 'Every child will see unkindness online. This strand makes sure they know what to do, whether it lands on them or someone else.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Supporting a target without becoming one, and knowing when to report instead.', 'My child is 16 plus. Help me with the lesson topic: Calling it out safely.', 500, 'stub'),
('foundation', 'parent', 'information', 'Real or pretend?', 'Spotting the difference between stories, adverts and true things on a screen.',
 'Feeds are built to hold attention, not to tell the truth. This strand teaches how information really reaches us and how to check it.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Spotting the difference between stories, adverts and true things on a screen.', 'My child is 4 to 7. Help me with the lesson topic: Real or pretend?.', 500, 'stub'),
('builder', 'parent', 'information', 'Adverts are everywhere', 'Noticing when something on a screen is trying to sell you something.',
 'Feeds are built to hold attention, not to tell the truth. This strand teaches how information really reaches us and how to check it.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Noticing when something on a screen is trying to sell you something.', 'My child is 8 to 10. Help me with the lesson topic: Adverts are everywhere.', 500, 'stub'),
('shaper', 'parent', 'information', 'Deepfakes and doctored truth', 'Verifying before believing or sharing, because seeing is no longer proof.',
 'Feeds are built to hold attention, not to tell the truth. This strand teaches how information really reaches us and how to check it.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Verifying before believing or sharing, because seeing is no longer proof.', 'My child is 13 to 15. Help me with the lesson topic: Deepfakes and doctored truth.', 500, 'stub'),
('independent', 'parent', 'information', 'Your news diet', 'Building an information diet you chose on purpose instead of one chosen for you.',
 'Feeds are built to hold attention, not to tell the truth. This strand teaches how information really reaches us and how to check it.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Building an information diet you chose on purpose instead of one chosen for you.', 'My child is 16 plus. Help me with the lesson topic: Your news diet.', 500, 'stub'),
('foundation', 'parent', 'wellbeing', 'Screens, sleep and growing bodies', 'Why screens live outside the bedroom from the very start.',
 'Sleep, mood and movement are where screens bite first. This strand builds routines that protect all three without a daily fight.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Why screens live outside the bedroom from the very start.', 'My child is 4 to 7. Help me with the lesson topic: Screens, sleep and growing bodies.', 500, 'stub'),
('builder', 'parent', 'wellbeing', 'The cool down lap', 'Ending screen time without a meltdown, every time.',
 'Sleep, mood and movement are where screens bite first. This strand builds routines that protect all three without a daily fight.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Ending screen time without a meltdown, every time.', 'My child is 8 to 10. Help me with the lesson topic: The cool down lap.', 500, 'stub'),
('explorer', 'parent', 'wellbeing', 'Mood and the scroll', 'Noticing what the feed does to how you feel, and acting on it.',
 'Sleep, mood and movement are where screens bite first. This strand builds routines that protect all three without a daily fight.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Noticing what the feed does to how you feel, and acting on it.', 'My child is 11 to 13. Help me with the lesson topic: Mood and the scroll.', 500, 'stub'),
('shaper', 'parent', 'wellbeing', 'Sleep is not optional', 'Keeping nine hours a night when the phone wants them all.',
 'Sleep, mood and movement are where screens bite first. This strand builds routines that protect all three without a daily fight.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Keeping nine hours a night when the phone wants them all.', 'My child is 13 to 15. Help me with the lesson topic: Sleep is not optional.', 500, 'stub'),
('independent', 'parent', 'wellbeing', 'Designing your own digital life', 'Choosing habits on purpose before university and work choose them for you.',
 'Sleep, mood and movement are where screens bite first. This strand builds routines that protect all three without a daily fight.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Choosing habits on purpose before university and work choose them for you.', 'My child is 16 plus. Help me with the lesson topic: Designing your own digital life.', 500, 'stub'),
('foundation', 'parent', 'privacy', 'My privacy shield', 'Knowing what we never tell a screen: name, school, address, passwords.',
 'Personal information is valuable and children give it away without knowing. This strand builds the privacy shield early and keeps it growing.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Knowing what we never tell a screen: name, school, address, passwords.', 'My child is 4 to 7. Help me with the lesson topic: My privacy shield.', 500, 'stub'),
('builder', 'parent', 'privacy', 'Passwords are secrets', 'Making strong passwords and understanding why they are never shared.',
 'Personal information is valuable and children give it away without knowing. This strand builds the privacy shield early and keeps it growing.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Making strong passwords and understanding why they are never shared.', 'My child is 8 to 10. Help me with the lesson topic: Passwords are secrets.', 500, 'stub'),
('explorer', 'parent', 'privacy', 'Location, cameras and microphones', 'Knowing what your phone shares without asking and turning it off.',
 'Personal information is valuable and children give it away without knowing. This strand builds the privacy shield early and keeps it growing.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Knowing what your phone shares without asking and turning it off.', 'My child is 11 to 13. Help me with the lesson topic: Location, cameras and microphones.', 500, 'stub'),
('shaper', 'parent', 'privacy', 'Scams aimed at teenagers', 'Recognising sextortion, fake offers and pressure tactics, and what to do next.',
 'Personal information is valuable and children give it away without knowing. This strand builds the privacy shield early and keeps it growing.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Recognising sextortion, fake offers and pressure tactics, and what to do next.', 'My child is 13 to 15. Help me with the lesson topic: Scams aimed at teenagers.', 500, 'stub'),
('independent', 'parent', 'privacy', 'Your data, your accounts, your money', 'Securing an adult digital life before it holds anything worth stealing.',
 'Personal information is valuable and children give it away without knowing. This strand builds the privacy shield early and keeps it growing.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Securing an adult digital life before it holds anything worth stealing.', 'My child is 16 plus. Help me with the lesson topic: Your data, your accounts, your money.', 500, 'stub'),
('foundation', 'parent', 'ownership', 'Someone made that', 'Understanding that pictures, songs and games belong to the people who made them.',
 'Everything online was made by someone. This strand teaches respect for other peoples work and pride in your own.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Understanding that pictures, songs and games belong to the people who made them.', 'My child is 4 to 7. Help me with the lesson topic: Someone made that.', 500, 'stub'),
('builder', 'parent', 'ownership', 'Copying and creating', 'Using other peoples work fairly and starting to make your own.',
 'Everything online was made by someone. This strand teaches respect for other peoples work and pride in your own.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Using other peoples work fairly and starting to make your own.', 'My child is 8 to 10. Help me with the lesson topic: Copying and creating.', 500, 'stub'),
('explorer', 'parent', 'ownership', 'Remix culture', 'Memes, edits and giving credit where credit is due.',
 'Everything online was made by someone. This strand teaches respect for other peoples work and pride in your own.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Memes, edits and giving credit where credit is due.', 'My child is 11 to 13. Help me with the lesson topic: Remix culture.', 500, 'stub'),
('shaper', 'parent', 'ownership', 'Your work has value', 'Protecting what you make and post, because it is worth something.',
 'Everything online was made by someone. This strand teaches respect for other peoples work and pride in your own.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Protecting what you make and post, because it is worth something.', 'My child is 13 to 15. Help me with the lesson topic: Your work has value.', 500, 'stub'),
('independent', 'parent', 'ownership', 'Creating and getting paid', 'Ownership, licensing and earning from what you make online.',
 'Everything online was made by someone. This strand teaches respect for other peoples work and pride in your own.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Ownership, licensing and earning from what you make online.', 'My child is 16 plus. Help me with the lesson topic: Creating and getting paid.', 500, 'stub'),
('foundation', 'parent', 'ai_safety', 'Some voices are not people', 'Knowing that assistants and characters are tools, not friends.',
 'AI will be the water this generation swims in. This strand teaches what it is, what it is not, and how to use it to grow rather than shrink.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Knowing that assistants and characters are tools, not friends.', 'My child is 4 to 7. Help me with the lesson topic: Some voices are not people.', 500, 'stub'),
('builder', 'parent', 'ai_safety', 'What is a robot brain?', 'Understanding that AI learns from examples, and gets things wrong.',
 'AI will be the water this generation swims in. This strand teaches what it is, what it is not, and how to use it to grow rather than shrink.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Understanding that AI learns from examples, and gets things wrong.', 'My child is 8 to 10. Help me with the lesson topic: What is a robot brain?.', 500, 'stub'),
('explorer', 'parent', 'ai_safety', 'AI companions and real friends', 'Feeling the pull of an AI that always agrees, and keeping it in its place.',
 'AI will be the water this generation swims in. This strand teaches what it is, what it is not, and how to use it to grow rather than shrink.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Feeling the pull of an AI that always agrees, and keeping it in its place.', 'My child is 11 to 13. Help me with the lesson topic: AI companions and real friends.', 500, 'stub'),
('shaper', 'parent', 'ai_safety', 'Using AI to learn, not to skip learning', 'Homework, honesty and using AI to get stronger instead of weaker.',
 'AI will be the water this generation swims in. This strand teaches what it is, what it is not, and how to use it to grow rather than shrink.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Homework, honesty and using AI to get stronger instead of weaker.', 'My child is 13 to 15. Help me with the lesson topic: Using AI to learn, not to skip learning.', 500, 'stub'),
('independent', 'parent', 'ai_safety', 'Building with AI', 'Moving from user to maker: prompting, judgement and the changing world of work.',
 'AI will be the water this generation swims in. This strand teaches what it is, what it is not, and how to use it to grow rather than shrink.',
 'The full lesson with its video is on the way. Ask DiGi to walk you through this topic today.',
 'Moving from user to maker: prompting, judgement and the changing world of work.', 'My child is 16 plus. Help me with the lesson topic: Building with AI.', 500, 'stub')
) as v(stage_id, audience, strand, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status)
on conflict do nothing;

-- The school voice: every parent stub exists as a teacher stub too. Slides
-- and the materials layer differ when written; the topic spine is shared.
insert into public.lessons (stage_id, audience, strand, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, category)
select stage_id, 'teacher', strand, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, category
from public.lessons
where status = 'stub' and audience = 'parent'
on conflict do nothing;
