-- Guided Childhood — Migration 074
-- Rosenshine format family lessons, one exemplar per stage, built on the
-- interactive slide player (017/031/032) at the rigour of the school
-- curriculum (033): starter recall, small step teaching with a spoken script,
-- guided practice, an independent prove it check (multiple choice with
-- feedback on every option), and the DiGi close. Grounded in the UK
-- Education for a Connected World framework, Catherine Knibbs (the nervous
-- system and safety lens) and Dr Becky Kennedy (connection first, the child
-- is good inside). Difficulty rises with the stage: two option choices at 4,
-- subtle four option judgement calls by 16. No dashes in any copy.
--
-- Idempotent: each insert is guarded by title, so this can run twice with no
-- duplicates. Dashboard safe: flat statements, dollar quoted JSON.

set lock_timeout = '3s';

-- ── Stage 1, Foundation (4 to 7) · Safe online ──────────────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'foundation', 'parent', 'safety', 'The stop and tell rule',
  'When something on a screen feels funny in your tummy, you stop, and you tell a grown up. That is the whole rule, and it works because telling never gets you in trouble.',
  'Children who trust that telling is safe, tell. Children who fear losing the screen, hide. The single strongest early protection is a child who comes to you.',
  'Practise the rule away from screens first. Ask: if a picture made your tummy feel funny, what would you do? Celebrate the answer like a goal.',
  'Stop, and tell a grown up. Telling is always safe.',
  'How do I teach my young child to come to me when something online upsets them?',
  910, 'live',
  $s1$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Foundation · Ages 4 to 7 · Safe online","title":"The stop and tell rule","body":"A sofa lesson for you and your child together. One rule, practised until it is easy.","script":"Sit together somewhere comfy. Say: we are going to learn our family's most important screen rule. It is tiny. It fits in two words."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can stop and tell a grown up when a screen makes me feel funny inside.","why":"Screens sometimes show us things that give us a funny feeling in our tummy. That feeling is a helper. It tells us to go and find our grown up.","gains":["I know what the funny tummy feeling means","I know telling never gets me in trouble","I can say the rule out loud"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🛑","heading":"Your tummy is a helper","body":"Sometimes a picture or a video feels wrong. Maybe scary, maybe just strange. Your body notices first, a funny feeling in your tummy. That feeling is not naughty. It is your body being clever.","script":"Ask your child: where do you feel it in your body when something is scary or strange? Tummy, chest, throat, any answer is right. Say: that feeling is your helper. When it comes, we do two things."},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"💛","heading":"Stop, then tell","body":"Step one: stop looking. Put the screen down or look away. Step two: tell your grown up. You will never ever be in trouble for telling. Not even if you tapped something. Not even if it was a mistake.","script":"This is the Dr Becky line, say it slowly: even if you tapped it, even if you were somewhere you should not have been, telling me is always the right choice, and I will always be glad you told me."},
    {"type":"choice","phase":"practise","minutes":2,"question":"A video pops up and it makes your tummy feel funny. What do you do first?","options":[{"text":"Stop looking and put the screen down","correct":true,"feedback":"Yes. Stop first, every time. Your tummy told you, and you listened."},{"text":"Keep watching to see what happens","correct":false,"feedback":"The funny feeling means stop. We do not need to see what happens next. Stopping is the brave move."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"You tapped something by accident and now the screen shows something strange. If you tell your grown up, what happens?","options":[{"text":"I get in trouble for tapping","correct":false,"feedback":"Never. In this family, telling is always safe, even after a mistake."},{"text":"My grown up is glad I told them, and they help","correct":true,"feedback":"Exactly right. Telling is always safe, and helping is our job, not telling off."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Stop, and tell a grown up.","Your tummy is a helper.","Telling is always safe in this family."]}
  ]$s1$::jsonb
where not exists (select 1 from public.lessons where title = 'The stop and tell rule');

-- ── Stage 2, Builder (8 to 10) · Healthy balance ────────────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'builder', 'parent', 'screen_habits', 'Why stopping feels hard, and how to win at it',
  'Stopping a screen feels bad because the body is mid reward, not because the child is defiant. A warning, a finish point and a next thing make the off switch painless.',
  'The research is consistent: transitions, not total minutes, are where the battles live. A child who can stop calmly at 9 has the core skill the algorithm will test at 13.',
  'Agree the finish point before the screen goes on: one more episode, one more level. Let a timer be the messenger so you stay the ally.',
  'Stopping is a skill. We practise it while the stakes are small.',
  'My child melts down every time screen time ends. What actually helps?',
  920, 'live',
  $s2$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Builder · Ages 8 to 10 · Healthy balance","title":"Why stopping feels hard, and how to win at it","body":"A ten minute lesson for you and your child, about what happens in your body when a screen goes off.","script":"Start with the recall question from the last lesson: what is our family screen rule when something feels wrong? Stop and tell. Today is about a different kind of stopping."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can stop a screen calmly, because I know why it feels hard and I have a plan.","why":"Stopping feels genuinely uncomfortable. That is not you being bad. It is your brain mid game. Knowing that is half the win.","gains":["I know why the end of screen time feels bad in my body","I have my own finish point plan","I know what to do the moment the timer goes"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🧠","heading":"Your brain mid game","body":"Games and videos hand your brain little rewards, over and over. When the screen stops, the rewards stop suddenly, and everything else feels flat and slow for a few minutes. Your body can feel cross, even when nothing is wrong.","script":"Knibbs framing, child sized: it is like being woken from a dream mid story. The cross feeling is real, it is chemistry, and it passes in a few minutes on its own. Naming this together takes the shame out of it."},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🏁","heading":"The finish point trick","body":"Stopping mid level feels the worst. So we choose the finish point before we start: one more episode, the end of this level, the next save point. Then the timer is just the reminder of the deal we already made together.","script":"Agree it out loud each time: what is our finish point today? The child names it, you confirm it. Ownership is what turns the timer from an enemy into a referee."},
    {"type":"choice","phase":"practise","minutes":2,"question":"The timer goes but you are halfway through a level. What is the strong move?","options":[{"text":"Ignore the timer, the level matters more","correct":false,"feedback":"The deal was made before the screen went on. Halfway through a level is exactly why we picked a finish point first."},{"text":"Finish at the save point you agreed, then stop","correct":true,"feedback":"That is the plan working. You picked the finish point, you landed it. That is what strong looks like."},{"text":"Ask for ten more minutes","correct":false,"feedback":"Asking every time slowly breaks the deal. The finish point was yours. Landing it is the win."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"Why does the end of screen time feel bad in your body?","options":[{"text":"Because parents make it bad","correct":false,"feedback":"It is not anyone's fault. It is what a brain does when little rewards stop suddenly."},{"text":"Because the little rewards stop suddenly and the feeling passes in a few minutes","correct":true,"feedback":"Exactly. It is chemistry, not naughtiness, and it fades on its own if you let it."},{"text":"Because screens are bad for you","correct":false,"feedback":"Screens are not the villain. It is the sudden stop that stings, and a finish point softens it."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["The cross feeling after a screen is chemistry, and it passes.","Pick the finish point before you start.","Stopping is a skill, and you are getting good at it."]}
  ]$s2$::jsonb
where not exists (select 1 from public.lessons where title = 'Why stopping feels hard, and how to win at it');

-- ── Stage 3, Explorer (11 to 13) · AI and chatbots ──────────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'explorer', 'parent', 'chatbots and ai', 'The feed is built to hold you',
  'A feed is not a window, it is a machine that watches what you linger on and serves more of it. Once a child can see the machine, they can stop being run by it.',
  'Orben and Odgers place ages 11 to 13 as the sensitive window: the age when the algorithm arrives and the age when abstract thinking can finally understand it. Teaching it now is exactly on time.',
  'Open a feed together and play spot the hook: why was THIS video chosen for you? Guess the signal it read. Make the machine visible, together.',
  'The feed learns you. Your move is knowing that it is learning.',
  'How do I explain the algorithm to my 12 year old without lecturing?',
  930, 'live',
  $s3$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Explorer · Ages 11 to 13 · AI and chatbots","title":"The feed is built to hold you","body":"Fifteen minutes together on the machine behind every feed, and how to be the one holding the controls.","script":"Starter recall: what did we learn about why stopping feels hard? The rewards stop suddenly. Today: who decides which rewards your feed serves you in the first place?"},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can explain how a recommendation algorithm chooses what I see, and name one signal it reads from me.","why":"Every scroll trains a machine that exists to keep you scrolling. Understanding it is the difference between using a feed and being used by one.","gains":["I can say what an algorithm optimises for","I can name the signals it reads from me","I can catch it steering me in real time"]},
    {"type":"concept","phase":"teach","minutes":3,"emoji":"⚙️","heading":"The machine has one job","body":"The feed's only goal is your watch time. It reads signals: what you pause on, replay, like, even how long you hover. Then it serves more of whatever held you. It does not know if that content is good for you. It only knows it held you.","script":"Small step check before moving on: ask them to name two signals the machine reads. Pause on, replay, hover, like, share. Any two. Rosenshine rule: do not move on until this lands."},
    {"type":"scenario","phase":"teach","minutes":3,"label":"Evidence","platform":"feed","handle":"fitspiration.daily","avatar":"💪","meta":"Suggested for you","text":"They will not tell you this but skipping breakfast is how the top athletes stay lean. Day 4 of my water only mornings!","image":"🏃","stats":"❤ 89.2K   ↻ 41K   💬 12K","prompt":"You paused on one gym video yesterday. Why is THIS in your feed today, and what happens if you pause on it too?","script":"Let them answer before you do. The machine read one pause as interest, and this post is the test. Pause again and tomorrow there are five of them. This is how a feed drifts dark without anyone choosing it."},
    {"type":"choice","phase":"practise","minutes":2,"question":"You notice your feed has filled with videos that make you feel bad about your body. What is actually happening?","options":[{"text":"The app knows this content is important for me","correct":false,"feedback":"The machine has no idea what is good for you. It only measured that this content held your attention."},{"text":"I paused on content like this, and the machine served more","correct":true,"feedback":"Exactly. It read your pause as a vote. The machine is doing its one job: watch time."},{"text":"Everyone gets shown the same videos","correct":false,"feedback":"No two feeds are the same. Yours is built from your signals, which is exactly why it feels so personal."},{"text":"It is random","correct":false,"feedback":"Nothing in a feed is random. Every slot is an experiment the machine is running on you."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"What is the single thing every feed algorithm is optimising for?","options":[{"text":"Showing you the truth","correct":false,"feedback":"Truth is not a signal it can read. Holding you is."},{"text":"Your watch time","correct":true,"feedback":"That is the whole machine. Everything else follows from it."},{"text":"Your happiness","correct":false,"feedback":"If misery holds you longer than happiness, the machine serves misery. It cannot tell the difference."},{"text":"What your friends like","correct":false,"feedback":"Friends are one signal, but the target is your watch time, not their taste."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["The feed learns you from every pause.","It optimises for watch time, not for you.","See the machine, and you hold the controls."]}
  ]$s3$::jsonb
where not exists (select 1 from public.lessons where title = 'The feed is built to hold you');

-- ── Stage 4, Shaper (13 to 15) · Social media ready ─────────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'shaper', 'parent', 'social media', 'The footprint test',
  'Everything posted is a footprint: copyable, searchable, and older than the mood it was posted in. The test before posting is one question: would I stand behind this in two years?',
  'At 13 to 15 the stakes become real: friendship groups, first platforms, a searchable name. Judgement built now is what monitored access is for.',
  'Do the search together: their name, your name. Talk about what a stranger would think. Not as a scare, as an audit you run as a team.',
  'Post like it is permanent, because it is.',
  'My 14 year old posts without thinking. How do I build the pause?',
  940, 'live',
  $s4$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Shaper · Ages 13 to 15 · Social media ready","title":"The footprint test","body":"Fifteen minutes on the one question that should sit between a thought and a post.","script":"Starter recall: what does the feed optimise for? Watch time. Today flips the camera: what does the feed learn about you from what YOU post?"},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can run the footprint test before I post, and explain why deleting does not really delete.","why":"A post outlives the mood it was made in. Screenshots, caches and other people's saves mean the delete button is a hope, not a tool.","gains":["I can explain why deleted is not gone","I can run the two year test on a real post","I know what a stranger reads from my profile"]},
    {"type":"concept","phase":"teach","minutes":3,"emoji":"👣","heading":"Deleted is not gone","body":"The moment a post is up, it can be screenshotted, cached, saved and forwarded. Deleting removes your copy, not the copies. That is not a reason to post nothing. It is the reason to post like every post is permanent.","script":"Check for understanding before moving on: ask them to explain in their own words why the delete button is weaker than it looks. Wait for the screenshot answer."},
    {"type":"scenario","phase":"teach","minutes":3,"label":"Evidence","platform":"message","handle":"group chat · 14 people","avatar":"😂","text":"omg post that video of Jay falling in PE he will find it hilarious","image":"📱","prompt":"Jay is not in this chat. Run the footprint test on this post, for you and for Jay.","script":"Two footprints here: the poster's and Jay's. Jay never chose this. The two year test fails twice. Let them find both before you point them out. This is Knibbs territory: consent is part of safety."},
    {"type":"choice","phase":"practise","minutes":2,"question":"A post is funny today but you are not sure about it. What is the footprint test?","options":[{"text":"Would my friends like it right now?","correct":false,"feedback":"Right now is the mood talking. The test looks further out."},{"text":"Would I stand behind this in two years, in front of anyone?","correct":true,"feedback":"That is the test. Two years, any audience: a coach, an employer, Jay's mum."},{"text":"Can I delete it later if it goes wrong?","correct":false,"feedback":"Delete removes your copy, not the screenshots. The test happens before, not after."},{"text":"Will it get likes?","correct":false,"feedback":"Likes measure the machine's interest, not your judgement."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"A friend wants to post a video of someone who does not know it exists. What is the real issue?","options":[{"text":"Nothing, if it is funny","correct":false,"feedback":"Funny to the room is not consent from the person. Their footprint is being written without them."},{"text":"The person has not consented, and the post writes their footprint for them","correct":true,"feedback":"Exactly. Consent is part of online safety, both directions: what you share of others is their permanent record too."},{"text":"It might not get many views","correct":false,"feedback":"Views are not the issue. Consent and permanence are."},{"text":"The video quality","correct":false,"feedback":"The issue is the person in it never chose to be posted."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Deleted is not gone.","Two years, any audience: that is the test.","Other people's footprints are yours to protect too."]}
  ]$s4$::jsonb
where not exists (select 1 from public.lessons where title = 'The footprint test');

-- ── Stage 5, Independent (16 plus) · AI and what is real ────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'independent', 'parent', 'deepfakes and ai', 'Real, fake and AI made',
  'AI can now fake a face, a voice and a news clip well enough to beat instinct. Verification is a habit, not a talent: source, corroboration, motive.',
  'At 16 the training wheels are off. The last skill the pathway hands over is the one adults are still learning: assume nothing is real until it survives three checks.',
  'Pick one viral clip this week and run the three checks together as equals. You are not teaching now, you are comparing notes.',
  'Trust is earned by checking, not by looking real.',
  'How do I talk to my 16 year old about deepfakes without sounding paranoid?',
  950, 'live',
  $s5$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Independent · 16 plus · AI and what is real","title":"Real, fake and AI made","body":"The last lesson on the road: verification as a reflex, for a world where seeing is no longer believing.","script":"This one is a conversation between adults. Recall the whole road in one line each: stop and tell, the finish point, the machine behind the feed, the footprint test. This lesson is the graduation: nothing on a screen is real until it survives checking."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can run source, corroboration and motive on any clip before I believe or share it.","why":"AI generated video and voice now beat human instinct in controlled tests. The people who stay grounded are not better spotters. They are better checkers.","gains":["I can name the three checks","I can explain why instinct fails against AI fakes","I check before I share, every time"]},
    {"type":"concept","phase":"teach","minutes":3,"emoji":"🧪","heading":"Instinct lost. Method wins.","body":"Looking closely at pixels is a losing game: the fakes improve monthly. The three checks do not age. Source: who published this first? Corroboration: is anyone reputable reporting the same thing? Motive: who benefits if I believe this?","script":"Small step check: three checks, from memory. Source, corroboration, motive. Then the hard truth: a fake that flatters what you already believe is the one that gets through. Motive includes YOUR motive to believe it."},
    {"type":"scenario","phase":"teach","minutes":3,"label":"Evidence","platform":"feed","handle":"breaking.newsfeed","avatar":"🚨","meta":"14 min ago · Shared 214,000 times","text":"LEAKED: audio of the health secretary admitting the new policy is a cover up. Listen before it is taken down!","image":"🎧","stats":"❤ 412K   ↻ 214K   💬 88K","prompt":"Run the three checks on this post, out loud, before your thumb does anything.","script":"Source: an account called breaking.newsfeed is not a source. Corroboration: fourteen minutes and no newsroom has it? Motive: listen before it is taken down is urgency engineering, and 214,000 shares is proof it works. The clip may even be real. The point is you do not know yet, and sharing is vouching."},
    {"type":"choice","phase":"practise","minutes":2,"question":"A voice clip of a politician says something outrageous. It sounds exactly like them. What settles whether it is real?","options":[{"text":"How authentic the voice sounds","correct":false,"feedback":"Voice cloning passed the sounds real bar years ago. Your ear is not the instrument."},{"text":"Whether reputable outlets independently confirm it","correct":true,"feedback":"Corroboration is the strongest single check. Real events leave multiple independent trails."},{"text":"How many people have shared it","correct":false,"feedback":"Share counts measure how well it spreads, and fakes are engineered to spread."},{"text":"Whether it matches what you already suspected about them","correct":false,"feedback":"That is exactly the fake most likely to get through you. Your priors are the attack surface."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"Why is sharing an unverified clip worse than just believing it privately?","options":[{"text":"It is not, sharing is neutral","correct":false,"feedback":"Sharing is vouching. Your name travels with the clip to people who trust you."},{"text":"Because your share is an endorsement that spends your credibility and fuels the machine","correct":true,"feedback":"Exactly. Every share is your reputation lent to a stranger's clip, and a signal that spreads it further."},{"text":"Because you might get in legal trouble","correct":false,"feedback":"Occasionally true, but the everyday cost is your credibility and everyone downstream of it."},{"text":"Because it uses your data allowance","correct":false,"feedback":"The cost is trust, not megabytes."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Seeing is no longer believing. Checking is.","Source, corroboration, motive.","This is the last stamp: you are the verification now."]}
  ]$s5$::jsonb
where not exists (select 1 from public.lessons where title = 'Real, fake and AI made');
