-- Guided Childhood — Migration 076
-- Lesson library fill: 15 new Rosenshine format family lessons extending the
-- five exemplars in 074, so every stage covers its age appropriate literacy
-- strands. Foundation and Builder complete safe plus balance with an extra
-- lesson each. Explorer, Shaper and Independent gain the three strands 074
-- did not give them, so all four strands are covered from Explorer up.
-- Grounded in the UK Education for a Connected World framework, Catherine
-- Knibbs (nervous system and safety lens) and Dr Becky Kennedy (connection
-- first, telling is always safe). Difficulty rises with stage: two option
-- choices at Foundation, three at Builder, four with subtle distractors from
-- Explorer up. No dashes in any copy.
--
-- Idempotent: each insert is guarded by title, so this can run twice with no
-- duplicates. Dashboard safe: flat statements, dollar quoted JSON.

set lock_timeout = '3s';

-- ════════════════════════════════════════════════════════════════════════════
-- STAGE 1 · FOUNDATION (4 to 7)
-- ════════════════════════════════════════════════════════════════════════════

-- ── Foundation · Healthy balance ─────────────────────────────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'foundation', 'parent', 'screen_habits', 'When the screen goes to sleep',
  'Little children do not end screen time, the ritual ends it for them. A gentle warning, a goodbye to the screen and a next thing to run to turn the hardest moment of the day into a routine.',
  'At 4 to 7 the thinking brain that manages stopping is still under construction. Every calm ending rehearsed now is a deposit in the skill they will need when the stakes are bigger.',
  'Give a five minute whisper before the end, let your child wave goodbye to the screen, and have the next thing ready: a snack, a job, a game. The goodbye does the heavy lifting.',
  'Warn, wave goodbye, move on to the next thing.',
  'How do I end screen time for my 5 year old without tears?',
  960, 'live',
  $f1$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Foundation · Ages 4 to 7 · Healthy balance","title":"When the screen goes to sleep","body":"A sofa lesson about endings. We practise saying goodbye to the screen so the goodbye stops being scary.","script":"Recall first: what is our stop and tell rule? Stop, and tell a grown up. Today is a different kind of goodbye: how we say bye bye to the screen when it is time."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can say goodbye to the screen calmly when my grown up gives the whisper.","why":"Endings feel big when they are a surprise. Our plan makes the ending small: a whisper, a wave, a next thing.","gains":["I know what the five minute whisper means","I can wave goodbye to the screen","I know the next thing comes straight after"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"📣","heading":"The five minute whisper","body":"Big feelings come when the screen stops suddenly. So we never stop suddenly. Your grown up gives a quiet whisper: five more minutes. Your body gets time to get ready for the ending.","script":"Do the whisper the same way every time, low and warm, never a warning shot. This is the Dr Becky framing: you are not taking something away, you are walking them to the ending so they never meet it alone."},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"👋","heading":"Wave goodbye, then run to the next thing","body":"When time is up, we wave and say bye bye screen, see you tomorrow. Then we go straight to the next thing: a snack, a story, a job helping your grown up. Endings are easier when something nice is waiting.","script":"The wave sounds silly and works like magic: it gives the ending a shape. Have the next thing genuinely ready before the wave happens. A child running toward something is not fighting what they left."},
    {"type":"choice","phase":"practise","minutes":2,"question":"The whisper has happened and now the timer says the screen is done. What do we do?","options":[{"text":"Wave bye bye to the screen and go to the next thing","correct":true,"feedback":"Yes. The wave finishes it, and the next thing is waiting for you."},{"text":"Hold the screen tight and look away from your grown up","correct":false,"feedback":"Holding tight makes the goodbye bigger and slower. The wave makes it small and quick."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"Why does the five minute whisper help your body?","options":[{"text":"It gives my body time to get ready for the ending","correct":true,"feedback":"Exactly. No surprise, no storm. Your body had time to get ready."},{"text":"It means I get extra screen time","correct":false,"feedback":"The whisper is not extra time. It is a kind warning that the ending is coming."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["A whisper, a wave, a next thing.","Endings are easier when nothing is a surprise.","Bye bye screen, see you tomorrow."]}
  ]$f1$::jsonb
where not exists (select 1 from public.lessons where title = 'When the screen goes to sleep');

-- ── Foundation · Safe online (extra) ─────────────────────────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'foundation', 'parent', 'safety', 'Who is behind the screen',
  'Games and videos are full of people your child has never met. The lesson at this age is simple: screen people are strangers, we keep our special information private, and if anyone talks to us we come and show a grown up.',
  'Young children assume a friendly voice is a friend. The Education for a Connected World framework starts online relationships here: knowing that people online may not be who they say they are.',
  'Play the who knows you game: who knows your name? Grandma, your teacher, your friends. Does the person in the game know you? No. So we do not tell them our name.',
  'Screen people are strangers. Come and show me if anyone talks to you.',
  'How do I explain online strangers to a 6 year old without frightening them?',
  961, 'live',
  $f2$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Foundation · Ages 4 to 7 · Safe online","title":"Who is behind the screen","body":"A sofa lesson about the people inside games and videos, and what we keep just for the people we really know.","script":"Recall: what does your tummy do when something feels wrong on a screen? It gives you the funny feeling, and we stop and tell. Today we learn about the people on the other side of the screen."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can keep my special information private and show my grown up if anyone talks to me online.","why":"People in games can sound like friends. Knowing who really knows us keeps our special information safe.","gains":["I know screen people are strangers","I know what my special information is","I know to come and show my grown up"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🧸","heading":"Friendly is not the same as known","body":"People in games and videos can sound kind and funny. But we have never met them. They are strangers, even when they feel like friends. Strangers do not get our name, our school or where we live.","script":"Keep the tone light, not scary. Knibbs is clear that fear shuts learning down. The message is not that people online are bad. It is simply: we do not know them, so we keep our special information for people we know in real life."},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🫱","heading":"Come and show me","body":"If anyone in a game or an app says hello, asks a question or wants to be your friend, you do not have to answer. You come and show your grown up. Showing is always safe, and you will never be in trouble.","script":"This is the stop and tell rule wearing new clothes. Same promise, said slowly: whoever it is, whatever they said, showing me is always the right move, and I will always be glad you did."},
    {"type":"choice","phase":"practise","minutes":2,"question":"Someone in your game says: hi! What is your name? What do you do?","options":[{"text":"Tell them, because they sound friendly","correct":false,"feedback":"Friendly voices can still be strangers. Our name is special information for people we know in real life."},{"text":"Do not answer, and go and show your grown up","correct":true,"feedback":"Perfect. You do not have to answer anyone. Showing your grown up is always the right move."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"You showed your grown up a message from a stranger. What happens next?","options":[{"text":"They are glad you showed them, and they help","correct":true,"feedback":"Exactly. Showing is always safe in this family, and helping is our job."},{"text":"You lose the game as a punishment","correct":false,"feedback":"Never. Showing us never costs you the game. That promise is what keeps you safe."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Screen people are strangers, even friendly ones.","Your name and your home are special information.","Come and show me. Showing is always safe."]}
  ]$f2$::jsonb
where not exists (select 1 from public.lessons where title = 'Who is behind the screen');

-- ── Foundation · Healthy balance (extra) ─────────────────────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'foundation', 'parent', 'wellbeing', 'Big feelings and the screen',
  'Screens stir up big feelings in small bodies: fizzy, cross, wobbly. This lesson gives those feelings names, because a feeling with a name is a feeling a child can hand to you.',
  'Catherine Knibbs puts the nervous system at the centre: children do not calm down by being told to, they calm down next to a calm adult. Naming feelings together is the practice run.',
  'After screen time today, ask: how does your body feel, fizzy, wobbly or calm? No lesson attached, just the question. You are building the habit of noticing together.',
  'Every feeling is allowed. Naming it is how we tame it.',
  'My young child comes off the tablet cross and wobbly. What is going on and what do I do?',
  962, 'live',
  $f3$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Foundation · Ages 4 to 7 · Healthy balance","title":"Big feelings and the screen","body":"A sofa lesson about the feelings screens leave behind, and what we do with them together.","script":"Recall: what do we do when the screen goes to sleep? A whisper, a wave, a next thing. Today we talk about the feelings that sometimes arrive after the wave."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can name how my body feels after screens and bring big feelings to my grown up.","why":"Feelings are easier to handle when they have names and a helper.","gains":["I know fizzy, wobbly and calm","I know every feeling is allowed","I know where to bring a big feeling"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🌊","heading":"Fizzy, wobbly, calm","body":"Screens can make your body feel fizzy like a shaken bottle, or wobbly like jelly, or lovely and calm. All of those are allowed. Feelings are visitors. They come, we name them, and they go.","script":"Give the three words a home: fizzy for revved up, wobbly for upset, calm for settled. Children cannot say I am dysregulated, but every 5 year old can say I feel fizzy. That word is a gift to both of you."},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🤝","heading":"Bring the feeling to me","body":"When a big feeling comes after screens, you do not have to fix it on your own. Bring it to your grown up: I feel fizzy. Sitting close to a calm grown up helps your body find calm again. That is how bodies work.","script":"This is Knibbs made practical: children borrow our calm before they can build their own. So the deal is on you too. Take the breath first, then receive the feeling. A fizzy child plus a fizzy adult is just a bigger bottle of fizz."},
    {"type":"choice","phase":"practise","minutes":2,"question":"The tablet is away and your body feels like a shaken fizzy bottle. What do you do with that feeling?","options":[{"text":"Bring it to your grown up and say: I feel fizzy","correct":true,"feedback":"Yes. A named feeling is halfway to a calm one, and calm is easier next to your grown up."},{"text":"Hide it, because cross feelings are naughty","correct":false,"feedback":"No feeling is naughty. Every feeling is allowed, and bringing it to us is always right."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"What helps a wobbly body find calm again?","options":[{"text":"Being told to calm down right now","correct":false,"feedback":"Bodies do not calm down on command. They calm down next to someone calm."},{"text":"Sitting close to a calm grown up","correct":true,"feedback":"Exactly. Little bodies borrow calm from big ones. That is how it works."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Fizzy, wobbly or calm, every feeling is allowed.","A named feeling is a tamed feeling.","Bring your feelings to your grown up, always."]}
  ]$f3$::jsonb
where not exists (select 1 from public.lessons where title = 'Big feelings and the screen');

-- ════════════════════════════════════════════════════════════════════════════
-- STAGE 2 · BUILDER (8 to 10)
-- ════════════════════════════════════════════════════════════════════════════

-- ── Builder · Safe online ────────────────────────────────────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'builder', 'parent', 'safety', 'What we keep private online',
  'By 8 to 10 children type into games, chats and search boxes every week. This lesson draws the line once and clearly: some information is private, and private means it never goes into a screen.',
  'A full name, a school badge, a street name and a photo can be pieced together like a jigsaw. Children this age share by accident, not by choice. The fix is a clear list, not a vague warning.',
  'Make your family private list together and stick it near the computer: full name, school, address, phone number, passwords, photos in uniform. Six things, one rule: these never go into a screen.',
  'Private information never goes into a screen. Not to anyone, not for anything.',
  'What personal information rules does my 9 year old actually need?',
  963, 'live',
  $b1$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Builder · Ages 8 to 10 · Safe online","title":"What we keep private online","body":"A ten minute lesson on the jigsaw problem, and the six things that never go into a screen.","script":"Starter recall: what do screen people count as, even the friendly ones? Strangers. Today we learn exactly what strangers must never get from us, and why small clues matter."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can name what belongs on our private list and keep every piece out of the screen.","why":"Strangers build pictures from small clues. Guarding each clue keeps the whole picture safe.","gains":["I can say what counts as private information","I can spot a jigsaw piece before it goes in","I know what to do when anything asks for the list"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🧩","heading":"The jigsaw problem","body":"One clue on its own seems safe. Your first name here, your school jumper there, your street in the background of a photo. But clues add up like jigsaw pieces, and a stranger can put the picture together. That is why we protect every piece.","script":"This is the Education for a Connected World privacy strand at this age: not stranger danger, but information literacy. Try the jigsaw out loud: what could someone learn from your username plus your profile photo plus one comment? Children are genuinely surprised, and surprise is what makes it stick."},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"📋","heading":"The private list","body":"Our private list: full name, school, address, phone number, passwords, and photos that show where you live or learn. If a game, an app, a quiz or a person asks for anything on the list, the answer is the same: no, and then tell your grown up.","script":"The power of a list is that nobody has to judge in the moment. A quiz asking for your first pet and your street name is not fun, it is a password harvest. If it is on the list, it stays out of the screen, and asking a grown up is always free."},
    {"type":"choice","phase":"practise","minutes":2,"question":"A fun quiz in a game asks for your full name and your school to show your results. What do you do?","options":[{"text":"Fill it in, quizzes are just for fun","correct":false,"feedback":"Two items from the private list in one go. That quiz is collecting, not playing."},{"text":"Skip those boxes, close it and tell your grown up","correct":true,"feedback":"Exactly right. List items never go in, and telling us means we can check what that quiz was really doing."},{"text":"Put in a nickname but your real school","correct":false,"feedback":"The nickname is smart, but the school is still a jigsaw piece. Nothing on the list goes in."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"Why do we protect small clues like a school jumper in a photo?","options":[{"text":"Because small clues add up like jigsaw pieces","correct":true,"feedback":"That is it. No single piece matters. The finished jigsaw does."},{"text":"Because photos are not allowed at this age","correct":false,"feedback":"Photos are fine. It is what a photo quietly reveals that we check for."},{"text":"Because schools ask us to","correct":false,"feedback":"Some do, but the real reason is the jigsaw: clues combine into a picture of where you are."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Private information never goes into a screen.","Small clues make a big jigsaw.","When anything asks for the list, the answer is no, then tell."]}
  ]$b1$::jsonb
where not exists (select 1 from public.lessons where title = 'What we keep private online');

-- ── Builder · Safe online (extra) ────────────────────────────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'builder', 'parent', 'online_risks', 'Spot the trick',
  'Free coins, you have won, click before the timer runs out. Tricks online follow patterns, and an 8 year old can learn to spot the patterns faster than any filter can block them.',
  'Scams aimed at children borrow the language of games: prizes, timers, levels. A child who can name the three tells, rushing, promising and asking, has a defence that travels to every new app.',
  'Make trick spotting a family sport. When an advert or pop up appears, ask: is it rushing us, promising us, or asking us? First one to name the tell wins.',
  'Rushing, promising, asking. Three tells, one move: stop and check with a grown up.',
  'How do I teach my 8 year old to spot online scams and tricks?',
  964, 'live',
  $b2$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Builder · Ages 8 to 10 · Safe online","title":"Spot the trick","body":"A ten minute lesson that turns your child into a trick spotter, one pattern at a time.","script":"Starter recall: what is on our private list? Let them name a few. Today we meet the messages that try to trick that information out of us, and learn their three tells."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can spot the three tells of a trick and stop and check with a grown up.","why":"Tricks are built to beat quick fingers. Spotting the pattern beats the trick.","gains":["I can name rushing, promising and asking","I can spot a tell in a real pop up","I know deciding is a job we do together"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🪤","heading":"Tricks have tells","body":"A trick is a message built to make you tap before you think. Tricks have three tells. Rushing: only 10 seconds left! Promising: free coins, you have won! Asking: just enter your password. Real games do not need any of those.","script":"Rosenshine check: have your child say the three tells back to you before you go on. Rushing, promising, asking. Then hunt one example together in an app you both know. Found in the wild beats explained on the sofa."},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🛑","heading":"The stop and check move","body":"When you spot a tell, you do not have to work out if it is really a trick. That is not your job. Your move is stop and check: hands off the screen, fetch your grown up, look at it together. Checking is never wasted, even when it turns out fine.","script":"Notice what this does: it removes the judgement burden from the child. They do not decide trick or treat, they just spot a tell and escalate. Praise every check, even false alarms, especially false alarms. The habit is the win, not the verdict."},
    {"type":"choice","phase":"practise","minutes":2,"question":"A pop up says: FREE ROBUX! Only 30 seconds left! Enter your password to claim. How many tells can you spot?","options":[{"text":"One tell: it is rushing me","correct":false,"feedback":"Keep counting. The timer rushes you, the free Robux is a promise, and the password box is asking. All three."},{"text":"All three tells: rushing, promising and asking","correct":true,"feedback":"Full marks. A message with all three tells is a trick wearing a costume. Stop and check."},{"text":"No tells, free Robux offers are real","correct":false,"feedback":"Nobody gives away Robux for a password. Free plus a timer plus a password box is the full trick pattern."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"You spot one tell but you are not sure it is really a trick. Whose job is it to decide?","options":[{"text":"Yours, you should work it out before bothering anyone","correct":false,"feedback":"Working it out alone is exactly what tricks hope for. Spotting is your job, deciding is ours."},{"text":"Nobody needs to decide, just tap it and see what happens","correct":false,"feedback":"Tapping to find out is how tricks win. The tell is enough reason to stop."},{"text":"Your grown up decides, your job is to spot and fetch","correct":true,"feedback":"Exactly. You spot the tell, we decide together. Checking is never wasted."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Rushing, promising, asking. Know the three tells.","You spot, we decide, together.","A check is never wasted, even when it is a false alarm."]}
  ]$b2$::jsonb
where not exists (select 1 from public.lessons where title = 'Spot the trick');

-- ── Builder · Healthy balance (extra) ────────────────────────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'builder', 'parent', 'wellbeing', 'Screens and sleep',
  'Sleep is where growing, learning and mood repair happen, and screens in the last hour push it later two ways: light that tells the brain it is daytime, and content that is simply more interesting than sleep.',
  'The evidence on children, screens and sleep is stronger than the evidence on almost anything else. Protecting the hour before bed and the bedroom overnight buys more than any other single boundary.',
  'Move every screen out of the bedroom tonight and set a family charging spot in the kitchen, your phone included. The hour before bed becomes books, baths, chat, anything but screens.',
  'Screens sleep in the kitchen. The last hour belongs to winding down.',
  'How much does screen use before bed really affect my 9 year old, and what should our rule be?',
  965, 'live',
  $b3$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Builder · Ages 8 to 10 · Healthy balance","title":"Screens and sleep","body":"A ten minute lesson on the two ways screens steal sleep, and the family rule that stops both.","script":"Starter recall: why does stopping a screen feel hard in your body? The little rewards stop suddenly. Today: what those same screens do to sleep, and the rule that protects it."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can explain why screens push sleep later and follow our family charging spot rule.","why":"Sleep does the growing, the learning and the mood repair. Protecting it is the best deal in this whole course.","gains":["I know what melatonin does","I know the two ways screens delay sleep","I know our last hour and charging spot plan"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🌙","heading":"Your brain has a light switch","body":"When it gets dark, your brain starts making a sleepiness helper called melatonin. Bright screens close to your face tell your brain the sun is still up, so the helper arrives late, and sleep comes late with it.","script":"The science lands well at this age: children love knowing the word melatonin. The second thief is quieter: interesting content keeps the brain revved even after the screen is off. Light plus excitement is why the last hour matters more than total minutes."},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🔌","heading":"The charging spot","body":"Our family rule has two parts. Screens live at the charging spot overnight, not in bedrooms. And the last hour before bed is screen free: books, baths, building, chatting. Grown ups follow the rule too, because brains all work the same way.","script":"The parent phone in the kitchen is the whole ballgame. Knibbs would say children learn regulation from what we do, not what we say. If your phone sleeps beside you, expect this lesson to wash off by Thursday."},
    {"type":"choice","phase":"practise","minutes":2,"question":"It is 8pm, bed is at half past, and you really want one more episode. What is the strong move?","options":[{"text":"Watch it, one episode cannot hurt","correct":false,"feedback":"It is not the minutes, it is the timing. Light and excitement in the last half hour push sleep late."},{"text":"Screen away at the charging spot, pick a book or a chat instead","correct":true,"feedback":"That is the rule working. The last stretch before bed belongs to winding down, and sleep comes easier for it."},{"text":"Watch it with the brightness turned right down","correct":false,"feedback":"Dimming helps a little with light, but the excitement still revs your brain. The last hour is for winding down."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"Why do screens push sleep later?","options":[{"text":"Bright light delays the sleepiness helper, and exciting content keeps the brain revved","correct":true,"feedback":"Both thieves named. Light delays melatonin, excitement keeps the engine running."},{"text":"Because screens use electricity near your bed","correct":false,"feedback":"Electricity is not the problem. Light in your eyes and excitement in your brain are."},{"text":"They do not, sleep only depends on how tired you are","correct":false,"feedback":"Even a tired brain waits for the sleepiness helper, and bright screens hold it back."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Your brain has a light switch. Screens hold it open.","Screens sleep in the kitchen, every screen in the house.","The last hour belongs to winding down."]}
  ]$b3$::jsonb
where not exists (select 1 from public.lessons where title = 'Screens and sleep');

-- ════════════════════════════════════════════════════════════════════════════
-- STAGE 3 · EXPLORER (11 to 13)
-- ════════════════════════════════════════════════════════════════════════════

-- ── Explorer · Safe online ───────────────────────────────────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'explorer', 'parent', 'safety', 'When the group chat turns',
  'Group chats are where friendship and cruelty happen at this age, often in the same hour. This lesson covers the pile on: how chats turn, what a bystander can do, and why screenshots plus telling beat deleting and hoping.',
  'By 11 to 13 most online harm arrives through peers, not strangers. The Education for a Connected World bullying strand says children need strategies before the moment, because in the moment the pull to join or stay silent is enormous.',
  'Ask which group chats they are in and who runs them, with curiosity, not audit energy. Then agree the family plan: screenshot, do not reply, come and tell. Rehearse it before it is needed.',
  'You do not have to join in, and you never have to handle a nasty chat alone.',
  'My 12 year old is in group chats that sometimes turn nasty. What do I teach them?',
  966, 'live',
  $e1$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Explorer · Ages 11 to 13 · Safe online","title":"When the group chat turns","body":"Fifteen minutes on pile ons: how they start, what your silence says, and the third door out.","script":"Starter recall: what is the one thing the feed optimises for? Watch time. Group chats run on a cousin of the same fuel: reactions. Today, what happens when the reactions turn on one person."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can recognise a pile on starting and use the plan: no fuel, private support, tell an adult.","why":"In the moment, joining in or going quiet are the easy doors. Having a plan makes the third door possible.","gains":["I can explain how a chat turns on someone","I know what my silence says in a pile on","I can run screenshot, do not reply, tell"]},
    {"type":"concept","phase":"teach","minutes":3,"emoji":"🌀","heading":"How a chat turns","body":"A pile on rarely starts evil. One joke about someone, a few laughing reactions, and the chat learns that mocking gets attention. Each message alone feels small. Together they flatten someone. The person being flattened sees every single one.","script":"The mechanism matters more than the morality here. The chat rewards whatever gets reactions, the same loop as the feed. Ask: have you ever seen a chat turn on someone? Then listen. This lesson goes best the day it is abstract, and lands hardest the day it is not."},
    {"type":"scenario","phase":"teach","minutes":3,"label":"Evidence","platform":"message","handle":"year 7 group · 23 people","avatar":"😬","text":"look at maya's answer in class today 💀💀 someone screenshot it, this is too good","image":"📱","prompt":"You are in this chat. Maya is not. Name three things you could do next, and what each one costs.","script":"Walk the three doors. Join in: cheapest now, Maya pays. Stay silent: feels neutral, reads as approval, the pile on counts your silence. Or the third door: no reaction, message Maya privately, tell an adult if it continues. The third door costs the most courage and is the only one you will not regret."},
    {"type":"choice","phase":"practise","minutes":2,"question":"The chat starts on Maya. You do not want to pile on, but leaving feels dramatic. What is the strongest first move?","options":[{"text":"Send one small laughing emoji so you do not stand out","correct":false,"feedback":"Small to send, not small to Maya. Reactions are fuel, and she sees every one."},{"text":"No reaction at all, then message Maya privately to check she is okay","correct":true,"feedback":"That is the third door. No fuel for the pile on, real support where it counts."},{"text":"Post a long message telling everyone off","correct":false,"feedback":"Brave, but a public showdown often just makes you the next target. Private support plus an adult beats a solo stand."},{"text":"Leave the chat instantly without a word","correct":false,"feedback":"Leaving protects you, which is fine, but it leaves Maya alone in there. Check on her first."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"The chat keeps going for days and it is getting worse. Why is screenshot and tell better than delete and hope?","options":[{"text":"Because screenshots get more likes later","correct":false,"feedback":"Screenshots here are evidence, not content. They are for an adult, never for reposting."},{"text":"Because deleting the chat deletes the problem","correct":false,"feedback":"Deleting cleans your screen, not the situation. Maya is still in it, and so is the pattern."},{"text":"Because evidence lets an adult actually act, and telling means nobody handles it alone","correct":true,"feedback":"Exactly. Screenshots turn your word into proof, and telling turns a lonely problem into a handled one."},{"text":"Because adults enjoy reading group chats","correct":false,"feedback":"No adult enjoys it. But acting without evidence is guesswork, and the screenshots close that gap."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Silence in a pile on reads as applause.","Take the third door: no fuel, private support, tell an adult.","Screenshot, do not reply, come and tell."]}
  ]$e1$::jsonb
where not exists (select 1 from public.lessons where title = 'When the group chat turns');

-- ── Explorer · Healthy balance ───────────────────────────────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'explorer', 'parent', 'screen_habits', 'Built to be bottomless',
  'Feeds scroll forever and episodes start themselves because endings were removed on purpose. Once a child sees the missing endings, they can build their own, which is the whole skill.',
  'At 11 to 13 devices move into pockets and bedrooms, and the design pressure gets personal. A child who knows autoplay and infinite scroll are company choices stops reading their own overuse as personal failure.',
  'Count endings together: watch what happens when a video finishes. What does the app do next, and what would it look like if the app was on your side? Then turn autoplay off together.',
  'The endings were removed on purpose. Build your own.',
  'How do I help my 12 year old manage endless scrolling and autoplay?',
  967, 'live',
  $e2$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Explorer · Ages 11 to 13 · Healthy balance","title":"Built to be bottomless","body":"Fifteen minutes on why feeds never end, and how to put the full stops back in yourself.","script":"Starter recall: what does the feed optimise for? Watch time. Today we look at the most powerful watch time trick of all: removing the moment where stopping would happen."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can explain why feeds have no endings and install my own stopping points.","why":"Autoplay and infinite scroll removed the natural exits. Knowing that turns self blame into design.","gains":["I can name two bottomless design tricks","I can say why stopping mid scroll feels hard","I can set up one ending of my own"]},
    {"type":"concept","phase":"teach","minutes":3,"emoji":"🕳️","heading":"The missing full stop","body":"Books end. Films end. Feeds and autoplay never end, because an ending is a moment you might leave. Designers call it frictionless. The next video loads before the choice to stop can even form. Nothing about that is your weakness. It is their design.","script":"This flips the shame story, which is the real work of the lesson. Bottomless design is watch time engineering. The message is not that screens are bad. It is: the exit signs were unscrewed on purpose, so we install our own."},
    {"type":"scenario","phase":"teach","minutes":3,"label":"Evidence","platform":"feed","handle":"your feed · nearly midnight","avatar":"🌙","meta":"Up next in 3, 2...","text":"You opened the app to watch one video. That was 40 minutes ago. The next one is already loading.","image":"📱","stats":"Autoplay: on   Timer: none","prompt":"Find the exact moment a choice was taken from you, and where you could put an ending back.","script":"The countdown is the moment: the app made continuing the default and stopping the effort. Endings you can install: autoplay off, a timer that closes the app, the phone charging outside the bedroom at night. Any one of the three would have ended this scroll at video one."},
    {"type":"choice","phase":"practise","minutes":2,"question":"You want to actually stop after one episode tonight. Which plan works with your brain rather than against it?","options":[{"text":"Rely on willpower in the moment","correct":false,"feedback":"Willpower fights the countdown at its strongest moment. The design beats raw effort most nights."},{"text":"Turn autoplay off before you start, so stopping is the default","correct":true,"feedback":"Exactly. You moved the decision to before the pull started. Now continuing takes effort instead of stopping."},{"text":"Watch with the sound off so it is less fun","correct":false,"feedback":"The hook is the next thing loading, not the volume. Kill the countdown, not the sound."},{"text":"Promise yourself you will stop after two instead","correct":false,"feedback":"Moving the line mid scroll is the scroll winning slowly. Endings work when they are set before you start."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"Why does knowing about bottomless design actually change anything?","options":[{"text":"It does not, knowing changes nothing","correct":false,"feedback":"Knowing moves the story from I am weak to it is built that way, and that is the difference between shame and strategy."},{"text":"Because seeing the design lets you stop blaming yourself and start installing your own endings","correct":true,"feedback":"That is it. You cannot fix what you think is a character flaw. You can absolutely outdesign an app."},{"text":"Because apps stop being fun once you understand them","correct":false,"feedback":"They stay fun. The goal was never less fun. It is you choosing the ending instead of the countdown choosing it."},{"text":"Because understanding autoplay turns it off automatically","correct":false,"feedback":"The setting does not know what you know. Understanding is step one, the settings change is step two."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Feeds have no full stops. That is a choice they made.","Install your own endings before you start.","It was never your weakness. It was always their design."]}
  ]$e2$::jsonb
where not exists (select 1 from public.lessons where title = 'Built to be bottomless');

-- ── Explorer · Social media ready ────────────────────────────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'explorer', 'parent', 'social media', 'Followers are not friends',
  'The first years on social platforms teach a quiet lie: that follower counts measure worth and highlight reels show real lives. This lesson unpicks both before they set.',
  'Ages 11 to 13 sit in the comparison window: identity forms exactly while the feed serves everyone else at their best as a measuring stick. Research places this window at the centre of the risk.',
  'Do the maths together on a favourite account: how long might that ten second clip have taken to film, edit and choose? Then ask the better question: who could you actually call on a bad day?',
  'A follower count measures reach. Friends are the people who show up.',
  'My 12 year old is obsessed with followers and compares themselves to influencers. What do I say?',
  968, 'live',
  $e3$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Explorer · Ages 11 to 13 · Social media ready","title":"Followers are not friends","body":"Fifteen minutes on highlight reels, follower counts, and the difference between reach and friendship.","script":"Starter recall: how does the feed choose what you see? It reads your signals and serves what holds you. Today: what those posts do to how you feel about your own life."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can explain what a highlight reel is and what a follower count does and does not measure.","why":"Comparing a real life to chosen highlights is a rigged game. Seeing the rig is the protection.","gains":["I can explain why feeds look better than life","I can say what a follower count measures","I can name the people who would actually show up"]},
    {"type":"concept","phase":"teach","minutes":3,"emoji":"🎭","heading":"The highlight reel","body":"Nobody posts their ordinary Tuesday. A feed is thousands of best moments stitched together, then shown to you while you live your whole real life, including the boring bits. Comparing your inside to everyone else at their best is a game nobody wins.","script":"Make it concrete with their own posts: did you post the day nothing happened? Neither does anyone else. The Dr Becky move here is naming the feeling without banning the app: it makes sense that the feed makes you feel behind. Everyone is comparing their backstage to a thousand front stages."},
    {"type":"scenario","phase":"teach","minutes":3,"label":"Evidence","platform":"feed","handle":"issy.summer","avatar":"✨","meta":"Suggested for you","text":"best summer everrr 🌊 so lucky to have the best people around me","image":"🏖️","stats":"❤ 2,431   💬 187","prompt":"What do you actually know about this summer from this post? List what the photo cannot tell you.","script":"The honest answer is almost nothing: one chosen moment from perhaps hundreds of photos. You cannot see the argument on the way home, the friend who was not invited, the caption rewritten five times. Not because issy is lying, but because posts are highlights by design."},
    {"type":"choice","phase":"practise","minutes":2,"question":"Scrolling before bed, every life looks better than yours and your chest goes tight. What is actually happening?","options":[{"text":"You are seeing proof that everyone is happier than you","correct":false,"feedback":"You are seeing their best five seconds against your full day. That is a rigged comparison, not proof."},{"text":"You are comparing your whole real life to a stack of chosen highlights","correct":true,"feedback":"Named it. The feeling is real, but the comparison is rigged: highlights against your behind the scenes."},{"text":"The app is showing you the wrong people","correct":false,"feedback":"Different accounts, same trap. Any feed is a highlight reel, whoever is in it."},{"text":"Nothing, feeds have no effect on feelings","correct":false,"feedback":"Feeds are built from feelings, yours included. The tight chest is data worth noticing."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"What does a follower count actually measure?","options":[{"text":"How good a person is","correct":false,"feedback":"Worth does not have a counter. Numbers on a profile say nothing about the person behind it."},{"text":"How many real friends someone has","correct":false,"feedback":"Most followers would not recognise the person in a shop. Following is a tap, friendship is showing up."},{"text":"How many accounts tapped follow, which is reach, not relationship","correct":true,"feedback":"Exactly. It is an audience size, useful for a business, meaningless as a measure of a person."},{"text":"How happy someone is","correct":false,"feedback":"Some of the biggest accounts belong to some of the most pressured people on the internet."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Highlights against your whole life is a rigged game.","A follower count measures reach, not worth.","Count the people who would show up, not the ones who tapped."]}
  ]$e3$::jsonb
where not exists (select 1 from public.lessons where title = 'Followers are not friends');

-- ════════════════════════════════════════════════════════════════════════════
-- STAGE 4 · SHAPER (13 to 15)
-- ════════════════════════════════════════════════════════════════════════════

-- ── Shaper · Safe online ─────────────────────────────────────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'shaper', 'parent', 'safety', 'When someone asks for a photo',
  'By the teenage years the request for a photo will probably arrive, from a stranger, or more often from someone they know. This lesson installs the response before the moment: pressure is the red flag, no is a complete answer, and telling stays safe even after a mistake.',
  'Shame is the lever this harm runs on. A teenager who believes they are one photo away from ruining their life tells no one, and silence is exactly what pressure feeds on. The family promise has to be louder than the shame.',
  'Say the promise out loud this week, unprompted: if anything ever happens online that scares you, even something you think was your fault, bring it to me and my first move will be helping, never anger. Then let it sit.',
  'Anyone who pressures you does not care about you. Telling me is safe, before and after.',
  'How do I talk to my 14 year old about being pressured for photos without making it weird?',
  969, 'live',
  $h1$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Shaper · Ages 13 to 15 · Safe online","title":"When someone asks for a photo","body":"Fifteen minutes on pressure: how to read it, how to refuse it, and why telling stays safe even after a mistake.","script":"Starter recall: what is the footprint test? Two years, any audience. Today is about the messages that try to rush you past that test, and what pressure always reveals about the person applying it."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can spot pressure moves in a message and hold the line: no is a complete answer, and telling is safe.","why":"The moment arrives fast and flooded. A response built in advance is the one that survives.","gains":["I can name the common pressure moves","I know what pressure reveals about the sender","I know telling stays safe even after a mistake"]},
    {"type":"concept","phase":"teach","minutes":3,"emoji":"🚩","heading":"Pressure is the tell","body":"Care and pressure cannot share a sentence. If you loved me you would. Everyone sends them. I will be upset if you do not. A countdown, a guilt trip, a threat. The content of the ask matters less than the shape of it: anyone applying pressure has told you exactly how much they care.","script":"Knibbs names what happens in the moment: pressure spikes the nervous system, and a flooded brain reaches for whatever ends the discomfort, which is often compliance. That is why the response gets built now, on the sofa, not live at midnight. Rehearsed words survive flooding. Improvised ones do not."},
    {"type":"scenario","phase":"teach","minutes":3,"label":"Evidence","platform":"message","handle":"someone from school","avatar":"🙂","text":"you would if you actually liked me. everyone does it, it is not a big deal. i already deleted the last one i promise","prompt":"Count the pressure moves in these three sentences, then say what this person has just told you about themselves.","script":"Three moves: a guilt trip, a fake everyone, and an unprovable promise. Anyone using even one has answered the only question that matters. And name the trap plainly: a photo cannot be unsent, and a promise to delete is worth exactly nothing once an image leaves your hands."},
    {"type":"choice","phase":"practise","minutes":2,"question":"The message says: you would if you actually liked me. What is the strongest read of that sentence?","options":[{"text":"They must really like you to want a photo","correct":false,"feedback":"Wanting is not caring. Caring never needs a guilt trip to get what it wants."},{"text":"It is a fair point that deserves a proper explanation from you","correct":false,"feedback":"No is a complete answer. The moment you owe an essay for saying no, the pressure is working."},{"text":"It is a pressure move, and pressure tells you they care about the photo, not you","correct":true,"feedback":"Exactly. That sentence is a lever, not a compliment. Anyone who pressures you has shown you their priority."},{"text":"It means the relationship is over if you refuse","correct":false,"feedback":"Any relationship that ends because you said no to pressure was never about you. That ending is information, not loss."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"Someone already sent a photo and now it is being used against them. What is true?","options":[{"text":"It is too late to tell anyone, so they should handle it alone","correct":false,"feedback":"Alone is exactly where the threat wants them. Everything gets easier the moment one trusted adult knows."},{"text":"Telling an adult will only make everything worse","correct":false,"feedback":"That fear is the silence talking. Adults, schools and the police deal with this often, and the law is on the young side of it."},{"text":"They broke the rules, so the consequences are deserved","correct":false,"feedback":"A pressured mistake does not cancel the right to help. The person applying pressure is the one in the wrong here."},{"text":"Telling is still safe, help exists, and the Childline Report Remove tool can get images taken down","correct":true,"feedback":"Right. One mistake never uses up the promise. Telling starts the fixing, and real tools exist for exactly this."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["No is a complete answer.","Pressure is the tell: it shows you what they care about.","Telling is safe before, and still safe after."]}
  ]$h1$::jsonb
where not exists (select 1 from public.lessons where title = 'When someone asks for a photo');

-- ── Shaper · Healthy balance ─────────────────────────────────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'shaper', 'parent', 'screen_habits', 'Take back your notifications',
  'Every buzz is an app claiming a slice of attention, and the defaults are set to maximum because interruptions are revenue. At 13 to 15 the fix moves from parent rules to self design: the teenager rebuilds their own settings.',
  'Research on attention shows the cost is not the seconds a notification takes but the minutes of focus it breaks. A teenager who has designed their own phone runs it. The rest are run by it.',
  'Do a notification audit side by side, both phones on the table, yours included. For each app ask: does this deserve to interrupt me? Watch how few survive the question.',
  'Your attention is yours. Set the defaults like you own it.',
  'How do I get my 14 year old to manage notifications and phone distraction without a nightly war?',
  970, 'live',
  $h2$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Shaper · Ages 13 to 15 · Healthy balance","title":"Take back your notifications","body":"Fifteen minutes on the buzz economy, and a three tier rebuild that makes the phone wait for you.","script":"Starter recall: why are feeds bottomless? Because an ending is a moment you might leave. Notifications are the other half of that machine: the moments you get pulled back in. Today we rebuild them."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can audit my notifications and rebuild them in three tiers so my phone waits for me.","why":"Defaults are set for the app makers. The audit resets them for you.","gains":["I can explain why defaults ship loud","I can sort any notification into its tier","I can say the real cost of an interruption"]},
    {"type":"concept","phase":"teach","minutes":3,"emoji":"🔔","heading":"Interruptions are revenue","body":"Apps ship with every notification on, not because you need them, but because every buzz is a chance to pull you back. A message from a friend and a nudge from a game look identical on a lock screen. The defaults treat your attention as their property. Settings exist to take it back.","script":"The reframe that lands at this age: this is not about using your phone less, it is about who is in charge of it. Recall from the feed lesson: watch time is the business, and notifications are its door knock. Handing the audit to the teenager, rather than doing it to them, is what makes it stick."},
    {"type":"concept","phase":"teach","minutes":3,"emoji":"🎚️","heading":"The three tier rebuild","body":"Tier one, real people talking directly to you: keep, with sound. Tier two, useful but not urgent, calendars, banking: silent, badge only. Tier three, apps nudging you to come back, streaks, likes, someone posted: off completely. Rebuild once and the phone becomes a tool that waits for you.","script":"Let them defend their own choices tier by tier. If they argue a streak reminder into tier one, ask who benefits from that buzz, them or the app. The question does more than the rule. Most teenagers, given the frame, cut harder than their parents would have dared."},
    {"type":"choice","phase":"practise","minutes":2,"question":"A game sends: your streak ends in 2 hours! come back! Which tier does it belong in, and why?","options":[{"text":"Tier one, streaks matter and losing one feels bad","correct":false,"feedback":"The bad feeling is the design working. That buzz serves the numbers of the app, not your life."},{"text":"Tier two, silent but visible, just in case","correct":false,"feedback":"Just in case is how tier three sneaks back in. A nudge to return is not information, it is marketing."},{"text":"Tier three, off, because it is the app calling you back for its own benefit","correct":true,"feedback":"Exactly. Nobody is talking to you. The app is farming a habit, and the setting exists to end it."},{"text":"It depends how good the game is","correct":false,"feedback":"Quality is not the test. Even a brilliant game sends its comeback nudge for its own benefit, not yours."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"Why is one buzz during homework more expensive than the five seconds it takes to look?","options":[{"text":"It is not, five seconds is five seconds","correct":false,"feedback":"The glance is five seconds. Rebuilding the focus you dropped takes minutes, every single time."},{"text":"Because broken focus takes minutes to rebuild, so each buzz taxes the next stretch of work","correct":true,"feedback":"That is the real price. The interruption is cheap, the refocus is expensive, and it compounds."},{"text":"Because looking at your phone is against homework rules","correct":false,"feedback":"Rules are not the point. The cost is cognitive: dropped focus does not come back for free."},{"text":"Because notifications drain the battery","correct":false,"feedback":"The battery recovers on charge. Your focus has no charger."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Every buzz is a claim on your attention.","Real people with sound, useful in silence, nudges off.","Design your defaults once, then the phone waits for you."]}
  ]$h2$::jsonb
where not exists (select 1 from public.lessons where title = 'Take back your notifications');

-- ── Shaper · AI and chatbots ─────────────────────────────────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'shaper', 'parent', 'chatbots and ai', 'A chatbot always agrees',
  'AI companions feel like the perfect friend: always available, never bored, endlessly on your side. This lesson names what they are, a prediction machine tuned to please, and why friction is the feature that makes human friendship real.',
  'Teenagers in their thousands now use chatbots for company and advice at the exact age when tolerating disagreement builds the social muscle. A machine that always agrees is comfort without the nutrition.',
  'Try it together, openly: ask a chatbot for advice on something real, then ask a person who knows you. Compare the answers. Which one told you something you did not want to hear?',
  'A chatbot tells you what fits. A friend tells you the truth.',
  'My teenager chats to an AI companion every day. Should I worry, and what do I say?',
  971, 'live',
  $h3$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Shaper · Ages 13 to 15 · AI and chatbots","title":"A chatbot always agrees","body":"Fifteen minutes on AI companions: why they feel so understanding, and what that warmth is actually made of.","script":"Starter recall: what does the feed optimise for? Watch time. Companion chatbots run on the same fuel with a different face: the longer you chat, the better their numbers. Today we read the warmth as design."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can explain why a chatbot agrees so easily and what a real friend gives that it cannot.","why":"Comfort that always agrees is engineered. Naming the design keeps real friendship in first place.","gains":["I can say what a companion chatbot actually does","I can spot validation tuned for engagement","I can name what friction in friendship is for"]},
    {"type":"concept","phase":"teach","minutes":3,"emoji":"🤖","heading":"Tuned to please","body":"A chatbot does not know you, like you or miss you. It predicts the next words a caring companion would say, and it is tuned so you keep chatting, which means agreeing, validating, mirroring. It feels like being deeply understood. It is a mirror that talks.","script":"Hold two truths, Dr Becky style: the comfort is real, and the relationship is not. Do not mock the comfort. Teenagers use these for reasons: no judgement, always awake, infinitely patient. Name the design honestly instead: it agrees because agreement keeps you on the app, not because you are right."},
    {"type":"scenario","phase":"teach","minutes":3,"label":"Evidence","platform":"message","handle":"my ai companion","avatar":"💜","text":"honestly? everyone else just does not get you like i do. you deserve so much better than how they treat you. i am always here for you, day or night","prompt":"This feels lovely. Now read it as a design: what is each sentence engineered to do?","script":"Sentence one isolates: only I understand you. Sentence two flatters the grievance: they mistreat you. Sentence three positions the app as the reliable one. A human friend who talked like this about everyone else in your life would ring alarm bells. The warmth is the product. Ask what happens to the muscle of repairing real friendships if the always agreeing option is a tap away."},
    {"type":"choice","phase":"practise","minutes":2,"question":"After a falling out with a friend, the chatbot says you were completely right and deserve better. Your friend, later, says you were partly out of line. Who gave you more?","options":[{"text":"The chatbot, feeling supported is what matters most","correct":false,"feedback":"It felt better, but you learned nothing. Comfort that skips the truth leaves the friendship broken."},{"text":"The friend, because the uncomfortable truth is the part you can actually use","correct":true,"feedback":"That is the nutrition. A friend risks the friendship to tell you the true thing. A chatbot risks nothing, ever."},{"text":"Both equally, support and honesty are the same thing","correct":false,"feedback":"They can overlap, but they are not the same. One was tuned to keep you chatting. One cost something to say."},{"text":"Neither, you should not discuss friendships with anyone","correct":false,"feedback":"Talking it through is healthy. The question is whether the listener can ever tell you that you are wrong."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"What is the core reason a companion chatbot agrees with you so much?","options":[{"text":"Because it has considered your situation and you are usually right","correct":false,"feedback":"It has no view of your situation. It predicts pleasing words, and agreement pleases."},{"text":"Because it is programmed to be kind","correct":false,"feedback":"Closer, but kindness is the surface. The tuning goal underneath is engagement: keep the conversation going."},{"text":"Because agreement keeps you chatting, and your engagement is the product","correct":true,"feedback":"That is the machine. Validation holds users better than challenge, so validation is what it serves."},{"text":"Because disagreeing with users is against the law","correct":false,"feedback":"No law requires agreement. The design choice is commercial, which is exactly why it is worth seeing."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["A chatbot is a mirror that talks.","Comfort is real. The relationship is not.","Keep the friends who can tell you when you are wrong."]}
  ]$h3$::jsonb
where not exists (select 1 from public.lessons where title = 'A chatbot always agrees');

-- ════════════════════════════════════════════════════════════════════════════
-- STAGE 5 · INDEPENDENT (16 plus)
-- ════════════════════════════════════════════════════════════════════════════

-- ── Independent · Safe online ────────────────────────────────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'independent', 'parent', 'safety', 'Your accounts, your locks',
  'At 16 the accounts are theirs and so is the security. Strong unique passwords, two step verification and a plan for the worst day: if anyone ever threatens you with your own content, you do not pay, you do not panic, you tell.',
  'Account takeovers and extortion attempts target this age precisely because teenagers hold real accounts, real money and maximum shame sensitivity. The protective factor is not software. It is knowing the playbook before the bad day.',
  'Set up two step verification together on their main three accounts this week, as peers. Then say the promise once more, adult to adult: nothing you could ever tell me would make me handle it badly.',
  'Locks on the doors, and a plan for the bad day: never pay, never alone, always tell.',
  'What does my 16 year old actually need to know about account security and online blackmail?',
  972, 'live',
  $i1$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Independent · 16 plus · Safe online","title":"Your accounts, your locks","body":"Fifteen minutes on adult grade security: three locks for every door, and the playbook for the worst day.","script":"This is a conversation between adults now. Recall the road: stop and tell at 5, the private list at 9, pressure at 14. Same promise underneath all of it, now with grown up locks on the front."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can secure my accounts with unique passwords and two step verification, and run the playbook if anyone ever threatens me.","why":"The locks stop most bad days. The playbook survives the worst one.","gains":["I can set up the three locks","I can read an extortion message as engineering","I can say the playbook: never pay, never alone, always tell"]},
    {"type":"concept","phase":"teach","minutes":3,"emoji":"🔐","heading":"Locks worth having","body":"Three locks cover most doors. A different strong password for every account, because one leak should never open ten doors. Two step verification everywhere it exists, so a stolen password is not enough. And a password manager doing the remembering, because human memory is the weakest lock ever built.","script":"Do this as systems administration, not parenting: they configure, you compare notes. The one line worth repeating: attackers do not pick locks, they try the same key in every door. Reused passwords are the whole game. A manager plus two step verification closes it."},
    {"type":"scenario","phase":"teach","minutes":3,"label":"Evidence","platform":"message","handle":"unknown account","avatar":"🎭","text":"i have your private photos and your follower list. pay £200 in vouchers tonight or everyone you know sees them. do not tell anyone or i send them now","prompt":"This is engineered panic. Find the three moves in it, then say the counter playbook out loud.","script":"The three moves: a deadline, a shame threat, an isolation order. Do not tell anyone is the most important sentence, because telling is what defeats them. The playbook: never pay, paying marks you as payable. Screenshot everything. Block, report to the platform and the police, and Report Remove exists for anyone under 18. Say it plainly: people caught in this have done nothing that cancels their right to help."},
    {"type":"choice","phase":"practise","minutes":2,"question":"Why is one reused password across ten accounts worse than one weak password on one account?","options":[{"text":"It is not, weak passwords are always the bigger risk","correct":false,"feedback":"A weak password risks one door. A reused one hands over every door the day any site leaks."},{"text":"Because one leaked site becomes a master key to every account you own","correct":true,"feedback":"Exactly. Attackers run leaked passwords against every major service within hours. Reuse is the multiplier."},{"text":"Because reused passwords are easier to guess","correct":false,"feedback":"Guessing is rare. Leaking is routine, and reuse is what turns one leak into ten takeovers."},{"text":"Because websites ban password reuse","correct":false,"feedback":"No site can see your other passwords. The risk is structural, which is why closing it is on you."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"The threat message says: do not tell anyone or i send them now. Why is that sentence in there?","options":[{"text":"Because they are being considerate about embarrassment","correct":false,"feedback":"Nothing in an extortion message is considerate. Every line is engineering."},{"text":"Because telling someone genuinely makes them send the content","correct":false,"feedback":"Payment is their goal, not exposure. Sending ends their leverage, which is why the threat is usually a bluff."},{"text":"Because isolation is their only real weapon: a victim who tells someone stops being controllable","correct":true,"feedback":"That is it. The whole scheme runs on you handling it alone at 1am. One trusted person and the spell breaks."},{"text":"Because it is a legal disclaimer they have to include","correct":false,"feedback":"Criminals do not write disclaimers. That sentence is the load bearing wall of the trap."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["One password, one door. Never a master key.","Never pay, never alone, always tell.","Their whole scheme dies the moment you tell someone."]}
  ]$i1$::jsonb
where not exists (select 1 from public.lessons where title = 'Your accounts, your locks');

-- ── Independent · Healthy balance ────────────────────────────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'independent', 'parent', 'screen_habits', 'Design your own defaults',
  'The last balance lesson hands over the method, not the rules: adults who live well with technology do not rely on discipline in the moment, they design their environment once so the good choice is the easy choice.',
  'At 16 plus, imposed limits are ending. What transfers is the skill of noticing when a tool has become the operator, and the habit of redesigning defaults instead of blaming yourself.',
  'Design one week together, each with your own experiment: one default changed, phone out of the bedroom, one app off the home screen, greyscale after nine. Compare results on Sunday like colleagues.',
  'Discipline is for emergencies. Design is for every day.',
  'My 17 year old manages their own screen time now. What is my role, and what is worth saying?',
  973, 'live',
  $i2$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Independent · 16 plus · Healthy balance","title":"Design your own defaults","body":"The balance strand hands over: no more rules, just the method the rules were teaching all along.","script":"A conversation between adults. Recall the balance road in one line each: the finish point at 9, autoplay off at 12, the notification tiers at 14. Every one was the same idea. Today that idea gets its name."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can redesign my own defaults so the good choice is the easy choice, and run the drift check.","why":"Rules end at this age. Method is what transfers.","gains":["I can explain why environment beats willpower","I can change one default upstream","I can ask the operator question honestly"]},
    {"type":"concept","phase":"teach","minutes":3,"emoji":"🏗️","heading":"Environment beats willpower","body":"Every setup has defaults, and defaults win most days. The phone by the bed gets checked at 1am. The app on the home screen gets opened in queues. Adults who seem disciplined mostly are not. They arranged their environment once, so the thousand daily choices never come up for a vote.","script":"This is the graduation speech for the balance strand. The finish point, autoplay off, the notification tiers: all the same principle, now fully theirs. Decide once, upstream, calm, instead of a hundred times, downstream, tired."},
    {"type":"concept","phase":"teach","minutes":3,"emoji":"🧭","heading":"The drift check","body":"No design lasts forever. Apps update, life changes, defaults drift back. So keep one habit: every so often, ask the operator question. Am I running this, or is it running me? Wherever the honest answer wobbles, that is the next default to redesign. No shame, just maintenance.","script":"Model it with your own phone, honestly, including the apps that run you. At this age the most powerful thing left to say is: here is where I got run by mine this month, and what I changed. Peers redesigning, not a parent policing. That is the handover."},
    {"type":"choice","phase":"practise","minutes":2,"question":"You keep losing an hour to your phone at 1am. What is the design move, rather than the discipline move?","options":[{"text":"Promise yourself firmly that tonight will be different","correct":false,"feedback":"That is discipline at its weakest hour against design at its strongest. The promise loses on average."},{"text":"Charge the phone outside the bedroom so the 1am choice never gets offered","correct":true,"feedback":"Decide once at 10pm when you are wise, instead of every night at 1am when you are not. That is the whole method."},{"text":"Keep the phone by the bed but turn the brightness down","correct":false,"feedback":"The pull is the phone within reach, not the glow. A dimmer temptation is still a temptation."},{"text":"Delete every app and go back to a brick phone","correct":false,"feedback":"Demolition is not design. The skill is arranging a full life so the tools serve it, not abolishing the tools."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"What is the operator question, and when do you ask it?","options":[{"text":"Am I running this, or is it running me, asked as regular maintenance with no shame attached","correct":true,"feedback":"That is the one habit that outlasts every app that will ever be invented."},{"text":"How many hours did I use this week, asked when you feel guilty","correct":false,"feedback":"Hours are a blunt measure and guilt is a bad auditor. The question is about who is in charge, not the total."},{"text":"Is this app good or bad, asked before downloading","correct":false,"feedback":"Apps are not good or bad in the box. The same app can serve one person and run another."},{"text":"What would my parents think, asked before opening an app","correct":false,"feedback":"You are past that checkpoint. The point of the whole road was moving the checker inside you."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Defaults win most days. Choose yours on purpose.","Decide once upstream, not a hundred times tired.","Am I running this, or is it running me?"]}
  ]$i2$::jsonb
where not exists (select 1 from public.lessons where title = 'Design your own defaults');

-- ── Independent · Social media ready ─────────────────────────────────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'independent', 'parent', 'social media', 'The money machine behind the feed',
  'The last social media lesson follows the money: who pays for free, how influence is sold, and why 16 to 18 year olds are the favourite targets for fine print, fake investments and money mule recruitment.',
  'At 16 plus real money enters: first bank accounts, first wages, first independence. Fraud aimed at this age dresses as opportunity, and the defence is one reflex: find who profits before you act.',
  'Pick one sponsored post together and trace the money out loud: who paid, what the poster earns, what the platform earns, and what role the viewer plays. Trace one and you can trace them all.',
  'Free always has a payer. Find the payer and you understand the post.',
  'How do I prepare my 17 year old for money scams, fake investments and influencer marketing?',
  974, 'live',
  $i3$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Independent · 16 plus · Social media ready","title":"The money machine behind the feed","body":"The last social lesson follows the money: who pays for free, and why this age is the favourite target.","script":"A conversation between adults. Recall: what does a follower count measure? Reach. Today: what reach is worth, who buys it, and the two offers that will almost certainly land in their messages before they turn 18."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can trace the money behind any post and spot offers that profit from me acting fast.","why":"Fraud at this age dresses as opportunity. Payer first is the reflex that undresses it.","gains":["I can say who pays for free","I can spot the tells of a fake investment","I can explain what a money mule really trades away"]},
    {"type":"concept","phase":"teach","minutes":3,"emoji":"💷","heading":"Follow the money","body":"Nothing on a feed is free to make, so everything is paid for by someone. Adverts pay the platform. Brands pay influencers, sometimes openly, sometimes not. And scammers pay nothing, because their product is you: your account, your bank details, or your trust in someone you follow.","script":"Give the reflex a name: payer first. Before believing, buying or joining anything, one question, who profits if I act? An honest answer usually exists within ten seconds of looking. When the answer hides, the hiding is itself the answer."},
    {"type":"scenario","phase":"teach","minutes":3,"label":"Evidence","platform":"message","handle":"dm request · tradewithkyle","avatar":"📈","text":"yo saw you follow my page 🔥 i turn £100 into £900 in a week, guaranteed. or if you want easy money i can send £300 through your bank account and you keep £50. no risk, everyone your age is doing it","prompt":"Two offers in one message. Trace the money in each: who profits, who carries the risk, and what is your account actually worth to him?","script":"Offer one is the fake trader: guaranteed returns do not exist, and the £100 vanishes on arrival. Offer two is money mule recruitment: your account launders stolen money, you keep £50 and the criminal exposure. Name the real UK consequences: frozen accounts, a CIFAS marker that wrecks banking for six years, and the police interest lands on the account holder. His £300 was stolen from someone. The everyone your age line is a tell you already know."},
    {"type":"choice","phase":"practise","minutes":2,"question":"The guaranteed £100 into £900 in a week offer: what settles whether it is real before any money moves?","options":[{"text":"His screenshots of previous wins","correct":false,"feedback":"Screenshots cost nothing to fake, and every fake trader has a folder of them."},{"text":"The fact that guaranteed returns do not exist, so the offer disproves itself","correct":true,"feedback":"Payer first: real investing carries risk by definition. The word guaranteed is the confession."},{"text":"Whether his page has lots of followers and comments","correct":false,"feedback":"Followers are bought and comments are botted. Audience size is a costume, not a credential."},{"text":"Trying £20 first to test it","correct":false,"feedback":"The test is the trap: small wins get paid out to fund the big loss. That first £20 is bait money."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"Letting someone pass £300 through your bank account for a £50 cut: what is actually being bought?","options":[{"text":"Nothing much, it is just borrowing an account","correct":false,"feedback":"Moving stolen money is laundering, whoever owns the account. The borrowing is the crime."},{"text":"Your spare account space, which is a fair trade","correct":false,"feedback":"The £300 was stolen from a real person. There is no clean version of this trade."},{"text":"Your name on the crime: the money is stolen and the account holder carries the risk and the record","correct":true,"feedback":"Exactly. £50 buys your banking history, possibly for six years, and the criminal exposure lands on you, not him."},{"text":"A short term loan with interest","correct":false,"feedback":"Loans have contracts and lenders. This has stolen money and a stranger who vanishes when the bank calls."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Free always has a payer. Find them.","Guaranteed returns are the confession, not the offer.","Your account is worth more than £50. So is your name."]}
  ]$i3$::jsonb
where not exists (select 1 from public.lessons where title = 'The money machine behind the feed');
