-- Guided Childhood — Migration 115
-- The England English curriculum, years 1 to 6.
--
-- Companion to 114. Source: National curriculum in England, English programmes
-- of study, the GOV.UK version updated 16 July 2014, supplied by Justin on
-- 27 July. 113 statutory requirements, landing as 220 rows once the key stage 2
-- year pairs are expanded. Key stages 3 and 4 are in the same document and are
-- deliberately excluded: these sheets are years 1 to 6.
--
-- ── Two things here are genuinely different from maths ───────────────────────
--
-- FIRST, THE TERM IS 'all', NOT A TERM.
--
-- Maths gets a term because schools do sequence it. English does not. The
-- programmes of study set reading and writing out for the whole year and no
-- school teaches handwriting in the spring and stops. Putting these rows in a
-- term would be inventing a fact, which is the exact failure this table is
-- shaped to prevent, so they carry the term 'all' and the sheet reads them
-- whatever the date is. The page says so on the sheet rather than leaving a
-- parent to assume the heading means their child's term.
--
-- SECOND, KEY STAGE 2 IS WRITTEN IN PAIRS.
--
-- English is set out year by year for key stage 1 and TWO YEARLY for key stage
-- 2: one programme of study for years 3 and 4, one for years 5 and 6. That is
-- the document, not an omission. So the years 3 and 4 requirements are inserted
-- against year 3 AND year 4, and likewise 5 and 6, and each row's source says
-- 'years 3 and 4' rather than pretending to be year specific. A Year 3 sheet
-- and a Year 4 sheet are therefore the same sheet, which is correct: the
-- statutory expectation is the same for both.
--
-- Spoken language is the same again, one set of 12 requirements that applies
-- across all six years, inserted against every one of them.
--
-- ── Reading is its own subject, English is the rest ──────────────────────────
--
-- The printables page already had three tabs. Reading word reading and reading
-- comprehension go to 'reading' because that is what a parent means by it.
-- Writing, spelling, handwriting and spoken language go to 'english'.
--
-- ── What the GOV.UK rendering broke, and what was done about it ──────────────
--
-- The 2014 web version renders links to the appendices as raw markup, and the
-- debris lands in the middle of the statutory text: bare paths beginning
-- /government/uploads, and trailing fragments like _Spelling.pdf). The same
-- breakage duplicates a word in the year 1 grammar line, which reads 'in
-- English English appendix 2' where every other year reads 'in English appendix
-- 2'. All of it is stripped. It is rendering debris, not wording, and it is the
-- only editing done to any line.
--
-- Structure was checked against the September 2013 PDF, as it was for maths.
--
-- ── Supabase editor rules ────────────────────────────────────────────────────
--
-- Idempotent creates, no DO blocks, flat statements only, and no semicolons
-- inside string literals: the dashboard splits statements naively and a
-- semicolon in copy breaks the paste. The statutory text is full of them, so
-- they are spliced with chr(59) and the stored value stays byte for byte the
-- published text.

insert into public.curriculum_objectives (year_group, subject, term, strand, objective, source, verbatim, checkpoint, sort_order) values
  (1, 'reading', 'all', 'Reading word reading', 'apply phonic knowledge and skills as the route to decode words', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 10),
  (1, 'reading', 'all', 'Reading word reading', 'respond speedily with the correct sound to graphemes (letters or groups of letters) for all 40+ phonemes, including, where applicable, alternative sounds for graphemes', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 20),
  (1, 'reading', 'all', 'Reading word reading', 'read accurately by blending sounds in unfamiliar words containing GPCs that have been taught', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 30),
  (1, 'reading', 'all', 'Reading word reading', 'read common exception words, noting unusual correspondences between spelling and sound and where these occur in the word', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 40),
  (1, 'reading', 'all', 'Reading word reading', 'read words containing taught GPCs and -s, -es, -ing, -ed, -er and -est endings', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 50),
  (1, 'reading', 'all', 'Reading word reading', 'read other words of more than one syllable that contain taught GPCs', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 60),
  (1, 'reading', 'all', 'Reading word reading', 'read words with contractions [for example, I''m, I''ll, we''ll], and understand that the apostrophe represents the omitted letter(s)', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 70),
  (1, 'reading', 'all', 'Reading word reading', 'read books aloud, accurately, that are consistent with their developing phonic knowledge and that do not require them to use other strategies to work out words', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 80),
  (1, 'reading', 'all', 'Reading word reading', 'reread these books to build up their fluency and confidence in word reading', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 90),
  (1, 'reading', 'all', 'Reading comprehension', 'develop pleasure in reading, motivation to read, vocabulary and understanding by: listening to and discussing a wide range of poems, stories and non-fiction at a level beyond that at which they can read independently' || chr(59) || ' being encouraged to link what they read or hear to their own experiences' || chr(59) || ' becoming very familiar with key stories, fairy stories and traditional tales, retelling them and considering their particular characteristics' || chr(59) || ' recognising and joining in with predictable phrases' || chr(59) || ' learning to appreciate rhymes and poems, and to recite some by heart' || chr(59) || ' discussing word meanings, linking new meanings to those already known', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 100),
  (1, 'reading', 'all', 'Reading comprehension', 'understand both the books they can already read accurately and fluently and those they listen to by: drawing on what they already know or on background information and vocabulary provided by the teacher' || chr(59) || ' checking that the text makes sense to them as they read, and correcting inaccurate reading' || chr(59) || ' discussing the significance of the title and events' || chr(59) || ' making inferences on the basis of what is being said and done' || chr(59) || ' predicting what might happen on the basis of what has been read so far', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 110),
  (1, 'reading', 'all', 'Reading comprehension', 'participate in discussion about what is read to them, taking turns and listening to what others say', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 120),
  (1, 'reading', 'all', 'Reading comprehension', 'explain clearly their understanding of what is read to them', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 130)
on conflict (curriculum, year_group, subject, term, objective) do nothing;

insert into public.curriculum_objectives (year_group, subject, term, strand, objective, source, verbatim, checkpoint, sort_order) values
  (1, 'english', 'all', 'Spoken language', 'listen and respond appropriately to adults and their peers', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 10),
  (1, 'english', 'all', 'Spoken language', 'ask relevant questions to extend their understanding and knowledge', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 20),
  (1, 'english', 'all', 'Spoken language', 'use relevant strategies to build their vocabulary', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 30),
  (1, 'english', 'all', 'Spoken language', 'articulate and justify answers, arguments and opinions', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 40),
  (1, 'english', 'all', 'Spoken language', 'give well-structured descriptions, explanations and narratives for different purposes, including for expressing feelings', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 50),
  (1, 'english', 'all', 'Spoken language', 'maintain attention and participate actively in collaborative conversations, staying on topic and initiating and responding to comments', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 60),
  (1, 'english', 'all', 'Spoken language', 'use spoken language to develop understanding through speculating, hypothesising, imagining and exploring ideas', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 70),
  (1, 'english', 'all', 'Spoken language', 'speak audibly and fluently with an increasing command of Standard English', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 80),
  (1, 'english', 'all', 'Spoken language', 'participate in discussions, presentations, performances, role play/improvisations and debates', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 90),
  (1, 'english', 'all', 'Spoken language', 'gain, maintain and monitor the interest of the listener(s)', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 100),
  (1, 'english', 'all', 'Spoken language', 'consider and evaluate different viewpoints, attending to and building on the contributions of others', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 110),
  (1, 'english', 'all', 'Spoken language', 'select and use appropriate registers for effective communication', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 120),
  (1, 'english', 'all', 'Writing transcription (spelling)', 'spell: words containing each of the 40+ phonemes already taught' || chr(59) || ' common exception words' || chr(59) || ' the days of the week', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 130),
  (1, 'english', 'all', 'Writing transcription (spelling)', 'name the letters of the alphabet: naming the letters of the alphabet in order' || chr(59) || ' using letter names to distinguish between alternative spellings of the same sound', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 140),
  (1, 'english', 'all', 'Writing transcription (spelling)', 'add prefixes and suffixes: using the spelling rule for adding -s or -es as the plural marker for nouns and the third person singular marker for verbs' || chr(59) || ' using the prefix un-' || chr(59) || ' using -ing, -ed, -er and -est where no change is needed in the spelling of root words [for example, helping, helped, helper, eating, quicker, quickest]', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 150),
  (1, 'english', 'all', 'Writing transcription (spelling)', 'apply simple spelling rules and guidance, as listed in English appendix 1', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 160),
  (1, 'english', 'all', 'Writing transcription (spelling)', 'write from memory simple sentences dictated by the teacher that include words using the GPCs and common exception words taught so far', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 170),
  (1, 'english', 'all', 'Writing transcription (handwriting)', 'sit correctly at a table, holding a pencil comfortably and correctly', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 180),
  (1, 'english', 'all', 'Writing transcription (handwriting)', 'begin to form lower-case letters in the correct direction, starting and finishing in the right place', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 190),
  (1, 'english', 'all', 'Writing transcription (handwriting)', 'form capital letters', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 200),
  (1, 'english', 'all', 'Writing transcription (handwriting)', 'form digits 0-9', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 210),
  (1, 'english', 'all', 'Writing transcription (handwriting)', 'understand which letters belong to which handwriting ''families'' (ie letters that are formed in similar ways) and to practise these', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 220),
  (1, 'english', 'all', 'Writing composition', 'write sentences by: saying out loud what they are going to write about' || chr(59) || ' composing a sentence orally before writing it' || chr(59) || ' sequencing sentences to form short narratives' || chr(59) || ' re-reading what they have written to check that it makes sense', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 230),
  (1, 'english', 'all', 'Writing composition', 'discuss what they have written with the teacher or other pupils', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 240),
  (1, 'english', 'all', 'Writing composition', 'read their writing aloud, clearly enough to be heard by their peers and the teacher', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 250),
  (1, 'english', 'all', 'Writing vocabulary grammar and punctuation', 'develop their understanding of the concepts set out in English appendix 2 by: leaving spaces between words' || chr(59) || ' joining words and joining clauses using ''and''' || chr(59) || ' beginning to punctuate sentences using a capital letter and a full stop, question mark or exclamation mark' || chr(59) || ' using a capital letter for names of people, places, the days of the week, and the personal pronoun ''I''' || chr(59) || ' learning the grammar for year 1 in English appendix 2', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 260),
  (1, 'english', 'all', 'Writing vocabulary grammar and punctuation', 'use the grammatical terminology in English appendix 2 in discussing their writing', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 1', true, null, 270)
on conflict (curriculum, year_group, subject, term, objective) do nothing;

insert into public.curriculum_objectives (year_group, subject, term, strand, objective, source, verbatim, checkpoint, sort_order) values
  (2, 'reading', 'all', 'Reading word reading', 'continue to apply phonic knowledge and skills as the route to decode words until automatic decoding has become embedded and reading is fluent', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 10),
  (2, 'reading', 'all', 'Reading word reading', 'read accurately by blending the sounds in words that contain the graphemes taught so far, especially recognising alternative sounds for graphemes', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 20),
  (2, 'reading', 'all', 'Reading word reading', 'read accurately words of two or more syllables that contain the same graphemes as above', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 30),
  (2, 'reading', 'all', 'Reading word reading', 'read words containing common suffixes', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 40),
  (2, 'reading', 'all', 'Reading word reading', 'read further common exception words, noting unusual correspondences between spelling and sound and where these occur in the word', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 50),
  (2, 'reading', 'all', 'Reading word reading', 'read most words quickly and accurately, without overt sounding and blending, when they have been frequently encountered', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 60),
  (2, 'reading', 'all', 'Reading word reading', 'read aloud books closely matched to their improving phonic knowledge, sounding out unfamiliar words accurately, automatically and without undue hesitation', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 70),
  (2, 'reading', 'all', 'Reading word reading', 'reread these books to build up their fluency and confidence in word reading', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 80),
  (2, 'reading', 'all', 'Reading comprehension', 'develop pleasure in reading, motivation to read, vocabulary and understanding by: listening to, discussing and expressing views about a wide range of contemporary and classic poetry, stories and non-fiction at a level beyond that at which they can read independently' || chr(59) || ' discussing the sequence of events in books and how items of information are related' || chr(59) || ' becoming increasingly familiar with and retelling a wider range of stories, fairy stories and traditional tales' || chr(59) || ' being introduced to non-fiction books that are structured in different ways' || chr(59) || ' recognising simple recurring literary language in stories and poetry' || chr(59) || ' discussing and clarifying the meanings of words, linking new meanings to known vocabulary' || chr(59) || ' discussing their favourite words and phrases' || chr(59) || ' continuing to build up a repertoire of poems learnt by heart, appreciating these and reciting some, with appropriate intonation to make the meaning clear', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 90),
  (2, 'reading', 'all', 'Reading comprehension', 'understand both the books that they can already read accurately and fluently and those that they listen to by: drawing on what they already know or on background information and vocabulary provided by the teacher' || chr(59) || ' checking that the text makes sense to them as they read, and correcting inaccurate reading' || chr(59) || ' making inferences on the basis of what is being said and done' || chr(59) || ' answering and asking questions' || chr(59) || ' predicting what might happen on the basis of what has been read so far', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 100),
  (2, 'reading', 'all', 'Reading comprehension', 'participate in discussion about books, poems and other works that are read to them and those that they can read for themselves, taking turns and listening to what others say', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 110),
  (2, 'reading', 'all', 'Reading comprehension', 'explain and discuss their understanding of books, poems and other material, both those that they listen to and those that they read for themselves', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 120)
on conflict (curriculum, year_group, subject, term, objective) do nothing;

insert into public.curriculum_objectives (year_group, subject, term, strand, objective, source, verbatim, checkpoint, sort_order) values
  (2, 'english', 'all', 'Spoken language', 'listen and respond appropriately to adults and their peers', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 10),
  (2, 'english', 'all', 'Spoken language', 'ask relevant questions to extend their understanding and knowledge', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 20),
  (2, 'english', 'all', 'Spoken language', 'use relevant strategies to build their vocabulary', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 30),
  (2, 'english', 'all', 'Spoken language', 'articulate and justify answers, arguments and opinions', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 40),
  (2, 'english', 'all', 'Spoken language', 'give well-structured descriptions, explanations and narratives for different purposes, including for expressing feelings', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 50),
  (2, 'english', 'all', 'Spoken language', 'maintain attention and participate actively in collaborative conversations, staying on topic and initiating and responding to comments', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 60),
  (2, 'english', 'all', 'Spoken language', 'use spoken language to develop understanding through speculating, hypothesising, imagining and exploring ideas', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 70),
  (2, 'english', 'all', 'Spoken language', 'speak audibly and fluently with an increasing command of Standard English', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 80),
  (2, 'english', 'all', 'Spoken language', 'participate in discussions, presentations, performances, role play/improvisations and debates', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 90),
  (2, 'english', 'all', 'Spoken language', 'gain, maintain and monitor the interest of the listener(s)', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 100),
  (2, 'english', 'all', 'Spoken language', 'consider and evaluate different viewpoints, attending to and building on the contributions of others', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 110),
  (2, 'english', 'all', 'Spoken language', 'select and use appropriate registers for effective communication', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 120),
  (2, 'english', 'all', 'Writing transcription (spelling)', 'spell by: segmenting spoken words into phonemes and representing these by graphemes, spelling many correctly' || chr(59) || ' learning new ways of spelling phonemes for which 1 or more spellings are already known, and learn some words with each spelling, including a few common homophones' || chr(59) || ' learning to spell common exception words' || chr(59) || ' learning to spell more words with contracted forms' || chr(59) || ' learning the possessive apostrophe (singular) [for example, the girl''s book]' || chr(59) || ' distinguishing between homophones and near-homophones', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 130),
  (2, 'english', 'all', 'Writing transcription (spelling)', 'add suffixes to spell longer words including -ment, -ness, -ful, -less, -ly', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 140),
  (2, 'english', 'all', 'Writing transcription (spelling)', 'apply spelling rules and guidance, as listed in English appendix 1 (https://www.gov.uk', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 150),
  (2, 'english', 'all', 'Writing transcription (spelling)', 'write from memory simple sentences dictated by the teacher that include words using the GPCs, common exception words and punctuation taught so far', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 160),
  (2, 'english', 'all', 'Writing transcription (handwriting)', 'form lower-case letters of the correct size relative to one another', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 170),
  (2, 'english', 'all', 'Writing transcription (handwriting)', 'start using some of the diagonal and horizontal strokes needed to join letters and understand which letters, when adjacent to one another, are best left unjoined', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 180),
  (2, 'english', 'all', 'Writing transcription (handwriting)', 'write capital letters and digits of the correct size, orientation and relationship to one another and to lower-case letters', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 190),
  (2, 'english', 'all', 'Writing transcription (handwriting)', 'use spacing between words that reflects the size of the letters', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 200),
  (2, 'english', 'all', 'Writing composition', 'develop positive attitudes towards and stamina for writing by: writing narratives about personal experiences and those of others (real and fictional)' || chr(59) || ' writing about real events' || chr(59) || ' writing poetry' || chr(59) || ' writing for different purposes', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 210),
  (2, 'english', 'all', 'Writing composition', 'consider what they are going to write before beginning by: planning or saying out loud what they are going to write about' || chr(59) || ' writing down ideas and/or key words, including new vocabulary' || chr(59) || ' encapsulating what they want to say, sentence by sentence', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 220),
  (2, 'english', 'all', 'Writing composition', 'make simple additions, revisions and corrections to their own writing by: evaluating their writing with the teacher and other pupils' || chr(59) || ' rereading to check that their writing makes sense and that verbs to indicate time are used correctly and consistently, including verbs in the continuous form' || chr(59) || ' proofreading to check for errors in spelling, grammar and punctuation (for example, ends of sentences punctuated correctly)', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 230),
  (2, 'english', 'all', 'Writing composition', 'read aloud what they have written with appropriate intonation to make the meaning clear', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 240),
  (2, 'english', 'all', 'Writing vocabulary grammar and punctuation', 'develop their understanding of the concepts set out in English appendix 2 by: learning how to use both familiar and new punctuation correctly - see English appendix 2 , including full stops, capital letters, exclamation marks, question marks, commas for lists and apostrophes for contracted forms and the possessive (singular)' || chr(59) || ' learn how to use: sentences with different forms: statement, question, exclamation, command' || chr(59) || ' expanded noun phrases to describe and specify [for example, the blue butterfly]' || chr(59) || ' the present and past tenses correctly and consistently, including the progressive form' || chr(59) || ' subordination (using when, if, that, or because) and co-ordination (using or, and, or but)' || chr(59) || ' the grammar for year 2 in English appendix 2' || chr(59) || ' some features of written Standard English', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 250),
  (2, 'english', 'all', 'Writing vocabulary grammar and punctuation', 'use and understand the grammatical terminology in English appendix 2 in discussing their writing', 'National curriculum in England: English programmes of study, updated 16 July 2014, year 2', true, null, 260)
on conflict (curriculum, year_group, subject, term, objective) do nothing;

insert into public.curriculum_objectives (year_group, subject, term, strand, objective, source, verbatim, checkpoint, sort_order) values
  (3, 'reading', 'all', 'Reading word reading', 'apply their growing knowledge of root words, prefixes and suffixes (etymology and morphology) as listed in - see English appendix 1 , both to read aloud and to understand the meaning of new words they meet', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 10),
  (3, 'reading', 'all', 'Reading word reading', 'read further exception words, noting the unusual correspondences between spelling and sound, and where these occur in the word', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 20),
  (3, 'reading', 'all', 'Reading comprehension', 'develop positive attitudes to reading, and an understanding of what they read, by: listening to and discussing a wide range of fiction, poetry, plays, non-fiction and reference books or textbooks' || chr(59) || ' reading books that are structured in different ways and reading for a range of purposes' || chr(59) || ' using dictionaries to check the meaning of words that they have read' || chr(59) || ' increasing their familiarity with a wide range of books, including fairy stories, myths and legends, and retelling some of these orally' || chr(59) || ' identifying themes and conventions in a wide range of books' || chr(59) || ' preparing poems and play scripts to read aloud and to perform, showing understanding through intonation, tone, volume and action' || chr(59) || ' discussing words and phrases that capture the reader''s interest and imagination' || chr(59) || ' recognising some different forms of poetry [for example, free verse, narrative poetry]', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 30),
  (3, 'reading', 'all', 'Reading comprehension', 'understand what they read, in books they can read independently, by: checking that the text makes sense to them, discussing their understanding, and explaining the meaning of words in context' || chr(59) || ' asking questions to improve their understanding of a text' || chr(59) || ' drawing inferences such as inferring characters'' feelings, thoughts and motives from their actions, and justifying inferences with evidence' || chr(59) || ' predicting what might happen from details stated and implied' || chr(59) || ' identifying main ideas drawn from more than 1 paragraph and summarising these' || chr(59) || ' identifying how language, structure, and presentation contribute to meaning', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 40),
  (3, 'reading', 'all', 'Reading comprehension', 'retrieve and record information from non-fiction', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 50),
  (3, 'reading', 'all', 'Reading comprehension', 'participate in discussion about both books that are read to them and those they can read for themselves, taking turns and listening to what others say', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 60)
on conflict (curriculum, year_group, subject, term, objective) do nothing;

insert into public.curriculum_objectives (year_group, subject, term, strand, objective, source, verbatim, checkpoint, sort_order) values
  (3, 'english', 'all', 'Spoken language', 'listen and respond appropriately to adults and their peers', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 10),
  (3, 'english', 'all', 'Spoken language', 'ask relevant questions to extend their understanding and knowledge', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 20),
  (3, 'english', 'all', 'Spoken language', 'use relevant strategies to build their vocabulary', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 30),
  (3, 'english', 'all', 'Spoken language', 'articulate and justify answers, arguments and opinions', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 40),
  (3, 'english', 'all', 'Spoken language', 'give well-structured descriptions, explanations and narratives for different purposes, including for expressing feelings', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 50),
  (3, 'english', 'all', 'Spoken language', 'maintain attention and participate actively in collaborative conversations, staying on topic and initiating and responding to comments', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 60),
  (3, 'english', 'all', 'Spoken language', 'use spoken language to develop understanding through speculating, hypothesising, imagining and exploring ideas', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 70),
  (3, 'english', 'all', 'Spoken language', 'speak audibly and fluently with an increasing command of Standard English', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 80),
  (3, 'english', 'all', 'Spoken language', 'participate in discussions, presentations, performances, role play/improvisations and debates', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 90),
  (3, 'english', 'all', 'Spoken language', 'gain, maintain and monitor the interest of the listener(s)', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 100),
  (3, 'english', 'all', 'Spoken language', 'consider and evaluate different viewpoints, attending to and building on the contributions of others', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 110),
  (3, 'english', 'all', 'Spoken language', 'select and use appropriate registers for effective communication', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 120),
  (3, 'english', 'all', 'Writing transcription (spelling)', 'use further prefixes and suffixes and understand how to add them - see English appendix 1', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 130),
  (3, 'english', 'all', 'Writing transcription (spelling)', 'spell further homophones', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 140),
  (3, 'english', 'all', 'Writing transcription (spelling)', 'spell words that are often misspelt - see English appendix 1', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 150),
  (3, 'english', 'all', 'Writing transcription (spelling)', 'place the possessive apostrophe accurately in words with regular plurals [for example, girls'', boys''] and in words with irregular plurals [for example, children''s]', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 160),
  (3, 'english', 'all', 'Writing transcription (spelling)', 'use the first 2 or 3 letters of a word to check its spelling in a dictionary', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 170),
  (3, 'english', 'all', 'Writing transcription (spelling)', 'write from memory simple sentences, dictated by the teacher, that include words and punctuation taught so far', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 180),
  (3, 'english', 'all', 'Writing transcription (handwriting)', 'use the diagonal and horizontal strokes that are needed to join letters and understand which letters, when adjacent to one another, are best left unjoined', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 190),
  (3, 'english', 'all', 'Writing transcription (handwriting)', 'increase the legibility, consistency and quality of their handwriting, [for example, by ensuring that the downstrokes of letters are parallel and equidistant, and that lines of writing are spaced sufficiently so that the ascenders and descenders of letters do not touch]', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 200),
  (3, 'english', 'all', 'Writing composition', 'plan their writing by: discussing writing similar to that which they are planning to write in order to understand and learn from its structure, vocabulary and grammar' || chr(59) || ' discussing and recording ideas', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 210),
  (3, 'english', 'all', 'Writing composition', 'draft and write by: composing and rehearsing sentences orally (including dialogue), progressively building a varied and rich vocabulary and an increasing range of sentence structures English appendix 2' || chr(59) || ' organising paragraphs around a theme' || chr(59) || ' in narratives, creating settings, characters and plot' || chr(59) || ' in non-narrative material, using simple organisational devices [for example, headings and sub-headings]', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 220),
  (3, 'english', 'all', 'Writing composition', 'evaluate and edit by: assessing the effectiveness of their own and others'' writing and suggesting improvements' || chr(59) || ' proposing changes to grammar and vocabulary to improve consistency, including the accurate use of pronouns in sentences', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 230),
  (3, 'english', 'all', 'Writing composition', 'proofread for spelling and punctuation errors', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 240),
  (3, 'english', 'all', 'Writing composition', 'read their own writing aloud to a group or the whole class, using appropriate intonation and controlling the tone and volume so that the meaning is clear', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 250),
  (3, 'english', 'all', 'Writing vocabulary grammar and punctuation', 'develop their understanding of the concepts set out in English appendix 2 by: extending the range of sentences with more than one clause by using a wider range of conjunctions, including: when, if, because, although' || chr(59) || ' using the present perfect form of verbs in contrast to the past tense' || chr(59) || ' choosing nouns or pronouns appropriately for clarity and cohesion and to avoid repetition' || chr(59) || ' using conjunctions, adverbs and prepositions to express time and cause' || chr(59) || ' using fronted adverbials' || chr(59) || ' learning the grammar for years 3 and 4 in [English appendix 2]', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 260),
  (3, 'english', 'all', 'Writing vocabulary grammar and punctuation', 'indicate grammatical and other features by: using commas after fronted adverbials' || chr(59) || ' indicating possession by using the possessive apostrophe with plural nouns' || chr(59) || ' using and punctuating direct speech', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 270),
  (3, 'english', 'all', 'Writing vocabulary grammar and punctuation', 'use and understand the grammatical terminology in English appendix 2 accurately and appropriately when discussing their writing and reading', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 280)
on conflict (curriculum, year_group, subject, term, objective) do nothing;

insert into public.curriculum_objectives (year_group, subject, term, strand, objective, source, verbatim, checkpoint, sort_order) values
  (4, 'reading', 'all', 'Reading word reading', 'apply their growing knowledge of root words, prefixes and suffixes (etymology and morphology) as listed in - see English appendix 1 , both to read aloud and to understand the meaning of new words they meet', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 10),
  (4, 'reading', 'all', 'Reading word reading', 'read further exception words, noting the unusual correspondences between spelling and sound, and where these occur in the word', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 20),
  (4, 'reading', 'all', 'Reading comprehension', 'develop positive attitudes to reading, and an understanding of what they read, by: listening to and discussing a wide range of fiction, poetry, plays, non-fiction and reference books or textbooks' || chr(59) || ' reading books that are structured in different ways and reading for a range of purposes' || chr(59) || ' using dictionaries to check the meaning of words that they have read' || chr(59) || ' increasing their familiarity with a wide range of books, including fairy stories, myths and legends, and retelling some of these orally' || chr(59) || ' identifying themes and conventions in a wide range of books' || chr(59) || ' preparing poems and play scripts to read aloud and to perform, showing understanding through intonation, tone, volume and action' || chr(59) || ' discussing words and phrases that capture the reader''s interest and imagination' || chr(59) || ' recognising some different forms of poetry [for example, free verse, narrative poetry]', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 30),
  (4, 'reading', 'all', 'Reading comprehension', 'understand what they read, in books they can read independently, by: checking that the text makes sense to them, discussing their understanding, and explaining the meaning of words in context' || chr(59) || ' asking questions to improve their understanding of a text' || chr(59) || ' drawing inferences such as inferring characters'' feelings, thoughts and motives from their actions, and justifying inferences with evidence' || chr(59) || ' predicting what might happen from details stated and implied' || chr(59) || ' identifying main ideas drawn from more than 1 paragraph and summarising these' || chr(59) || ' identifying how language, structure, and presentation contribute to meaning', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 40),
  (4, 'reading', 'all', 'Reading comprehension', 'retrieve and record information from non-fiction', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 50),
  (4, 'reading', 'all', 'Reading comprehension', 'participate in discussion about both books that are read to them and those they can read for themselves, taking turns and listening to what others say', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 60)
on conflict (curriculum, year_group, subject, term, objective) do nothing;

insert into public.curriculum_objectives (year_group, subject, term, strand, objective, source, verbatim, checkpoint, sort_order) values
  (4, 'english', 'all', 'Spoken language', 'listen and respond appropriately to adults and their peers', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 10),
  (4, 'english', 'all', 'Spoken language', 'ask relevant questions to extend their understanding and knowledge', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 20),
  (4, 'english', 'all', 'Spoken language', 'use relevant strategies to build their vocabulary', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 30),
  (4, 'english', 'all', 'Spoken language', 'articulate and justify answers, arguments and opinions', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 40),
  (4, 'english', 'all', 'Spoken language', 'give well-structured descriptions, explanations and narratives for different purposes, including for expressing feelings', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 50),
  (4, 'english', 'all', 'Spoken language', 'maintain attention and participate actively in collaborative conversations, staying on topic and initiating and responding to comments', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 60),
  (4, 'english', 'all', 'Spoken language', 'use spoken language to develop understanding through speculating, hypothesising, imagining and exploring ideas', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 70),
  (4, 'english', 'all', 'Spoken language', 'speak audibly and fluently with an increasing command of Standard English', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 80),
  (4, 'english', 'all', 'Spoken language', 'participate in discussions, presentations, performances, role play/improvisations and debates', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 90),
  (4, 'english', 'all', 'Spoken language', 'gain, maintain and monitor the interest of the listener(s)', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 100),
  (4, 'english', 'all', 'Spoken language', 'consider and evaluate different viewpoints, attending to and building on the contributions of others', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 110),
  (4, 'english', 'all', 'Spoken language', 'select and use appropriate registers for effective communication', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 120),
  (4, 'english', 'all', 'Writing transcription (spelling)', 'use further prefixes and suffixes and understand how to add them - see English appendix 1', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 130),
  (4, 'english', 'all', 'Writing transcription (spelling)', 'spell further homophones', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 140),
  (4, 'english', 'all', 'Writing transcription (spelling)', 'spell words that are often misspelt - see English appendix 1', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 150),
  (4, 'english', 'all', 'Writing transcription (spelling)', 'place the possessive apostrophe accurately in words with regular plurals [for example, girls'', boys''] and in words with irregular plurals [for example, children''s]', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 160),
  (4, 'english', 'all', 'Writing transcription (spelling)', 'use the first 2 or 3 letters of a word to check its spelling in a dictionary', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 170),
  (4, 'english', 'all', 'Writing transcription (spelling)', 'write from memory simple sentences, dictated by the teacher, that include words and punctuation taught so far', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 180),
  (4, 'english', 'all', 'Writing transcription (handwriting)', 'use the diagonal and horizontal strokes that are needed to join letters and understand which letters, when adjacent to one another, are best left unjoined', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 190),
  (4, 'english', 'all', 'Writing transcription (handwriting)', 'increase the legibility, consistency and quality of their handwriting, [for example, by ensuring that the downstrokes of letters are parallel and equidistant, and that lines of writing are spaced sufficiently so that the ascenders and descenders of letters do not touch]', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 200),
  (4, 'english', 'all', 'Writing composition', 'plan their writing by: discussing writing similar to that which they are planning to write in order to understand and learn from its structure, vocabulary and grammar' || chr(59) || ' discussing and recording ideas', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 210),
  (4, 'english', 'all', 'Writing composition', 'draft and write by: composing and rehearsing sentences orally (including dialogue), progressively building a varied and rich vocabulary and an increasing range of sentence structures English appendix 2' || chr(59) || ' organising paragraphs around a theme' || chr(59) || ' in narratives, creating settings, characters and plot' || chr(59) || ' in non-narrative material, using simple organisational devices [for example, headings and sub-headings]', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 220),
  (4, 'english', 'all', 'Writing composition', 'evaluate and edit by: assessing the effectiveness of their own and others'' writing and suggesting improvements' || chr(59) || ' proposing changes to grammar and vocabulary to improve consistency, including the accurate use of pronouns in sentences', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 230),
  (4, 'english', 'all', 'Writing composition', 'proofread for spelling and punctuation errors', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 240),
  (4, 'english', 'all', 'Writing composition', 'read their own writing aloud to a group or the whole class, using appropriate intonation and controlling the tone and volume so that the meaning is clear', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 250),
  (4, 'english', 'all', 'Writing vocabulary grammar and punctuation', 'develop their understanding of the concepts set out in English appendix 2 by: extending the range of sentences with more than one clause by using a wider range of conjunctions, including: when, if, because, although' || chr(59) || ' using the present perfect form of verbs in contrast to the past tense' || chr(59) || ' choosing nouns or pronouns appropriately for clarity and cohesion and to avoid repetition' || chr(59) || ' using conjunctions, adverbs and prepositions to express time and cause' || chr(59) || ' using fronted adverbials' || chr(59) || ' learning the grammar for years 3 and 4 in [English appendix 2]', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 260),
  (4, 'english', 'all', 'Writing vocabulary grammar and punctuation', 'indicate grammatical and other features by: using commas after fronted adverbials' || chr(59) || ' indicating possession by using the possessive apostrophe with plural nouns' || chr(59) || ' using and punctuating direct speech', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 270),
  (4, 'english', 'all', 'Writing vocabulary grammar and punctuation', 'use and understand the grammatical terminology in English appendix 2 accurately and appropriately when discussing their writing and reading', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 3 and 4', true, null, 280)
on conflict (curriculum, year_group, subject, term, objective) do nothing;

insert into public.curriculum_objectives (year_group, subject, term, strand, objective, source, verbatim, checkpoint, sort_order) values
  (5, 'reading', 'all', 'Reading word reading', 'apply their growing knowledge of root words, prefixes and suffixes (morphology and etymology), as listed in English appendix 1 , both to read aloud and to understand the meaning of new words that they meet', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 10),
  (5, 'reading', 'all', 'Reading comprehension', 'maintain positive attitudes to reading and an understanding of what they read by: continuing to read and discuss an increasingly wide range of fiction, poetry, plays, non- fiction and reference books or textbooks' || chr(59) || ' reading books that are structured in different ways and reading for a range of purposes' || chr(59) || ' increasing their familiarity with a wide range of books, including myths, legends and traditional stories, modern fiction, fiction from our literary heritage, and books from other cultures and traditions' || chr(59) || ' recommending books that they have read to their peers, giving reasons for their choices' || chr(59) || ' identifying and discussing themes and conventions in and across a wide range of writing' || chr(59) || ' making comparisons within and across books' || chr(59) || ' learning a wider range of poetry by heart' || chr(59) || ' preparing poems and plays to read aloud and to perform, showing understanding through intonation, tone and volume so that the meaning is clear to an audience', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 20),
  (5, 'reading', 'all', 'Reading comprehension', 'understand what they read by: checking that the book makes sense to them, discussing their understanding and exploring the meaning of words in context' || chr(59) || ' asking questions to improve their understanding' || chr(59) || ' drawing inferences such as inferring characters'' feelings, thoughts and motives from their actions, and justifying inferences with evidence' || chr(59) || ' predicting what might happen from details stated and implied' || chr(59) || ' summarising the main ideas drawn from more than 1 paragraph, identifying key details that support the main ideas' || chr(59) || ' identifying how language, structure and presentation contribute to meaning', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 30),
  (5, 'reading', 'all', 'Reading comprehension', 'discuss and evaluate how authors use language, including figurative language, considering the impact on the reader', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 40),
  (5, 'reading', 'all', 'Reading comprehension', 'distinguish between statements of fact and opinion', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 50),
  (5, 'reading', 'all', 'Reading comprehension', 'retrieve, record and present information from non-fiction', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 60),
  (5, 'reading', 'all', 'Reading comprehension', 'participate in discussions about books that are read to them and those they can read for themselves, building on their own and others'' ideas and challenging views courteously', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 70),
  (5, 'reading', 'all', 'Reading comprehension', 'explain and discuss their understanding of what they have read, including through formal presentations and debates, maintaining a focus on the topic and using notes where necessary', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 80),
  (5, 'reading', 'all', 'Reading comprehension', 'provide reasoned justifications for their views', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 90)
on conflict (curriculum, year_group, subject, term, objective) do nothing;

insert into public.curriculum_objectives (year_group, subject, term, strand, objective, source, verbatim, checkpoint, sort_order) values
  (5, 'english', 'all', 'Spoken language', 'listen and respond appropriately to adults and their peers', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 10),
  (5, 'english', 'all', 'Spoken language', 'ask relevant questions to extend their understanding and knowledge', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 20),
  (5, 'english', 'all', 'Spoken language', 'use relevant strategies to build their vocabulary', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 30),
  (5, 'english', 'all', 'Spoken language', 'articulate and justify answers, arguments and opinions', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 40),
  (5, 'english', 'all', 'Spoken language', 'give well-structured descriptions, explanations and narratives for different purposes, including for expressing feelings', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 50),
  (5, 'english', 'all', 'Spoken language', 'maintain attention and participate actively in collaborative conversations, staying on topic and initiating and responding to comments', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 60),
  (5, 'english', 'all', 'Spoken language', 'use spoken language to develop understanding through speculating, hypothesising, imagining and exploring ideas', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 70),
  (5, 'english', 'all', 'Spoken language', 'speak audibly and fluently with an increasing command of Standard English', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 80),
  (5, 'english', 'all', 'Spoken language', 'participate in discussions, presentations, performances, role play/improvisations and debates', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 90),
  (5, 'english', 'all', 'Spoken language', 'gain, maintain and monitor the interest of the listener(s)', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 100),
  (5, 'english', 'all', 'Spoken language', 'consider and evaluate different viewpoints, attending to and building on the contributions of others', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 110),
  (5, 'english', 'all', 'Spoken language', 'select and use appropriate registers for effective communication', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 120),
  (5, 'english', 'all', 'Writing transcription (spelling)', 'use further prefixes and suffixes and understand the guidance for adding them', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 130),
  (5, 'english', 'all', 'Writing transcription (spelling)', 'spell some words with ''silent'' letters [for example, knight, psalm, solemn]', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 140),
  (5, 'english', 'all', 'Writing transcription (spelling)', 'continue to distinguish between homophones and other words which are often confused', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 150),
  (5, 'english', 'all', 'Writing transcription (spelling)', 'use knowledge of morphology and etymology in spelling and understand that the spelling of some words needs to be learnt specifically, as listed in English appendix 1', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 160),
  (5, 'english', 'all', 'Writing transcription (spelling)', 'use dictionaries to check the spelling and meaning of words', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 170),
  (5, 'english', 'all', 'Writing transcription (spelling)', 'use the first 3 or 4 letters of a word to check spelling, meaning or both of these in a dictionary', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 180),
  (5, 'english', 'all', 'Writing transcription (spelling)', 'use a thesaurus', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 190),
  (5, 'english', 'all', 'Writing transcription (handwriting and presentation)', 'write legibly, fluently and with increasing speed by: choosing which shape of a letter to use when given choices and deciding whether or not to join specific letters' || chr(59) || ' choosing the writing implement that is best suited for a task', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 200),
  (5, 'english', 'all', 'Writing composition', 'plan their writing by: identifying the audience for and purpose of the writing, selecting the appropriate form and using other similar writing as models for their own' || chr(59) || ' noting and developing initial ideas, drawing on reading and research where necessary' || chr(59) || ' in writing narratives, considering how authors have developed characters and settings in what pupils have read, listened to or seen performed', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 210),
  (5, 'english', 'all', 'Writing composition', 'draft and write by: selecting appropriate grammar and vocabulary, understanding how such choices can change and enhance meaning' || chr(59) || ' in narratives, describing settings, characters and atmosphere and integrating dialogue to convey character and advance the action' || chr(59) || ' précising longer passages' || chr(59) || ' using a wide range of devices to build cohesion within and across paragraphs' || chr(59) || ' using further organisational and presentational devices to structure text and to guide the reader [for example, headings, bullet points, underlining]', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 220),
  (5, 'english', 'all', 'Writing composition', 'evaluate and edit by: assessing the effectiveness of their own and others'' writing' || chr(59) || ' proposing changes to vocabulary, grammar and punctuation to enhance effects and clarify meaning' || chr(59) || ' ensuring the consistent and correct use of tense throughout a piece of writing' || chr(59) || ' ensuring correct subject and verb agreement when using singular and plural, distinguishing between the language of speech and writing and choosing the appropriate register', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 230),
  (5, 'english', 'all', 'Writing composition', 'proofread for spelling and punctuation errors', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 240),
  (5, 'english', 'all', 'Writing composition', 'perform their own compositions, using appropriate intonation, volume, and movement so that meaning is clear', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 250),
  (5, 'english', 'all', 'Writing vocabulary grammar and punctuation', 'develop their understanding of the concepts set out in English appendix 2 by: recognising vocabulary and structures that are appropriate for formal speech and writing, including subjunctive forms' || chr(59) || ' using passive verbs to affect the presentation of information in a sentence' || chr(59) || ' using the perfect form of verbs to mark relationships of time and cause' || chr(59) || ' using expanded noun phrases to convey complicated information concisely' || chr(59) || ' using modal verbs or adverbs to indicate degrees of possibility' || chr(59) || ' using relative clauses beginning with who, which, where, when, whose, that or with an implied (ie omitted) relative pronoun' || chr(59) || ' learning the grammar for years 5 and 6 in English appendix 2', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 260),
  (5, 'english', 'all', 'Writing vocabulary grammar and punctuation', 'indicate grammatical and other features by: using commas to clarify meaning or avoid ambiguity in writing' || chr(59) || ' using hyphens to avoid ambiguity' || chr(59) || ' using brackets, dashes or commas to indicate parenthesis' || chr(59) || ' using semicolons, colons or dashes to mark boundaries between independent clauses' || chr(59) || ' using a colon to introduce a list' || chr(59) || ' punctuating bullet points consistently', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 270),
  (5, 'english', 'all', 'Writing vocabulary grammar and punctuation', 'use and understand the grammatical terminology in English appendix 2 accurately and appropriately in discussing their writing and reading', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 280)
on conflict (curriculum, year_group, subject, term, objective) do nothing;

insert into public.curriculum_objectives (year_group, subject, term, strand, objective, source, verbatim, checkpoint, sort_order) values
  (6, 'reading', 'all', 'Reading word reading', 'apply their growing knowledge of root words, prefixes and suffixes (morphology and etymology), as listed in English appendix 1 , both to read aloud and to understand the meaning of new words that they meet', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 10),
  (6, 'reading', 'all', 'Reading comprehension', 'maintain positive attitudes to reading and an understanding of what they read by: continuing to read and discuss an increasingly wide range of fiction, poetry, plays, non- fiction and reference books or textbooks' || chr(59) || ' reading books that are structured in different ways and reading for a range of purposes' || chr(59) || ' increasing their familiarity with a wide range of books, including myths, legends and traditional stories, modern fiction, fiction from our literary heritage, and books from other cultures and traditions' || chr(59) || ' recommending books that they have read to their peers, giving reasons for their choices' || chr(59) || ' identifying and discussing themes and conventions in and across a wide range of writing' || chr(59) || ' making comparisons within and across books' || chr(59) || ' learning a wider range of poetry by heart' || chr(59) || ' preparing poems and plays to read aloud and to perform, showing understanding through intonation, tone and volume so that the meaning is clear to an audience', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 20),
  (6, 'reading', 'all', 'Reading comprehension', 'understand what they read by: checking that the book makes sense to them, discussing their understanding and exploring the meaning of words in context' || chr(59) || ' asking questions to improve their understanding' || chr(59) || ' drawing inferences such as inferring characters'' feelings, thoughts and motives from their actions, and justifying inferences with evidence' || chr(59) || ' predicting what might happen from details stated and implied' || chr(59) || ' summarising the main ideas drawn from more than 1 paragraph, identifying key details that support the main ideas' || chr(59) || ' identifying how language, structure and presentation contribute to meaning', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 30),
  (6, 'reading', 'all', 'Reading comprehension', 'discuss and evaluate how authors use language, including figurative language, considering the impact on the reader', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 40),
  (6, 'reading', 'all', 'Reading comprehension', 'distinguish between statements of fact and opinion', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 50),
  (6, 'reading', 'all', 'Reading comprehension', 'retrieve, record and present information from non-fiction', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 60),
  (6, 'reading', 'all', 'Reading comprehension', 'participate in discussions about books that are read to them and those they can read for themselves, building on their own and others'' ideas and challenging views courteously', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 70),
  (6, 'reading', 'all', 'Reading comprehension', 'explain and discuss their understanding of what they have read, including through formal presentations and debates, maintaining a focus on the topic and using notes where necessary', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 80),
  (6, 'reading', 'all', 'Reading comprehension', 'provide reasoned justifications for their views', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 90)
on conflict (curriculum, year_group, subject, term, objective) do nothing;

insert into public.curriculum_objectives (year_group, subject, term, strand, objective, source, verbatim, checkpoint, sort_order) values
  (6, 'english', 'all', 'Spoken language', 'listen and respond appropriately to adults and their peers', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 10),
  (6, 'english', 'all', 'Spoken language', 'ask relevant questions to extend their understanding and knowledge', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 20),
  (6, 'english', 'all', 'Spoken language', 'use relevant strategies to build their vocabulary', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 30),
  (6, 'english', 'all', 'Spoken language', 'articulate and justify answers, arguments and opinions', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 40),
  (6, 'english', 'all', 'Spoken language', 'give well-structured descriptions, explanations and narratives for different purposes, including for expressing feelings', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 50),
  (6, 'english', 'all', 'Spoken language', 'maintain attention and participate actively in collaborative conversations, staying on topic and initiating and responding to comments', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 60),
  (6, 'english', 'all', 'Spoken language', 'use spoken language to develop understanding through speculating, hypothesising, imagining and exploring ideas', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 70),
  (6, 'english', 'all', 'Spoken language', 'speak audibly and fluently with an increasing command of Standard English', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 80),
  (6, 'english', 'all', 'Spoken language', 'participate in discussions, presentations, performances, role play/improvisations and debates', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 90),
  (6, 'english', 'all', 'Spoken language', 'gain, maintain and monitor the interest of the listener(s)', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 100),
  (6, 'english', 'all', 'Spoken language', 'consider and evaluate different viewpoints, attending to and building on the contributions of others', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 110),
  (6, 'english', 'all', 'Spoken language', 'select and use appropriate registers for effective communication', 'National curriculum in England: English programmes of study, updated 16 July 2014, spoken language years 1 to 6', true, null, 120),
  (6, 'english', 'all', 'Writing transcription (spelling)', 'use further prefixes and suffixes and understand the guidance for adding them', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 130),
  (6, 'english', 'all', 'Writing transcription (spelling)', 'spell some words with ''silent'' letters [for example, knight, psalm, solemn]', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 140),
  (6, 'english', 'all', 'Writing transcription (spelling)', 'continue to distinguish between homophones and other words which are often confused', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 150),
  (6, 'english', 'all', 'Writing transcription (spelling)', 'use knowledge of morphology and etymology in spelling and understand that the spelling of some words needs to be learnt specifically, as listed in English appendix 1', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 160),
  (6, 'english', 'all', 'Writing transcription (spelling)', 'use dictionaries to check the spelling and meaning of words', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 170),
  (6, 'english', 'all', 'Writing transcription (spelling)', 'use the first 3 or 4 letters of a word to check spelling, meaning or both of these in a dictionary', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 180),
  (6, 'english', 'all', 'Writing transcription (spelling)', 'use a thesaurus', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 190),
  (6, 'english', 'all', 'Writing transcription (handwriting and presentation)', 'write legibly, fluently and with increasing speed by: choosing which shape of a letter to use when given choices and deciding whether or not to join specific letters' || chr(59) || ' choosing the writing implement that is best suited for a task', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 200),
  (6, 'english', 'all', 'Writing composition', 'plan their writing by: identifying the audience for and purpose of the writing, selecting the appropriate form and using other similar writing as models for their own' || chr(59) || ' noting and developing initial ideas, drawing on reading and research where necessary' || chr(59) || ' in writing narratives, considering how authors have developed characters and settings in what pupils have read, listened to or seen performed', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 210),
  (6, 'english', 'all', 'Writing composition', 'draft and write by: selecting appropriate grammar and vocabulary, understanding how such choices can change and enhance meaning' || chr(59) || ' in narratives, describing settings, characters and atmosphere and integrating dialogue to convey character and advance the action' || chr(59) || ' précising longer passages' || chr(59) || ' using a wide range of devices to build cohesion within and across paragraphs' || chr(59) || ' using further organisational and presentational devices to structure text and to guide the reader [for example, headings, bullet points, underlining]', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 220),
  (6, 'english', 'all', 'Writing composition', 'evaluate and edit by: assessing the effectiveness of their own and others'' writing' || chr(59) || ' proposing changes to vocabulary, grammar and punctuation to enhance effects and clarify meaning' || chr(59) || ' ensuring the consistent and correct use of tense throughout a piece of writing' || chr(59) || ' ensuring correct subject and verb agreement when using singular and plural, distinguishing between the language of speech and writing and choosing the appropriate register', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 230),
  (6, 'english', 'all', 'Writing composition', 'proofread for spelling and punctuation errors', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 240),
  (6, 'english', 'all', 'Writing composition', 'perform their own compositions, using appropriate intonation, volume, and movement so that meaning is clear', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 250),
  (6, 'english', 'all', 'Writing vocabulary grammar and punctuation', 'develop their understanding of the concepts set out in English appendix 2 by: recognising vocabulary and structures that are appropriate for formal speech and writing, including subjunctive forms' || chr(59) || ' using passive verbs to affect the presentation of information in a sentence' || chr(59) || ' using the perfect form of verbs to mark relationships of time and cause' || chr(59) || ' using expanded noun phrases to convey complicated information concisely' || chr(59) || ' using modal verbs or adverbs to indicate degrees of possibility' || chr(59) || ' using relative clauses beginning with who, which, where, when, whose, that or with an implied (ie omitted) relative pronoun' || chr(59) || ' learning the grammar for years 5 and 6 in English appendix 2', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 260),
  (6, 'english', 'all', 'Writing vocabulary grammar and punctuation', 'indicate grammatical and other features by: using commas to clarify meaning or avoid ambiguity in writing' || chr(59) || ' using hyphens to avoid ambiguity' || chr(59) || ' using brackets, dashes or commas to indicate parenthesis' || chr(59) || ' using semicolons, colons or dashes to mark boundaries between independent clauses' || chr(59) || ' using a colon to introduce a list' || chr(59) || ' punctuating bullet points consistently', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 270),
  (6, 'english', 'all', 'Writing vocabulary grammar and punctuation', 'use and understand the grammatical terminology in English appendix 2 accurately and appropriately in discussing their writing and reading', 'National curriculum in England: English programmes of study, updated 16 July 2014, years 5 and 6', true, null, 280)
on conflict (curriculum, year_group, subject, term, objective) do nothing;
