-- Guided Childhood - Migration 158
--
-- The cards for the moments that are not about a screen.
--
-- Justin: "there should be lots of cards, can we check, and we should have them
-- for every occasion issue, Dr Becky Good Inside level."
--
-- The audit said the library is strong exactly where it was built to be and
-- thin exactly where a parent is on the floor of a bedroom at seven in the
-- evening. 233 cards: shaper had 81 covering sexting, revenge porn,
-- radicalisation, AI homework and gambling mechanics. Foundation had 26 and
-- builder 42, and mood-confidence, which is the whole territory of big
-- feelings, had ONE card at each of those two stages.
--
-- That is the wrong shape for what this product claims to be. A parent whose
-- five year old is hitting, or lying, or terrified of the dark, does not have a
-- digital problem to solve first. They have a Tuesday. And a parent who opens
-- the app in that moment and finds nothing learns that this is a screens tool
-- to reach for occasionally, rather than the thing they open when parenting is
-- hard. The screen cards are the specialism. These are the ground they stand on.
--
-- The library already crossed this line deliberately, with teeth brushing,
-- dinner refusal and getting dressed. This finishes the job rather than
-- starting something new.
--
-- Written to the same shape as every existing card, because the shape is the
-- product: the words to say, the trap to avoid, why it works, one thing to do
-- tonight, what to do when they push back, and when to check back.
--
-- On why_it_works: mechanism, never a fabricated citation. Every line here
-- describes what is happening in the moment and why the response fits it. Where
-- a claim would need a study behind it to be honest, it is not made.
--
-- On the hard ones: the cards touching disclosure, self harm and grief name
-- real services and say plainly that a script is not the whole answer. A card
-- that implied a parent could handle those alone with the right sentence would
-- be the most dangerous thing in the library.
--
-- Supabase editor rules: idempotent, no DO blocks, flat statements. Re-running
-- changes nothing because every insert is guarded on the title not existing.

-- FOUNDATION, ages 5 to 7. The stage that needed this most.

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'mood-confidence', 'The full body tantrum', 'They are on the floor, screaming, and nothing you say is getting in.', 'I am right here. You are safe. I am not going anywhere until this passes.', 'Stop it right now or you are going to your room.', 'A tantrum at this age is a nervous system that has run out of capacity, not a decision to be difficult. The thinking part of the brain is offline while it is happening, which is why reasoning, bargaining and threats all bounce off. Your calm presence is the only thing that helps, because a regulated adult beside them is what lets their system come back down. The talking comes after, never during.', 'Say nothing except that one line, and repeat it. Do not explain, negotiate or ask questions until they are breathing normally again.', 'They may scream at you to go away. Move back a little so they have space, stay in the room, and say it once more. Going away is the one thing that confirms the fear underneath. Staying without crowding is the answer.', 'A day later, when everyone is calm, name it lightly. Say, ''That was a big one yesterday. Everybody gets those. I will always stay with you.'' It teaches them the feeling was survivable and that you did not think less of them for it.', true, 3000, 'none'
where not exists (select 1 from public.scripts where title = 'The full body tantrum');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'mood-confidence', 'Hitting when they are angry', 'They hit you, or a sibling, when the anger comes up faster than the words.', 'I will not let you hit. I am going to hold your hands. You are allowed to be this angry and you are not allowed to hurt.', 'We do not hit! Say sorry to your brother right now.', 'Two things have to be true at once and most responses only manage one. The feeling is allowed, and the behaviour is stopped. Punishing the feeling teaches a child that anger itself makes them bad, which drives it underground rather than teaching them what to do with it. Physically preventing the hit while naming the anger as legitimate does both jobs in one move. A forced apology in the heat teaches performance, not repair.', 'Stop the hand, name the anger, and leave the apology until they are calm. Then help them do a repair they actually mean.', 'If they say they hate you, do not take the bait or match it. Say, ''You are allowed to feel that. I still love you.'' Hate at this age is almost always the biggest word they have for a feeling they cannot name.', 'In a calm moment later that week, give them somewhere for it to go. Say, ''When you get that angry feeling in your hands, come and find me, or squeeze a pillow as hard as you can.'' A child needs a yes, not only a no.', true, 3001, 'none'
where not exists (select 1 from public.scripts where title = 'Hitting when they are angry');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'mood-confidence', 'Biting', 'They have bitten another child, or you, and you are horrified.', 'Biting hurts. I am going to help you until you can stop. Let us find your words together.', 'That is disgusting. How would you like it if I bit you?', 'Biting is almost always a communication problem rather than a cruelty problem. It clusters where language is not yet fast enough to carry a big feeling, and biting a child back to teach them how it feels only proves that hurting people is what big people do when they are cross. Shame does not build the missing skill. Words do.', 'Watch for the twenty seconds before the next bite. That is where the intervention lives, not in the moment after.', 'If they laugh, it is usually surprise or shame rather than glee. Do not escalate to match it. Say the line again, quietly, and move them away from the situation.', 'Two weeks on, notice out loud when they used words in a moment that would once have been a bite. That is the skill landing, and naming it makes it stick.', false, 3002, 'none'
where not exists (select 1 from public.scripts where title = 'Biting');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'mood-confidence', 'Throwing things', 'Toys, food or the remote go flying when they do not get what they want.', 'I am going to move you away from the things you can throw. When your body is calm we will sort this out together.', 'Right, that toy is going in the bin.', 'Throwing is a discharge of energy that has nowhere else to go. Removing the ammunition rather than the child is the smaller intervention, and confiscating a favourite thing in the middle of it turns a regulation problem into a grief problem on top. Everything is harder after that.', 'Move objects, not the child, unless there is danger. Talk once the throwing stops.', 'If they escalate to throwing something bigger, this is now a safety matter and you can move them. Stay matter of fact about it. It is not a punishment and it should not sound like one.', 'Later, give the energy a legitimate home. Say, ''You can throw the soft ball at the fence any time you like.'' Children need a yes that meets the same need.', false, 3003, 'none'
where not exists (select 1 from public.scripts where title = 'Throwing things');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'mood-confidence', 'Scared of the dark', 'Bedtime has become a negotiation about lights, doors and monsters.', 'Your brain is doing the thing brains do at night, looking for danger. Nothing is here. I have checked and I am nearby.', 'There is nothing to be scared of, do not be silly.', 'Telling a frightened child there is nothing to be scared of asks them to distrust their own alarm system, which does not switch it off and does teach them not to bring you fear. Naming what the brain is doing gives them a story that makes the fear ordinary rather than shameful, and a small predictable ritual gives the system something to settle on.', 'Agree one small thing that stays the same every night: the same check, the same light, the same words. Predictability is the medicine.', 'If they ask you to stay all night, do not promise what you will not do. Say, ''I will sit here for five minutes, and then I will check on you when you are asleep.'' Then actually do the checking. Kept promises are what build the safety.', 'After a fortnight of the same ritual, ask them how bedtime feels now. If it is better, say so out loud. Children rarely notice their own progress unless somebody points at it.', true, 3004, 'none'
where not exists (select 1 from public.scripts where title = 'Scared of the dark');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'mood-confidence', 'Nightmares and waking in the night', 'They wake crying at two in the morning and cannot say what happened.', 'You had a dream. Dreams feel completely real and they are not happening. I am here. Let us get your breathing slow.', 'It was only a dream, go back to sleep.', 'A child waking from a nightmare is in a genuine physiological fear state. Only a dream is factually true and emotionally useless, because their body has not caught up with the fact yet. Naming it as real feeling and not real event, then working on the breathing, treats the state they are actually in.', 'Do not interrogate the dream in the dark. Comfort first, curiosity in the morning if they want to.', 'If they will not settle in their own bed, decide once what your family does and be consistent about it. Either answer is fine. The inconsistency is what makes every subsequent night a negotiation.', 'In the morning, ask lightly if they want to tell you about it. If they do not, leave it. Some children process by talking and some by not talking, and forcing the first on the second helps nobody.', false, 3005, 'none'
where not exists (select 1 from public.scripts where title = 'Nightmares and waking in the night');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'mood-confidence', 'A huge worry about a small thing', 'Something you consider tiny has become the end of the world and you can feel your patience going.', 'That feels really big to you. Tell me about it and I will listen properly.', 'It is not a big deal. You are overreacting.', 'Proportion is learned, not innate, and a child at this age genuinely does not have the comparison set that makes a lost hairband small. Being told they are overreacting does not teach proportion, it teaches that their reading of their own feelings is wrong, which is the beginning of not bringing you the big things later. Take the feeling seriously and the size sorts itself out with time.', 'Listen for two minutes without fixing anything. Most small worries shrink simply from being heard.', 'If it spirals into a list of everything wrong, that is usually tiredness or hunger wearing a worry costume. Meet the body first, then come back to it.', 'A few days later, if it has passed, say so gently. Say, ''Remember how big that felt on Tuesday? Feelings do that. They get huge and then they shrink.'' You are teaching them the shape of their own weather.', false, 3006, 'none'
where not exists (select 1 from public.scripts where title = 'A huge worry about a small thing');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'mood-confidence', 'I am rubbish at this', 'They give up on something hard and turn it on themselves.', 'You are not rubbish at it. You cannot do it YET. Those are really different things and the second one is just true.', 'Of course you are not rubbish, you are brilliant at everything!', 'Blanket reassurance is easy to disprove and a child knows when it is not true, which quietly makes your praise worth less. Naming the gap as a matter of time rather than of capacity is both more honest and more useful, because it points at the one thing they control, which is practice. It also stops a hard afternoon from becoming a fact about who they are.', 'Catch one yet moment today and say the word out loud. It only works if they hear it in the moment, not as a lecture.', 'If they insist they will never be able to, do not argue them out of it. Say, ''You might feel like that today. I have watched you learn hard things before.'' Then name one, specifically.', 'Two weeks later, point at something they can now do that they could not before. Concrete evidence beats encouragement every single time.', true, 3007, 'none'
where not exists (select 1 from public.scripts where title = 'I am rubbish at this');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'mood-confidence', 'They will not let you leave', 'Nursery, school or a babysitter, and the goodbye has become a scene at the door.', 'It is hard to say goodbye. I always come back. I am going now and I will see you at three.', 'Look, I will just stay five more minutes.', 'A long, guilty, drawn out goodbye tells a child there is something here worth being frightened of, because you clearly cannot bear to go either. Short, warm and certain does the opposite. The five more minutes teaches that distress extends your stay, which makes the next goodbye longer rather than shorter.', 'Say the same words every time and then go. The consistency is what builds the confidence.', 'If they cling harder, hand over to the adult who is staying and leave. Nearly every child settles within minutes of the parent being gone. Ask the staff to text you if it helps.', 'After a week, ask the teacher how long the tears last. It is usually far shorter than the parent imagines, and knowing that makes the next morning easier for you as well as them.', false, 3008, 'none'
where not exists (select 1 from public.scripts where title = 'They will not let you leave');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'everyday-routines', 'Whining that will not stop', 'The voice. It has been going for twenty minutes and you can feel yourself about to snap.', 'I want to hear you and I am finding that voice hard. Can you ask me again in your ordinary voice?', 'I cannot understand you when you talk like that.', 'Whining is usually a bid for connection made in the only register that has previously worked. It persists when it intermittently succeeds, which is the pattern hardest to shift, so consistency matters more than severity here. Naming your own difficulty rather than mocking theirs keeps it about the sound and not about them.', 'Respond to the ordinary voice quickly and warmly the moment it arrives. The reward has to be immediate to teach anything.', 'If they carry on, do not engage with the content while the whine is running. Stay friendly, stay nearby, and wait. Arguing with it counts as answering it.', 'Notice within the week whether it is dropping. If it is worse, look at what else is going on. Whining often spikes when a child is short of your attention in bigger ways.', false, 3009, 'none'
where not exists (select 1 from public.scripts where title = 'Whining that will not stop');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'everyday-routines', 'Accidents after being dry', 'They were reliably dry and now they are not, and you are washing sheets again.', 'Bodies do this sometimes. It is not naughty and I am not cross. Let us get you clean.', 'You are too old for this. You did this on purpose.', 'Regression in toileting is common and is usually about something else: a new sibling, a change at school, a house move, anything that has cost a child a sense of control. Shame reliably makes it worse, because anxiety about wetting is itself a cause of wetting. Removing the stakes is treatment, not indulgence. If it persists, or comes with pain or thirst, it is a GP visit rather than a parenting problem.', 'Handle it matter of factly, with no lecture and no audience. Then look at what changed in their world about a month ago.', 'If they are mortified, keep it brief and private. The less of an event you make it, the faster it passes.', 'If it is still happening after a few weeks, or there is any pain, blood or unusual thirst, book the GP. Some regressions are medical and no amount of patience fixes those.', false, 3010, 'none'
where not exists (select 1 from public.scripts where title = 'Accidents after being dry');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'everyday-routines', 'Getting out of the house', 'Shoes, coat, door. Every single morning is a fight and you are always late.', 'Shoes on by the time I count to ten, or I will help you. You choose.', 'Why do you do this to me every single morning?', 'Morning conflict is nearly always a demand for speed made on a child who has no sense of time. A choice with a clear boundary gives them the autonomy they are fighting for while keeping the outcome fixed. The why do you do this question invites a child to explain their character, which no child can do, and starts the day with them cast as the problem.', 'Move one thing to the night before. Bags packed, clothes out, shoes by the door. The morning is not where this gets fixed.', 'If they dawdle deliberately, follow through calmly and help them. Doing what you said you would do is the whole mechanism. Repeating the warning is what teaches them the count means nothing.', 'After a week, tell them you noticed the mornings are easier. Give them the credit even if the change was mostly your own preparation.', true, 3011, 'none'
where not exists (select 1 from public.scripts where title = 'Getting out of the house');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'family-rules', 'After you lost your temper', 'You shouted. They are quiet now and you feel sick about it.', 'I shouted and that was not okay. It was not your fault. I am working on it. I love you.', 'I am sorry I shouted, but you would not listen to me.', 'Repair is the single most useful thing in this whole library, because no parent avoids the rupture and every parent can do the repair. The word but deletes the apology and hands the blame back, which is why the version without it lands so differently. Naming it as yours also teaches a child that a person can own a mistake without falling apart, which is the exact skill you want them to have.', 'Do the repair today, before bed if you can. It does not expire, but sooner is better and shorter is better.', 'If they say it is fine, do not press them into a bigger conversation. The apology is for them to receive however they want, not a scene for you to feel better in.', 'A few days later, if you catch yourself before shouting, notice it privately. Repair works on you as well as on them.', true, 3012, 'none'
where not exists (select 1 from public.scripts where title = 'After you lost your temper');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'family-rules', 'They told a lie', 'They have said something you know is not true, about something small.', 'I think that might not be quite what happened. You are not in trouble for telling me the real version.', 'Do not lie to me! I know exactly what you did.', 'Most lying at this age is wish thinking or fear of your reaction rather than deception. Interrogation teaches a child to lie better, because it demonstrates that being caught is dangerous. Making honesty the safer option is the only thing that produces an honest child, and it costs you the satisfaction of the confrontation.', 'Give them a way back that does not require humiliation. An off ramp is not the same as letting it go.', 'If they stick to the story, do not force a confession. Say, ''Okay. If it turns out differently you can always come and tell me.'' Then leave it. Many children come back within the hour.', 'When they do tell you a hard truth, however small, say thank you for it out loud. That is the moment that builds the teenager who tells you things.', true, 3013, 'none'
where not exists (select 1 from public.scripts where title = 'They told a lie');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'family-rules', 'They will not share', 'Another child wants the toy and yours is not letting go.', 'You are still using it. You can tell them, I am not finished yet. When you are done it is their turn.', 'Do not be selfish, give it to her now.', 'Forced sharing teaches that possession is decided by whoever complains loudest, and that a bigger person can take your things if they judge you have had them long enough. Turn taking based on being finished teaches the actual skill, which is noticing somebody else is waiting and choosing to stop. It looks slower and it is the version that generalises.', 'Try it once with a timer nobody controls, so it is the clock ending the turn and not you.', 'If the waiting child melts down, that is theirs to be helped with, not something the first child has to fix. Say, ''Waiting is really hard. It is nearly your turn.''', 'Watch for the first time they hand something over unprompted. Name it. That is generosity arriving on its own, which is worth far more than compliance.', false, 3014, 'none'
where not exists (select 1 from public.scripts where title = 'They will not share');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'family-rules', 'A new baby and the jealousy', 'The older one has gone backwards, or turned on the baby, since the birth.', 'You had me all to yourself and now you have to share me. That is genuinely hard. You have not lost your place.', 'You should be happy, you are a big brother now!', 'Being told to feel a feeling you do not have does not produce the feeling, it produces concealment. Naming the loss honestly is what lets a child stop defending against it. The regression and the aggression are both bids for the certainty they used to have, and they fade fastest when the certainty is restored rather than demanded.', 'Ten minutes alone with them, with the baby elsewhere, doing something they choose. Protected time beats reassurance.', 'If they say they hate the baby, do not correct it. Say, ''Right now you do. That is allowed. You are still allowed to love them later.'' Corrected feelings go underground.', 'After a few weeks of protected time, see whether the behaviour has settled. If it has, you have your answer about what it was for.', false, 3015, 'none'
where not exists (select 1 from public.scripts where title = 'A new baby and the jealousy');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'school-and-ai', 'Starting school', 'The first weeks, and they are exhausted, tearful or clinging.', 'School uses up all your energy right now. You are not doing it wrong. It gets easier and I will be here every day when you come out.', 'Did you have a good day? Who did you play with? What did you learn?', 'A child who has held themselves together for six hours has nothing left at the door, which is why the meltdown so often lands on the person they feel safest with. Three questions on the walk home is an interview they do not have the resources for. Food, quiet and presence first, conversation later or not at all.', 'Snack in the car or at the gate, no questions for the first twenty minutes. Watch what happens.', 'If they say school is horrible and they are never going back, do not solve it or panic. Say, ''That sounds like a hard day.'' Most of these pass. If it persists for weeks, talk to the teacher.', 'At half term, ask them what the best bit of school is. By then there usually is one, and hearing themselves say it matters.', true, 3016, 'none'
where not exists (select 1 from public.scripts where title = 'Starting school');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'school-and-ai', 'Reading is a battle', 'The reading book comes out and so do the tears, theirs or yours.', 'We are going to read for five minutes and then we are going to stop, whatever happens. I am not going to make you fight through it.', 'We are not stopping until you have finished the page.', 'A child who associates reading with conflict reads less, which is the one thing that reliably makes reading harder. Protecting the relationship with books is worth more over ten years than any single page. A short, guaranteed end point lowers the resistance enough that the five minutes actually happen, which is more reading than a forty minute standoff produces.', 'Set a timer for five minutes. Stop when it goes, even mid sentence, especially if it is going well.', 'If they refuse entirely, read it to them. Being read to is not cheating and it builds the same vocabulary and love of story. Decoding will come.', 'If they are still well behind after a term of this, ask school for a proper assessment. Persistent difficulty is worth investigating rather than practising harder at.', false, 3017, 'none'
where not exists (select 1 from public.scripts where title = 'Reading is a battle');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'school-and-ai', 'Nobody played with me', 'They come out of school and tell you they had nobody at playtime.', 'That sounds lonely. I am sorry today was like that. Tell me what happened.', 'Just go and ask them if you can join in! It is easy.', 'Advice arrives before comfort in most parent responses, and it lands as a correction: you had this problem because you did the wrong thing. A child who feels blamed for their own loneliness stops reporting it. Comfort first buys you the standing to problem solve later, if they even want that.', 'Listen and sympathise. Offer no strategy at all today unless they ask for one.', 'If they say nobody likes them, resist the urge to list their friends. Say, ''Today felt like that. That is a horrible feeling.'' Contradiction feels like not being heard.', 'If it is the same story for more than a week or two, speak to the teacher. Playground dynamics are visible to staff and invisible to you.', true, 3018, 'none'
where not exists (select 1 from public.scripts where title = 'Nobody played with me');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'staying-safe', 'Private parts and body rules', 'You want them to have the language and the rules before they need them.', 'These parts are private. They have proper names. No grown up should ever ask to see or touch them, and if anyone does, you tell me and you will never be in trouble.', 'We do not talk about that.', 'Correct anatomical language and an explicit never in trouble clause are both associated with children being able to disclose. Nicknames and embarrassment make a child unable to describe what happened, and the fear of being blamed is the single most common reason disclosure is delayed. This conversation is protective and it is ordinary. It should sound ordinary.', 'Say it once, calmly, in the bath or getting dressed. It should be as unremarkable as road safety.', 'If they giggle, let them. Say it anyway and move on. The giggling does not mean it did not land.', 'Repeat it every few months in passing. Once is a conversation, repeated is a rule they actually hold. The NSPCC PANTS guidance is a good script if you want a fuller version.', true, 3019, 'none'
where not exists (select 1 from public.scripts where title = 'Private parts and body rules');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'foundation', 'staying-safe', 'If you get lost', 'A busy shop, a park, a station, and you want them to know what to do before it happens.', 'If you cannot find me, stay exactly where you are and look for a grown up with a name badge, or another grown up with children. I will always come and find you.', 'Do not talk to strangers.', 'Do not talk to strangers is the advice most likely to leave a lost child standing silently, because the person who can help them is by definition a stranger. Naming the safe categories gives them a plan they can act on. Staying put also makes them findable, since two moving people in a crowd rarely meet.', 'Practise it once out loud next time you are somewhere busy. Point at who counts as a helper.', 'If they find it frightening, keep it short and confident. Frame it as a plan, like knowing where the fire exit is, rather than as a warning about the world.', 'Ask them a month later what the plan is. If they can tell you, it has landed.', false, 3020, 'none'
where not exists (select 1 from public.scripts where title = 'If you get lost');


-- BUILDER, ages 8 to 10.

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'mood-confidence', 'A feeling they cannot name', 'Something is clearly wrong and every question gets I do not know.', 'You do not have to know what it is. Sit with me for a bit. You do not have to talk.', 'I cannot help you if you will not tell me what is wrong.', 'I do not know is often literally true at this age. The feeling arrived without a label and being pressed for one adds the failure to answer on top of the original distress. Company without demand is the offer that works, and it is also the offer that makes them more likely to talk in ten minutes, or tomorrow.', 'Sit near them doing something else. Side by side beats face to face for this age, every time.', 'If they tell you to go away, go, but say where you will be. Say, ''I will be in the kitchen. Come and find me whenever.'' Then actually be there.', 'Later that week, if they open up about anything at all, do not make it a big moment. Underreacting is what keeps the door open.', true, 3100, 'none'
where not exists (select 1 from public.scripts where title = 'A feeling they cannot name');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'mood-confidence', 'Anxious about school', 'Sunday nights, stomach aches, and a child who does not want to go in.', 'Your tummy really does hurt. Worry does that. We are still going in, and I think you can do this.', 'There is nothing wrong with you, you are fine.', 'School related anxiety usually produces genuine physical symptoms, so telling a child nothing is wrong contradicts what their body is telling them. Believing the symptom while holding the boundary is the combination that works. Avoidance reliably makes anxiety worse over time, because the relief of not going is the thing that trains it, which is why the going in matters even when it is hard.', 'Believe the symptom out loud, then go anyway. Both halves are the treatment.', 'If it becomes a daily battle, get school involved early. A phased morning or a named adult at the gate is standard practice and schools are used to arranging it.', 'If it lasts more than a few weeks, or they are missing days, talk to the GP and the school together. Persistent school anxiety responds well to early help and badly to waiting.', true, 3101, 'none'
where not exists (select 1 from public.scripts where title = 'Anxious about school');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'mood-confidence', 'They tore up their own work', 'It was not good enough for them, so they destroyed it.', 'You wanted it to be better than it came out. That is a horrible feeling. It does not mean the work was bad.', 'Do not be ridiculous, it was really good!', 'Perfectionism is not the same as high standards. It is the belief that anything short of the picture in their head is worthless, and praise aimed at the object does not touch it because the object was never the point. Naming the gap between intention and result is what a perfectionist actually experiences, and hearing it described accurately is a relief.', 'Talk about the feeling, not the drawing. Do not rescue the paper.', 'If they refuse to try again, do not push. Say, ''You can come back to it or not. Either is fine.'' Pressure to retry confirms that the output was what mattered.', 'Model it yourself within the week. Say out loud, ''This did not come out how I wanted, and I am going to leave it as it is.'' Children copy what they see far more than what they are told.', false, 3102, 'none'
where not exists (select 1 from public.scripts where title = 'They tore up their own work');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'mood-confidence', 'Left out of the friendship group', 'The group they were part of has closed and they are on the outside.', 'That is genuinely painful and you have not done anything wrong. Friendship groups shift at your age, and it is horrible while it is happening.', 'They are not worth it, find some new friends.', 'Telling a child to find new friends dismisses the loss and skips to a solution they cannot execute. Being excluded at this age is a real social injury and it deserves to be treated as one. Naming the shifting as normal separates the pain from the conclusion that something is wrong with them, which is the thought that does the lasting damage.', 'Grieve it with them before you strategise. Today is for the feeling.', 'If they blame themselves, do not simply contradict it. Ask what they think happened, listen, and then offer your read. Being argued out of a belief entrenches it.', 'Over the next month, help them widen the field: a club, a cousin, a different set. One group being closed hurts far less when it is not the only one.', true, 3103, 'none'
where not exists (select 1 from public.scripts where title = 'Left out of the friendship group');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'mood-confidence', 'They said they hate themselves', 'It came out in the middle of an argument or a bad evening and it has frightened you.', 'That is a really heavy thing to be carrying. I want to hear about it, and I am not going to tell you off for it.', 'Do not say that! You are wonderful.', 'A fast contradiction closes the conversation, because the child learns the statement was too much for you. Staying calm and curious is what keeps it open. Most of the time this is a big sentence for a bad day, and it should still be taken seriously enough to be talked about rather than corrected.', 'Stay in it for a few minutes. Ask when they feel like that, and listen to the answer.', 'If they shut down, leave the door open explicitly. Say, ''You can tell me that any time and I will not panic.'' Keeping that promise is what makes the next disclosure possible.', 'If it comes up repeatedly, or with any talk of not wanting to be here, that is a GP appointment rather than a parenting conversation. In the UK you can also call Childline on 0800 1111 or the NSPCC helpline on 0808 800 5000 for advice.', true, 3104, 'none'
where not exists (select 1 from public.scripts where title = 'They said they hate themselves');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'family-rules', 'A lie that got bigger', 'A small untruth has grown and they are now defending it hard.', 'I think this has got bigger than you meant it to. There is a way out of this and it is telling me the whole thing now. Then it is over.', 'I am going to keep asking until you admit it.', 'A child defending a lie is usually trapped rather than defiant, and each round of questioning raises the cost of admitting it. Offering a clean exit with a stated end point makes the truth cheaper than the defence, which is the only way this resolves without a war. The over has to be real or it will not work next time.', 'Offer the exit, then keep your word about it being finished.', 'If they still hold the line, stop. Say, ''Okay. The offer stands today.'' Going again immediately just proves the exit was not real.', 'When the truth arrives, thank them for it before you deal with the thing itself. The order matters more than anything else here.', false, 3105, 'none'
where not exists (select 1 from public.scripts where title = 'A lie that got bigger');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'family-rules', 'Rudeness and answering back', 'The tone has turned and you are being spoken to in a way you will not accept.', 'I am not going to talk to you while you speak to me like that. I will be here when you are ready.', 'Do not you dare speak to me like that, who do you think you are?', 'Matching their escalation gives them a bigger fight and teaches that volume wins. Withdrawing from the exchange while staying available holds the boundary without a battle. It also gives you somewhere to go that is not a punishment you will later regret setting.', 'Leave the room rather than raising your voice. Come back when it has passed.', 'If they follow you and keep going, say the line once more and do not engage with the content. Answering any part of it restarts the exchange.', 'Once calm, do the repair from both sides. Say what was not okay, and ask what was going on underneath. Rudeness at this age is often a feeling arriving badly.', true, 3106, 'none'
where not exists (select 1 from public.scripts where title = 'Rudeness and answering back');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'family-rules', 'It is not fair, they get more', 'The fairness accounting between siblings has become a full time job.', 'I do not give everybody the same. I give everybody what they need. Right now you need something different from your sister.', 'Life is not fair, get used to it.', 'Chasing exact equality is unwinnable and it teaches children to audit each other rather than to ask for what they need. Naming a different principle, needs rather than portions, gives them something they can actually use, and it lets you respond to the real request underneath, which is almost always about your attention rather than the object.', 'Ask what they actually want, not what their sibling got. The answers are usually different.', 'If they keep score, do not defend each individual decision. Say the principle again. Litigating cases confirms that the ledger is the right frame.', 'Give each of them something that is theirs alone that week, however small. Sibling fairness fights ease when each child has something not divided.', false, 3107, 'none'
where not exists (select 1 from public.scripts where title = 'It is not fair, they get more');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'everyday-routines', 'The nagging about jobs', 'You have asked four times and it still is not done.', 'I am not asking again. It needs doing before tea. I will not remind you.', 'Why do I have to ask you five times to do anything in this house?', 'Repeated reminders teach a child that your first ask is not the real one, so waiting is rational. Stating the deadline once and then not reminding transfers the responsibility to them, which is the whole point of a job. It only works if you genuinely do not remind, which is harder for the parent than for the child.', 'Say it once. Then stop. Let the consequence be the natural one.', 'If it is not done, do not rescue it or rage about it. Apply whatever you agreed beforehand, calmly, and say nothing else.', 'After a fortnight, notice out loud the first time something is done without asking. That moment is the whole return on the discomfort.', false, 3108, 'none'
where not exists (select 1 from public.scripts where title = 'The nagging about jobs');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'everyday-routines', 'They lose everything', 'Another jumper, another water bottle, another PE bag gone.', 'Things go missing at your age because your brain is busy. Let us build a system so it is not down to remembering.', 'You would lose your head if it was not screwed on.', 'Organisation is a developing skill, not a character trait, and it develops at very different rates. Character framing makes it permanent in a child''s mind and does nothing to improve it. Systems, a named place, a checklist on the door, a photograph of the packed bag, are the actual intervention.', 'Build one system together tonight. Let them design it so it is theirs to use.', 'If they resist the system as babyish, point out that adults use them constantly. Show them your own list.', 'If losses are constant and paired with other difficulties around focus and organisation, it is worth raising with school. Some children need more than a better hook by the door.', false, 3109, 'none'
where not exists (select 1 from public.scripts where title = 'They lose everything');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'school-and-ai', 'Falling behind at school', 'The report, or the teacher, has said they are behind and you are worried.', 'This tells us what you need help with. It does not tell us anything about how clever you are.', 'You are going to have to work much harder from now on.', 'A child who hears behind as a verdict on their ability disengages, because effort feels pointless against a fixed fact. Framing it as information about what to teach next keeps the door open. Work harder is also rarely the actual answer, since most children who are behind are already working as hard as they know how to.', 'Ask the school one specific question: what exactly is the gap, and what would help most at home.', 'If they say they are thick, do not simply deny it. Say, ''You are finding this bit hard. That is different.'' Then point at something they learned that was once hard.', 'Ask school for a review date rather than waiting for the next report. Six weeks of targeted help changes a great deal at this age.', true, 3110, 'none'
where not exists (select 1 from public.scripts where title = 'Falling behind at school');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'school-and-ai', 'Being bullied at school', 'It is happening in the playground or the classroom and they have finally told you.', 'Thank you for telling me. This is not your fault and it is not something you have to sort out on your own. We are going to deal with it together.', 'Just stand up to them and they will leave you alone.', 'Telling a bullied child to handle it themselves is the message they already fear, that this is theirs to fix and adults will not act. Bullying is a safeguarding matter and schools have a legal duty to have a policy on it. Thanking them for telling you also directly counters the shame that keeps most children silent for months.', 'Write down what they have told you, with dates. It is what makes the school conversation concrete rather than a general worry.', 'If they beg you not to tell school, take it seriously and do not promise silence. Say, ''I will not do anything without telling you first.'' Then involve school anyway, with them in the loop.', 'Ask school for a specific plan and a date to review it. If nothing changes, escalate in writing to the head teacher. A written record changes how these are handled.', true, 3111, 'none'
where not exists (select 1 from public.scripts where title = 'Being bullied at school');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'staying-safe', 'A grown up made them uncomfortable', 'They have told you something about an adult that has made your stomach drop.', 'I am really glad you told me. You have done nothing wrong. Tell me what happened and I am not going to be angry with you.', 'Are you sure? That does not sound like him.', 'Doubting the first account is the single most common reason a child stops talking, and once stopped it can take years to restart. Your job in this moment is to receive it, not to investigate it. Repeated questioning can also compromise a later formal interview, which is why professionals ask parents to listen and record rather than to probe.', 'Listen. Write down what they said in their words, as close to exactly as you can, with the date. Do not cross examine.', 'If they backtrack because you looked upset, stay calm and say, ''You can tell me anything and I will not be angry.'' Your face is doing more work here than your words.', 'If you have any concern that a child is at risk, contact the NSPCC helpline on 0808 800 5000, or the police on 101, or 999 if it is urgent. Your local council children''s services can also be called directly. This is not a card that ends with a script; it ends with a professional.', true, 3112, 'none'
where not exists (select 1 from public.scripts where title = 'A grown up made them uncomfortable');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'builder', 'mood-confidence', 'Someone they love has died', 'A grandparent, or a pet, and you do not know what to say.', 'They died. That means their body stopped working and they will not be coming back. It is alright to be sad, and it is alright to be fine sometimes too.', 'We lost Grandad. He has gone to sleep.', 'Euphemisms confuse young children and can create new fears, since a child told somebody went to sleep may become frightened of sleeping. Plain words are kinder than they feel. Naming that grief comes and goes also prevents a child from thinking there is something wrong with them when they are happily playing an hour later, which is entirely normal at this age.', 'Use the real words. Answer the questions they actually ask, and stop there rather than explaining more than was asked.', 'If they ask whether you will die, do not promise you will not. Say, ''Most people live a very long time, and I plan to be here for a very long time.'' Honesty with reassurance beats a promise they may one day remember.', 'Expect the questions to come back in waves for months. That is normal. Winston''s Wish and Child Bereavement UK both have free guidance and helplines for families.', true, 3113, 'none'
where not exists (select 1 from public.scripts where title = 'Someone they love has died');
