-- Guided Childhood - Migration 159
--
-- The same job for the older three stages, and a harder one.
--
-- 158 filled the gap at foundation and builder, where the missing cards were
-- tantrums, lying and the dark. From eleven up the missing cards are grief,
-- separation, a first break up, a body changing, and a disclosure of self harm.
-- The library already covered what happens on a teenager's phone in real depth.
-- It had almost nothing for what happens to a teenager.
--
-- Three of these cards end at a phone number rather than at a script, and that
-- is deliberate. A card that implied a parent could hold self harm, or abuse, or
-- suicidal talk alone with the right sentence would be the most dangerous thing
-- in this product. The words here are for the first ten minutes. The next step
-- is a professional, named on the card, so a frightened parent does not have to
-- go looking.
--
-- Supabase editor rules: idempotent, no DO blocks, flat statements.

-- EXPLORER, ages 11 to 13.

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'mood-confidence', 'Puberty and the mood swings', 'They are furious, then fine, then in tears, and none of it is about what it is about.', 'Your body is doing a lot right now and it makes feelings arrive much bigger than usual. You are not going mad and I am not going anywhere.', 'Are you hormonal? Is this that time?', 'Naming the mechanism separates the child from the mood, which is a relief to somebody who is frightened by the size of their own reactions. Teasing about hormones does the opposite: it makes every genuine feeling dismissible and teaches them not to bring you any of it.', 'Do not take the content of the outburst literally. Respond to the state, not the sentence.', 'If they insist you do not understand, agree. Say, ''You are probably right. Tell me and I will listen.'' Claiming to understand is what ends the conversation.', 'Notice out loud, once, when they handle a big feeling well. At this age they are watching for evidence that they are normal.', true, 3200, 'none'
where not exists (select 1 from public.scripts where title = 'Puberty and the mood swings');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'mood-confidence', 'They have stopped talking to you', 'Answers have become one word and the door is shut more than it is open.', 'I am around. You do not have to talk. I am going to keep offering and you can keep saying no.', 'You never tell me anything any more.', 'Withdrawal at this age is developmental rather than a verdict on you, and guilt is the least effective way to reopen a door. Persistent low pressure availability is what works: driving somewhere, cooking together, walking the dog. Side by side, with no eye contact and an easy exit, is where teenagers talk.', 'Offer one thing that involves being next to each other with something else to look at.', 'If they say leave me alone, do it, and come back tomorrow. The repeated returning is the message, not any individual conversation.', 'Count over a fortnight how many times they started a conversation. It is usually more than it feels like, and it usually rises when the pressure comes off.', true, 3201, 'none'
where not exists (select 1 from public.scripts where title = 'They have stopped talking to you');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'mood-confidence', 'Their body is changing and they hate it', 'Mirrors, baggy clothes, and comments about how they look.', 'Bodies change at really different speeds and yours is doing exactly what it should. I know it does not feel that way.', 'You look lovely, do not be daft.', 'Appearance reassurance keeps the conversation on the topic of how they look, which is the frame doing the damage. Normalising the timing addresses the actual fear, which is almost always about being different rather than about being unattractive. What you say about your own body in front of them matters more than either.', 'Say nothing about anyone''s body, including your own, for a week. Notice how often you nearly did.', 'If they fish for reassurance, give it once and briefly, then change the subject to something they did rather than something they are.', 'If eating changes, or exercise becomes rigid or secretive, take it seriously early. Beat, the UK eating disorder charity, has a helpline on 0808 801 0677 and early help matters enormously here.', false, 3202, 'none'
where not exists (select 1 from public.scripts where title = 'Their body is changing and they hate it');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'mood-confidence', 'The friendship group turned on them', 'They have been dropped, and it may be playing out at school and online at once.', 'This is one of the worst things that happens at your age. I am not going to tell you it does not matter, because it does.', 'In ten years you will not even remember their names.', 'Perspective offered too early reads as dismissal, and it is also not true to their experience: at this age the peer group is the primary social world. Sitting in it with them is what makes you somebody they will tell next time. The perspective can come later, from them, once the wound has closed.', 'Do not fix it, do not ring the other parents, unless there is bullying. Sit with them.', 'If they want to retaliate online, slow it down without lecturing. Say, ''Write it and do not send it tonight.'' Almost nothing survives the morning.', 'Within a couple of weeks, help them get one thing outside school: a club, a team, a cousin. A second social world is the real protection.', true, 3203, 'none'
where not exists (select 1 from public.scripts where title = 'The friendship group turned on them');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'family-rules', 'Telling them about a separation', 'You and their other parent are splitting up and you have to say it out loud.', 'We have decided to live apart. This is a grown up decision and it is not because of anything you did. We both love you and that is not changing.', 'We are separating because your dad has decided he does not want to be here.', 'Children at this age routinely construct a version where they caused it, so the explicit denial has to be said even though it sounds obvious. Keeping the other parent out of the firing line is the single strongest predictor in the separation literature of how well children do, and it is also the hardest thing to manage when you are hurt.', 'Tell them together if you possibly can, and answer only the questions they ask.', 'If they get angry at you, take it without defending yourself. They need somewhere safe to put it, and the safest parent usually gets it first.', 'Expect the questions to come back for months, usually about logistics rather than feelings. Answer the practical ones plainly. Relate has free guidance for families going through this.', true, 3204, 'none'
where not exists (select 1 from public.scripts where title = 'Telling them about a separation');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'family-rules', 'Someone has died', 'A grandparent, a friend, or worse, and they are old enough to understand it fully.', 'I do not have anything that makes this better. I am here and I am not going to rush you through it.', 'They would want you to be strong.', 'Being told what the dead person would want is a demand for a performance at the exact moment a child has nothing to perform with. Grief at this age often comes out as anger, or as apparent indifference, and both are normal. Company without a timetable is the whole offer.', 'Let them grieve their way, including not talking about it and including laughing.', 'If they seem completely unaffected, do not force it. Say, ''Whenever you want to talk about him, I am here.'' Delayed grief is common and pressing rarely brings it forward.', 'Winston''s Wish (08088 020 021) and Child Bereavement UK (0800 02 888 40) both support children and parents directly, and both are free.', true, 3205, 'none'
where not exists (select 1 from public.scripts where title = 'Someone has died');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'school-and-ai', 'Exam and test anxiety', 'SATs, entrance tests, or the first exams that feel like they count.', 'I care how you feel about this a lot more than I care what you get. That is true, and I will still think it when the results come.', 'Just do your best. No pressure!', 'No pressure delivered by a visibly tense parent is heard as pressure with a denial attached. Saying the thing plainly, and then behaving consistently with it when results arrive, is what makes it credible. Children calibrate to what parents do on results day far more than to what they say in the run up.', 'Ask what would make revision easier rather than telling them how to revise.', 'If they refuse to revise at all, look for avoidance rather than laziness. A child convinced they will fail often stops trying to protect themselves from proof.', 'On results day, react the way you promised you would. That is the moment the whole message is either confirmed or destroyed.', false, 3206, 'none'
where not exists (select 1 from public.scripts where title = 'Exam and test anxiety');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'school-and-ai', 'A new diagnosis', 'ADHD, autism, dyslexia, or an assessment that has named something.', 'This explains some things that have been hard. It does not change who you are, and it means we can finally get you the right kind of help.', 'It is just a label, you are perfectly normal.', 'Dismissing the diagnosis to reassure them also dismisses the difficulty they have actually been living with, which many children experience as a relief to have named. Framing it as an explanation and a route to support is both accurate and useful. Explaining it as a deficit is neither.', 'Ask them what they think it means. Correct any frightening misunderstandings, and leave the rest.', 'If they are upset at being different, do not minimise it. Tell them it is a lot to take in, and that they are the same person they were last week.', 'Make sure school has it and that something concrete changes as a result. A diagnosis with no adjustments attached is a piece of paper.', false, 3207, 'none'
where not exists (select 1 from public.scripts where title = 'A new diagnosis');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'everyday-routines', 'Going out on their own', 'They want to walk into town with a friend and you are not sure.', 'I think you are ready for this. Here is the deal: I need to know where, who with, and a message when you get there.', 'Fine, but if anything happens it is on you.', 'Independence granted with clear conditions builds judgement, and independence granted with a threat attached teaches only that you are waiting for them to fail. The conditions are also the thing that lets you say yes to the next, bigger ask, because you have evidence rather than hope.', 'Agree the conditions before the first trip, not after something goes wrong.', 'If they say nobody else has to check in, hold it lightly and firmly. Say, ''This is how we build up to more.'' Framing it as a route to freedom rather than a restriction changes how it lands.', 'When they keep to it, say so and widen it slightly. Trust that visibly grows is what makes the rules worth keeping.', false, 3208, 'none'
where not exists (select 1 from public.scripts where title = 'Going out on their own');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'explorer', 'staying-safe', 'Vapes, alcohol and the first offers', 'It has come up, at a party or from a friend, and you want to get ahead of it.', 'You will get offered this. I would rather you knew what it does than found out at a party. And whatever happens, if you need picking up, I will come, no questions that night.', 'If I ever catch you vaping you are grounded for a month.', 'A threat makes concealment the rational choice, and the child most at risk is the one who cannot ring you. An explicit no questions tonight rescue clause is the single most protective sentence a parent of a teenager can offer, and it costs nothing to give. The conversation about what happened comes the next day.', 'Say the rescue clause out loud and mean it. Then keep it, the first time it is used.', 'If they say everyone does it, do not argue the statistic. Ask what they think about it. Their own reasoning holds better than yours.', 'If they do call, honour it completely. What you do that night decides whether they ever call again.', true, 3209, 'none'
where not exists (select 1 from public.scripts where title = 'Vapes, alcohol and the first offers');


-- SHAPER, ages 14 to 15.

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'shaper', 'mood-confidence', 'They are self harming', 'You have seen marks, or they have told you, and you are frightened.', 'Thank you for letting me see this. I am not angry and I am not going to panic. I want to understand what it does for you.', 'Promise me you will never do this again.', 'Self harm is usually a way of managing unbearable feeling rather than an attempt to end life, and demanding a promise to stop removes the coping strategy without replacing it, which tends to drive it underground rather than away. Calm curiosity keeps the young person talking, and talking is what makes treatment possible. This card is the first ten minutes, not the answer.', 'Stay calm, keep the conversation open, and make a GP appointment. Do not make it conditional on them agreeing.', 'If they beg you not to tell anyone, do not promise secrecy. Say, ''I will not go behind your back, and I am going to get us both some help.'' Broken confidence here is worse than a difficult conversation now.', 'GP first. Childline is 0800 1111, the Samaritans are 116 123, and YoungMinds has a parents helpline on 0808 802 5544. If there is any risk to life, A and E or 999. Keep this card, and use the numbers.', true, 3300, 'none'
where not exists (select 1 from public.scripts where title = 'They are self harming');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'shaper', 'mood-confidence', 'A low mood that will not lift', 'Weeks of flatness, not days. They have stopped doing things they used to like.', 'I have noticed you have not been yourself for a while. I am not going to make you talk about it, and I am going to get you somebody to talk to.', 'You have got nothing to be depressed about.', 'Duration is the signal that matters. A bad fortnight is adolescence; six weeks of anhedonia and withdrawal is worth assessing. Telling a young person they have no reason to feel it adds guilt to depression, which is already one of its features. Acting rather than waiting is the useful parental move.', 'Name what you have observed, specifically, without a diagnosis attached.', 'If they refuse help, go to the GP yourself first and ask for advice. Parents can be seen alone and it is a normal route in.', 'If there is ever talk of not wanting to be here, treat it as urgent. Samaritans 116 123, or 999. Do not wait to see if it passes.', true, 3301, 'none'
where not exists (select 1 from public.scripts where title = 'A low mood that will not lift');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'shaper', 'mood-confidence', 'Their first break up', 'It has ended and the grief is completely out of proportion to how long it lasted.', 'This really hurts. First ones do. I am not going to tell you how long it lasted or how young you are.', 'You are fifteen, there will be hundreds more.', 'Minimising by counting the weeks tells them their feelings are wrong sized, which is the fastest way to make sure you do not hear about the next relationship. The intensity is genuine, and it is often their first experience of loss of this kind. Treat it as one.', 'Feed them, sit near them, say very little.', 'If they want to talk about it repeatedly, let them. Repetition is how the story gets processed.', 'Watch the phone for a fortnight. Break ups at this age often continue online long after they ended in person, which is what turns grief into something worse.', false, 3302, 'none'
where not exists (select 1 from public.scripts where title = 'Their first break up');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'shaper', 'mood-confidence', 'They have told you they are gay, bi or trans', 'They have said it, or half said it, and how you respond in the next thirty seconds matters enormously.', 'Thank you for telling me. I love you exactly the same as I did five minutes ago. Tell me what you need from me.', 'Are you sure? You are very young to know that.', 'Family acceptance is one of the most consistently protective factors we have for LGBT young people, and rejection one of the strongest risks. Are you sure is heard as a rejection whatever it was meant as, because it questions the one thing they have just found the courage to state. Questions can come later; the first response should be acceptance.', 'Get the first thirty seconds right. Everything else can be worked out afterwards.', 'If you are struggling privately, that is allowed, and it is not theirs to carry. Take it to another adult, not to them.', 'Ask who else knows and follow their lead on who is told. Outing them, even accidentally to family, is a serious breach. FFLAG and Stonewall both support parents directly.', true, 3303, 'none'
where not exists (select 1 from public.scripts where title = 'They have told you they are gay, bi or trans');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'shaper', 'family-rules', 'They came home hours late', 'Curfew was eleven and they walked in at one, and you have spent two hours imagining the worst.', 'I am relieved you are home. I was frightened. We are going to talk about this tomorrow, not now.', 'Do you have any idea what time it is? You are grounded for a month.', 'Consequences set in the middle of fear and relief are almost always too big to enforce, and an unenforceable consequence teaches that your sanctions are theatre. Delaying the conversation to a point where you are calm produces a proportionate outcome and models exactly the emotional regulation you want from them.', 'Say those three sentences and go to bed. Do not negotiate at one in the morning.', 'If they are drunk or unwell, that is a care matter tonight and a conversation matter tomorrow. Deal with the body first.', 'Have the conversation the next day, agree what happens next time, and make it something you will actually apply.', true, 3304, 'none'
where not exists (select 1 from public.scripts where title = 'They came home hours late');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'shaper', 'family-rules', 'They want a part time job', 'They have asked, and you are weighing money and independence against school.', 'I think work is good for you. Let us look at the hours together, because school still has to come first.', 'Absolutely not, you need to concentrate on your exams.', 'A first job at this age builds competence and money sense that nothing at home replicates, and a flat refusal removes the chance to shape it. Setting the boundary at hours rather than at the principle keeps you in the negotiation and gives them a real say. In England, there are legal limits on hours for under sixteens, and it is worth checking your council''s rules.', 'Agree a maximum number of hours in writing before they accept anything.', 'If they want more hours than you agreed, tie it to how school is going rather than to your authority. It keeps the argument about evidence.', 'Review it after a month. If grades or sleep have gone, cut the hours as agreed rather than as a punishment.', false, 3305, 'none'
where not exists (select 1 from public.scripts where title = 'They want a part time job');


-- INDEPENDENT, 16 and over.

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'independent', 'everyday-routines', 'They cannot cook, wash or manage a bill', 'They are about to leave and you realise nobody has taught them any of it.', 'I want to teach you the boring stuff before you go, because I would rather you learned it here than at midnight in a flat on your own.', 'You are going to struggle when you have to look after yourself.', 'Warning about a future failure produces anxiety without competence. Teaching produces competence. The window before leaving home is short and the list is genuinely small: five meals, a washing machine, a doctor registration, a bank app and how to challenge a bill.', 'Pick one thing and do it together this week. One a week is plenty between now and September.', 'If they say they will work it out, agree that they probably will, and do it anyway. Frame it as saving money rather than as being cared for.', 'Before they go, have them cook a whole meal and do a whole wash unaided. That is the test, not the lesson.', true, 3400, 'none'
where not exists (select 1 from public.scripts where title = 'They cannot cook, wash or manage a bill');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'independent', 'everyday-routines', 'Learning to drive', 'Lessons have started and you are quietly terrified about the first year alone.', 'The riskiest time is the first year after you pass, with friends in the car at night. That is not me not trusting you, it is what the numbers say.', 'If I ever hear you have been speeding, the car goes.', 'Young drivers are at their highest risk in the months immediately after passing, and peer passengers at night are a well documented factor. Giving the reason rather than the rule lets a young adult own the decision, which is the only enforcement that survives the moment you are not there.', 'Agree the first six months together: passengers, night driving, and the rescue clause if they have been drinking.', 'If they say their friends all drive people about straight away, do not argue about their friends. Ask what they would do if a passenger distracted them at seventy.', 'Revisit it after six months. Loosening it because they earned it works. Loosening it because you gave up does not.', false, 3401, 'none'
where not exists (select 1 from public.scripts where title = 'Learning to drive');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'independent', 'everyday-routines', 'Money of their own', 'Wages, an overdraft, or a first credit offer, and no habits yet.', 'Let me show you the two things that cause most of the trouble: paying interest, and not knowing what leaves your account each month.', 'Do not waste it all like I did at your age.', 'Regret framed as a warning teaches nothing operational. Two concrete mechanisms do. Buy now pay later and gambling adverts both target this age group hard, and naming the mechanism is more protective than naming the danger.', 'Sit down and list their monthly outgoings together, on paper. Most young adults have never seen the total.', 'If they get defensive about their spending, do not audit it. Show them yours instead. Modelling beats inspection.', 'MoneyHelper is the free government backed service and it is genuinely good. Send them the link rather than the lecture.', false, 3402, 'none'
where not exists (select 1 from public.scripts where title = 'Money of their own');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'independent', 'mood-confidence', 'They are anxious about leaving', 'University, work or moving out, and the closer it gets the worse they are.', 'Being nervous about this does not mean it is the wrong decision. You can be ready and frightened at the same time.', 'You will be fine! It is the best time of your life.', 'Cheerful certainty leaves a frightened young adult alone with the fear, and it sets a standard they then feel they are failing. Holding both, ready and frightened, is more accurate and lets them stop treating the nerves as evidence they cannot do it.', 'Ask what specifically they are dreading. It is usually smaller and more solvable than the general dread.', 'If they want to pull out entirely, slow it down rather than arguing. Say, ''Let us look at deferring rather than cancelling.'' Options reduce panic.', 'Ring them in the first fortnight rather than waiting for them to ring you. The first two weeks are the hardest and pride stops most of them calling.', true, 3403, 'none'
where not exists (select 1 from public.scripts where title = 'They are anxious about leaving');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'independent', 'mood-confidence', 'They failed something that mattered', 'Results, an audition, an application, and it has not gone their way.', 'This is genuinely disappointing and I am sorry. It closes one door. It does not tell us anything about what you are capable of.', 'Everything happens for a reason.', 'Silver linings offered on the day ask a person to skip the disappointment, and the skipped feeling tends to come back later as something harder. Naming the loss and separating it from a verdict on their ability is what lets them come back to it. The routes forward are a conversation for next week.', 'Let it be a bad day. Do not plan anything.', 'If they spiral into never being good enough, do not argue. Ask what they would say to a friend in the same position.', 'A week later, look at options together. By then it is problem solving rather than consolation, and they will be able to hear it.', false, 3404, 'none'
where not exists (select 1 from public.scripts where title = 'They failed something that mattered');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'independent', 'family-rules', 'Living at home as an adult', 'They are eighteen or over, still at home, and the old rules do not fit any more.', 'The rules that worked when you were fifteen do not fit now. Let us agree what living here as an adult actually looks like.', 'My house, my rules, while you are under my roof.', 'My house my rules is true and it is also the fastest way to keep a twenty year old behaving like a fifteen year old, because it removes any adult stake in the arrangement. Renegotiating explicitly gives them responsibilities rather than restrictions, which is what actually changes the behaviour you are frustrated by.', 'Write down four things: money, meals, mess, and letting each other know where you are.', 'If they refuse to engage, do not impose it unilaterally. Say, ''I am not doing this to control you, I am doing it so we can live together.'' Then wait.', 'Review it every few months. An agreement that never changes stops being an agreement.', true, 3405, 'none'
where not exists (select 1 from public.scripts where title = 'Living at home as an adult');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'independent', 'family-rules', 'A choice you strongly disagree with', 'A course, a partner, a job, a plan you think is a mistake.', 'I think this is the wrong call and I have told you why once. It is your decision and I am not going to withdraw from you over it.', 'Do not come running to me when it goes wrong.', 'Said once and then held is the version that preserves the relationship and leaves the door open for them to come back. Repeating it converts you into an opponent and makes changing course an admission of defeat, which is the thing most likely to keep them in a bad decision.', 'Say it once, properly, and then stop saying it.', 'If they push for approval you cannot give, be honest without repeating the argument. Tell them you are not going to pretend to agree, and that you are still here.', 'If it does go wrong, do not say you were right. Not saying it is what makes you the person they ring.', true, 3406, 'none'
where not exists (select 1 from public.scripts where title = 'A choice you strongly disagree with');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'independent', 'staying-safe', 'Consent, in relationships, properly', 'They are old enough for this to be a real conversation about their own relationships.', 'Consent is not just a no. It is somebody actively wanting to, every time, and being free to change their mind at any point without it costing them anything.', 'No means no, that is all you need to know.', 'No means no describes the floor and leaves out everything above it, including pressure, drink, and the difference between compliance and enthusiasm. Framing it as an active yes that can be withdrawn is both the legal position and the useful one, and it is a conversation to have with sons and daughters equally.', 'Have it once, plainly, without linking it to anything they have done.', 'If they are mortified, keep it short and say it anyway. Awkward and said beats comfortable and unsaid.', 'Come back to it once more in a different context, for instance about a storyline or a news story. Twice makes it a value rather than a lecture.', true, 3407, 'none'
where not exists (select 1 from public.scripts where title = 'Consent, in relationships, properly');

insert into public.scripts
  (stage_id, category, title, situation, say_this, not_this, why_it_works, tonight, if_they_push_back, check_back, is_free, sort_order, law_flag)
select 'independent', 'school-and-ai', 'University, or not', 'The decision is live and your hopes and theirs may not match.', 'I will back you either way. Let us look at what each route actually costs and leads to, rather than which one sounds better.', 'You will regret it for the rest of your life if you do not go.', 'A decision made to satisfy a parent is the one most likely to be abandoned in the first year. Backing either route removes the need to rebel against the preferred one, and comparing real costs and outcomes gives them something to reason with rather than a verdict to accept.', 'Look at apprenticeships and degrees side by side, with actual numbers.', 'If they choose the one you did not want, say you will back them and then behave like it. Visible disappointment does the damage, not the words.', 'Whatever they choose, check in properly at the three month mark. Both routes have a wobble, and both are survivable.', false, 3408, 'none'
where not exists (select 1 from public.scripts where title = 'University, or not');
