-- Guided Childhood — Migration 161
-- A real question on every AI lesson.
--
-- Counted on the live table: 54 ai_lessons rows, and NOT ONE has a slides deck.
-- So it was never that they had zero questions, it is that there was nothing to
-- have questions in. Every one falls to autoSlidesFromLesson, which builds a
-- deck from the four text fields and closes on one generated prove check with
-- the same two wrong answers every single time:
--
--   "It is best to keep what happens online a secret from a grown up."
--   "None of this really matters, so you can ignore it."
--
-- Fifty four lessons, the same two throwaway wrongs. A reader learns the shape
-- of the answer instead of the idea, which is the opposite of a check.
--
-- The deck built from the text is fine, so this does not replace it. It adds
-- one authored question per lesson and autoSlidesFromLesson uses it in place of
-- the generic close. Nullable and additive: a row without one, or a database
-- without this migration, renders exactly as it does today.
--
-- Every question is written to its own audience. age_7 gets two plain options,
-- age_9 and up get three, and the parent and teacher rows are asked as a grown
-- up would be asked. The wrong answers are the plausible misreading of that
-- lesson, never filler, because a wrong answer worth picking is what makes the
-- right one worth knowing.
--
-- Supabase editor rules: idempotent creates, no DO blocks, no semicolons inside
-- string literals, flat statements only. Keyed by id, so re running is a no op.

alter table public.ai_lessons add column if not exists quiz jsonb;

-- ── Ages 7 ──────────────────────────────────────────────────────────────────

update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"Is AI a thinking person?","options":[{"text":"No, it is a guessing machine","correct":true,"feedback":"That is it. It guesses what comes next, very fast. It is not a person thinking."},{"text":"Yes, it thinks like we do","correct":false,"feedback":"It can sound like it does, but it is guessing from patterns, not thinking."}]}'::jsonb where id = '1248a3d0-20ec-4c0d-81a8-baa7c9171217';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"How does AI learn what to say?","options":[{"text":"By spotting patterns in lots of examples","correct":true,"feedback":"Yes. It sees masses of examples and learns the patterns in them."},{"text":"A teacher tells it every answer","correct":false,"feedback":"Nobody could type in every answer. It finds patterns in examples instead."}]}'::jsonb where id = 'fe4386e1-c5c2-445a-a056-4d6cc7822028';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"What is a chatbot actually doing when it answers you?","options":[{"text":"Guessing the next word, very fast","correct":true,"feedback":"Exactly. Word after word, each one a very fast guess."},{"text":"Looking the answer up in a book","correct":false,"feedback":"It is not looking anything up. It is guessing the next word each time."}]}'::jsonb where id = '10819c6d-dfcf-440d-a6ef-a93a801c94eb';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"An AI tells you something and you are not sure about it. What do you do?","options":[{"text":"Ask a grown up you trust","correct":true,"feedback":"Always. A trusted grown up comes before a screen, every time."},{"text":"Believe it, it sounded sure","correct":false,"feedback":"Sounding sure is not the same as being right. Go and ask your grown up."}]}'::jsonb where id = 'b89ca662-e3e1-431f-a2af-4db843e33b24';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"Can AI be wrong even when it sounds really sure?","options":[{"text":"Yes, sure and wrong at the same time","correct":true,"feedback":"Yes. Sounding sure tells you nothing about whether it is right."},{"text":"No, if it sounds sure it is right","correct":false,"feedback":"It can sound completely sure and still be completely wrong."}]}'::jsonb where id = '6ed5fe67-bbf6-44f7-a2c1-0fa0a02f8892';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"A chatbot asks where you live. What do you say?","options":[{"text":"Nothing, that is private","correct":true,"feedback":"Right. Private things stay for the people you know in real life."},{"text":"Tell it, it is only a computer","correct":false,"feedback":"Even a computer. Your private things stay with people you really know."}]}'::jsonb where id = '2f1ed16f-9aa3-4cd2-b1eb-0aa092f0e6bf';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"An AI says it is happy for you. Does it really feel that?","options":[{"text":"No, real care comes from real people","correct":true,"feedback":"Yes. It can say kind words, but the caring comes from real people."},{"text":"Yes, it really feels happy","correct":false,"feedback":"It is saying the words that fit. Real feelings come from real people."}]}'::jsonb where id = '455144aa-546b-4296-aed8-f76e39e7eb35';

-- ── Ages 9 ──────────────────────────────────────────────────────────────────

update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"What is the honest description of what AI does?","options":[{"text":"It predicts patterns","correct":true,"feedback":"Yes. Prediction, at enormous speed. Thinking is a different thing."},{"text":"It thinks and decides like a person","correct":false,"feedback":"It can look like that from outside. Underneath it is predicting patterns."},{"text":"It searches the internet for the answer","correct":false,"feedback":"Not usually. It predicts from what it learned, rather than looking up."}]}'::jsonb where id = '29c7eea4-ec77-43d7-97cf-9490576d2768';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"An AI learned mostly from one country''s writing. What follows?","options":[{"text":"It will be better on that country and weaker elsewhere","correct":true,"feedback":"Exactly. It is only as good as the examples it saw."},{"text":"It works the same everywhere","correct":false,"feedback":"It cannot. Gaps in what it learned become gaps in what it knows."},{"text":"It will teach itself the rest","correct":false,"feedback":"It does not go and find what it missed. The gap stays."}]}'::jsonb where id = '1f2ac4db-2d80-4bf5-b92c-c336e08e5c65';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"When a chatbot gives you a fact, where did it come from?","options":[{"text":"It predicted the words that usually follow","correct":true,"feedback":"Yes. It predicts likely words. That is why facts need checking."},{"text":"It looked it up in a database","correct":false,"feedback":"It is not looking things up. It is predicting what tends to come next."},{"text":"A person wrote that answer in advance","correct":false,"feedback":"Nobody wrote it. It was generated word by word as you asked."}]}'::jsonb where id = 'fd5a9f8f-53d8-481a-8102-4283c5b3d7f1';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"You need a date for your history homework and the AI gives you one. Next move?","options":[{"text":"Check it somewhere else before you use it","correct":true,"feedback":"Always, for anything that matters. Sure and wrong is a real combination."},{"text":"Use it, it gave an exact date","correct":false,"feedback":"An exact number is not proof. Exactness is easy to generate."},{"text":"Ask the same AI if it is sure","correct":false,"feedback":"It will usually say yes. Check somewhere independent instead."}]}'::jsonb where id = '29cfe6ac-540f-4686-82d7-f31211cb3ec3';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"A photo looks completely real. What does that tell you?","options":[{"text":"Very little, real looking is easy to make now","correct":true,"feedback":"Right. Seeing is not believing any more. Pause and check."},{"text":"It is definitely real","correct":false,"feedback":"Looking real is the easy part now. It tells you almost nothing."},{"text":"It is definitely fake","correct":false,"feedback":"Not that either. You cannot tell by looking, which is why you check."}]}'::jsonb where id = '7e50fb32-b6f5-4cef-89e3-a0342120d840';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"Which of these is safe to type into a chatbot?","options":[{"text":"A question about how volcanoes work","correct":true,"feedback":"Yes. Curiosity is fine. It is your private details that stay out."},{"text":"Your address so it can help better","correct":false,"feedback":"Never. Private details stay out of the chatbot, whatever it offers."},{"text":"Your school and what time you finish","correct":false,"feedback":"That is exactly the kind of detail to keep out of it."}]}'::jsonb where id = 'f558d4bb-a988-4db7-ad02-6f12123ad203';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"What is the best way to use AI on a piece of work?","options":[{"text":"To help you understand it, then do it yourself","correct":true,"feedback":"That is the line. It helps you think. It does not think for you."},{"text":"Let it write the whole thing","correct":false,"feedback":"Then it is not your work and you have not learned the thing."},{"text":"Copy it and change a few words","correct":false,"feedback":"Changing words does not make it yours. Use it to understand instead."}]}'::jsonb where id = '5b8b6d99-9f47-468f-b8a6-7226cec001b8';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"Something upsetting happens and you want to talk. Who first?","options":[{"text":"A trusted adult","correct":true,"feedback":"Always first. An AI is not a swap for a person who knows you."},{"text":"A chatbot, it is always there","correct":false,"feedback":"Always there is not the same as able to help. Go to your adult first."},{"text":"Nobody, sort it yourself","correct":false,"feedback":"You never have to. A trusted adult is there for exactly this."}]}'::jsonb where id = '6d5de491-92dc-4692-9a8a-2af2e3ea8b83';

-- ── Ages 11 ─────────────────────────────────────────────────────────────────

update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"What is AI actually doing when it produces an answer?","options":[{"text":"Powerful pattern prediction","correct":true,"feedback":"Yes. Extremely powerful prediction, and no understanding underneath."},{"text":"Understanding your question and reasoning about it","correct":false,"feedback":"It behaves as if it does. The mechanism is prediction, not understanding."},{"text":"Retrieving a stored correct answer","correct":false,"feedback":"There is no stored answer. It is generated, one prediction at a time."}]}'::jsonb where id = 'd7068b40-10bb-4d22-8c69-f00778598a16';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"Why does what an AI was trained on matter so much?","options":[{"text":"It mirrors that data, gaps and all","correct":true,"feedback":"Exactly. Whatever was missing or skewed in the data comes out the other side."},{"text":"It does not, the AI works it out itself","correct":false,"feedback":"It has nothing else to work from. The training data is the whole world to it."},{"text":"It only matters for pictures, not words","correct":false,"feedback":"It matters for everything it produces, words included."}]}'::jsonb where id = '22be7e2e-5621-4a2f-a291-780c0c469148';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"A language model is very good at one thing. What?","options":[{"text":"Predicting language","correct":true,"feedback":"Right. It predicts language brilliantly. Truth is a separate question."},{"text":"Guaranteeing facts are true","correct":false,"feedback":"Nothing in how it works guarantees truth. It predicts language."},{"text":"Knowing when it does not know","correct":false,"feedback":"That is one of its weakest points. It rarely signals its own gaps."}]}'::jsonb where id = 'a21828a1-8ad6-44c7-8ea3-7c32bfe662f0';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"An AI gives you a confident answer with a source you have never heard of. What is the move?","options":[{"text":"Verify the source exists before using any of it","correct":true,"feedback":"Yes. Invented sources are a classic. Confident does not mean correct."},{"text":"Use it, it named a source","correct":false,"feedback":"Naming a source is easy to generate. Existing is the part to check."},{"text":"Trust it if the rest of the answer looked right","correct":false,"feedback":"The rest looking right is not evidence. Check the source itself."}]}'::jsonb where id = '4ebed05c-3a3f-4131-8548-28eb380682da';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"Which clips are most worth checking before you believe or share them?","options":[{"text":"The ones that could change what people think","correct":true,"feedback":"Exactly. The higher the stakes, the more the check is worth doing."},{"text":"Only the ones that look low quality","correct":false,"feedback":"Quality tells you nothing now. Good fakes look good."},{"text":"None, you can tell a fake by watching closely","correct":false,"feedback":"You cannot, reliably. That is why the habit is checking, not squinting."}]}'::jsonb where id = '32ae29c6-3bfd-4304-be6c-7e4ce6e7acac';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"Where is the line between learning with AI and cheating with it?","options":[{"text":"Using it to understand is fine, passing its work off as yours is not","correct":true,"feedback":"That is the line exactly. Understand with it, never pretend with it."},{"text":"Any use of AI is cheating","correct":false,"feedback":"Not at all. Used to understand something, it is a good tool."},{"text":"It is fine as long as nobody finds out","correct":false,"feedback":"Hiding it is the signal you have crossed the line."}]}'::jsonb where id = '3c36abb2-65bf-4fe2-8592-8d0287e29dee';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"What is the simple rule for what you type into a chatbot?","options":[{"text":"If it is private, keep it out","correct":true,"feedback":"That is the whole rule, and it is easy to hold on to."},{"text":"Private is fine if you delete the chat after","correct":false,"feedback":"Deleting your view of it does not undo what was sent."},{"text":"Private is fine with a well known company","correct":false,"feedback":"The name on the app does not change the rule."}]}'::jsonb where id = '74dda1bc-0406-469a-b812-6a080a81de29';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"Why can an AI be unfair?","options":[{"text":"Because the world it learned from is unfair","correct":true,"feedback":"Yes. It learned from us, so it can carry our unfairness forward."},{"text":"Because it chooses to be","correct":false,"feedback":"It chooses nothing. The unfairness comes in with the data."},{"text":"It cannot be, maths is neutral","correct":false,"feedback":"The maths is neutral. What it learned from was not."}]}'::jsonb where id = '1fc36834-0945-437a-bf21-558b65eff530';

-- ── Ages 13 ─────────────────────────────────────────────────────────────────

update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"An AI writes something that sounds genuinely thoughtful. What has happened?","options":[{"text":"It predicted thoughtful sounding language","correct":true,"feedback":"Yes. However human it sounds, it is prediction, not thought."},{"text":"It thought about it","correct":false,"feedback":"Sounding thoughtful and thinking are different things here."},{"text":"It copied a person who did","correct":false,"feedback":"Not copying either. It generated it by predicting what fits."}]}'::jsonb where id = '9e180982-a7ce-402b-be57-b724e0149aaf';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"Fluent and confident. What does that combination prove?","options":[{"text":"Nothing about whether it is correct","correct":true,"feedback":"Exactly. Fluency is what it is best at. Correctness is separate."},{"text":"It has checked its answer","correct":false,"feedback":"There is no checking step. Fluency comes for free."},{"text":"It is more likely to be right","correct":false,"feedback":"Confidence is not evidence. It reads the same either way."}]}'::jsonb where id = '4394b0da-351c-41dc-9fec-ef18d9d8b76a';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"Which AI answers need checking?","options":[{"text":"Anything that actually matters","correct":true,"feedback":"That is the habit. Trust nothing important until you have checked it."},{"text":"Only ones that sound uncertain","correct":false,"feedback":"The confident ones are the risky ones, because they do not prompt a check."},{"text":"Only ones about famous people","correct":false,"feedback":"It can invent anywhere. Stakes are the test, not topic."}]}'::jsonb where id = 'ed6a5090-97b3-4d9b-a81b-c068cf239c98';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"Someone makes a fake image of a real classmate. How serious is that?","options":[{"text":"A real harm to a real person","correct":true,"feedback":"Yes. The image is fake. The harm to them is completely real."},{"text":"A joke, since it is not real","correct":false,"feedback":"Not being real does not make it harmless. It lands on a real person."},{"text":"Only serious if it spreads widely","correct":false,"feedback":"The harm starts at making it, not at the share count."}]}'::jsonb where id = '5054a450-0f29-4712-bd51-83deff85b5b8';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"An AI is always available and always agrees with you. What does that make it?","options":[{"text":"A tool that is easy to talk to, not a friend","correct":true,"feedback":"Right. It can sound caring. Friendship is not what is happening."},{"text":"A good friend, since it always listens","correct":false,"feedback":"Always agreeing is not friendship. A friend can tell you something hard."},{"text":"Better than friends who are busy","correct":false,"feedback":"Available is not the same as good for you."}]}'::jsonb where id = '9ce61bfb-38f6-4488-9d26-9641a322fd19';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"What is the honest test for AI use in schoolwork?","options":[{"text":"Would you be comfortable saying exactly how you used it","correct":true,"feedback":"That is the test. If you would hide it, you have crossed the line."},{"text":"Whether the school can detect it","correct":false,"feedback":"Detection is not the point. The test is whether you would say so."},{"text":"Whether your friends do the same","correct":false,"feedback":"That tells you nothing about where your own line is."}]}'::jsonb where id = '20401909-a0c2-42fc-bf99-af809dfceb9c';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"What is the safest assumption about anything you type into an AI?","options":[{"text":"It could be kept","correct":true,"feedback":"Assume kept, and share less. That assumption costs you nothing."},{"text":"It disappears when you close the tab","correct":false,"feedback":"Closing the tab is your end of it, not theirs."},{"text":"It is private because it feels private","correct":false,"feedback":"Feeling private is the trap. Typing alone is not the same as private."}]}'::jsonb where id = '09c6d48b-89f0-4980-8308-202837f8b357';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"AI output sounds neutral. Why is that worth watching?","options":[{"text":"A neutral tone can carry bias without flagging it","correct":true,"feedback":"Exactly. The calm voice is what makes the bias easy to miss."},{"text":"Neutral tone means it is unbiased","correct":false,"feedback":"Tone is style. It says nothing about what is underneath."},{"text":"It only matters for political topics","correct":false,"feedback":"It can show up anywhere, including things that look ordinary."}]}'::jsonb where id = '507d4654-02f7-401d-bf7d-317ed1714699';

-- ── Ages 16 ─────────────────────────────────────────────────────────────────

update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"Which pair of statements about AI are both true at once?","options":[{"text":"Genuinely capable, and not conscious","correct":true,"feedback":"Hold both. Dropping either one gets you a worse picture of it."},{"text":"Conscious, and therefore capable","correct":false,"feedback":"Capability here does not require or imply consciousness."},{"text":"Not conscious, and therefore not really capable","correct":false,"feedback":"It is genuinely capable. Dismissing that is its own mistake."}]}'::jsonb where id = '5519f322-513d-4527-b071-baa3dbb1a14a';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"What is the right posture towards a model''s output?","options":[{"text":"Treat it as a draft you judge","correct":true,"feedback":"Yes. A draft to work on, never an answer to obey."},{"text":"Treat it as an answer to follow","correct":false,"feedback":"That hands over the judgement, which is the part that is yours."},{"text":"Treat it as worthless until proven","correct":false,"feedback":"Too far the other way. A draft is genuinely useful."}]}'::jsonb where id = '7655e69e-1a90-46e2-ac50-e586b50da47c';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"When plausible text is effortless to produce, what becomes valuable?","options":[{"text":"The ability to verify","correct":true,"feedback":"Exactly. When plausibility is cheap, verification is the edge."},{"text":"The ability to write fluently","correct":false,"feedback":"That is now the cheap part. Verification is what is scarce."},{"text":"Reading faster","correct":false,"feedback":"Volume is not the problem. Knowing what is true is."}]}'::jsonb where id = 'f8485301-80aa-4871-84e2-ea5d865a22d4';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"You are about to share a striking clip. What comes first?","options":[{"text":"Check the source","correct":true,"feedback":"Before you trust it and before you share it. Sharing is a claim too."},{"text":"Share it and add that you are unsure","correct":false,"feedback":"The hedge rarely travels with it. Check first."},{"text":"Judge it on how professional it looks","correct":false,"feedback":"Production quality is no longer a signal of anything."}]}'::jsonb where id = 'e57e0ba2-c7b7-4c42-96cd-241c26cfa1ed';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"Where does an AI sit when someone is genuinely struggling?","options":[{"text":"After real people, never instead of them","correct":true,"feedback":"Yes. It can have a place. It cannot replace the humans."},{"text":"It is a reasonable substitute for a therapist","correct":false,"feedback":"It is not, and treating it as one is where real harm happens."},{"text":"It has no use at all","correct":false,"feedback":"Too absolute. The rule is that real support comes first."}]}'::jsonb where id = 'd46f0d6c-2591-47dd-a3a7-6c87e8f3d17f';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"What is the workable rule for AI in your studying?","options":[{"text":"If you could not declare it, do not do it that way","correct":true,"feedback":"That is it. Declarable is the standard, not undetectable."},{"text":"Anything goes if the work is good","correct":false,"feedback":"Quality does not settle the honesty question."},{"text":"Avoid AI entirely to be safe","correct":false,"feedback":"Unnecessary. Used declarably, it is a legitimate tool."}]}'::jsonb where id = 'f9f689d6-31db-44a5-b6be-77b96161a2b6';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"What does taking control of your data actually look like?","options":[{"text":"Deciding what you share before you are asked","correct":true,"feedback":"Yes. Decide in advance, or the defaults decide for you."},{"text":"Reading every terms page in full","correct":false,"feedback":"Nobody manages that. A rule you actually hold beats a document you skim."},{"text":"Assuming reputable companies handle it","correct":false,"feedback":"That is handing the decision over, which is the thing to avoid."}]}'::jsonb where id = '48634ac5-5fbc-490c-99c0-0dd0402740fd';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"What makes AI bias different in scale from one unfair person?","options":[{"text":"It applies the same unfairness to enormous numbers of people at once","correct":true,"feedback":"Yes. Scale is the difference, which is why asking who it serves matters."},{"text":"It is not different, just faster","correct":false,"feedback":"Speed plus scale changes what it is. One decision reaches millions."},{"text":"It is less serious because no person meant it","correct":false,"feedback":"Intent does not change what it does to the people on the end of it."}]}'::jsonb where id = '0b38cd9e-3481-40ce-94ab-283684644211';

-- ── Parents ─────────────────────────────────────────────────────────────────

update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"What is the most useful way to describe AI to a child?","options":[{"text":"A prediction tool","correct":true,"feedback":"Plain and accurate, and it holds up as they get older."},{"text":"A robot brain that thinks","correct":false,"feedback":"Warm but wrong, and it has to be unlearned later."},{"text":"Something too complicated to explain","correct":false,"feedback":"It is explainable, and children handle the honest version well."}]}'::jsonb where id = 'a1dcef5e-9312-4617-acab-5b877f358618';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"What does a chatbot guarantee?","options":[{"text":"Fluent language, and nothing about truth","correct":true,"feedback":"Right. It predicts language. Truth is not part of the mechanism."},{"text":"Accurate retrieval of facts","correct":false,"feedback":"There is no retrieval step to be accurate. It predicts."},{"text":"That it will say when it is unsure","correct":false,"feedback":"That is one of the weakest parts of how it behaves."}]}'::jsonb where id = '3a449e4d-9dc1-4e11-a5e0-1572c287c095';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"How is checking best taught at home?","options":[{"text":"As an ordinary habit, done out loud, often","correct":true,"feedback":"Yes. Normal and frequent beats a solemn warning they tune out."},{"text":"As a serious talk when something goes wrong","correct":false,"feedback":"By then it is a telling off. Habits are built before, not after."},{"text":"By blocking the tools until they are older","correct":false,"feedback":"That delays the habit rather than building it."}]}'::jsonb where id = 'c6174b04-3ba7-4bc9-b54a-d2869229155d';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"A child is leaning on an AI companion. What is the concern?","options":[{"text":"It cannot do what real relationships do for them","correct":true,"feedback":"Yes. It is what it displaces that matters, not the app itself."},{"text":"The app is dangerous in itself","correct":false,"feedback":"Usually not. The question is what it is standing in for."},{"text":"Nothing, if they still have friends","correct":false,"feedback":"Worth watching either way, gently and without panic."}]}'::jsonb where id = '0f83481c-cb81-4307-b432-7a9425cb0eb6';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"On something that genuinely matters, who does a child go to first?","options":[{"text":"A trusted adult","correct":true,"feedback":"Always, and it is worth saying out loud before it is needed."},{"text":"Whichever is quickest to reach","correct":false,"feedback":"Convenience is exactly how an AI ends up first. Name the order early."},{"text":"An AI, then an adult if it is serious","correct":false,"feedback":"They are not well placed to judge which is serious. Adult first."}]}'::jsonb where id = '7a3fa324-5633-4d9b-bece-02b8768e8c62';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"What kind of family rule about AI and private information actually holds?","options":[{"text":"One clear line everyone knows","correct":true,"feedback":"Yes. A rule that can be said in one sentence is a rule that gets used."},{"text":"Case by case as things come up","correct":false,"feedback":"Case by case means deciding in the moment, which is when it goes wrong."},{"text":"Whatever each app''s settings allow","correct":false,"feedback":"That hands your family rule to the app."}]}'::jsonb where id = 'e0f3fc47-6831-4675-8566-92959b08c0bf';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"What teaches a child most about using AI well?","options":[{"text":"Watching how you use it","correct":true,"feedback":"Your everyday habits teach more than any rule you state."},{"text":"The rules you set for them","correct":false,"feedback":"Rules help, but they lose to what you are seen doing."},{"text":"What school covers","correct":false,"feedback":"School adds to it. Home is where the habit is picked up."}]}'::jsonb where id = 'aa801028-edbf-423b-86ee-8de341881b2e';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"Which use of AI on homework builds a child rather than cheating them?","options":[{"text":"Using it to understand, then doing the work","correct":true,"feedback":"That is the line. Understanding builds them. Finished work robs them."},{"text":"Using it to produce the finished piece","correct":false,"feedback":"They hand in something real and learn nothing, which is the cost."},{"text":"Any use, as long as they read it after","correct":false,"feedback":"Reading an answer is not the same as having done the thinking."}]}'::jsonb where id = 'd1354ed0-7226-4530-b923-03014d47173d';

-- ── Teachers ────────────────────────────────────────────────────────────────

update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"What should pupils be anchored on first?","options":[{"text":"AI predicts patterns, it does not think","correct":true,"feedback":"Get that in early and the rest of the topic has something to sit on."},{"text":"The list of tools they are allowed to use","correct":false,"feedback":"Tool lists date fast. The mechanism does not."},{"text":"The risks and what to avoid","correct":false,"feedback":"Risks land better once they understand what it actually is."}]}'::jsonb where id = '8d0623e1-270a-429a-bb15-18214e3233c8';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"Why teach the mechanism behind chatbots rather than just the rules?","options":[{"text":"Pupils who grasp it use them critically","correct":true,"feedback":"Yes. Understanding transfers to tools that do not exist yet."},{"text":"It is on the syllabus","correct":false,"feedback":"True or not, that is not the reason it works."},{"text":"It discourages them from using AI","correct":false,"feedback":"The aim is critical use, not avoidance."}]}'::jsonb where id = '0528ee11-e2c9-458b-8636-dbe2d41e5b74';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"An AI produces a confidently wrong answer in class. What is that?","options":[{"text":"A ready made lesson in verification","correct":true,"feedback":"The best kind. Its errors teach the skill better than a warning does."},{"text":"A reason to stop using it","correct":false,"feedback":"The errors are the teaching material. Use them."},{"text":"An embarrassment to move past","correct":false,"feedback":"It is the most useful thing that could have happened in that lesson."}]}'::jsonb where id = 'f73b1819-73a8-46d3-929b-41df56b89c5e';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"What holds academic integrity better than detection tools?","options":[{"text":"Clear expectations everyone shares","correct":true,"feedback":"Yes. Detection is an arms race. Shared expectations are not."},{"text":"Stronger detection software","correct":false,"feedback":"It is unreliable and it puts staff and pupils on opposite sides."},{"text":"Banning AI outright","correct":false,"feedback":"Unenforceable, and it teaches nothing about using it well."}]}'::jsonb where id = '60f39bd3-fd1c-4672-9747-37074dda2d16';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"What is AI bias most useful for in the classroom?","options":[{"text":"Growing critical, fair minded thinkers","correct":true,"feedback":"Yes. It makes something abstract concrete enough to examine."},{"text":"Showing that AI cannot be trusted","correct":false,"feedback":"Too blunt, and it stops the thinking rather than starting it."},{"text":"A standalone lesson once a year","correct":false,"feedback":"It runs through everything. Once a year makes it a box."}]}'::jsonb where id = 'e81eb50e-8cc2-418a-9d52-af376b2af63a';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"A pupil discloses something serious to a chatbot instead of a person. What does that tell you?","options":[{"text":"The safeguarding route still has to lead to a trusted adult","correct":true,"feedback":"Yes. No chatbot replaces an adult in safeguarding, ever."},{"text":"The chatbot handled it","correct":false,"feedback":"It cannot act, escalate, or protect. Only people can."},{"text":"They did the right thing first","correct":false,"feedback":"Understandable, but the route has to end with an adult who can act."}]}'::jsonb where id = 'd5745249-e046-4321-8b2d-1026a8adbf72';
update public.ai_lessons set quiz = '{"type":"choice","phase":"prove","question":"Teaching deepfakes well means two things. Which pair?","options":[{"text":"Question what you see, and never make fakes of real people","correct":true,"feedback":"Both halves. Media literacy alone leaves the harm side untaught."},{"text":"Question what you see, and learn the tools in depth","correct":false,"feedback":"Tool skill without the ethics is the risky half on its own."},{"text":"Avoid the topic until they are older","correct":false,"feedback":"They are already meeting it. Late is the one option that does not work."}]}'::jsonb where id = '3e03da65-3b8c-47cc-a57b-894da3ada38b';
