-- Guided Childhood — Migration 236
-- The twelve gap lessons from the Common Sense curriculum mapping
-- (plans/week-of-2026-08-31-lesson-quality-and-common-sense-gaps.md).
-- Justin, 1 September 2026: "review common sense curriculum and let's copy
-- what's missing from ours for each age", then "Yes lessons".
--
-- Same shape as 076: Rosenshine arc in 7 to 8 slides, two option choices at
-- Foundation, three at Builder, four with subtle distractors from Explorer
-- up, scripts written to the grown up, DiGi closes every lesson. The biggest
-- hole was news literacy between 8 and 12, so Builder and Explorer each gain
-- a news lesson; the rest fill the per age list in the plan. No invented
-- statistics anywhere: where the evidence register would want a number we
-- teach the mechanism instead, which no hostile expert can kill.
--
-- Idempotent: each insert is guarded by title. Dashboard safe: flat
-- statements, dollar quoted JSON. No dashes in any copy.

set lock_timeout = '3s';

-- ════════════════════════════════════════════════════════════════════════════
-- STAGE 1 · FOUNDATION (4 to 7)
-- ════════════════════════════════════════════════════════════════════════════

-- ── Foundation · Safe online: judging a new app BEFORE anything goes wrong ──
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'foundation', 'parent', 'safety', 'Is this app safe to open?',
  'Stop and tell covers what happens after something feels wrong. This lesson covers the moment before: a new game or video appears, and the child learns the traffic light, green means my grown up said yes, amber means ask first, red means we do not open it.',
  'Young children meet new apps and videos constantly, usually through a sibling or a friend. A simple before rule beats any amount of after comfort, and asking first is a habit that scales all the way to the teenage years.',
  'Walk through the apps on the tablet together and give each one a light: green for the ones you have said yes to, amber for ask me first. Let your child do the sorting. The sorting is the lesson.',
  'Green means yes, amber means ask first. New things always start amber.',
  'How do I teach my 5 year old which apps and videos are okay to open?',
  975, 'live',
  $g1$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Foundation · Ages 4 to 7 · Safe online","title":"Is this app safe to open?","body":"A sofa lesson about new games and videos, and the traffic light that tells us what to do before we open them.","script":"Recall first: what do we do when something on a screen feels wrong? Stop and tell. Today is about the moment BEFORE: a brand new game or video appears. What do we do before we even open it?"},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can use the traffic light before I open anything new: green is yes, amber is ask first.","why":"New games and videos pop up all the time. The traffic light means I always know what to do, even when my grown up is not right next to me.","gains":["I know what green, amber and red mean","I know every new thing starts amber","I know asking first is always free"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🚦","heading":"The traffic light","body":"Every game, app and video gets a light. Green: my grown up said yes, I can open it. Amber: I do not know yet, so I ask first. Red: we looked together and decided no, so it stays closed. Simple as crossing the road.","script":"Borrowed with pride from how schools teach this age: children this young cannot judge an app, and we never ask them to. The light does the judging in advance. Your job later is to actually give lights to the things they use, so green means something real."},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🆕","heading":"New things start amber","body":"A new game your friend showed you? Amber. A video that starts by itself after your video? Amber. A button that says download? Amber. Amber does not mean bad. It just means: ask first, and then we will know its real colour together.","script":"The framing matters: amber is not a punishment or a suspicion, it is simply not sorted yet. Answer every amber ask warmly and quickly, even mid task, because the speed of your yes is what keeps the asking habit alive."},
    {"type":"choice","phase":"practise","minutes":2,"question":"Your friend shows you a brilliant new game and you really want to play it at home. What light is it?","options":[{"text":"Amber, because it is new, so I ask my grown up first","correct":true,"feedback":"Exactly. New things always start amber, even brilliant ones. Ask first and we will sort it together."},{"text":"Green, because my friend already plays it","correct":false,"feedback":"Your friend's grown up said yes for your friend. Your grown up has not seen it yet, so it starts amber."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"You ask about an amber game and your grown up says: let me look at it with you. Is asking a good thing or a bad thing?","options":[{"text":"A good thing, asking first is always free","correct":true,"feedback":"Always. Asking never gets you in trouble, and lots of ambers turn green after we look together."},{"text":"A bad thing, because now I might not get to play","correct":false,"feedback":"Asking is never the reason a game says no. Looking together is how ambers become greens."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Green is yes. Amber is ask first.","New things always start amber.","Asking first is always free, and it is how ambers turn green."]}
  ]$g1$::jsonb
where not exists (select 1 from public.lessons where title = 'Is this app safe to open?');

-- ── Foundation · Online relationships: belonging, not only rules ────────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'foundation', 'parent', 'relationships', 'My online neighbourhood',
  'Even at this age a child is part of online places: the game where cousins play, the video comments, the class photo stream. This lesson reframes the internet from a scary place with rules into a neighbourhood where we are kind, we take turns, and we help.',
  'Rules tell a child what not to do. Belonging tells them who to be. A child who thinks of the internet as their neighbourhood treats the people in it like neighbours, which is the root of every good digital habit that follows.',
  'Name your family''s online neighbourhood together: the game with the cousins, the video calls with grandma, the photos we share. Then ask: what makes someone a good neighbour there? Their answers will be better than any rule.',
  'The internet is a neighbourhood, and we are good neighbours in it.',
  'How do I talk about being kind online with a 6 year old who barely goes online?',
  976, 'live',
  $g2$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Foundation · Ages 4 to 7 · Online friends","title":"My online neighbourhood","body":"A sofa lesson about the online places we already belong to, and what good neighbours do there.","script":"Recall: who are screen people, even the friendly ones? Strangers. But some online places are full of people we DO know: cousins in the game, grandma on the video call. Today is about those places, our online neighbourhood."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can name my online neighbourhood and be a good neighbour in it.","why":"We are already part of online places with real people we love in them. Places are nicer when the people in them are kind.","gains":["I can name the online places my family belongs to","I know what a good neighbour does","I know taking turns and kind words count online too"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🏘️","heading":"You already have an online neighbourhood","body":"Think about it: the game where you play with your cousin. The video call where grandma waves. The photos your family shares. Those are online places, and the people in them are your neighbours. You belong there.","script":"This is deliberately warm before it is careful. The school frameworks start community this early for a reason: a child who feels they belong somewhere protects that place. Map YOUR family's real online places out loud, with names. Specific beats general at this age, every time."},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🤝","heading":"Good neighbours online","body":"Good neighbours are the same everywhere. They take turns. They use kind words. They help when someone is stuck. They wave hello and goodbye. On a screen you cannot see faces, so kind words matter even more, because words are all your neighbour gets.","script":"Link it to what they already know: we do not shout in grandma's house, we do not grab toys at a friend's. Same person, same manners, screen or no screen. One sentence to plant now and repeat for a decade: you are the same kind person everywhere you go."},
    {"type":"choice","phase":"practise","minutes":2,"question":"Your cousin keeps losing in your game and feels sad. What does a good neighbour do?","options":[{"text":"Help them, take turns, and say kind words","correct":true,"feedback":"That is a good neighbour. The game matters much less than the cousin."},{"text":"Laugh, because losing is funny","correct":false,"feedback":"It might feel funny for a second, but a good neighbour helps. Kind words keep the neighbourhood nice for everyone."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"Why do kind words matter extra much on a screen?","options":[{"text":"Because your neighbour cannot see your face, so words are all they get","correct":true,"feedback":"Exactly. No smile, no wave, just your words. So we make them kind ones."},{"text":"Because screens make words louder","correct":false,"feedback":"Not louder, but lonelier. Without your face and your voice, the words do all the work."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["You already belong to an online neighbourhood.","Good neighbours take turns, help, and use kind words.","You are the same kind person everywhere you go."]}
  ]$g2$::jsonb
where not exists (select 1 from public.lessons where title = 'My online neighbourhood');

-- ════════════════════════════════════════════════════════════════════════════
-- STAGE 2 · BUILDER (8 to 10)
-- ════════════════════════════════════════════════════════════════════════════

-- ── Builder · Real or fake: altered photos, at the age belief forms ─────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'builder', 'parent', 'information', 'Is seeing believing?',
  'At 8 to 10 a photo still feels like proof. This lesson breaks that gently: pictures can be cropped, staged, filtered and faked, so a photo is a claim, not a fact, and the question to ask is who took this and why.',
  'Photo trust is the root of every later misinformation problem. A child who learns at 8 that pictures are made by people, with choices and reasons, meets deepfakes at 13 already holding the right question.',
  'Play the cropping game at dinner: take a photo of the table, then crop it so the mess is gone and it looks perfect. Same table, different story. Ask: which photo is true? Both, and neither. That is the lesson.',
  'A photo is a claim, not a fact. Ask who made it and why.',
  'How do I teach my 9 year old that photos online can be fake or misleading?',
  977, 'live',
  $b3$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Builder · Ages 8 to 10 · Real or fake","title":"Is seeing believing?","body":"A ten minute lesson on why a photo is not proof, and the two questions that see through almost every picture.","script":"Starter recall: what are the three tells of a trick? Rushing, promising, asking. Today we meet a quieter kind of trick: a picture that tells only part of the truth."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can treat a surprising photo as a claim and ask who made it and why.","why":"Pictures feel like proof, but every picture was made by a person who chose what to show. Knowing that is a superpower.","gains":["I know four ways a real photo can still mislead","I can ask who made this and why","I know surprise is my signal to slow down"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"✂️","heading":"Four ways a picture can bend the truth","body":"Cropped: the messy bit is cut out of the frame. Staged: everything was arranged before the photo. Filtered: colours and faces are polished until they glow. Faked: the picture was changed or made by a computer. All four can happen to one photo, and it still looks completely real.","script":"Have your child say the four back: cropped, staged, filtered, faked. Then find a tame example together, a perfect looking food photo works well. The goal is not suspicion of everything, it is knowing that every photo had a maker who made choices."},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🔍","heading":"Who made this, and why?","body":"You do not need to be a detective to check a picture. Two questions do most of the work. Who made this? A friend, a shop, a stranger, nobody knows? And why? To make me laugh, to sell me something, to shock me? A photo that wants something from you deserves a slower look.","script":"This is the same escalation move as Spot the trick: the child does not have to reach a verdict, they just ask the two questions and bring the odd ones to you. Model it out loud when YOU see a too good photo: hmm, who made this, and what do they want me to feel?"},
    {"type":"choice","phase":"practise","minutes":2,"question":"A photo shows a giant shark swimming next to a surfer, and it looks amazing. What is the smart first move?","options":[{"text":"Believe it, photos show what really happened","correct":false,"feedback":"Photos show what the maker chose to show, and this one might be faked or staged. Surprise is your slow down signal."},{"text":"Ask who made this and why, and show a grown up if it is everywhere","correct":true,"feedback":"That is the move. Amazing pictures are exactly the ones worth the two questions."},{"text":"Share it quickly so your friends see it first","correct":false,"feedback":"Sharing fast spreads the picture before anyone has checked it. The two questions come first."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"A photo of a toy looks perfect in the advert but the real toy looks worse at home. Which truth bender was probably at work?","options":[{"text":"Staged and filtered, the photo was arranged and polished to sell","correct":true,"feedback":"Exactly. Adverts stage and polish because they want something from you: your pocket money."},{"text":"Faked by a computer, the toy does not exist","correct":false,"feedback":"Probably not fake, the toy exists. It was staged and polished, which is quieter but works better."},{"text":"Nothing, cameras just make things look better","correct":false,"feedback":"Cameras record choices. Someone chose the light, the angle and the polish, because the photo had a job to do."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["A photo is a claim, not a fact.","Cropped, staged, filtered, faked. Four benders to know.","Who made this, and why? Two questions, most of the answer."]}
  ]$b3$::jsonb
where not exists (select 1 from public.lessons where title = 'Is seeing believing?');

-- ── Builder · News literacy, first rung: what news is and what adverts are ──
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'builder', 'parent', 'information', 'Reading news online',
  'By 8 to 10 news reaches children sideways: a headline on a shared tablet, a YouTuber reacting, a friend retelling. This lesson gives them the three coats a story can wear, news, opinion and advert, and the habit of asking which coat this one has on.',
  'This is the biggest hole in most children''s digital education: news literacy is taught at 6 or at 13 and skipped in between, exactly when children start meeting real headlines. Naming the three coats now makes every later lesson land.',
  'Next time a headline crosses the kitchen, play which coat: is this telling me what happened, telling me what someone thinks, or selling me something? One question, asked lightly, again and again.',
  'Every story wears a coat: news, opinion or advert. Ask which one.',
  'How do I start teaching my 9 year old what real news is?',
  978, 'live',
  $b4$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Builder · Ages 8 to 10 · Real or fake","title":"Reading news online","body":"A ten minute lesson on the three coats a story can wear, and how to tell them apart before you believe or share.","script":"Starter recall: what are the two questions for a surprising photo? Who made this, and why. Today we ask the same questions about stories, because stories wear coats."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can tell whether a story is news, opinion or an advert before I believe it.","why":"Stories reach me every day: headlines, videos, friends retelling. Knowing which coat a story wears tells me how much to trust it.","gains":["I can name the three coats","I can spot the clues for each one","I know sharing waits until I know the coat"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🧥","heading":"The three coats","body":"News tells you what happened: who, what, where, when, checked by someone whose job it is. Opinion tells you what someone thinks: I reckon, the best, the worst. An advert wants your money or your click, however it is dressed. The same event can appear in all three coats on the same day.","script":"Give one concrete example of each from your own week. The checked by someone whose job it is line matters: real news organisations employ people to verify before publishing, and getting it wrong costs them. That is the difference between news and a stranger typing."},
    {"type":"scenario","phase":"practise","minutes":2,"label":"Which coat?","platform":"feed","handle":"GamerNewsNow","avatar":"🎮","meta":"1h · Sponsored","text":"BREAKING: this new headset changes gaming FOREVER. Every serious player needs one. Tap to get yours before the price goes up!","image":"🎧","stats":"❤ 3.1K   ↻ 890","prompt":"News, opinion or advert? Look for the clues before you decide.","script":"Walk the clues together: the word Sponsored in the meta line, needs one, tap to get yours, price pressure. It is dressed as breaking news and it is an advert head to toe. This is the practise moment: let your child find the clues before you point at them."},
    {"type":"choice","phase":"practise","minutes":2,"question":"That headset post: which coat is it wearing?","options":[{"text":"News, because it says BREAKING","correct":false,"feedback":"BREAKING is part of the costume. News tells you what happened. This tells you what to buy."},{"text":"An advert dressed as news","correct":true,"feedback":"Caught it. Sponsored, tap to get yours, hurry before the price goes up. That coat is bought and paid for."},{"text":"Opinion, because someone likes the headset","correct":false,"feedback":"Close, it does sound like an opinion. But the tap to buy and the Sponsored tag tell you money is the point."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"A YouTuber you love says a new game is the best ever made. Which coat is that, and what do you do with it?","options":[{"text":"Opinion, so I can enjoy it without treating it as fact","correct":true,"feedback":"Exactly. Opinions are allowed and fun. You just do not confuse the best ever with checked and true."},{"text":"News, because they have lots of subscribers","correct":false,"feedback":"Subscribers measure popularity, not checking. A million people can watch one person's opinion."},{"text":"An advert, all YouTubers are paid to say things","correct":false,"feedback":"Some are, and they must say ad when they are. Without that, this is opinion: what one person thinks."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["News, opinion, advert. Three coats.","Ask which coat before you believe or share.","Real news is checked by people whose job it is."]}
  ]$b4$::jsonb
where not exists (select 1 from public.lessons where title = 'Reading news online');

-- ── Builder · Online relationships: how we play, not only who with ──────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'builder', 'parent', 'relationships', 'Keeping games fun',
  'Friends you know covers who a child plays with. This lesson covers how: winning without gloating, losing without exploding, and what to do when someone in the game turns nasty, mute, leave, tell, never fight back in the chat.',
  'Games are where this age actually practises friendship under pressure. Rage, gloating and pile ons in game chat are most children''s first taste of online conflict, and the habits formed here walk straight into group chats at 11.',
  'After the next gaming session, ask one question: was everyone still having fun at the end? If not, talk through what happened with the mute, leave, tell ladder, no blame attached.',
  'Play so everyone wants a rematch. If it turns nasty: mute, leave, tell.',
  'My 9 year old rages at the game and squabbles in game chat. What do I teach?',
  979, 'live',
  $b5$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Builder · Ages 8 to 10 · Online friends","title":"Keeping games fun","body":"A ten minute lesson on being brilliant to play with, and the three step ladder for when a game turns nasty.","script":"Starter recall: how do we tell a real friend online from a stranger who plays one? Real friends we know from real life. Today is about how we play WITH those friends, because games test friendship like nothing else."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can win kindly, lose steadily, and use mute, leave, tell when chat turns nasty.","why":"Games are more fun when everyone wants a rematch. And knowing the ladder means nasty chat never has to be my problem to fix alone.","gains":["I know what a good winner and a good loser look like","I can feel rage coming and take a breather","I know the mute, leave, tell ladder"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🏆","heading":"The rematch test","body":"Here is how to know if you played well: does everyone want a rematch? Good winners say good game and mean it. Good losers say well played and mean it. Gloating and rage both fail the rematch test, because nobody queues up to play with either.","script":"The rematch test gives your child a standard they can check themselves against, which beats any rule you could set. Name the body signal too: rage arrives in the body first, hot face, tight hands. Feeling it come is the moment to take a breather, and that noticing is a genuine skill worth praising."},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🪜","heading":"Mute, leave, tell","body":"Sometimes someone in a game turns nasty: mean chat, unkind names, spoiling on purpose. You never have to fight back, and you never have to stay. The ladder: mute them so the words stop reaching you. Leave the game if it is still not fun. Tell your grown up if it was aimed at you or would not stop.","script":"The crucial line is you never have to fight back. Children believe replying is standing up for themselves; in game chat it only feeds the fire and sometimes gets them reported too. The ladder gives them power without a fight. All three rungs are wins, tell especially."},
    {"type":"choice","phase":"practise","minutes":2,"question":"You just won three games in a row. Which message passes the rematch test?","options":[{"text":"EZ. You are all terrible at this game","correct":false,"feedback":"That is gloating, and it fails the test: nobody wants a rematch with it. Winning does not need a victory lap."},{"text":"Good games! That last one was so close","correct":true,"feedback":"That passes. You told the truth, you were kind, and everyone wants to play you again."},{"text":"Say nothing and leave straight away","correct":false,"feedback":"Not unkind, but a good game costs nothing and makes the whole lobby better."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"Someone in the game keeps calling you names in chat. What is the ladder?","options":[{"text":"Reply with worse names so they stop","correct":false,"feedback":"Fighting back feeds it, and now the chat has two people being unkind. The ladder never includes fighting back."},{"text":"Mute them, leave if it is still not fun, and tell your grown up","correct":true,"feedback":"That is the ladder, in order. Every rung is a win, and telling is the strongest one."},{"text":"Stay quiet and keep playing however bad it feels","correct":false,"feedback":"You never have to sit inside nasty chat. Mute is one tap, and it is always allowed."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Play so everyone wants a rematch.","Rage arrives in the body first. Feel it, breathe, step back.","Mute, leave, tell. You never have to fight back."]}
  ]$b5$::jsonb
where not exists (select 1 from public.lessons where title = 'Keeping games fun');

-- ── Builder · Identity: stereotypes in games and videos, named early ────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'builder', 'parent', 'identity', 'Boys, girls and the screen',
  'Games, videos and adverts quietly teach children what boys and girls are supposed to like, wear and be good at. This lesson makes the quiet loud: a stereotype is a shortcut somebody chose, and you get to like what you like.',
  'Stereotype ideas harden between 8 and 10, fed heavily by what children watch. Naming the pattern now, lightly and without a lecture, is the groundwork for the harder conversations the teenage internet will demand.',
  'Watch ten minutes of their favourite videos together and count shortcuts as a game: who gets to be clever, who gets to be strong, who is selling what to whom. Counting beats lecturing every time.',
  'A stereotype is a shortcut someone chose. You get to like what you like.',
  'The games and videos my 8 year old watches are full of gender stereotypes. What do I say?',
  980, 'live',
  $b6$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Builder · Ages 8 to 10 · Being you","title":"Boys, girls and the screen","body":"A ten minute lesson on the shortcuts screens take about boys and girls, and why you get to like what you like.","script":"Starter recall: in Your first avatar we chose what to show about ourselves. Today we look at the choices screens make about us: what they show boys and girls liking, wearing and being good at."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can spot a stereotype shortcut on a screen and know it is a choice, not a rule.","why":"Screens repeat the same shortcuts so often they start to feel like rules. Spotting them keeps me free to like what I actually like.","gains":["I know what a stereotype shortcut is","I can spot one in a game or advert","I know real people are bigger than shortcuts"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"✂️","heading":"Screens take shortcuts","body":"Making a game or an advert takes ages, so makers use shortcuts: the boy likes fighting games, the girl likes pink and ponies, the hero is strong, the helper smiles. A stereotype is exactly that, a shortcut about a whole group of people. Quick to make. Often wrong.","script":"Keep it mechanical, not moral, at this age: stereotypes exist because they are CHEAP for the maker, not because they are true. That framing lets children spot them like they spot advert tricks, without anyone feeling told off for liking pink or fighting games, which they are entirely allowed to do."},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🎨","heading":"Real people are bigger than shortcuts","body":"Here is what the shortcut misses: real boys dance, bake and cry at sad films. Real girls code, box and captain teams. And liking the expected thing is fine too! The shortcut is not wrong because pink is wrong. It is wrong because it decides for you before you got to choose.","script":"The both directions point is what keeps this honest: a girl who loves pink is not a problem and neither is a boy who loves football. The problem is only ever the deciding for you. Land it personally: name things people in your own family like that break the shortcut, and things that match it. Both are fine. That IS the lesson."},
    {"type":"choice","phase":"practise","minutes":2,"question":"An advert shows only boys playing the new building set, but your friend who is a girl would love it. What is going on?","options":[{"text":"The advert took a shortcut, the set is for whoever likes building","correct":true,"feedback":"Exactly. The maker chose a shortcut. The toy has no opinion about who plays with it."},{"text":"Building sets are really for boys, the advert knows best","correct":false,"feedback":"The advert is a choice someone made in an office, not a rule. Whoever loves building gets to build."},{"text":"Your friend should like something else instead","correct":false,"feedback":"Backwards! People do not change to fit shortcuts. Shortcuts are just too small to fit people."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"Why do games and adverts use so many stereotype shortcuts?","options":[{"text":"Because shortcuts are true about everyone","correct":false,"feedback":"They are not, that is the point. Plenty of real people never match the shortcut at all."},{"text":"Because shortcuts are quick and cheap for the people making them","correct":true,"feedback":"That is it. Shortcuts save the maker time. Spotting them is how you stop them deciding for you."},{"text":"Because there is a law about what boys and girls like","correct":false,"feedback":"No such law anywhere. Just habits and shortcuts, and both can be spotted and skipped."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["A stereotype is a shortcut somebody chose.","Real people are always bigger than shortcuts.","You get to like what you like. That is the whole rule."]}
  ]$b6$::jsonb
where not exists (select 1 from public.lessons where title = 'Boys, girls and the screen');

-- ════════════════════════════════════════════════════════════════════════════
-- STAGE 3 · EXPLORER (11 to 12)
-- ════════════════════════════════════════════════════════════════════════════

-- ── Explorer · News literacy, second rung: checking before sharing ──────────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'explorer', 'parent', 'information', 'Finding news you can trust',
  'At 11 to 12 the group chat becomes a news source: screenshots, clips and headlines arrive stripped of everything that would let you judge them. This lesson teaches the sideways check, open a new tab and see who else is reporting it, which is how professional fact checkers actually work.',
  'This is the age misinformation starts arriving through friends, which makes it feel pre trusted. The sideways check is the single most evidence backed media literacy move there is, and it takes under a minute.',
  'Next time a surprising claim reaches the family, check sideways together, out loud: open a new tab, search the claim, see who else says so. Let your child drive. One real rep beats ten explanations.',
  'Do not go deeper into the page. Go sideways: who else is reporting this?',
  'How do I teach my 11 year old to check whether news in the group chat is true?',
  981, 'live',
  $e1$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Explorer · Ages 11 to 12 · Information","title":"Finding news you can trust","body":"The sideways check: the one minute move fact checkers use, for the headlines that arrive in your chats.","script":"Retrieval: the three coats a story wears? News, opinion, advert. That was about what a story IS. Today is about what to DO when a surprising one lands in your group chat."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can check a surprising claim sideways before I believe it or pass it on.","why":"News now reaches me through friends, which makes it feel checked when nobody checked it. The sideways check takes a minute and works.","gains":["I know why staring harder at a post proves nothing","I can run a sideways check in a new tab","I know share is a publish button, not a chat button"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"↔️","heading":"Go sideways, not deeper","body":"Staring at a post cannot tell you if it is true: fakes are built to look real, that is their whole job. Professional fact checkers do something different. They leave the post, open a new tab, and search for the claim. If something big really happened, several real news organisations will be reporting it within hours. If only one strange site has it, that silence is your answer.","script":"This is lateral reading, the method with the strongest research behind it, taught here without the jargon. The key mental shift: the post itself contains almost no evidence about its own truth. Looking classy is cheap. Being reported by three unconnected newsrooms is not."},
    {"type":"scenario","phase":"practise","minutes":2,"label":"It just landed in the chat","platform":"message","handle":"Football News 24 7","avatar":"⚽","meta":"Forwarded many times","text":"CONFIRMED: your club's star striker has SIGNED for the rival tonight!! Medical done in secret. Papers tomorrow. Spread the word before they delete this!!","image":"📝","prompt":"Forwarded, urgent, and asking you to spread it. What does the sideways check look like here?","script":"Walk it: open a new tab, search the striker's name plus transfer. If it were real, every sports desk in the country would have it within the hour. Also name the tell hiding in plain sight: spread the word before they delete this is the rushing tell from Spot the trick, all grown up."},
    {"type":"choice","phase":"practise","minutes":2,"question":"You run the sideways check on the transfer message. A search shows no real news organisation reporting it, just two accounts reposting the same screenshot. Verdict?","options":[{"text":"It is probably true, secrets take time to reach the news","correct":false,"feedback":"Big transfers leak to real sports desks in minutes, not days. Silence from every newsroom IS the evidence."},{"text":"Almost certainly false, and it does not get shared onwards","correct":true,"feedback":"Right. One source, no corroboration, urgency and a plea to spread it. That pattern is the fake's fingerprint."},{"text":"Share it with is this true? added, so others can check","correct":false,"feedback":"Even with a question mark you just multiplied it. A claim you could not verify does not travel through you."},{"text":"True because the account has news in its name","correct":false,"feedback":"Anyone can put news in a username. The name is part of the costume, not part of the checking."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"Why does the sideways check beat examining the post really carefully?","options":[{"text":"Because fakes are built to survive careful looking, but they cannot fake every other newsroom","correct":true,"feedback":"Exactly. A fake controls its own appearance. It cannot control whether the rest of the world confirms it."},{"text":"Because reading the whole post takes too long","correct":false,"feedback":"Speed is a bonus, not the reason. The reason is that the post holds no evidence about its own truth."},{"text":"Because posts with spelling mistakes are always fake","correct":false,"feedback":"Some fakes are polished and some real posts are scruffy. Corroboration beats cosmetics."},{"text":"Because new tabs block fake news automatically","correct":false,"feedback":"No tab does the thinking for you. The check works because you compare sources, not because of the browser."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["The post cannot prove itself. Go sideways.","Who else is reporting this? Silence is an answer.","If you could not verify it, it does not travel through you."]}
  ]$e1$::jsonb
where not exists (select 1 from public.lessons where title = 'Finding news you can trust');

-- ── Explorer · Privacy and security: phishing at first smartphone age ───────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'explorer', 'parent', 'online_risks', 'The bait message',
  'Spot the trick taught the pop up patterns at 8. At 11 to 12 the tricks arrive dressed as people and platforms: a delivery text, a message from the game company, a friend whose account was taken over. This lesson teaches the hook check: real organisations do not ask for codes and passwords in messages, ever.',
  'This is typically first smartphone age, and a phone means messages from strangers land in your child''s pocket. One clear rule about codes and passwords, plus the never reply, go direct move, covers almost every phishing shape they will meet.',
  'Show your child a real spam text from your own phone, hunt the hook together, then delete it side by side. Nothing teaches this faster than the real thing found in the wild.',
  'Real companies never ask for codes or passwords in a message. Never reply, go direct, tell someone.',
  'My 11 year old just got their first phone. How do I prepare them for scam texts and fake messages?',
  982, 'live',
  $e2$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Explorer · Ages 11 to 12 · Privacy and security","title":"The bait message","body":"Phishing: messages that fish for your logins and codes, and the one rule that beats nearly all of them.","script":"Retrieval: the three tells of a trick? Rushing, promising, asking. Those tricks lived in pop ups. Today they have grown up and moved into your messages, wearing better costumes."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can spot a bait message and respond with never reply, go direct, tell someone.","why":"On a phone, tricks arrive as texts and DMs that look like real companies and real friends. One rule and one move beat nearly all of them.","gains":["I know what phishing means and what the bait wants","I know the code and password rule","I know never reply, go direct, tell someone"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🎣","heading":"Fishing for your keys","body":"Phishing is fishing for the keys to your accounts: passwords, login codes, card numbers. The bait looks official, a delivery you missed, a problem with your account, a prize from the game you play. The hook is always the same ask: tap this link, type your password, send that code. The costume changes every week. The hook never does.","script":"The liberating insight for this age: you do not need to recognise every scam, you only need to recognise the hook. New costumes appear weekly, which is why filters lag. The ask for keys is the constant. If a message wants a password or a code, the conversation is over."},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🚪","heading":"Never reply, go direct, tell someone","body":"The rule: real companies never ask for your password or a login code in a message. Not banks, not games, not delivery firms. So the move is three steps. Never reply, not even no. Go direct: if you think it might be real, open the actual app or website yourself and check there. Tell someone, because the same bait is probably in your friends' pockets too. And if a friend suddenly asks for a code? Their account may be stolen, so check with them off the app before you do anything.","script":"Go direct is the step that makes this bulletproof: it gives the worried brain a safe path. Not sure if the delivery text is real? Fine, open the courier's real app and look. The stolen friend account line matters at this age because that is exactly how account takeover chains spread through a year group."},
    {"type":"choice","phase":"practise","minutes":2,"question":"A text says: Your game account will be DELETED in 24 hours. Verify now with your password: [link]. What is the move?","options":[{"text":"Tap the link fast, you cannot lose your account","correct":false,"feedback":"The 24 hours is the rushing tell doing its job. The link is the hook. Real companies do not delete accounts by text ultimatum."},{"text":"Reply asking if it is really the game company","correct":false,"feedback":"Replying confirms your number is live and gets you more bait. Never reply, not even to ask."},{"text":"Do not reply, open the real game app yourself to check, and tell your grown up","correct":true,"feedback":"Perfect, all three steps. If anything were truly wrong, the real app would say so when you open it directly."},{"text":"Send the link to friends to warn them","correct":false,"feedback":"Warning them is right, spreading the live link is not. Tell them in your own words, no link attached."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"Your best friend messages: quick, send me the 6 digit code that just texted you, I need it for a surprise. What is really happening?","options":[{"text":"A surprise, best friends would never trick you","correct":false,"feedback":"Your friend would not, but this may not be your friend. A stolen account wears your friend's face and asks for codes."},{"text":"Probably a stolen account trying to steal yours next, so no code, and check with your friend off the app","correct":true,"feedback":"Exactly. That code IS the key to your account. Nobody real ever needs it, and your real friend will thank you for checking."},{"text":"Fine to send, codes expire quickly anyway","correct":false,"feedback":"It expires after it has been used, and using it is precisely the plan. The code rule has no exceptions."},{"text":"Ignore your friend for a week as punishment","correct":false,"feedback":"Your friend may be a victim here too. Check with them in person or by a call: did you send that?"}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["The costume changes weekly. The hook never does.","Nobody real asks for your password or code in a message.","Never reply, go direct, tell someone."]}
  ]$e2$::jsonb
where not exists (select 1 from public.lessons where title = 'The bait message');

-- ── Explorer · Privacy: data collection, BEFORE the first accounts at 13 ────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'explorer', 'parent', 'privacy', 'What the app knows about you',
  'Free apps are not free, they are paid in attention and information. This lesson shows an 11 to 12 year old what an app quietly collects, taps, time, searches, location, contacts, and the two minute permissions check that puts them back in charge.',
  'The deal you signed teaches the data contract at 13 to 15, after most children have already signed several. This lesson arrives two years earlier, so the first real account a child ever makes is made with open eyes.',
  'Pick one app together and open its permissions in the phone settings: what can it see, and does it need that to do its job? A torch app wanting your contacts is a conversation that teaches itself.',
  'If the app is free, information is how you pay. Check what it takes.',
  'What should my 12 year old understand about app data collection before social media?',
  983, 'live',
  $e3$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Explorer · Ages 11 to 12 · Privacy and security","title":"What the app knows about you","body":"What free really costs, what apps quietly collect, and the two minute check that puts you back in charge.","script":"Retrieval: what goes on the private list, the things we never type into a screen? Name, school, address, passwords. Today: the information apps collect WITHOUT asking you to type anything at all."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can explain how a free app makes money and run a permissions check on my own apps.","why":"Apps collect quietly, in the background, from the moment they are installed. Knowing what they take is the difference between using an app and being used by one.","gains":["I can explain what free apps collect and why","I can run the does it need this permissions test","I know this gets bigger at 13, and I will be ready"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"👀","heading":"The quiet collectors","body":"A free app can notice: every tap, how long you watch each thing, what you search, when you are online, and, if you allow it, where you are and who is in your contacts. Why? Because knowing you means predicting you, and predicting you is worth money to advertisers. The app is free because you are the interesting part.","script":"Keep the tone matter of fact, not creepy: this is a business model, not a villain, and treating it as a mechanism keeps your child curious instead of frightened. The line worth planting: nothing here is secret, it is all in the settings, most people just never look. Your family looks."},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🎛️","heading":"The permissions check","body":"Every app asks the phone for permissions: camera, microphone, location, contacts, photos. The test is one question: does the app need this to do its actual job? A maps app needs location. A drawing app asking for your contacts fails the test. You can say no in settings, and the app almost always works fine without it.","script":"Do a live one together on their phone or yours, two minutes, their finger on the screen. The does it need this test is transferable judgement, not a rule to memorise, which is exactly what Explorer age can start doing. Every permission they turn off themselves is worth ten you turned off for them."},
    {"type":"choice","phase":"practise","minutes":2,"question":"A free wallpaper app asks for your location and your contacts when it installs. Run the test.","options":[{"text":"Allow both, apps know what they need","correct":false,"feedback":"Apps ask for what is VALUABLE, not what is needed. Wallpapers need neither where you are nor who you know."},{"text":"Fails the test twice: wallpapers need neither, so say no to both","correct":true,"feedback":"Exactly. The app will still work, and it just learned a lot less about you. That is the check doing its job."},{"text":"Allow location but not contacts, as a compromise","correct":false,"feedback":"Kind instinct, wrong tool. This is not a negotiation: it fails the does it need this test, so it gets a no."},{"text":"Delete your contacts so there is nothing to take","correct":false,"feedback":"You never have to shrink your life to stay private. Just say no to the permission and keep your contacts."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"Why is a free video app worth millions of pounds?","options":[{"text":"Adverts alone, the same as posters at a bus stop","correct":false,"feedback":"Warmer than you think, but bus stop posters cannot learn. The value is adverts AIMED using what the app knows about each viewer."},{"text":"Because what it learns about millions of viewers makes its adverts precisely aimed, and aimed adverts sell","correct":true,"feedback":"That is the whole machine. Watching you watch is the product. Free is how they get you in the door."},{"text":"Donations from generous people","correct":false,"feedback":"No app at that scale runs on kindness. Follow the information and you find the money."},{"text":"It is not really worth anything, free means free","correct":false,"feedback":"If you are not paying money, you are paying something else. Here it is attention and information, and both are worth a fortune at scale."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Free apps are paid in attention and information.","One test: does it need this to do its job?","Most people never look at the settings. You do."]}
  ]$e3$::jsonb
where not exists (select 1 from public.lessons where title = 'What the app knows about you');

-- ════════════════════════════════════════════════════════════════════════════
-- STAGE 4 · SHAPER (13 to 15)
-- ════════════════════════════════════════════════════════════════════════════

-- ── Shaper · Hate speech: the pile on's uglier cousin, named directly ───────
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'shaper', 'parent', 'bullying', 'When banter becomes hate',
  'The bullying lessons cover cruelty aimed at one person. This one covers cruelty aimed at what someone IS: their race, faith, sex, disability or sexuality, often arriving dressed as banter, edgy memes and just jokes. It teaches the line, the ratchet that moves it, and the three responses that do not feed it.',
  'The 2025 RSHE guidance names online hate and misogynistic cultures as compulsory ground for this age, because this is when feeds start serving it. A teenager who can name the ratchet while it is happening is far harder to move along it.',
  'Ask what edgy humour is going around at the moment, and listen without sentencing anyone. The conversation you want exists only if naming what they have seen never costs them their phone.',
  'Aimed at what someone is, it is not banter. Do not feed it, do not spread it, back the target.',
  'My 14 year old says the group chat humour is getting nastier. How do we talk about hate speech?',
  984, 'live',
  $s1$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Shaper · Ages 13 to 15 · Respect online","title":"When banter becomes hate","body":"Where the line actually is, how feeds and group chats move it without you noticing, and the three responses that work.","script":"Retrieval: in the pile on lesson, what turns a disagreement into a pile on? Numbers and speed. Today is the harder version: when the target is not what someone DID but what someone IS."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can tell banter from hate, spot the ratchet moving, and respond without feeding it.","why":"This content is in feeds and chats at my age whether anyone invites it or not. Knowing the line and the ratchet keeps me the one deciding what I laugh at, spread and stand behind.","gains":["I can name the line between banter and hate","I can see the ratchet while it is turning","I know refuse, do not spread, back the target"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"📏","heading":"The line","body":"Banter punches at what someone did: your terrible pass, your worse haircut, and both of you are laughing. Hate punches at what someone is: race, faith, sex, disability, sexuality. That is the line, and just joking does not move it. A joke where the whole point is that a kind of person is lesser is the message wearing a costume.","script":"Hold the definition steady and unemotional, because at this age the argument is always about edge cases. The test that survives them: could the target opt out? A haircut grows back and a bad pass is forgotten. What someone IS goes home with them, which is exactly why the joke picks it."},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"⚙️","heading":"The ratchet","body":"Nobody starts at hate. Feeds and chats get there by a ratchet: an edgy joke gets laughs, the next needs to be edgier for the same laugh, and slowly the unsayable becomes the normal. Rage and shock hold attention, and attention is what feeds are built to keep. The ratchet is not an accident. Seeing it turn is how you step off.","script":"This connects straight to the rabbit hole lesson: same attention machinery, aimed at contempt instead of content. The ratchet framing does something valuable for a teenager: it lets them notice their own chat drifted without having to decide their friends are evil, which is the admission that usually blocks this whole conversation."},
    {"type":"choice","phase":"practise","minutes":2,"question":"A meme lands in the group chat. The joke only works if you agree that girls are stupid. Half the chat is laughing. What is it, and what do you do?","options":[{"text":"Banter, because it is a meme and memes are jokes","correct":false,"feedback":"The format is a costume. The message is a whole group of people are lesser, and that is the wrong side of the line whoever laughs."},{"text":"Hate dressed as a joke: do not laugh it along, do not forward it, and say something if you can","correct":true,"feedback":"That is the read. You do not have to give a speech. Not spreading it and one flat not funny already slows the ratchet."},{"text":"Fine within the chat, wrong only if girls see it","correct":false,"feedback":"A room where contempt is safe as long as the targets cannot hear is a room the ratchet owns. The line does not move with the audience."},{"text":"Report every person in the chat immediately","correct":false,"feedback":"Report the content when it is reportable, but mass reporting friends skips the useful step: refusing the laugh is what actually shifts a chat."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"Why does the ratchet keep turning if nobody in the chat actually hates anyone?","options":[{"text":"Because each edgier joke needs to beat the last one for the same laugh, and attention rewards shock","correct":true,"feedback":"Exactly. No villain required, just a mechanism running. Which means anyone who sees it can be the one who stops feeding it."},{"text":"Because teenagers are naturally hateful","correct":false,"feedback":"No. The mechanism uses ordinary humans wanting laughs and attention. Naming the mechanism beats blaming the people."},{"text":"It does not, chats stay however they start","correct":false,"feedback":"Drift is the whole danger. Compare any long chat's first week with its worst week and you can watch the ratchet's teeth."},{"text":"Because phones make people angry","correct":false,"feedback":"Too vague to act on. The specific gear is escalation for attention, and specific gears can be jammed."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Aimed at what someone is, it is not banter.","The ratchet turns one edgier joke at a time. See it turning.","Refuse the laugh, do not spread it, back the target."]}
  ]$s1$::jsonb
where not exists (select 1 from public.lessons where title = 'When banter becomes hate');

-- ── Shaper · Information: confirmation bias, the reader's side of the feed ──
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'shaper', 'parent', 'information', 'Why the feed agrees with you',
  'The rabbit hole lessons cover what the algorithm does. This one covers the reader''s half: confirmation bias, the wiring that makes agreeing content feel true and disagreeing content feel like an attack, and the two moves that loosen its grip, notice the feeling, and argue your own side.',
  'A teenager who knows the feed is engineered but thinks their own judgement is neutral is only half protected. Bias literacy is the difference between knowing about echo chambers and being able to feel yourself inside one.',
  'At dinner, each pick one thing you believe and take turns making the best honest case AGAINST it. Play it as a game. A family that can argue its own side has the skill the feed never teaches.',
  'Feels obviously true is a feeling, not a fact check. Argue your own side.',
  'How do I teach my 15 year old to notice their own bias, not just the algorithm''s?',
  985, 'live',
  $s2$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Shaper · Ages 13 to 15 · Information","title":"Why the feed agrees with you","body":"The algorithm is half the story. The other half is wiring inside your own head, and it has a name.","script":"Retrieval: why does a feed serve you more extreme versions of what held your attention? Stronger reactions hold attention longer. Today, the uncomfortable half: why your own brain is such an easy customer for it."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can catch confirmation bias working in me and test a belief by arguing its other side.","why":"Everyone believes bias is something other people have. Catching it in yourself is a genuine edge: better arguments, better calls, and a feed that runs you less.","gains":["I can explain confirmation bias in one sentence","I know the two feelings that signal it firing","I can run the argue your own side test"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🧲","heading":"The magnet in your head","body":"Confirmation bias: your brain welcomes whatever supports what you already think, and finds reasons to dismiss whatever does not. Everyone has it. It fires fastest on the things you care most about. And it feels like nothing at all, which is the problem: agreeing content just feels TRUE, disagreeing content just feels WRONG, and no checking ever seems needed.","script":"The one that lands with teenagers: this is not a flaw in stupid people, it fires hardest in clever people, because clever people are better at building reasons for what they already believe. Own one of yours first: name a time you dismissed something because you wanted it to be wrong. That admission buys the whole lesson."},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🤝","heading":"Your bias and the feed, a perfect team","body":"Now put the two halves together. The feed learns what you agree with, because agreeing keeps you watching. Your bias welcomes everything the feed serves, because it all supports your side. Each makes the other stronger, and the result feels like everyone sensible agrees with me. Two warning feelings tell you the team is at work: obviously true, and I do not even need to read that.","script":"The two named feelings are the practical tool here: obviously true and not worth reading are exactly when a fact check feels most unnecessary and is most needed. That inversion, check hardest when you feel surest, is the entire skill, and it is learnable."},
    {"type":"choice","phase":"practise","minutes":2,"question":"A post confirms exactly what you think about a team you already cannot stand. It feels obviously true and you want to share it. What is the bias aware move?","options":[{"text":"Share it, things that feel obviously true usually are","correct":false,"feedback":"Obviously true is the bias feeling itself. The surer you feel without checking, the harder the magnet is pulling."},{"text":"Notice the feeling, and check it exactly as hard as you would a post you hated","correct":true,"feedback":"That is the discipline: one standard of checking for posts you love and posts you hate. Sideways check still applies."},{"text":"Trust it because it matches what several friends already sent you","correct":false,"feedback":"Friends who share your view sharing your view is the echo, not evidence. Corroboration means unconnected sources."},{"text":"Never share anything about topics you care about","correct":false,"feedback":"Caring is not the fault and silence is not the fix. Checking your own side at full strength is."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"What does it mean if you cannot make ANY honest argument for the other side of something you believe?","options":[{"text":"Your belief is so right that no other side exists","correct":false,"feedback":"On almost any real question, thoughtful people disagree somewhere. Seeing zero other side usually measures your exposure, not the truth."},{"text":"You have probably only ever heard your own side, so it is time to go find the best version of the other one","correct":true,"feedback":"Exactly. Not the stupid version of the other side, the best one. If your belief survives that, it has earned its place."},{"text":"You should immediately switch to the other side","correct":false,"feedback":"The test is not a verdict. It measures how much of the map you have seen, then sends you to look at the rest."},{"text":"Arguing the other side is disloyal to your side","correct":false,"feedback":"Loyalty to conclusions is how bias wins. Understanding the other side is how your own side gets stronger."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Obviously true is a feeling, not a fact check.","Your bias and the feed are a team. You can bench one of them.","Check hardest when you feel surest. That is the whole skill."]}
  ]$s2$::jsonb
where not exists (select 1 from public.lessons where title = 'Why the feed agrees with you');

-- ════════════════════════════════════════════════════════════════════════════
-- STAGE 5 · INDEPENDENT (16 and up)
-- ════════════════════════════════════════════════════════════════════════════

-- ── Independent · Privacy as a citizen: the debate, not only the settings ───
insert into public.lessons (stage_id, audience, category, title, the_idea, why_it_matters, try_this, key_message, digi_prompt, sort_order, status, slides)
select 'independent', 'parent', 'privacy', 'The privacy line',
  'The practical privacy lessons secure the accounts. This one steps up a level: privacy as a citizen. Where should the line sit between safety and surveillance, who gets to read messages and track locations, and how does a 16 year old hold a real position in that debate rather than a shrug?',
  'At 16 they can shape the rules they will live under: they vote soon, they sign terms daily, and the trade offs, encryption, age checks, tracking, are live political questions in the UK right now. Nothing but a shrug is the only wrong answer.',
  'Take one live question, should private messages ever be scannable to catch criminals, and swap sides over dinner: each of you argues the position you hold less. The aim is not agreement, it is a position each of you can defend.',
  'Privacy versus safety is a line someone will draw. Be able to say where and why.',
  'How do I talk to my 16 year old about surveillance, encryption and privacy as a citizen?',
  986, 'live',
  $i1$[
    {"type":"title","phase":"starter","minutes":1,"eyebrow":"Independent · Ages 16 and up · Privacy and security","title":"The privacy line","body":"You have locked your accounts. Now the adult question: where should the line between safety and surveillance sit, and who draws it?","script":"Retrieval: what does two step verification protect you from? Someone with your password still cannot get in. Today the question grows up: not how to protect your own accounts, but who should be able to look inside anyone's."},
    {"type":"objective","phase":"starter","minutes":1,"outcome":"I can explain the real trade off between safety and surveillance and defend where I would draw the line.","why":"These rules are being written now, in my country, for my adult life. People who cannot argue a position get handed one.","gains":["I can steelman both sides of the encryption debate","I know why this is a trade off and not a trick question","I can say where I would draw the line, and why"]},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"⚖️","heading":"Two true things at once","body":"Hold both honestly. True: encrypted messages protect everyone, including people talking to doctors, journalists' sources, and anyone living under a government that jails critics. Also true: the same encryption shelters people planning genuine harm, and investigators sometimes stand outside a locked door they have every legal right to open. Anyone who tells you only one of these is real is selling a side.","script":"The teaching move at this age is refusing to pre chew the answer. Both truths get full weight, spoken plainly. What you are modelling is that an adult can hold a tension without collapsing it, which is precisely what the loudest voices on both sides of this debate cannot do."},
    {"type":"concept","phase":"teach","minutes":2,"emoji":"🚪","heading":"The backdoor problem","body":"The recurring proposal: build a special way in, only for the good guys, only with a warrant. The recurring engineering answer: a door that exists cannot be told who it is for. Criminals, hostile states and leakers look for it too, and weakening everyone's lock to catch some lawbreakers is a real cost, not a free win. That does not end the debate, targeted powers exist and hard cases are hard. It just means every position must pay its bill honestly.","script":"Keep this concrete with the physical analogy: a master key for every front door in the country, held safely, would genuinely help catch criminals, and its existence would genuinely be a new danger. Neither half cancels the other. A 16 year old who can hold that is already arguing better than most adults online."},
    {"type":"choice","phase":"practise","minutes":2,"question":"A proposal says messaging apps must scan all messages for illegal content before sending. A friend says: I have nothing to hide, so why should I care? What is the strongest honest reply?","options":[{"text":"Agree, people with nothing to hide lose nothing","correct":false,"feedback":"Privacy is not only for secrets: it protects medical chats, legal advice, sources, and anyone a future government dislikes. Nothing to hide assumes power stays friendly."},{"text":"Scanning everyone changes what privacy IS for every citizen, so the case for it has to be strong enough to justify that, and we should each know if we think it is","correct":true,"feedback":"That is the adult shape of the answer: name the real cost, name the real aim, then take an actual position on the trade."},{"text":"Refuse to discuss it, governments will do what they want anyway","correct":false,"feedback":"The shrug is the one guaranteed losing move. These rules are contested and changed by people who show up with arguments."},{"text":"Anyone supporting scanning must want to spy on people","correct":false,"feedback":"Most supporters want to catch predators, and calling that spying ends the conversation you needed to have. Steelman first, then argue."}]},
    {"type":"choice","phase":"prove","minutes":2,"question":"Why does where should the line sit beat privacy always wins or safety always wins?","options":[{"text":"It does not, one side is simply correct","correct":false,"feedback":"Both absolutes fail somewhere: total surveillance and total darkness each have costs no honest person wants. The argument is about the line."},{"text":"Because both values are real, so every position is a trade off, and a line is a position you can actually defend and revise","correct":true,"feedback":"Exactly. Grown up politics is trade offs owned honestly. A defensible line beats a slogan on either side."},{"text":"Because saying it depends means never being wrong","correct":false,"feedback":"It depends with no line attached is the shrug in disguise. The task is to SAY where and why, and stand somewhere."},{"text":"Because the middle of any argument is always right","correct":false,"feedback":"Splitting the difference is not thinking either. Some lines belong near one end. The point is defending yours, not averaging."}]},
    {"type":"digi","phase":"close","minutes":1,"heading":"DiGi says","lines":["Two true things at once. Hold both, then choose.","Every position pays a bill. Pay yours honestly.","Be able to say where your line is, and why. That is citizenship."]}
  ]$i1$::jsonb
where not exists (select 1 from public.lessons where title = 'The privacy line');
