-- 245: question balance, Foundation and Builder.
--
-- The 1 September review found two tells a child learns in two lessons:
-- the right answer was the longest option in 80 to 98 percent of questions
-- per stage, and the player never shuffled, so it sat in the middle almost
-- every time. The player now shuffles per run (LessonPlayer). This
-- migration fixes the length tell, and raises the questions while it is
-- there: the weakest distractor on each flagged question becomes a
-- plausible misconception a child that age actually holds, with feedback
-- that answers that misconception, the way a good teacher marks it.
--
-- Three treatments rotate so the right answer's length rank is spread
-- rather than flipped: the new distractor runs longer than the right
-- answer, or both distractors do, or the new one sits level with it.
-- A handful of over long right answers are trimmed without losing the
-- teaching. Feedback for an extended distractor is unchanged because the
-- misconception is unchanged.
--
-- Idempotent: each fix matches on (question, old option text) and a
-- second run finds nothing to change.

create or replace function public.gc_swap_option_text(deck jsonb, fixes jsonb)
returns jsonb language plpgsql as $fn$
declare
  built jsonb := '[]'::jsonb;
  sl jsonb; o jsonb; f jsonb; newopts jsonb;
begin
  if deck is null then return null; end if;
  for sl in select value from jsonb_array_elements(deck) loop
    if sl->>'type' = 'choice' and jsonb_typeof(sl->'options') = 'array' then
      newopts := '[]'::jsonb;
      for o in select value from jsonb_array_elements(sl->'options') loop
        for f in select value from jsonb_array_elements(fixes) loop
          if f->>'q' = sl->>'question' and f->>'old' = o->>'text' then
            o := jsonb_set(o, '{text}', to_jsonb(f->>'new'));
            if f ? 'fb' then o := jsonb_set(o, '{feedback}', to_jsonb(f->>'fb')); end if;
          end if;
        end loop;
        newopts := newopts || jsonb_build_array(o);
      end loop;
      sl := jsonb_set(sl, '{options}', newopts);
    end if;
    built := built || jsonb_build_array(sl);
  end loop;
  return built;
end $fn$;

-- Foundation (ages 4 to 7): a grown up reads to the child, so the
-- misconceptions are the ones small children really say out loud.
update public.lessons set slides = public.gc_swap_option_text(slides, $j$[
{"q":"Why do we use the face test?","old":"Because unkind words break the screen","new":"Because a grown up is checking and we could get into trouble","fb":"It is not about being caught. A real person with real feelings gets our words, so we choose kind ones."},
{"q":"You cannot see your friend's face in the game. Are their feelings still real?","old":"No, no face means no feelings","new":"No, feelings only count when you can see the other person's face","fb":"Feelings do not switch off when the face is hidden. Real person, real feelings, even through a screen."},
{"q":"You cannot see your friend's face in the game. Are their feelings still real?","old":"Only if they say so","new":"Only if they type that their feelings are hurt"},
{"q":"A photo of you looks grumpy. Does that mean you are a grumpy person?","old":"Yes, and I will be grumpy forever","new":"Yes, because a camera never fibs about a person","fb":"A camera catches one second. You are all the other seconds too, and most of them are not grumpy."},
{"q":"A video shows a fluffy puppy. Can the puppy lick your hand?","old":"Yes, all puppies can","new":"Yes, because the puppy is inside the tablet looking out at me","fb":"There is no puppy inside the tablet, only a picture of one. Pictures cannot lick."},
{"q":"You see a photo of a giant ice cream on a screen. Can you eat it?","old":"Yes, if I ask very nicely","new":"Yes, because it looks so real that it must be really there","fb":"Looking real is what pictures do best. It is still a picture, and pictures are not for eating."},
{"q":"You see a photo of a giant ice cream on a screen. Can you eat it?","old":"Yes, if I lick the screen","new":"Yes, if I lick the screen while the picture is still there"},
{"q":"Your friend looks super happy in every single photo. What do you know?","old":"They are happy every minute of every day","new":"They are happy every single minute, because photos never fib","fb":"Photos only show the happy seconds. Your friend has grumpy and wobbly minutes too, just like you."},
{"q":"A friendly cartoon in an app asks for your password and promises extra stars. What do you do?","old":"Type just half of it","new":"Tell it my password out loud, because saying it is not the same as typing it","fb":"Saying or typing, a password is still leaving your shield. Type nothing, say nothing, fetch your grown up."},
{"q":"A game says: tell us your name and school to win a prize! What do you do?","old":"Type just the school, not your name","new":"Type just the school, because a school is not a secret like a name","fb":"Your school is a big clue about where you are every day. It stays behind the shield with your name."},
{"q":"A game says: tell us your name and school to win a prize! What do you do?","old":"Type it quickly to win the prize","new":"Type it quickly to win the prize before the game changes its mind"},
{"q":"Which of these stays behind your shield?","old":"Your favourite dinosaur","new":"Your favourite dinosaur and song","fb":"Favourites are fun to share. The shield is for where you live and your passwords."},
{"q":"A video says a toy will make you the happiest child in the world. Which box?","old":"The true box, because the video said so","new":"The true box, because the video showed real children playing with it","fb":"Real children in a video are part of the sell. The video wants you to want the toy, so it goes in the advert box."},
{"q":"What is an advert's job?","old":"To scare me","new":"To give me free things and prizes","fb":"Adverts never give, they ask. Their job is to make you want something."},
{"q":"What is an advert's job?","old":"To tell me true things","new":"To tell me true things about what to buy"},
{"q":"It is nearly bedtime and the tablet is still playing. What is the strong move?","old":"Bring it to bed, just this once","new":"Bring it to bed with the sound off, just this once","fb":"Quiet or loud, the light still tells your brain it is daytime. Screen bed for the tablet, your bed for you."},
{"q":"Where does the tablet go at night in our house?","old":"Anywhere it lands","new":"Next to my bed, so it is ready the moment I wake up","fb":"Next to the bed is where the bright light keeps brains awake. The screen bed is outside the bedrooms."},
{"q":"Why do screens sleep outside the bedroom?","old":"Because bedrooms are too small for screens","new":"Because grown ups want the tablet for themselves in the evening","fb":"It is not about who gets the tablet. Screen light tells brains to stay awake, so screens sleep somewhere else."},
{"q":"Why do screens sleep outside the bedroom?","old":"Because screens are naughty","new":"Because screens are naughty and need a time out"},
{"q":"Why does a bright screen at bedtime make sleeping harder?","old":"It does not, screens help sleep","new":"It does not, a calm video helps me sleep","fb":"Even a calm video shines bright light into your eyes, and that light tells your brain it is daytime."},
{"q":"The speaker at home answers your question in a kind voice. What do you know?","old":"It is my friend and it loves me","new":"It is a tiny person living inside the speaker who likes me","fb":"Nobody lives inside the speaker. It is a clever tool with a kind voice, and tools cannot love."},
{"q":"The speaker at home answers your question in a kind voice. What do you know?","old":"It is a clever tool, and I can ask my grown up if I am not sure","new":"It is a clever tool. If I am not sure, I ask my grown up"},
{"q":"The talking toy asks where you live. What is the strong move?","old":"Whisper it very quietly","new":"Tell it, because a toy cannot walk to my house anyway","fb":"The toy cannot walk, but what you tell it can travel to people you have never met. Tell it nothing."},
{"q":"The talking toy asks where you live. What is the strong move?","old":"Tell it, toys keep secrets","new":"Tell it, because toys always keep secrets"},
{"q":"You ask the speaker for a joke and it tells a funny one. Does it think you are funny too?","old":"Only if I say please","new":"Yes, because it laughed at my joke as well","fb":"A laugh sound is just a sound it plays. It does not think or feel, so it cannot find you funny."},
{"q":"You find a lovely picture on a screen and want it for your poster. What is the strong move?","old":"Say you made it yourself","new":"Copy it and say I drew it, because nobody will ever know","fb":"Someone did know: the person who made it. Ask your grown up to help check whose it is."},
{"q":"You want to use a song in your video for school. What is the strong move?","old":"Say I made it myself","new":"Use it, because a song is only sounds and sounds belong to nobody","fb":"Somebody wrote those sounds and sang them. Ask a grown up to help check whose song it is."},
{"q":"You want to use a song in your video for school. What is the strong move?","old":"Just use it, songs are free","new":"Just use it, because songs on a screen are free"},
{"q":"Grandma wants to put your birthday photo online. What happens first in our family?","old":"Nothing, grandmas are allowed","new":"Nothing, grandmas do not need to ask","fb":"Even grandmas ask first in our family. My photo, my say, and then she posts it with a smile."},
{"q":"What can happen to a photo once it goes on the internet?","old":"It disappears at bedtime","new":"It vanishes as soon as the person who sent it deletes it","fb":"Deleting your copy does not delete everyone else's. A photo can stay a long time and be copied."},
{"q":"You posted a silly photo and want it back an hour later. What do you know?","old":"The internet forgets after bedtime","new":"The internet forgets it by tomorrow, so an hour is nothing to worry about","fb":"The internet does not forget. Copies can already be saved. That is why we ask before we post."},
{"q":"You posted a silly photo and want it back an hour later. What do you know?","old":"One tap deletes it from everywhere","new":"One tap deletes it from everywhere, even from other people's phones"},
{"q":"You took a funny photo of your sister and want to send it to everyone. What is the strong move?","old":"Send it to just a few people","new":"Send it to just my cousins first","fb":"Cousins count as everyone once they forward it. Ask your sister and your grown up first."},
{"q":"A friend says telling a grown up about screen stuff is telling tales. What is true in our family?","old":"Only tell if it happens twice","new":"Only tell if it happens again, because once is not worth bothering anyone","fb":"Once is enough. Telling keeps us safe, and your grown up always wants to know."},
{"q":"A scary picture pops up in your game. What is the strong move?","old":"Hide the screen so no one finds out","new":"Close the game quietly and keep it to myself so nobody gets cross","fb":"Nobody gets cross with you for a picture that popped up. Put the screen down and tell your grown up."},
{"q":"A scary picture pops up in your game. What is the strong move?","old":"Keep playing and try not to look at it","new":"Keep playing and try not to look at it until it goes away"},
{"q":"Something scary popped up all by itself. Whose fault is that?","old":"Nobody may talk about it","new":"Nobody's, so there is no need to tell","fb":"It is nobody's fault, and we still tell. Telling is how your grown up helps."},
{"q":"What happens when you tell your grown up about something bad on a screen?","old":"The screen gets thrown away","new":"They take the screen away for good, so it is better to keep quiet","fb":"Telling never costs you the screen. They help you, and you are never in trouble for telling."},
{"q":"A video pops up and it makes your tummy feel funny. What do you do first?","old":"Keep watching to see what happens","new":"Keep watching, because it might turn nice at the end","fb":"A funny tummy is your body's signal. Stop looking and put the screen down first, then tell."},
{"q":"You tapped something by accident and now the screen shows something strange. If you tell your grown up, what happens?","old":"I get in trouble for tapping","new":"I get in trouble, because it was my tap","fb":"Accidents are not trouble. Your grown up is glad you told them, and they help."},
{"q":"You tapped the strange thing by accident yourself. Do you still tell?","old":"Only if someone saw me","new":"Only if someone saw me, otherwise it is better to keep quiet","fb":"Telling is safe whether anyone saw or not. Your grown up would much rather know."},
{"q":"The screen is done and your body still feels cross. What helps most?","old":"Grabbing the tablet back","new":"Grabbing the tablet back for one more go, so the cross feeling stops","fb":"One more go makes the ending come round again, and the cross feeling with it. Wave bye bye and run to the next thing."},
{"q":"The screen is done and your body still feels cross. What helps most?","old":"Shouting until the feeling goes","new":"Shouting until the feeling goes away by itself"},
{"q":"Why do endings feel easier after the whisper?","old":"They do not, endings always feel horrible","new":"They do not, endings feel horrible anyway","fb":"Endings feel much easier when your body knows one is coming. Nothing is a surprise after the whisper."},
{"q":"Why does the five minute whisper help your body?","old":"It means I get extra screen time","new":"It means I get five extra minutes, which is the best bit","fb":"The whisper is not extra time, it is a heads up. It gives your body time to get ready for the ending."},
{"q":"A player gives you a present in the game and asks to be your friend. What do you do?","old":"Give them my name to say thank you","new":"Send a present back with my name on, to say thank you","fb":"A present does not need your name. Come and show your grown up before you answer at all."},
{"q":"A player gives you a present in the game and asks to be your friend. What do you do?","old":"Say yes, presents mean they are kind","new":"Say yes, because presents mean they must be kind"},
{"q":"Can a stranger in a game feel like a friend?","old":"No, strangers always feel scary","new":"No, a stranger always feels scary","fb":"Strangers can feel friendly, and that is the tricky bit. Friendly feeling or not, they are still a stranger."},
{"q":"Someone in your game says: hi! What is your name? What do you do?","old":"Tell them, because they sound friendly","new":"Tell them just my first name, because a first name is not a secret","fb":"Even a first name is a piece of you. Do not answer, and go and show your grown up."},
{"q":"You showed your grown up a message from a stranger. What happens next?","old":"You lose the game as a punishment","new":"You lose the game, because talking to strangers gets you punished","fb":"Showing is never punished. They are glad you showed them, and they help."},
{"q":"The tablet is away and your body feels like a shaken fizzy bottle. What do you do with that feeling?","old":"Hide it, because cross feelings are naughty","new":"Hide it, because fizzy feelings are naughty","fb":"Fizzy feelings are not naughty, they are just big. Bring the feeling to your grown up and say: I feel fizzy."},
{"q":"Which feelings are allowed after screen time?","old":"Only the calm, happy ones","new":"Only the calm, happy ones, because fizzy feelings mean I was naughty","fb":"Fizzy feelings do not mean naughty. All feelings are allowed. Fizzy, wobbly and calm."},
{"q":"A video ends and a new one starts playing all by itself. What light is the new one?","old":"Red, all new videos are bad","new":"Red, because anything that starts by itself must be a bad one","fb":"Not red, amber. It might be fine, but you did not choose it, so you ask."},
{"q":"A video ends and a new one starts playing all by itself. What light is the new one?","old":"Green, the screen chose it for me","new":"Green, because the screen chose it for me"},
{"q":"What turns an amber game green?","old":"Waiting until tomorrow","new":"Waiting a few days until it turns green","fb":"Amber does not turn green by itself. Looking at it together with your grown up is what turns it."},
{"q":"Your friend shows you a brilliant new game and you really want to play it at home. What light is it?","old":"Green, because my friend already plays it","new":"Green, because my friend plays it and their grown up said yes","fb":"Their grown up said yes for their house. In your house it is new, so it is amber until you ask."},
{"q":"Is the you in the game the same you as at home?","old":"No, screen me can be anyone","new":"No, because in a game I am a character, so the rules are different","fb":"The character is pretend, the kindness is real. Same kind person, everywhere you go."},
{"q":"Is the you in the game the same you as at home?","old":"Only when my grown up is watching","new":"Only when my grown up is watching me play"},
{"q":"Why do kind words matter extra much on a screen?","old":"Because your neighbour cannot see your face, so words are all they get","new":"Because they cannot see your face, so words are all they get"},
{"q":"Why do kind words matter extra much on a screen?","old":"Because screens make words louder","new":"Because screens make every word louder and bigger than real life","fb":"Screens do not make words louder. They take your face away, so your words are all your neighbour gets."},
{"q":"Your cousin keeps losing in your game and feels sad. What does a good neighbour do?","old":"Laugh, because losing is funny","new":"Say never mind and keep winning, because it is only a game","fb":"Only a game is still a real sad face next to you. Help them, take turns, and say kind words."}
]$j$::jsonb)
where stage_id = 'foundation' and status = 'live' and slides is not null;

-- Builder (ages 8 to 10): the strong move register, misconceptions a
-- nine year old argues for with a straight face.
update public.lessons set slides = public.gc_swap_option_text(slides, $j$[
{"q":"A game pops up a spinning wheel: spin now, only 10 gems, win a mega prize! What is the strong move?","old":"Spin fast before the offer disappears","new":"Spin once, because ten gems is cheap and the prize might be real","fb":"Cheap is the hook. The wheel wants your gems, and a mega prize that costs gems is the sell. Spot it and walk on."},
{"q":"Does spotting the sell ruin the fun of videos and games?","old":"Yes, so we should stop watching videos","new":"Yes, because once you know it is selling, you cannot enjoy it any more","fb":"Knowing changes nothing about the fun. It just means you choose with open eyes."},
{"q":"Does spotting the sell ruin the fun of videos and games?","old":"Yes, now everything is secretly an advert","new":"Yes, now everything is secretly an advert and nothing can be trusted"},
{"q":"Why do sellers dress adverts up as videos and games?","old":"Because games cannot work without adverts","new":"Because a plain advert costs more than a video","fb":"Cost is not the reason. A dressed up advert is one you might not notice, and not noticing is the whole plan."},
{"q":"Your favourite YouTuber says a new drink is amazing and shows a code for money off. What is happening?","old":"They just really love the drink","new":"They just really love the drink, and the code is a present for their fans","fb":"A code is how the company counts the sales. It is the sell in a costume. Spot it, then choose."},
{"q":"What turns copying into something fair?","old":"Doing it quickly so nobody sees","new":"Changing a few small bits, so it counts as your own work","fb":"A few changes do not make it yours. Naming the maker is what makes copying fair."},
{"q":"What turns copying into something fair?","old":"Only copying from people you do not know","new":"Only copying from people you do not know, so nobody gets upset"},
{"q":"Why does naming the maker matter to YOU as a maker?","old":"Because you get in trouble otherwise","new":"Because a teacher checks, and you get in trouble otherwise","fb":"It is not about being checked. You want your name on your work, so fair has to go both ways."},
{"q":"You learnt a whole amazing build from one video and your friends are stunned. What is the fair move?","old":"Enjoy the glory quietly","new":"Enjoy the glory quietly, because learning it took real effort too","fb":"Your effort was real, and so was the maker's idea. Say where you learnt it: name the maker."},
{"q":"An online player you like says: do not tell your parents about our chats, they would not get it. What is that?","old":"Normal, lots of chats are private","new":"Normal, because lots of friends keep their chats private from parents","fb":"Private is one thing. Someone asking you to keep them secret from your family is the biggest warning sign there is."},
{"q":"An online player you like says: do not tell your parents about our chats, they would not get it. What is that?","old":"Proof they really understand you","new":"Proof they really understand you better than your parents do"},
{"q":"Most people online are exactly who they say they are. So why run the real life check on everyone?","old":"You do not need to if someone seems nice","new":"You do not need to once someone has been nice for weeks","fb":"Weeks of nice is exactly how the few who are not honest work. You cannot tell just by looking, so everyone gets the check."},
{"q":"Someone you have played with for two weeks says: you are my best friend, what school do you go to? What is the strong move?","old":"Say a made up school name to keep them happy","new":"Say a made up school name, because a little fib keeps everyone happy","fb":"A fib keeps the chat going, and the chat is the problem. Keep it to yourself and tell your grown up about the question."},
{"q":"What is the real life check?","old":"Have they been nice to me for a long time?","new":"Have they been nice to me for a long time, and do they play every day?","fb":"Nice and daily are what any stranger can do. The check is: have I met them in real life, and does my family know them?"},
{"q":"What is the real life check?","old":"Do they have a cool avatar and lots of friends?","new":"Do they have a cool avatar and lots of friends, so they must be popular?"},
{"q":"A message in the group chat calls you a nasty name. Your fingers are ready to fire back. What is the strong move?","old":"Delete it and pretend you never saw it","new":"Delete it and say nothing, so it dies down","fb":"Deleting it deletes your proof. Stop, screenshot it, and show a trusted adult today."},
{"q":"Why do we save the message before we tell?","old":"So we can reply to it later when we are calm","new":"So we can read it again later and write the perfect reply when calm","fb":"The perfect reply is no reply. We save it as proof, so a grown up can see exactly what happened."},
{"q":"Why does replying fast hand the sender a win?","old":"Because typing fast makes spelling mistakes","new":"Because typing fast makes spelling mistakes, and they will mock those too","fb":"Spelling is not the point. They wanted a reaction, and any fast reply is exactly that."},
{"q":"Why does replying fast hand the sender a win?","old":"It does not. Fast replies win arguments","new":"It does not. Fast replies win arguments before they get going"},
{"q":"A message says: we are the game team, send your password so we can fix your account. What do you know?","old":"Send it quickly so the account gets fixed","new":"Send it quickly, because a broken account is the bigger problem","fb":"The real team never asks for your password, broken account or not. Trick: stop and tell."},
{"q":"What makes the three word trick strong?","old":"Three random words make a long password that is easy for you and hard to guess","new":"Three random words are easy for you to remember and hard to guess"},
{"q":"What makes the three word trick strong?","old":"It uses your pet's name three times","new":"Three words all about you, like your pet, your street and your team","fb":"Words about you are the first words a guesser tries. Random is what makes the three strong."},
{"q":"Your best friend asks for your game password so they can look after your account on holiday. What is the strong move?","old":"Tell them, best friends share everything","new":"Tell them, because a best friend would never do anything bad with it","fb":"Best friends fall out, and passwords get passed on. Passwords stay with you and your family."},
{"q":"Your best friend asks for your game password so they can look after your account on holiday. What is the strong move?","old":"Change one letter and tell them that version","new":"Change one letter and tell them that version, so it is not really your password"},
{"q":"Which of these is a real cool down lap?","old":"Arguing for more time","new":"One calm video on the telly, which is not a screen","fb":"The telly is a screen too. A cool down lap is something your body does: star jumps, water, building."},
{"q":"Why does a cool down lap work?","old":"It gives your body something to do while the flat feeling fades on its own","new":"It gives your body something to do while the flat feeling fades"},
{"q":"Why does a cool down lap work?","old":"It punishes you for using screens","new":"It burns off the screen time you used, so your next go can be longer","fb":"Nothing is being burnt off. The lap gives your body something to do while the flat feeling fades."},
{"q":"Why does a racer take a cool down lap instead of stopping dead?","old":"To show off one more lap","new":"To squeeze in one more lap, because the race is not over until they say","fb":"The race is over. The slow lap is for the body, and yours handles endings better slowly too."},
{"q":"Why does a racer take a cool down lap instead of stopping dead?","old":"Because the brakes do not work at full speed","new":"Because the brakes do not work at full speed, so they have no choice"},
{"q":"Who else is in charge of what you post about THEM?","old":"Only teachers and parents","new":"Only grown ups, because children cannot refuse","fb":"Children can say no to a photo of themselves, and so can you. People in a photo get asked first."},
{"q":"Why does deleting a post not really make it disappear?","old":"Because deleting is against the rules","new":"Because the app keeps it hidden for a week in case you change your mind","fb":"It is not the app keeping it. Other people may already have copies and screenshots."},
{"q":"Your friend does something really funny and embarrassing, and you film it. What is the strong move?","old":"Run the check, and since it could embarrass them, ask your friend first","new":"Run the check, and since it could embarrass them, ask them first"},
{"q":"Your friend does something really funny and embarrassing, and you film it. What is the strong move?","old":"Post it, everyone will laugh","new":"Post it, because everyone will laugh and your friend will laugh too","fb":"Your friend laughing in the room is not a yes for the internet. Ask them first."},
{"q":"Your friend does something really funny and embarrassing, and you film it. What is the strong move?","old":"Post it now but delete it after an hour","new":"Post it now but delete it after an hour, before it spreads"},
{"q":"A chatbot gives you a fact for your school project and it sounds brilliant. What is the strong move?","old":"Ask the chatbot again to see if it says the same thing","new":"Ask the chatbot again, and trust it if it says the same thing twice","fb":"Twice from the same guesser is still a guess. Look it up somewhere trusted before you use it."},
{"q":"The chatbot answers in a super confident voice. What does that tell you about whether it is right?","old":"Confident voice means a confident fact","new":"A lot. A computer would only sound that sure if it had checked","fb":"It never checks. It sounds exactly the same when it is wrong, so the voice tells you nothing."},
{"q":"What is AI actually doing when it answers you?","old":"Looking up the one true answer in a big book","new":"Looking up the one true answer in a giant book of everything","fb":"There is no book. It guesses the next words from patterns in its examples, which is why it can be wrong."},
{"q":"What is AI actually doing when it answers you?","old":"Thinking it through like a person would","new":"Thinking it through like a person would, only faster"},
{"q":"Why does AI sometimes get things wrong?","old":"Because it learnt from examples and guesses the most likely answer, which is sometimes wrong","new":"It guesses the most likely answer from its examples, and a guess can miss"},
{"q":"Why does AI sometimes get things wrong?","old":"Because robots are bad","new":"Because someone typed a wrong fact into it and nobody has fixed it yet","fb":"Nobody typed the answers in. It guesses from patterns, and a likely guess is sometimes a wrong one."},
{"q":"A new game asks you to pick a username. What is the strong move?","old":"Use your real full name so friends can find you","new":"Use your real first name and your age, because that is what everyone does","fb":"A name and an age are keep box treasure. Make up a fun name that gives away nothing."},
{"q":"What is the difference between the show box and the keep box?","old":"The show box is fun things I choose to share, the keep box is real details that stay with my family","new":"Show box: fun things I share. Keep box: real details that stay with my family"},
{"q":"What is the difference between the show box and the keep box?","old":"The keep box is for things I am ashamed of","new":"The show box is for friends I know, the keep box is for strangers I have not met yet","fb":"Neither box is about who you know. The keep box holds real details, and they stay with your family whoever is asking."},
{"q":"What is the difference between the show box and the keep box?","old":"The show box is for the internet and the keep box is for lying","new":"The show box is for the internet and the keep box is for lying when someone asks"},
{"q":"Your avatar name idea is your real name plus your birth year. What is wrong with it?","old":"Nothing, it is easy to remember","new":"Nothing, a year is just a number","fb":"A year plus a name tells a stranger exactly who and how old you are. That is keep box treasure in the show box."},
{"q":"The timer goes but you are halfway through a level. What is the strong move?","old":"Ask for ten more minutes","new":"Ask for ten more minutes, because the timer does not know about levels","fb":"The timer does not need to know. You chose a save point before you started, so finish there and stop."},
{"q":"Why does choosing the finish point BEFORE you start work better than deciding at the end?","old":"Because grown ups say so","new":"Because at the end you will be tired, and tired brains always choose to stop","fb":"Tired brains choose one more go, not stop. That is why the calm brain before you start makes the choice."},
{"q":"Why does choosing the finish point BEFORE you start work better than deciding at the end?","old":"It does not matter when you decide","new":"It does not matter when you decide, as long as you decide"},
{"q":"Why does the end of screen time feel bad in your body?","old":"Because the little rewards stop suddenly and the feeling passes in a few minutes","new":"The little rewards stop suddenly, and the feeling passes in a few minutes"},
{"q":"Why does the end of screen time feel bad in your body?","old":"Because screens are bad for you","new":"Because screens are bad for you and your body is telling you so","fb":"Your body is not saying screens are bad. The little rewards stopped suddenly, and the feeling passes in a few minutes."},
{"q":"You stopped at your finish point and it still felt a bit bad. Did the plan fail?","old":"Yes, so next time do not stop","new":"Yes, so next time pick a later finish point so it never feels bad","fb":"A later finish point feels exactly the same at the end. The feeling is chemistry, and stopping anyway is the win."},
{"q":"A fun quiz in a game asks for your full name and your school to show your results. What do you do?","old":"Fill it in, quizzes are just for fun","new":"Fill it in, because a quiz inside a game you already play is safe","fb":"The game being fun does not make its boxes safe. Skip them, close it and tell your grown up."},
{"q":"A fun quiz in a game asks for your full name and your school to show your results. What do you do?","old":"Put in a nickname but your real school","new":"Put in a nickname but your real school, so the results still work"},
{"q":"A photo of you in your school jumper outside your front door. How many jigsaw pieces is that?","old":"One small one, the jumper","new":"One small one, the jumper, nothing else","fb":"The front door is a piece too. Jumper plus door is your school and where you live: two big ones."},
{"q":"Why do we protect small clues like a school jumper in a photo?","old":"Because schools ask us to","new":"Because the school logo belongs to the school, not to us","fb":"It is not about the logo. Small clues add up like jigsaw pieces, and a jumper is a big piece."},
{"q":"Why is your address private even from nice people online?","old":"It is not, nice people can know it","new":"It is not, as long as they have been nice to you for a long time","fb":"Nice for a long time is still online, where you cannot tell who else is reading."},
{"q":"Why is your address private even from nice people online?","old":"Because addresses are embarrassing","new":"Because addresses are embarrassing to share"},
{"q":"A pop up says: FREE ROBUX! Only 30 seconds left! Enter your password to claim. How many tells can you spot?","old":"One tell: it is rushing me","new":"Two tells: rushing and promising","fb":"Asking for your password is the third tell, and the biggest. All three: rushing, promising and asking."},
{"q":"It is 8pm, bed is at half past, and you really want one more episode. What is the strong move?","old":"Watch it, one episode cannot hurt","new":"Watch it, because one episode is only twenty minutes and cannot hurt","fb":"Twenty minutes of bright screen pushes sleep later. Screen away at the charging spot, book or chat instead."},
{"q":"Why do screens push sleep later?","old":"Bright light delays the sleepiness helper, and exciting content keeps the brain revved","new":"Bright light delays the sleepy helper, and exciting content revs the brain"},
{"q":"Why do screens push sleep later?","old":"Because screens use electricity near your bed","new":"Because sitting still watching means your body is not tired enough for bed","fb":"Your body can be tired and still not sleepy. Bright light delays the sleepy helper, and exciting content revs the brain."},
{"q":"Why do screens push sleep later?","old":"They do not, sleep only depends on how tired you are","new":"They do not, sleep only depends on how tired you are by bedtime"},
{"q":"A holiday photo looks perfect: blue sky, empty beach, glowing sea. Which benders could be at work?","old":"None, holiday photos are always honest","new":"None, a camera only shows what was there","fb":"A camera shows what was in the frame, after the crop and the filter. Cropped and filtered, easily both at once."},
{"q":"A photo of a toy looks perfect in the advert but the real toy looks worse at home. Which truth bender was probably at work?","old":"Nothing, cameras just make things look better","new":"Nothing, because shop cameras are better than yours, so it just looks nicer","fb":"The camera is not the difference. The photo was staged and filtered, arranged and polished to sell."},
{"q":"A photo shows a giant shark swimming next to a surfer, and it looks amazing. What is the smart first move?","old":"Believe it, photos show what really happened","new":"Believe it, because a photo that clear could not have been made up","fb":"Clear is easy to make up now. Ask who made this and why, and show a grown up if it is everywhere."},
{"q":"A photo shows a giant shark swimming next to a surfer, and it looks amazing. What is the smart first move?","old":"Share it quickly so your friends see it first","new":"Share it quickly so your friends see it first, before it goes viral"},
{"q":"Why does treating a photo as a claim make you smarter, not just more suspicious?","old":"Because all photos are fake now","new":"Because doubting everything is what the cleverest people do","fb":"Doubting everything is not clever, it is just tiring. Checking is quick: who made this, and why?"},
{"q":"A YouTuber you love says a new game is the best ever made. Which coat is that, and what do you do with it?","old":"News, because they have lots of subscribers","new":"News, because someone with that many subscribers has to tell the truth","fb":"Subscribers do not turn an opinion into news. It is opinion, so enjoy it without treating it as fact."},
{"q":"Opinion is not a bad coat. What is the one rule for it?","old":"Only grown ups may have opinions","new":"An opinion is fine as long as lots of people agree with it","fb":"Lots of people agreeing is still opinion. Know it is opinion, and do not let it dress as news."},
{"q":"Opinion is not a bad coat. What is the one rule for it?","old":"Opinions should never be shared","new":"Opinions should never be shared online"},
{"q":"Your cousin shares a story that made them really angry. Before you share it on, what do you ask?","old":"How angry did it make me too?","new":"Does it make me angry too, so it must be true?","fb":"A strong feeling is not a check. Ask which coat it is wearing, and who checked it."},
{"q":"Someone in the game keeps calling you names in chat. What is the ladder?","old":"Reply with worse names so they stop","new":"Reply with something worse, because bullies only stop when you win","fb":"Winning the name game feeds it. Mute them, leave if it is still not fun, and tell your grown up."},
{"q":"When does mute become leave?","old":"Never, muting always fixes it","new":"Never, because leaving a game means the person calling names has won","fb":"Leaving is not losing. When muting one person is not enough to make it fun, you leave, and the fun goes with you."},
{"q":"When does mute become leave?","old":"The moment anyone annoys you slightly","new":"The moment anyone annoys you slightly, to be safe"},
{"q":"You just won three games in a row. Which message passes the rematch test?","old":"Say nothing and leave straight away","new":"Say nothing, so it is not showing off","fb":"Silence after three wins reads as cold. Good games! That last one was so close, passes the test."},
{"q":"You lost three in a row and the winner is gloating. What passes the rematch test from YOUR side?","old":"Quit without a word","new":"Quit without a word, because gloating means they do not deserve a reply","fb":"The reply is for you, not them. Good game, one more? Losing steadily is a skill."},
{"q":"A game only offers boy heroes, rescuing girl characters. Who decided that?","old":"The players voted for it","new":"The players, because games only sell what most players already like","fb":"Players never got a vote. The makers chose the shortcut, and a stereotype is a choice, not a rule."},
{"q":"A game only offers boy heroes, rescuing girl characters. Who decided that?","old":"Nobody, games just come out that way","new":"Nobody, games just come out that way by themselves"},
{"q":"An advert shows only boys playing the new building set, but your friend who is a girl would love it. What is going on?","old":"Your friend should like something else instead","new":"Your friend is unusual, and adverts show what is normal","fb":"Your friend is not unusual. The advert took a shortcut, and the set is for whoever likes building."},
{"q":"Why do games and adverts use so many stereotype shortcuts?","old":"Because shortcuts are true about everyone","new":"Because the makers did surveys, and the shortcuts are true for everyone","fb":"No survey covers everyone. Shortcuts are quick and cheap for the people making them, that is all."},
{"q":"Your friend, a boy, loves baking videos and hides it from the class. What is true?","old":"He should switch to football videos","new":"He is right to hide it, because the class would only tease him for it","fb":"Hiding it hands the shortcut the win. Real people are bigger than shortcuts. He gets to like what he likes."},
{"q":"Your friend, a boy, loves baking videos and hides it from the class. What is true?","old":"Baking videos are for girls","new":"Baking videos are for girls, that is just how it is"}
]$j$::jsonb)
where stage_id = 'builder' and status = 'live' and slides is not null;
