-- 248: question balance, Independent (16 plus, and the Taking the wheel
-- parent deck). Same fix as 245, same helper. Also replaces one duplicate
-- question in Building with AI: the school arc added a yes or no version of
-- the cover letter scenario the deck already opened with, so the second
-- becomes a fresh editor's pass question.

update public.lessons set slides = public.gc_swap_option_text(slides, $j$[
{"q":"AI drafts your cover letter. It reads beautifully, but one line stretches your experience beyond the truth. What is the strong move?","old":"Send it. It sounds professional and everyone stretches a little","new":"Send it. It sounds professional, everyone stretches a little, and the interview is where the truth comes out","fb":"The interview is where the stretched line gets asked about. Run the editor's pass: fix the claim, cut what is not you, rewrite it into your voice."},
{"q":"What is the editor's pass?","old":"Checking, correcting and rewriting anything AI touched until it is true and sounds like you","new":"Checking, correcting and rewriting anything AI touched until it is true and yours"},
{"q":"What is the editor's pass?","old":"Running the output through a second AI to check the first one","new":"Running the output through a second AI to check the first one, then sending whatever both agree on","fb":"Two guessers agreeing is still a guess. The pass is you: checking, correcting and rewriting until it is true and yours."},
{"q":"What is the editor's pass?","old":"A rule that AI must never be used for anything that matters","new":"A rule that AI must never be used for anything that matters, like applications"},
{"q":"When AI gets cheap at producing work, what stays paid?","old":"Only jobs with no computers","new":"Only the trades, where computers cannot reach, so retrain now","fb":"Trades are fine, and so is everything else that needs judgement: knowing what good looks like and catching what is wrong."},
{"q":"A mate is getting shredded in a big group chat and the jokes keep coming. What is the strong move?","old":"Message your mate privately, report the worst messages, and add one calm line in the chat only if it feels safe to","new":"Message your mate privately, report the worst of it, and add one calm line only if it feels safe"},
{"q":"A mate is getting shredded in a big group chat and the jokes keep coming. What is the strong move?","old":"Leave the chat quietly so you are not part of it","new":"Leave the chat quietly, because staying makes you part of it and leaving is the cleanest protest there is","fb":"Leaving protests to nobody and leaves your mate alone in there. Message them privately, report the worst, one calm line if safe."},
{"q":"What does the private message do that the public defence cannot?","old":"Nothing, public support is worth more","new":"Nothing much, because support nobody else can see does not count as standing up for someone","fb":"It counts to the one person it is for. It reaches them without feeding the pile."},
{"q":"What does the private message do that the public defence cannot?","old":"It is quicker to type","new":"It is quicker to type than a proper defence"},
{"q":"When does reporting beat replying?","old":"When the content breaks rules, when there are threats or private images, or when any reply would just feed it","new":"When the content breaks rules, involves threats or private images, or when any reply would feed it"},
{"q":"When does reporting beat replying?","old":"Only when you are the one being targeted","new":"Only when you are the one being targeted, because reporting for someone else is not your place","fb":"Reporting for someone else is exactly your place. It beats replying whenever rules are broken or a reply would feed it."},
{"q":"Why does even a DEFENDING reply push the pile higher?","old":"It does not, defences calm things down","new":"It does not, because a well written defence makes the ringleader look foolish and ends it","fb":"The algorithm cannot read who looked foolish. It reads replies as engagement and shows the pile to more people."},
{"q":"A clothing brand DMs you: they love your artwork, want to repost it, and ask for the original file. They offer exposure to eighty thousand followers. What is the strong move?","old":"Run the rights check, then reply asking what they will pay and exactly what use they want, in writing","new":"Run the rights check, then ask what they will pay and exactly what use they want, in writing"},
{"q":"A clothing brand DMs you: they love your artwork, want to repost it, and ask for the original file. They offer exposure to eighty thousand followers. What is the strong move?","old":"Send the file. Exposure to eighty thousand people has to be worth something","new":"Send the file. Exposure to eighty thousand people has to be worth something, and asking about money looks ungrateful","fb":"Asking about money is what professionals do, and brands expect it. Run the rights check, then ask what they pay and what use they want, in writing."},
{"q":"A clothing brand DMs you: they love your artwork, want to repost it, and ask for the original file. They offer exposure to eighty thousand followers. What is the strong move?","old":"Block them. Any brand sliding into your DMs is a scam","new":"Block them. Any brand sliding into your DMs is a scam, real ones use email"},
{"q":"A competition's terms say all entries become their property. What is that?","old":"Standard, all competitions work that way","new":"Standard and fair, because running one costs money","fb":"Costs do not buy your copyright. That is a rights grab, exactly what the rights check exists to catch."},
{"q":"Exposure to eighty thousand followers: what is it actually worth as payment?","old":"Exactly £80","new":"About a pound a follower, which is the industry standard rate for exposure","fb":"There is no rate, because exposure is not a payment. Nothing enforceable: a licence and a fee are terms."},
{"q":"What does it mean to license your work to someone?","old":"They rent agreed uses of it, for an agreed time or purpose, while you keep ownership","new":"They rent agreed uses for an agreed time or purpose, and you keep ownership"},
{"q":"What does it mean to license your work to someone?","old":"They can use it however they like as long as they credit you","new":"They can use it however they like as long as they credit you, and credit is what a licence guarantees","fb":"Credit is a courtesy, not a licence. A licence rents agreed uses for an agreed time, and you keep ownership."},
{"q":"What does it mean to license your work to someone?","old":"They own it now and can do anything with it forever","new":"They own it now and can do anything with it forever, that is the deal"},
{"q":"The 1am video habit nobody chose: default or decision?","old":"Neither, it is fate","new":"Both, and it does not matter as long as you enjoy them","fb":"It matters at 8am. Default: autoplay and the bedside phone decided it, not you."},
{"q":"What is the difference between a default and a decision?","old":"A default is a choice someone else made for you, still running. A decision is one you examined and made on purpose","new":"A default is someone else's choice, still running. A decision is one you examined and made"},
{"q":"What is the difference between a default and a decision?","old":"Defaults are always bad and decisions are always good","new":"Defaults are always bad and decisions are always good, so the goal is to change every setting on the phone","fb":"Plenty of defaults are fine. The goal is to know which ones are running you, and decide those on purpose."},
{"q":"Why does design matter MORE at university than it does at home?","old":"It matters less, university has rules","new":"It matters less, because by eighteen your habits are set and design cannot change them","fb":"Habits are exactly what design changes, at any age. Freedom arrives as structure leaves, and your defaults become the only structure."},
{"q":"Why does design matter MORE at university than it does at home?","old":"Because university wifi is faster","new":"Because university wifi is faster and always on"},
{"q":"You notice you are watching videos until one in the morning most nights, and you never actually decided to. What is the strong move?","old":"Run default or decision: choose your real finish time, then set the phone up to back the choice, autoplay off and charging out of reach","new":"Choose your real finish time, then make the phone back it: autoplay off, charging out of reach"},
{"q":"You notice you are watching videos until one in the morning most nights, and you never actually decided to. What is the strong move?","old":"Accept it. Everyone your age is up watching the same stuff","new":"Accept it. Everyone your age is up watching the same stuff, and you will grow out of it","fb":"Growing out of it is not a plan. Choose your real finish time, then make the phone back it."},
{"q":"A first meeting goes badly: the person was nothing like their profile and pushed to move somewhere private. Whose fault is that, and what is the move?","old":"Nobody needs to know, since nothing serious actually happened in the end","new":"Nobody needs to know, since nothing serious happened, and telling people would just worry them for no reason","fb":"Someone pushing you somewhere private is serious whatever happened next. The fault is theirs, and the move is telling someone you trust straight away."},
{"q":"Someone you have talked to for three months suggests finally meeting. They offer to pick you up and drive you to their place. What is the strong move?","old":"Say you would love to meet, and counter with the first meet plan: a public place, someone told, your own way there and back","new":"Say yes to meeting, and counter with the plan: a public place, someone told, your own way there and back"},
{"q":"Someone you have talked to for three months suggests finally meeting. They offer to pick you up and drive you to their place. What is the strong move?","old":"Agree. Three months of talking every day means you basically know them","new":"Agree. Three months of talking every day means you basically know them, and insisting on your own plan would insult them","fb":"A genuine person is not insulted by a public place. Say yes, and counter with the plan: public, someone told, your own way home."},
{"q":"Someone you have talked to for three months suggests finally meeting. They offer to pick you up and drive you to their place. What is the strong move?","old":"Cancel the whole thing. Meeting people from the internet is not worth the risk","new":"Cancel the whole thing. Meeting people from the internet is not worth the risk at any age"},
{"q":"Who gets told about the meet, and when?","old":"Nobody, you are an adult now","new":"Nobody, because you are an adult and can handle yourself","fb":"Adults tell people where they are going. Someone you trust, with the place and time, before, not after."},
{"q":"You are completely sure about this person. Why does the plan still hold?","old":"It does not, certainty earns exceptions","new":"It does not, because three months of daily conversation is more than most people know about a stranger","fb":"Three months of typing is still a stranger. You cannot tell which few are not real, and the plan costs nothing when they are."},
{"q":"The logged out look finds an old account full of posts from when you were fourteen. Nothing terrible, but it reads badly now. What is the strong move?","old":"Delete or lock it, then publish something current you are proud of so the real you rises up the results","new":"Delete or lock it, then publish something current you are proud of, so the real you rises"},
{"q":"The logged out look finds an old account full of posts from when you were fourteen. Nothing terrible, but it reads badly now. What is the strong move?","old":"Leave it. Everyone knows people grow out of their fourteen year old selves","new":"Leave it. Everyone knows people grow out of their fourteen year old selves, and deleting it looks like you have something to hide","fb":"Nobody reads a tidy record as hiding. Delete or lock it, then publish something current, so the real you rises up the results."},
{"q":"The logged out look finds an old account full of posts from when you were fourteen. Nothing terrible, but it reads badly now. What is the strong move?","old":"Make a glowing fake profile under a slightly different spelling to push it down","new":"Make a glowing fake profile under a slightly different spelling to push it down the results"},
{"q":"What is actually worth building on the record, on purpose?","old":"Daily updates about everything","new":"Daily updates, because an active account looks more employable","fb":"Active is not the same as good. Work you would defend out loud: projects, skills, things you made."},
{"q":"Why does the audit happen logged out, in a private window?","old":"Because logged in results are personalised to you, and a stranger sees a different, colder page","new":"Logged in results are personalised to you. A stranger sees a different, colder page"},
{"q":"Why does the audit happen logged out, in a private window?","old":"Because private windows delete things from the internet as you find them","new":"Because a private window hides the search from your own history, so the audit cannot affect your feed","fb":"Your feed is not the point. Logged out, you see the colder page a stranger sees, which is the one that matters."},
{"q":"Why lock or delete selectively rather than panic deleting everything?","old":"Panic deleting is faster and safer","new":"Panic deleting is faster and safer, because an empty record cannot be held against you","fb":"An empty record says nothing for you either. The record should end up yours, not empty. Build follows clean."},
{"q":"Why lock or delete selectively rather than panic deleting everything?","old":"Deleting anything is impossible","new":"Deleting anything is impossible once it has been indexed"},
{"q":"A text says your bank account is compromised: click the link in the next ten minutes and move your balance to a safe account. What is the strong move?","old":"Ignore the link, open your banking app yourself or call the number on your card, and tell someone what arrived","new":"Ignore the link. Open your banking app yourself or call the number on your card, then tell someone"},
{"q":"A text says your bank account is compromised: click the link in the next ten minutes and move your balance to a safe account. What is the strong move?","old":"Click fast. Fraud is time sensitive and this could be real","new":"Click fast. Fraud is time sensitive, this could be real, and ten minutes is not long to check","fb":"Ten minutes is the pressure, not the reality. Open the real app yourself or call the number on your card."},
{"q":"What breaks the urgency plus authority engine every time?","old":"Asking them to prove they are the bank","new":"Asking them security questions only the real bank could answer, like your account number","fb":"Scammers often already have your account number. Hang up and call the real number you find yourself."},
{"q":"Why does your email get secured before every other account?","old":"Because email companies make you do it","new":"Because it is usually the oldest account you own, and older accounts tend to have weaker passwords","fb":"Age is not the reason. Password resets flow through email, so it is the master key to everything else."},
{"q":"Why does your email get secured before every other account?","old":"Because email holds the most embarrassing things","new":"Because email holds the most embarrassing things you have written"},
{"q":"Why is move your balance to a safe account ALWAYS a scam?","old":"It is not, banks do this in emergencies","new":"It is not, in a real breach the bank moves money fast","fb":"A real bank freezes and refunds. It never asks you to move money. The safe account is the thief's."},
{"q":"What is the byline test?","old":"Imagining your full name printed under the post and asking if you would stand by it in any room","new":"Imagining your full name under the post and asking if you would stand by it in any room"},
{"q":"What is the byline test?","old":"Making separate anonymous accounts so nothing links back to you","new":"Making separate anonymous accounts so nothing links back to you, which is what the byline is","fb":"Anonymous is the opposite of a byline. The test is your full name under the post, and whether you would stand by it in any room."},
{"q":"Why run the byline test on comments too, not just posts?","old":"No need, comments disappear","new":"No need, because comments sit buried under the post and nobody ever searches them","fb":"Search finds comments, and screenshots keep them. Everything carries the byline."},
{"q":"Why run the byline test on comments too, not just posts?","old":"Because comments have a word limit","new":"Because comments have a word limit, so they need more care"},
{"q":"You have typed a savage joke about a classmate into the group chat. It would land. You also have a university interview next month. What is the strong move?","old":"Run the byline test. If you would not own it with your name attached in any room, rewrite it or let it go","new":"Run the byline test. If you would not own it with your name in any room, rewrite it or let it go"},
{"q":"You have typed a savage joke about a classmate into the group chat. It would land. You also have a university interview next month. What is the strong move?","old":"Send it. Group chats are private","new":"Send it. Group chats are private, and no admissions tutor is reading your mates' group messages","fb":"Tutors do not need to read the chat. One screenshot travels on its own. Run the byline test first."},
{"q":"You talk one way with your mates and another way in interviews. Is that fake?","old":"Yes, always speak formally everywhere","new":"Yes, because a person with one set of values should sound the same in every room","fb":"Values stay the same, tone changes. Register is normal. The byline test is about content, not tone."},
{"q":"A big story breaks and your feed floods with furious thirty second clips. You want to post about it. What is the strong move?","old":"Share the most powerful clip while it is still trending","new":"Share the most powerful clip while it is still trending, because being early is how you get heard","fb":"Early and wrong is how you get remembered. Check your chosen three first, then share once you know what happened."},
{"q":"A big story breaks and your feed floods with furious thirty second clips. You want to post about it. What is the strong move?","old":"Assume it is all fake and ignore the story completely","new":"Assume it is all fake and ignore the story completely until next week"},
{"q":"A big story is one hour old. What do you know about most of what you are seeing?","old":"The first hour is the most accurate hour","new":"The first hour is the most accurate, because it is raw footage before anyone spins it","fb":"Raw footage with no context is the easiest thing to misread. It is the fastest take, not the checked one."},
{"q":"Why does outrage travel faster than accuracy?","old":"Accurate news is illegal to promote","new":"Because outrage is usually a sign that something true has been uncovered","fb":"Outrage is a sign that something holds attention, true or not. The feed serves what holds."},
{"q":"Why does the chosen three include a source you disagree with?","old":"Because a diet of pure agreement makes you easier to fool, and it shows you where your own case is weak","new":"A diet of pure agreement makes you easier to fool, and it shows where your own case is weak"},
{"q":"Why does the chosen three include a source you disagree with?","old":"Because every disagreement means the truth sits exactly in the middle","new":"Because every disagreement means the truth sits exactly in the middle, so you need both ends to find it","fb":"The truth is not always in the middle. The other source is there to show you where your own case is weak."},
{"q":"Why does the chosen three include a source you disagree with?","old":"So you can screenshot their worst takes and dunk on them","new":"So you can screenshot their worst takes and dunk on them publicly"},
{"q":"What does verified actually mean for a shocking voice clip?","old":"It has over a million plays","new":"It has over a million plays, so someone would have spotted a fake","fb":"A million people spotting nothing is not verification. A credible independent source confirming it happened is."},
{"q":"Why is sharing an unverified clip worse than just believing it privately?","old":"Because your share is an endorsement that spends your credibility and fuels the machine","new":"Your share is an endorsement. It spends your credibility and fuels the machine"},
{"q":"Why is sharing an unverified clip worse than just believing it privately?","old":"It is not, sharing is neutral","new":"It is not, because sharing is neutral and your followers can make their own minds up","fb":"A share is not neutral, it is your name saying look at this. It spends your credibility and fuels the machine."},
{"q":"Why is squinting at pixels a losing game?","old":"Squinting is bad for your eyes","new":"It is not, because every fake leaves artefacts and a trained eye will always find them","fb":"Last year's artefacts are gone this year. Fakes improve monthly, and the method does not depend on the fake's quality."},
{"q":"Why is squinting at pixels a losing game?","old":"Screens are too small to squint at","new":"Screens are too small to squint at properly"},
{"q":"A password leaks from some small forum you forgot you joined. Where does it get tried next?","old":"Nowhere, small leaks stay small","new":"Nowhere much, a small forum leak is not worth a criminal's time","fb":"It costs them nothing to try. Leaked passwords are tried against every big service automatically."},
{"q":"The threat message says: do not tell anyone or i send them now. Why is that sentence in there?","old":"Because isolation is their only real weapon: a victim who tells someone stops being controllable","new":"Isolation is their only real weapon. A victim who tells someone stops being controllable"},
{"q":"The threat message says: do not tell anyone or i send them now. Why is that sentence in there?","old":"Because they are being considerate about embarrassment","new":"Because they are being considerate about embarrassment, which shows they can be reasoned with","fb":"Nothing in a threat is considerate. Isolation is their only real weapon, and telling someone takes it away."},
{"q":"What does two step verification actually buy you?","old":"Nothing, it is security theatre","new":"Nothing much, because anyone who has your password can get the code too","fb":"The code goes to your phone, not to them. A stolen password alone stops being enough to get in."},
{"q":"What does two step verification actually buy you?","old":"Faster logins","new":"Faster logins on devices you use a lot"},
{"q":"Why is one reused password across ten accounts worse than one weak password on one account?","old":"It is not, weak passwords are always the bigger risk","new":"It is not, a strong password stays strong wherever you use it","fb":"Strong until one site leaks it. Then one leaked site becomes a master key to every account you own."},
{"q":"Losing an hour to the phone at 1am: what is the design move, as opposed to the discipline move?","old":"Promising yourself to stop earlier","new":"Promising yourself to stop earlier, but this time writing it down so it sticks","fb":"Written or not, that is discipline, and it loses at 1am. The phone charges outside the room, and the fight is won in the afternoon."},
{"q":"What is the operator question, and when do you ask it?","old":"Am I running this, or is it running me, asked as regular maintenance with no shame attached","new":"Am I running this, or is it running me, asked as regular maintenance, no shame attached"},
{"q":"What is the operator question, and when do you ask it?","old":"How many hours did I use this week, asked when you feel guilty","new":"How many hours did I use this week, asked whenever you feel guilty, because guilt is the honest signal","fb":"Guilt is a bad clock and hours are a bad measure. Am I running this, or is it running me, asked as regular maintenance."},
{"q":"What is the operator question, and when do you ask it?","old":"Is this app good or bad, asked before downloading","new":"Is this app good or bad, asked before downloading anything"},
{"q":"Why schedule the drift check at all, if the design works?","old":"No reason, good designs are permanent","new":"No reason, a good design holds without checking","fb":"Apps update and defaults creep back. No design lasts unwatched."},
{"q":"You keep losing an hour to your phone at 1am. What is the design move, rather than the discipline move?","old":"Keep the phone by the bed but turn the brightness down","new":"Keep the phone by the bed but turn the brightness down and put it on silent, so it bothers you less","fb":"Silent and dim is still within reach at 1am. Charge it outside the bedroom so the choice never gets offered."},
{"q":"Letting someone pass £300 through your bank account for a £50 cut: what is actually being bought?","old":"Your name on the crime: the money is stolen and the account holder carries the risk and the record","new":"Your name on the crime. The money is stolen, and the account holder carries the record"},
{"q":"Letting someone pass £300 through your bank account for a £50 cut: what is actually being bought?","old":"Nothing much, it is just borrowing an account","new":"Nothing much, because it is just borrowing an account and the money is in and out in a day","fb":"In and out in a day is exactly how laundering looks. Your name on the crime: the account holder carries the record."},
{"q":"Letting someone pass £300 through your bank account for a £50 cut: what is actually being bought?","old":"A short term loan with interest","new":"A short term loan with interest, paid in cash"},
{"q":"The guaranteed £100 into £900 in a week offer: what settles whether it is real before any money moves?","old":"Trying £20 first to test it","new":"Trying £20 first, because a small loss is a cheap way to find out","fb":"The £20 is the bait, and it often pays out to hook you for more. Guaranteed returns do not exist, so the offer disproves itself."},
{"q":"What does the word GUARANTEED tell you about an investment offer, all by itself?","old":"That the returns are merely likely","new":"That the returns are merely likely, since nobody would risk their reputation on a promise","fb":"Scammers have no reputation to risk. Real investments cannot guarantee returns, so the word itself is the tell."},
{"q":"Why does follow the money explain a free app better than its own description does?","old":"It does not, descriptions are accurate","new":"It does not, because descriptions are legally checked and following money is just cynicism","fb":"Descriptions list features and leave out the business. The money names whose interests the app serves."},
{"q":"Why does follow the money explain a free app better than its own description does?","old":"Because money is the root of all evil","new":"Because money is the root of all evil, apps included"},
{"q":"A proposal says messaging apps must scan all messages for illegal content before sending. A friend says: I have nothing to hide, so why should I care? What is the strongest honest reply?","old":"Scanning everyone changes what privacy IS for every citizen, so the case for it has to be strong enough to justify that, and we should each know if we think it is","new":"Scanning everyone changes what privacy is for every citizen, so the case has to be strong enough to justify that"},
{"q":"A proposal says messaging apps must scan all messages for illegal content before sending. A friend says: I have nothing to hide, so why should I care? What is the strongest honest reply?","old":"Agree, people with nothing to hide lose nothing","new":"Agree, because people with nothing to hide lose nothing, and objecting is what people with something to hide do","fb":"Victims, journalists and dissidents object loudest, and they have the most to lose. Privacy is for every citizen, so the case has to be strong."},
{"q":"What is technically wrong with a backdoor built only for the good guys?","old":"Nothing, keys can check credentials","new":"Nothing, because the key can be held by the police and only used with a warrant","fb":"The key can be copied by whoever finds it, warrant or not. Doors do not check credentials."},
{"q":"Why does where should the line sit beat privacy always wins or safety always wins?","old":"Because both values are real, so every position is a trade off, and a line is a position you can actually defend and revise","new":"Both values are real, so every position is a trade off, and a line can be defended and revised"},
{"q":"Why does where should the line sit beat privacy always wins or safety always wins?","old":"Because the middle of any argument is always right","new":"Because the middle of any argument is always right, and a line is just a polite word for the middle","fb":"The line does not have to be in the middle. It is a position you can defend and revise, because both values are real."},
{"q":"Why does where should the line sit beat privacy always wins or safety always wins?","old":"It does not, one side is simply correct","new":"It does not, one side is simply correct and the other is wrong"},
{"q":"Why is nothing to hide the weakest position in the whole debate?","old":"Privacy protects the vulnerable most: victims, journalists, dissidents. Your comfort is not the measure","new":"Privacy protects victims, journalists and dissidents most. Your comfort is not the measure"},
{"q":"Why is nothing to hide the weakest position in the whole debate?","old":"Because everyone has something to hide","new":"Because everyone has something to hide, so the honest reply is to admit it","fb":"It is not about what you have to hide. Privacy protects the people with the most to lose, and your comfort is not the measure."},
{"q":"What does gripping the dashboard look like, from the passenger seat?","old":"Sitting in the back seat instead","new":"Asking how their day was online, every evening, and listening to the answer","fb":"Asking and listening is the passenger seat done well. Gripping is checking their feeds and quizzing every choice: control wearing concern."},
{"q":"What is the one thing to make unmissably clear as you hand over the wheel?","old":"That you will be checking up regularly","new":"That you will be checking up regularly, because trust has to be earned and verified","fb":"Checking up is the dashboard grip in a new coat. The one thing: coming to you with a problem will always be met with help."},
{"q":"What is the one thing to make unmissably clear as you hand over the wheel?","old":"That the wifi password changes weekly","new":"That the wifi password changes weekly, so the rules still hold"},
{"q":"Why does the built in protection stepping back at this age matter?","old":"The safeguards fade by design. Their own judgement is the replacement, and it needs handing over","new":"The safeguards fade by design. Their own judgement is the replacement, so hand it over"},
{"q":"Why does the built in protection stepping back at this age matter?","old":"It does not, the safeguards continue forever","new":"It does not, because most platforms keep the safeguards on until the account holder is 21","fb":"Most platforms drop them at 18, some at 16. The safeguards fade by design, so their own judgement has to be ready."},
{"q":"Your 17 year old wants to sort out their own social media use. What is the most useful thing you can offer?","old":"A firm rule about how long they are allowed on it.","new":"A firm rule about how long they are allowed on it, because structure is what they secretly want.","fb":"At 17 the structure has to be theirs. A question that hands them the decision, and your trust in their reasoning."}
]$j$::jsonb)
where stage_id = 'independent' and status = 'live' and slides is not null;

-- Building with AI opened with the stretched cover letter and then asked it
-- again as a yes or no. The second becomes the paragraph you cannot explain.
update public.lessons l set slides = (
  select jsonb_agg(
    case when s.value->>'type' = 'choice'
          and s.value->>'question' = 'The AI cover letter reads beautifully, and one line stretches your experience beyond the truth. Ship it?'
      then s.value || $s${"question":"AI wrote a paragraph you do not fully understand, but it sounds impressive. What does the editor's pass say?","options":[{"text":"Keep it, because sounding impressive is the point of a cover letter","correct":false,"feedback":"Impressive you cannot explain falls apart in the interview. Cut it or learn it."},{"text":"Cut it or learn it. Nothing goes out under your name that you could not defend out loud","correct":true,"feedback":"That is the pass doing its job. Your name, your claims, your words when someone asks."},{"text":"Keep it but add a line saying AI helped, so nobody can accuse you of anything","correct":false,"feedback":"A disclaimer does not make the claim yours. Cut it or learn it, then the letter is honest without one."}]}$s$::jsonb
      else s.value end
    order by s.ordinality)
  from jsonb_array_elements(l.slides) with ordinality s
)
where l.stage_id = 'independent' and l.status = 'live' and l.title = 'Building with AI' and l.slides is not null
  and exists (
    select 1 from jsonb_array_elements(l.slides) x
    where x.value->>'question' = 'The AI cover letter reads beautifully, and one line stretches your experience beyond the truth. Ship it?'
  );
