-- Guided Childhood — Migration 260
-- DiGi's situations and forecasts bank.
--
-- Justin, 6 September 2026: "DiGi needs to be clever enough to know all the
-- exact problems parents have with devices: after school, in the morning,
-- holidays, whether they use devices more to help with parenting, and helping
-- the parents deal with the stress ... forecasting what happens when a child
-- gets a new phone or starts to love a game on the Switch, how children can
-- learn AI in a safe way, and the US picture from Pew Research Center."
--
-- The bank knew topics (sleep, social media, mood). It did not know MOMENTS.
-- A parent types "he will not come off after school", not "screen time
-- transitions", and the rows below are tagged by the moment as well as the
-- topic so the keyword path and the meaning search both land on them.
--
-- Every row comes from the verified briefing
-- briefings/2026-09-06-digi-situations-and-forecasts-v2.html (six lenses,
-- six citation verifier passes). Findings whose figures could not be traced
-- to the primary source were left out or written without the figure. Nothing
-- here is a guess, and each row names the country its number comes from,
-- because an adoption figure is a UK or a US number, never a world one.
--
-- Situation tags: after_school, morning, holidays, parent_stress,
-- device_as_helper, balanced_use, pull_and_design, history, temperament,
-- adhd, autism, anxiety, new_phone, new_game, ai_use, ai_readiness, forecast.
-- The knowledge embed sweep gives each row its vector the same day.

insert into public.expert_knowledge (source_type, source_name, finding, age_bands, topics, url) values

-- After school and the endings
('researcher', 'Hiniker et al, Screen Time Tantrums (CHI 2016)', 'For under sixes the hardest moment is the end, not the start. In 27 interviews and a 28 family diary study, endings set by the technology (the show finished, the device timed out) went far better than endings called by a parent, and the spoken two minute warning made transitions worse. Let the episode end itself or set the device to end it, and agree the stopping point before it starts.', '{4-7}', '{after_school,routines,tantrum,screen_time}', 'https://dl.acm.org/doi/10.1145/2858036.2858278'),
('researcher', 'Baughan et al, children in Roblox and Minecraft (IDC 2024)', 'An online match cannot be paused, so a clock time that lands mid game is what turns a stop into a fight. Watching 17 children aged 8 to 13 play Roblox and Minecraft, researchers found the pauses the game itself starts are when a child can hear a parent. Set the stop at the end of the current match, agreed before play begins, rather than at a time on the clock.', '{8-10,11-13}', '{after_school,new_game,gaming,routines}', 'https://dl.acm.org/doi/10.1145/3628516.3655808'),
('report', 'Ofcom, Children''s Media Lives 2025', 'For most children a game is a room full of friends, not a solo screen. Ofcom''s filmed panel of children aged 8 to 18 found gaming working as a social activity, with children running Discord, FaceTime or Snapchat alongside Fortnite and Roblox so they can hear the game and their friends at once. Stopping feels like leaving a room. Ask who they were playing with before asking how long.', '{8-10,11-13,13-15,16+}', '{after_school,new_game,gaming,friendships}', 'https://www.ofcom.org.uk/siteassets/resources/documents/research-and-data/media-literacy-research/children/childrens-media-lives-2025/childrens-media-lives-2025-summary-report.pdf'),

-- The morning is lost the night before
('report', 'Carter et al, JAMA Pediatrics 2016 (sleep meta analysis)', 'A bad morning is mostly lost the night before. Across 20 studies and 125,198 children, using a device at bedtime roughly doubled the odds of too little sleep and nearly tripled the odds of daytime sleepiness, and a device merely present in the bedroom, switched off, still raised the odds of short sleep. Charge every device outside the bedroom, including the parent''s, and the morning gets easier on its own.', '{8-10,11-13,13-15,16+}', '{morning,sleep,routines,balanced_use}', 'https://jamanetwork.com/journals/jamapediatrics/fullarticle/2571467'),
('researcher', 'Nagata et al, Sleep Health 2023 (ABCD cohort)', 'In 10,280 US children aged 10 to 14, a screen in the bedroom raised the risk of trouble falling or staying asleep by 27%, and leaving the phone''s ringer on overnight raised it by 23% compared with switching the phone off. Two small settings, phone out of the room and ringer off, are the highest value morning fix there is (US figures).', '{8-10,11-13}', '{morning,sleep,new_phone,routines}', 'https://www.sciencedirect.com/science/article/pii/S2352721823000347'),
('association', 'RCPCH, the health impacts of screen time (2019)', 'The UK paediatricians give no hours limit. They ask four questions: is screen time in your house under control, does it interfere with what your family wants to do, does it interfere with sleep, and can you control snacking during it. Answer those honestly and you are doing as well as the evidence can tell you to. Keep screens out of the hour before bed; 88% of the 109 young people they consulted said screens hurt their sleep.', '{4-7,8-10,11-13,13-15,16+}', '{balanced_use,screen_time,sleep,routines}', 'https://www.rcpch.ac.uk/sites/default/files/2018-12/rcpch_screen_time_guide_-_final.pdf'),

-- Holidays
('researcher', 'Brazendale et al, the structured days hypothesis (2017)', 'Holidays are hard because the structure goes, not because children get worse. Across 190 studies of primary aged children, about 80% found sleep, movement and screen habits slide on unstructured days compared with school days. This is weekday versus weekend data about weight, not a holiday screen study, so treat it as a principle: give each holiday day two or three fixed anchors, a morning outing and a set screen window, and let the rest of the day stay loose.', '{4-7,8-10,11-13}', '{holidays,routines,screen_time,sleep}', 'https://ijbnpa.biomedcentral.com/articles/10.1186/s12966-017-0555-2'),

-- The calming screen and the parent's own stress
('report', 'Common Sense Media, Zero to Eight census 2025', 'Two thirds of US parents of under eights use screens to occupy a child so they can get things done or take a break, and that is not the pattern the research worries about. Using a screen to cook, work or breathe is fine and always was. The one to watch is the screen becoming the routine answer to a child who is upset. Keep occupy and calm as separate jobs in your head (US figure).', '{4-7}', '{device_as_helper,parent_stress,screen_time}', 'https://www.commonsensemedia.org/research/the-2025-common-sense-census-media-use-by-kids-zero-to-eight'),
('researcher', 'Radesky et al, JAMA Pediatrics 2023 (devices for calming)', 'If your three to five year old is the big feelings, high energy type, the phone is the last calming tool to reach for, not the first. In 422 children followed for six months, using a device to calm predicted more emotional reactivity later in boys and in high energy children, and the reactivity then drove more device use. Sit with them, name the feeling, offer a body based calm down, and keep the screen for occupying rather than soothing.', '{4-7}', '{device_as_helper,temperament,tantrum,mood}', 'https://jamanetwork.com/journals/jamapediatrics/fullarticle/2799042'),
('researcher', 'Radesky et al, JAMA Pediatrics 2016 (calming upset children)', 'Among 144 parents of toddlers, the less control and more frustration a parent felt over their child''s behaviour, the more likely they were to hand over a device to calm them. The device is often a sign of an exhausted parent, not a bad one. The first move is support for the parent, then a second calming tool to practise alongside the screen.', '{4-7}', '{device_as_helper,parent_stress,tantrum}', 'https://jamanetwork.com/journals/jamapediatrics/fullarticle/2498404'),
('researcher', 'McDaniel and Radesky, technoference (Pediatric Research 2018)', 'The loop runs both ways. In 183 couples with a child under five followed for six months, a child''s hard behaviour raised parenting stress, stressed parents retreated into their phones during time with the child, and that phone use went with more acting out and withdrawal in the child. Forgive yourself, then protect one short daily window, tea or bath, where your phone is genuinely out of reach.', '{4-7,8-10}', '{parent_stress,device_as_helper,mood,routines}', 'https://www.nature.com/articles/s41390-018-0052-6'),
('report', 'Pew Research Center, how teens and parents approach screen time (2024)', 'Teenagers notice the parent''s phone as sharply as the parent notices theirs. Among 1,453 US teens, 46% say a parent is at least sometimes distracted by their phone when the teen is trying to talk, while only 31% of parents say it happens regularly. A rule lands better when the parent visibly keeps the same rule at the table and at bedtime (US figures).', '{11-13,13-15,16+}', '{parent_stress,balanced_use,relationships}', 'https://www.pewresearch.org/internet/2024/03/11/how-teens-and-parents-approach-screen-time/'),
('researcher', 'Schmidt-Persson et al, JAMA Network Open 2024 (family screen trial)', 'Rules aimed only at the child have almost no trial evidence behind them. The one randomised trial that improved children''s mental health, 89 Danish families and 181 children, cut leisure screen use for the whole household for two weeks, and the children''s difficulties fell by a meaningful amount (Cohen d 0.53). If you want a rule to work, apply it to yourself too.', '{4-7,8-10,11-13,13-15}', '{parent_stress,balanced_use,screen_time,mood}', 'https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2821176'),

-- Balanced use: hours are a poor thermometer
('researcher', 'Orben and Przybylski, Nature Human Behaviour 2019', 'Hours are a poor thermometer. Across three datasets and 355,358 adolescents, digital technology use explained at most 0.4% of the variation in wellbeing, an association the authors compared to eating potatoes. Watch sleep, mood, friends and what the screen is replacing instead of counting minutes.', '{11-13,13-15,16+}', '{balanced_use,screen_time,mood}', 'https://www.nature.com/articles/s41562-018-0506-1'),
('researcher', 'Beyens, Valkenburg et al, Scientific Reports 2020', 'The same hour of social media leaves most teenagers unchanged, lifts some, and drags a minority down. Sampled six times a day for a week, 46% felt better after scrolling, 44% felt no different and 10% felt worse. Your job is to find out which one yours is, by asking how they feel afterwards, not by assuming harm.', '{13-15,16+}', '{balanced_use,temperament,social_media,mood}', 'https://www.nature.com/articles/s41598-020-67727-7'),
('researcher', 'Collier et al, parental mediation meta analysis (2016) and Lukavska et al (2022)', 'Across 57 studies the link between any parental mediation style and children''s outcomes is small, a meta analysis of adolescent problem internet use found active and restrictive mediation both sitting at zero, and in teens over 14 strict rules tracked slightly more problem use, not less. The rule is only as good as the relationship it sits inside; warmth predicted less problem use than control did.', '{8-10,11-13,13-15,16+}', '{balanced_use,parent_stress,screen_time,relationships}', 'https://www.sciencedirect.com/science/article/abs/pii/S0306460322001897'),
('researcher', 'Stoilova, Bulger and Livingstone, parental control tools review (2023)', 'A rapid review of 40 studies found parental control tools rarely do what families hope on their own. Use a control as a fence around a plan the child has agreed to, never instead of one, and say what the control does out loud so it is a shared rule rather than surveillance.', '{4-7,8-10,11-13,13-15,16+}', '{balanced_use,parent_stress,safety}', 'https://www.tandfonline.com/doi/full/10.1080/17482798.2023.2265512'),

-- Pull and design: the money, the buttons, the notifications
('report', 'Ofcom, Children''s Online Experiences 2026', '97% of UK 8 to 17 year olds play games online and 53% of them spend real money inside those games; among children who spent in the last month, 32% say they often regret it. The money arrives before the phone. Agree a fixed monthly amount in advance and never top it up mid month (UK figures).', '{8-10,11-13,13-15,16+}', '{pull_and_design,new_game,gaming,forecast}', 'https://www.ofcom.org.uk/siteassets/resources/documents/online-safety/research-statistics-and-data/protecting-children/childrens-online-experiences-research-report.pdf'),
('researcher', 'Xiao and Lund, loot boxes on the App Store (Royal Society Open Science 2025)', 'The games industry''s own UK rules say under 18s should need a parent''s consent before buying loot boxes. Of the 100 highest grossing iPhone games, not one of those with loot boxes asked, and only 23.5% even said the loot boxes were there. Treat the rules as absent and set the spend limit yourself at the console, the phone and the card.', '{8-10,11-13,13-15,16+}', '{pull_and_design,new_game,gaming}', 'https://royalsocietypublishing.org/rsos/article/12/5/250704/235838'),
('report', 'US Federal Trade Commission, Epic Games order (2023)', 'Fortnite''s maker paid $245 million for a button layout that charged children with one accidental press and let them buy with no parent involved. If a game can take money in one tap, the design is the problem, not your child. Turn off one tap purchase and require a password on every store.', '{8-10,11-13,13-15}', '{pull_and_design,new_game,gaming}', 'https://www.ftc.gov/news-events/news/press-releases/2023/03/ftc-finalizes-order-requiring-fortnite-maker-epic-games-pay-245-million-tricking-users-making'),
('report', 'Gambling Commission, Young People and Gambling 2025', 'In Great Britain, 11 to 13 year olds mostly pay for in game items with a gift card (63%) while 14 to 17 year olds mostly use their own bank account (62%). The gift card is the lever at the younger age: one agreed amount, bought together, and the conversation about what it bought afterwards.', '{11-13,13-15,16+}', '{pull_and_design,new_game,gaming,money}', 'https://www.gamblingcommission.gov.uk/report/young-people-and-gambling-2025-official-statistics/ypg-2025-gambling-activities-and-gaming-gaming'),
('report', 'Common Sense Media, Constant Companion (2023)', 'A teenager''s phone asks for attention a couple of hundred times a day: 203 US 11 to 17 year olds had a median of 237 notifications daily, and 59% used their phones on school nights, usually briefly. Turning off notifications is the single change children say they can feel, so make it the first setting done together, not the parent''s secret (US figures).', '{11-13,13-15,16+}', '{pull_and_design,new_phone,sleep,screen_time}', 'https://www.commonsensemedia.org/research/constant-companion-a-week-in-the-life-of-a-young-persons-smartphone-use'),
('researcher', 'Maza et al, JAMA Pediatrics 2023, and Miller et al, Cortex 2023', 'What the brain science actually shows: 169 young teenagers who checked social media habitually showed brains growing more sensitive to social reward and punishment over three years, while a large scan study of 9 to 12 year olds found no screen effect above its preregistered threshold. Habit is the defensible story. Say "this is very engaging and hard to stop", never "this is a drug"; it is true and it keeps your child listening.', '{8-10,11-13,13-15}', '{pull_and_design,social_media,history}', 'https://www.sciencedirect.com/science/article/pii/S001094522300237X'),

-- The new game: loving it is not a disorder
('association', 'World Health Organization, gaming disorder (ICD 11)', 'Loving a game is not a disorder. The clinical line is three things together, normally for a year: they cannot stop when they try, the game comes before friends, school and sleep, and they carry on despite real harm. If you see all three and life is clearly suffering, ask the GP or self refer to the NHS National Centre for Gaming Disorders, which takes children from 13.', '{8-10,11-13,13-15,16+}', '{new_game,gaming,crisis}', 'https://www.who.int/news-room/questions-and-answers/item/addictive-behaviours-gaming-disorder'),
('researcher', 'Stevens et al, gaming disorder prevalence (ANZJP 2021)', 'Real gaming disorder is rare: the best pooled estimate is about 3 in 100 gamers. So if your child is one of the 97, the plan is habits and structure, not treatment. Watch for loss of control, not hours.', '{8-10,11-13,13-15,16+}', '{new_game,gaming,balanced_use}', 'https://journals.sagepub.com/doi/10.1177/0004867420962851'),
('researcher', 'Coyne et al, six year gaming study (Developmental Psychology 2020)', 'When a child falls in love with a new game, the hours are not the warning sign. Followed for six years from age 15, about one in ten teenagers drifted into rising problem symptoms while 72% never did. Watch for the game crowding out sleep, friends and mood, and for how they behave when it ends, not the clock.', '{11-13,13-15,16+}', '{new_game,gaming,forecast,mood}', 'https://pubmed.ncbi.nlm.nih.gov/32352827/'),
('researcher', 'Przybylski and Weinstein, violent games registered report (2019)', 'The forty year fear that violent games make violent children did not survive the evidence. In a preregistered study of 1,004 British 14 and 15 year olds there was no link between violent game play and aggressive behaviour, and the US Surgeon General admitted in 1982 that his arcade warning had no science behind it. Judge a new game by what it displaces and how they behave when it ends, not by its rating alone.', '{11-13,13-15,16+}', '{new_game,gaming,history}', 'https://royalsocietypublishing.org/doi/10.1098/rsos.171474'),

-- The new phone
('report', 'Ofcom, Children and Parents Media Use and Attitudes 2026', 'The first phone lands with the move to secondary school. UK smartphone ownership jumps from 56% of ten year olds to 83% of eleven year olds, and Ofcom calls starting senior school the tipping point. A third of parents (32%) say they find it hard to control their child''s screen time. Plan the phone in Year 6, together, while it is still a plan rather than a negotiation (UK figures).', '{8-10,11-13}', '{new_phone,forecast,phone,school}', 'https://www.ofcom.org.uk/siteassets/resources/documents/research-and-data/media-literacy-research/children/2026-children-and-parents-report/children-and-parents-media-use-and-attitudes-report-2025-6.pdf'),
('researcher', 'Barzilay et al, Pediatrics 2025 (ABCD smartphone cohort)', 'Expect the first smartphone to show up in sleep first. In 10,588 US children, twelve year olds with a phone had 1.6 times the odds of too little sleep, 1.4 times the odds of obesity and 1.3 times the odds of depression compared with those without, and among children who had no phone at 12, getting one in the following year raised the odds of clinical level problems by 57% and of too little sleep by 50%. Association, not proof, so delay where you can and set the bedtime charging rule before the box is opened (US figures).', '{8-10,11-13,13-15}', '{new_phone,forecast,sleep,mood}', 'https://publications.aap.org/pediatrics/article/157/1/e2025072941/205716/Smartphone-Ownership-Age-of-Smartphone-Acquisition'),
('association', 'Children''s Commissioner for England (December 2025) and the DSIT national consultation (July 2026)', 'Children go quiet when telling costs them the phone. The Children''s Commissioner found many children would not turn to family first when something goes wrong online and urged parents not to simply confiscate the device. In the government''s consultation of 116,211 people, children asked for feature fixes rather than an age wall: explicit images (63%), stranger contact (49%), livestreaming (45%). Say the no confiscation promise out loud before the phone is handed over: if you show me something bad, the phone stays yours.', '{8-10,11-13,13-15,16+}', '{new_phone,disclosure,safety,relationships}', 'https://www.gov.uk/government/consultations/growing-up-in-the-online-world-a-national-consultation/outcome/growing-up-in-the-online-world-government-response-july-2026'),
('researcher', 'Livingstone (LSE 1999) and Borzekowski and Robinson (2005), the bedroom', 'The oldest parenting move in the record is where the screen lives. By 1999, 63% of British 6 to 17 year olds had a television in their bedroom, and American third graders with a bedroom TV scored about 8 points lower in maths and 7 lower in reading while children with a family computer scored higher. Keep the first device in a shared room and let the bedroom stay for sleep.', '{8-10,11-13,13-15}', '{new_phone,history,sleep,routines}', 'https://eprints.lse.ac.uk/21177/1/Young_people_new_media_(LSERO).pdf'),

-- Different children
('researcher', 'Nikkelen et al (2014) and Ra et al (JAMA 2018), screens and ADHD', 'Children with ADHD find screens harder to leave and screens make the restlessness slightly worse, but the link is small (r 0.12 across 45 studies) and runs both ways, and in 2,587 US tenth graders each extra high frequency digital activity raised the odds of new ADHD like symptoms by about a tenth. Do not blame the game for the ADHD. Do build the exits: a visible timer they can see, the same stop cue every day, and a physical activity waiting on the other side.', '{4-7,8-10,11-13,13-15}', '{adhd,temperament,after_school,routines}', 'https://jamanetwork.com/journals/jama/fullarticle/2687861'),
('researcher', 'Ophir et al (JAMA Network Open 2023) and Mazurek and Wenstrup (2013), autism', 'The claim that screens cause autism did not survive a fair test: a 2023 meta analysis found the link not sufficiently supported once publication bias was accounted for. Autistic children do play more than their siblings (boys 2.4 hours a day against 1.6, girls 1.8 against 0.8), often because the game is the predictable, safe place. The useful question is what the screen is doing for them; the fix is a visual schedule that shows when the game starts and ends, not surprise removal.', '{4-7,8-10,11-13,13-15}', '{autism,temperament,after_school,routines}', 'https://link.springer.com/article/10.1007/s10803-012-1659-9'),
('researcher', 'Mougharbel et al, Frontiers in Public Health 2023', 'For an anxious teenager, screens are often the hiding place, and heavy use this year predicts more anxiety and depression symptoms next year: 17,174 Canadian high school pupils showed the link for every type of screen. Watch for the pattern where the phone is the only thing that settles them and everything else is avoided. Keep one offline thing they still do with a person each day, and treat it as protected time.', '{13-15,16+}', '{anxiety,temperament,mood,screen_time}', 'https://www.frontiersin.org/journals/public-health/articles/10.3389/fpubh.2023.1101594/full'),
('researcher', 'Orben, Przybylski, Blakemore and Kievit, Nature Communications 2022', 'There are windows when a child is more sensitive to social media: in 17,409 UK young people, heavier use predicted lower life satisfaction a year later at 11 to 13 for girls and 14 to 15 for boys, and at 19 for both. An arrival into the window is the moment for watchfulness and a closer check in, not for panic (UK figures).', '{11-13,13-15,16+}', '{forecast,temperament,social_media,mood}', 'https://www.nature.com/articles/s41467-022-29296-3'),

-- AI use and readiness
('report', 'Ofcom, Children and Parents Media Use and Attitudes 2026 (AI)', 'Over half of UK 8 to 17 year olds (56%) have used AI, rising to two thirds of 16 to 17s, and 11% have used it as someone to talk to or as a friend. Teenagers feel confident spotting AI content, but a quarter of the confident ones failed when Ofcom tested them. Ask what they use it for before any rule, and teach checking as a habit: who made it, and can two other sources confirm it (UK figures).', '{8-10,11-13,13-15,16+}', '{ai_use,ai_readiness,forecast}', 'https://www.ofcom.org.uk/online-safety/protecting-children/younger-phone-owners-the-rise-of-ai-and-consumption-over-creation-our-latest-look-at-uk-childrens-media-lives'),
('report', 'Pew Research Center, Teens, Social Media and AI Chatbots 2025', 'In the US, 64% of teenagers use an AI chatbot and about three in ten use one every day, mostly ChatGPT, mainly for schoolwork: researching a topic, maths and editing their own writing. A minority use it for casual chat (16%) or emotional support (12%), and that is the part worth a gentle question. Half of parents say their teen uses one; three in ten do not know. Ask directly, and ask which one (US figures).', '{11-13,13-15,16+}', '{ai_use,ai_readiness,forecast,school}', 'https://www.pewresearch.org/internet/2025/12/09/teens-social-media-and-ai-chatbots-2025/'),
('report', 'Common Sense Media, Talk, Trust, and Trade Offs (2025)', 'In the US, 72% of teenagers have tried an AI companion and half use one regularly. A third of users have chosen the AI over a person for a serious conversation, and younger teens trust it more than older ones, yet 80% still put real friendships first. Say plainly at home: it is a tool, not a friend, and here is why (US figures).', '{11-13,13-15,16+}', '{ai_use,ai_readiness,friendships}', 'https://www.commonsensemedia.org/research/talk-trust-and-trade-offs-how-and-why-teens-use-ai-companions'),
('report', 'Common Sense Media, AI Use by Tweens and Teens census 2026', 'AI arrives well before the phone. In the US, 86% of 9 to 17 year olds use or interact with some form of AI and 81% of 9 to 12 year olds already do, a quarter of all of them daily. Among those who have used it to talk about feelings, a quarter say it sometimes understands them better than most people, and daily users are more likely to say they feel lonely. The first AI conversation belongs in Stage 2, not Stage 4 (US figures).', '{8-10,11-13,13-15,16+}', '{ai_use,ai_readiness,forecast}', 'https://www.commonsensemedia.org/sites/default/files/research/report/2026-ai-use-by-tweens-and-teens-1.pdf'),
('association', 'Internet Matters, Me, Myself and AI (2025)', 'The child most likely to lean on a chatbot as a friend is the child with SEND or a health condition. Among 1,000 UK 9 to 17 year olds, 64% use chatbots, 71% of vulnerable children against 62% of the rest, and 35% of users say it feels like talking to a friend, rising to half among vulnerable children. If your child says the chatbot is their friend, that is a prompt to increase real contact, not a crisis. Ask who else they talk to before asking them to stop.', '{8-10,11-13,13-15,16+}', '{ai_use,temperament,friendships,anxiety}', 'https://www.internetmatters.org/hub/research/me-myself-and-ai-chatbot-research/'),
('researcher', 'Bastani et al, PNAS 2025 (AI in the maths classroom)', 'In a randomised trial with nearly 1,000 high school pupils, a chatbot that gave answers lifted practice scores and then left pupils 17% worse on the unassisted exam; a version that only gave hints lifted practice by 127% and largely avoided the harm. Set the rule at home: AI may explain and quiz, it may not answer. Ask it something together and check what it says against a book or a person.', '{11-13,13-15,16+}', '{ai_readiness,ai_use,school}', 'https://www.pnas.org/doi/10.1073/pnas.2422633122'),
('report', 'Character.AI (October 2025), OpenAI (September 2025) and Common Sense AI toys assessment (January 2026)', 'The AI products children meet change their rules only under pressure. Character.AI removed open ended chat for under 18s in November 2025, ChatGPT added parental controls with quiet hours and distress alerts in September 2025, and Common Sense rated AI toys unsafe for children five and under after 27% of tested outputs were inappropriate. Assume a product is unsafe for a child until its child mode has been switched on by you.', '{4-7,8-10,11-13,13-15,16+}', '{ai_readiness,ai_use,safety}', 'https://openai.com/index/introducing-parental-controls/'),

-- Forecast: the ban and what it moves
('report', 'UK Government, under 16 social media ban (15 June 2026) and eSafety Australia (2026)', 'From spring 2027 the UK ban is set to cover Snapchat, TikTok, YouTube, Instagram, Facebook and X, with messaging apps like WhatsApp outside it and games not named. Australia''s platforms restricted 4.7 million under 16 accounts within a fortnight of its ban, and four months later the regulator found more than eight in ten 10 to 15 year olds still using social media. Expect the pull to move to games, group chats and AI, not to vanish, and plan for the relocation rather than the removal.', '{11-13,13-15,16+}', '{forecast,social_media,ai_use,gaming}', 'https://www.gov.uk/government/news/social-media-to-be-banned-for-under-16s-in-landmark-government-move-to-givekids-their-childhood-back'),
('association', 'Girlguiding poll of 10 to 16 year olds (2025)', 'In a poll of nearly 2,000 UK 10 to 16 year olds, 62% said a social media ban would feel like punishment and only 15% felt it would make them safer; 69% would rather know a platform is safe. A child who hears the ban framed as protection from the platforms, not from themselves, is far more likely to keep talking to you after it lands (UK figures).', '{8-10,11-13,13-15,16+}', '{forecast,social_media,relationships}', 'https://www.girlguiding.org.uk/about-us/press-releases/social-media-companies-need-to-do-more-to-protect-young-people/'),
('report', 'Pew Research Center, Teens, Social Media and Mental Health (2025)', 'Teenagers are already cutting down by themselves: 44% of US teens say they have cut back on social media and the same share on their phone, and they think it harms other people (48%) far more than themselves (14%). Treat a teen who says "I want to use it less" as an ally with a plan to protect, not a problem to police. "For your own good" misses, because they do not believe it is hurting them (US figures).', '{13-15,16+}', '{forecast,balanced_use,social_media,mood}', 'https://www.pewresearch.org/internet/2025/04/22/teens-social-media-and-mental-health/'),

-- History: what survived every panic
('researcher', 'Himmelweit, Oppenheim and Vince, Television and the Child (1958)', 'The first big British television study followed over 4,000 children in five cities, including Norwich before and after its transmitter switched on, and asked what television displaced rather than how long it was on. That is still the right question. When a new screen arrives, look at what it is pushing out of the day: if it is replacing sleep, play or people, act; if it is replacing another screen, relax.', '{4-7,8-10,11-13,13-15}', '{history,balanced_use,screen_time}', 'https://www.worldradiohistory.com/BOOKSHELF-ARH/Commentary/Television-and-the-Child-Himmelweit-et-al-1958.pdf'),
('researcher', 'Reiser, Tessmer and Phelps (1984) and Anderson et al, the recontact study (2001)', 'Sesame Street proved that what is on the screen, plus a grown up saying something about it, beats a time limit. Three and four year olds whose adult asked them to name the letters and numbers remembered more three days later, and 570 adolescents followed from preschool did better if their early viewing was educational, whatever the hours, more consistently for boys. Choosing what a four year old watches is a decision with a ten year shadow, so spend your energy there rather than on the timer.', '{4-7,8-10}', '{history,device_as_helper,balanced_use}', 'https://pubmed.ncbi.nlm.nih.gov/11326591/'),
('researcher', 'Orben, the Sisyphean cycle of technology panics (2020)', 'Every generation has panicked about the newest medium, from radio crime to comics to television to games, and the research restarts from scratch each time. Knowing this helps you hold steady: take the specific, well evidenced risks seriously (sleep, calming with screens, a phone very early, the lonely child and the chatbot) and let the general dread go. The parenting move that survived every panic was a shared room, a routine, and a grown up beside the child asking what they are watching.', '{4-7,8-10,11-13,13-15,16+}', '{history,parent_stress,balanced_use}', 'https://journals.sagepub.com/doi/10.1177/1745691620919372'),
('association', 'Byron Review, Safer Children in a Digital World (2008)', 'The UK''s own review of children and technology landed on a swimming pool: "we have gates, put up signs, have lifeguards and shallow ends, but we also teach children how to swim." The watershed, PEGI ratings and the Online Safety Act codes are the gates; they lower the odds of the worst and none of them changes what a parent has to do at 8pm. The job tonight is one lesson in swimming, not a taller gate.', '{4-7,8-10,11-13,13-15}', '{history,safety,parent_stress}', 'https://dera.ioe.ac.uk/id/eprint/7332/7/Final%20Report%20Bookmarked_Redacted.pdf');
