-- Guided Childhood — Migration 262
-- PCAST and the US direction of travel on children and AI.
--
-- Justin, 6 September 2026, clearing up "ocas" from his research brief: "It's
-- the President's Council of Advisors on Science and Technology (PCAST)." He
-- wants the US picture on AI and technology in the bank so DiGi can say what
-- is coming for a child who reaches sixteen in the UK.
--
-- What the record actually holds, checked by exact phrase search against the
-- primary pages (the sandbox blocks whitehouse.gov, federalregister.gov and
-- ed.gov to fetch): PCAST was reconstituted on 23 January 2025 and its members
-- named on 25 March 2026; its only AI report so far is the previous council's
-- Supercharging Research (29 April 2024), about AI for science, not children.
-- The federal moves that touch children come from three places PCAST's co
-- chair also leads or advises: Executive Order 14277 on AI education for
-- American youth (23 April 2025), the Department of Education's five
-- principles for AI in schools (22 July 2025), and the OSTP report Science: A
-- New Golden Age (21 July 2026). Each row says which, and says US.

insert into public.expert_knowledge (source_type, source_name, finding, age_bands, topics, url) values
('report', 'PCAST, the President''s Council of Advisors on Science and Technology', 'PCAST is the US President''s science advisory council, reconstituted on 23 January 2025 and co chaired by Michael Kratsios, the White House science director, and David Sacks, the AI adviser; its members named on 25 March 2026 include the heads of Meta, Nvidia, Oracle and AMD and a Google co founder. Its only AI report so far, Supercharging Research (29 April 2024), is about AI for science and says AI should support, not replace, human scientists. It has not yet published on children and AI. When it does, expect the line to be the same one the US is already taking with schools: AI as a skill to teach from primary age, with a person beside the child (US).', '{8-10,11-13,13-15,16+}', '{ai_readiness,forecast,history}', 'https://bidenwhitehouse.archives.gov/wp-content/uploads/2024/04/AI-Report_Letter-ExSumm-29APRIL2024_SEND.pdf'),
('report', 'US Executive Order 14277, Advancing Artificial Intelligence Education for American Youth (23 April 2025)', 'The US has made AI literacy a stated national policy for children: "to promote AI literacy and proficiency among Americans by promoting the appropriate integration of AI into education, providing comprehensive AI training for educators, and fostering early exposure to AI concepts and technology". A White House task force chaired by the science director (who also co chairs PCAST) is building K to 12 resources on "foundational AI literacy and critical thinking skills". The forecast for a UK child: the children they will compete with at 18 are being taught to build with AI from primary age, so the AI together habit belongs in Stage 2, not Stage 4 (US).', '{4-7,8-10,11-13,13-15,16+}', '{ai_readiness,forecast,school}', 'https://www.presidency.ucsb.edu/documents/executive-order-14277-advancing-artificial-intelligence-education-for-american-youth'),
('report', 'The Presidential AI Challenge (2026)', 'The first Presidential AI Challenge ran across all 50 US states in the 2025 to 2026 school year: children from elementary age upwards submitted projects that use or build an AI tool to solve a problem in their community, with state champions named on 16 March 2026 and a national final in June. The message to a parent is that AI is being treated as something a seven year old can make with, not only something to be protected from. Ask your child what they could build with it, not only whether they cheated with it (US).', '{4-7,8-10,11-13,13-15,16+}', '{ai_readiness,forecast,school}', 'https://www.ai.gov/initiatives/presidential-challenge'),
('report', 'US Department of Education, Dear Colleague letter on artificial intelligence (22 July 2025)', 'The US Department of Education set five conditions for AI in schools and, for the first time, let federal money pay for it: AI use must be educator led, ethical, accessible, transparent, and protective of student data, with parents named among the people schools must involve. Those five are a good checklist for any AI tool a child uses at home too: is a grown up leading it, is it honest about what it is, can every child use it, do you know what it does, and where does the child''s data go (US).', '{4-7,8-10,11-13,13-15,16+}', '{ai_readiness,ai_use,school,safety}', 'https://www.ed.gov/media/document/opepd-ai-dear-colleague-letter-7222025-110427.pdf'),
('report', 'Office of Science and Technology Policy, Science: A New Golden Age (21 July 2026)', 'The White House science director''s July 2026 blueprint puts AI at the centre of American science and asks schools to expand K to 12 STEM enrichment by "connecting students with expert mentors and similarly capable peers" and giving "sustained exposure to real world technical environments". Its line that technology lives "in the tacit knowledge passed from mentor to mentee" is the oldest finding in the bank in new words: a child learns a new tool best with a person beside them. For a family, the mentor is you, and the first mentoring is asking the AI something together (US).', '{8-10,11-13,13-15,16+}', '{ai_readiness,forecast,history}', 'https://www.whitehouse.gov/wp-content/uploads/2026/07/Science-A-New-Golden-Age.pdf');
