-- 268_lesson_contract_oak_and_common_sense.sql
-- The lesson contract, as data, on all 21 school modules.
--
-- Plan: plans/2026-09-07-oak-as-the-basis-plan.md, Phase 1.
-- Sources: research/2026-09-07-oak-and-common-sense-source-mining.md, the read
-- of the live Oak lesson page (KS1 Computing, Painting using computers) and the
-- Common Sense digital literacy curriculum, 7 September 2026.
--
-- Adds six keys to schools.school_lessons.teacher_notes on every module:
--   essential_question   one question in the pupil's own words (Common Sense).
--   cycles               [{verb, title, outcome, minutes}] (Common Sense's
--                        pattern: a verb, a title and a runtime per cycle).
--   prior_knowledge      three statements, what a pupil needs before this.
--   key_learning_points  four or five statements, the knowledge taught (Oak).
--   teacher_tip          one line, the thing that goes wrong if skipped (Oak).
--   equipment            one line, what the room needs, honestly (Oak).
-- And fills the one missing keywords array, on ks3-12.
--
-- Nothing here is invented from nothing. Cycle titles come from the decks' own
-- teach headings, cycle minutes come from the existing timing string and sum to
-- the teaching total it already states, and cycle outcomes come from the
-- existing i_can ladder. Prior knowledge points at the preceding module in the
-- spiral by module_id. No statistic is claimed anywhere, so nothing in this
-- migration needs a citation it cannot survive.
--
-- Non destructive: teacher_notes is merged with ||, so no existing key is
-- touched. Idempotent: re running replaces the same six keys with the same
-- values. Backed up first.

begin;

-- Backup, per the migration rules. RLS on, no policies, so only the service
-- role reaches it.
create table if not exists schools.school_lessons_backup_268 as
  select id, module_id, teacher_notes, now() as backed_up_at
  from schools.school_lessons;

alter table schools.school_lessons_backup_268 enable row level security;

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "How do I know if something on a screen is really real?", "cycles": [{"verb": "Look", "title": "Real and made up", "outcome": "I can point to something real and something made up.", "minutes": 6}, {"verb": "Ask", "title": "Stop, look, ask a grown up", "outcome": "I can stop and ask a grown up if something on a screen is real.", "minutes": 4}], "prior_knowledge": ["A child can name a screen they have used at home, a telly, a tablet or a phone.", "A child can join in with a simple sorting activity, this pile and that pile.", "A child knows who their trusted grown ups are at school and at home."], "key_learning_points": ["Some things on a screen are real and some are made up.", "Made up things are lovely, they are just not real.", "You cannot always tell which is which by looking.", "When you are not sure, you stop and ask a grown up."], "teacher_tip": "Do the sorting game with real objects and picture cards before anything appears on a screen. A child who has sorted with their hands will sort on a screen.", "equipment": "Nothing beyond the board. The sorting cards are in the print room, so the lesson runs with no devices in the room."}'::jsonb
  where module_id = 'eyfs-01-screens-kindness';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "Why do I feel wiggly or grumpy when the screen goes off?", "cycles": [{"verb": "Notice", "title": "Screens give our bodies feelings", "outcome": "I can notice how my body feels after screen time.", "minutes": 7}, {"verb": "Name", "title": "Pebble''s three steps", "outcome": "I can name the feeling and tell my grown up.", "minutes": 6}], "prior_knowledge": ["A child can name a few feelings: happy, sad, cross, tired.", "A child knows a grown up can help when something feels wrong, from eyfs-01.", "A child can point to where in their body a feeling sits, tummy, chest or head."], "key_learning_points": ["Screens leave a feeling in your body, and the feeling is real.", "Wiggly and grumpy are two of the feelings screens can leave behind.", "Feelings pass more quickly once you have named them.", "Pebble''s three steps are feel it, name it, tell a grown up.", "Telling a grown up is brave, not naughty."], "teacher_tip": "Do the body check yourself, out loud, first. Children copy the naming, and a class that has heard an adult say I feel a bit wiggly will say it back.", "equipment": "Nothing beyond the board. Floor space for the body check if you have it."}'::jsonb
  where module_id = 'ks1-02-kind-screens-calm-bodies';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "How can a picture look like a photo when the thing never happened?", "cycles": [{"verb": "Look", "title": "Three kinds of pictures", "outcome": "I can spot that a picture might be pretend or made by a computer.", "minutes": 7}, {"verb": "Ask", "title": "The detective question", "outcome": "I can stop and ask real, pretend, or computer made before I believe it.", "minutes": 7}], "prior_knowledge": ["A child can sort real from made up, from eyfs-01.", "A child knows to stop and ask a grown up when they are not sure.", "A child can describe what is happening in a picture in a sentence."], "key_learning_points": ["Pictures come in three kinds: real, pretend, and made by a computer.", "A computer made picture can look exactly like a photo.", "Pretend is playing, not lying. A cartoon is not a trick.", "The detective question is real, pretend, or computer made?", "A picture that makes you say WOW is the one to ask the question about."], "teacher_tip": "Ask the detective question about a picture you already know is real, before you show one that is not. Children who only meet the question next to a fake learn to distrust everything.", "equipment": "Nothing beyond the board. The paper detective practice is in the print room if the room has no screen."}'::jsonb
  where module_id = 'ks1-03-real-pretend-computer';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "Why is it so hard to stop, even when I meant to?", "cycles": [{"verb": "Notice", "title": "Routines beat willpower", "outcome": "I can spot the difference between a routine that works and a trap.", "minutes": 9}, {"verb": "Practise", "title": "The cool down lap", "outcome": "I can run my own cool down lap: warn, finish, swap.", "minutes": 10}, {"verb": "Place", "title": "Where screens sleep matters", "outcome": "I can explain why where a screen sleeps changes how well I sleep.", "minutes": 9}], "prior_knowledge": ["A pupil can describe their own evening in order, from getting home to lights out.", "A pupil can name a feeling a screen leaves behind, from ks1-02.", "A pupil understands that a rule and a habit are different things."], "key_learning_points": ["Willpower runs out, especially when you are tired. A routine does not.", "A routine is decided once, in a calm moment, and followed after that.", "The cool down lap is warn, finish, swap.", "The warning is what makes stopping possible, because it lets the brain finish.", "Where a screen sleeps decides whether it interrupts your sleep."], "teacher_tip": "Let pupils design a routine for a character before their own. A routine written for someone else gets written honestly.", "equipment": "Nothing beyond the board. The routine planner is in the print room."}'::jsonb
  where module_id = 'ks2-04-screen-routines';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "If the game is free, how is it making money out of me?", "cycles": [{"verb": "Hold", "title": "Brilliant AND designed. Both true.", "outcome": "I can hold both ideas at once: a game can be brilliant and built to keep me playing.", "minutes": 9}, {"verb": "Follow", "title": "Free games that cost, and how the price hides", "outcome": "I can spot when a game is rushing me, hiding a price or selling a mystery.", "minutes": 12}, {"verb": "Check", "title": "The spend spotters", "outcome": "I can stop before I spend and run the three spend spotter questions.", "minutes": 7}], "prior_knowledge": ["A pupil can name a game they play and say what they enjoy about it.", "A pupil can explain that a routine beats willpower, from ks2-04.", "A pupil understands that real money and game money are not the same thing."], "key_learning_points": ["A game can be brilliant and designed to keep you playing. Both are true at once.", "Game currency hides the real price, because gems do not feel like pounds.", "A loot box sells a chance, not a thing.", "A countdown clock is there to stop you thinking, not to help you.", "The spend spotters ask: what is the real price, what am I actually getting, and what is the rush?"], "teacher_tip": "Name a game you enjoy yourself before you take the design apart. A lesson that opens by criticising what pupils love will lose the room in the first minute.", "equipment": "Nothing beyond the board. No game is played or shown in the lesson."}'::jsonb
  where module_id = 'ks2-05-gaming-time-spend';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "Why does my feed always seem to know what I want next?", "cycles": [{"verb": "Learn", "title": "Algorithms are recipes", "outcome": "I can say what an algorithm is in my own words.", "minutes": 6}, {"verb": "Trace", "title": "The feed loop", "outcome": "I can describe the feed loop: you watch, it learns, it serves more.", "minutes": 14}, {"verb": "Catch", "title": "The bottomless bowl", "outcome": "I can catch the loop working on me when a video starts on its own.", "minutes": 8}], "prior_knowledge": ["A pupil can follow and give a set of instructions in order.", "A pupil can name something a game does to keep them playing, from ks2-05.", "A pupil has seen a feed, on their own device or someone else''s."], "key_learning_points": ["An algorithm is a list of steps followed in order. A recipe for machines.", "While you watch the feed, the feed watches you.", "The loop is: you watch, it learns, it serves more of the same.", "Your attention is what the app collects, and it is the thing being sold.", "The feed never ends on purpose, because an ending is a place to stop."], "teacher_tip": "Run the jam sandwich algorithm properly before the feed appears. Pupils who have argued about whether you open the jar first understand order, and order is the whole idea.", "equipment": "Nothing beyond the board. The feed examples are built into the deck, so no live app is opened in the classroom."}'::jsonb
  where module_id = 'ks2-06-how-algorithms-work';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "Who else can see this, and for how long?", "cycles": [{"verb": "Decide", "title": "You are the editor of your own story", "outcome": "I can spot when something is risky to share.", "minutes": 7}, {"verb": "Follow", "title": "The journey of one shared photo", "outcome": "I can explain how one share can follow future me around.", "minutes": 9}, {"verb": "Check", "title": "The share test", "outcome": "I can run the share test before I share anything.", "minutes": 12}], "prior_knowledge": ["A pupil can explain that a feed collects data about them, from ks2-06.", "A pupil can name information that belongs to their family, such as an address.", "A pupil understands that a message can be passed on by the person who receives it."], "key_learning_points": ["You are the editor of your own story, and every share is an editing decision.", "Private information is yours to give, and most people asking do not need it.", "Anyone can screenshot anything you send, and you will never know.", "Your digital footprint grows whether you look after it or not.", "The share test is run before you share, never after."], "teacher_tip": "Keep every example invented. A pupil who names a real classmate''s post turns a privacy lesson into the thing it is warning about.", "equipment": "Nothing beyond the board."}'::jsonb
  where module_id = 'ks2-07-privacy-reputation';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "What do I actually do when I see someone being torn apart online?", "cycles": [{"verb": "Name", "title": "Unkind or bullying? There is a difference", "outcome": "I can recognise unkindness online when I see it.", "minutes": 8}, {"verb": "Understand", "title": "Why pile ons grow", "outcome": "I can explain why a pile on grows and what a bystander adds to it.", "minutes": 8}, {"verb": "Move", "title": "The three moves", "outcome": "I can make the three moves: do not pile on, save the evidence, tell someone who can help.", "minutes": 12}], "prior_knowledge": ["A pupil can explain what a screenshot is and that anyone can take one, from ks2-07.", "A pupil can name a trusted adult at school and at home.", "A pupil can tell the difference between a one off unkind comment and a pattern."], "key_learning_points": ["Bullying is repeated, targeted and on purpose. All three together.", "A pile on grows because joining in is easy and costs the joiner nothing.", "A bystander watches. An upstander makes one safe move.", "The three moves are: do not pile on, save the evidence, tell someone who can help.", "Report and block are safety tools, not tantrums, and telling is strength, not snitching."], "teacher_tip": "Rehearse the exact words for telling. Pupils rarely fail on knowing they should tell, they fail on not having a sentence ready.", "equipment": "Nothing beyond the board."}'::jsonb
  where module_id = 'ks2-08-kind-safe-online';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "If I found it online, why is it not mine to use?", "cycles": [{"verb": "Own", "title": "You are a maker, and makers own their work", "outcome": "I can tell the difference between my work and someone else''s work.", "minutes": 9}, {"verb": "Use", "title": "Make it, credit it, ask first", "outcome": "I can credit the maker or ask first before I use their work.", "minutes": 10}, {"verb": "Question", "title": "The AI wrinkle", "outcome": "I can explain where an AI picture really comes from.", "minutes": 9}], "prior_knowledge": ["A pupil has made something they are proud of and can say why it is theirs.", "A pupil can explain that a picture might be made by a computer, from ks1-03.", "A pupil understands what asking permission means in everyday life."], "key_learning_points": ["You own your work the moment you make it. So does everyone else.", "Copyright is the rule that says the maker owns their work.", "Crediting names the maker. Permission asks first and waits for a yes.", "An AI picture is built from work made by people who were not asked.", "Make it, credit it, ask first."], "teacher_tip": "Start with a piece of their own work being taken, not someone else''s. Ownership is felt before it is understood.", "equipment": "Nothing beyond the board."}'::jsonb
  where module_id = 'ks2-09-copyright-ownership';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "Does this app actually leave me feeling better, or do I just keep opening it?", "cycles": [{"verb": "Weigh", "title": "What the research actually says", "outcome": "I can describe what the evidence says without overstating it.", "minutes": 7}, {"verb": "Sort", "title": "Connecting or comparing", "outcome": "I can notice what an app leaves behind: better, worse or nothing.", "minutes": 6}, {"verb": "Audit", "title": "The mood audit", "outcome": "I can run the mood audit on my own habits for a week and read the pattern.", "minutes": 15}], "prior_knowledge": ["A pupil can describe the feed loop, from ks2-06.", "A pupil can name their own most used apps honestly.", "A pupil understands that a headline and a study are not the same thing."], "key_learning_points": ["The evidence is quieter and more mixed than the headlines about it.", "What you do on an app matters more than how long you spend on it.", "Connecting tends to read better. Comparing tends to read worse.", "Nothing is the sneaky verdict: time that left no trace is still time spent.", "An audit only works with honest answers, not the answers that sound good."], "teacher_tip": "Say out loud that no number from this lesson is collected or marked. Pupils give honest audit answers only once they believe nobody is reading them.", "equipment": "Nothing beyond the board. The mood audit is a paper sheet from the print room and stays with the pupil."}'::jsonb
  where module_id = 'ks3-10-mood-and-screens';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "What am I actually giving up when I get around the rule?", "cycles": [{"verb": "See", "title": "How the machine works", "outcome": "I can name the protection hiding behind a rule.", "minutes": 8}, {"verb": "Trade", "title": "Workaround culture", "outcome": "I can name what a workaround skips before I decide anything.", "minutes": 13}, {"verb": "Judge", "title": "Group chats and judgement", "outcome": "I can explain why a group chat with strangers in it changes the risk.", "minutes": 7}], "prior_knowledge": ["A pupil can explain how a feed learns from what they watch, from ks2-06.", "A pupil knows that platforms have minimum ages and can name one.", "A pupil can describe a group chat they have been in, without naming anyone."], "key_learning_points": ["An age setting switches on protections, it does not only unlock features.", "A workaround is a trade, never a free win.", "A false age tells the machine to treat you as an adult, and it will.", "Moderation is the system that finds harmful content. A workaround steps outside it.", "A group chat with strangers in it is a different room from a group chat with friends."], "teacher_tip": "Never ask who has a workaround. Ask what a workaround costs. The first question gets silence or bravado, the second gets thinking.", "equipment": "Nothing beyond the board. No platform is opened and no workaround is demonstrated."}'::jsonb
  where module_id = 'ks3-11-social-workarounds';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "How do I know whether to believe this before I pass it on?", "cycles": [{"verb": "Notice", "title": "Content can be manufactured", "outcome": "I can spot the signs that something might be fake or engineered.", "minutes": 10}, {"verb": "Check", "title": "The three checks", "outcome": "I can run the three checks and give my verdict: believe, pause or do not share.", "minutes": 11}, {"verb": "Trace", "title": "How a fake travels", "outcome": "I can explain why a fake spreads faster than the correction.", "minutes": 8}], "prior_knowledge": ["A pupil can explain that a picture can be made by a computer, from ks1-03 and ks2-09.", "A pupil can describe how a feed decides what to show them, from ks2-06.", "A pupil has shared or received something forwarded on from someone else."], "key_learning_points": ["Content can be manufactured: images, audio and video, not only text.", "Looking real is no longer evidence that something is real.", "The three checks are: who made it, what is the source, and what does it want from me?", "Pause is a verdict, not a failure to reach one.", "A fake travels further than its correction, so the decision that matters is made before you share."], "teacher_tip": "Run one check on something true before you run three on something false. A class taught only to debunk learns to doubt everything, which is the outcome the fakes want.", "equipment": "Nothing beyond the board. Every example in the deck is invented, so no real post, account or person is shown.", "keywords": [{"word": "misinformation", "definition": "False information passed on by someone who believes it is true. No intent to deceive, and it still does the damage."}, {"word": "disinformation", "definition": "False information spread on purpose by someone who knows it is false. The lie is the plan."}, {"word": "deepfake", "definition": "Video or audio generated by AI so that a real person appears to say or do something they never did."}, {"word": "verdict", "definition": "The decision you reach after checking: believe, pause, or do not share. Pause is a real verdict, not a dodge."}]}'::jsonb
  where module_id = 'ks3-12-misinfo-deepfakes';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "Why would a scammer bother with me?", "cycles": [{"verb": "Spot", "title": "Phishing: the fake that fishes", "outcome": "I can spot a scam''s three tells: it rushes, it asks for something odd, it is too good to be true.", "minutes": 10}, {"verb": "Value", "title": "Why your gaming account is worth stealing", "outcome": "I can explain why my accounts are worth money to someone else.", "minutes": 8}, {"verb": "Refuse", "title": "Anatomy of an account theft", "outcome": "I can stop, check and refuse when a message rushes me.", "minutes": 10}], "prior_knowledge": ["A pupil can explain that a message can be faked, from ks3-12.", "A pupil has an account of their own, in a game or an app.", "A pupil understands that urgency changes how carefully people think."], "key_learning_points": ["The three tells are: it rushes you, it asks for something odd, it is too good to be true.", "Phishing dresses a fake up as something you already trust.", "A gaming account is worth money, which is why it is a target.", "Scam scripts work on clever people, because they attack the moment, not the intelligence.", "Stop, check, refuse. Checking through a different route is what breaks the script."], "teacher_tip": "Make it explicit that being scammed says nothing about intelligence. A pupil who believes only fools fall for it will never tell you when it happens to them.", "equipment": "Nothing beyond the board."}'::jsonb
  where module_id = 'ks3-13-scams-fraud-money';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "Why do I feel worse about myself after scrolling?", "cycles": [{"verb": "See", "title": "Every polished image is a set of choices", "outcome": "I can spot when an image has been edited to sell a feeling.", "minutes": 6}, {"verb": "Follow", "title": "The economics of insecurity", "outcome": "I can explain who profits when we feel worse about ourselves.", "minutes": 9}, {"verb": "Check", "title": "The image check", "outcome": "I can run the image check when a post makes me feel worse about how I look.", "minutes": 13}], "prior_knowledge": ["A pupil can explain that an image can be altered or generated, from ks3-12.", "A pupil can name what an app collects about them, from ks2-06.", "A pupil can describe a feeling an app left them with, from ks3-10."], "key_learning_points": ["Every polished image is a set of choices: angle, lighting, editing and selection.", "Retouching is usually invisible, which is what makes the comparison unfair.", "Insecure people scroll longer and buy more, so insecurity has a market value.", "You are comparing your ordinary day with someone else''s chosen highlight.", "The image check is run on the feeling, not on the picture."], "teacher_tip": "Never use a real pupil, a real classmate or a named public figure as the example. Every image in this lesson is invented and it needs to stay that way when the discussion opens up.", "equipment": "Nothing beyond the board."}'::jsonb
  where module_id = 'ks3-14-bodies-image-pressure';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "Who decided I would want this, and what do they get if I do?", "cycles": [{"verb": "Spot", "title": "Dark patterns", "outcome": "I can notice the pull before I act on it.", "minutes": 9}, {"verb": "Name", "title": "Engineered outrage", "outcome": "I can name the technique being used on me: urgency, outrage, flattery or FOMO.", "minutes": 7}, {"verb": "Follow", "title": "Influencers, and follow the money", "outcome": "I can explain where the money goes when the technique works.", "minutes": 12}], "prior_knowledge": ["A pupil can explain how a feed learns and serves, from ks2-06.", "A pupil can name a scam''s tells, from ks3-13.", "A pupil follows at least one creator and can describe why."], "key_learning_points": ["You are the target market, and the design assumes it.", "A dark pattern pushes you into a choice you did not mean to make.", "Rage is a business model, because furious people comment, share and stay.", "Parasocial trust sells: you feel you know them, they do not know you exist.", "UK rules say a paid post must be labelled. Hidden ones bank on your trust."], "teacher_tip": "Have pupils design the manipulation before they spot it. A class that has written the fake countdown never falls for the real one in the same way.", "equipment": "Nothing beyond the board. Dark patterns are shown as invented mock ups, never live sites."}'::jsonb
  where module_id = 'ks4-15-manipulation-persuasion';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "What does the law actually say, and what are my options if it has already happened?", "cycles": [{"verb": "Define", "title": "Consent", "outcome": "I can say what real consent means and name its four properties.", "minutes": 6}, {"verb": "Know", "title": "The law", "outcome": "I can say what the law actually covers.", "minutes": 7}, {"verb": "Resist", "title": "Pressure", "outcome": "I can explain why pressure is not consent.", "minutes": 9}, {"verb": "Act", "title": "Options", "outcome": "I can tell a friend their options, including Report Remove, without judgement.", "minutes": 6}], "prior_knowledge": ["A pupil can explain that a screenshot can be taken of anything, from ks2-07.", "A pupil can name a trusted adult and one reporting route.", "A pupil understands that a yes given under pressure is not a free yes."], "key_learning_points": ["Real consent is free, specific, ongoing, and can be taken back.", "Coercion produces a yes that is not consent.", "In UK law an indecent image is any sexual image of a person under 18.", "Everyone is not sending them. The belief that they are is itself the pressure.", "Report Remove is free, confidential, and it works."], "teacher_tip": "Give the DSL notice before this lesson runs and read the DSL note first. This is the module most likely to produce a disclosure, and it should.", "equipment": "Nothing beyond the board. Have the DSL note and the reporting routes printed and in the room before you start."}'::jsonb
  where module_id = 'ks4-16-consent-images-law';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "If this happened to me tonight, what would I actually do?", "cycles": [{"verb": "Recognise", "title": "What sextortion is, and how it starts", "outcome": "I can recognise how sextortion starts and the scripts it uses.", "minutes": 14}, {"verb": "Understand", "title": "Why paying never makes it stop", "outcome": "I can explain why paying never ends it.", "minutes": 4}, {"verb": "Act", "title": "The three lifelines", "outcome": "I can use the three lifelines: do not pay, do not keep it secret, report it.", "minutes": 10}], "prior_knowledge": ["A pupil can explain what consent is and what the law covers, from ks4-16.", "A pupil can name a scam''s tells and how urgency works, from ks3-13.", "A pupil knows at least one adult they would tell something difficult."], "key_learning_points": ["Sextortion is blackmail, and the crime belongs to the blackmailer.", "It starts with an ordinary friendly conversation, which is what makes it work.", "Paying funds the next demand. It never ends it.", "The three lifelines are: do not pay, do not keep it secret, report it.", "Report Remove and CEOP exist for exactly this and are used every day."], "teacher_tip": "Say not your fault and not in trouble in the first five minutes, not only at the end. A pupil in this situation stops listening the moment they think they are about to be blamed.", "equipment": "Nothing beyond the board. Have the DSL note, Report Remove and CEOP routes printed and in the room before you start."}'::jsonb
  where module_id = 'ks4-17-sextortion';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "How does someone end up believing something they would have rejected a year ago?", "cycles": [{"verb": "Trace", "title": "Nobody starts at the extreme", "outcome": "I can describe how a pipeline moves someone gradually.", "minutes": 9}, {"verb": "Recognise", "title": "Belief grooming runs the grooming playbook", "outcome": "I can recognise when content is grooming my beliefs.", "minutes": 11}, {"verb": "Check", "title": "The pipeline check", "outcome": "I can run the pipeline check when content makes me angry.", "minutes": 9}], "prior_knowledge": ["A pupil can name persuasion techniques including rage bait, from ks4-15.", "A pupil can explain that an algorithm optimises for attention, from ks2-06.", "A pupil understands what grooming means in a safeguarding sense."], "key_learning_points": ["Nobody starts at the extreme. The movement is gradual and that is the design.", "A pipeline starts with content that is reasonable, or funny, or true.", "Belief grooming uses the same playbook as any other grooming: attention, belonging, then isolation.", "Misogyny is the most common on ramp, and RSHE 2025 names it.", "Anger keeps you watching, and someone is paid for that."], "teacher_tip": "Do not name real accounts or personalities. Naming them recruits for them, and the mechanism is the lesson, not the man.", "equipment": "Nothing beyond the board. No real account, channel or personality is shown or named."}'::jsonb
  where module_id = 'ks4-18-radicalisation-misogyny';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "The day full access arrives, what is my first week actually going to look like?", "cycles": [{"verb": "Locate", "title": "The world you are standing in", "outcome": "I can name what will be waiting for me when full access arrives.", "minutes": 8}, {"verb": "Understand", "title": "The cliff edge", "outcome": "I can explain why a change that arrives all at once is harder than one that arrives gradually.", "minutes": 10}, {"verb": "Plan", "title": "The arrival plan", "outcome": "I can write my arrival plan: my defaults, my first week audit, my exit rule.", "minutes": 13}], "prior_knowledge": ["A pupil can explain what a workaround costs, from ks3-11.", "A pupil can run a mood audit and read the pattern, from ks3-10.", "A pupil can name the techniques a platform uses on them, from ks4-15."], "key_learning_points": ["At 16 access goes from zero to full, and that is a cliff edge, not a ramp.", "A fresh account learns fastest, so the first week decides what the feed becomes.", "Whoever chooses the defaults quietly runs the experience, so choose them yourself.", "Habits beat rules, because a habit is already running when nobody is enforcing anything.", "An exit rule is written before you need it, not during."], "teacher_tip": "Stay ban neutral. Whatever the law does, the plan is the lesson, and a class that argues about the law for twenty minutes leaves without one.", "equipment": "Nothing beyond the board. The arrival plan is a paper sheet from the print room and stays with the pupil."}'::jsonb
  where module_id = 'ks4-19-readiness-at-16';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "If everyone has the same AI, what makes my work worth more than theirs?", "cycles": [{"verb": "Brief", "title": "Using is not mastering", "outcome": "I can use an AI tool like a professional, with a clear brief.", "minutes": 14}, {"verb": "Check", "title": "Use it, check it, own it", "outcome": "I can check AI output like an editor and defend where I checked its work.", "minutes": 6}, {"verb": "Trade", "title": "Free tools, and what they cost", "outcome": "I can explain the data trade behind a free tool and my rights inside it.", "minutes": 4}], "prior_knowledge": ["A student can explain what data an app collects and why, from ks2-06 and ks2-07.", "A student has used at least one AI tool and can describe what they asked it.", "A student can explain what a source check is, from ks3-12."], "key_learning_points": ["Using is not mastering. The brief decides the output.", "Hallucination is a feature of how these models generate, not a glitch to wait out.", "Bias is inherited from training data: whose voices were in it, and whose were not.", "Use it, check it, own it. You own the output you put your name on.", "An agent acts rather than answers, which raises the cost of not checking."], "teacher_tip": "Have students break the tool on purpose before they use it for anything real. A confident wrong answer they produced themselves teaches more than any warning you give.", "equipment": "A device with access to an AI tool if you want the live brief task. Otherwise the paper version in the print room covers the same ground."}'::jsonb
  where module_id = 'ks5-20-ai-mastery-data-rights';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"essential_question": "What will still be worth paying me for in ten years?", "cycles": [{"verb": "Audit", "title": "Identity as portfolio", "outcome": "I can explain the record I want found under my own name and how I am building it.", "minutes": 9}, {"verb": "Map", "title": "The jobs landscape", "outcome": "I can describe what AI compresses and what it expands.", "minutes": 10}, {"verb": "Test", "title": "Skills that endure", "outcome": "I can run the endurance test on my own plans and choose a skill to build.", "minutes": 7}], "prior_knowledge": ["A student can explain what an AI agent does, from ks5-20.", "A student can describe their own digital footprint, from ks2-07.", "A student has a plan, however loose, for what comes after school."], "key_learning_points": ["You already have a portfolio. The question is whether you wrote it on purpose.", "Automation is cheap and tireless at the routine layer of work.", "What compresses is the routine. What expands is judgement, taste and trust.", "AI produces options. Judgement chooses between them, and that is the paid part.", "The endurance test asks what still needs a person when the tool is free."], "teacher_tip": "Do not predict specific jobs disappearing by a date. Name the layer that compresses and let students apply it to their own plan, which is the transferable part.", "equipment": "Nothing beyond the board. The endurance test is a paper sheet from the print room."}'::jsonb
  where module_id = 'ks5-21-digital-identity-future-work';

-- Every module must now carry all six keys, and keywords must be 21 of 21.
do $$
declare missing int;
begin
  select count(*) into missing from schools.school_lessons
   where not (teacher_notes ?& array['essential_question','cycles','prior_knowledge',
                                     'key_learning_points','teacher_tip','equipment','keywords']);
  if missing > 0 then
    raise exception 'Migration 268: % module(s) still missing contract keys', missing;
  end if;
end $$;

commit;
