-- 269_starter_and_exit_quizzes.sql
-- Real starter and exit quiz banks on all 21 school modules.
--
-- Plan: plans/2026-09-07-oak-as-the-basis-plan.md, Phase 2.
-- Sources: research/2026-09-07-oak-and-common-sense-source-mining.md.
--
-- Oak ships two quizzes per lesson, four questions each, in mixed formats,
-- and every quiz has a question version and an answer version. This is that,
-- as data, so one route can render both versions and a wording change updates
-- every printed sheet at once.
--
--   starter_quiz  4 questions checking the PRIOR KNOWLEDGE this module needs,
--                 drawn from teacher_notes.prior_knowledge (migration 268) and
--                 from the preceding module in the spiral. Oak's own framing:
--                 the readiness check is four questions a teacher can run, not
--                 a paragraph they have to interpret.
--   exit_quiz     5 questions checking the KEY LEARNING POINTS, drawn from
--                 teacher_notes.key_learning_points and aimed squarely at the
--                 module's own misconceptions.
--
-- Shape per question: { format, question, answer, teaching_point } plus
-- options for tick_one and pairs for match. Formats are mixed within every
-- quiz (tick_one, true_false, match, fill_blank, short_answer), which the
-- migration enforces below rather than trusting.
--
-- The in lesson choice slides are untouched. They are the checks for
-- understanding, which is a different job: a check runs mid cycle and is
-- discussed, a quiz runs at the edges and is marked.
--
-- No statistic is claimed in any question or teaching point, so nothing here
-- needs a citation it cannot survive.
--
-- Non destructive: teacher_notes merged with ||. Idempotent. Backed up first.

begin;

create table if not exists schools.school_lessons_backup_269 as
  select id, module_id, teacher_notes, now() as backed_up_at
  from schools.school_lessons;

alter table schools.school_lessons_backup_269 enable row level security;

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "tick_one", "question": "Which one of these is a screen?", "options": ["A tablet", "A shoe", "A banana"], "answer": "A tablet", "teaching_point": "The word screen has to be in the room before the lesson can use it. If hands go up slowly, hold up a tablet and say the word together."}, {"format": "short_answer", "question": "Name one screen you have at home.", "answer": "Any of: the telly, a tablet, a phone, a computer.", "teaching_point": "Every child has one to name, so the lesson starts as theirs. A child who names none has still told you something useful."}, {"format": "tick_one", "question": "We are sorting into two piles, big things and small things. Where does an elephant go?", "options": ["The big pile", "The small pile"], "answer": "The big pile", "teaching_point": "Checks the child can sort into two piles, which is the exact shape of today''s game. If this is shaky, do one more round with objects first."}, {"format": "short_answer", "question": "Who is a grown up you could ask if you were not sure about something?", "answer": "Any trusted adult the child names, at school or at home.", "teaching_point": "A child who cannot name one needs that fixed before anything else in this lesson can land."}], "exit_quiz": [{"format": "true_false", "question": "Everything you see on a screen is real.", "answer": "False", "teaching_point": "The main misconception of the lesson. Some things on a screen are made up, and a computer can make a picture of something that never happened."}, {"format": "tick_one", "question": "A cartoon dragon breathing fire is:", "options": ["Real", "Made up", "Both"], "answer": "Made up", "teaching_point": "Cartoons are made up on purpose. Naming an easy one first makes the hard ones easier."}, {"format": "true_false", "question": "Made up things are naughty.", "answer": "False", "teaching_point": "Made up is lovely, it is just not real. A child who thinks made up means naughty will stop asking about it."}, {"format": "fill_blank", "question": "When I am not sure if something is real, I stop and ___ a grown up.", "answer": "ask", "teaching_point": "The single action outcome in the child''s own words. This is the one line to hear back."}, {"format": "tick_one", "question": "You see a picture of an elephant wearing pyjamas. What is the clever thing to do?", "options": ["Believe it", "Ask a grown up", "Get cross"], "answer": "Ask a grown up", "teaching_point": "Asking is clever and kind, never trouble. Say so out loud when you mark it."}]}'::jsonb
  where module_id = 'eyfs-01-screens-kindness';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "short_answer", "question": "Name three feelings.", "answer": "Any three, such as happy, sad, cross, tired, excited.", "teaching_point": "The lesson needs a feelings vocabulary to build on. Three is the floor."}, {"format": "tick_one", "question": "Where in your body might a worried feeling sit?", "options": ["Your tummy", "Your elbow", "Your hair"], "answer": "Your tummy", "teaching_point": "Feelings live somewhere in the body, and children can point to it. That is the whole body check."}, {"format": "true_false", "question": "If something on a screen makes you feel funny, you should keep it a secret.", "answer": "False", "teaching_point": "Carried forward from eyfs-01. Telling a grown up is the move, and it is never trouble."}, {"format": "short_answer", "question": "Who helps you when something feels wrong?", "answer": "Any trusted adult they name.", "teaching_point": "Same check as last time, one rung up. It should be quicker this year."}], "exit_quiz": [{"format": "match", "question": "Match the feeling word to what it means.", "pairs": [{"left": "Wiggly", "right": "My body cannot sit still"}, {"left": "Grumpy", "right": "A cross, growly feeling inside"}, {"left": "Calm", "right": "Quiet and comfy, like after a story"}], "answer": "Wiggly goes with my body cannot sit still; Grumpy goes with a cross, growly feeling inside; Calm goes with quiet and comfy, like after a story", "teaching_point": "Three words, three meanings. A child who can name the feeling can tell someone about it."}, {"format": "true_false", "question": "Screens can leave a feeling in your body.", "answer": "True", "teaching_point": "The feeling is real, and naming it is the skill. Do not let this be answered as a guess."}, {"format": "short_answer", "question": "What are Pebble''s three steps?", "answer": "Feel it, name it, tell a grown up.", "teaching_point": "The portable routine. If it does not come back word for word, say it together twice before they leave."}, {"format": "true_false", "question": "Telling a grown up how you feel is telling tales.", "answer": "False", "teaching_point": "Telling about a feeling is not telling tales. Children who confuse the two go quiet exactly when you need them not to."}, {"format": "fill_blank", "question": "Feelings pass more quickly once you have ___ them.", "answer": "named", "teaching_point": "The mechanism behind step two. Naming is not a nicety, it is what makes the feeling shrink."}]}'::jsonb
  where module_id = 'ks1-02-kind-screens-calm-bodies';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "tick_one", "question": "Which of these is real?", "options": ["A photo of your class", "A cartoon cat in a hat", "A dragon in a story"], "answer": "A photo of your class", "teaching_point": "Carried forward from eyfs-01. Real should now be quick."}, {"format": "true_false", "question": "Some things on a screen are made up.", "answer": "True", "teaching_point": "Last year''s headline, back as a warm up. If this is slow, the new idea today will be slower."}, {"format": "short_answer", "question": "What do you do when you are not sure if something is real?", "answer": "Stop and ask a grown up.", "teaching_point": "The eyfs-01 action, still the fallback under everything taught today."}, {"format": "short_answer", "question": "Tell me in one sentence what is happening in a picture your teacher shows you.", "answer": "Any accurate one sentence description.", "teaching_point": "The lesson asks children to look hard at a picture. This checks they can describe before they judge."}], "exit_quiz": [{"format": "tick_one", "question": "How many kinds of pictures did we learn about?", "options": ["Two", "Three", "Five"], "answer": "Three", "teaching_point": "Real, pretend, and made by a computer. Three, and the third one is the new one."}, {"format": "true_false", "question": "If a picture looks exactly like a photo, it must be real.", "answer": "False", "teaching_point": "The lesson''s main misconception. Computers can now make pictures that look exactly like photos."}, {"format": "match", "question": "Match each kind of picture to an example.", "pairs": [{"left": "Real", "right": "A photo of your birthday cake"}, {"left": "Pretend", "right": "A cartoon dog driving a bus"}, {"left": "Computer made", "right": "A photo of a cat riding a horse that never happened"}], "answer": "Real goes with a photo of your birthday cake; Pretend goes with a cartoon dog driving a bus; Computer made goes with a photo of a cat riding a horse that never happened", "teaching_point": "Sorting the three is the skill. Watch for children who put computer made with pretend."}, {"format": "short_answer", "question": "What is the detective question?", "answer": "Real, pretend, or computer made?", "teaching_point": "The tool they leave with. It should come back in those words."}, {"format": "tick_one", "question": "A picture makes you say WOW. What does a detective do?", "options": ["Share it straight away", "Ask the detective question", "Ignore it"], "answer": "Ask the detective question", "teaching_point": "WOW is the signal. The bigger the reaction, the more the question is worth asking."}]}'::jsonb
  where module_id = 'ks1-03-real-pretend-computer';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "short_answer", "question": "Describe your evening in order, from getting home to lights out.", "answer": "Any ordered account of their own evening.", "teaching_point": "The lesson builds a routine onto their real evening. If they cannot describe it, they cannot redesign it."}, {"format": "tick_one", "question": "Which of these is a feeling a screen can leave behind?", "options": ["Wiggly", "Hungry for maths", "Taller"], "answer": "Wiggly", "teaching_point": "Carried forward from ks1-02. The body still notices, and now they can name it."}, {"format": "true_false", "question": "A rule and a habit are the same thing.", "answer": "False", "teaching_point": "A rule is enforced from outside. A habit runs on its own. The difference is the whole lesson."}, {"format": "short_answer", "question": "Name one thing you always do at the same time every day, without being told.", "answer": "Any genuine habit: brushing teeth, feeding a pet, packing a bag.", "teaching_point": "Proof they already own habits. The lesson is not asking for a new skill, it is pointing at one they have."}], "exit_quiz": [{"format": "true_false", "question": "Stopping is easy if you really try.", "answer": "False", "teaching_point": "Apps and games are built with no finishing line, so willpower is the wrong tool. This is the misconception to smash."}, {"format": "short_answer", "question": "What are the three steps of the cool down lap?", "answer": "Warn, finish, swap.", "teaching_point": "The tool they leave with. Three words, in order."}, {"format": "tick_one", "question": "Why does the warning step work?", "options": ["It makes you feel guilty", "It lets your brain finish what it started", "It turns the screen off faster"], "answer": "It lets your brain finish what it started", "teaching_point": "Not willpower, not punishment. The warning gives the brain a landing place, which is why it works."}, {"format": "fill_blank", "question": "Willpower runs out, especially when you are tired. A ___ does not.", "answer": "routine", "teaching_point": "The headline of the lesson in one line."}, {"format": "short_answer", "question": "Why does it matter where a screen sleeps at night?", "answer": "Because a screen in the bedroom keeps pulling, and lost sleep never comes back.", "teaching_point": "Watch for the shallow answer, that it makes a noise. Silent does not fix it, the pull does not need a sound."}]}'::jsonb
  where module_id = 'ks2-04-screen-routines';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "short_answer", "question": "Name a game you play and one thing you enjoy about it.", "answer": "Any game and any genuine reason.", "teaching_point": "The lesson opens by respecting the game. Get the enjoyment on the record before anything is taken apart."}, {"format": "true_false", "question": "A routine beats willpower.", "answer": "True", "teaching_point": "Carried forward from ks2-04. It should be quick and confident by now."}, {"format": "tick_one", "question": "You buy 500 gems for five pounds. The gems are:", "options": ["Real money", "Game money you paid real money for", "Free"], "answer": "Game money you paid real money for", "teaching_point": "The gap between real money and game money is where the whole lesson lives. If this is fuzzy, slow down on cycle two."}, {"format": "short_answer", "question": "What does it mean if something is random?", "answer": "You cannot know what you will get before you get it.", "teaching_point": "Needed before loot boxes make sense. A child without this word will hear a loot box as a present."}], "exit_quiz": [{"format": "true_false", "question": "A game can be brilliant and be built to keep you playing at the same time.", "answer": "True", "teaching_point": "Both true at once. A pupil who answers false has heard the lesson as an attack on what they love."}, {"format": "tick_one", "question": "A loot box sells you:", "options": ["A thing you chose", "A chance", "Nothing at all"], "answer": "A chance", "teaching_point": "You are buying a chance, not a thing. Like a raffle ticket, and that is the honest comparison."}, {"format": "fill_blank", "question": "A countdown clock in a shop is there to stop you ___.", "answer": "thinking", "teaching_point": "The rush is the design, not a kindness. Naming the purpose is what breaks it."}, {"format": "short_answer", "question": "What are the three spend spotter questions?", "answer": "What is the real price, what am I actually getting, and what is the rush?", "teaching_point": "The tool they leave with. Three questions, asked before the tap, never after."}, {"format": "true_false", "question": "Only weak willed people get hooked by these tricks.", "answer": "False", "teaching_point": "The tricks are built by expert teams to work on everyone. Pupils who believe otherwise will never admit it happened to them."}]}'::jsonb
  where module_id = 'ks2-05-gaming-time-spend';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "short_answer", "question": "Give the steps for making a jam sandwich, in order.", "answer": "Any ordered set of steps ending with a sandwich.", "teaching_point": "This is an algorithm and they already know how to write one. Say so when you mark it."}, {"format": "tick_one", "question": "Which of these is something a game does to keep you playing?", "options": ["A countdown clock", "A loading screen", "A volume button"], "answer": "A countdown clock", "teaching_point": "Carried forward from ks2-05. Designed to keep you going, and they can already spot one."}, {"format": "true_false", "question": "You have seen a feed of videos or posts, on your own device or someone else''s.", "answer": "True", "teaching_point": "Not a knowledge check. A show of hands that tells you how close the lesson is to their real life."}, {"format": "short_answer", "question": "What does a computer need in order to do a job?", "answer": "Instructions, in the right order.", "teaching_point": "The one idea the whole lesson is built on. Anything close to this is a pass."}], "exit_quiz": [{"format": "fill_blank", "question": "An algorithm is a list of ___ followed in order.", "answer": "steps", "teaching_point": "A recipe for machines. Plain, and it should come back plainly."}, {"format": "short_answer", "question": "Say the feed loop in three steps.", "answer": "You watch, it learns, it serves more.", "teaching_point": "The tool they leave with. Three steps, in order, and it should be quick."}, {"format": "true_false", "question": "If I never like or comment, the feed learns nothing about me.", "answer": "False", "teaching_point": "Watch time is the loudest clue of all. This is the misconception most pupils arrive holding."}, {"format": "tick_one", "question": "What is the app actually collecting from you?", "options": ["Your money", "Your attention", "Your homework"], "answer": "Your attention", "teaching_point": "Attention is the product. Once a pupil sees that, the rest of the lesson explains itself."}, {"format": "short_answer", "question": "Why does the feed never end?", "answer": "Because an ending would be a place to stop, and the app does not want you to stop.", "teaching_point": "The bottomless bowl. Accept any answer that names the missing finishing line."}]}'::jsonb
  where module_id = 'ks2-06-how-algorithms-work';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "short_answer", "question": "Name two things a feed collects about you.", "answer": "Any two of: what you watch, what you skip, what you pause on, what you rewatch, what you like.", "teaching_point": "Carried forward from ks2-06. Data is not an abstract word to them now."}, {"format": "tick_one", "question": "Which of these belongs to your family and not to the internet?", "options": ["Your home address", "The weather", "The name of a football team"], "answer": "Your home address", "teaching_point": "The vault list starts here. If this is slow, the share test will be slow too."}, {"format": "true_false", "question": "A message you send can be passed on by the person who gets it.", "answer": "True", "teaching_point": "Obvious once said, and easily forgotten in the moment. This is the seed of the whole lesson."}, {"format": "short_answer", "question": "What is a screenshot?", "answer": "A photo of what is on a screen.", "teaching_point": "Needed before the lesson can explain why delete does not work."}], "exit_quiz": [{"format": "true_false", "question": "Deleting a post removes it from the internet.", "answer": "False", "teaching_point": "Delete removes your copy. Screenshots and forwards are already gone from your reach."}, {"format": "short_answer", "question": "What are the four things on the private list?", "answer": "Answers should name the vault items taught in the lesson, such as your address, your school, your password and where you will be.", "teaching_point": "Accept the lesson''s own four. The point is that the list is short, not that privacy means silence."}, {"format": "fill_blank", "question": "Your digital ___ grows whether you look after it or not.", "answer": "footprint", "teaching_point": "It is growing either way. The only choice is whether you are the one steering it."}, {"format": "tick_one", "question": "When is the share test run?", "options": ["After you share", "Before you share", "Only if someone complains"], "answer": "Before you share", "teaching_point": "Before, every time. A test run afterwards is not a test, it is a regret."}, {"format": "short_answer", "question": "Why does one share matter to future you?", "answer": "Because what you post stays findable and speaks for you when you are not there.", "teaching_point": "Reputation in their own words. Accept anything that reaches future me."}]}'::jsonb
  where module_id = 'ks2-07-privacy-reputation';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "short_answer", "question": "What is a screenshot, and who can take one?", "answer": "A photo of a screen, and anyone who can see it.", "teaching_point": "Carried forward from ks2-07. It matters today because evidence is one of the three moves."}, {"format": "short_answer", "question": "Name a trusted adult at school and one at home.", "answer": "Any two adults they name.", "teaching_point": "Two, not one. A pupil with only one named adult is a pupil with a single point of failure."}, {"format": "tick_one", "question": "Which of these is a pattern rather than a one off?", "options": ["Someone was rude once", "Someone is rude to the same person every day", "Someone was rude by accident"], "answer": "Someone is rude to the same person every day", "teaching_point": "Repeated is one of the three parts of bullying. Get the word pattern working before the definition lands."}, {"format": "true_false", "question": "Being unkind once is the same as bullying.", "answer": "False", "teaching_point": "Opens the lesson''s first cycle. Some will get this wrong, and that is the point of asking now."}], "exit_quiz": [{"format": "short_answer", "question": "What are the three parts of bullying?", "answer": "Repeated, targeted at the same person, and on purpose.", "teaching_point": "All three together. Two out of three is unkindness, which still needs dealing with but is a different thing."}, {"format": "match", "question": "Match the word to the person.", "pairs": [{"left": "Bystander", "right": "Sees it and does nothing"}, {"left": "Upstander", "right": "Sees it and makes one safe move"}, {"left": "Pile on", "right": "Lots of people joining in against one person"}], "answer": "Bystander goes with sees it and does nothing; Upstander goes with sees it and makes one safe move; Pile on goes with lots of people joining in against one person", "teaching_point": "The vocabulary of the lesson. Upstander is the one to hear used out loud afterwards."}, {"format": "short_answer", "question": "What are the three moves?", "answer": "Do not pile on, save the evidence, tell someone who can help.", "teaching_point": "The tool they leave with. In order, because saving evidence before deleting matters."}, {"format": "true_false", "question": "Telling an adult is snitching.", "answer": "False", "teaching_point": "Snitching tries to get someone into trouble. Telling gets someone out of it. Say the difference in those words."}, {"format": "tick_one", "question": "Why should you save the evidence before you delete anything?", "options": ["To look at it again", "So an adult can actually act on it", "To send it to friends"], "answer": "So an adult can actually act on it", "teaching_point": "A deleted message is an adult with nothing to work with. This is the step pupils skip."}]}'::jsonb
  where module_id = 'ks2-08-kind-safe-online';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "short_answer", "question": "Tell me about something you made that you are proud of, and why it is yours.", "answer": "Any genuine answer naming their own effort.", "teaching_point": "Ownership is felt before it is understood. Start with theirs, never someone else''s."}, {"format": "true_false", "question": "A picture can be made by a computer.", "answer": "True", "teaching_point": "Carried forward from ks1-03. It comes back today with a new question attached: where did it come from?"}, {"format": "short_answer", "question": "What does asking permission mean?", "answer": "Asking first and waiting for a yes.", "teaching_point": "Waiting for the yes is the half that gets dropped. Watch for answers that stop at asking."}, {"format": "tick_one", "question": "Someone copies your drawing and puts their name on it. That feels:", "options": ["Fine", "Unfair", "Funny"], "answer": "Unfair", "teaching_point": "The feeling arrives before the rule does. Use their word unfair when you introduce copyright."}], "exit_quiz": [{"format": "true_false", "question": "If something is online, it is free to use.", "answer": "False", "teaching_point": "Easy to find is not the same as free to take. This is the misconception the whole lesson turns on."}, {"format": "fill_blank", "question": "The rule that says the maker owns their work is called ___.", "answer": "copyright", "teaching_point": "One word, and they should own it by now."}, {"format": "match", "question": "Match each action to what it means.", "pairs": [{"left": "Credit", "right": "Naming the person who made it"}, {"left": "Permission", "right": "Asking first and waiting for a yes"}, {"left": "Original", "right": "Work that came from your own head"}], "answer": "Credit goes with naming the person who made it; Permission goes with asking first and waiting for a yes; Original goes with work that came from your own head", "teaching_point": "Three actions, three meanings. Credit and permission are different jobs and pupils blur them."}, {"format": "short_answer", "question": "Where does an AI picture really come from?", "answer": "From millions of pieces of work made by people who were not asked.", "teaching_point": "The AI wrinkle. Accept anything that reaches people who were not asked."}, {"format": "short_answer", "question": "Say the three word rule from this lesson.", "answer": "Make it, credit it, ask first.", "teaching_point": "The tool they leave with."}]}'::jsonb
  where module_id = 'ks2-09-copyright-ownership';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "short_answer", "question": "Describe the feed loop in three steps.", "answer": "You watch, it learns, it serves more.", "teaching_point": "Carried forward from ks2-06. Today it gets pointed at how they feel rather than at what they see."}, {"format": "short_answer", "question": "Name your three most used apps, honestly.", "answer": "Any three. Nobody collects this.", "teaching_point": "Say out loud that nothing here is collected or marked. Honest answers only arrive once pupils believe that."}, {"format": "true_false", "question": "A newspaper headline about a study says exactly what the study found.", "answer": "False", "teaching_point": "The gap between a headline and a study is the first cycle of the lesson."}, {"format": "tick_one", "question": "Which of these tells you most about how an app affects you?", "options": ["How many hours you spent", "What you actually did on it", "How many apps you have"], "answer": "What you actually did on it", "teaching_point": "The lesson''s central claim, asked before it is taught. Expect a split, and use it."}], "exit_quiz": [{"format": "true_false", "question": "Screen time hours decide your mood.", "answer": "False", "teaching_point": "The biggest studies found raw hours barely predict wellbeing. What you do matters more than how long."}, {"format": "match", "question": "Match the use to what it usually leaves behind.", "pairs": [{"left": "Connecting", "right": "Usually reads better"}, {"left": "Comparing", "right": "Usually reads worse"}, {"left": "Nothing", "right": "Time that left no trace at all"}], "answer": "Connecting goes with usually reads better; Comparing goes with usually reads worse; Nothing goes with time that left no trace at all", "teaching_point": "Three verdicts, and nothing is the one pupils forget to look for."}, {"format": "short_answer", "question": "Why is nothing a sneaky verdict?", "answer": "Because an hour that gave you nothing is still an hour spent.", "teaching_point": "The quiet one. Pupils look for better or worse and miss the hour that simply vanished."}, {"format": "fill_blank", "question": "An audit only works with ___ answers, not the answers that sound good.", "answer": "honest", "teaching_point": "The condition on the whole tool. Without it the audit is decoration."}, {"format": "short_answer", "question": "Name one thing you would change after a week of the mood audit, and why.", "answer": "Any specific change with a reason drawn from their own pattern.", "teaching_point": "The lesson''s real outcome. Vague answers mean the audit was not run honestly."}]}'::jsonb
  where module_id = 'ks3-10-mood-and-screens';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "short_answer", "question": "How does a feed learn what to show you?", "answer": "From what you watch, skip, pause on and rewatch.", "teaching_point": "Carried forward from ks2-06, because today the machine is being asked to judge an age."}, {"format": "short_answer", "question": "Name one platform and the minimum age it sets.", "answer": "Any platform with a plausible minimum age.", "teaching_point": "They know these. Getting them said out loud stops the lesson feeling theoretical."}, {"format": "true_false", "question": "A group chat with people you have never met is the same as one with your friends.", "answer": "False", "teaching_point": "Cycle three in advance. If this is answered true, that cycle needs more time."}, {"format": "tick_one", "question": "What is a VPN?", "options": ["A game", "A tool that hides where you really are", "A kind of phone"], "answer": "A tool that hides where you really are", "teaching_point": "Neutral definition first. A VPN is a normal work tool, and the risk arrives with what it is used for."}], "exit_quiz": [{"format": "true_false", "question": "An age setting only unlocks features.", "answer": "False", "teaching_point": "It switches protections on and off. This is the misconception the lesson exists to correct."}, {"format": "short_answer", "question": "What does a false age tell the machine to do?", "answer": "To treat you as an adult, and it will.", "teaching_point": "The machine cannot see kindness or intent. It reads the number and acts."}, {"format": "fill_blank", "question": "A workaround is a ___, never a free win.", "answer": "trade", "teaching_point": "The one line of the lesson. Trade, because something is always given up."}, {"format": "tick_one", "question": "What does moderation do?", "options": ["Decides what is popular", "Finds and removes harmful content", "Sets the price"], "answer": "Finds and removes harmful content", "teaching_point": "A workaround steps outside it, which is the cost pupils do not see."}, {"format": "short_answer", "question": "Name one protection hiding behind an age rule.", "answer": "Any of: stricter default privacy, no adult direct messages, less recommended content from strangers, tighter moderation.", "teaching_point": "Naming one is enough. The habit of looking for the protection is what transfers."}]}'::jsonb
  where module_id = 'ks3-11-social-workarounds';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "short_answer", "question": "How can a picture be made by a computer?", "answer": "A tool generates it from a description, so it can show something that never happened.", "teaching_point": "Carried forward from ks1-03 and ks2-09. Today it extends to video and audio."}, {"format": "short_answer", "question": "How does a feed decide what to show you?", "answer": "From what you watch, skip and rewatch, to keep you watching.", "teaching_point": "Carried forward from ks2-06. It matters today because the feed is how a fake travels."}, {"format": "true_false", "question": "You have shared or received something that was forwarded on from someone else.", "answer": "True", "teaching_point": "A show of hands, not a knowledge check. It puts every pupil inside the lesson."}, {"format": "tick_one", "question": "Something looks real. That means it is:", "options": ["Definitely real", "Possibly real", "Definitely fake"], "answer": "Possibly real", "teaching_point": "Looking real is no longer evidence. Expect some to pick definitely real, which is exactly why the lesson runs."}], "exit_quiz": [{"format": "match", "question": "Match each word to what it means.", "pairs": [{"left": "Misinformation", "right": "False, passed on by someone who believes it"}, {"left": "Disinformation", "right": "False, spread on purpose"}, {"left": "Deepfake", "right": "Generated video or audio of a real person"}], "answer": "Misinformation goes with false, passed on by someone who believes it; Disinformation goes with false, spread on purpose; Deepfake goes with generated video or audio of a real person", "teaching_point": "The three words of the lesson. The difference between the first two is intent, not accuracy."}, {"format": "short_answer", "question": "What are the three checks?", "answer": "Who made it, what is the source, and what does it want from me?", "teaching_point": "The tool they leave with. Three, in order, and the third one is the one people skip."}, {"format": "true_false", "question": "Pause is a weak answer.", "answer": "False", "teaching_point": "Pause is a verdict, not a failure to reach one. Say it out loud when you mark this."}, {"format": "fill_blank", "question": "A fake travels further than its ___.", "answer": "correction", "teaching_point": "Which is why the decision that matters is made before you share, not after."}, {"format": "tick_one", "question": "A video makes you furious and you want to repost it to warn people. What does the lesson say?", "options": ["Repost it fast", "Run the three checks first", "Never repost anything"], "answer": "Run the three checks first", "teaching_point": "Sharing to debunk spreads the fake further than the correction. Fury is the signal to slow down, not to speed up."}]}'::jsonb
  where module_id = 'ks3-12-misinfo-deepfakes';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "true_false", "question": "A message can be faked to look like it came from someone you trust.", "answer": "True", "teaching_point": "Carried forward from ks3-12. Today it comes with a motive attached: money."}, {"format": "short_answer", "question": "Name an account you own in a game or an app.", "answer": "Any account they name.", "teaching_point": "They need to be holding something of their own before the lesson explains why it is worth stealing."}, {"format": "tick_one", "question": "When someone rushes you, you think:", "options": ["More carefully", "Less carefully", "Exactly the same"], "answer": "Less carefully", "teaching_point": "Urgency is the engine of every scam. Establish the mechanism before the examples."}, {"format": "short_answer", "question": "What would you do if a friend messaged asking to borrow money right now?", "answer": "Any answer. Note who says they would check another way.", "teaching_point": "No right answer yet. Come back to their own words at the end of the lesson."}], "exit_quiz": [{"format": "short_answer", "question": "What are the three tells?", "answer": "It rushes you, it asks for something odd, it is too good to be true.", "teaching_point": "The tool they leave with. Three, and any one of them is enough to stop."}, {"format": "fill_blank", "question": "A fake message or login page dressed up as a real one is called ___.", "answer": "phishing", "teaching_point": "One word, spelled their way or ours. The idea is what counts."}, {"format": "true_false", "question": "Scams only catch older people.", "answer": "False", "teaching_point": "Scammers deliberately target teenagers, partly because this belief lowers their guard."}, {"format": "tick_one", "question": "Why is a gaming account worth stealing?", "options": ["It is not, they just do it for fun", "It can be sold, and it can scam the owner''s friends", "Only to annoy you"], "answer": "It can be sold, and it can scam the owner''s friends", "teaching_point": "Both halves matter. The second is why a message from a friend''s account is not automatically safe."}, {"format": "short_answer", "question": "A message rushes you. What are the three steps?", "answer": "Stop, check, refuse.", "teaching_point": "Checking through a different route is what breaks the script. Not replying to the message itself."}]}'::jsonb
  where module_id = 'ks3-13-scams-fraud-money';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "true_false", "question": "An image can be altered or generated.", "answer": "True", "teaching_point": "Carried forward from ks3-12. Today it is pointed at bodies rather than at news."}, {"format": "short_answer", "question": "Name two things an app collects about you.", "answer": "Any two of: what you watch, what you pause on, what you rewatch, how long you stay.", "teaching_point": "Carried forward from ks2-06, because the economics of the lesson run on attention."}, {"format": "short_answer", "question": "Name a feeling an app has left you with.", "answer": "Any honest answer. Nothing is collected.", "teaching_point": "Carried forward from ks3-10. Say again that no answer is recorded."}, {"format": "tick_one", "question": "A polished photo on a feed is:", "options": ["Exactly what the person looks like", "A set of choices", "Always fake"], "answer": "A set of choices", "teaching_point": "Neither trusting nor dismissing. Choices is the honest middle, and it is the lesson''s frame."}], "exit_quiz": [{"format": "short_answer", "question": "Name three choices that go into a polished image.", "answer": "Any three of: angle, lighting, editing, selection, posing, filters.", "teaching_point": "Selection is the one pupils miss. One shot kept out of two hundred is itself an edit."}, {"format": "true_false", "question": "You can always tell when a photo has been edited.", "answer": "False", "teaching_point": "Most retouching is invisible by design, which is what makes the comparison unfair."}, {"format": "fill_blank", "question": "Insecure people scroll longer and buy more, so insecurity has a market ___.", "answer": "value", "teaching_point": "The economics of insecurity, in one line. Follow the money and the design makes sense."}, {"format": "tick_one", "question": "You are comparing your ordinary day with:", "options": ["Someone else''s ordinary day", "Someone else''s chosen highlight", "Nothing at all"], "answer": "Someone else''s chosen highlight", "teaching_point": "Not a fair contest, and naming it is most of the defence."}, {"format": "short_answer", "question": "What does the image check get run on?", "answer": "The feeling, not the picture.", "teaching_point": "The tool they leave with. Run it when a post makes you feel worse, not when you suspect an edit."}]}'::jsonb
  where module_id = 'ks3-14-bodies-image-pressure';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "short_answer", "question": "How does a feed learn and then serve?", "answer": "It learns from what you watch and serves more of the same.", "teaching_point": "Carried forward from ks2-06. Today the question becomes who benefits."}, {"format": "short_answer", "question": "Name a scam''s three tells.", "answer": "It rushes you, it asks for something odd, it is too good to be true.", "teaching_point": "Carried forward from ks3-13. Persuasion uses the same levers, legally."}, {"format": "short_answer", "question": "Name a creator you follow and say why.", "answer": "Any creator and any genuine reason.", "teaching_point": "Parasocial trust needs a real example in the room, and it should be theirs, not yours."}, {"format": "tick_one", "question": "An advert works on:", "options": ["Only people who are not paying attention", "Everyone, including the people who make them", "Nobody who knows about it"], "answer": "Everyone, including the people who make them", "teaching_point": "The misconception to break in the first minute. Knowing the technique does not switch it off."}], "exit_quiz": [{"format": "short_answer", "question": "Name the four techniques from this lesson.", "answer": "Urgency, outrage, flattery and FOMO.", "teaching_point": "The tool they leave with. Naming the technique is what breaks the pull."}, {"format": "fill_blank", "question": "A design trick that pushes you into a choice you did not mean to make is a dark ___.", "answer": "pattern", "teaching_point": "One word. Fake countdowns and hidden cancel buttons are the everyday examples."}, {"format": "true_false", "question": "Rage bait is just people with strong opinions.", "answer": "False", "teaching_point": "Fury is farmed deliberately, because angry people comment, share and stay. The fury is the product."}, {"format": "tick_one", "question": "A creator you feel you know personally, who does not know you exist, is a:", "options": ["Friendship", "Parasocial relationship", "Sponsorship"], "answer": "Parasocial relationship", "teaching_point": "One way by definition. It is not a criticism of the pupil, it is a description of the design."}, {"format": "short_answer", "question": "Under UK rules, what must a paid post carry?", "answer": "A label saying it is an advert.", "teaching_point": "Hidden ones bank on your trust. Spotting the missing label is a real, usable skill."}]}'::jsonb
  where module_id = 'ks4-15-manipulation-persuasion';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "true_false", "question": "A screenshot can be taken of anything you send.", "answer": "True", "teaching_point": "Carried forward from ks2-07. It matters more today than it ever has."}, {"format": "short_answer", "question": "Name a trusted adult and one reporting route.", "answer": "Any adult, plus any of: Childline, Report Remove, CEOP, the school''s DSL.", "teaching_point": "Both halves. A pupil who can name neither needs that fixed before this lesson goes further."}, {"format": "true_false", "question": "A yes given under pressure is a free yes.", "answer": "False", "teaching_point": "The heart of cycle one, asked before it is taught. Note anyone who hesitates."}, {"format": "tick_one", "question": "Consent means:", "options": ["Not saying no", "A free, genuine yes", "Agreeing once, for ever"], "answer": "A free, genuine yes", "teaching_point": "Two of the three wrong answers are the two most common misconceptions. Use them."}], "exit_quiz": [{"format": "short_answer", "question": "Name the four properties of real consent.", "answer": "Free, specific, ongoing, and it can be taken back.", "teaching_point": "All four. Ongoing and revocable are the two that get dropped."}, {"format": "true_false", "question": "It is legal if you are both under 18 and you both agree.", "answer": "False", "teaching_point": "It is not. The law covers making, holding and sharing, and an indecent image is any sexual image of a person under 18."}, {"format": "fill_blank", "question": "Pressuring, guilting or threatening someone into a yes is called ___.", "answer": "coercion", "teaching_point": "One word, and a yes it produces is not consent."}, {"format": "true_false", "question": "Everyone is sending them.", "answer": "False", "teaching_point": "The evidence consistently shows most young people do not. The belief that everyone does is itself the pressure."}, {"format": "short_answer", "question": "A friend tells you an image of them is out there. What do you say?", "answer": "That it is not their fault, that they are not in trouble, and that Report Remove is free, confidential and works.", "teaching_point": "Three parts. Watch for answers that reach the tool but skip the two reassurances that let someone use it."}]}'::jsonb
  where module_id = 'ks4-16-consent-images-law';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "short_answer", "question": "What are the four properties of real consent?", "answer": "Free, specific, ongoing, and it can be taken back.", "teaching_point": "Carried forward from ks4-16. Today''s lesson is what happens when all four are absent."}, {"format": "short_answer", "question": "Name a scam''s tells and say how urgency works.", "answer": "It rushes you, asks for something odd, is too good to be true, and rushing stops you thinking.", "teaching_point": "Carried forward from ks3-13. Sextortion runs the same engine with far higher stakes."}, {"format": "short_answer", "question": "Name one adult you would tell something genuinely difficult.", "answer": "Any adult they name.", "teaching_point": "Ask for it in writing, privately. A pupil who names nobody is the reason this lesson exists."}, {"format": "tick_one", "question": "Blackmail is a crime committed by:", "options": ["The person being blackmailed", "The blackmailer", "Both"], "answer": "The blackmailer", "teaching_point": "Establish this before a single detail of the lesson. Everything after it depends on the pupil believing it."}], "exit_quiz": [{"format": "true_false", "question": "If you sent an image yourself, you are the one in trouble.", "answer": "False", "teaching_point": "The law treats under 18s in this situation as victims. Say it plainly and say it early, not only here."}, {"format": "short_answer", "question": "What are the three lifelines?", "answer": "Do not pay, do not keep it secret, report it.", "teaching_point": "The tool they leave with. Three, and the second is the one shame attacks."}, {"format": "true_false", "question": "Paying once makes it stop.", "answer": "False", "teaching_point": "Payment proves pressure works, so the demands continue and grow."}, {"format": "match", "question": "Match the service to what it does.", "pairs": [{"left": "Report Remove", "right": "Helps get intimate images of under 18s taken down"}, {"left": "CEOP", "right": "Sends the report to specialist police officers"}, {"left": "Childline", "right": "Free, confidential support to talk it through"}], "answer": "Report Remove goes with helps get intimate images of under 18s taken down; CEOP goes with sends the report to specialist police officers; Childline goes with free, confidential support to talk it through", "teaching_point": "Three routes, three jobs. Pupils should leave knowing at least one by name."}, {"format": "tick_one", "question": "This mostly happens to:", "options": ["Girls only", "Boys and girls, with financially motivated cases most often targeting teenage boys", "Adults only"], "answer": "Boys and girls, with financially motivated cases most often targeting teenage boys", "teaching_point": "Boys who believe this is a girls'' problem do not come forward. That belief is the risk."}]}'::jsonb
  where module_id = 'ks4-17-sextortion';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "short_answer", "question": "Name two persuasion techniques from the last lesson.", "answer": "Any two of: urgency, outrage, flattery, FOMO, dark patterns, rage bait.", "teaching_point": "Carried forward from ks4-15. Outrage is the one that matters most today."}, {"format": "short_answer", "question": "What does an algorithm optimise for?", "answer": "Your attention, not your wellbeing.", "teaching_point": "Carried forward from ks2-06. It is the engine under the pipeline."}, {"format": "short_answer", "question": "What does grooming mean?", "answer": "Slowly building trust and dependence in order to use someone.", "teaching_point": "They know it in a safeguarding sense. Today it is applied to beliefs rather than bodies."}, {"format": "tick_one", "question": "Someone with extreme beliefs usually started:", "options": ["With those beliefs", "Somewhere ordinary", "By reading a book"], "answer": "Somewhere ordinary", "teaching_point": "Nobody starts at the extreme. Establishing this stops the lesson being heard as about other people."}], "exit_quiz": [{"format": "true_false", "question": "Only loners and outsiders get radicalised.", "answer": "False", "teaching_point": "Pipelines are built for ordinary people in ordinary bad moments. That is what makes them work."}, {"format": "short_answer", "question": "What does a pipeline start with?", "answer": "Content that is reasonable, or funny, or true.", "teaching_point": "It has to, or nobody would enter it. Pupils expecting it to start extreme will not see it coming."}, {"format": "short_answer", "question": "Name the three stages of the grooming playbook.", "answer": "Attention, belonging, then isolation.", "teaching_point": "The same playbook, pointed at belief. Isolation is the stage that does the damage."}, {"format": "fill_blank", "question": "Anger keeps you watching, and someone is ___ for that.", "answer": "paid", "teaching_point": "Follow the money. Anger is not a side effect, it is the business."}, {"format": "tick_one", "question": "Content makes you furious about a whole group of people. What do you run?", "options": ["Straight to the comments", "The pipeline check", "Nothing, it is just jokes"], "answer": "The pipeline check", "teaching_point": "Fury is the trigger for the tool, exactly as in ks3-12. It is just jokes is the misconception, and the drip feed is why."}]}'::jsonb
  where module_id = 'ks4-18-radicalisation-misogyny';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "short_answer", "question": "What does a workaround cost?", "answer": "It skips the protections an age setting switches on, so it is a trade.", "teaching_point": "Carried forward from ks3-11. Today it is revisited with the arrival in sight."}, {"format": "short_answer", "question": "What does a mood audit tell you?", "answer": "What an app actually leaves behind: better, worse or nothing.", "teaching_point": "Carried forward from ks3-10. It becomes the week one audit in the arrival plan."}, {"format": "short_answer", "question": "Name two techniques a platform uses on you.", "answer": "Any two of: urgency, outrage, flattery, FOMO, dark patterns, infinite scroll.", "teaching_point": "Carried forward from ks4-15. They are naming what will be waiting for them."}, {"format": "tick_one", "question": "At 16, access goes from:", "options": ["A little to a bit more", "Zero to full", "Full to less"], "answer": "Zero to full", "teaching_point": "The cliff edge, stated before it is taught. It is the whole reason a plan beats a rule."}], "exit_quiz": [{"format": "short_answer", "question": "Why is the arrival at 16 a cliff edge and not a ramp?", "answer": "Because access goes from zero to full overnight rather than gradually.", "teaching_point": "A ramp can be learned on. A cliff edge cannot, which is why the plan is written in advance."}, {"format": "true_false", "question": "A fresh account learns slowly, so the first week does not matter much.", "answer": "False", "teaching_point": "A fresh account learns fastest. The first week decides what the feed becomes."}, {"format": "fill_blank", "question": "Whoever chooses the ___ quietly runs the experience.", "answer": "defaults", "teaching_point": "Which is why you choose them yourself, on day one, before anything else."}, {"format": "short_answer", "question": "Name the three parts of an arrival plan.", "answer": "My defaults, my first week audit, my exit rule.", "teaching_point": "The tool they leave with. Written before you need it, never during."}, {"format": "tick_one", "question": "Why do habits beat rules?", "options": ["Rules are unfair", "A habit is already running when nobody is enforcing anything", "Habits are easier to break"], "answer": "A habit is already running when nobody is enforcing anything", "teaching_point": "Arriving with habits beats arriving with rules. That is the line to hear back."}]}'::jsonb
  where module_id = 'ks4-19-readiness-at-16';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "short_answer", "question": "What data does an app collect about you, and why?", "answer": "Behaviour such as what you watch, tap and pause on, to predict and hold your attention.", "teaching_point": "Carried forward from ks2-06 and ks2-07. It sets up the data trade in cycle three."}, {"format": "short_answer", "question": "Name an AI tool you have used and what you asked it.", "answer": "Any tool and any genuine task.", "teaching_point": "Almost all will have one. The brief they gave it is the raw material for cycle one."}, {"format": "short_answer", "question": "What is a source check?", "answer": "Finding out who made a claim and whether it holds up.", "teaching_point": "Carried forward from ks3-12. It becomes the editor''s check on AI output."}, {"format": "tick_one", "question": "An AI tool gives a confident answer. That means it is:", "options": ["Correct", "Not necessarily correct", "Always wrong"], "answer": "Not necessarily correct", "teaching_point": "Confidence is a property of the output, never evidence about it."}], "exit_quiz": [{"format": "true_false", "question": "Hallucinations are rare glitches that the next update will fix.", "answer": "False", "teaching_point": "Plausible generation is the design, not a bug waiting for a patch."}, {"format": "short_answer", "question": "What decides the quality of what comes back from an AI tool?", "answer": "The quality of the brief you put in.", "teaching_point": "Using is not mastering. The brief is the skill."}, {"format": "short_answer", "question": "Where does bias in a model come from?", "answer": "The training data: whose voices were in it and whose were not.", "teaching_point": "An inheritance, not an opinion the model holds. That framing keeps the discussion useful."}, {"format": "short_answer", "question": "Say the three step rule from this lesson.", "answer": "Use it, check it, own it.", "teaching_point": "The tool they leave with. You own the output you put your name on."}, {"format": "tick_one", "question": "An agent differs from a chatbot because it:", "options": ["Answers faster", "Acts rather than only answers", "Costs more"], "answer": "Acts rather than only answers", "teaching_point": "It browses, books, buys and emails, which raises the cost of not checking."}]}'::jsonb
  where module_id = 'ks5-20-ai-mastery-data-rights';

update schools.school_lessons set teacher_notes = coalesce(teacher_notes, '{}'::jsonb) || '{"starter_quiz": [{"format": "short_answer", "question": "What does an AI agent do?", "answer": "It acts rather than only answers: it plans steps, uses tools and completes tasks.", "teaching_point": "Carried forward from ks5-20. It is the thing reshaping the work in this lesson."}, {"format": "short_answer", "question": "What is a digital footprint?", "answer": "The trail of everything you have posted, sent, liked or typed online.", "teaching_point": "Carried forward from ks2-07. Today it is renamed a portfolio and taken seriously."}, {"format": "short_answer", "question": "What is your plan for after school, however loose?", "answer": "Any answer, including no idea yet.", "teaching_point": "No idea yet is a real answer and this lesson works for it. Say so before you ask."}, {"format": "tick_one", "question": "If everyone has the same AI, what makes one person''s work worth more?", "options": ["Speed", "Judgement and taste", "Nothing"], "answer": "Judgement and taste", "teaching_point": "The essential question, asked cold. Come back to their first answer at the end."}], "exit_quiz": [{"format": "true_false", "question": "A blank search result is the safest online identity.", "answer": "False", "teaching_point": "A blank page is not safe, it is spare. Someone else''s account of you fills the gap."}, {"format": "short_answer", "question": "What does AI compress, and what does it expand?", "answer": "It compresses the routine layer and expands judgement, taste and trust.", "teaching_point": "Both halves. A pupil who answers only the first half has heard a threat, not a map."}, {"format": "fill_blank", "question": "AI produces options. ___ chooses between them, and that is the paid part.", "answer": "Judgement", "teaching_point": "The one line of the lesson."}, {"format": "short_answer", "question": "What does the endurance test ask?", "answer": "What still needs a person when the tool is free.", "teaching_point": "The tool they leave with. It is applied to their own plan, not to a list of jobs."}, {"format": "true_false", "question": "AI will take all the jobs, so there is no point preparing.", "answer": "False", "teaching_point": "The work changes shape rather than disappearing, and preparing is exactly what changes your position in it."}]}'::jsonb
  where module_id = 'ks5-21-digital-identity-future-work';

-- Guards. Every module carries both quizzes, at the right lengths, and no
-- quiz may be a single format: Oak mixes them on purpose and a sheet of five
-- identical questions is a worksheet, not a quiz.
do $$
declare bad int;
begin
  select count(*) into bad from schools.school_lessons
   where not (teacher_notes ?& array['starter_quiz','exit_quiz'])
      or jsonb_array_length(teacher_notes->'starter_quiz') <> 4
      or jsonb_array_length(teacher_notes->'exit_quiz') <> 5;
  if bad > 0 then
    raise exception 'Migration 269: % module(s) with a missing or wrong length quiz', bad;
  end if;

  select count(*) into bad from schools.school_lessons l
   where exists (
     select 1 from (values ('starter_quiz'), ('exit_quiz')) v(k)
      where (select count(distinct q->>'format')
               from jsonb_array_elements(l.teacher_notes->v.k) q) < 2);
  if bad > 0 then
    raise exception 'Migration 269: % module(s) with a single format quiz', bad;
  end if;
end $$;

commit;
