-- 297_the_passport_carries_through.sql
--
-- THE PASSPORT BEAT IN EVERY LESSON WITH A PAGE.
--
-- Justin, 13 September 2026, on the schools lessons: "make sure the passport
-- theme carries through and updates for progression as agreed, fills up,
-- makes sense, matches the other platform passport." Until this migration
-- only lesson 1 mentioned the passport in its deck (migration 231), as a digi
-- slide the class watched, and every other lesson filled a page it never
-- showed. The parents app's passport, the same morning, put the four agreed
-- areas on every page (PR #1057). This is the school side of that.
--
-- ONE BEAT PER LESSON, near the end, before DiGi closes: an interactive of
-- component passport-page. The player draws the page this lesson fills, in
-- the child's book's own colours and shape (shared/components/PassportPage),
-- and the class taps Fill the page: the ring and the area bar move by one and
-- the room says the word stamp. The count is the screen's memory of its
-- classes (shared/schools-taught), never a child. Nothing here writes a
-- completion, a stamp or a code, and the seal stays open on the wall because
-- the stamp is the stage's, earned at home.
--
-- An interactive is an action under the council's four minute rule, so the
-- closing stretch of watching can only get shorter. Lesson 1's old passport
-- digi slide is replaced by the beat in the same place, at the same length.
-- The two KS5 modules sit after the passport (migration 277) and get nothing,
-- on purpose.
--
-- WHAT THE DO BLOCK GUARDS, and every one of them rolls the whole thing back:
--   0. exactly 23 beat rows, one per module with a page, none for KS5
--   1. no dash in any new copy
--   2. every deck closes on DiGi and carries no beat yet
--   3. every beat names its own module and the page the row already knows
--   4. no passive stretch over four minutes afterwards, and the stricter
--      contract rule never gets worse than it was
--   5. the timing string states the new real total
--   6. the scheme grows by exactly 22 slides (23 beats in, lesson 1's old
--      slide out)
--   7. afterwards, every module with a page carries exactly one beat naming
--      itself, right before the close, and no module after the passport
--      carries one
--
-- Not idempotent by construction: a second run fails guard 2 on every module.
-- Backed up first.
--
-- Generated by scripts/gen-297.mjs; the readable source is
-- content/beats/2026-09-14-passport-beats.json.

begin;

create table if not exists schools.school_lessons_backup_297 as
  select id, module_id, slides, teacher_notes, now() as backed_up_at from schools.school_lessons;
alter table schools.school_lessons_backup_297 enable row level security;
create table schools._m297 (module_id text primary key, beat jsonb not null);

insert into schools._m297 (module_id, beat) values ($b$eyfs-01-screens-kindness$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"foundation","moduleId":"eyfs-01-screens-kindness","register":"bouncy","heading":"The passport","prompt":"Today filled a little bit of the First steps page. Tap to fill it in!","after":"A full page brings the big check, and the big check earns Pebble's stamp!","button":"Fill the page"},"script":"DiGi Junior keeps a special book called the passport. It is the book of getting ready for phones and screens, all the way to sixteen. Every lesson we do together fills a little bit of the page, and jobs at home fill it too. Ask one child to come up and tap Fill the page, and when the ring moves, everybody shouts the word stamp. Then say: when the page is full, DiGi asks five little questions, the big check, and the page earns Pebble's stamp. Nobody can fail the passport. It only ever fills up. The note going home today tells your grown ups which page it is. The count on the wall is this screen's memory of your class, not any child's record: the real passport is the one at home."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks1-02-kind-screens-calm-bodies$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"foundation","moduleId":"ks1-02-kind-screens-calm-bodies","register":"bouncy","heading":"The passport","prompt":"Today filled a little bit of the First steps page. Tap to fill it in!","after":"A full page brings the big check, and the big check earns Pebble's stamp!","button":"Fill the page"},"script":"DiGi Junior keeps a special book called the passport. It is the book of getting ready for phones and screens, all the way to sixteen. Every lesson we do together fills a little bit of the page, and jobs at home fill it too. Ask one child to come up and tap Fill the page, and when the ring moves, everybody shouts the word stamp. Then say: when the page is full, DiGi asks five little questions, the big check, and the page earns Pebble's stamp. Nobody can fail the passport. It only ever fills up. The note going home today tells your grown ups which page it is. The count on the wall is this screen's memory of your class, not any child's record: the real passport is the one at home."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks1-03-real-pretend-computer$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"foundation","moduleId":"ks1-03-real-pretend-computer","register":"bouncy","heading":"The passport","prompt":"Today filled a little bit of the First steps page. Tap to fill it in!","after":"A full page brings the big check, and the big check earns Pebble's stamp!","button":"Fill the page"},"script":"DiGi Junior keeps a special book called the passport. It is the book of getting ready for phones and screens, all the way to sixteen. Every lesson we do together fills a little bit of the page, and jobs at home fill it too. Ask one child to come up and tap Fill the page, and when the ring moves, everybody shouts the word stamp. Then say: when the page is full, DiGi asks five little questions, the big check, and the page earns Pebble's stamp. Nobody can fail the passport. It only ever fills up. The note going home today tells your grown ups which page it is. The count on the wall is this screen's memory of your class, not any child's record: the real passport is the one at home."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks2-04-screen-routines$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"builder","moduleId":"ks2-04-screen-routines","register":"playful","heading":"The passport","prompt":"Today filled a little of the Good habits page. Tap to fill it in.","after":"A full page brings the big check, and the big check earns Bloop's stamp.","button":"Fill the page"},"script":"The passport is the book of getting ready for screens and phones, all the way to sixteen, and many of your families keep it at home in the parents app. Every lesson here fills a little of the page, and jobs at home fill it too. One volunteer taps Fill the page; the ring and the area bar move by one, and the class says the word stamp. Say: when the page is full, the big check earns Bloop's stamp. Nobody can fail the passport, it only fills up. The parent note going home says which page today filled and carries the home code that puts it in the child's own book. The count on the wall is this screen's memory of your classes, never a child's record."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks2-05-gaming-time-spend$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"builder","moduleId":"ks2-05-gaming-time-spend","register":"playful","heading":"The passport","prompt":"Today filled a little of the Good habits page. Tap to fill it in.","after":"A full page brings the big check, and the big check earns Bloop's stamp.","button":"Fill the page"},"script":"The passport is the book of getting ready for screens and phones, all the way to sixteen, and many of your families keep it at home in the parents app. Every lesson here fills a little of the page, and jobs at home fill it too. One volunteer taps Fill the page; the ring and the area bar move by one, and the class says the word stamp. Say: when the page is full, the big check earns Bloop's stamp. Nobody can fail the passport, it only fills up. The parent note going home says which page today filled and carries the home code that puts it in the child's own book. The count on the wall is this screen's memory of your classes, never a child's record."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks2-06-how-algorithms-work$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"builder","moduleId":"ks2-06-how-algorithms-work","register":"playful","heading":"The passport","prompt":"Today filled a little of the Good habits page. Tap to fill it in.","after":"A full page brings the big check, and the big check earns Bloop's stamp.","button":"Fill the page"},"script":"The passport is the book of getting ready for screens and phones, all the way to sixteen, and many of your families keep it at home in the parents app. Every lesson here fills a little of the page, and jobs at home fill it too. One volunteer taps Fill the page; the ring and the area bar move by one, and the class says the word stamp. Say: when the page is full, the big check earns Bloop's stamp. Nobody can fail the passport, it only fills up. The parent note going home says which page today filled and carries the home code that puts it in the child's own book. The count on the wall is this screen's memory of your classes, never a child's record."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks2-07-privacy-reputation$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"builder","moduleId":"ks2-07-privacy-reputation","register":"playful","heading":"The passport","prompt":"Today filled a little of the Good habits page. Tap to fill it in.","after":"A full page brings the big check, and the big check earns Bloop's stamp.","button":"Fill the page"},"script":"The passport is the book of getting ready for screens and phones, all the way to sixteen, and many of your families keep it at home in the parents app. Every lesson here fills a little of the page, and jobs at home fill it too. One volunteer taps Fill the page; the ring and the area bar move by one, and the class says the word stamp. Say: when the page is full, the big check earns Bloop's stamp. Nobody can fail the passport, it only fills up. The parent note going home says which page today filled and carries the home code that puts it in the child's own book. The count on the wall is this screen's memory of your classes, never a child's record."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks2-08-kind-safe-online$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"builder","moduleId":"ks2-08-kind-safe-online","register":"playful","heading":"The passport","prompt":"Today filled a little of the Good habits page. Tap to fill it in.","after":"A full page brings the big check, and the big check earns Bloop's stamp.","button":"Fill the page"},"script":"The passport is the book of getting ready for screens and phones, all the way to sixteen, and many of your families keep it at home in the parents app. Every lesson here fills a little of the page, and jobs at home fill it too. One volunteer taps Fill the page; the ring and the area bar move by one, and the class says the word stamp. Say: when the page is full, the big check earns Bloop's stamp. Nobody can fail the passport, it only fills up. The parent note going home says which page today filled and carries the home code that puts it in the child's own book. The count on the wall is this screen's memory of your classes, never a child's record."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks2-09-copyright-ownership$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"builder","moduleId":"ks2-09-copyright-ownership","register":"playful","heading":"The passport","prompt":"Today filled a little of the Good habits page. Tap to fill it in.","after":"A full page brings the big check, and the big check earns Bloop's stamp.","button":"Fill the page"},"script":"The passport is the book of getting ready for screens and phones, all the way to sixteen, and many of your families keep it at home in the parents app. Every lesson here fills a little of the page, and jobs at home fill it too. One volunteer taps Fill the page; the ring and the area bar move by one, and the class says the word stamp. Say: when the page is full, the big check earns Bloop's stamp. Nobody can fail the passport, it only fills up. The parent note going home says which page today filled and carries the home code that puts it in the child's own book. The count on the wall is this screen's memory of your classes, never a child's record."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks2-23-when-a-machine-talks-like-a-friend$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"builder","moduleId":"ks2-23-when-a-machine-talks-like-a-friend","register":"playful","heading":"The passport","prompt":"Today filled a little of the Good habits page. Tap to fill it in.","after":"A full page brings the big check, and the big check earns Bloop's stamp.","button":"Fill the page"},"script":"The passport is the book of getting ready for screens and phones, all the way to sixteen, and many of your families keep it at home in the parents app. Every lesson here fills a little of the page, and jobs at home fill it too. One volunteer taps Fill the page; the ring and the area bar move by one, and the class says the word stamp. Say: when the page is full, the big check earns Bloop's stamp. Nobody can fail the passport, it only fills up. The parent note going home says which page today filled and carries the home code that puts it in the child's own book. The count on the wall is this screen's memory of your classes, never a child's record."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks2-25-stay-the-maker$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"builder","moduleId":"ks2-25-stay-the-maker","register":"playful","heading":"The passport","prompt":"Today filled a little of the Good habits page. Tap to fill it in.","after":"A full page brings the big check, and the big check earns Bloop's stamp.","button":"Fill the page"},"script":"The passport is the book of getting ready for screens and phones, all the way to sixteen, and many of your families keep it at home in the parents app. Every lesson here fills a little of the page, and jobs at home fill it too. One volunteer taps Fill the page; the ring and the area bar move by one, and the class says the word stamp. Say: when the page is full, the big check earns Bloop's stamp. Nobody can fail the passport, it only fills up. The parent note going home says which page today filled and carries the home code that puts it in the child's own book. The count on the wall is this screen's memory of your classes, never a child's record."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks3-10-mood-and-screens$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"shaper","moduleId":"ks3-10-mood-and-screens","register":"level","heading":"The passport","prompt":"Today filled part of the Making choices page. Tap to fill it in.","after":"When the page is full, the big check earns Orbit's stamp.","button":"Fill the page"},"script":"Thirty seconds, not a lecture. The passport is the record of getting ready for full access at sixteen, kept at home in the parents app, and every lesson here fills part of a page. Tap Fill the page, or hand the clicker to someone. Point at the area today built and the count moving. Say: when the page is full, the big check earns Orbit's stamp, and nobody can fail it. The parent note carries the home code that puts today in their own passport. The count on the wall is this screen's memory of your classes, not anyone's record."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks3-11-social-workarounds$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"shaper","moduleId":"ks3-11-social-workarounds","register":"level","heading":"The passport","prompt":"Today filled part of the Making choices page. Tap to fill it in.","after":"When the page is full, the big check earns Orbit's stamp.","button":"Fill the page"},"script":"Thirty seconds, not a lecture. The passport is the record of getting ready for full access at sixteen, kept at home in the parents app, and every lesson here fills part of a page. Tap Fill the page, or hand the clicker to someone. Point at the area today built and the count moving. Say: when the page is full, the big check earns Orbit's stamp, and nobody can fail it. The parent note carries the home code that puts today in their own passport. The count on the wall is this screen's memory of your classes, not anyone's record."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks3-12-misinfo-deepfakes$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"shaper","moduleId":"ks3-12-misinfo-deepfakes","register":"level","heading":"The passport","prompt":"Today filled part of the Making choices page. Tap to fill it in.","after":"When the page is full, the big check earns Orbit's stamp.","button":"Fill the page"},"script":"Thirty seconds, not a lecture. The passport is the record of getting ready for full access at sixteen, kept at home in the parents app, and every lesson here fills part of a page. Tap Fill the page, or hand the clicker to someone. Point at the area today built and the count moving. Say: when the page is full, the big check earns Orbit's stamp, and nobody can fail it. The parent note carries the home code that puts today in their own passport. The count on the wall is this screen's memory of your classes, not anyone's record."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks3-13-scams-fraud-money$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"shaper","moduleId":"ks3-13-scams-fraud-money","register":"level","heading":"The passport","prompt":"Today filled part of the Making choices page. Tap to fill it in.","after":"When the page is full, the big check earns Orbit's stamp.","button":"Fill the page"},"script":"Thirty seconds, not a lecture. The passport is the record of getting ready for full access at sixteen, kept at home in the parents app, and every lesson here fills part of a page. Tap Fill the page, or hand the clicker to someone. Point at the area today built and the count moving. Say: when the page is full, the big check earns Orbit's stamp, and nobody can fail it. The parent note carries the home code that puts today in their own passport. The count on the wall is this screen's memory of your classes, not anyone's record."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks3-14-bodies-image-pressure$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"shaper","moduleId":"ks3-14-bodies-image-pressure","register":"level","heading":"The passport","prompt":"Today filled part of the Making choices page. Tap to fill it in.","after":"When the page is full, the big check earns Orbit's stamp.","button":"Fill the page"},"script":"Thirty seconds, not a lecture. The passport is the record of getting ready for full access at sixteen, kept at home in the parents app, and every lesson here fills part of a page. Tap Fill the page, or hand the clicker to someone. Point at the area today built and the count moving. Say: when the page is full, the big check earns Orbit's stamp, and nobody can fail it. The parent note carries the home code that puts today in their own passport. The count on the wall is this screen's memory of your classes, not anyone's record."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks3-22-when-an-ai-acts-like-a-friend$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"shaper","moduleId":"ks3-22-when-an-ai-acts-like-a-friend","register":"level","heading":"The passport","prompt":"Today filled part of the Making choices page. Tap to fill it in.","after":"When the page is full, the big check earns Orbit's stamp.","button":"Fill the page"},"script":"Thirty seconds, not a lecture. The passport is the record of getting ready for full access at sixteen, kept at home in the parents app, and every lesson here fills part of a page. Tap Fill the page, or hand the clicker to someone. Point at the area today built and the count moving. Say: when the page is full, the big check earns Orbit's stamp, and nobody can fail it. The parent note carries the home code that puts today in their own passport. The count on the wall is this screen's memory of your classes, not anyone's record."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks3-24-is-it-doing-my-thinking$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"shaper","moduleId":"ks3-24-is-it-doing-my-thinking","register":"level","heading":"The passport","prompt":"Today filled part of the Making choices page. Tap to fill it in.","after":"When the page is full, the big check earns Orbit's stamp.","button":"Fill the page"},"script":"Thirty seconds, not a lecture. The passport is the record of getting ready for full access at sixteen, kept at home in the parents app, and every lesson here fills part of a page. Tap Fill the page, or hand the clicker to someone. Point at the area today built and the count moving. Say: when the page is full, the big check earns Orbit's stamp, and nobody can fail it. The parent note carries the home code that puts today in their own passport. The count on the wall is this screen's memory of your classes, not anyone's record."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks4-15-manipulation-persuasion$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"independent","moduleId":"ks4-15-manipulation-persuasion","register":"still","heading":"The passport","prompt":"Today counts toward the Ready at sixteen page. Tap to fill it in.","after":"When the page is full, the big check earns Nova's stamp.","button":"Fill the page"},"script":"Level and brief. The passport is the record of preparation for full access at sixteen, kept at home. Today fills part of its last page. Tap Fill the page, name the area it built, and say once: when the page is full, the big check earns Nova's stamp, and it is proof of judgement, never a licence. The parent note carries the home code that puts today in their own passport. The count on the wall is this screen's memory of your classes, not a record of anyone."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks4-16-consent-images-law$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"independent","moduleId":"ks4-16-consent-images-law","register":"still","heading":"The passport","prompt":"Today counts toward the Ready at sixteen page. Tap to fill it in.","after":"When the page is full, the big check earns Nova's stamp.","button":"Fill the page"},"script":"Level and brief. The passport is the record of preparation for full access at sixteen, kept at home. Today fills part of its last page. Tap Fill the page, name the area it built, and say once: when the page is full, the big check earns Nova's stamp, and it is proof of judgement, never a licence. The parent note carries the home code that puts today in their own passport. The count on the wall is this screen's memory of your classes, not a record of anyone."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks4-17-sextortion$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"independent","moduleId":"ks4-17-sextortion","register":"still","heading":"The passport","prompt":"Today counts toward the Ready at sixteen page. Tap to fill it in.","after":"When the page is full, the big check earns Nova's stamp.","button":"Fill the page"},"script":"Level and brief. The passport is the record of preparation for full access at sixteen, kept at home. Today fills part of its last page. Tap Fill the page, name the area it built, and say once: when the page is full, the big check earns Nova's stamp, and it is proof of judgement, never a licence. The parent note carries the home code that puts today in their own passport. The count on the wall is this screen's memory of your classes, not a record of anyone."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks4-18-radicalisation-misogyny$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"independent","moduleId":"ks4-18-radicalisation-misogyny","register":"still","heading":"The passport","prompt":"Today counts toward the Ready at sixteen page. Tap to fill it in.","after":"When the page is full, the big check earns Nova's stamp.","button":"Fill the page"},"script":"Level and brief. The passport is the record of preparation for full access at sixteen, kept at home. Today fills part of its last page. Tap Fill the page, name the area it built, and say once: when the page is full, the big check earns Nova's stamp, and it is proof of judgement, never a licence. The parent note carries the home code that puts today in their own passport. The count on the wall is this screen's memory of your classes, not a record of anyone."}$b$::jsonb);
insert into schools._m297 (module_id, beat) values ($b$ks4-19-readiness-at-16$b$, $b${"type":"interactive","phase":"close","minutes":1,"component":"passport-page","config":{"placement":"independent","moduleId":"ks4-19-readiness-at-16","register":"still","heading":"The passport","prompt":"Today counts toward the Ready at sixteen page. Tap to fill it in.","after":"When the page is full, the big check earns Nova's stamp.","button":"Fill the page"},"script":"Level and brief. The passport is the record of preparation for full access at sixteen, kept at home. Today fills part of its last page. Tap Fill the page, name the area it built, and say once: when the page is full, the big check earns Nova's stamp, and it is proof of judgement, never a licence. The parent note carries the home code that puts today in their own passport. The count on the wall is this screen's memory of your classes, not a record of anyone."}$b$::jsonb);

commit;

do $$
declare
  r record;
  s jsonb; x jsonb; o jsonb;
  n int; i int; ld int; removed int; added int;
  run int; maxrun int; srun int; smax_before int; smax_after int;
  tot int; lead int; m text; timing text;
  total_before int; total_after int; bad int;
begin
  select coalesce(sum(jsonb_array_length(slides)), 0) into total_before from schools.school_lessons;

  -- 0. one beat per module with a page, and nothing for the two after it
  if (select count(*) from schools._m297) <> 23 then
    raise exception 'guard 0: expected 23 beat rows, found %', (select count(*) from schools._m297);
  end if;
  if (select count(*) from schools._m297 h join schools.school_lessons l using (module_id)) <> 23 then
    raise exception 'guard 0: a beat row names a module that does not exist';
  end if;
  if exists (select 1 from schools._m297 h join schools.school_lessons l using (module_id) where l.key_stage = 'KS5') then
    raise exception 'guard 0: a KS5 module must not carry a passport beat';
  end if;
  if (select count(*) from schools.school_lessons where coalesce(teacher_notes->>'passport_stage', '') not in ('', 'after')) <> 23 then
    raise exception 'guard 0: the scheme has % modules with a page, expected 23',
      (select count(*) from schools.school_lessons where coalesce(teacher_notes->>'passport_stage', '') not in ('', 'after'));
  end if;

  -- 1. no dash in any new copy
  select count(*) into bad from (
    select unnest(array[
      h.beat->>'script', h.beat->'config'->>'heading', h.beat->'config'->>'prompt',
      h.beat->'config'->>'after', h.beat->'config'->>'button'
    ]) as t from schools._m297 h
  ) q where t ~ '[‐-―]' or t ~ '[A-Za-z] - [A-Za-z]' or t ~ '[A-Za-z]-[A-Za-z]';
  if bad > 0 then raise exception 'guard 1: % new copy strings carry a dash', bad; end if;

  for r in select h.module_id, h.beat, l.slides, l.teacher_notes
             from schools._m297 h join schools.school_lessons l using (module_id) order by h.module_id loop
    s := r.slides;
    n := jsonb_array_length(s);

    -- 3. the beat names its own module and the page the row already knows
    if r.beat->>'type' <> 'interactive' or r.beat->>'component' <> 'passport-page' or r.beat->>'phase' <> 'close' then
      raise exception 'guard 3: % beat is not a close phase passport-page interactive', r.module_id;
    end if;
    if r.beat->'config'->>'moduleId' is distinct from r.module_id then
      raise exception 'guard 3: % beat names another module', r.module_id;
    end if;
    if coalesce(r.teacher_notes->>'passport_stage', '') in ('', 'after') then
      raise exception 'guard 3: % has no passport page', r.module_id;
    end if;
    if r.beat->'config'->>'placement' is distinct from r.teacher_notes->>'passport_stage' then
      raise exception 'guard 3: % beat says page % but the row says %', r.module_id,
        r.beat->'config'->>'placement', r.teacher_notes->>'passport_stage';
    end if;

    -- 2. the deck closes on DiGi and carries no beat yet
    ld := null;
    for i in 0..n-1 loop
      if s->i->>'type' = 'digi' then ld := i; end if;
      if s->i->>'type' = 'interactive' and s->i->>'component' = 'passport-page' then
        raise exception 'guard 2: % already carries a passport beat', r.module_id;
      end if;
    end loop;
    if ld is null or ld <> n - 1 then raise exception 'guard 2: % does not close on DiGi', r.module_id; end if;

    -- the stricter contract rule, before
    srun := 0; smax_before := 0;
    for i in 0..n-1 loop
      x := s->i;
      if x->>'type' in ('choice','discussion','interactive','tryit') then srun := 0;
      else srun := srun + coalesce((x->>'minutes')::int, 0); if srun > smax_before then smax_before := srun; end if; end if;
    end loop;

    -- the splice: lesson 1's old passport slide out, the beat in before the close
    o := '[]'::jsonb; removed := 0;
    for i in 0..n-1 loop
      x := s->i;
      if x->>'type' = 'digi' and x->>'heading' = 'The passport' then
        removed := removed + coalesce((x->>'minutes')::int, 0);
        continue;
      end if;
      if i = ld then o := o || r.beat; end if;
      o := o || x;
    end loop;

    -- 4. the council's rule holds afterwards, and the stricter rule is no worse
    run := 0; maxrun := 0; srun := 0; smax_after := 0; tot := 0;
    for i in 0..jsonb_array_length(o)-1 loop
      x := o->i;
      tot := tot + coalesce((x->>'minutes')::int, 0);
      if x->>'type' in ('choice','discussion','tryit','interactive','scenario','quote')
         or (x->>'type' = 'diagram' and jsonb_array_length(coalesce(x->'verdicts','[]'::jsonb)) > 0) then
        run := 0;
      else
        run := run + coalesce((x->>'minutes')::int, 0);
        if run > maxrun then maxrun := run; end if;
      end if;
      if x->>'type' in ('choice','discussion','interactive','tryit') then srun := 0;
      else srun := srun + coalesce((x->>'minutes')::int, 0); if srun > smax_after then smax_after := srun; end if; end if;
    end loop;
    if maxrun > 4 then raise exception 'guard 4: % has a passive run of % minutes after the beat', r.module_id, maxrun; end if;
    if smax_after > greatest(smax_before, 4) then
      raise exception 'guard 4: % strict passive run grew from % to %', r.module_id, smax_before, smax_after;
    end if;

    -- 5. the timing string keeps telling the truth
    timing := r.teacher_notes->>'timing';
    lead := substring(timing from '^\d+')::int;
    if lead is null then raise exception 'guard 5: % timing has no leading total', r.module_id; end if;
    added := coalesce((r.beat->>'minutes')::int, 0) - removed;
    if added <> 0 then
      timing := regexp_replace(timing, '^\d+', (lead + added)::text);
      m := substring(timing from 'close (\d+)');
      if m is null then raise exception 'guard 5: % timing has no close count', r.module_id; end if;
      timing := regexp_replace(timing, 'close \d+', 'close ' || (m::int + added)::text);
    end if;
    if lead + added <> tot then
      raise exception 'guard 5: % timing would state % but the deck runs %', r.module_id, lead + added, tot;
    end if;

    update schools.school_lessons
       set slides = o,
           teacher_notes = jsonb_set(teacher_notes, '{timing}', to_jsonb(timing))
     where module_id = r.module_id;
  end loop;

  -- 6. the scheme grew by exactly the beats less lesson 1's old slide
  select sum(jsonb_array_length(slides)) into total_after from schools.school_lessons;
  if total_after <> total_before + 22 then
    raise exception 'guard 6: the scheme has % slides, expected %', total_after, total_before + 22;
  end if;

  -- 7. every module with a page carries exactly one beat naming itself, right
  --    before the close; no module after the passport carries one
  select count(*) into bad from schools.school_lessons l
   where coalesce(l.teacher_notes->>'passport_stage', '') not in ('', 'after')
     and (select count(*) from jsonb_array_elements(l.slides) sl
           where sl->>'type' = 'interactive' and sl->>'component' = 'passport-page'
             and sl->'config'->>'moduleId' = l.module_id
             and sl->'config'->>'placement' = l.teacher_notes->>'passport_stage') <> 1;
  if bad > 0 then raise exception 'guard 7: % modules with a page do not carry exactly one beat naming themselves', bad; end if;
  select count(*) into bad from schools.school_lessons l
   where coalesce(l.teacher_notes->>'passport_stage', '') not in ('', 'after')
     and l.slides->(jsonb_array_length(l.slides) - 2)->>'component' is distinct from 'passport-page';
  if bad > 0 then raise exception 'guard 7: % beats are not right before the close', bad; end if;
  select count(*) into bad from schools.school_lessons l
   where l.teacher_notes->>'passport_stage' = 'after'
     and exists (select 1 from jsonb_array_elements(l.slides) sl where sl->>'component' = 'passport-page');
  if bad > 0 then raise exception 'guard 7: % modules after the passport carry a beat', bad; end if;
  select count(*) into bad from schools.school_lessons l, jsonb_array_elements(l.slides) sl
   where sl->>'type' = 'digi' and sl->>'heading' = 'The passport';
  if bad > 0 then raise exception 'guard 7: % old passport digi slides survived', bad; end if;

  raise notice '297 applied: % slides before, % after', total_before, total_after;
end $$;


drop table schools._m297;
