-- 326: the lesson review, batch 1 of 11: eyfs-01-screens-kindness, ks1-02-kind-screens-calm-bodies, ks1-03-real-pretend-computer
--
-- Generated by scripts/gen-review-batch.mjs from the verified findings in
-- ../../../tmp/claude-0/-home-user-guided-childhood/c93e2e38-cb42-5d4e-9d75-365c993da6a1/scratchpad/lesson-review/must-all. One reviewer and one verifier per lesson against
-- scripts/lesson-rubric.md; only edits the verifier accepted are here, and
-- every one was checked on the module JSON before this file was written:
-- exact current text, no dashes, inside the wall ceiling, every attested
-- phrase kept, the module contract no worse. The same checks run again below,
-- on the server, and any miss aborts the whole batch.
--
-- THE EDITS (7)
--   eyfs-01-screens-kindness s18 script [A4 must]: The script tells the teacher DiGi closes on the next slide, but the next slide is the passport page and DiGi Junior closes two slides on, so the presenter bar contradicts the wall order.
--   ks1-02-kind-screens-calm-bodies s18 script [A6 must]: The script says DiGi closes on the next slide, but the passport beat is next and DiGi Junior closes two slides on; a teacher reading the bar live is sent to the wrong beat.
--   ks1-02-kind-screens-calm-bodies s20 script [E9 must]: The bubbles appear on their own while the teacher hands out sheets, so a class that cannot yet read never hears the closing mission; and the exit sheets were already in hands at slide 14, so hand out the exit sheets is an instruction the teacher cannot follow.
--   ks1-03-real-pretend-computer s6 script [E21 must]: The player shuffles the options every run, so 'ask one pupil who chose the middle answer' points the teacher at a random option, and there is no think pause before hands go up.
--   ks1-03-real-pretend-computer s12 script [E28 must]: The verdict sort only counts the tap and flies the card away; it never shows a reason or marks the answer, so a teacher told to 'read the reason that appears' waits for text the wall never draws and the class gets no why.
--   ks1-03-real-pretend-computer s14 script [C2 must]: The script says these two wall checks are the printed quiz, but teacher_notes.exit_quiz prints five different items, and 'if anyone picks the third option' names a position the player shuffles; the popular wrong answer, the lesson's main misconception, is never named.
--   ks1-03-real-pretend-computer s15 script [E20 must]: 'If the class lands the first answer' names a position the player shuffles, and the script never says how everyone answers at once or gives a think pause.

begin;

create table schools.school_lessons_backup_326 as select * from schools.school_lessons;
alter table schools.school_lessons_backup_326 enable row level security;

create temp table miss(module text, target text);

-- One string on one slide, proven by the slide's type and heading and by its
-- exact current text. Anything else is a miss, and a miss aborts everything.
create or replace function schools.review_set_326(p_module text, p_pos int, p_ident text, p_path text[], p_expect text, p_new text)
returns void language plpgsql as $$
declare cur text; have text;
begin
  select (l.slides->p_pos->>'type') || ':' || coalesce(l.slides->p_pos->>'heading', l.slides->p_pos->>'title', l.slides->p_pos->>'question', l.slides->p_pos->>'prompt', l.slides->p_pos->>'component', '')
    into have from schools.school_lessons l where l.module_id = p_module;
  if have is distinct from p_ident then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' is ' || coalesce(have, 'absent') || ', expected ' || p_ident); return; end if;
  select l.slides #>> (array[p_pos::text] || p_path) into cur from schools.school_lessons l where l.module_id = p_module;
  if cur is null or cur <> p_expect then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' ' || array_to_string(p_path, '/') || ' is not the expected text'); return; end if;
  update schools.school_lessons l set slides = jsonb_set(l.slides, array[p_pos::text] || p_path, to_jsonb(p_new)) where l.module_id = p_module;
end $$;

-- eyfs-01-screens-kindness s18 script [A4]
select schools.review_set_326('eyfs-01-screens-kindness', 17, 'digi:Pebble''s job for you', array['script']::text[],
  'The handover. Say nothing over it. When the last line lands, ask them to look at you and say the mission once more in your own words. DiGi closes on the next slide.',
  'The handover. Say nothing over it. When the last line lands, ask them to look at you and say the mission once more in your own words. The passport page is next, and then DiGi Junior says goodbye.');

-- ks1-02-kind-screens-calm-bodies s18 script [A6]
select schools.review_set_326('ks1-02-kind-screens-calm-bodies', 17, 'digi:Pebble''s job for you', array['script']::text[],
  'The handover. Say nothing over it. When the last line lands, ask them to look at you and say the mission once more in your own words. DiGi closes on the next slide.',
  'The handover. Say nothing over it. When the last line lands, ask them to look at you and say the mission once more in your own words. The passport is next, then DiGi Junior closes.');

-- ks1-02-kind-screens-calm-bodies s20 script [E9]
select schools.review_set_326('ks1-02-kind-screens-calm-bodies', 19, 'digi:DiGi Junior says goodbye', array['script']::text[],
  'Let DiGi Junior land the ending, the speech bubbles appear on their own. While it plays, hand out the exit sheets to go home in book bags with the parent note. Wave goodbye to DiGi Junior together, they love it, and it seals the lesson.',
  'Let DiGi Junior land the ending, the speech bubbles appear on their own. Read each bubble aloud in your best DiGi Junior voice as it lands, because most of the class cannot read them yet. Then the parent note goes into book bags and the exit cards come in to you, as your evidence of who has got it. Wave goodbye to DiGi Junior together, they love it, and it seals the lesson.');

-- ks1-03-real-pretend-computer s6 script [E21]
select schools.review_set_326('ks1-03-real-pretend-computer', 5, 'choice:Warm up from last lesson. You have been watching videos and your tummy feels cross and wobbly. What does a screen time detective do?', array['script']::text[],
  'Retrieval from last lesson. Read all three out loud, then hands up for each one. Ask one pupil who chose the middle answer: who is YOUR grown up you would tell? Celebrate the answer. Then bridge: today we get a brand new detective question, and it is about pictures.',
  'Retrieval from last lesson, Pebble''s three steps. Read all three out loud, give thinking time with hands down, then hands up for each one. The options shuffle on the wall, so name the answer rather than its place. Ask one pupil who chose feel it, name it, tell a grown up: who is YOUR grown up you would tell? Celebrate the answer. Then bridge: today Pebble has a brand new detective question, and it is about pictures.');

-- ks1-03-real-pretend-computer s12 script [E28]
select schools.review_set_326('ks1-03-real-pretend-computer', 11, 'interactive:verdict-sort', array['script']::text[],
  'Now we play detective together before the sheet. Read each card aloud with plenty of drama, take hands up for real, pretend or computer made, then tap the class answer and read the reason that appears. If the class picks wrong, do not correct them flatly, read the reason and ask what they think now.',
  'Now we play detective together before the sheet. Read each card aloud with plenty of drama, take hands up for real, pretend or computer made, then tap the class answer. The wall counts the votes, it does not mark them, so the verdict and the reason are yours to say. The answers: the football photo is real, the cartoon mouse is pretend, the dog on the moon is computer made, the rainbow is real, the purple elephant is computer made, and Pebble''s flying cat is computer made, because looking clear is not proof. If the class picks wrong, do not correct them flatly: give the reason and ask what they think now.');

-- ks1-03-real-pretend-computer s14 script [C2]
select schools.review_set_326('ks1-03-real-pretend-computer', 13, 'choice:Exit check one. You see a photo of a cat flying with big feathery wings. It looks just like a real photo. What does a detective do?', array['script']::text[],
  'First of two exit checks, these two are the printed quiz too. Read all three options aloud, thinking time, then vote. If anyone picks the third option, reassure warmly: made up pictures are not scary, they can be brilliant, we just ask the question first.',
  'First of two exit checks on the wall; the printed exit quiz in your pack asks its own questions. Read all three options aloud, thinking time, then vote. The options shuffle, so watch for the answer, not the position. The popular wrong answer is believe it because it looks real, the lesson''s main misconception, so give that feedback line in full. If anyone picks feel scared, reassure warmly: made up pictures are not scary, they can be brilliant, we just ask the question first.');

-- ks1-03-real-pretend-computer s15 script [E20]
select schools.review_set_326('ks1-03-real-pretend-computer', 14, 'choice:Exit check two. Are computer made pictures always naughty?', array['script']::text[],
  'Second exit check, two options only. This is the big feeling of the lesson: no fear, just smart. If the class lands the first answer, celebrate: you are officially picture detectives. Wrong answers tell you exactly who needs a small group replay of the diagram slide next time.',
  'Second exit check, two options only. Read both aloud, thinking time, then everyone votes with fingers: one finger for no, they can be fun, two fingers for yes, all bad. This is the big feeling of the lesson: no fear, just smart. If the class lands on no, they can be fun, celebrate: you are officially picture detectives. Wrong answers tell you exactly who needs a small group replay of the diagram slide next time.');

do $$
declare n int; list text;
begin
  select count(*), string_agg(module || ' / ' || target, '; ') into n, list from miss;
  if n > 0 then raise exception 'MIGRATION ABORTED. % target(s) not as expected: %', n, list; end if;
end $$;

-- ── the proof: nothing on the wall is over its ceiling ───────────────────
-- The same rule the council runs (scripts/council-checks.mjs).
do $$
declare cnt int; list text;
begin
  with s as (
    select l.module_id, l.key_stage, e.ord as sn, e.slide
    from schools.school_lessons l, jsonb_array_elements(l.slides) with ordinality e(slide, ord)
  ), prose as (
    select module_id, key_stage, sn,
      case slide->>'type'
        when 'title' then concat_ws(' ', slide->>'title', slide->>'body')
        when 'concept' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'tryit' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'recap' then slide->>'heading'
        when 'keywords' then slide->>'heading'
        when 'digi' then slide->>'heading'
        when 'diagram' then concat_ws(' ', slide->>'heading', slide->>'caption')
        else null end as text
    from s
  ), over as (
    select module_id, sn, array_length(regexp_split_to_array(btrim(text), '\s+'), 1) as words
    from prose where text is not null
      and array_length(regexp_split_to_array(btrim(text), '\s+'), 1) > case key_stage when 'EYFS' then 12 when 'KS1' then 12 else 105 end
  )
  select count(*), string_agg(module_id || ' s' || sn || ' (' || words || ')', '; ') into cnt, list from over;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % slide(s) still over the wall ceiling: %', cnt, list; end if;
end $$;

-- ── the proof: every attested phrase the batch's modules are named on still holds ──
-- 28 phrase checks (shared/schools-rshe-2026.ts, mode any: at least one of
-- the requirement's modules carries it; shared/schools-computing-pos.ts, mode all:
-- every named module carries it), the same lower(text) test the two guards run.
do $$
declare cnt int; list text;
begin
  with probe(rid, phrase, mods, mode) as (values
    ('RSHE-P-OSA-1', 'same kind words', array['ks1-02-kind-screens-calm-bodies','ks2-07-privacy-reputation','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-OSA-1', 'screen words are still real words', array['ks1-02-kind-screens-calm-bodies','ks2-07-privacy-reputation','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-OSA-1', 'cannot see who is talking to you', array['ks1-02-kind-screens-calm-bodies','ks2-07-privacy-reputation','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-OSA-2', 'real, pretend', array['ks1-03-real-pretend-computer','ks2-07-privacy-reputation','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-OSA-2', 'never met', array['ks1-03-real-pretend-computer','ks2-07-privacy-reputation','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-OSA-2', 'anybody can say they are anybody', array['ks1-03-real-pretend-computer','ks2-07-privacy-reputation','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-OSA-6', 'is this real', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-OSA-6', 'never in trouble for telling', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-WO-1', 'brilliant things in it and rubbish things in it', array['ks2-04-screen-routines','eyfs-01-screens-kindness']::text[], 'any'),
    ('RSHE-P-WO-3', 'screen time', array['ks1-02-kind-screens-calm-bodies','ks2-04-screen-routines']::text[], 'any'),
    ('RSHE-P-WO-3', 'bedtime', array['ks1-02-kind-screens-calm-bodies','ks2-04-screen-routines']::text[], 'any'),
    ('RSHE-P-WO-4', 'how it feels to send', array['ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-WO-4', 'kind words', array['ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-WO-7', 'does not make it real', array['eyfs-01-screens-kindness','ks1-03-real-pretend-computer','ks2-06-how-algorithms-work']::text[], 'any'),
    ('RSHE-P-WO-7', 'detective', array['eyfs-01-screens-kindness','ks1-03-real-pretend-computer','ks2-06-how-algorithms-work']::text[], 'any'),
    ('RSHE-P-WO-11', 'tell a grown up', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-WO-11', 'report button and a block button', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-BS-2', 'secret', array['ks1-02-kind-screens-calm-bodies','ks2-07-privacy-reputation']::text[], 'any'),
    ('RSHE-P-BS-6', 'feel it, name it', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-BS-6', 'tell someone who can help', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-GW-9', 'trusted grown up', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-GW-9', 'will not go away by itself', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-GW-9', 'keep it secret', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-GW-9', 'whose actual job is this', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('CPOS-KS1-6', 'is this real', array['eyfs-01-screens-kindness']::text[], 'all'),
    ('CPOS-KS1-6', 'tell a grown up', array['ks1-02-kind-screens-calm-bodies','ks1-03-real-pretend-computer']::text[], 'all'),
    ('CPOS-KS1-6', 'never in trouble for telling', array['ks1-02-kind-screens-calm-bodies']::text[], 'all'),
    ('CPOS-KS2-5', 'detective', array['ks1-03-real-pretend-computer','ks2-06-how-algorithms-work']::text[], 'all')
  ), sl as (select l.module_id, lower(l.slides::text) as txt from schools.school_lessons l),
  per as (select p.rid, p.phrase, p.mode, m as module_id, coalesce(position(lower(p.phrase) in sl.txt) > 0, false) as hit
    from probe p, unnest(p.mods) m left join sl on sl.module_id = m),
  bad as (
    select rid, phrase, module_id from per where mode = 'all' and not hit
    union all
    select rid, phrase, null::text from per where mode = 'any' group by rid, phrase having not bool_or(hit))
  select count(*), string_agg(rid || ': ' || phrase || coalesce(' in ' || module_id, ''), '; ') into cnt, list from bad;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % attested phrase(s) lost: %', cnt, list; end if;
end $$;

-- ── the proof: eyfs-01-screens-kindness equals content/modules/eyfs-01-screens-kindness.json ──
-- 326_must_findings_1
--
-- eyfs-01-screens-kindness was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/326_must_findings_1.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 20 slides, 322 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'eyfs-01-screens-kindness' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'eyfs-01-screens-kindness' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'eyfs-01-screens-kindness' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'eyfs-01-screens-kindness' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'eyfs-01-screens-kindness' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'eyfs-01-screens-kindness' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'eyfs-01-screens-kindness'
  union all
  select title from schools.school_lessons where module_id = 'eyfs-01-screens-kindness'
  union all
  select key_stage from schools.school_lessons where module_id = 'eyfs-01-screens-kindness'
  union all
  select year_band from schools.school_lessons where module_id = 'eyfs-01-screens-kindness'
  union all
  select audience from schools.school_lessons where module_id = 'eyfs-01-screens-kindness'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'eyfs-01-screens-kindness'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'eyfs-01-screens-kindness'
  union all
  select character_cast from schools.school_lessons where module_id = 'eyfs-01-screens-kindness'
  union all
  select scaffold from schools.school_lessons where module_id = 'eyfs-01-screens-kindness'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'eyfs-01-screens-kindness'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'eyfs-01-screens-kindness'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'eyfs-01-screens-kindness';
  if got_slides is distinct from 20
     or got_n is distinct from 322
     or got_hash is distinct from '620d8c70404e93af7ef2bd349300d7a4' then
    raise exception '326_must_findings_1: eyfs-01-screens-kindness is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

-- ── the proof: ks1-02-kind-screens-calm-bodies equals content/modules/ks1-02-kind-screens-calm-bodies.json ──
-- 326_must_findings_1
--
-- ks1-02-kind-screens-calm-bodies was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/326_must_findings_1.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 20 slides, 308 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks1-02-kind-screens-calm-bodies' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks1-02-kind-screens-calm-bodies' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks1-02-kind-screens-calm-bodies' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks1-02-kind-screens-calm-bodies' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks1-02-kind-screens-calm-bodies' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks1-02-kind-screens-calm-bodies' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks1-02-kind-screens-calm-bodies'
  union all
  select title from schools.school_lessons where module_id = 'ks1-02-kind-screens-calm-bodies'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks1-02-kind-screens-calm-bodies'
  union all
  select year_band from schools.school_lessons where module_id = 'ks1-02-kind-screens-calm-bodies'
  union all
  select audience from schools.school_lessons where module_id = 'ks1-02-kind-screens-calm-bodies'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks1-02-kind-screens-calm-bodies'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks1-02-kind-screens-calm-bodies'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks1-02-kind-screens-calm-bodies'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks1-02-kind-screens-calm-bodies'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks1-02-kind-screens-calm-bodies'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks1-02-kind-screens-calm-bodies'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks1-02-kind-screens-calm-bodies';
  if got_slides is distinct from 20
     or got_n is distinct from 308
     or got_hash is distinct from '9735cc96c6f91068d999543077562658' then
    raise exception '326_must_findings_1: ks1-02-kind-screens-calm-bodies is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

-- ── the proof: ks1-03-real-pretend-computer equals content/modules/ks1-03-real-pretend-computer.json ──
-- 326_must_findings_1
--
-- ks1-03-real-pretend-computer was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/326_must_findings_1.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 20 slides, 337 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks1-03-real-pretend-computer' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks1-03-real-pretend-computer' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks1-03-real-pretend-computer' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks1-03-real-pretend-computer' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks1-03-real-pretend-computer' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks1-03-real-pretend-computer' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks1-03-real-pretend-computer'
  union all
  select title from schools.school_lessons where module_id = 'ks1-03-real-pretend-computer'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks1-03-real-pretend-computer'
  union all
  select year_band from schools.school_lessons where module_id = 'ks1-03-real-pretend-computer'
  union all
  select audience from schools.school_lessons where module_id = 'ks1-03-real-pretend-computer'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks1-03-real-pretend-computer'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks1-03-real-pretend-computer'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks1-03-real-pretend-computer'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks1-03-real-pretend-computer'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks1-03-real-pretend-computer'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks1-03-real-pretend-computer'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks1-03-real-pretend-computer';
  if got_slides is distinct from 20
     or got_n is distinct from 337
     or got_hash is distinct from 'f2028cd85e3f53927d82d6861e38de4b' then
    raise exception '326_must_findings_1: ks1-03-real-pretend-computer is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

commit;
