-- 327: the lesson review, batch 2 of 11: ks2-04-screen-routines, ks2-05-gaming-time-spend
--
-- Generated by scripts/gen-review-batch.mjs from the verified findings in
-- ../../../tmp/claude-0/-home-user-guided-childhood/c93e2e38-cb42-5d4e-9d75-365c993da6a1/scratchpad/lesson-review/must-all. One reviewer and one verifier per lesson against
-- scripts/lesson-rubric.md; only edits the verifier accepted are here, and
-- every one was checked on the module JSON before this file was written:
-- exact current text, no dashes, inside the wall ceiling, every attested
-- phrase kept, the module contract no worse. The same checks run again below,
-- on the server, and any miss aborts the whole batch.
--
-- THE EDITS (8)
--   ks2-04-screen-routines s6 options/0/text [E17 must]: The retrieval asks what we learned to ask last time, but the previous module (ks1-03) taught the detective question 'Real, pretend, or computer made? Ask before you believe', so a child who did that lesson cannot find the words they learned and retrieval practice retrieves nothing.
--   ks2-04-screen-routines s6 options/0/feedback [E28 must]: The feedback must explain the corrected answer in the previous lesson's own terms: the WOW picture is the one to ask the detective question about, because a computer made picture can look just like a photo.
--   ks2-04-screen-routines s6 script [E17 must]: The script tells the teacher that 'could this picture be made' was the whole of last lesson in seven words, which contradicts what ks1-03 actually chanted and now contradicts the corrected option on the wall.
--   ks2-04-screen-routines s9 script [E20 must]: The script tells the teacher to watch for 'the second answer', but the player shuffles the options every run so the second line on the wall is a different answer each time; it also never says how the whole class answers and has no think pause.
--   ks2-04-screen-routines s14 script [E20 must]: The script says 'the third option matters' on a wall that shuffles its options, so the teacher is pointed at the wrong line; it also gives no whole class answer method and no think pause.
--   ks2-04-screen-routines s19 script [E20 must]: The script names 'the third option' on a wall that shuffles its options, and never says how everyone answers or gives a think pause.
--   ks2-04-screen-routines s19 question [E26 must]: The question asks when to run the lap, but the lap is run when the warning fires, which is the mid round distractor; the item and its feedback are about when to decide the lap, so as written a careful child has two defensible answers.
--   ks2-05-gaming-time-spend s5 script [C2 must]: The script tells the teacher that two goes meaning double luck is a misconception, but two chests at 1 in 100 really is about two chances in a hundred, so a teacher following it would correct a child who is right; the real misconception is that enough goes make a win certain or that a win is owed.

begin;

create table schools.school_lessons_backup_327 as select * from schools.school_lessons;
alter table schools.school_lessons_backup_327 enable row level security;

create temp table miss(module text, target text);

-- One string on one slide, proven by the slide's type and heading and by its
-- exact current text. Anything else is a miss, and a miss aborts everything.
create or replace function schools.review_set_327(p_module text, p_pos int, p_ident text, p_path text[], p_expect text, p_new text)
returns void language plpgsql as $$
declare cur text; have text;
begin
  select (l.slides->p_pos->>'type') || ':' || coalesce(l.slides->p_pos->>'heading', l.slides->p_pos->>'title', l.slides->p_pos->>'question', l.slides->p_pos->>'prompt', l.slides->p_pos->>'component', '')
    into have from schools.school_lessons l where l.module_id = p_module;
  if have is distinct from p_ident then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' is ' || coalesce(have, 'absent') || ', expected ' || p_ident); return; end if;
  select l.slides #>> (array[p_pos::text] || p_path) into cur from schools.school_lessons l where l.module_id = p_module;
  if cur is null or cur <> p_expect then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' ' || array_to_string(p_path, '/') || ' is not the expected text'); return; end if;
  update schools.school_lessons l set slides = jsonb_set(l.slides, array[p_pos::text] || p_path, to_jsonb(p_new)) where l.module_id = p_module;
end $$;

-- ks2-04-screen-routines s6 options/0/text [E17]
select schools.review_set_327('ks2-04-screen-routines', 5, 'choice:Mission memory from last time. A game advert shows a prize that looks absolutely amazing. What did we learn to ask first?', array['options','0','text']::text[],
  'Could this picture be made or changed? Looking real is not the same as being real',
  'Real, pretend, or computer made?');

-- ks2-04-screen-routines s6 options/0/feedback [E28]
select schools.review_set_327('ks2-04-screen-routines', 5, 'choice:Mission memory from last time. A game advert shows a prize that looks absolutely amazing. What did we learn to ask first?', array['options','0','feedback']::text[],
  'That is the one. Pictures can be made or changed by a computer, so amazing looking is a reason to check, not a reason to believe.',
  'That is the detective question from last time. A WOW picture is exactly the one to ask it about, because a computer can make a picture that looks just like a photo.');

-- ks2-04-screen-routines s6 script [E17]
select schools.review_set_327('ks2-04-screen-routines', 5, 'choice:Mission memory from last time. A game advert shows a prize that looks absolutely amazing. What did we learn to ask first?', array['script']::text[],
  'Retrieval from the last module. Thirty seconds of thinking time before any hands. Cold call two pupils and ask for the reasoning, not just the answer. If the room is shaky on this, spend one extra minute: the question could this picture be made is the whole of last lesson in seven words.',
  'Retrieval from the last module. Thirty seconds of thinking time before any hands, then cold call two pupils and ask for the reasoning, not just the answer. If the room is shaky on this, spend one extra minute: real, pretend, or computer made, then ask before you believe, is the whole of last lesson in one line.');

-- ks2-04-screen-routines s9 script [E20]
select schools.review_set_327('ks2-04-screen-routines', 8, 'choice:Your five minute warning goes off right in the middle of a level. What does the cool down lap say to do?', array['script']::text[],
  'First check on the tool. Watch for pupils choosing the second answer because it sounds strict and therefore right, that is a really useful wrong answer to unpack: this module is not about stopping harder, it is about stopping smarter. The lap is kind to you on purpose, which is why it works.',
  'First check on the tool. Ten seconds of thinking time, hands down, then everyone holds up one, two or three fingers for the keycap number of their answer. Watch for pupils choosing the turn it off instantly option because it sounds strict and therefore right, that is a really useful wrong answer to unpack: this module is not about stopping harder, it is about stopping smarter. The lap is kind to you on purpose, which is why it works.');

-- ks2-04-screen-routines s14 script [E20]
select schools.review_set_327('ks2-04-screen-routines', 13, 'choice:Your phone is on silent under your pillow. Problem solved?', array['script']::text[],
  'The third option matters, some pupils will have heard scare stories about phones near heads. Be straight with them: we do not need scary made up reasons, the true reason is strong enough. Sleep displacement is real, measurable in how you feel tomorrow, and the fix costs nothing.',
  'Ten seconds of thinking time, then everyone holds up one, two or three fingers for the keycap number. The dangerous option matters: some pupils will have heard scare stories about phones near heads. Be straight with them: we do not need scary made up reasons, the true reason is strong enough. Sleep displacement is real, measurable in how you feel tomorrow, and the fix costs nothing.');

-- ks2-04-screen-routines s19 script [E20]
select schools.review_set_327('ks2-04-screen-routines', 18, 'choice:When is the smartest time to run the cool down lap on a school night?', array['script']::text[],
  'Last check before practice. The phrase to send them into the worksheet with: routines win battles before they begin. Get the class to repeat it once. If anyone picked the third option, do not scold it, name it as the most human answer on the slide, we have all made that promise, and that is exactly why the lap exists.',
  'Last check before practice. Ten seconds of thinking time, then everyone holds up one, two or three fingers for the keycap number. The phrase to send them into the worksheet with: routines win battles before they begin. Get the class to repeat it once. If anyone picked the promise to be sensible, do not scold it, name it as the most human answer on the slide, we have all made that promise, and that is exactly why the lap exists.');

-- ks2-04-screen-routines s19 question [E26]
select schools.review_set_327('ks2-04-screen-routines', 18, 'choice:When is the smartest time to run the cool down lap on a school night?', array['question']::text[],
  'When is the smartest time to run the cool down lap on a school night?',
  'When is the smartest time to decide your cool down lap on a school night?');

-- ks2-05-gaming-time-spend s5 script [C2]
select schools.review_set_327('ks2-05-gaming-time-spend', 4, 'keywords:Spotter words for today', array['script']::text[],
  'Say each word, class repeats it back. Pause on odds, it is the one they will not have met. Ask: if the odds are 1 in 100 and you open two chests, are you sure to win? Listen for the misconception that two goes means double luck. You do not need to fix it fully yet, the raffle slide later does that job.',
  'Say each word, class repeats it back. Pause on odds, it is the one they will not have met. Ask: if the odds are 1 in 100 and you open two chests, are you sure to win? No. Two chests is about two chances in a hundred, so it is still nearly always nothing. Listen for the idea that enough goes make a win certain, or that a win is owed after a run of losses. You do not need to fix it fully yet, the raffle slide later does that job.');

do $$
declare n int; list text;
begin
  select count(*), string_agg(module || ' / ' || target, '; ') into n, list from miss;
  if n > 0 then raise exception 'MIGRATION ABORTED. % target(s) not as expected: %', n, list; end if;
end $$;

-- ── the proof: nothing on the wall is over its ceiling ───────────────────
-- The same rule the council runs (scripts/council-checks.mjs).
do $$
declare cnt int; list text;
begin
  with s as (
    select l.module_id, l.key_stage, e.ord as sn, e.slide
    from schools.school_lessons l, jsonb_array_elements(l.slides) with ordinality e(slide, ord)
  ), prose as (
    select module_id, key_stage, sn,
      case slide->>'type'
        when 'title' then concat_ws(' ', slide->>'title', slide->>'body')
        when 'concept' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'tryit' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'recap' then slide->>'heading'
        when 'keywords' then slide->>'heading'
        when 'digi' then slide->>'heading'
        when 'diagram' then concat_ws(' ', slide->>'heading', slide->>'caption')
        else null end as text
    from s
  ), over as (
    select module_id, sn, array_length(regexp_split_to_array(btrim(text), '\s+'), 1) as words
    from prose where text is not null
      and array_length(regexp_split_to_array(btrim(text), '\s+'), 1) > case key_stage when 'EYFS' then 12 when 'KS1' then 12 else 105 end
  )
  select count(*), string_agg(module_id || ' s' || sn || ' (' || words || ')', '; ') into cnt, list from over;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % slide(s) still over the wall ceiling: %', cnt, list; end if;
end $$;

-- ── the proof: every attested phrase the batch's modules are named on still holds ──
-- 12 phrase checks (shared/schools-rshe-2026.ts, mode any: at least one of
-- the requirement's modules carries it; shared/schools-computing-pos.ts, mode all:
-- every named module carries it), the same lower(text) test the two guards run.
do $$
declare cnt int; list text;
begin
  with probe(rid, phrase, mods, mode) as (values
    ('RSHE-P-WO-1', 'brilliant things in it and rubbish things in it', array['ks2-04-screen-routines','eyfs-01-screens-kindness']::text[], 'any'),
    ('RSHE-P-WO-3', 'screen time', array['ks1-02-kind-screens-calm-bodies','ks2-04-screen-routines']::text[], 'any'),
    ('RSHE-P-WO-3', 'bedtime', array['ks1-02-kind-screens-calm-bodies','ks2-04-screen-routines']::text[], 'any'),
    ('RSHE-P-WO-5', 'games carry numbers too', array['ks2-26-why-thirteen','ks2-05-gaming-time-spend']::text[], 'any'),
    ('RSHE-P-WO-5', 'gambling sites', array['ks2-26-why-thirteen','ks2-05-gaming-time-spend']::text[], 'any'),
    ('RSHE-P-WO-5', 'find the number, ask what it is for', array['ks2-26-why-thirteen','ks2-05-gaming-time-spend']::text[], 'any'),
    ('RSHE-P-WO-6', 'loot box', array['ks2-05-gaming-time-spend']::text[], 'any'),
    ('RSHE-P-WO-6', 'gambling machines work', array['ks2-05-gaming-time-spend']::text[], 'any'),
    ('RSHE-S-WO-4', 'loot box', array['ks4-28-the-money-and-the-odds','ks2-05-gaming-time-spend']::text[], 'any'),
    ('RSHE-S-WO-4', 'house edge', array['ks4-28-the-money-and-the-odds','ks2-05-gaming-time-spend']::text[], 'any'),
    ('RSHE-S-WO-4', 'how fast is the loop', array['ks4-28-the-money-and-the-odds','ks2-05-gaming-time-spend']::text[], 'any'),
    ('RSHE-S-WO-4', 'borrowing', array['ks4-28-the-money-and-the-odds','ks2-05-gaming-time-spend']::text[], 'any')
  ), sl as (select l.module_id, lower(l.slides::text) as txt from schools.school_lessons l),
  per as (select p.rid, p.phrase, p.mode, m as module_id, coalesce(position(lower(p.phrase) in sl.txt) > 0, false) as hit
    from probe p, unnest(p.mods) m left join sl on sl.module_id = m),
  bad as (
    select rid, phrase, module_id from per where mode = 'all' and not hit
    union all
    select rid, phrase, null::text from per where mode = 'any' group by rid, phrase having not bool_or(hit))
  select count(*), string_agg(rid || ': ' || phrase || coalesce(' in ' || module_id, ''), '; ') into cnt, list from bad;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % attested phrase(s) lost: %', cnt, list; end if;
end $$;

-- ── the proof: ks2-04-screen-routines equals content/modules/ks2-04-screen-routines.json ──
-- 327_must_findings_2
--
-- ks2-04-screen-routines was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/327_must_findings_2.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 29 slides, 395 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks2-04-screen-routines' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks2-04-screen-routines' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks2-04-screen-routines' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks2-04-screen-routines' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks2-04-screen-routines' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks2-04-screen-routines' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks2-04-screen-routines'
  union all
  select title from schools.school_lessons where module_id = 'ks2-04-screen-routines'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks2-04-screen-routines'
  union all
  select year_band from schools.school_lessons where module_id = 'ks2-04-screen-routines'
  union all
  select audience from schools.school_lessons where module_id = 'ks2-04-screen-routines'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks2-04-screen-routines'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks2-04-screen-routines'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks2-04-screen-routines'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks2-04-screen-routines'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks2-04-screen-routines'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks2-04-screen-routines'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks2-04-screen-routines';
  if got_slides is distinct from 29
     or got_n is distinct from 395
     or got_hash is distinct from '8ffb1e810e1af9fb8a31280442f8a8dc' then
    raise exception '327_must_findings_2: ks2-04-screen-routines is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

-- ── the proof: ks2-05-gaming-time-spend equals content/modules/ks2-05-gaming-time-spend.json ──
-- 327_must_findings_2
--
-- ks2-05-gaming-time-spend was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/327_must_findings_2.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 31 slides, 441 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks2-05-gaming-time-spend' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks2-05-gaming-time-spend' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks2-05-gaming-time-spend' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks2-05-gaming-time-spend' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks2-05-gaming-time-spend' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks2-05-gaming-time-spend' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks2-05-gaming-time-spend'
  union all
  select title from schools.school_lessons where module_id = 'ks2-05-gaming-time-spend'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks2-05-gaming-time-spend'
  union all
  select year_band from schools.school_lessons where module_id = 'ks2-05-gaming-time-spend'
  union all
  select audience from schools.school_lessons where module_id = 'ks2-05-gaming-time-spend'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks2-05-gaming-time-spend'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks2-05-gaming-time-spend'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks2-05-gaming-time-spend'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks2-05-gaming-time-spend'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks2-05-gaming-time-spend'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks2-05-gaming-time-spend'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks2-05-gaming-time-spend';
  if got_slides is distinct from 31
     or got_n is distinct from 441
     or got_hash is distinct from '28601ae5c2a11b21c233ed89b150d3bc' then
    raise exception '327_must_findings_2: ks2-05-gaming-time-spend is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

commit;
