-- 328: the lesson review, batch 3 of 11: ks2-06-how-algorithms-work, ks2-08-kind-safe-online
--
-- APPLIED 21 September 2026, inside the transaction recorded as
-- 327_to_329_must_findings. The eleven files in this batch went up in four
-- transactions, not eleven, so the pre batch snapshot is the single table
-- schools.school_lessons_backup_326 taken before the first edit, and the per
-- module hash proofs below ran afterwards as one query over all 26 changed
-- lessons: 26 of 26 byte identical to content/modules. Do not replay this
-- file on its own. Every edit guards on the exact text it is replacing, so a
-- replay aborts rather than writing twice, which is the point.
--
-- Generated by scripts/gen-review-batch.mjs from the verified findings in
-- ../../../tmp/claude-0/-home-user-guided-childhood/c93e2e38-cb42-5d4e-9d75-365c993da6a1/scratchpad/lesson-review/must-all. One reviewer and one verifier per lesson against
-- scripts/lesson-rubric.md; only edits the verifier accepted are here, and
-- every one was checked on the module JSON before this file was written:
-- exact current text, no dashes, inside the wall ceiling, every attested
-- phrase kept, the module contract no worse. The same checks run again below,
-- on the server, and any miss aborts the whole batch.
--
-- THE EDITS (10)
--   ks2-06-how-algorithms-work s22 body [E45 must]: The wall says six video cards each showing how a viewer behaved, but the printed sheet's sixth card is Teo's question, and the big question the wall names is not on the sheet at all, so a child scoring card six as a video or hunting for a question that is not there loses minutes of the practise.
--   ks2-06-how-algorithms-work s14 script [E21 must]: The script tells the teacher the misconception is option two, but the player shuffles the options every run, so the teacher names the wrong line to half the classes; and the script's only pause word is silence in a different sentence, so there is no real think pause.
--   ks2-06-how-algorithms-work s23 script [E20 must]: The exit check that IS the lesson outcome tells the teacher a pupil who picks the first option has met the objective, but the player shuffles the options, so the evidence is read off the wrong line; and the script names no whole class method and no think pause.
--   ks2-06-how-algorithms-work s9 script [E21 must]: The script says if anyone picks the third answer, but the player shuffles the options so the third line is different in every run; and there is no think pause before hands go up.
--   ks2-08-kind-safe-online s3 script [E47 must]: Two minutes after the title script promised nobody will be asked to share a story, this asks for hands up if you have ever seen someone being unkind, the disclosure pattern E47 forbids and a public decision for a child who is being bullied.
--   ks2-08-kind-safe-online s14 script [E21 must]: The script points at the third option, but the player shuffles options every run, so the teacher names the wrong line to most classes; and there is no think pause before hands go up.
--   ks2-08-kind-safe-online s24 script [E20 must]: The script calls the trap the second option, but the player shuffles options per run; it names no whole class method and no think pause on the exit check that is the lesson's evidence; and the printed exit quiz has five items, not these two.
--   ks2-08-kind-safe-online s20 script [E20 must]: The script says pupils will wrestle with option two, but the player shuffles options every run; and it passes E20 only by accident (everyone in another sentence) and never says how the whole class answers.
--   ks2-08-kind-safe-online s22 config/posts/5/text [C5 must]: Card six asks Do you agree? and offers only the three verdicts, none of which answers that, so the stored answer Pile on forming has no defensible mapping from the question; recast the claim as a situation so the verdict is what is happening and the why still carries Orbit's half right claim.
--   ks2-08-kind-safe-online s12 body [E12 must]: The attesting phrase for RSHE-P-WO-2, thinner than being with them, lives only in a recap body the player never draws, so the statutory point is on no wall a child sees; this slide explains why a joke lands harder than it was sent, so it is the phrase's home, and the same rewrite mends E12 (first appearance of both pile on and bystander) by leaving the bystander effect to the script, and softens usually breaks the spell to can, which is what the recap already says.

begin;

create table schools.school_lessons_backup_328 as select * from schools.school_lessons;
alter table schools.school_lessons_backup_328 enable row level security;

create temp table miss(module text, target text);

-- One string on one slide, proven by the slide's type and heading and by its
-- exact current text. Anything else is a miss, and a miss aborts everything.
create or replace function schools.review_set_328(p_module text, p_pos int, p_ident text, p_path text[], p_expect text, p_new text)
returns void language plpgsql as $$
declare cur text; have text;
begin
  select (l.slides->p_pos->>'type') || ':' || coalesce(l.slides->p_pos->>'heading', l.slides->p_pos->>'title', l.slides->p_pos->>'question', l.slides->p_pos->>'prompt', l.slides->p_pos->>'component', '')
    into have from schools.school_lessons l where l.module_id = p_module;
  if have is distinct from p_ident then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' is ' || coalesce(have, 'absent') || ', expected ' || p_ident); return; end if;
  select l.slides #>> (array[p_pos::text] || p_path) into cur from schools.school_lessons l where l.module_id = p_module;
  if cur is null or cur <> p_expect then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' ' || array_to_string(p_path, '/') || ' is not the expected text'); return; end if;
  update schools.school_lessons l set slides = jsonb_set(l.slides, array[p_pos::text] || p_path, to_jsonb(p_new)) where l.module_id = p_module;
end $$;

-- ks2-06-how-algorithms-work s22 body [E45]
select schools.review_set_328('ks2-06-how-algorithms-work', 21, 'tryit:Be the algorithm, on paper', array['body']::text[],
  'Your teacher has six video cards on the worksheet, each showing how a viewer behaved: watched to the end, rewatched, liked, paused or skipped. YOU are the algorithm. Use the scoring rules on the sheet to score every card, then give each one a verdict: serve more, show sometimes, or bury it. Fifteen minutes. When you finish, answer the big question at the bottom: what has this feed learned about its viewer, and did the viewer mean to teach it?',
  'Your teacher has six cards on the worksheet. Five show how a viewer behaved: watched to the end, rewatched, liked, paused or skipped. YOU are the algorithm. Use the scoring rules on the sheet to score those five, then give each one a verdict: serve more, show sometimes, or bury it. Card six is the big question: Teo says the app is being kind to him. Use the feed loop to say whether you agree. Fifteen minutes.');

-- ks2-06-how-algorithms-work s14 script [E21]
select schools.review_set_328('ks2-06-how-algorithms-work', 13, 'choice:You watch a skateboard fail video right to the end and rewatch the crash twice. What does the feed loop do next?', array['script']::text[],
  'Quick loop check, hands or devices. The misconception to smash here is option two: loads of pupils believe that if they never like anything, the feed learns nothing. Say it plainly: silence is not invisibility. Watch time talks even when your thumbs stay still.',
  'Quick loop check, hands or devices. Ten seconds of thinking time, hands down, then everyone shows at once. The misconception to catch here is the nothing because you did not press like answer: loads of pupils believe that if they never like anything, the feed learns nothing. Say it plainly: silence is not invisibility. Watch time talks even when your thumbs stay still.');

-- ks2-06-how-algorithms-work s23 script [E20]
select schools.review_set_328('ks2-06-how-algorithms-work', 22, 'choice:Exit check one. Your feed has become wall to wall football videos. What is the honest explanation?', array['script']::text[],
  'First of two exit checks and this one IS the lesson outcome, so treat it as your evidence. Silent, independent answers. A pupil who picks the first option and can mutter the loop chant has met the objective. Anyone on mind reading needs the diagram slide again, the back button works.',
  'First of two exit checks and this one IS the lesson outcome, so treat it as your evidence. Everyone answers on their own device or whiteboard, no talking, twenty seconds of thinking time before anyone taps. A pupil who picks the loop answer and can say the chant has met the objective. Anyone on mind reading needs the diagram slide again, the back button works.');

-- ks2-06-how-algorithms-work s9 script [E21]
select schools.review_set_328('ks2-06-how-algorithms-work', 8, 'choice:Which of these is closest to what an algorithm really is?', array['script']::text[],
  'Quick check, hands or devices. If anyone picks the third answer, celebrate the suspicion but sharpen it: an algorithm is a tool, like a recipe. A recipe can make a birthday cake or something horrible. The question is always what result the steps are chasing. Perfect setup for the next slide.',
  'Quick check, hands or devices. Ten seconds of thinking time first, then everyone shows at once. If anyone picks the sneaky trick answer, celebrate the suspicion but sharpen it: an algorithm is a tool, like a recipe. A recipe can make a birthday cake or something horrible. The question is always what result the steps are chasing. Perfect setup for the next slide.');

-- ks2-08-kind-safe-online s3 script [E47]
select schools.review_set_328('ks2-08-kind-safe-online', 2, 'objective:', array['script']::text[],
  'Read the mission out loud, then the why. Ask: hands up if you have ever seen someone being unkind in a group chat or under a photo. Most hands will go up, and that is the point. Say: so this lesson is not about IF it happens. It is about what the squad does WHEN it happens. Keep it brisk and warm, no stories collected here.',
  'Read the mission out loud, then the why. Ask: hands up if you think unkindness in a group chat or under a photo happens somewhere in this school every week. Most hands will go up, and that is the point. Say: so this lesson is not about IF it happens. It is about what the squad does WHEN it happens. Keep it brisk and warm, no stories collected here.');

-- ks2-08-kind-safe-online s14 script [E21]
select schools.review_set_328('ks2-08-kind-safe-online', 13, 'choice:The pile on about Ravi is growing. Which is the strongest upstander move you could make right now?', array['script']::text[],
  'Whole class, hands or devices. The third option is the important one to unpack: lots of kind pupils believe staying silent keeps them innocent. Handle it gently, no shame, because plenty in the room have done exactly that. Say: staying out of it is better than joining in, AND the squad can do better than better. Which sets up the tool of the whole module, coming next.',
  'Whole class, hands or devices, after ten seconds of thinking time with no hands up. The watch quietly option is the important one to unpack: lots of kind pupils believe staying silent keeps them innocent. Handle it gently, no shame, because plenty in the room have done exactly that. Say: staying out of it is better than joining in, AND the squad can do better than better. Which sets up the tool of the whole module, coming next.');

-- ks2-08-kind-safe-online s24 script [E20]
select schools.review_set_328('ks2-08-kind-safe-online', 23, 'choice:Exit check. Unkind posts about one pupil are stacking up in a group chat. What are the three moves?', array['script']::text[],
  'First of two exit checks, and these two are the printed exit quiz, so no hints. The second option is the clever trap: it starts with a screenshot so it sounds like move two. The difference is where the evidence goes. A wrong answer here tells you exactly who to revisit the diagram with.',
  'First of two exit checks, and both are on the printed exit quiz, so no hints. Fifteen seconds of silent thinking, then everyone shows fingers at once: one, two or three. The send it round option is the clever trap: it starts with a screenshot so it sounds like move two. The difference is where the evidence goes. A wrong answer here tells you exactly who to revisit the diagram with.');

-- ks2-08-kind-safe-online s20 script [E20]
select schools.review_set_328('ks2-08-kind-safe-online', 19, 'choice:A friend shows you nasty messages they keep getting every night, then says: promise you will not tell anyone. What do the three moves say?', array['script']::text[],
  'The hardest question of the day because loyalty is sacred at this age. Thirty seconds thinking time. The feedback line to make sure everyone hears out loud: I am telling someone BECAUSE I am your friend. Some pupils will genuinely wrestle with option two, honour that, loyalty is a good instinct pointed at the wrong target here. This exact dilemma is item five on the worksheet, so it gets a second pass.',
  'The hardest question of the day because loyalty is sacred at this age. Thirty seconds thinking time, then everyone votes with fingers, one, two or three. The feedback line to make sure everyone hears out loud: I am telling someone BECAUSE I am your friend. Some pupils will genuinely wrestle with the keep the secret option, honour that, loyalty is a good instinct pointed at the wrong target here. This exact dilemma is item five on the worksheet, so it gets a second pass.');

-- ks2-08-kind-safe-online s22 config/posts/5/text [C5]
select schools.review_set_328('ks2-08-kind-safe-online', 21, 'interactive:verdict-sort', array['config','posts','5','text']::text[],
  'Orbit says: if you just watch a pile on and never type anything, you have done nothing wrong. Do you agree? Explain your reasoning.',
  'Orbit is in a group chat where a pile on has started, reads every message and never types anything. Orbit says: I did nothing, so I have done nothing wrong. What is happening, and is Orbit right?');

-- ks2-08-kind-safe-online s12 body [E12]
select schools.review_set_328('ks2-08-kind-safe-online', 11, 'concept:Why pile ons grow', array['body']::text[],
  'To each person joining in, one laughing emoji feels tiny, barely anything at all. To Ravi, it is not one emoji, it is fourteen people laughing at once, and it is still there every time he opens his phone. Pile ons grow because of a strange trick our brains play called the bystander effect: when lots of people are watching, everyone waits for someone else to be the one who acts. And here is the secret the pile on does not want you to know: it is performing for its audience, so the very first kind move usually breaks the spell.',
  'To each person joining in, one laughing emoji feels tiny. To Ravi, it is fourteen people laughing at once, there every time he opens his phone. Talking online is real talking, but it is thinner than being with them: a screen carries your words and drops your face and voice, so a joke lands harder than it was sent. Pile ons grow because of a trick our brains play: when lots of people are watching, everyone waits for someone else to act. The pile on is performing for its audience, so the first kind move can break the spell.');

do $$
declare n int; list text;
begin
  select count(*), string_agg(module || ' / ' || target, '; ') into n, list from miss;
  if n > 0 then raise exception 'MIGRATION ABORTED. % target(s) not as expected: %', n, list; end if;
end $$;

-- ── the proof: nothing on the wall is over its ceiling ───────────────────
-- The same rule the council runs (scripts/council-checks.mjs).
do $$
declare cnt int; list text;
begin
  with s as (
    select l.module_id, l.key_stage, e.ord as sn, e.slide
    from schools.school_lessons l, jsonb_array_elements(l.slides) with ordinality e(slide, ord)
  ), prose as (
    select module_id, key_stage, sn,
      case slide->>'type'
        when 'title' then concat_ws(' ', slide->>'title', slide->>'body')
        when 'concept' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'tryit' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'recap' then slide->>'heading'
        when 'keywords' then slide->>'heading'
        when 'digi' then slide->>'heading'
        when 'diagram' then concat_ws(' ', slide->>'heading', slide->>'caption')
        else null end as text
    from s
  ), over as (
    select module_id, sn, array_length(regexp_split_to_array(btrim(text), '\s+'), 1) as words
    from prose where text is not null
      and array_length(regexp_split_to_array(btrim(text), '\s+'), 1) > case key_stage when 'EYFS' then 12 when 'KS1' then 12 else 105 end
  )
  select count(*), string_agg(module_id || ' s' || sn || ' (' || words || ')', '; ') into cnt, list from over;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % slide(s) still over the wall ceiling: %', cnt, list; end if;
end $$;

-- ── the proof: every attested phrase the batch's modules are named on still holds ──
-- 37 phrase checks (shared/schools-rshe-2026.ts, mode any: at least one of
-- the requirement's modules carries it; shared/schools-computing-pos.ts, mode all:
-- every named module carries it), the same lower(text) test the two guards run.
do $$
declare cnt int; list text;
begin
  with probe(rid, phrase, mods, mode) as (values
    ('RSHE-P-OSA-1', 'same kind words', array['ks1-02-kind-screens-calm-bodies','ks2-07-privacy-reputation','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-OSA-1', 'screen words are still real words', array['ks1-02-kind-screens-calm-bodies','ks2-07-privacy-reputation','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-OSA-1', 'cannot see who is talking to you', array['ks1-02-kind-screens-calm-bodies','ks2-07-privacy-reputation','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-OSA-2', 'real, pretend', array['ks1-03-real-pretend-computer','ks2-07-privacy-reputation','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-OSA-2', 'never met', array['ks1-03-real-pretend-computer','ks2-07-privacy-reputation','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-OSA-2', 'anybody can say they are anybody', array['ks1-03-real-pretend-computer','ks2-07-privacy-reputation','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-OSA-6', 'is this real', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-OSA-6', 'never in trouble for telling', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-WO-2', 'thinner than being with them', array['ks2-08-kind-safe-online','ks2-23-when-a-machine-talks-like-a-friend']::text[], 'any'),
    ('RSHE-P-WO-4', 'how it feels to send', array['ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-WO-4', 'kind words', array['ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-WO-7', 'does not make it real', array['eyfs-01-screens-kindness','ks1-03-real-pretend-computer','ks2-06-how-algorithms-work']::text[], 'any'),
    ('RSHE-P-WO-7', 'detective', array['eyfs-01-screens-kindness','ks1-03-real-pretend-computer','ks2-06-how-algorithms-work']::text[], 'any'),
    ('RSHE-P-WO-8', 'pile on', array['ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-WO-8', 'bullying', array['ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-WO-9', 'algorithm', array['ks2-06-how-algorithms-work']::text[], 'any'),
    ('RSHE-P-WO-9', 'search boxes follow a recipe', array['ks2-06-how-algorithms-work']::text[], 'any'),
    ('RSHE-P-WO-9', 'first does not mean truest', array['ks2-06-how-algorithms-work']::text[], 'any'),
    ('RSHE-P-WO-11', 'tell a grown up', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-WO-11', 'report button and a block button', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-RKR-9', 'pile on', array['ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-RKR-9', 'one unkind moment', array['ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-BS-6', 'feel it, name it', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-BS-6', 'tell someone who can help', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-GW-7', 'bullying', array['ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-GW-9', 'trusted grown up', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-GW-9', 'will not go away by itself', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-GW-9', 'keep it secret', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-P-GW-9', 'whose actual job is this', array['eyfs-01-screens-kindness','ks1-02-kind-screens-calm-bodies','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-S-RR-6', 'bystander', array['ks3-27-when-it-turns-on-you','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-S-RR-6', 'the quiet majority is the whole audience', array['ks3-27-when-it-turns-on-you','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-S-RR-6', 'bullying is repeated, aimed at one person', array['ks3-27-when-it-turns-on-you','ks2-08-kind-safe-online']::text[], 'any'),
    ('CPOS-KS2-5', 'search boxes follow a recipe', array['ks2-06-how-algorithms-work']::text[], 'all'),
    ('CPOS-KS2-5', 'first does not mean truest', array['ks2-06-how-algorithms-work']::text[], 'all'),
    ('CPOS-KS2-5', 'detective', array['ks1-03-real-pretend-computer','ks2-06-how-algorithms-work']::text[], 'all'),
    ('CPOS-KS2-7', 'report button and a block button', array['ks2-08-kind-safe-online']::text[], 'all'),
    ('CPOS-KS2-7', 'bullying', array['ks2-08-kind-safe-online']::text[], 'all')
  ), sl as (select l.module_id, lower(l.slides::text) as txt from schools.school_lessons l),
  per as (select p.rid, p.phrase, p.mode, m as module_id, coalesce(position(lower(p.phrase) in sl.txt) > 0, false) as hit
    from probe p, unnest(p.mods) m left join sl on sl.module_id = m),
  bad as (
    select rid, phrase, module_id from per where mode = 'all' and not hit
    union all
    select rid, phrase, null::text from per where mode = 'any' group by rid, phrase having not bool_or(hit))
  select count(*), string_agg(rid || ': ' || phrase || coalesce(' in ' || module_id, ''), '; ') into cnt, list from bad;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % attested phrase(s) lost: %', cnt, list; end if;
end $$;

-- ── the proof: ks2-06-how-algorithms-work equals content/modules/ks2-06-how-algorithms-work.json ──
-- 328_must_findings_3
--
-- ks2-06-how-algorithms-work was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/328_must_findings_3.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 29 slides, 375 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks2-06-how-algorithms-work' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks2-06-how-algorithms-work' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks2-06-how-algorithms-work' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks2-06-how-algorithms-work' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks2-06-how-algorithms-work' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks2-06-how-algorithms-work' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks2-06-how-algorithms-work'
  union all
  select title from schools.school_lessons where module_id = 'ks2-06-how-algorithms-work'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks2-06-how-algorithms-work'
  union all
  select year_band from schools.school_lessons where module_id = 'ks2-06-how-algorithms-work'
  union all
  select audience from schools.school_lessons where module_id = 'ks2-06-how-algorithms-work'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks2-06-how-algorithms-work'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks2-06-how-algorithms-work'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks2-06-how-algorithms-work'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks2-06-how-algorithms-work'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks2-06-how-algorithms-work'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks2-06-how-algorithms-work'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks2-06-how-algorithms-work';
  if got_slides is distinct from 29
     or got_n is distinct from 375
     or got_hash is distinct from '17286e8177a99f1c9d30bb1fcc4621f6' then
    raise exception '328_must_findings_3: ks2-06-how-algorithms-work is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

-- ── the proof: ks2-08-kind-safe-online equals content/modules/ks2-08-kind-safe-online.json ──
-- 328_must_findings_3
--
-- ks2-08-kind-safe-online was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/328_must_findings_3.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 30 slides, 431 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks2-08-kind-safe-online' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks2-08-kind-safe-online' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks2-08-kind-safe-online' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks2-08-kind-safe-online' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks2-08-kind-safe-online' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks2-08-kind-safe-online' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks2-08-kind-safe-online'
  union all
  select title from schools.school_lessons where module_id = 'ks2-08-kind-safe-online'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks2-08-kind-safe-online'
  union all
  select year_band from schools.school_lessons where module_id = 'ks2-08-kind-safe-online'
  union all
  select audience from schools.school_lessons where module_id = 'ks2-08-kind-safe-online'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks2-08-kind-safe-online'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks2-08-kind-safe-online'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks2-08-kind-safe-online'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks2-08-kind-safe-online'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks2-08-kind-safe-online'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks2-08-kind-safe-online'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks2-08-kind-safe-online';
  if got_slides is distinct from 30
     or got_n is distinct from 431
     or got_hash is distinct from '12877629a1e1ace2a4adc77d62d3af75' then
    raise exception '328_must_findings_3: ks2-08-kind-safe-online is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

commit;
