-- 329: the lesson review, batch 4 of 11: ks2-09-copyright-ownership, ks3-10-mood-and-screens
--
-- APPLIED 21 September 2026, inside the transaction recorded as
-- 327_to_329_must_findings. The eleven files in this batch went up in four
-- transactions, not eleven, so the pre batch snapshot is the single table
-- schools.school_lessons_backup_326 taken before the first edit, and the per
-- module hash proofs below ran afterwards as one query over all 26 changed
-- lessons: 26 of 26 byte identical to content/modules. Do not replay this
-- file on its own. Every edit guards on the exact text it is replacing, so a
-- replay aborts rather than writing twice, which is the point.
--
-- Generated by scripts/gen-review-batch.mjs from the verified findings in
-- ../../../tmp/claude-0/-home-user-guided-childhood/c93e2e38-cb42-5d4e-9d75-365c993da6a1/scratchpad/lesson-review/must-all. One reviewer and one verifier per lesson against
-- scripts/lesson-rubric.md; only edits the verifier accepted are here, and
-- every one was checked on the module JSON before this file was written:
-- exact current text, no dashes, inside the wall ceiling, every attested
-- phrase kept, the module contract no worse. The same checks run again below,
-- on the server, and any miss aborts the whole batch.
--
-- THE EDITS (15)
--   ks2-09-copyright-ownership s6 options/0/text [E17 must]: The retrieval item asks for last lesson's three moves but the correct option quotes a tool ks2-08 never taught; its wall, chant and recap say do not pile on, save the evidence, tell someone who can help, so the class is marked wrong for remembering correctly.
--   ks2-09-copyright-ownership s6 options/0/feedback [E17 must]: The correct feedback explains three moves that are not ks2-08's three, so the retrieval rehearses the wrong tool and contradicts last lesson's diagram, where move three is an adult with moves pupils do not have.
--   ks2-09-copyright-ownership s6 options/1/feedback [E17 must]: The wrong option's feedback restates the three moves in words ks2-08 never used, so a child who picked wrongly is corrected towards a tool they were never taught.
--   ks2-09-copyright-ownership s6 options/2/feedback [E17 must]: Same fault as the other feedback: the three moves it restates are not the three moves ks2-08 put on the wall, the bookmark and the chant.
--   ks2-09-copyright-ownership s19 options/0/feedback [C1 must]: The feedback says the correct option is six words; I made this with an AI tool is seven, and a Year 4 class will count it on the wall. It also uses capitals for emphasis, which the BDA guide rules out for readers with dyslexia.
--   ks2-09-copyright-ownership s19 options/1/feedback [C1 must]: The feedback says the friend typed four words; the prompt on this slide, the concept and the diagram all say castle in space, which is three, so the feedback is wrong about the case in front of the class.
--   ks2-09-copyright-ownership s10 options/1/feedback [E29 must]: A child who picks Yes is told that is the excuse of someone who knows they took something, which blames the child for the pick rather than explaining the answer; feedback must be about the task, never the pupil.
--   ks2-09-copyright-ownership s27 script [A6 must]: The script tells the teacher DiGi closes on the next slide, but the next slide is the passport page and DiGi closes two slides on, so the teacher sets up a beat that does not come.
--   ks2-09-copyright-ownership s2 lines/2 [E40 must]: The script says to leave the question hanging and not answer it because the class talks before anyone is told, but Bloop's third line answers it on the wall; and Bloop never voices a struggle of its own, it explains like an adult.
--   ks2-09-copyright-ownership s26 script [A8 must]: The recap's body carries the only attested phrase for the personal data right, belong to you in exactly the way your drawing does, but the player draws a recap's heading and points only (RecapSlide has no body field), and no script says it, so the requirement is held by text no child sees or hears; the teacher's script should speak it until the wall can.
--   ks3-10-mood-and-screens s16 script [E21 must]: The script tells the teacher to watch the second option, but the player shuffles options every run, so the teacher names the wrong line to most classes; and there is no think pause before hands go up.
--   ks3-10-mood-and-screens s18 caption [C6 must]: Unlocks is on the banned AI phrasing list and it is on the wall in the caption of the lesson's action slide; a thirteen year old hears an advert, not a teacher.
--   ks3-10-mood-and-screens s18 heading [E1 must]: The heading says three moves while the wall draws four steps, the script says walk the four moves and the recap lists four; a child counts, and the heading names the idea wrongly.
--   ks3-10-mood-and-screens s21 script [E44 must]: The script contradicts the wall three ways: it says the audit takes five seconds where the title, the objective, the diagram and the caption all say ten; it says count hands where the SEND note says the tally is anonymous tokens, not hands up; and it states that nothing is the most common answer in real studies, a norm claim with no source anywhere in the lesson.
--   ks3-10-mood-and-screens s29 lines/1 [C3 must]: DiGi says the question is seven words long and then quotes eight (after I closed it, better, worse, or nothing), so the one line meant to fix the tool in memory carries a counting error a class will spot.

begin;

create table schools.school_lessons_backup_329 as select * from schools.school_lessons;
alter table schools.school_lessons_backup_329 enable row level security;

create temp table miss(module text, target text);

-- One string on one slide, proven by the slide's type and heading and by its
-- exact current text. Anything else is a miss, and a miss aborts everything.
create or replace function schools.review_set_329(p_module text, p_pos int, p_ident text, p_path text[], p_expect text, p_new text)
returns void language plpgsql as $$
declare cur text; have text;
begin
  select (l.slides->p_pos->>'type') || ':' || coalesce(l.slides->p_pos->>'heading', l.slides->p_pos->>'title', l.slides->p_pos->>'question', l.slides->p_pos->>'prompt', l.slides->p_pos->>'component', '')
    into have from schools.school_lessons l where l.module_id = p_module;
  if have is distinct from p_ident then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' is ' || coalesce(have, 'absent') || ', expected ' || p_ident); return; end if;
  select l.slides #>> (array[p_pos::text] || p_path) into cur from schools.school_lessons l where l.module_id = p_module;
  if cur is null or cur <> p_expect then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' ' || array_to_string(p_path, '/') || ' is not the expected text'); return; end if;
  update schools.school_lessons l set slides = jsonb_set(l.slides, array[p_pos::text] || p_path, to_jsonb(p_new)) where l.module_id = p_module;
end $$;

-- ks2-09-copyright-ownership s6 options/0/text [E17]
select schools.review_set_329('ks2-09-copyright-ownership', 5, 'choice:Mission memory from last lesson. Someone in a group chat starts being unkind about a classmate. What were our three moves?', array['options','0','text']::text[],
  'Do not join in, stick up for the person, and tell a trusted adult',
  'Do not pile on, save the evidence, tell someone who can help');

-- ks2-09-copyright-ownership s6 options/0/feedback [E17]
select schools.review_set_329('ks2-09-copyright-ownership', 5, 'choice:Mission memory from last lesson. Someone in a group chat starts being unkind about a classmate. What were our three moves?', array['options','0','feedback']::text[],
  'That is the three. Never add to the pile, be the friend who backs them up, and bring in an adult who can actually help. A bystander who acts stops being a bystander.',
  'That is the three. Starve the pile on, screenshot the evidence for a helper, and bring in an adult who has moves that pupils do not. One safe move turns a bystander into an upstander.');

-- ks2-09-copyright-ownership s6 options/1/feedback [E17]
select schools.review_set_329('ks2-09-copyright-ownership', 5, 'choice:Mission memory from last lesson. Someone in a group chat starts being unkind about a classmate. What were our three moves?', array['options','1','feedback']::text[],
  'A tiny bit of unkind is still unkind, and sorry later does not unsend it. The three moves were: do not join in, stick up for the person, tell a trusted adult.',
  'A tiny bit of unkind is still unkind, and sorry later does not unsend it. The three moves were: do not pile on, save the evidence, tell someone who can help.');

-- ks2-09-copyright-ownership s6 options/2/feedback [E17]
select schools.review_set_329('ks2-09-copyright-ownership', 5, 'choice:Mission memory from last lesson. Someone in a group chat starts being unkind about a classmate. What were our three moves?', array['options','2','feedback']::text[],
  'Leaving keeps you out of it, but it leaves the person alone with it. The three moves were: do not join in, stick up for the person, tell a trusted adult.',
  'Leaving keeps you out of it, but it leaves the person alone with it. The three moves were: do not pile on, save the evidence, tell someone who can help.');

-- ks2-09-copyright-ownership s19 options/0/feedback [C1]
select schools.review_set_329('ks2-09-copyright-ownership', 18, 'choice:Your friend types castle in space into an AI tool and gets an amazing picture. What is the honest thing to say when they share it?', array['options','0','feedback']::text[],
  'That is it. Six words, completely honest. People can enjoy the picture AND know how it was made. Honesty about the making is the one part of this puzzle that is not confusing at all.',
  'That is it. Seven words, completely honest. People can enjoy the picture and know how it was made. Honesty about the making is the one part of this puzzle that is not confusing at all.');

-- ks2-09-copyright-ownership s19 options/1/feedback [C1]
select schools.review_set_329('ks2-09-copyright-ownership', 18, 'choice:Your friend types castle in space into an AI tool and gets an amazing picture. What is the honest thing to say when they share it?', array['options','1','feedback']::text[],
  'Typing four words is not drawing, and everyone who has ever spent an hour on a drawing knows it. Claiming AI work as hand made work is taking credit that is not yours.',
  'Typing three words is not drawing, and everyone who has ever spent an hour on a drawing knows it. Claiming AI work as hand made work is taking credit that is not yours.');

-- ks2-09-copyright-ownership s10 options/1/feedback [E29]
select schools.review_set_329('ks2-09-copyright-ownership', 9, 'choice:Leo says: Priya only TOLD me the idea, she never wrote it down, so it is not really hers. Is he right?', array['options','1','feedback']::text[],
  'That is the excuse of someone who knows they took something. The idea came from Priya''s head. Fair makers ask first, they do not look for loopholes.',
  'Written down or not, the idea came from Priya''s head, so it is hers. Fair makers ask first instead of hunting for a loophole.');

-- ks2-09-copyright-ownership s27 script [A6]
select schools.review_set_329('ks2-09-copyright-ownership', 26, 'digi:Bloop''s mission for you', array['script']::text[],
  'The handover. Say nothing over it. When the last line lands, ask them to look at you and say the mission once more in your own words. DiGi closes on the next slide.',
  'The handover. Say nothing over it. When the last line lands, ask them to look at you and say the mission once more in your own words. The passport is next, then DiGi closes.');

-- ks2-09-copyright-ownership s2 lines/2 [E40]
select schools.review_set_329('ks2-09-copyright-ownership', 1, 'digi:Bloop arrives', array['lines','2']::text[],
  'Because somebody made it. And you are a maker too, so today is about you as well.',
  'Last week I nearly used a dragon I found online as my own picture. Oops. Keep that question in your head, because you are a maker too, and today is about you as well.');

-- ks2-09-copyright-ownership s26 script [A8]
select schools.review_set_329('ks2-09-copyright-ownership', 25, 'recap:What to remember', array['script']::text[],
  'Four points, read by four pupils, one each. Then one last connection: remember the feeling from the pair talk, when you imagined someone taking your proudest make? Every move we learned today exists to stop anyone feeling that. Fairness for makers, and you are all makers.',
  'Four points, read by four pupils, one each. Then say the fifth thing yourself, the one that is about them: your name, your face, your birthday and where you live belong to you in exactly the way your drawing does. Nobody gets to use them without asking, and asking means a real yes from you, not a box that was already ticked. You are allowed to say no, and you are allowed to change your mind later. Then one last connection: remember the feeling from the pair talk, when you imagined someone taking your proudest make? Every move we learned today exists to stop anyone feeling that. Fairness for makers, and you are all makers.');

-- ks3-10-mood-and-screens s16 script [E21]
select schools.review_set_329('ks3-10-mood-and-screens', 15, 'choice:You close an app after an hour and feel nothing at all. Not better, not worse. What is the honest verdict?', array['script']::text[],
  'Quick check, whole class. The second option is the one to watch, it sounds reasonable and it is exactly how the nothing hours stay hidden. Land the line: the audit has three verdicts, not two, and the third one does the most detective work.',
  'Quick check, whole class, hands or devices after ten seconds of thinking time. The no verdict needed option is the one to watch, wherever the player puts it: it sounds reasonable and it is exactly how the nothing hours stay hidden. Land the line: the audit has three verdicts, not two, and the third one does the most detective work.');

-- ks3-10-mood-and-screens s18 caption [C6]
select schools.review_set_329('ks3-10-mood-and-screens', 17, 'diagram:Your three moves', array['caption']::text[],
  'The audit finds the pattern. These moves are what the pattern unlocks. Never all or nothing, always calibrated.',
  'The audit finds the pattern. The pattern earns one of these moves. Never all or nothing, always calibrated.');

-- ks3-10-mood-and-screens s18 heading [E1]
select schools.review_set_329('ks3-10-mood-and-screens', 17, 'diagram:Your three moves', array['heading']::text[],
  'Your three moves',
  'Your four moves');

-- ks3-10-mood-and-screens s21 script [E44]
select schools.review_set_329('ks3-10-mood-and-screens', 20, 'interactive:class-tally', array['script']::text[],
  'The mood audit run as a whole class experiment. Ten seconds of silent recall first, no naming of apps or people, then count hands and tap the bars. Read the finished chart back like a scientist: this is our class data, and it will not match anyone''s guess exactly. The nothing bar deserves its own moment, because nothing is the most common answer in real studies and nobody expects it. Close with: the audit is not for judging, it is for noticing, and you can run it on yourself any night in five seconds.',
  'The mood audit run as a whole class experiment. Ten seconds of silent recall first, no naming of apps or people, then take the count the way this room votes, tokens or hands, and tap the bars. Read the finished chart back like a scientist: this is our class data, and it will not match anyone''s guess exactly. The nothing bar deserves its own moment, because nobody expects it to be there at all. Close with: the audit is not for judging, it is for noticing, and you can run it on yourself any night in ten seconds.');

-- ks3-10-mood-and-screens s29 lines/1 [C3]
select schools.review_set_329('ks3-10-mood-and-screens', 28, 'digi:DiGi closes the study', array['lines','1']::text[],
  'The question that changes everything is seven words long: after I closed it, better, worse, or nothing?',
  'The question that changes everything is eight words long: after I closed it, better, worse, or nothing?');

do $$
declare n int; list text;
begin
  select count(*), string_agg(module || ' / ' || target, '; ') into n, list from miss;
  if n > 0 then raise exception 'MIGRATION ABORTED. % target(s) not as expected: %', n, list; end if;
end $$;

-- ── the proof: nothing on the wall is over its ceiling ───────────────────
-- The same rule the council runs (scripts/council-checks.mjs).
do $$
declare cnt int; list text;
begin
  with s as (
    select l.module_id, l.key_stage, e.ord as sn, e.slide
    from schools.school_lessons l, jsonb_array_elements(l.slides) with ordinality e(slide, ord)
  ), prose as (
    select module_id, key_stage, sn,
      case slide->>'type'
        when 'title' then concat_ws(' ', slide->>'title', slide->>'body')
        when 'concept' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'tryit' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'recap' then slide->>'heading'
        when 'keywords' then slide->>'heading'
        when 'digi' then slide->>'heading'
        when 'diagram' then concat_ws(' ', slide->>'heading', slide->>'caption')
        else null end as text
    from s
  ), over as (
    select module_id, sn, array_length(regexp_split_to_array(btrim(text), '\s+'), 1) as words
    from prose where text is not null
      and array_length(regexp_split_to_array(btrim(text), '\s+'), 1) > case key_stage when 'EYFS' then 12 when 'KS1' then 12 else 105 end
  )
  select count(*), string_agg(module_id || ' s' || sn || ' (' || words || ')', '; ') into cnt, list from over;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % slide(s) still over the wall ceiling: %', cnt, list; end if;
end $$;

-- ── the proof: every attested phrase the batch's modules are named on still holds ──
-- 10 phrase checks (shared/schools-rshe-2026.ts, mode any: at least one of
-- the requirement's modules carries it; shared/schools-computing-pos.ts, mode all:
-- every named module carries it), the same lower(text) test the two guards run.
do $$
declare cnt int; list text;
begin
  with probe(rid, phrase, mods, mode) as (values
    ('RSHE-P-WO-10', 'credit', array['ks2-07-privacy-reputation','ks2-09-copyright-ownership']::text[], 'any'),
    ('RSHE-P-WO-10', 'permission', array['ks2-07-privacy-reputation','ks2-09-copyright-ownership']::text[], 'any'),
    ('RSHE-P-WO-10', 'belong to you in exactly the way your drawing does', array['ks2-07-privacy-reputation','ks2-09-copyright-ownership']::text[], 'any'),
    ('RSHE-S-OSA-12', 'profiling', array['ks4-15-manipulation-persuasion','ks5-20-ai-mastery-data-rights','ks3-10-mood-and-screens']::text[], 'any'),
    ('RSHE-S-OSA-12', 'the profile is what is actually for sale', array['ks4-15-manipulation-persuasion','ks5-20-ai-mastery-data-rights','ks3-10-mood-and-screens']::text[], 'any'),
    ('RSHE-S-WO-1', 'mood audit', array['ks3-10-mood-and-screens']::text[], 'any'),
    ('RSHE-S-WO-1', 'raw hours', array['ks3-10-mood-and-screens']::text[], 'any'),
    ('RSHE-S-WO-2', 'comparing', array['ks3-10-mood-and-screens','ks3-14-bodies-image-pressure']::text[], 'any'),
    ('RSHE-S-WO-2', 'connecting', array['ks3-10-mood-and-screens','ks3-14-bodies-image-pressure']::text[], 'any'),
    ('RSHE-S-WO-2', 'survive the app closing', array['ks3-10-mood-and-screens','ks3-14-bodies-image-pressure']::text[], 'any')
  ), sl as (select l.module_id, lower(l.slides::text) as txt from schools.school_lessons l),
  per as (select p.rid, p.phrase, p.mode, m as module_id, coalesce(position(lower(p.phrase) in sl.txt) > 0, false) as hit
    from probe p, unnest(p.mods) m left join sl on sl.module_id = m),
  bad as (
    select rid, phrase, module_id from per where mode = 'all' and not hit
    union all
    select rid, phrase, null::text from per where mode = 'any' group by rid, phrase having not bool_or(hit))
  select count(*), string_agg(rid || ': ' || phrase || coalesce(' in ' || module_id, ''), '; ') into cnt, list from bad;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % attested phrase(s) lost: %', cnt, list; end if;
end $$;

-- ── the proof: ks2-09-copyright-ownership equals content/modules/ks2-09-copyright-ownership.json ──
-- 329_must_findings_4
--
-- ks2-09-copyright-ownership was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/329_must_findings_4.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 29 slides, 423 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks2-09-copyright-ownership' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks2-09-copyright-ownership' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks2-09-copyright-ownership' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks2-09-copyright-ownership' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks2-09-copyright-ownership' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks2-09-copyright-ownership' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks2-09-copyright-ownership'
  union all
  select title from schools.school_lessons where module_id = 'ks2-09-copyright-ownership'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks2-09-copyright-ownership'
  union all
  select year_band from schools.school_lessons where module_id = 'ks2-09-copyright-ownership'
  union all
  select audience from schools.school_lessons where module_id = 'ks2-09-copyright-ownership'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks2-09-copyright-ownership'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks2-09-copyright-ownership'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks2-09-copyright-ownership'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks2-09-copyright-ownership'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks2-09-copyright-ownership'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks2-09-copyright-ownership'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks2-09-copyright-ownership';
  if got_slides is distinct from 29
     or got_n is distinct from 423
     or got_hash is distinct from '87cc126a45c20ded661823bb456854a4' then
    raise exception '329_must_findings_4: ks2-09-copyright-ownership is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

-- ── the proof: ks3-10-mood-and-screens equals content/modules/ks3-10-mood-and-screens.json ──
-- 329_must_findings_4
--
-- ks3-10-mood-and-screens was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/329_must_findings_4.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 29 slides, 403 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks3-10-mood-and-screens' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks3-10-mood-and-screens' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks3-10-mood-and-screens' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks3-10-mood-and-screens' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks3-10-mood-and-screens' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks3-10-mood-and-screens' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks3-10-mood-and-screens'
  union all
  select title from schools.school_lessons where module_id = 'ks3-10-mood-and-screens'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks3-10-mood-and-screens'
  union all
  select year_band from schools.school_lessons where module_id = 'ks3-10-mood-and-screens'
  union all
  select audience from schools.school_lessons where module_id = 'ks3-10-mood-and-screens'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks3-10-mood-and-screens'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks3-10-mood-and-screens'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks3-10-mood-and-screens'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks3-10-mood-and-screens'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks3-10-mood-and-screens'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks3-10-mood-and-screens'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks3-10-mood-and-screens';
  if got_slides is distinct from 29
     or got_n is distinct from 403
     or got_hash is distinct from 'b12fd0663c29c31d285d48d18d2ad714' then
    raise exception '329_must_findings_4: ks3-10-mood-and-screens is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

commit;
