-- 330: the lesson review, batch 5 of 11: ks3-11-social-workarounds, ks3-12-misinfo-deepfakes, ks3-14-bodies-image-pressure
--
-- Generated by scripts/gen-review-batch.mjs from the verified findings in
-- ../../../tmp/claude-0/-home-user-guided-childhood/c93e2e38-cb42-5d4e-9d75-365c993da6a1/scratchpad/lesson-review/must-all. One reviewer and one verifier per lesson against
-- scripts/lesson-rubric.md; only edits the verifier accepted are here, and
-- every one was checked on the module JSON before this file was written:
-- exact current text, no dashes, inside the wall ceiling, every attested
-- phrase kept, the module contract no worse. The same checks run again below,
-- on the server, and any miss aborts the whole batch.
--
-- THE EDITS (4)
--   ks3-11-social-workarounds s11 script [E44 must]: The script says "a third of the country's kids" but the figure on the wall is a third of children aged 8 to 17 WITH a social media profile, so the spoken line overstates the Ofcom finding and a sharp pupil can catch the teacher out.
--   ks3-12-misinfo-deepfakes s12 script [E20 must]: The script tells the teacher to watch for pupils picking the third answer, but the player shuffles options every run, so the teacher names the wrong option to most classes; there is no whole class method and no think pause; and laziness lands on the child who chose it.
--   ks3-12-misinfo-deepfakes s21 caption [E15 must]: The caption says check three is the deepfake tell, which contradicts the lesson's own hinge (slide 17's correct feedback: a big instant feeling is not proof something is false) and the stat that nothing is a tell; and the exit quiz's fill blank word, correction, never appears on the wall, so the caption should carry the key learning point the cycle exists to teach.
--   ks3-14-bodies-image-pressure s17 claim [E44 must]: The wall says most young people did not go looking for it the first time, but the report behind the slide puts accidental exposure at a minority and the lesson's own evidence base only claims often, so the stat slide overstates its source in front of a class.

begin;

create table schools.school_lessons_backup_330 as select * from schools.school_lessons;
alter table schools.school_lessons_backup_330 enable row level security;

create temp table miss(module text, target text);

-- One string on one slide, proven by the slide's type and heading and by its
-- exact current text. Anything else is a miss, and a miss aborts everything.
create or replace function schools.review_set_330(p_module text, p_pos int, p_ident text, p_path text[], p_expect text, p_new text)
returns void language plpgsql as $$
declare cur text; have text;
begin
  select (l.slides->p_pos->>'type') || ':' || coalesce(l.slides->p_pos->>'heading', l.slides->p_pos->>'title', l.slides->p_pos->>'question', l.slides->p_pos->>'prompt', l.slides->p_pos->>'component', '')
    into have from schools.school_lessons l where l.module_id = p_module;
  if have is distinct from p_ident then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' is ' || coalesce(have, 'absent') || ', expected ' || p_ident); return; end if;
  select l.slides #>> (array[p_pos::text] || p_path) into cur from schools.school_lessons l where l.module_id = p_module;
  if cur is null or cur <> p_expect then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' ' || array_to_string(p_path, '/') || ' is not the expected text'); return; end if;
  update schools.school_lessons l set slides = jsonb_set(l.slides, array[p_pos::text] || p_path, to_jsonb(p_new)) where l.module_id = p_module;
end $$;

-- ks3-11-social-workarounds s11 script [E44]
select schools.review_set_330('ks3-11-social-workarounds', 10, 'stat:', array['script']::text[],
  'Let the number land before you speak. A third of the country''s kids are walking around online in an adult costume. Then the honest question: did those children become adults when they typed a different birthday? No. So what happened to their four protections? Gone, all four, and nobody sent them a warning about it. Nothing looked different that day. That is the trap.',
  'Let the number land before you speak. A third of the children in this country with a social media profile are walking around online in an adult costume. Then the honest question: did those children become adults when they typed a different birthday? No. So what happened to their four protections? Gone, all four, and nobody sent them a warning about it. Nothing looked different that day. That is the trap.');

-- ks3-12-misinfo-deepfakes s12 script [E20]
select schools.review_set_330('ks3-12-misinfo-deepfakes', 11, 'choice:A video shows a famous footballer saying something shocking. It looks completely real. What is the honest position before you check?', array['script']::text[],
  'This is the footballer post from evidence item one. Watch for pupils picking the third answer: assuming everything is fake feels streetwise but it is the same laziness as believing everything. Name that if it comes up.',
  'This is the footballer post from evidence item one. Ten seconds of thinking time, then whole class, hands or devices for a, b, c. Watch for the it is probably fake option, wherever the player puts it: assuming everything is fake feels streetwise, but it is the same shortcut as believing everything, just facing the other way. Name that if it comes up, and land the line from the teacher tip: the checks end in believe verdicts too.');

-- ks3-12-misinfo-deepfakes s21 caption [E15]
select schools.review_set_330('ks3-12-misinfo-deepfakes', 20, 'diagram:How a fake travels', array['caption']::text[],
  'The checks break this loop at step one. That is why check three is the deepfake tell.',
  'The checks break this loop at step one. A fake travels further than its correction, so the decision that matters is made before you share.');

-- ks3-14-bodies-image-pressure s17 claim [E44]
select schools.review_set_330('ks3-14-bodies-image-pressure', 16, 'stat:', array['claim']::text[],
  'In a large survey of young people in England, the average age of first seeing online pornography was thirteen. Many saw it younger, and most did not go looking for it the first time.',
  'In a large survey of young people in England, the average age of first seeing online pornography was thirteen. Many saw it younger, and it often arrived without anyone looking for it.');

do $$
declare n int; list text;
begin
  select count(*), string_agg(module || ' / ' || target, '; ') into n, list from miss;
  if n > 0 then raise exception 'MIGRATION ABORTED. % target(s) not as expected: %', n, list; end if;
end $$;

-- ── the proof: nothing on the wall is over its ceiling ───────────────────
-- The same rule the council runs (scripts/council-checks.mjs).
do $$
declare cnt int; list text;
begin
  with s as (
    select l.module_id, l.key_stage, e.ord as sn, e.slide
    from schools.school_lessons l, jsonb_array_elements(l.slides) with ordinality e(slide, ord)
  ), prose as (
    select module_id, key_stage, sn,
      case slide->>'type'
        when 'title' then concat_ws(' ', slide->>'title', slide->>'body')
        when 'concept' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'tryit' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'recap' then slide->>'heading'
        when 'keywords' then slide->>'heading'
        when 'digi' then slide->>'heading'
        when 'diagram' then concat_ws(' ', slide->>'heading', slide->>'caption')
        else null end as text
    from s
  ), over as (
    select module_id, sn, array_length(regexp_split_to_array(btrim(text), '\s+'), 1) as words
    from prose where text is not null
      and array_length(regexp_split_to_array(btrim(text), '\s+'), 1) > case key_stage when 'EYFS' then 12 when 'KS1' then 12 else 105 end
  )
  select count(*), string_agg(module_id || ' s' || sn || ' (' || words || ')', '; ') into cnt, list from over;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % slide(s) still over the wall ceiling: %', cnt, list; end if;
end $$;

-- ── the proof: every attested phrase the batch's modules are named on still holds ──
-- 26 phrase checks (shared/schools-rshe-2026.ts, mode any: at least one of
-- the requirement's modules carries it; shared/schools-computing-pos.ts, mode all:
-- every named module carries it), the same lower(text) test the two guards run.
do $$
declare cnt int; list text;
begin
  with probe(rid, phrase, mods, mode) as (values
    ('RSHE-S-OSA-1', 'the same rules apply', array['ks4-16-consent-images-law','ks3-11-social-workarounds']::text[], 'any'),
    ('RSHE-S-OSA-1', 'never what is decent', array['ks4-16-consent-images-law','ks3-11-social-workarounds']::text[], 'any'),
    ('RSHE-S-OSA-2', 'privacy setting', array['ks3-11-social-workarounds','ks4-19-readiness-at-16']::text[], 'any'),
    ('RSHE-S-OSA-2', 'private account', array['ks3-11-social-workarounds','ks4-19-readiness-at-16']::text[], 'any'),
    ('RSHE-S-OSA-2', 'private space is one where you could name everyone', array['ks3-11-social-workarounds','ks4-19-readiness-at-16']::text[], 'any'),
    ('RSHE-S-OSA-3', 'idealis', array['ks3-12-misinfo-deepfakes','ks3-14-bodies-image-pressure','ks4-15-manipulation-persuasion','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-OSA-3', 'accounts can be too', array['ks3-12-misinfo-deepfakes','ks3-14-bodies-image-pressure','ks4-15-manipulation-persuasion','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-OSA-3', 'go further online than they would in a room', array['ks3-12-misinfo-deepfakes','ks3-14-bodies-image-pressure','ks4-15-manipulation-persuasion','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-OSA-7', 'deepfake', array['ks3-12-misinfo-deepfakes']::text[], 'any'),
    ('RSHE-S-OSA-11', 'pornography', array['ks3-14-bodies-image-pressure']::text[], 'any'),
    ('RSHE-S-OSA-11', 'carrying that expectation into a real relationship', array['ks3-14-bodies-image-pressure']::text[], 'any'),
    ('RSHE-S-WO-2', 'comparing', array['ks3-10-mood-and-screens','ks3-14-bodies-image-pressure']::text[], 'any'),
    ('RSHE-S-WO-2', 'connecting', array['ks3-10-mood-and-screens','ks3-14-bodies-image-pressure']::text[], 'any'),
    ('RSHE-S-WO-2', 'survive the app closing', array['ks3-10-mood-and-screens','ks3-14-bodies-image-pressure']::text[], 'any'),
    ('RSHE-S-WO-5', 'misinformation', array['ks3-12-misinfo-deepfakes','ks4-15-manipulation-persuasion']::text[], 'any'),
    ('RSHE-S-WO-5', 'disinformation', array['ks3-12-misinfo-deepfakes','ks4-15-manipulation-persuasion']::text[], 'any'),
    ('RSHE-S-WO-5', 'conspiracy theory', array['ks3-12-misinfo-deepfakes','ks4-15-manipulation-persuasion']::text[], 'any'),
    ('RSHE-S-WO-5', 'unfalsifiable', array['ks3-12-misinfo-deepfakes','ks4-15-manipulation-persuasion']::text[], 'any'),
    ('RSHE-S-RR-11', 'pornography', array['ks3-14-bodies-image-pressure']::text[], 'any'),
    ('RSHE-S-RR-11', 'as though another person owes them something', array['ks3-14-bodies-image-pressure']::text[], 'any'),
    ('RSHE-S-PS-2', 'everyone else', array['ks3-12-misinfo-deepfakes','ks4-15-manipulation-persuasion','ks3-11-social-workarounds']::text[], 'any'),
    ('CPOS-KS3-8', 'misinformation', array['ks3-12-misinfo-deepfakes']::text[], 'all'),
    ('CPOS-KS3-8', 'three questions', array['ks3-12-misinfo-deepfakes']::text[], 'all'),
    ('CPOS-KS3-9', 'privacy setting', array['ks3-11-social-workarounds']::text[], 'all'),
    ('CPOS-KS3-9', 'password', array['ks3-11-social-workarounds','ks3-13-scams-fraud-money']::text[], 'all'),
    ('CPOS-KS3-9', 'deepfake', array['ks3-12-misinfo-deepfakes']::text[], 'all')
  ), sl as (select l.module_id, lower(l.slides::text) as txt from schools.school_lessons l),
  per as (select p.rid, p.phrase, p.mode, m as module_id, coalesce(position(lower(p.phrase) in sl.txt) > 0, false) as hit
    from probe p, unnest(p.mods) m left join sl on sl.module_id = m),
  bad as (
    select rid, phrase, module_id from per where mode = 'all' and not hit
    union all
    select rid, phrase, null::text from per where mode = 'any' group by rid, phrase having not bool_or(hit))
  select count(*), string_agg(rid || ': ' || phrase || coalesce(' in ' || module_id, ''), '; ') into cnt, list from bad;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % attested phrase(s) lost: %', cnt, list; end if;
end $$;

-- ── the proof: ks3-11-social-workarounds equals content/modules/ks3-11-social-workarounds.json ──
-- 330_must_findings_5
--
-- ks3-11-social-workarounds was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/330_must_findings_5.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 31 slides, 436 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks3-11-social-workarounds' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks3-11-social-workarounds' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks3-11-social-workarounds' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks3-11-social-workarounds' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks3-11-social-workarounds' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks3-11-social-workarounds' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks3-11-social-workarounds'
  union all
  select title from schools.school_lessons where module_id = 'ks3-11-social-workarounds'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks3-11-social-workarounds'
  union all
  select year_band from schools.school_lessons where module_id = 'ks3-11-social-workarounds'
  union all
  select audience from schools.school_lessons where module_id = 'ks3-11-social-workarounds'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks3-11-social-workarounds'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks3-11-social-workarounds'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks3-11-social-workarounds'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks3-11-social-workarounds'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks3-11-social-workarounds'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks3-11-social-workarounds'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks3-11-social-workarounds';
  if got_slides is distinct from 31
     or got_n is distinct from 436
     or got_hash is distinct from '19d1f4779591ffebb03aa32195101505' then
    raise exception '330_must_findings_5: ks3-11-social-workarounds is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

-- ── the proof: ks3-12-misinfo-deepfakes equals content/modules/ks3-12-misinfo-deepfakes.json ──
-- 330_must_findings_5
--
-- ks3-12-misinfo-deepfakes was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/330_must_findings_5.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 35 slides, 488 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks3-12-misinfo-deepfakes' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks3-12-misinfo-deepfakes' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks3-12-misinfo-deepfakes' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks3-12-misinfo-deepfakes' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks3-12-misinfo-deepfakes' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks3-12-misinfo-deepfakes' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks3-12-misinfo-deepfakes'
  union all
  select title from schools.school_lessons where module_id = 'ks3-12-misinfo-deepfakes'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks3-12-misinfo-deepfakes'
  union all
  select year_band from schools.school_lessons where module_id = 'ks3-12-misinfo-deepfakes'
  union all
  select audience from schools.school_lessons where module_id = 'ks3-12-misinfo-deepfakes'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks3-12-misinfo-deepfakes'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks3-12-misinfo-deepfakes'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks3-12-misinfo-deepfakes'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks3-12-misinfo-deepfakes'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks3-12-misinfo-deepfakes'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks3-12-misinfo-deepfakes'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks3-12-misinfo-deepfakes';
  if got_slides is distinct from 35
     or got_n is distinct from 488
     or got_hash is distinct from 'c653559aa0e9a184d35dd72066c05083' then
    raise exception '330_must_findings_5: ks3-12-misinfo-deepfakes is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

-- ── the proof: ks3-14-bodies-image-pressure equals content/modules/ks3-14-bodies-image-pressure.json ──
-- 330_must_findings_5
--
-- ks3-14-bodies-image-pressure was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/330_must_findings_5.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 30 slides, 442 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks3-14-bodies-image-pressure' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks3-14-bodies-image-pressure' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks3-14-bodies-image-pressure' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks3-14-bodies-image-pressure' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks3-14-bodies-image-pressure' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks3-14-bodies-image-pressure' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks3-14-bodies-image-pressure'
  union all
  select title from schools.school_lessons where module_id = 'ks3-14-bodies-image-pressure'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks3-14-bodies-image-pressure'
  union all
  select year_band from schools.school_lessons where module_id = 'ks3-14-bodies-image-pressure'
  union all
  select audience from schools.school_lessons where module_id = 'ks3-14-bodies-image-pressure'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks3-14-bodies-image-pressure'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks3-14-bodies-image-pressure'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks3-14-bodies-image-pressure'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks3-14-bodies-image-pressure'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks3-14-bodies-image-pressure'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks3-14-bodies-image-pressure'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks3-14-bodies-image-pressure';
  if got_slides is distinct from 30
     or got_n is distinct from 442
     or got_hash is distinct from '26ec6e338499db53bcd914221d991ef0' then
    raise exception '330_must_findings_5: ks3-14-bodies-image-pressure is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

commit;
