-- 331: the lesson review, batch 6 of 11: ks4-15-manipulation-persuasion, ks4-16-consent-images-law
--
-- APPLIED 21 September 2026, inside the transaction recorded as
-- 330_to_333_must_findings. The eleven files in this batch went up in four
-- transactions, not eleven, so the pre batch snapshot is the single table
-- schools.school_lessons_backup_326 taken before the first edit, and the per
-- module hash proofs below ran afterwards as one query over all 26 changed
-- lessons: 26 of 26 byte identical to content/modules. Do not replay this
-- file on its own. Every edit guards on the exact text it is replacing, so a
-- replay aborts rather than writing twice, which is the point.
--
-- Generated by scripts/gen-review-batch.mjs from the verified findings in
-- ../../../tmp/claude-0/-home-user-guided-childhood/c93e2e38-cb42-5d4e-9d75-365c993da6a1/scratchpad/lesson-review/must-all. One reviewer and one verifier per lesson against
-- scripts/lesson-rubric.md; only edits the verifier accepted are here, and
-- every one was checked on the module JSON before this file was written:
-- exact current text, no dashes, inside the wall ceiling, every attested
-- phrase kept, the module contract no worse. The same checks run again below,
-- on the server, and any miss aborts the whole batch.
--
-- THE EDITS (8)
--   ks4-15-manipulation-persuasion s13 claim [E44 must]: Vosoughi, Roy and Aral found replies to false stories expressed surprise and disgust, not anger, so the wall misquotes the one source the lesson cites and a pupil who checks it catches the lesson doing what it teaches against.
--   ks4-15-manipulation-persuasion s6 options/0/text [E17 must]: The correct option quotes a check that does not exist in the scheme: ks3-12 teaches the three checks (who made this, what do other places say, how does it want me to feel) and ks3-14's image check asks different questions, so the retrieval retrieves a tool nobody was taught.
--   ks4-15-manipulation-persuasion s6 options/0/feedback [E17 must]: The feedback names the same wrong tool as the option; it must name the three checks the class actually learned and still hand the third one forward to today.
--   ks4-15-manipulation-persuasion s6 script [E17 must]: The bridge says last module was about content pretending to be real, but the previous module is ks3-14 on bodies and image pressure; the lesson being retrieved is ks3-12, and the script must say so or the teacher tells the class something false.
--   ks4-15-manipulation-persuasion s6 question [E17 must]: The question says retrieval from last module, which was bodies and image pressure, not deepfakes; naming the right lesson on the wall is what makes the retrieval reach back rather than confuse.
--   ks4-15-manipulation-persuasion s27 script [A8 must]: The recap body that holds the two RSHE profiling phrases (the profile is what is actually for sale; buy the right to reach the kind of person) is never drawn by the player, which renders a recap's heading and points only, and no script speaks it, so the requirement this lesson is attested on is taught to nobody; until a proper slide exists the teacher must at least say it.
--   ks4-16-consent-images-law s7 script [E1 must]: The scripted word for word passage names the fourth property Reversible while the wall, the objective, the recap and the exit quiz all say Revocable, so a pupil hears one word and reads another, and the same script calls worn down a property when the property is freely given.
--   ks4-16-consent-images-law s12 script [E1 must]: The script opens with walk the three steps while the wall shows four and the heading says four, so the teacher is told to skip the generated image step the same script later calls the newest and most misunderstood.

begin;

create table schools.school_lessons_backup_331 as select * from schools.school_lessons;
alter table schools.school_lessons_backup_331 enable row level security;

create temp table miss(module text, target text);

-- One string on one slide, proven by the slide's type and heading and by its
-- exact current text. Anything else is a miss, and a miss aborts everything.
create or replace function schools.review_set_331(p_module text, p_pos int, p_ident text, p_path text[], p_expect text, p_new text)
returns void language plpgsql as $$
declare cur text; have text;
begin
  select (l.slides->p_pos->>'type') || ':' || coalesce(l.slides->p_pos->>'heading', l.slides->p_pos->>'title', l.slides->p_pos->>'question', l.slides->p_pos->>'prompt', l.slides->p_pos->>'component', '')
    into have from schools.school_lessons l where l.module_id = p_module;
  if have is distinct from p_ident then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' is ' || coalesce(have, 'absent') || ', expected ' || p_ident); return; end if;
  select l.slides #>> (array[p_pos::text] || p_path) into cur from schools.school_lessons l where l.module_id = p_module;
  if cur is null or cur <> p_expect then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' ' || array_to_string(p_path, '/') || ' is not the expected text'); return; end if;
  update schools.school_lessons l set slides = jsonb_set(l.slides, array[p_pos::text] || p_path, to_jsonb(p_new)) where l.module_id = p_module;
end $$;

-- ks4-15-manipulation-persuasion s13 claim [E44]
select schools.review_set_331('ks4-15-manipulation-persuasion', 12, 'stat:', array['claim']::text[],
  'In a study of around 126,000 stories on Twitter, false stories reached 1,500 people about six times faster than true ones. The strongest fuel was surprise and anger.',
  'In a study of around 126,000 stories on Twitter, false stories reached 1,500 people about six times faster than true ones. The strongest fuel was surprise and disgust.');

-- ks4-15-manipulation-persuasion s6 options/0/text [E17]
select schools.review_set_331('ks4-15-manipulation-persuasion', 5, 'choice:Retrieval from last module. A striking image lands in the group chat and it looks completely real. What did we learn to do before trusting it?', array['options','0','text']::text[],
  'Run the image check: who posted it, does it appear anywhere else, and what feeling is it built for',
  'Run the three checks: who made this, what do other places say, how does it want me to feel');

-- ks4-15-manipulation-persuasion s6 options/0/feedback [E17]
select schools.review_set_331('ks4-15-manipulation-persuasion', 5, 'choice:Retrieval from last module. A striking image lands in the group chat and it looks completely real. What did we learn to do before trusting it?', array['options','0','feedback']::text[],
  'Right. Looking harder stopped working, so the image check does the work your eyes cannot. Keep that third question in your pocket, because today is entirely about the feeling something is built for.',
  'Right. Looking harder stopped working, so the three checks do the work your eyes cannot. Keep that third check in your pocket, because today is entirely about how something wants you to feel, and who ordered it.');

-- ks4-15-manipulation-persuasion s6 script [E17]
select schools.review_set_331('ks4-15-manipulation-persuasion', 5, 'choice:Retrieval from last module. A striking image lands in the group chat and it looks completely real. What did we learn to do before trusting it?', array['script']::text[],
  'Thirty seconds thinking time, then cold call two pupils for reasoning, not just a letter. Land the bridge: last module was about content pretending to be real. Today is about design pretending to be neutral. Same detective, new case.',
  'Thirty seconds thinking time, then cold call two pupils for reasoning, not just a letter. Land the bridge: the deepfakes lesson was about content pretending to be real. Today is about design pretending to be neutral. Same detective, new case.');

-- ks4-15-manipulation-persuasion s6 question [E17]
select schools.review_set_331('ks4-15-manipulation-persuasion', 5, 'choice:Retrieval from last module. A striking image lands in the group chat and it looks completely real. What did we learn to do before trusting it?', array['question']::text[],
  'Retrieval from last module. A striking image lands in the group chat and it looks completely real. What did we learn to do before trusting it?',
  'Retrieval from the deepfakes lesson. A striking image lands in the group chat and it looks completely real. What did we learn to do before trusting it?');

-- ks4-15-manipulation-persuasion s27 script [A8]
select schools.review_set_331('ks4-15-manipulation-persuasion', 26, 'recap:What to remember', array['script']::text[],
  'Return to the hands up count from the start: who thought adverts do not work on them? Ask again now and let the room notice the shift. Then the recap, four pupils, one point each. Read out the best who profits line you collected during practice.',
  'Return to the hands up count from the start: who thought adverts do not work on them? Ask again now and let the room notice the shift. Then the recap, four pupils, one point each. Then one more thing, said rather than shown: every scroll, pause, search and like is collected into a profile, and the profile is what is actually for sale. Advertisers do not buy your name, they buy the right to reach the kind of person you have been measured to be, which is why the free app was never free. Read out the best who profits line you collected during practice.');

-- ks4-16-consent-images-law s7 script [E1]
select schools.review_set_331('ks4-16-consent-images-law', 6, 'concept:What consent actually is', array['script']::text[],
  'Deliver this slowly and plainly. The two ideas pupils most often do not have are specific and revocable. Use a neutral everyday example first: lending a friend your bike on Saturday is not lending it forever, and you can ask for it back. Then make the link: with images the same rules apply, except the stakes are far higher because a shared image can be copied. Keep the register calm and factual throughout. Say this, as written: Those four properties were never only about images. They are what consent is for anything: going further, meeting up, being touched, being filmed, being posted. Freely given means nobody was worn down first. Specific means yes to one thing is not yes to the next thing. Ongoing means it gets checked rather than assumed from last time. Reversible means anybody can change their mind partway through, and that is simply the end of it, with no debt and no explanation owed. Exactly the same in a room and on a phone, and the phone is the harder one, because a message makes it so much easier to keep asking. Land the four properties as a general rule before the lesson narrows to images, because taught the other way round they sound like a rule about photographs. The last sentence is the one to say slowly: a phone makes asking again cost nothing, which is exactly why worn down is the property that breaks first. Do not invite examples and do not ask anybody to apply it to themselves.',
  'Deliver this slowly and plainly. The two ideas pupils most often do not have are specific and revocable. Use a neutral everyday example first: lending a friend your bike on Saturday is not lending it forever, and you can ask for it back. Then make the link: with images the same rules apply, except the stakes are far higher because a shared image can be copied. Keep the register calm and factual throughout. Say this, as written: Those four properties were never only about images. They are what consent is for anything: going further, meeting up, being touched, being filmed, being posted. Freely given means nobody was worn down first. Specific means yes to one thing is not yes to the next thing. Ongoing means it gets checked rather than assumed from last time. Revocable means anybody can change their mind partway through, and that is simply the end of it, with no debt and no explanation owed. Exactly the same in a room and on a phone, and the phone is the harder one, because a message makes it so much easier to keep asking. Land the four properties as a general rule before the lesson narrows to images, because taught the other way round they sound like a rule about photographs. The last sentence is the one to say slowly: a phone makes asking again cost nothing, which is exactly why freely given is the property that breaks first. Do not invite examples and do not ask anybody to apply it to themselves.');

-- ks4-16-consent-images-law s12 script [E1]
select schools.review_set_331('ks4-16-consent-images-law', 11, 'diagram:Four things the law covers', array['script']::text[],
  'Walk the three steps steadily. The one pupils most often get wrong is holding: an image that lands in a group chat you never asked for still creates a legal problem on your device, and the right move is delete, do not forward, and tell an adult. Forwarding deserves a moment too, because whoever forwards is legally sharing, and adding I am just passing it on changes nothing. Point at the verdict chips and repeat the frame: illegal under 18, no exceptions, and the purpose is protection first. The fourth one is the newest and the one adults get wrong too. An image generated or edited by an app is treated the same as a photograph, so a face pasted onto a body by an app is the same offence. Say that once, flatly, and do not dwell: the point is that the word real is not a defence.',
  'Walk the four steps steadily. The one pupils most often get wrong is holding: an image that lands in a group chat you never asked for still creates a legal problem on your device, and the right move is delete, do not forward, and tell an adult. Forwarding deserves a moment too, because whoever forwards is legally sharing, and adding I am just passing it on changes nothing. Point at the verdict chips and repeat the frame: illegal under 18, no exceptions, and the purpose is protection first. The fourth one is the newest and the one adults get wrong too. An image generated or edited by an app is treated the same as a photograph, so a face pasted onto a body by an app is the same offence. Say that once, flatly, and do not dwell: the point is that the word real is not a defence.');

do $$
declare n int; list text;
begin
  select count(*), string_agg(module || ' / ' || target, '; ') into n, list from miss;
  if n > 0 then raise exception 'MIGRATION ABORTED. % target(s) not as expected: %', n, list; end if;
end $$;

-- ── the proof: nothing on the wall is over its ceiling ───────────────────
-- The same rule the council runs (scripts/council-checks.mjs).
do $$
declare cnt int; list text;
begin
  with s as (
    select l.module_id, l.key_stage, e.ord as sn, e.slide
    from schools.school_lessons l, jsonb_array_elements(l.slides) with ordinality e(slide, ord)
  ), prose as (
    select module_id, key_stage, sn,
      case slide->>'type'
        when 'title' then concat_ws(' ', slide->>'title', slide->>'body')
        when 'concept' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'tryit' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'recap' then slide->>'heading'
        when 'keywords' then slide->>'heading'
        when 'digi' then slide->>'heading'
        when 'diagram' then concat_ws(' ', slide->>'heading', slide->>'caption')
        else null end as text
    from s
  ), over as (
    select module_id, sn, array_length(regexp_split_to_array(btrim(text), '\s+'), 1) as words
    from prose where text is not null
      and array_length(regexp_split_to_array(btrim(text), '\s+'), 1) > case key_stage when 'EYFS' then 12 when 'KS1' then 12 else 105 end
  )
  select count(*), string_agg(module_id || ' s' || sn || ' (' || words || ')', '; ') into cnt, list from over;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % slide(s) still over the wall ceiling: %', cnt, list; end if;
end $$;

-- ── the proof: every attested phrase the batch's modules are named on still holds ──
-- 39 phrase checks (shared/schools-rshe-2026.ts, mode any: at least one of
-- the requirement's modules carries it; shared/schools-computing-pos.ts, mode all:
-- every named module carries it), the same lower(text) test the two guards run.
do $$
declare cnt int; list text;
begin
  with probe(rid, phrase, mods, mode) as (values
    ('RSHE-S-OSA-1', 'the same rules apply', array['ks4-16-consent-images-law','ks3-11-social-workarounds']::text[], 'any'),
    ('RSHE-S-OSA-1', 'never what is decent', array['ks4-16-consent-images-law','ks3-11-social-workarounds']::text[], 'any'),
    ('RSHE-S-OSA-3', 'idealis', array['ks3-12-misinfo-deepfakes','ks3-14-bodies-image-pressure','ks4-15-manipulation-persuasion','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-OSA-3', 'accounts can be too', array['ks3-12-misinfo-deepfakes','ks3-14-bodies-image-pressure','ks4-15-manipulation-persuasion','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-OSA-3', 'go further online than they would in a room', array['ks3-12-misinfo-deepfakes','ks3-14-bodies-image-pressure','ks4-15-manipulation-persuasion','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-OSA-4', 'under 18', array['ks4-16-consent-images-law']::text[], 'any'),
    ('RSHE-S-OSA-4', 'the law', array['ks4-16-consent-images-law']::text[], 'any'),
    ('RSHE-S-OSA-5', 'any image of a person under 18', array['ks4-16-consent-images-law']::text[], 'any'),
    ('RSHE-S-OSA-5', 'treated exactly like a photograph', array['ks4-16-consent-images-law']::text[], 'any'),
    ('RSHE-S-OSA-5', 'intimate image of an adult without their consent', array['ks4-16-consent-images-law']::text[], 'any'),
    ('RSHE-S-OSA-6', 'Report Remove', array['ks4-16-consent-images-law']::text[], 'any'),
    ('RSHE-S-OSA-6', 'Internet Watch Foundation', array['ks4-16-consent-images-law']::text[], 'any'),
    ('RSHE-S-OSA-12', 'profiling', array['ks4-15-manipulation-persuasion','ks5-20-ai-mastery-data-rights','ks3-10-mood-and-screens']::text[], 'any'),
    ('RSHE-S-OSA-12', 'the profile is what is actually for sale', array['ks4-15-manipulation-persuasion','ks5-20-ai-mastery-data-rights','ks3-10-mood-and-screens']::text[], 'any'),
    ('RSHE-S-OSA-13', 'advertis', array['ks4-15-manipulation-persuasion','ks4-19-readiness-at-16']::text[], 'any'),
    ('RSHE-S-OSA-13', 'buy the right to reach the kind of person', array['ks4-15-manipulation-persuasion','ks4-19-readiness-at-16']::text[], 'any'),
    ('RSHE-S-WO-5', 'misinformation', array['ks3-12-misinfo-deepfakes','ks4-15-manipulation-persuasion']::text[], 'any'),
    ('RSHE-S-WO-5', 'disinformation', array['ks3-12-misinfo-deepfakes','ks4-15-manipulation-persuasion']::text[], 'any'),
    ('RSHE-S-WO-5', 'conspiracy theory', array['ks3-12-misinfo-deepfakes','ks4-15-manipulation-persuasion']::text[], 'any'),
    ('RSHE-S-WO-5', 'unfalsifiable', array['ks3-12-misinfo-deepfakes','ks4-15-manipulation-persuasion']::text[], 'any'),
    ('RSHE-S-RR-12', 'incel', array['ks4-18-radicalisation-misogyny','ks4-15-manipulation-persuasion']::text[], 'any'),
    ('RSHE-S-RR-12', 'attraction is a ranking', array['ks4-18-radicalisation-misogyny','ks4-15-manipulation-persuasion']::text[], 'any'),
    ('RSHE-S-BS-1', 'freely given, specific, ongoing', array['ks4-16-consent-images-law']::text[], 'any'),
    ('RSHE-S-BS-1', 'never only about images', array['ks4-16-consent-images-law']::text[], 'any'),
    ('RSHE-S-BS-1', 'exactly the same in a room and on a phone', array['ks4-16-consent-images-law']::text[], 'any'),
    ('RSHE-S-BS-2', 'naming the technique', array['ks4-17-sextortion','ks4-15-manipulation-persuasion']::text[], 'any'),
    ('RSHE-S-BS-2', 'pressure is asking again after a no', array['ks4-17-sextortion','ks4-15-manipulation-persuasion']::text[], 'any'),
    ('RSHE-S-BS-2', 'read your own messages', array['ks4-17-sextortion','ks4-15-manipulation-persuasion']::text[], 'any'),
    ('RSHE-S-BS-6', 'under 18', array['ks4-16-consent-images-law']::text[], 'any'),
    ('RSHE-S-BS-6', 'upskirting', array['ks4-16-consent-images-law']::text[], 'any'),
    ('RSHE-S-BS-6', 'sexual harassment', array['ks4-16-consent-images-law']::text[], 'any'),
    ('RSHE-S-BS-16', 'not my fault', array['ks4-16-consent-images-law','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-BS-16', 'Report Remove', array['ks4-16-consent-images-law','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-BS-16', 'the same door opens the other way round', array['ks4-16-consent-images-law','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-BS-16', 'if it is your own behaviour worrying you', array['ks4-16-consent-images-law','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-BS-16', 'a gp, or 111, or a and e', array['ks4-16-consent-images-law','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-PS-2', 'everyone else', array['ks3-12-misinfo-deepfakes','ks4-15-manipulation-persuasion','ks3-11-social-workarounds']::text[], 'any'),
    ('CPOS-KS4-3', 'Report Remove', array['ks4-16-consent-images-law']::text[], 'all'),
    ('CPOS-KS4-3', 'Internet Watch Foundation', array['ks4-16-consent-images-law']::text[], 'all')
  ), sl as (select l.module_id, lower(l.slides::text) as txt from schools.school_lessons l),
  per as (select p.rid, p.phrase, p.mode, m as module_id, coalesce(position(lower(p.phrase) in sl.txt) > 0, false) as hit
    from probe p, unnest(p.mods) m left join sl on sl.module_id = m),
  bad as (
    select rid, phrase, module_id from per where mode = 'all' and not hit
    union all
    select rid, phrase, null::text from per where mode = 'any' group by rid, phrase having not bool_or(hit))
  select count(*), string_agg(rid || ': ' || phrase || coalesce(' in ' || module_id, ''), '; ') into cnt, list from bad;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % attested phrase(s) lost: %', cnt, list; end if;
end $$;

-- ── the proof: ks4-15-manipulation-persuasion equals content/modules/ks4-15-manipulation-persuasion.json ──
-- 331_must_findings_6
--
-- ks4-15-manipulation-persuasion was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/331_must_findings_6.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 30 slides, 437 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks4-15-manipulation-persuasion' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks4-15-manipulation-persuasion' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks4-15-manipulation-persuasion' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks4-15-manipulation-persuasion' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks4-15-manipulation-persuasion' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks4-15-manipulation-persuasion' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks4-15-manipulation-persuasion'
  union all
  select title from schools.school_lessons where module_id = 'ks4-15-manipulation-persuasion'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks4-15-manipulation-persuasion'
  union all
  select year_band from schools.school_lessons where module_id = 'ks4-15-manipulation-persuasion'
  union all
  select audience from schools.school_lessons where module_id = 'ks4-15-manipulation-persuasion'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks4-15-manipulation-persuasion'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks4-15-manipulation-persuasion'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks4-15-manipulation-persuasion'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks4-15-manipulation-persuasion'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks4-15-manipulation-persuasion'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks4-15-manipulation-persuasion'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks4-15-manipulation-persuasion';
  if got_slides is distinct from 30
     or got_n is distinct from 437
     or got_hash is distinct from '18185ce1b94df6b85ca7807ece3bf705' then
    raise exception '331_must_findings_6: ks4-15-manipulation-persuasion is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

-- ── the proof: ks4-16-consent-images-law equals content/modules/ks4-16-consent-images-law.json ──
-- 331_must_findings_6
--
-- ks4-16-consent-images-law was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/331_must_findings_6.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 32 slides, 446 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks4-16-consent-images-law' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks4-16-consent-images-law' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks4-16-consent-images-law' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks4-16-consent-images-law' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks4-16-consent-images-law' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks4-16-consent-images-law' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks4-16-consent-images-law'
  union all
  select title from schools.school_lessons where module_id = 'ks4-16-consent-images-law'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks4-16-consent-images-law'
  union all
  select year_band from schools.school_lessons where module_id = 'ks4-16-consent-images-law'
  union all
  select audience from schools.school_lessons where module_id = 'ks4-16-consent-images-law'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks4-16-consent-images-law'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks4-16-consent-images-law'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks4-16-consent-images-law'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks4-16-consent-images-law'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks4-16-consent-images-law'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks4-16-consent-images-law'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks4-16-consent-images-law';
  if got_slides is distinct from 32
     or got_n is distinct from 446
     or got_hash is distinct from '26785b7655440058d426b67f568832b6' then
    raise exception '331_must_findings_6: ks4-16-consent-images-law is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

commit;
