-- 332: the lesson review, batch 7 of 11: ks4-17-sextortion, ks4-18-radicalisation-misogyny
--
-- APPLIED 21 September 2026, inside the transaction recorded as
-- 330_to_333_must_findings. The eleven files in this batch went up in four
-- transactions, not eleven, so the pre batch snapshot is the single table
-- schools.school_lessons_backup_326 taken before the first edit, and the per
-- module hash proofs below ran afterwards as one query over all 26 changed
-- lessons: 26 of 26 byte identical to content/modules. Do not replay this
-- file on its own. Every edit guards on the exact text it is replacing, so a
-- replay aborts rather than writing twice, which is the point.
--
-- Generated by scripts/gen-review-batch.mjs from the verified findings in
-- ../../../tmp/claude-0/-home-user-guided-childhood/c93e2e38-cb42-5d4e-9d75-365c993da6a1/scratchpad/lesson-review/must-all. One reviewer and one verifier per lesson against
-- scripts/lesson-rubric.md; only edits the verifier accepted are here, and
-- every one was checked on the module JSON before this file was written:
-- exact current text, no dashes, inside the wall ceiling, every attested
-- phrase kept, the module contract no worse. The same checks run again below,
-- on the server, and any miss aborts the whole batch.
--
-- THE EDITS (6)
--   ks4-17-sextortion s10 question [E44 must]: The stat slide says the NCA wrote to every school; it does not say sextortion happens in every school, so the question states as fact a claim the lesson's only source does not make.
--   ks4-17-sextortion s22 script [C3 must]: The script says the first lifeline is not a phone number, it is a pause, which contradicts the three lifelines the wall, the recap and the exit quiz all name, and it claims the breath teaches the body the way back to steady, a benefit claim E39 rules out.
--   ks4-17-sextortion s14 script [E21 must]: The script says the second option and the third option, but the player deals the options in a seeded shuffle on every run, so the teacher is pointed at the wrong tile; the E21 check passes only because the word quiet appears by accident, there is no real think pause; and the exemplar fake profile is a phrase no teacher can place.
--   ks4-17-sextortion s24 script [E20 must]: The script says a pupil who picks the third option, but the player shuffles the options every run so that position means nothing on the wall, and it never says how everyone answers at once.
--   ks4-18-radicalisation-misogyny s1 script [C13 must]: The script has the teacher promise that nothing said in discussion goes on a report, which the lesson's own dsl_note and the slide 12 script tell the teacher to break under Prevent, and it sets no right to pass or no personal stories rule at the top of a sensitive lesson.
--   ks4-18-radicalisation-misogyny s11 body [A8 must]: The attested RSHE phrase attraction is a ranking, the idea incel communities actually sell, sits only in a recap body the player never draws (the recap case renders heading and points), so the statutory coverage rests on text no pupil sees; the body's opening sentence is teacher meta talk off the teaching point and makes room for it.

begin;

create table schools.school_lessons_backup_332 as select * from schools.school_lessons;
alter table schools.school_lessons_backup_332 enable row level security;

create temp table miss(module text, target text);

-- One string on one slide, proven by the slide's type and heading and by its
-- exact current text. Anything else is a miss, and a miss aborts everything.
create or replace function schools.review_set_332(p_module text, p_pos int, p_ident text, p_path text[], p_expect text, p_new text)
returns void language plpgsql as $$
declare cur text; have text;
begin
  select (l.slides->p_pos->>'type') || ':' || coalesce(l.slides->p_pos->>'heading', l.slides->p_pos->>'title', l.slides->p_pos->>'question', l.slides->p_pos->>'prompt', l.slides->p_pos->>'component', '')
    into have from schools.school_lessons l where l.module_id = p_module;
  if have is distinct from p_ident then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' is ' || coalesce(have, 'absent') || ', expected ' || p_ident); return; end if;
  select l.slides #>> (array[p_pos::text] || p_path) into cur from schools.school_lessons l where l.module_id = p_module;
  if cur is null or cur <> p_expect then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' ' || array_to_string(p_path, '/') || ' is not the expected text'); return; end if;
  update schools.school_lessons l set slides = jsonb_set(l.slides, array[p_pos::text] || p_path, to_jsonb(p_new)) where l.module_id = p_module;
end $$;

-- ks4-17-sextortion s10 question [E44]
select schools.review_set_332('ks4-17-sextortion', 9, 'choice:This happens in every school in the country. What does that tell you about the people doing it?', array['question']::text[],
  'This happens in every school in the country. What does that tell you about the people doing it?',
  'The National Crime Agency warned every school in the country. What does that tell you about the people doing it?');

-- ks4-17-sextortion s22 script [C3]
select schools.review_set_332('ks4-17-sextortion', 21, 'interactive:star-breath', array['script']::text[],
  'Keep this slow and completely unremarkable. Say: panic is the lever this crime pulls, every single time, because a person in panic pays and hides. So the first lifeline is not a phone number, it is a pause. We practise it now, together, for four breaths, so the body knows the way back to steady before it is ever needed. Then repeat the three lifelines quietly with the class: do not pay, do not keep it secret, report it. No drama, no scenario, just the skill.',
  'Keep this slow and completely unremarkable. Say: panic is the lever this crime pulls, every single time, because a person in panic pays and hides. So before any of the three lifelines comes a pause, and a pause is a thing you can practise. We do it now, together, four breaths in time with the star, so it is something you have already done once if it is ever needed. Then repeat the three lifelines quietly with the class: do not pay, do not keep it secret, report it. No drama, no scenario, just the skill.');

-- ks4-17-sextortion s14 script [E21]
select schools.review_set_332('ks4-17-sextortion', 13, 'choice:A new account you have never met is warm, flattering, and pushing to swap images within an hour of first contact. What is the strongest signal here?', array['script']::text[],
  'First formal check of the lesson. Take the vote, then spend the time on the feedback for the second option: the exemplar fake profile looks completely normal, which is why behaviour, not appearance, is what we read. If a good number choose the third option, revisit the diagram, the back button works. Watch for pupils who answer correctly but flippantly, and for those who answer nothing at all, the quiet ones carry this lesson home.',
  'First formal check of the lesson. Thirty seconds of silent thinking, then take the vote by hands or devices. The options land in a different order on every run, so name them by content. Spend the time on the feedback for the profile picture answer: the account on evidence item one looked completely normal, which is why behaviour, not appearance, is what we read. If a good number choose no signal, revisit the diagram, the back button works. Watch for pupils who answer correctly but flippantly, and for those who answer nothing at all, the quiet ones carry this lesson home.');

-- ks4-17-sextortion s24 script [E20]
select schools.review_set_332('ks4-17-sextortion', 23, 'choice:Exit check. Someone is being blackmailed with images and the account demands money in the next hour. What is the right first move?', array['script']::text[],
  'First of two exit questions, and together they are the printed exit quiz, so run it in quiet, individual conditions. This one tests the full pathway. A pupil who picks the third option has heard block and move on advice from other contexts, so the feedback matters: blocking is fine, but only after telling and saving evidence. Mark anyone who misses this for a quiet revisit, this is the module where working towards is not a label you leave until next term.',
  'First of two exit questions, and together they are the printed exit quiz, so run it in quiet, individual conditions: thirty seconds of silence, then everyone answers on their own device or sheet, nobody calls out. This one tests the full pathway. A pupil who picks delete and block has heard block and move on advice from other contexts, so the feedback matters: blocking is fine, but only after telling and saving evidence. Mark anyone who misses this for a quiet revisit, this is the module where working towards is not a label you leave until next term.');

-- ks4-18-radicalisation-misogyny s1 script [C13]
select schools.review_set_332('ks4-18-radicalisation-misogyny', 0, 'title:Radicalisation and misogyny', array['script']::text[],
  'Settle the room with this slide up and set the register early: today is a serious one, and I am going to talk to you like the near adults you are. Nobody is in trouble in this lesson, nobody is being accused of anything, and nothing anyone says in honest discussion goes on a report. We are studying a machine. By the end of the hour you will be able to see it working.',
  'Settle the room with this slide up and set the register early: today is a serious one, and I am going to talk to you like the near adults you are. Three ground rules, said once and not laboured. Nobody is in trouble in this lesson and nobody is being accused of anything. Anyone can pass on any question. No personal stories about yourself or anyone in this room: we are studying a machine, not people. By the end of the hour you will be able to see it working.');

-- ks4-18-radicalisation-misogyny s11 body [A8]
select schools.review_set_332('ks4-18-radicalisation-misogyny', 10, 'concept:Misogyny is the most common on ramp', array['body']::text[],
  'We are going to name this plainly, because naming it is the respectful option. For teenage boys in the UK, the most common pipeline entrance is misogyny: content that starts as dating or confidence advice and escalates into contempt for women and girls.',
  'For teenage boys in the UK, the most common pipeline entrance is misogyny: content that starts as dating or confidence advice and escalates into contempt for women and girls. Underneath it is an idea about other people: that attraction is a ranking, that women owe men something, and that anyone struggling has been cheated rather than simply being young. Every part of that is a claim about how people should be treated, and it falls apart the moment it meets a real person.');

do $$
declare n int; list text;
begin
  select count(*), string_agg(module || ' / ' || target, '; ') into n, list from miss;
  if n > 0 then raise exception 'MIGRATION ABORTED. % target(s) not as expected: %', n, list; end if;
end $$;

-- ── the proof: nothing on the wall is over its ceiling ───────────────────
-- The same rule the council runs (scripts/council-checks.mjs).
do $$
declare cnt int; list text;
begin
  with s as (
    select l.module_id, l.key_stage, e.ord as sn, e.slide
    from schools.school_lessons l, jsonb_array_elements(l.slides) with ordinality e(slide, ord)
  ), prose as (
    select module_id, key_stage, sn,
      case slide->>'type'
        when 'title' then concat_ws(' ', slide->>'title', slide->>'body')
        when 'concept' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'tryit' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'recap' then slide->>'heading'
        when 'keywords' then slide->>'heading'
        when 'digi' then slide->>'heading'
        when 'diagram' then concat_ws(' ', slide->>'heading', slide->>'caption')
        else null end as text
    from s
  ), over as (
    select module_id, sn, array_length(regexp_split_to_array(btrim(text), '\s+'), 1) as words
    from prose where text is not null
      and array_length(regexp_split_to_array(btrim(text), '\s+'), 1) > case key_stage when 'EYFS' then 12 when 'KS1' then 12 else 105 end
  )
  select count(*), string_agg(module_id || ' s' || sn || ' (' || words || ')', '; ') into cnt, list from over;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % slide(s) still over the wall ceiling: %', cnt, list; end if;
end $$;

-- ── the proof: every attested phrase the batch's modules are named on still holds ──
-- 30 phrase checks (shared/schools-rshe-2026.ts, mode any: at least one of
-- the requirement's modules carries it; shared/schools-computing-pos.ts, mode all:
-- every named module carries it), the same lower(text) test the two guards run.
do $$
declare cnt int; list text;
begin
  with probe(rid, phrase, mods, mode) as (values
    ('RSHE-S-OSA-3', 'idealis', array['ks3-12-misinfo-deepfakes','ks3-14-bodies-image-pressure','ks4-15-manipulation-persuasion','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-OSA-3', 'accounts can be too', array['ks3-12-misinfo-deepfakes','ks3-14-bodies-image-pressure','ks4-15-manipulation-persuasion','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-OSA-3', 'go further online than they would in a room', array['ks3-12-misinfo-deepfakes','ks3-14-bodies-image-pressure','ks4-15-manipulation-persuasion','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-OSA-8', 'misogyn', array['ks4-18-radicalisation-misogyny','ks4-29-did-not-go-looking']::text[], 'any'),
    ('RSHE-S-OSA-8', 'violent video', array['ks4-18-radicalisation-misogyny','ks4-29-did-not-go-looking']::text[], 'any'),
    ('RSHE-S-OSA-8', 'report harmful content', array['ks4-18-radicalisation-misogyny','ks4-29-did-not-go-looking']::text[], 'any'),
    ('RSHE-S-OSA-8', 'more ordinary than it is', array['ks4-18-radicalisation-misogyny','ks4-29-did-not-go-looking']::text[], 'any'),
    ('RSHE-S-OSA-14', 'fraud is a criminal offence', array['ks3-13-scams-fraud-money','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-OSA-14', 'sextortion', array['ks3-13-scams-fraud-money','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-RR-9', 'misogyn', array['ks4-18-radicalisation-misogyny']::text[], 'any'),
    ('RSHE-S-RR-9', 'runs on race, on religion, on disability', array['ks4-18-radicalisation-misogyny']::text[], 'any'),
    ('RSHE-S-RR-9', 'a stereotype repeated often enough', array['ks4-18-radicalisation-misogyny']::text[], 'any'),
    ('RSHE-S-RR-12', 'incel', array['ks4-18-radicalisation-misogyny','ks4-15-manipulation-persuasion']::text[], 'any'),
    ('RSHE-S-RR-12', 'attraction is a ranking', array['ks4-18-radicalisation-misogyny','ks4-15-manipulation-persuasion']::text[], 'any'),
    ('RSHE-S-BS-2', 'naming the technique', array['ks4-17-sextortion','ks4-15-manipulation-persuasion']::text[], 'any'),
    ('RSHE-S-BS-2', 'pressure is asking again after a no', array['ks4-17-sextortion','ks4-15-manipulation-persuasion']::text[], 'any'),
    ('RSHE-S-BS-2', 'read your own messages', array['ks4-17-sextortion','ks4-15-manipulation-persuasion']::text[], 'any'),
    ('RSHE-S-BS-11', 'sextortion', array['ks4-17-sextortion','ks4-29-did-not-go-looking']::text[], 'any'),
    ('RSHE-S-BS-11', 'exploitation is somebody getting something out of you', array['ks4-17-sextortion','ks4-29-did-not-go-looking']::text[], 'any'),
    ('RSHE-S-BS-11', 'grooming is the part that comes first', array['ks4-17-sextortion','ks4-29-did-not-go-looking']::text[], 'any'),
    ('RSHE-S-BS-11', 'the law calls that exploitation', array['ks4-17-sextortion','ks4-29-did-not-go-looking']::text[], 'any'),
    ('RSHE-S-BS-16', 'not my fault', array['ks4-16-consent-images-law','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-BS-16', 'Report Remove', array['ks4-16-consent-images-law','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-BS-16', 'the same door opens the other way round', array['ks4-16-consent-images-law','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-BS-16', 'if it is your own behaviour worrying you', array['ks4-16-consent-images-law','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-BS-16', 'a gp, or 111, or a and e', array['ks4-16-consent-images-law','ks4-17-sextortion']::text[], 'any'),
    ('RSHE-S-PS-6', 'groom', array['ks4-17-sextortion','ks4-18-radicalisation-misogyny','ks3-22-when-an-ai-acts-like-a-friend']::text[], 'any'),
    ('RSHE-S-PS-6', 'it moves fast, it moves private', array['ks4-17-sextortion','ks4-18-radicalisation-misogyny','ks3-22-when-an-ai-acts-like-a-friend']::text[], 'any'),
    ('CPOS-KS4-3', 'sextortion', array['ks4-17-sextortion']::text[], 'all'),
    ('CPOS-KS4-3', 'organised crime', array['ks4-17-sextortion']::text[], 'all')
  ), sl as (select l.module_id, lower(l.slides::text) as txt from schools.school_lessons l),
  per as (select p.rid, p.phrase, p.mode, m as module_id, coalesce(position(lower(p.phrase) in sl.txt) > 0, false) as hit
    from probe p, unnest(p.mods) m left join sl on sl.module_id = m),
  bad as (
    select rid, phrase, module_id from per where mode = 'all' and not hit
    union all
    select rid, phrase, null::text from per where mode = 'any' group by rid, phrase having not bool_or(hit))
  select count(*), string_agg(rid || ': ' || phrase || coalesce(' in ' || module_id, ''), '; ') into cnt, list from bad;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % attested phrase(s) lost: %', cnt, list; end if;
end $$;

-- ── the proof: ks4-17-sextortion equals content/modules/ks4-17-sextortion.json ──
-- 332_must_findings_7
--
-- ks4-17-sextortion was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/332_must_findings_7.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 30 slides, 406 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks4-17-sextortion' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks4-17-sextortion' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks4-17-sextortion' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks4-17-sextortion' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks4-17-sextortion' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks4-17-sextortion' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks4-17-sextortion'
  union all
  select title from schools.school_lessons where module_id = 'ks4-17-sextortion'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks4-17-sextortion'
  union all
  select year_band from schools.school_lessons where module_id = 'ks4-17-sextortion'
  union all
  select audience from schools.school_lessons where module_id = 'ks4-17-sextortion'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks4-17-sextortion'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks4-17-sextortion'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks4-17-sextortion'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks4-17-sextortion'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks4-17-sextortion'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks4-17-sextortion'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks4-17-sextortion';
  if got_slides is distinct from 30
     or got_n is distinct from 406
     or got_hash is distinct from 'a603155021acc72f5d2d266a00225900' then
    raise exception '332_must_findings_7: ks4-17-sextortion is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

-- ── the proof: ks4-18-radicalisation-misogyny equals content/modules/ks4-18-radicalisation-misogyny.json ──
-- 332_must_findings_7
--
-- ks4-18-radicalisation-misogyny was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/332_must_findings_7.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 30 slides, 410 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks4-18-radicalisation-misogyny' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks4-18-radicalisation-misogyny' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks4-18-radicalisation-misogyny' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks4-18-radicalisation-misogyny' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks4-18-radicalisation-misogyny' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks4-18-radicalisation-misogyny' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks4-18-radicalisation-misogyny'
  union all
  select title from schools.school_lessons where module_id = 'ks4-18-radicalisation-misogyny'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks4-18-radicalisation-misogyny'
  union all
  select year_band from schools.school_lessons where module_id = 'ks4-18-radicalisation-misogyny'
  union all
  select audience from schools.school_lessons where module_id = 'ks4-18-radicalisation-misogyny'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks4-18-radicalisation-misogyny'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks4-18-radicalisation-misogyny'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks4-18-radicalisation-misogyny'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks4-18-radicalisation-misogyny'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks4-18-radicalisation-misogyny'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks4-18-radicalisation-misogyny'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks4-18-radicalisation-misogyny';
  if got_slides is distinct from 30
     or got_n is distinct from 410
     or got_hash is distinct from '53b78861e236b7ae3fba258274e8c3b2' then
    raise exception '332_must_findings_7: ks4-18-radicalisation-misogyny is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

commit;
