-- 333: the lesson review, batch 8 of 11: ks4-19-readiness-at-16, ks5-20-ai-mastery-data-rights, ks5-21-digital-identity-future-work
--
-- APPLIED 21 September 2026, inside the transaction recorded as
-- 330_to_333_must_findings. The eleven files in this batch went up in four
-- transactions, not eleven, so the pre batch snapshot is the single table
-- schools.school_lessons_backup_326 taken before the first edit, and the per
-- module hash proofs below ran afterwards as one query over all 26 changed
-- lessons: 26 of 26 byte identical to content/modules. Do not replay this
-- file on its own. Every edit guards on the exact text it is replacing, so a
-- replay aborts rather than writing twice, which is the point.
--
-- Generated by scripts/gen-review-batch.mjs from the verified findings in
-- ../../../tmp/claude-0/-home-user-guided-childhood/c93e2e38-cb42-5d4e-9d75-365c993da6a1/scratchpad/lesson-review/must-all. One reviewer and one verifier per lesson against
-- scripts/lesson-rubric.md; only edits the verifier accepted are here, and
-- every one was checked on the module JSON before this file was written:
-- exact current text, no dashes, inside the wall ceiling, every attested
-- phrase kept, the module contract no worse. The same checks run again below,
-- on the server, and any miss aborts the whole batch.
--
-- THE EDITS (9)
--   ks4-19-readiness-at-16 s14 body [E42 must]: The wall tells a child that asking for help means explaining where you were and stops there, which is the exact barrier to disclosure safeguarding guidance exists to remove, and nothing in the cycle offers a route out.
--   ks4-19-readiness-at-16 s11 script [E21 must]: The script names the third option and the middle answer, but the player shuffles options on every run, so the teacher warns about the wrong option in front of the class; it also has no think pause before hands go up.
--   ks4-19-readiness-at-16 s15 script [E21 must]: The script says watch for the third option, but the player shuffles options, so the teacher is looking at the wrong line; there is also no think pause and no whole class method before answers are taken.
--   ks4-19-readiness-at-16 s21 script [E21 must]: The script points the teacher at the first feedback line, which after the shuffle is a different option on every run, and it takes answers with no think pause.
--   ks4-19-readiness-at-16 s28 script [E20 must]: The script says these two checks form the printed exit quiz, but teacher_notes.exit_quiz is a separate five item bank, and it flags the second option on a player that shuffles options, so the follow up goes to the wrong pupils; it also never says how everyone answers.
--   ks4-19-readiness-at-16 s29 script [E20 must]: The script marks anyone choosing the first or third option as working towards, but the player shuffles options so those positions mean nothing; it also has no think pause, no whole class method, and calls two pupil positions lazy.
--   ks5-20-ai-mastery-data-rights s8 caption [E44 must]: The caption claims every serious framework for AI literacy lands on the same four moves, which is an unevidenced universal and untrue (other frameworks use different domains); the lesson's own anchor names AILit, so name that instead.
--   ks5-21-digital-identity-future-work s24 script [C11 must]: The script tells the teacher these two wall choices form the printed quiz, but schools/app/print/[module]/exit-quiz prints the five item bank in teacher_notes.exit_quiz, and it names a popular wrong answer as the first option on a player that shuffles options, so the teacher prepares the wrong sheet and watches the wrong bar; it also never says how everyone answers or gives a think pause.
--   ks5-21-digital-identity-future-work s25 question [E34 must]: Capitals for emphasis on the wall, which the rubric rules out for readers with dyslexia; the stress belongs in the teacher's voice, not the type.

begin;

create table schools.school_lessons_backup_333 as select * from schools.school_lessons;
alter table schools.school_lessons_backup_333 enable row level security;

create temp table miss(module text, target text);

-- One string on one slide, proven by the slide's type and heading and by its
-- exact current text. Anything else is a miss, and a miss aborts everything.
create or replace function schools.review_set_333(p_module text, p_pos int, p_ident text, p_path text[], p_expect text, p_new text)
returns void language plpgsql as $$
declare cur text; have text;
begin
  select (l.slides->p_pos->>'type') || ':' || coalesce(l.slides->p_pos->>'heading', l.slides->p_pos->>'title', l.slides->p_pos->>'question', l.slides->p_pos->>'prompt', l.slides->p_pos->>'component', '')
    into have from schools.school_lessons l where l.module_id = p_module;
  if have is distinct from p_ident then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' is ' || coalesce(have, 'absent') || ', expected ' || p_ident); return; end if;
  select l.slides #>> (array[p_pos::text] || p_path) into cur from schools.school_lessons l where l.module_id = p_module;
  if cur is null or cur <> p_expect then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' ' || array_to_string(p_path, '/') || ' is not the expected text'); return; end if;
  update schools.school_lessons l set slides = jsonb_set(l.slides, array[p_pos::text] || p_path, to_jsonb(p_new)) where l.module_id = p_module;
end $$;

-- ks4-19-readiness-at-16 s14 body [E42]
select schools.review_set_333('ks4-19-readiness-at-16', 13, 'concept:Not early access, a different world', array['body']::text[],
  'So you are not getting early access to the world you will enter at 16. You are entering a different one: adult settings, adult content, adult strangers, and none of the under 18 protections, because the system believes you are 18. And if something goes wrong in there, asking for help means explaining where you were. That is the real price, and it lands exactly when you most need someone.',
  'So you are not getting early access to the world you will enter at 16. You are entering a different one: adult settings, adult content, adult strangers, and none of the under 18 protections, because the system believes you are 18. And if something goes wrong in there, asking for help feels harder, because it means saying where you were. That is the real price. If it ever happens, ask anyway: a trusted adult would far rather know, and you are not in trouble.');

-- ks4-19-readiness-at-16 s11 script [E21]
select schools.review_set_333('ks4-19-readiness-at-16', 10, 'choice:Straight question. What does the under 16 ban actually change, and what does it leave completely untouched?', array['script']::text[],
  'Whole class, hands or devices. The third option is the streetwise sounding trap, expect some takers and do not mock them, the everyone gets round it belief is common and half true. Use the feedback line: some do, and the cost is coming up next. This choice sets the thesis of the whole lesson, so make sure the middle answer is said out loud in full before you move on.',
  'Whole class, hands or devices, after ten seconds of silent thinking. The options shuffle on every run, so name them by their words, not their position. The everyone gets round it option is the streetwise sounding trap, expect some takers and do not mock them, that belief is common and half true. Use its feedback line: some do, and the cost is coming up next. This choice sets the thesis of the whole lesson, so make sure the correct answer, the law handles access and you handle readiness, is said out loud in full before you move on.');

-- ks4-19-readiness-at-16 s15 script [E21]
select schools.review_set_333('ks4-19-readiness-at-16', 14, 'choice:A workaround account in the ban world runs on a false adult age. What is the sharpest description of what it actually buys you?', array['script']::text[],
  'Watch for the third option: pupils who pick it are trying to give the answer they think adults want. Use its feedback out loud, because the credibility of this whole lesson rests on never pretending. Workarounds can work as access. The argument against them is what the access actually is, and that argument is strong enough to stand on its own without exaggeration.',
  'Ten seconds of silent thinking, then everyone votes, hands or devices. Watch for the workarounds never work option: pupils who pick it are trying to give the answer they think adults want. Use its feedback out loud, because the credibility of this whole lesson rests on never pretending. Workarounds can work as access. The argument against them is what the access actually is, and that argument is strong enough to stand on its own without exaggeration.');

-- ks4-19-readiness-at-16 s21 script [E21]
select schools.review_set_333('ks4-19-readiness-at-16', 20, 'choice:Your first week audit finds a feed full of content you never chose. What is the audit actually for?', array['script']::text[],
  'Quick whole class check. The subtle point sits in the first feedback line, say it even if nobody picks that option: the feed is indifferent, not hostile. Pupils who believe the algorithm hates them feel powerless, pupils who understand it is a mirror with a motor feel in charge. The audit works because the feed responds to steering, and week one is when steering costs least.',
  'Quick whole class check, hands or devices, after ten seconds of silent thinking. The subtle point sits in the feedback for the out to get you option, say it even if nobody picks it: the feed is indifferent, not hostile. Pupils who believe the algorithm hates them feel powerless, pupils who understand it is a mirror with a motor feel in charge. The audit works because the feed responds to steering, and week one is when steering costs least.');

-- ks4-19-readiness-at-16 s28 script [E20]
select schools.review_set_333('ks4-19-readiness-at-16', 27, 'choice:Exit check. It is the night before your 16th birthday. Which of these is genuinely the strongest position to be in?', array['script']::text[],
  'First of two exit checks, these two form the printed exit quiz, so run it in silence, no conferring. A pupil picking the second option here has not connected the workaround cost to arrival day, note them for a quiet follow up, without any suggestion that the answer was autobiographical.',
  'First of two exit checks. Run it in silence, no conferring: everyone answers on their own device, or writes the letter on their question card, and the options shuffle so nobody copies a neighbour. These two checks go on the register alongside the printed exit quiz. A pupil picking the borrowed account option has not connected the workaround cost to arrival day, note them for a quiet follow up, without any suggestion that the answer was autobiographical.');

-- ks4-19-readiness-at-16 s29 script [E20]
select schools.review_set_333('ks4-19-readiness-at-16', 28, 'choice:Exit check. Honestly, what does the under 16 ban actually do?', array['script']::text[],
  'Second exit check, still silent and independent. This is the thesis question: it proves whether pupils leave with the honest position or with one of the two lazy ones, the ban fixed everything or the ban is pointless. Anyone choosing the first or third option gets marked working towards on the register, the distinction is the whole module.',
  'Second exit check, still silent and independent: everyone on their own device or question card, ten seconds of thinking before anyone taps. This is the thesis question: it proves whether pupils leave with the honest position or with one of the two easy ones, the ban fixed everything or the ban is pointless. Anyone choosing either wrong option gets marked working towards on the register, the distinction is the whole module.');

-- ks5-20-ai-mastery-data-rights s8 caption [E44]
select schools.review_set_333('ks5-20-ai-mastery-data-rights', 7, 'diagram:The four domains of AI literacy', array['caption']::text[],
  'Every serious framework for AI literacy lands on the same four moves. Most people stop at the first one.',
  'The four domains of the AILit framework. Most people stop at the first one.');

-- ks5-21-digital-identity-future-work s24 script [C11]
select schools.review_set_333('ks5-21-digital-identity-future-work', 23, 'choice:Exit check. In 2030 an employer is choosing between two graduates. Both have the same qualifications and the same AI tools. What actually separates them?', array['script']::text[],
  'First of two exit checks and these two form the printed quiz, so no discussion until both are answered. This one tests whether the whole argument landed: same tools on both sides cancel out. A wrong answer here, especially the first option, tells you who still thinks the tool is the advantage.',
  'First of two exit checks, answered on paper and in silence, because both are your evidence for who met the outcome. Thirty seconds of thinking, then everyone writes their answer on their sheet, and no discussion until both are done. The printed exit quiz is a separate five question sheet from the print pack, not these two. This one tests whether the whole argument landed: same tools on both sides cancel out. A wrong answer here, especially the newest tools one, tells you who still thinks the tool is the advantage.');

-- ks5-21-digital-identity-future-work s25 question [E34]
select schools.review_set_333('ks5-21-digital-identity-future-work', 24, 'choice:Exit check. Which of these gets MORE valuable when everyone has AI?', array['question']::text[],
  'Exit check. Which of these gets MORE valuable when everyone has AI?',
  'Exit check. Which of these gets more valuable when everyone has AI?');

do $$
declare n int; list text;
begin
  select count(*), string_agg(module || ' / ' || target, '; ') into n, list from miss;
  if n > 0 then raise exception 'MIGRATION ABORTED. % target(s) not as expected: %', n, list; end if;
end $$;

-- ── the proof: nothing on the wall is over its ceiling ───────────────────
-- The same rule the council runs (scripts/council-checks.mjs).
do $$
declare cnt int; list text;
begin
  with s as (
    select l.module_id, l.key_stage, e.ord as sn, e.slide
    from schools.school_lessons l, jsonb_array_elements(l.slides) with ordinality e(slide, ord)
  ), prose as (
    select module_id, key_stage, sn,
      case slide->>'type'
        when 'title' then concat_ws(' ', slide->>'title', slide->>'body')
        when 'concept' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'tryit' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'recap' then slide->>'heading'
        when 'keywords' then slide->>'heading'
        when 'digi' then slide->>'heading'
        when 'diagram' then concat_ws(' ', slide->>'heading', slide->>'caption')
        else null end as text
    from s
  ), over as (
    select module_id, sn, array_length(regexp_split_to_array(btrim(text), '\s+'), 1) as words
    from prose where text is not null
      and array_length(regexp_split_to_array(btrim(text), '\s+'), 1) > case key_stage when 'EYFS' then 12 when 'KS1' then 12 else 105 end
  )
  select count(*), string_agg(module_id || ' s' || sn || ' (' || words || ')', '; ') into cnt, list from over;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % slide(s) still over the wall ceiling: %', cnt, list; end if;
end $$;

-- ── the proof: every attested phrase the batch's modules are named on still holds ──
-- 9 phrase checks (shared/schools-rshe-2026.ts, mode any: at least one of
-- the requirement's modules carries it; shared/schools-computing-pos.ts, mode all:
-- every named module carries it), the same lower(text) test the two guards run.
do $$
declare cnt int; list text;
begin
  with probe(rid, phrase, mods, mode) as (values
    ('RSHE-S-OSA-2', 'privacy setting', array['ks3-11-social-workarounds','ks4-19-readiness-at-16']::text[], 'any'),
    ('RSHE-S-OSA-2', 'private account', array['ks3-11-social-workarounds','ks4-19-readiness-at-16']::text[], 'any'),
    ('RSHE-S-OSA-2', 'private space is one where you could name everyone', array['ks3-11-social-workarounds','ks4-19-readiness-at-16']::text[], 'any'),
    ('RSHE-S-OSA-12', 'profiling', array['ks4-15-manipulation-persuasion','ks5-20-ai-mastery-data-rights','ks3-10-mood-and-screens']::text[], 'any'),
    ('RSHE-S-OSA-12', 'the profile is what is actually for sale', array['ks4-15-manipulation-persuasion','ks5-20-ai-mastery-data-rights','ks3-10-mood-and-screens']::text[], 'any'),
    ('RSHE-S-OSA-13', 'advertis', array['ks4-15-manipulation-persuasion','ks4-19-readiness-at-16']::text[], 'any'),
    ('RSHE-S-OSA-13', 'buy the right to reach the kind of person', array['ks4-15-manipulation-persuasion','ks4-19-readiness-at-16']::text[], 'any'),
    ('RSHE-S-OSA-15', 'chatbot', array['ks3-22-when-an-ai-acts-like-a-friend','ks5-20-ai-mastery-data-rights','ks3-24-is-it-doing-my-thinking']::text[], 'any'),
    ('CPOS-KS4-3', 'private account', array['ks4-19-readiness-at-16']::text[], 'all')
  ), sl as (select l.module_id, lower(l.slides::text) as txt from schools.school_lessons l),
  per as (select p.rid, p.phrase, p.mode, m as module_id, coalesce(position(lower(p.phrase) in sl.txt) > 0, false) as hit
    from probe p, unnest(p.mods) m left join sl on sl.module_id = m),
  bad as (
    select rid, phrase, module_id from per where mode = 'all' and not hit
    union all
    select rid, phrase, null::text from per where mode = 'any' group by rid, phrase having not bool_or(hit))
  select count(*), string_agg(rid || ': ' || phrase || coalesce(' in ' || module_id, ''), '; ') into cnt, list from bad;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % attested phrase(s) lost: %', cnt, list; end if;
end $$;

-- ── the proof: ks4-19-readiness-at-16 equals content/modules/ks4-19-readiness-at-16.json ──
-- 333_must_findings_8
--
-- ks4-19-readiness-at-16 was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/333_must_findings_8.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 34 slides, 432 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks4-19-readiness-at-16' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks4-19-readiness-at-16' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks4-19-readiness-at-16' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks4-19-readiness-at-16' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks4-19-readiness-at-16' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks4-19-readiness-at-16' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks4-19-readiness-at-16'
  union all
  select title from schools.school_lessons where module_id = 'ks4-19-readiness-at-16'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks4-19-readiness-at-16'
  union all
  select year_band from schools.school_lessons where module_id = 'ks4-19-readiness-at-16'
  union all
  select audience from schools.school_lessons where module_id = 'ks4-19-readiness-at-16'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks4-19-readiness-at-16'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks4-19-readiness-at-16'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks4-19-readiness-at-16'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks4-19-readiness-at-16'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks4-19-readiness-at-16'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks4-19-readiness-at-16'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks4-19-readiness-at-16';
  if got_slides is distinct from 34
     or got_n is distinct from 432
     or got_hash is distinct from '6a01a36c01b6eb7602cedf5696ecffb5' then
    raise exception '333_must_findings_8: ks4-19-readiness-at-16 is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

-- ── the proof: ks5-20-ai-mastery-data-rights equals content/modules/ks5-20-ai-mastery-data-rights.json ──
-- 333_must_findings_8
--
-- ks5-20-ai-mastery-data-rights was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/333_must_findings_8.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 30 slides, 414 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks5-20-ai-mastery-data-rights' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks5-20-ai-mastery-data-rights' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks5-20-ai-mastery-data-rights' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks5-20-ai-mastery-data-rights' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks5-20-ai-mastery-data-rights' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks5-20-ai-mastery-data-rights' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks5-20-ai-mastery-data-rights'
  union all
  select title from schools.school_lessons where module_id = 'ks5-20-ai-mastery-data-rights'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks5-20-ai-mastery-data-rights'
  union all
  select year_band from schools.school_lessons where module_id = 'ks5-20-ai-mastery-data-rights'
  union all
  select audience from schools.school_lessons where module_id = 'ks5-20-ai-mastery-data-rights'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks5-20-ai-mastery-data-rights'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks5-20-ai-mastery-data-rights'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks5-20-ai-mastery-data-rights'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks5-20-ai-mastery-data-rights'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks5-20-ai-mastery-data-rights'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks5-20-ai-mastery-data-rights'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks5-20-ai-mastery-data-rights';
  if got_slides is distinct from 30
     or got_n is distinct from 414
     or got_hash is distinct from 'bb97838f2053c86a70234e69e79e42d0' then
    raise exception '333_must_findings_8: ks5-20-ai-mastery-data-rights is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

-- ── the proof: ks5-21-digital-identity-future-work equals content/modules/ks5-21-digital-identity-future-work.json ──
-- 333_must_findings_8
--
-- ks5-21-digital-identity-future-work was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/333_must_findings_8.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 29 slides, 380 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks5-21-digital-identity-future-work' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks5-21-digital-identity-future-work' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks5-21-digital-identity-future-work' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks5-21-digital-identity-future-work' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks5-21-digital-identity-future-work' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks5-21-digital-identity-future-work' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks5-21-digital-identity-future-work'
  union all
  select title from schools.school_lessons where module_id = 'ks5-21-digital-identity-future-work'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks5-21-digital-identity-future-work'
  union all
  select year_band from schools.school_lessons where module_id = 'ks5-21-digital-identity-future-work'
  union all
  select audience from schools.school_lessons where module_id = 'ks5-21-digital-identity-future-work'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks5-21-digital-identity-future-work'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks5-21-digital-identity-future-work'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks5-21-digital-identity-future-work'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks5-21-digital-identity-future-work'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks5-21-digital-identity-future-work'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks5-21-digital-identity-future-work'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks5-21-digital-identity-future-work';
  if got_slides is distinct from 29
     or got_n is distinct from 380
     or got_hash is distinct from '5be43441292ff7ae8ec3c05a7a17f5ce' then
    raise exception '333_must_findings_8: ks5-21-digital-identity-future-work is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

commit;
