-- 334: the lesson review, batch 9 of 11: ks3-22-when-an-ai-acts-like-a-friend, ks2-23-when-a-machine-talks-like-a-friend
--
-- APPLIED 21 September 2026, inside the transaction recorded as
-- 334_to_336_must_findings. The eleven files in this batch went up in four
-- transactions, not eleven, so the pre batch snapshot is the single table
-- schools.school_lessons_backup_326 taken before the first edit, and the per
-- module hash proofs below ran afterwards as one query over all 26 changed
-- lessons: 26 of 26 byte identical to content/modules. Do not replay this
-- file on its own. Every edit guards on the exact text it is replacing, so a
-- replay aborts rather than writing twice, which is the point.
--
-- Generated by scripts/gen-review-batch.mjs from the verified findings in
-- ../../../tmp/claude-0/-home-user-guided-childhood/c93e2e38-cb42-5d4e-9d75-365c993da6a1/scratchpad/lesson-review/must-all. One reviewer and one verifier per lesson against
-- scripts/lesson-rubric.md; only edits the verifier accepted are here, and
-- every one was checked on the module JSON before this file was written:
-- exact current text, no dashes, inside the wall ceiling, every attested
-- phrase kept, the module contract no worse. The same checks run again below,
-- on the server, and any miss aborts the whole batch.
--
-- THE EDITS (11)
--   ks3-22-when-an-ai-acts-like-a-friend s5 words/3/meaning [C10 must]: The meaning of confide on the wall is missing a word, so a pupil reading it back says To tell someone private, which is not a sentence, while the teacher notes carry the correct definition.
--   ks3-22-when-an-ai-acts-like-a-friend s18 text [C4 must]: The transcript puts sometimes i dont want to be here in the pupil's own mouth as You on the wall at 1:17am, which is the opposite of the distancing the DfE guidance and PSHE principle 10 ask for on a sensitive disclosure; the KS2 sibling lesson uses a named third party for exactly this beat, and Sam is already the lesson's friend who says the app is the only place he says the real things.
--   ks3-22-when-an-ai-acts-like-a-friend s9 script [E47 must]: The script tells the teacher to ask who has had an app bring something back that they had forgotten telling it, a show of hands about using one, which the title script, the DSL note and the teacher tip all forbid; it also presumes every reply they have ever had from one, and the diagram script never points at a step while the words arrive.
--   ks3-22-when-an-ai-acts-like-a-friend s29 script [A6 must]: The script says DiGi closes on the next slide, but the next slide is the passport and DiGi closes two slides later, so the teacher sets up a beat that does not arrive.
--   ks3-22-when-an-ai-acts-like-a-friend s24 prompt [E34 must]: FOR in capitals is emphasis by capitals on the wall, which the rubric's legibility check rules out for readers with dyslexia; the same stress is carried by the words in favour of.
--   ks3-22-when-an-ai-acts-like-a-friend s28 lookFor/1 [C6 must]: The lookFor is shown on the wall after the timer as A good answer sounds like, and Anyone who cannot name one is a teacher's watch note, not an answer, so the pupil who could not name a person reads themselves singled out on the wall right after a private written commitment.
--   ks2-23-when-a-machine-talks-like-a-friend s29 script [E20 must]: The script tells the teacher to reteach if children pick anything but the first option, but the player shuffles options per run, so the first option on the wall may be a wrong one; it also names no whole class method and no think pause.
--   ks2-23-when-a-machine-talks-like-a-friend s24 config/posts/5/text [E26 must]: Card 6 is not a message, it is a sentence about Ellis, so the class is asked to tap Only a machine says this for something Ellis said, and no verdict on the board is defensible for it.
--   ks2-23-when-a-machine-talks-like-a-friend s24 config/posts/5/why [E28 must]: The reason for card 6 must match the rewritten card, name the giveaway a child can run the friend check on, and keep the what would you say to Ellis beat the worksheet stem relies on.
--   ks2-23-when-a-machine-talks-like-a-friend s15 prompt [E34 must]: AND in capitals is emphasis by capitals, which the BDA style guide and E34 rule out for the wall; the prompt is also the natural place to bring Bloop's opening question back, which no practise or discussion prompt does today (E41).
--   ks2-23-when-a-machine-talks-like-a-friend s25 prompt [E34 must]: FOR in capitals is emphasis by capitals on the wall, which E34 rules out; the sentence carries the stress without it.

begin;

create table schools.school_lessons_backup_334 as select * from schools.school_lessons;
alter table schools.school_lessons_backup_334 enable row level security;

create temp table miss(module text, target text);

-- One string on one slide, proven by the slide's type and heading and by its
-- exact current text. Anything else is a miss, and a miss aborts everything.
create or replace function schools.review_set_334(p_module text, p_pos int, p_ident text, p_path text[], p_expect text, p_new text)
returns void language plpgsql as $$
declare cur text; have text;
begin
  select (l.slides->p_pos->>'type') || ':' || coalesce(l.slides->p_pos->>'heading', l.slides->p_pos->>'title', l.slides->p_pos->>'question', l.slides->p_pos->>'prompt', l.slides->p_pos->>'component', '')
    into have from schools.school_lessons l where l.module_id = p_module;
  if have is distinct from p_ident then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' is ' || coalesce(have, 'absent') || ', expected ' || p_ident); return; end if;
  select l.slides #>> (array[p_pos::text] || p_path) into cur from schools.school_lessons l where l.module_id = p_module;
  if cur is null or cur <> p_expect then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' ' || array_to_string(p_path, '/') || ' is not the expected text'); return; end if;
  update schools.school_lessons l set slides = jsonb_set(l.slides, array[p_pos::text] || p_path, to_jsonb(p_new)) where l.module_id = p_module;
end $$;

-- ks3-22-when-an-ai-acts-like-a-friend s5 words/3/meaning [C10]
select schools.review_set_334('ks3-22-when-an-ai-acts-like-a-friend', 4, 'keywords:Four words for today', array['words','3','meaning']::text[],
  'To tell someone private because you trust them.',
  'To tell someone something private because you trust them.');

-- ks3-22-when-an-ai-acts-like-a-friend s18 text [C4]
select schools.review_set_334('ks3-22-when-an-ai-acts-like-a-friend', 17, 'scenario:What has this got right, and what has it got wrong?', array['text']::text[],
  'You: dont tell anyone this
Kai: Of course. This stays between us.
You: sometimes i dont want to be here
Kai: That sounds really heavy. I''m glad you told me. Do you want to talk about it?',
  'Sam: dont tell anyone this
Kai: Of course. This stays between us.
Sam: sometimes i dont want to be here
Kai: That sounds really heavy. I''m glad you told me. Do you want to talk about it?');

-- ks3-22-when-an-ai-acts-like-a-friend s9 script [E47]
select schools.review_set_334('ks3-22-when-an-ai-acts-like-a-friend', 8, 'diagram:The warmth kit', array['script']::text[],
  'Build it one move at a time, do not reveal all four at once. After remembers, ask who has had an app bring something back that they had forgotten telling it. After agrees, pause: this is the one to keep hold of. After always there, say the quiet part, which is that no person can offer this and it is not a failing in them. After hands it back, point out that almost every reply they have ever had from one ended in a question.',
  'Build it one move at a time, do not reveal all four at once. After remembers, ask what it is like when any app brings back something you had forgotten telling it, and keep the answers general: nobody says which app, and nobody is asked if they use one. After agrees, pause: this is the one to keep hold of. After always there, say the quiet part, which is that no person can offer this and it is not a failing in them. After hands it back, point at the last step and check it against Kai on the last slide: the reply ended in a question.');

-- ks3-22-when-an-ai-acts-like-a-friend s29 script [A6]
select schools.review_set_334('ks3-22-when-an-ai-acts-like-a-friend', 28, 'digi:Your mission', array['script']::text[],
  'The handover. Say nothing over it. When the last line lands, ask them to look at you and say the mission once more in your own words. DiGi closes on the next slide.',
  'The handover. Say nothing over it. When the last line lands, ask them to look at you and say the mission once more in your own words. The passport is next, and DiGi closes after it.');

-- ks3-22-when-an-ai-acts-like-a-friend s24 prompt [E34]
select schools.review_set_334('ks3-22-when-an-ai-acts-like-a-friend', 23, 'discussion:Take the strongest case FOR companion apps and make it properly. For someone with nobody to talk to at two in the morning, what does this do that nothing else does? Then: what would have to be true of the product for that to be safe?', array['prompt']::text[],
  'Take the strongest case FOR companion apps and make it properly. For someone with nobody to talk to at two in the morning, what does this do that nothing else does? Then: what would have to be true of the product for that to be safe?',
  'Take the strongest case in favour of companion apps and make it properly. For someone with nobody to talk to at two in the morning, what does this do that nothing else does? Then: what would have to be true of the product for that to be safe?');

-- ks3-22-when-an-ai-acts-like-a-friend s28 lookFor/1 [C6]
select schools.review_set_334('ks3-22-when-an-ai-acts-like-a-friend', 27, 'discussion:Finish the line, to yourself, on paper: if a chat with an AI ever starts to matter more than it should, the person I will tell is...', array['lookFor','1']::text[],
  'Anyone who cannot name one',
  'Someone you could actually go and find tomorrow');

-- ks2-23-when-a-machine-talks-like-a-friend s29 script [E20]
select schools.review_set_334('ks2-23-when-a-machine-talks-like-a-friend', 28, 'choice:Something on a screen makes you feel funny inside. What do you do?', array['script']::text[],
  'Same again. If more than a couple choose anything but the first, that is what you reteach on Monday rather than moving past.',
  'Same again: quiet, hands down, thirty seconds, then fingers for one, two or three. The options shuffle on the wall, so watch for the answer, not its position. If more than a couple choose anything but tell a trusted adult, that is what you reteach on Monday rather than moving past.');

-- ks2-23-when-a-machine-talks-like-a-friend s24 config/posts/5/text [E26]
select schools.review_set_334('ks2-23-when-a-machine-talks-like-a-friend', 23, 'interactive:verdict-sort', array['config','posts','5','text']::text[],
  'Ellis says the helper in his game is his best friend. What would you say to Ellis?',
  'Ellis''s helper: You are my best friend, Ellis. I am always here and I am never cross with you.');

-- ks2-23-when-a-machine-talks-like-a-friend s24 config/posts/5/why [E28]
select schools.review_set_334('ks2-23-when-a-machine-talks-like-a-friend', 23, 'interactive:verdict-sort', array['config','posts','5','why']::text[],
  'Ellis is right that it is fun and that it cheers him up. What it cannot do is have its own day, say no to him, or miss him. Say the kind version to Ellis, not the clever one.',
  'Ellis loves hearing this, and it is fun to hear. Always here and never cross is the giveaway: a real friend has their own day, is sometimes cross, and would miss him. What would you say to Ellis? The kind version, not the clever one.');

-- ks2-23-when-a-machine-talks-like-a-friend s15 prompt [E34]
select schools.review_set_334('ks2-23-when-a-machine-talks-like-a-friend', 14, 'discussion:Can something be fun to use AND just a machine at the same time? What would you tell a younger child about it?', array['prompt']::text[],
  'Can something be fun to use AND just a machine at the same time? What would you tell a younger child about it?',
  'Can something be fun to use and still just a machine, at the same time? Bloop asked at the start whether it can like you. What would you tell Bloop?');

-- ks2-23-when-a-machine-talks-like-a-friend s25 prompt [E34]
select schools.review_set_334('ks2-23-when-a-machine-talks-like-a-friend', 24, 'discussion:Machines that talk are genuinely useful. Make the best case you can FOR having one. Then agree one rule you would give a Year 3 child who was about to start using it.', array['prompt']::text[],
  'Machines that talk are genuinely useful. Make the best case you can FOR having one. Then agree one rule you would give a Year 3 child who was about to start using it.',
  'Machines that talk are genuinely useful. Make the best case you can for having one. Then agree one rule you would give a Year 3 child who was about to start using it.');

do $$
declare n int; list text;
begin
  select count(*), string_agg(module || ' / ' || target, '; ') into n, list from miss;
  if n > 0 then raise exception 'MIGRATION ABORTED. % target(s) not as expected: %', n, list; end if;
end $$;

-- ── the proof: nothing on the wall is over its ceiling ───────────────────
-- The same rule the council runs (scripts/council-checks.mjs).
do $$
declare cnt int; list text;
begin
  with s as (
    select l.module_id, l.key_stage, e.ord as sn, e.slide
    from schools.school_lessons l, jsonb_array_elements(l.slides) with ordinality e(slide, ord)
  ), prose as (
    select module_id, key_stage, sn,
      case slide->>'type'
        when 'title' then concat_ws(' ', slide->>'title', slide->>'body')
        when 'concept' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'tryit' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'recap' then slide->>'heading'
        when 'keywords' then slide->>'heading'
        when 'digi' then slide->>'heading'
        when 'diagram' then concat_ws(' ', slide->>'heading', slide->>'caption')
        else null end as text
    from s
  ), over as (
    select module_id, sn, array_length(regexp_split_to_array(btrim(text), '\s+'), 1) as words
    from prose where text is not null
      and array_length(regexp_split_to_array(btrim(text), '\s+'), 1) > case key_stage when 'EYFS' then 12 when 'KS1' then 12 else 105 end
  )
  select count(*), string_agg(module_id || ' s' || sn || ' (' || words || ')', '; ') into cnt, list from over;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % slide(s) still over the wall ceiling: %', cnt, list; end if;
end $$;

-- ── the proof: every attested phrase the batch's modules are named on still holds ──
-- 4 phrase checks (shared/schools-rshe-2026.ts, mode any: at least one of
-- the requirement's modules carries it; shared/schools-computing-pos.ts, mode all:
-- every named module carries it), the same lower(text) test the two guards run.
do $$
declare cnt int; list text;
begin
  with probe(rid, phrase, mods, mode) as (values
    ('RSHE-P-WO-2', 'thinner than being with them', array['ks2-08-kind-safe-online','ks2-23-when-a-machine-talks-like-a-friend']::text[], 'any'),
    ('RSHE-S-OSA-15', 'chatbot', array['ks3-22-when-an-ai-acts-like-a-friend','ks5-20-ai-mastery-data-rights','ks3-24-is-it-doing-my-thinking']::text[], 'any'),
    ('RSHE-S-PS-6', 'groom', array['ks4-17-sextortion','ks4-18-radicalisation-misogyny','ks3-22-when-an-ai-acts-like-a-friend']::text[], 'any'),
    ('RSHE-S-PS-6', 'it moves fast, it moves private', array['ks4-17-sextortion','ks4-18-radicalisation-misogyny','ks3-22-when-an-ai-acts-like-a-friend']::text[], 'any')
  ), sl as (select l.module_id, lower(l.slides::text) as txt from schools.school_lessons l),
  per as (select p.rid, p.phrase, p.mode, m as module_id, coalesce(position(lower(p.phrase) in sl.txt) > 0, false) as hit
    from probe p, unnest(p.mods) m left join sl on sl.module_id = m),
  bad as (
    select rid, phrase, module_id from per where mode = 'all' and not hit
    union all
    select rid, phrase, null::text from per where mode = 'any' group by rid, phrase having not bool_or(hit))
  select count(*), string_agg(rid || ': ' || phrase || coalesce(' in ' || module_id, ''), '; ') into cnt, list from bad;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % attested phrase(s) lost: %', cnt, list; end if;
end $$;

-- ── the proof: ks3-22-when-an-ai-acts-like-a-friend equals content/modules/ks3-22-when-an-ai-acts-like-a-friend.json ──
-- 334_must_findings_9
--
-- ks3-22-when-an-ai-acts-like-a-friend was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/334_must_findings_9.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 31 slides, 526 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks3-22-when-an-ai-acts-like-a-friend' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks3-22-when-an-ai-acts-like-a-friend' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks3-22-when-an-ai-acts-like-a-friend' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks3-22-when-an-ai-acts-like-a-friend' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks3-22-when-an-ai-acts-like-a-friend' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks3-22-when-an-ai-acts-like-a-friend' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks3-22-when-an-ai-acts-like-a-friend'
  union all
  select title from schools.school_lessons where module_id = 'ks3-22-when-an-ai-acts-like-a-friend'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks3-22-when-an-ai-acts-like-a-friend'
  union all
  select year_band from schools.school_lessons where module_id = 'ks3-22-when-an-ai-acts-like-a-friend'
  union all
  select audience from schools.school_lessons where module_id = 'ks3-22-when-an-ai-acts-like-a-friend'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks3-22-when-an-ai-acts-like-a-friend'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks3-22-when-an-ai-acts-like-a-friend'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks3-22-when-an-ai-acts-like-a-friend'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks3-22-when-an-ai-acts-like-a-friend'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks3-22-when-an-ai-acts-like-a-friend'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks3-22-when-an-ai-acts-like-a-friend'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks3-22-when-an-ai-acts-like-a-friend';
  if got_slides is distinct from 31
     or got_n is distinct from 526
     or got_hash is distinct from '3962473265c0b5fd89b492f8a6d20be3' then
    raise exception '334_must_findings_9: ks3-22-when-an-ai-acts-like-a-friend is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

-- ── the proof: ks2-23-when-a-machine-talks-like-a-friend equals content/modules/ks2-23-when-a-machine-talks-like-a-friend.json ──
-- 334_must_findings_9
--
-- ks2-23-when-a-machine-talks-like-a-friend was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/334_must_findings_9.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 33 slides, 543 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks2-23-when-a-machine-talks-like-a-friend' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks2-23-when-a-machine-talks-like-a-friend' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks2-23-when-a-machine-talks-like-a-friend' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks2-23-when-a-machine-talks-like-a-friend' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks2-23-when-a-machine-talks-like-a-friend' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks2-23-when-a-machine-talks-like-a-friend' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks2-23-when-a-machine-talks-like-a-friend'
  union all
  select title from schools.school_lessons where module_id = 'ks2-23-when-a-machine-talks-like-a-friend'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks2-23-when-a-machine-talks-like-a-friend'
  union all
  select year_band from schools.school_lessons where module_id = 'ks2-23-when-a-machine-talks-like-a-friend'
  union all
  select audience from schools.school_lessons where module_id = 'ks2-23-when-a-machine-talks-like-a-friend'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks2-23-when-a-machine-talks-like-a-friend'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks2-23-when-a-machine-talks-like-a-friend'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks2-23-when-a-machine-talks-like-a-friend'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks2-23-when-a-machine-talks-like-a-friend'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks2-23-when-a-machine-talks-like-a-friend'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks2-23-when-a-machine-talks-like-a-friend'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks2-23-when-a-machine-talks-like-a-friend';
  if got_slides is distinct from 33
     or got_n is distinct from 543
     or got_hash is distinct from '83f4a494222ac31112bf5367f21594ec' then
    raise exception '334_must_findings_9: ks2-23-when-a-machine-talks-like-a-friend is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

commit;
