-- 335: the lesson review, batch 10 of 11: ks3-24-is-it-doing-my-thinking, ks2-25-stay-the-maker, ks2-26-why-thirteen
--
-- APPLIED 21 September 2026, inside the transaction recorded as
-- 334_to_336_must_findings. The eleven files in this batch went up in four
-- transactions, not eleven, so the pre batch snapshot is the single table
-- schools.school_lessons_backup_326 taken before the first edit, and the per
-- module hash proofs below ran afterwards as one query over all 26 changed
-- lessons: 26 of 26 byte identical to content/modules. Do not replay this
-- file on its own. Every edit guards on the exact text it is replacing, so a
-- replay aborts rather than writing twice, which is the point.
--
-- Generated by scripts/gen-review-batch.mjs from the verified findings in
-- ../../../tmp/claude-0/-home-user-guided-childhood/c93e2e38-cb42-5d4e-9d75-365c993da6a1/scratchpad/lesson-review/must-all. One reviewer and one verifier per lesson against
-- scripts/lesson-rubric.md; only edits the verifier accepted are here, and
-- every one was checked on the module JSON before this file was written:
-- exact current text, no dashes, inside the wall ceiling, every attested
-- phrase kept, the module contract no worse. The same checks run again below,
-- on the server, and any miss aborts the whole batch.
--
-- THE EDITS (15)
--   ks3-24-is-it-doing-my-thinking s7 options/0/feedback [C1 must]: The feedback says this group did best in practice, but the next slide and the evidence base show the hints group gained 127 percent in practice against this group's 48, so the wall contradicts itself on the number the lesson turns on.
--   ks3-24-is-it-doing-my-thinking s31 lines/2 [E44 must]: Used it more than anyone is a usage claim the evidence base does not carry (the trial reports practice and exam scores, not how much each group used the tool), and the notes themselves only say as much as, so the closing line overstates and contradicts the notes.
--   ks3-24-is-it-doing-my-thinking s7 question [E34 must]: A capitalised word for emphasis on the wall is the thing the dyslexia style guide says not to do, and the sentence carries the stress without it.
--   ks3-24-is-it-doing-my-thinking s8 steps/0/text [E34 must]: BELOW in capitals is emphasis by capitals on a diagram step a child reads at their own pace; the number does the work on its own.
--   ks3-24-is-it-doing-my-thinking s12 steps/0/text [E34 must]: IS in capitals for emphasis, on the one slide written for the dyslexic pupil in the room; the contrast with the next step is carried by the words allowed and not allowed.
--   ks3-24-is-it-doing-my-thinking s12 steps/1/text [E34 must]: NOT in capitals for emphasis, on the same slide and for the same reader.
--   ks3-24-is-it-doing-my-thinking s14 options/2/feedback [E34 must]: IS in capitals for emphasis in feedback a child reads after a wrong pick, when the short sentence already lands it.
--   ks3-24-is-it-doing-my-thinking s15 prompt [E34 must]: IS in capitals for emphasis in the discussion prompt the whole class reads for sixty seconds.
--   ks2-25-stay-the-maker s7 script [E20 must]: The player deals the options in a fresh order every run (LessonPlayer optionOrder), so telling the teacher that option two is the popular answer points at a different line in most classrooms; the script also never says how everyone answers or gives the three second pause.
--   ks2-25-stay-the-maker s12 script [E20 must]: Option three is named by its position on a wall that shuffles the options each run, so the teacher spends time on the wrong line; no whole class method and no think pause either.
--   ks2-25-stay-the-maker s18 script [E20 must]: Option two is named by position on a shuffled wall, so the answer the teacher is told to head off hardest may be sitting on line one or three; no whole class method and no think pause.
--   ks2-25-stay-the-maker s17 body [E34 must]: WORKS IN STEPS is capitals for emphasis on the wall, which the BDA guide and E34 rule out for dyslexic readers, and column subtraction is a procedure, the one kind of thing the lesson's own evidence base says the explain it back effect was not found for, so the example undercuts the drill.
--   ks2-25-stay-the-maker s10 caption [E15 must]: The caption says Same tool under a picture whose two steps are a ruler and a computer, so the wall contradicts its own diagram; the relationship the picture shows is that the job, not the tool, decides the verdict.
--   ks2-25-stay-the-maker s26 script [E23 must]: The script sends a teacher back to cycle two if this wobbles, but what was the job is taught on the cycle one diagram (slide 10), so the direction is wrong; it also lacks the whole class method and the pause.
--   ks2-26-why-thirteen s25 question [E26 must]: A strong password does make an app safer, and the option's own feedback says so, so the question has two defensible right answers and the child who picks the password is marked wrong for being right.

begin;

create table schools.school_lessons_backup_335 as select * from schools.school_lessons;
alter table schools.school_lessons_backup_335 enable row level security;

create temp table miss(module text, target text);

-- One string on one slide, proven by the slide's type and heading and by its
-- exact current text. Anything else is a miss, and a miss aborts everything.
create or replace function schools.review_set_335(p_module text, p_pos int, p_ident text, p_path text[], p_expect text, p_new text)
returns void language plpgsql as $$
declare cur text; have text;
begin
  select (l.slides->p_pos->>'type') || ':' || coalesce(l.slides->p_pos->>'heading', l.slides->p_pos->>'title', l.slides->p_pos->>'question', l.slides->p_pos->>'prompt', l.slides->p_pos->>'component', '')
    into have from schools.school_lessons l where l.module_id = p_module;
  if have is distinct from p_ident then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' is ' || coalesce(have, 'absent') || ', expected ' || p_ident); return; end if;
  select l.slides #>> (array[p_pos::text] || p_path) into cur from schools.school_lessons l where l.module_id = p_module;
  if cur is null or cur <> p_expect then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' ' || array_to_string(p_path, '/') || ' is not the expected text'); return; end if;
  update schools.school_lessons l set slides = jsonb_set(l.slides, array[p_pos::text] || p_path, to_jsonb(p_new)) where l.module_id = p_module;
end $$;

-- ks3-24-is-it-doing-my-thinking s7 options/0/feedback [C1]
select schools.review_set_335('ks3-24-is-it-doing-my-thinking', 6, 'choice:Before you see the result. On the exam, with the tool taken away from everyone, which group came out WORST?', array['options','0','feedback']::text[],
  'Yes, and they had done best in every practice session. On the exam they came 17 percent BELOW the group who never had it at all.',
  'Yes, and while they still had it, their practice scores had gone up. On the exam they came 17 percent below the group who never had it at all.');

-- ks3-24-is-it-doing-my-thinking s31 lines/2 [E44]
select schools.review_set_335('ks3-24-is-it-doing-my-thinking', 30, 'digi:One last thing', array['lines','2']::text[],
  'The pupils who kept what they learned used it more than anyone. They just never asked it for the answer.',
  'The pupils who kept what they learned still used it. They just never asked it for the answer.');

-- ks3-24-is-it-doing-my-thinking s7 question [E34]
select schools.review_set_335('ks3-24-is-it-doing-my-thinking', 6, 'choice:Before you see the result. On the exam, with the tool taken away from everyone, which group came out WORST?', array['question']::text[],
  'Before you see the result. On the exam, with the tool taken away from everyone, which group came out WORST?',
  'Before you see the result. On the exam, with the tool taken away from everyone, which group came out worst?');

-- ks3-24-is-it-doing-my-thinking s8 steps/0/text [E34]
select schools.review_set_335('ks3-24-is-it-doing-my-thinking', 7, 'diagram:Same tool, opposite result', array['steps','0','text']::text[],
  'Practice scores went up 48 percent. On the exam, with the tool gone, they scored 17 percent BELOW the group who never had it.',
  'Practice scores went up 48 percent. On the exam, with the tool gone, they scored 17 percent below the group who never had it.');

-- ks3-24-is-it-doing-my-thinking s12 steps/0/text [E34]
select schools.review_set_335('ks3-24-is-it-doing-my-thinking', 11, 'diagram:The exam board already decided this', array['steps','0','text']::text[],
  'A computer reader IS allowed. A flat machine voice says the words and hands you nothing else.',
  'A computer reader is allowed. A flat machine voice says the words and hands you nothing else.');

-- ks3-24-is-it-doing-my-thinking s12 steps/1/text [E34]
select schools.review_set_335('ks3-24-is-it-doing-my-thinking', 11, 'diagram:The exam board already decided this', array['steps','1','text']::text[],
  'A human reader is NOT allowed. A person reading aloud adds emphasis and meaning, and working out the meaning is what that section marks.',
  'A human reader is not allowed. A person reading aloud adds emphasis and meaning, and working out the meaning is what that section marks.');

-- ks3-24-is-it-doing-my-thinking s14 options/2/feedback [E34]
select schools.review_set_335('ks3-24-is-it-doing-my-thinking', 13, 'choice:Science write up on a practical you did. You cannot get the introduction started, so you ask for a first sentence. Ramp or swap?', array['options','2','feedback']::text[],
  'Hard does not mean it is not the lesson. Sometimes the hard part IS the lesson. The question is what is being marked.',
  'Hard does not mean it is not the lesson. Sometimes the hard part is the lesson. The question is what is being marked.');

-- ks3-24-is-it-doing-my-thinking s15 prompt [E34]
select schools.review_set_335('ks3-24-is-it-doing-my-thinking', 14, 'discussion:Name a task where the hard part is in the way rather than the point. Then name one where the hard part IS the point.', array['prompt']::text[],
  'Name a task where the hard part is in the way rather than the point. Then name one where the hard part IS the point.',
  'Name a task where the hard part is in the way rather than the point. Then name one where the hard part is the point.');

-- ks2-25-stay-the-maker s7 script [E20]
select schools.review_set_335('ks2-25-stay-the-maker', 6, 'choice:You typed six words and the computer drew the dragon. Who is the maker?', array['script']::text[],
  'Option two is where most of the class lives and you must not squash it. Their idea IS real. Say that first, then separate having the idea from doing the making. That separation is the lesson.',
  'Hands down, three seconds of thinking time, then fingers up, one, two or three, everyone at once. The options land in a different order on every run, so name them by their words, never by their number. The answer that says it was your idea is where most of the class lives and you must not squash it. Their idea is real. Say that first, then separate having the idea from doing the making. That separation is the lesson.');

-- ks2-25-stay-the-maker s12 script [E20]
select schools.review_set_335('ks2-25-stay-the-maker', 11, 'choice:You are stuck on your story. Which ask keeps you as the maker?', array['script']::text[],
  'Option three is the one to spend time on. It sounds like learning and it is not, and clever children reach for it most. Say out loud that a wobbly story you wrote beats a brilliant one you read.',
  'Three seconds of thinking time, then fingers up, one, two or three, all at once. The options shuffle on every run, so name them by their words. The one that asks for the whole story so I can see how it should go is the one to spend time on. It sounds like learning and it is not, and clever children reach for it most. Say out loud that a wobbly story you wrote beats a brilliant one you read.');

-- ks2-25-stay-the-maker s18 script [E20]
select schools.review_set_335('ks2-25-stay-the-maker', 17, 'choice:Your second score was lower than your first. What does that actually mean?', array['script']::text[],
  'Option two is the one to head off hardest, and some child in this room will believe it. Nobody got worse. They got accurate. Say that phrase, write it up, leave it there.',
  'Three seconds of thinking time, then fingers up, one, two or three, everyone together. The options shuffle on every run, so name them by their words. The answer that says you got worse is the one to head off hardest, and some child in this room will believe it. Nobody got worse. They got accurate. Say that phrase, write it up, leave it there.');

-- ks2-25-stay-the-maker s17 body [E34]
select schools.review_set_335('ks2-25-stay-the-maker', 16, 'tryit:Try it now, on something that works in steps', array['body']::text[],
  'Pick something you learned this week that WORKS IN STEPS. How a plant drinks. How to do a column subtraction. Score yourself out of 5. Now say it out loud to your partner, every step. Score yourself again.',
  'Pick something you learned this week that works in steps. How a plant drinks. How a circuit lights a bulb. Score yourself out of 5. Now say it out loud to your partner, every step. Score yourself again.');

-- ks2-25-stay-the-maker s10 caption [E15]
select schools.review_set_335('ks2-25-stay-the-maker', 9, 'diagram:Helper, or took over?', array['caption']::text[],
  'Same tool. Two different jobs.',
  'The tool does not decide it. The job does.');

-- ks2-25-stay-the-maker s26 script [E23]
select schools.review_set_335('ks2-25-stay-the-maker', 25, 'choice:One question tells you whether something is a helper or whether it took over. Which one?', array['script']::text[],
  'Straight recall of the tool. If this one wobbles, the lesson did not land and cycle two is where to go back to.',
  'Straight recall of the tool. Three seconds of thinking time, then fingers up, one, two or three, everyone at once. If this one wobbles, the lesson did not land and cycle one, the helper or took over diagram, is where to go back to.');

-- ks2-26-why-thirteen s25 question [E26]
select schools.review_set_335('ks2-26-why-thirteen', 24, 'choice:Which of these would actually make an app safer for a ten year old?', array['question']::text[],
  'Which of these would actually make an app safer for a ten year old?',
  'Which of these would actually switch the shield on for a ten year old?');

do $$
declare n int; list text;
begin
  select count(*), string_agg(module || ' / ' || target, '; ') into n, list from miss;
  if n > 0 then raise exception 'MIGRATION ABORTED. % target(s) not as expected: %', n, list; end if;
end $$;

-- ── the proof: nothing on the wall is over its ceiling ───────────────────
-- The same rule the council runs (scripts/council-checks.mjs).
do $$
declare cnt int; list text;
begin
  with s as (
    select l.module_id, l.key_stage, e.ord as sn, e.slide
    from schools.school_lessons l, jsonb_array_elements(l.slides) with ordinality e(slide, ord)
  ), prose as (
    select module_id, key_stage, sn,
      case slide->>'type'
        when 'title' then concat_ws(' ', slide->>'title', slide->>'body')
        when 'concept' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'tryit' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'recap' then slide->>'heading'
        when 'keywords' then slide->>'heading'
        when 'digi' then slide->>'heading'
        when 'diagram' then concat_ws(' ', slide->>'heading', slide->>'caption')
        else null end as text
    from s
  ), over as (
    select module_id, sn, array_length(regexp_split_to_array(btrim(text), '\s+'), 1) as words
    from prose where text is not null
      and array_length(regexp_split_to_array(btrim(text), '\s+'), 1) > case key_stage when 'EYFS' then 12 when 'KS1' then 12 else 105 end
  )
  select count(*), string_agg(module_id || ' s' || sn || ' (' || words || ')', '; ') into cnt, list from over;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % slide(s) still over the wall ceiling: %', cnt, list; end if;
end $$;

-- ── the proof: every attested phrase the batch's modules are named on still holds ──
-- 7 phrase checks (shared/schools-rshe-2026.ts, mode any: at least one of
-- the requirement's modules carries it; shared/schools-computing-pos.ts, mode all:
-- every named module carries it), the same lower(text) test the two guards run.
do $$
declare cnt int; list text;
begin
  with probe(rid, phrase, mods, mode) as (values
    ('RSHE-P-OSA-3', 'thirteen is a real rule', array['ks2-26-why-thirteen']::text[], 'any'),
    ('RSHE-P-OSA-3', 'the protections are wired to the number', array['ks2-26-why-thirteen']::text[], 'any'),
    ('RSHE-P-OSA-3', 'who can reach you', array['ks2-26-why-thirteen']::text[], 'any'),
    ('RSHE-P-WO-5', 'games carry numbers too', array['ks2-26-why-thirteen','ks2-05-gaming-time-spend']::text[], 'any'),
    ('RSHE-P-WO-5', 'gambling sites', array['ks2-26-why-thirteen','ks2-05-gaming-time-spend']::text[], 'any'),
    ('RSHE-P-WO-5', 'find the number, ask what it is for', array['ks2-26-why-thirteen','ks2-05-gaming-time-spend']::text[], 'any'),
    ('RSHE-S-OSA-15', 'chatbot', array['ks3-22-when-an-ai-acts-like-a-friend','ks5-20-ai-mastery-data-rights','ks3-24-is-it-doing-my-thinking']::text[], 'any')
  ), sl as (select l.module_id, lower(l.slides::text) as txt from schools.school_lessons l),
  per as (select p.rid, p.phrase, p.mode, m as module_id, coalesce(position(lower(p.phrase) in sl.txt) > 0, false) as hit
    from probe p, unnest(p.mods) m left join sl on sl.module_id = m),
  bad as (
    select rid, phrase, module_id from per where mode = 'all' and not hit
    union all
    select rid, phrase, null::text from per where mode = 'any' group by rid, phrase having not bool_or(hit))
  select count(*), string_agg(rid || ': ' || phrase || coalesce(' in ' || module_id, ''), '; ') into cnt, list from bad;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % attested phrase(s) lost: %', cnt, list; end if;
end $$;

-- ── the proof: ks3-24-is-it-doing-my-thinking equals content/modules/ks3-24-is-it-doing-my-thinking.json ──
-- 335_must_findings_10
--
-- ks3-24-is-it-doing-my-thinking was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/335_must_findings_10.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 31 slides, 486 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks3-24-is-it-doing-my-thinking' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks3-24-is-it-doing-my-thinking' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks3-24-is-it-doing-my-thinking' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks3-24-is-it-doing-my-thinking' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks3-24-is-it-doing-my-thinking' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks3-24-is-it-doing-my-thinking' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks3-24-is-it-doing-my-thinking'
  union all
  select title from schools.school_lessons where module_id = 'ks3-24-is-it-doing-my-thinking'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks3-24-is-it-doing-my-thinking'
  union all
  select year_band from schools.school_lessons where module_id = 'ks3-24-is-it-doing-my-thinking'
  union all
  select audience from schools.school_lessons where module_id = 'ks3-24-is-it-doing-my-thinking'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks3-24-is-it-doing-my-thinking'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks3-24-is-it-doing-my-thinking'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks3-24-is-it-doing-my-thinking'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks3-24-is-it-doing-my-thinking'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks3-24-is-it-doing-my-thinking'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks3-24-is-it-doing-my-thinking'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks3-24-is-it-doing-my-thinking';
  if got_slides is distinct from 31
     or got_n is distinct from 486
     or got_hash is distinct from 'e3a23c1063e9ff211019bd39910583ab' then
    raise exception '335_must_findings_10: ks3-24-is-it-doing-my-thinking is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

-- ── the proof: ks2-25-stay-the-maker equals content/modules/ks2-25-stay-the-maker.json ──
-- 335_must_findings_10
--
-- ks2-25-stay-the-maker was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/335_must_findings_10.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 31 slides, 472 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks2-25-stay-the-maker' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks2-25-stay-the-maker' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks2-25-stay-the-maker' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks2-25-stay-the-maker' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks2-25-stay-the-maker' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks2-25-stay-the-maker' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks2-25-stay-the-maker'
  union all
  select title from schools.school_lessons where module_id = 'ks2-25-stay-the-maker'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks2-25-stay-the-maker'
  union all
  select year_band from schools.school_lessons where module_id = 'ks2-25-stay-the-maker'
  union all
  select audience from schools.school_lessons where module_id = 'ks2-25-stay-the-maker'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks2-25-stay-the-maker'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks2-25-stay-the-maker'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks2-25-stay-the-maker'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks2-25-stay-the-maker'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks2-25-stay-the-maker'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks2-25-stay-the-maker'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks2-25-stay-the-maker';
  if got_slides is distinct from 31
     or got_n is distinct from 472
     or got_hash is distinct from '5796cfbd3d392296d3629f4c8eb7ebb7' then
    raise exception '335_must_findings_10: ks2-25-stay-the-maker is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

-- ── the proof: ks2-26-why-thirteen equals content/modules/ks2-26-why-thirteen.json ──
-- 335_must_findings_10
--
-- ks2-26-why-thirteen was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/335_must_findings_10.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 31 slides, 441 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks2-26-why-thirteen' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks2-26-why-thirteen' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks2-26-why-thirteen' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks2-26-why-thirteen' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks2-26-why-thirteen' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks2-26-why-thirteen' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks2-26-why-thirteen'
  union all
  select title from schools.school_lessons where module_id = 'ks2-26-why-thirteen'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks2-26-why-thirteen'
  union all
  select year_band from schools.school_lessons where module_id = 'ks2-26-why-thirteen'
  union all
  select audience from schools.school_lessons where module_id = 'ks2-26-why-thirteen'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks2-26-why-thirteen'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks2-26-why-thirteen'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks2-26-why-thirteen'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks2-26-why-thirteen'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks2-26-why-thirteen'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks2-26-why-thirteen'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks2-26-why-thirteen';
  if got_slides is distinct from 31
     or got_n is distinct from 441
     or got_hash is distinct from '9e841811877c637b43c5998db46c2fe7' then
    raise exception '335_must_findings_10: ks2-26-why-thirteen is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

commit;
