-- 336: the lesson review, batch 11 of 11: ks3-27-when-it-turns-on-you, ks4-28-the-money-and-the-odds
--
-- Generated by scripts/gen-review-batch.mjs from the verified findings in
-- ../../../tmp/claude-0/-home-user-guided-childhood/c93e2e38-cb42-5d4e-9d75-365c993da6a1/scratchpad/lesson-review/must-all. One reviewer and one verifier per lesson against
-- scripts/lesson-rubric.md; only edits the verifier accepted are here, and
-- every one was checked on the module JSON before this file was written:
-- exact current text, no dashes, inside the wall ceiling, every attested
-- phrase kept, the module contract no worse. The same checks run again below,
-- on the server, and any miss aborts the whole batch.
--
-- THE EDITS (9)
--   ks3-27-when-it-turns-on-you s9 mode [E20 must]: The player knows only pairs, groups and class, so mode whole falls through to the label Talk to your partner on the wall while the script runs it as sixty seconds whole class.
--   ks3-27-when-it-turns-on-you s7 script [E22 must]: The player shuffles the options every run, so the third option the script names as the victim blaming trap is a different chip on the wall in most rooms; the script also has no think pause before the vote.
--   ks3-27-when-it-turns-on-you s14 script [E22 must]: The first option the script tells the teacher to handle warmly is not first on a shuffled wall, and the script never says how everyone answers or where the three seconds go.
--   ks3-27-when-it-turns-on-you s17 script [E22 must]: The third option the script asks the teacher to treat with respect is dealt to a different position each run, and the script has no whole class method or think pause.
--   ks3-27-when-it-turns-on-you s26 script [E22 must]: The second option the script watches for is the nastier people misconception, which the shuffle puts anywhere on the wall, so the teacher's one extra sentence can land on the wrong chip.
--   ks3-27-when-it-turns-on-you s18 caption [E34 must]: AND in capitals is emphasis by capitals, which the BDA style guide the rubric adopts rules out for dyslexic readers; the emphasis belongs in a short sentence instead.
--   ks4-28-the-money-and-the-odds s6 body [E44 must]: The wall says the hidden price is worth about a pound extra per purchase to whoever built it, a figure with no source anywhere in the evidence base and not derivable from the £4.99 example on the board, so the first thing a sharp pupil asks is where the pound comes from and the teacher has no answer.
--   ks4-28-the-money-and-the-odds s22 config/items/1/why [E44 must]: The reveal says the online slot is the product that does the most harm, which the lesson's own evidence base contradicts twice: the speed and harm link is an association not a cause, and the Gambling Commission's highest problem rate was for a slow product; slide 16 and the second prove question are careful about this and the sort undoes them.
--   ks4-28-the-money-and-the-odds s7 script [E47 must]: The script tells the teacher to ask whether anybody has ever had a balance they could not spend, which is asking who buys crates in a lesson whose title script and teacher tip both forbid exactly that, and it has no think pause before hands go up.

begin;

create table schools.school_lessons_backup_336 as select * from schools.school_lessons;
alter table schools.school_lessons_backup_336 enable row level security;

create temp table miss(module text, target text);

-- One string on one slide, proven by the slide's type and heading and by its
-- exact current text. Anything else is a miss, and a miss aborts everything.
create or replace function schools.review_set_336(p_module text, p_pos int, p_ident text, p_path text[], p_expect text, p_new text)
returns void language plpgsql as $$
declare cur text; have text;
begin
  select (l.slides->p_pos->>'type') || ':' || coalesce(l.slides->p_pos->>'heading', l.slides->p_pos->>'title', l.slides->p_pos->>'question', l.slides->p_pos->>'prompt', l.slides->p_pos->>'component', '')
    into have from schools.school_lessons l where l.module_id = p_module;
  if have is distinct from p_ident then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' is ' || coalesce(have, 'absent') || ', expected ' || p_ident); return; end if;
  select l.slides #>> (array[p_pos::text] || p_path) into cur from schools.school_lessons l where l.module_id = p_module;
  if cur is null or cur <> p_expect then insert into miss values (p_module, 'slide ' || (p_pos + 1) || ' ' || array_to_string(p_path, '/') || ' is not the expected text'); return; end if;
  update schools.school_lessons l set slides = jsonb_set(l.slides, array[p_pos::text] || p_path, to_jsonb(p_new)) where l.module_id = p_module;
end $$;

-- ks3-27-when-it-turns-on-you s9 mode [E20]
select schools.review_set_336('ks3-27-when-it-turns-on-you', 8, 'discussion:Why is it so much harder to be the first one to say stop than the second?', array['mode']::text[],
  'whole',
  'class');

-- ks3-27-when-it-turns-on-you s7 script [E22]
select schools.review_set_336('ks3-27-when-it-turns-on-you', 6, 'choice:A joke about Sam lands in a chat of forty. Within an hour there are thirty replies. What actually made it grow?', array['script']::text[],
  'Whole class, hands or devices. The third option is the victim blaming trap and some pupils will pick it honestly. Do not mock anyone: use its feedback out loud, name the move as old and common, and go straight on. Do not let this become a discussion of a real chat.',
  'Ten seconds of quiet thinking, then whole class, hands or devices. The option that blames Sam for replying is the victim blaming trap and some pupils will pick it honestly. Do not mock anyone: use its feedback out loud, name the move as old and common, and go straight on. Do not let this become a discussion of a real chat.');

-- ks3-27-when-it-turns-on-you s14 script [E22]
select schools.review_set_336('ks3-27-when-it-turns-on-you', 13, 'choice:What is actually happening in those messages?', array['script']::text[],
  'The first option is the important one and some pupils will pick it sincerely, because it is genuinely how it feels from inside. Give that feedback fully and warmly. Care does not need to check up on you is the sentence to leave on the screen. If anything in the room tells you this is live for a pupil, follow it up afterwards under your safeguarding policy, not now.',
  'Ten seconds of quiet, then everyone votes, fingers or devices. The option that says someone cares a lot is the important one and some pupils will pick it sincerely, because it is genuinely how it feels from inside. Give that feedback fully and warmly. Care does not need to check up on you is the sentence to leave on the screen. If anything in the room tells you this is live for a pupil, follow it up afterwards under your safeguarding policy, not now.');

-- ks3-27-when-it-turns-on-you s17 script [E22]
select schools.review_set_336('ks3-27-when-it-turns-on-you', 16, 'choice:Which is the most useful thing to do first, the moment you realise it is a pattern?', array['script']::text[],
  'The third option is chosen honestly by pupils who feel the injustice of it, so treat that feeling with respect before you correct it. Wanting people to know is fair. Telling everyone feeds exactly the machine they just learned about, and it also makes the adult''s job harder.',
  'Ten seconds of quiet, then everyone votes with fingers. The tell everyone option is chosen honestly by pupils who feel the injustice of it, so treat that feeling with respect before you correct it. Wanting people to know is fair. Telling everyone feeds exactly the machine they just learned about, and it also makes the adult''s job harder.');

-- ks3-27-when-it-turns-on-you s26 script [E22]
select schools.review_set_336('ks3-27-when-it-turns-on-you', 25, 'choice:Exit check. What makes online conflict grow faster than the same thing said out loud?', array['script']::text[],
  'Ten seconds of quiet thinking, then vote. If a lot of the room takes the second option, that is worth one more sentence: it is a comforting answer because it makes it somebody else''s fault, and it leaves you with no plan.',
  'Ten seconds of quiet thinking, then vote. If a lot of the room takes the nastier people option, that is worth one more sentence: it is a comforting answer because it makes it somebody else''s fault, and it leaves you with no plan.');

-- ks3-27-when-it-turns-on-you s18 caption [E34]
select schools.review_set_336('ks3-27-when-it-turns-on-you', 17, 'diagram:Where to take it', array['caption']::text[],
  'Report inside the app AND tell a person. The app can remove it. Only a person can change what happens next.',
  'Report inside the app and tell a person. Both, not one or the other. The app can remove it. Only a person can change what happens next.');

-- ks4-28-the-money-and-the-odds s6 body [E44]
select schools.review_set_336('ks4-28-the-money-and-the-odds', 5, 'concept:The price you actually paid', array['body']::text[],
  'Buy anything normally and one number tells you what it cost. A game that sells chances puts two conversions in the way. Your pounds become gems, and gems become an opening. By the time you reach the opening, the price is quoted in a currency that exists nowhere else and that nothing outside the game can price. That is not clumsy design. That is the design, and it is worth about a pound extra per purchase to whoever built it.',
  'Buy anything normally and one number tells you what it cost. A game that sells chances puts two conversions in the way. Your pounds become gems, and gems become an opening. By the time you reach the opening, the price is quoted in a currency that exists nowhere else and that nothing outside the game can price. That is not clumsy design. That is the design, and the stranded leftover it produces is what sells the next pack.');

-- ks4-28-the-money-and-the-odds s22 config/items/1/why [E44]
select schools.review_set_336('ks4-28-the-money-and-the-odds', 21, 'interactive:verdict-sort', array['config','items','1','why']::text[],
  'The fastest loop, with no closing time and nobody in the room. This is the product that does the most harm, and it is perfectly legal for adults.',
  'The fastest loop, with no closing time and nobody in the room. This is the product the law caps hardest and the one linked with more harm, and it is perfectly legal for adults.');

-- ks4-28-the-money-and-the-odds s7 script [E47]
select schools.review_set_336('ks4-28-the-money-and-the-odds', 6, 'choice:Why is the pack 500 gems when a crate costs 80?', array['script']::text[],
  'Whole class, hands or devices. Most rooms get this one once the leftover is on the board, and the moment it lands is worth pausing on. Ask whether anybody has ever had a balance they could not spend. Take two answers, no more, and move.',
  'Whole class, hands or devices, and ten seconds of thinking time before anybody shows an answer. Most rooms get this one once the leftover is on the board, and the moment it lands is worth pausing on. Ask which games they know of where a balance like that would sit there, which keeps it about the game rather than about anybody in the room. Take two answers, no more, and move.');

do $$
declare n int; list text;
begin
  select count(*), string_agg(module || ' / ' || target, '; ') into n, list from miss;
  if n > 0 then raise exception 'MIGRATION ABORTED. % target(s) not as expected: %', n, list; end if;
end $$;

-- ── the proof: nothing on the wall is over its ceiling ───────────────────
-- The same rule the council runs (scripts/council-checks.mjs).
do $$
declare cnt int; list text;
begin
  with s as (
    select l.module_id, l.key_stage, e.ord as sn, e.slide
    from schools.school_lessons l, jsonb_array_elements(l.slides) with ordinality e(slide, ord)
  ), prose as (
    select module_id, key_stage, sn,
      case slide->>'type'
        when 'title' then concat_ws(' ', slide->>'title', slide->>'body')
        when 'concept' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'tryit' then concat_ws(' ', slide->>'heading', slide->>'body')
        when 'recap' then slide->>'heading'
        when 'keywords' then slide->>'heading'
        when 'digi' then slide->>'heading'
        when 'diagram' then concat_ws(' ', slide->>'heading', slide->>'caption')
        else null end as text
    from s
  ), over as (
    select module_id, sn, array_length(regexp_split_to_array(btrim(text), '\s+'), 1) as words
    from prose where text is not null
      and array_length(regexp_split_to_array(btrim(text), '\s+'), 1) > case key_stage when 'EYFS' then 12 when 'KS1' then 12 else 105 end
  )
  select count(*), string_agg(module_id || ' s' || sn || ' (' || words || ')', '; ') into cnt, list from over;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % slide(s) still over the wall ceiling: %', cnt, list; end if;
end $$;

-- ── the proof: every attested phrase the batch's modules are named on still holds ──
-- 25 phrase checks (shared/schools-rshe-2026.ts, mode any: at least one of
-- the requirement's modules carries it; shared/schools-computing-pos.ts, mode all:
-- every named module carries it), the same lower(text) test the two guards run.
do $$
declare cnt int; list text;
begin
  with probe(rid, phrase, mods, mode) as (values
    ('RSHE-S-OSA-9', 'three brakes', array['ks3-27-when-it-turns-on-you']::text[], 'any'),
    ('RSHE-S-OSA-9', 'why it gets bigger online', array['ks3-27-when-it-turns-on-you']::text[], 'any'),
    ('RSHE-S-OSA-9', 'name it, save it, say it', array['ks3-27-when-it-turns-on-you']::text[], 'any'),
    ('RSHE-S-OSA-10', 'harassment', array['ks3-27-when-it-turns-on-you']::text[], 'any'),
    ('RSHE-S-OSA-10', 'coercive control', array['ks3-27-when-it-turns-on-you']::text[], 'any'),
    ('RSHE-S-OSA-10', 'stalking is being followed', array['ks3-27-when-it-turns-on-you']::text[], 'any'),
    ('RSHE-S-OSA-10', 'four things with real names', array['ks3-27-when-it-turns-on-you']::text[], 'any'),
    ('RSHE-S-WO-3', 'name it, save it, say it', array['ks3-27-when-it-turns-on-you','ks4-29-did-not-go-looking']::text[], 'any'),
    ('RSHE-S-WO-3', 'report and block', array['ks3-27-when-it-turns-on-you','ks4-29-did-not-go-looking']::text[], 'any'),
    ('RSHE-S-WO-3', 'childline on 0800 1111', array['ks3-27-when-it-turns-on-you','ks4-29-did-not-go-looking']::text[], 'any'),
    ('RSHE-S-WO-3', 'what helps afterwards', array['ks3-27-when-it-turns-on-you','ks4-29-did-not-go-looking']::text[], 'any'),
    ('RSHE-S-WO-4', 'loot box', array['ks4-28-the-money-and-the-odds','ks2-05-gaming-time-spend']::text[], 'any'),
    ('RSHE-S-WO-4', 'house edge', array['ks4-28-the-money-and-the-odds','ks2-05-gaming-time-spend']::text[], 'any'),
    ('RSHE-S-WO-4', 'how fast is the loop', array['ks4-28-the-money-and-the-odds','ks2-05-gaming-time-spend']::text[], 'any'),
    ('RSHE-S-WO-4', 'borrowing', array['ks4-28-the-money-and-the-odds','ks2-05-gaming-time-spend']::text[], 'any'),
    ('RSHE-S-RR-6', 'bystander', array['ks3-27-when-it-turns-on-you','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-S-RR-6', 'the quiet majority is the whole audience', array['ks3-27-when-it-turns-on-you','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-S-RR-6', 'bullying is repeated, aimed at one person', array['ks3-27-when-it-turns-on-you','ks2-08-kind-safe-online']::text[], 'any'),
    ('RSHE-S-MW-8', 'linked with anxiety and with depression', array['ks4-28-the-money-and-the-odds']::text[], 'any'),
    ('RSHE-S-MW-8', 'what it does to a person', array['ks4-28-the-money-and-the-odds']::text[], 'any'),
    ('RSHE-S-MW-8', '0808 8020 133', array['ks4-28-the-money-and-the-odds']::text[], 'any'),
    ('RSHE-S-MW-8', 'speed is what the law acts on', array['ks4-28-the-money-and-the-odds']::text[], 'any'),
    ('CPOS-KS3-9', 'report and block', array['ks3-27-when-it-turns-on-you']::text[], 'all'),
    ('CPOS-KS3-9', 'name it, save it, say it', array['ks3-27-when-it-turns-on-you']::text[], 'all'),
    ('CPOS-KS3-9', 'harassment', array['ks3-27-when-it-turns-on-you']::text[], 'all')
  ), sl as (select l.module_id, lower(l.slides::text) as txt from schools.school_lessons l),
  per as (select p.rid, p.phrase, p.mode, m as module_id, coalesce(position(lower(p.phrase) in sl.txt) > 0, false) as hit
    from probe p, unnest(p.mods) m left join sl on sl.module_id = m),
  bad as (
    select rid, phrase, module_id from per where mode = 'all' and not hit
    union all
    select rid, phrase, null::text from per where mode = 'any' group by rid, phrase having not bool_or(hit))
  select count(*), string_agg(rid || ': ' || phrase || coalesce(' in ' || module_id, ''), '; ') into cnt, list from bad;
  if cnt > 0 then raise exception 'MIGRATION ABORTED. % attested phrase(s) lost: %', cnt, list; end if;
end $$;

-- ── the proof: ks3-27-when-it-turns-on-you equals content/modules/ks3-27-when-it-turns-on-you.json ──
-- 336_must_findings_11
--
-- ks3-27-when-it-turns-on-you was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/336_must_findings_11.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 31 slides, 446 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks3-27-when-it-turns-on-you' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks3-27-when-it-turns-on-you' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks3-27-when-it-turns-on-you' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks3-27-when-it-turns-on-you' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks3-27-when-it-turns-on-you' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks3-27-when-it-turns-on-you' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks3-27-when-it-turns-on-you'
  union all
  select title from schools.school_lessons where module_id = 'ks3-27-when-it-turns-on-you'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks3-27-when-it-turns-on-you'
  union all
  select year_band from schools.school_lessons where module_id = 'ks3-27-when-it-turns-on-you'
  union all
  select audience from schools.school_lessons where module_id = 'ks3-27-when-it-turns-on-you'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks3-27-when-it-turns-on-you'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks3-27-when-it-turns-on-you'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks3-27-when-it-turns-on-you'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks3-27-when-it-turns-on-you'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks3-27-when-it-turns-on-you'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks3-27-when-it-turns-on-you'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks3-27-when-it-turns-on-you';
  if got_slides is distinct from 31
     or got_n is distinct from 446
     or got_hash is distinct from '44b95eece9f84fe0b698e9f69506ece3' then
    raise exception '336_must_findings_11: ks3-27-when-it-turns-on-you is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

-- ── the proof: ks4-28-the-money-and-the-odds equals content/modules/ks4-28-the-money-and-the-odds.json ──
-- 336_must_findings_11
--
-- ks4-28-the-money-and-the-odds was carried into production in hash verified chunks
-- (scripts/module-to-chunks.mjs, proved by scripts/module-string-hash.mjs)
-- rather than as one statement, because a module migration is forty to
-- seventy thousand characters and the Supabase tool cannot carry that
-- reliably. The migration itself is supabase/migrations/336_must_findings_11.sql in
-- the repository. This entry is the executable proof that the row arrived
-- intact: 31 slides, 481 strings, and the multiset hash the
-- source JSON produces. It raises if anything differs, which also makes it
-- fail loudly if anybody later edits the row by hand.
do $$
declare
  got_hash text;
  got_n int;
  got_slides int;
begin
  select md5(string_agg(md5(v), '' order by md5(v))), count(*)
    into got_hash, got_n
  from (
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.slides, '$.**') as x
  where l.module_id = 'ks4-28-the-money-and-the-odds' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.video_beats, '$.**') as x
  where l.module_id = 'ks4-28-the-money-and-the-odds' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.assessment, '$.**') as x
  where l.module_id = 'ks4-28-the-money-and-the-odds' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.parent_note, '$.**') as x
  where l.module_id = 'ks4-28-the-money-and-the-odds' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.teacher_notes, '$.**') as x
  where l.module_id = 'ks4-28-the-money-and-the-odds' and jsonb_typeof(x) = 'string'
  union all
  select x #>> '{}' as v from schools.school_lessons l, lateral jsonb_path_query(l.dsl_note, '$.**') as x
  where l.module_id = 'ks4-28-the-money-and-the-odds' and jsonb_typeof(x) = 'string'
  union all
  select module_id from schools.school_lessons where module_id = 'ks4-28-the-money-and-the-odds'
  union all
  select title from schools.school_lessons where module_id = 'ks4-28-the-money-and-the-odds'
  union all
  select key_stage from schools.school_lessons where module_id = 'ks4-28-the-money-and-the-odds'
  union all
  select year_band from schools.school_lessons where module_id = 'ks4-28-the-money-and-the-odds'
  union all
  select audience from schools.school_lessons where module_id = 'ks4-28-the-money-and-the-odds'
  union all
  select evidence_anchor from schools.school_lessons where module_id = 'ks4-28-the-money-and-the-odds'
  union all
  select single_action_outcome from schools.school_lessons where module_id = 'ks4-28-the-money-and-the-odds'
  union all
  select character_cast from schools.school_lessons where module_id = 'ks4-28-the-money-and-the-odds'
  union all
  select scaffold from schools.school_lessons where module_id = 'ks4-28-the-money-and-the-odds'
  union all
  select unnest(statutory_hooks) from schools.school_lessons where module_id = 'ks4-28-the-money-and-the-odds'
  union all
  select unnest(ailit_domains) from schools.school_lessons where module_id = 'ks4-28-the-money-and-the-odds'
  ) q;
  select jsonb_array_length(slides) into got_slides
  from schools.school_lessons where module_id = 'ks4-28-the-money-and-the-odds';
  if got_slides is distinct from 31
     or got_n is distinct from 481
     or got_hash is distinct from 'a1fbf9423a91bf27b869b83a41b9b314' then
    raise exception '336_must_findings_11: ks4-28-the-money-and-the-odds is not intact (slides %, strings %, hash %)',
      got_slides, got_n, got_hash;
  end if;
end $$;

commit;
