-- Guided Childhood: Builder stage scripts (ages 8 to 10). Run after seed.sql.
insert into public.scripts
  (stage_id, title, situation, say_this, not_this, why_it_works, tonight, law_flag, is_free, sort_order)
values
(
  'builder',
  'First messaging app request',
  'Your child says all their friends are on a messaging app and asks to join so they are not left out.',
  'I can hear that this matters to you, and I want to understand it properly. Let us look at the app together this week. I will set it up with you, we will agree who you can talk to, and I will be in the loop while you learn the ropes.',
  '"No, you are too young for that." It shuts the door and teaches them to ask you for nothing next time.',
  'At this age the social brain is coming online and belonging starts to feel urgent. Refusing flat out does not remove the pull, it just moves the activity out of your sight. Joining alongside them keeps you as the guide while the habits are still forming, which is exactly when influence is highest.',
  'Sit down together and look at one app they are asking for. Ask what their friends actually do on it before you decide anything.',
  'none',
  false,
  201
),
(
  'builder',
  'Left out of the group chat',
  'Your child is upset because a group chat went on without them, or they were removed, and they feel pushed out.',
  'That stings, and it makes sense that it does. Being left out feels real in your body, not just your head. Tell me what happened, and we will work out together what you want to do next, if anything.',
  '"Just ignore it, it does not matter." It tells them their feeling is wrong and they will stop bringing these things to you.',
  'Social exclusion activates the same brain regions as physical pain, so the hurt is genuine, not dramatic. A child who feels heard can think more clearly about their next move. Dismissing the feeling teaches them to manage social pain alone, which is the opposite of what you want at this age.',
  'Ask your child to describe the moment they noticed they were left out. Just listen. Do not fix it yet.',
  'none',
  false,
  202
),
(
  'builder',
  'Roblox and Minecraft time limits',
  'Your child loses track of time in a building game and resists stopping when you ask.',
  'These games are designed to never end, so stopping is genuinely hard. Let us pick a natural finish point together, like saving your build or ending the round, and I will give you a warning before we get there.',
  '"Off now, I said so." A sudden stop mid-task feels like punishment and guarantees a fight.',
  'Open-ended games offer no built-in stopping cue, so the brain keeps chasing the next small reward. Ending on a completed task respects how the game is structured and lowers the dopamine drop. A warning gives the prefrontal cortex, still developing at this age, time to prepare for the switch.',
  'Agree one natural stopping point with your child before they start playing tonight.',
  'none',
  false,
  203
),
(
  'builder',
  'Voice chat with strangers',
  'Your child is playing an online game where they can talk to people you do not know through voice chat.',
  'I am glad you enjoy playing with others. Some of those voices belong to people we do not know, so let us set a simple rule: you can chat about the game, but anything personal, like your name, school, or where we live, stays offline. If anyone asks for that, come and get me.',
  '"You are never using voice chat, end of story." It removes the chance to teach the very judgement they will need.',
  'Children this age trust easily and cannot yet read intent from a stranger online. A clear, concrete rule about what stays private gives them a script to follow under pressure. Telling them to fetch you keeps the door open rather than driving the contact underground.',
  'Ask your child to show you how voice chat works in their game so you understand what they hear.',
  'none',
  false,
  204
),
(
  'builder',
  'Obsessed with one YouTuber',
  'Your child quotes, copies, and wants to watch one particular YouTuber or streamer constantly.',
  'You really like this person. What is it about them that you enjoy so much? I would love to understand it. Let us watch one together so I can see what you see.',
  '"That person is rubbish, turn it off." Mocking their hero feels like you are mocking them.',
  'Looking up to an older figure is a normal part of identity forming at this age. Curiosity keeps the channel of communication open, while contempt closes it and pushes the interest somewhere you cannot see. Watching together lets you notice the values being modelled and talk about them naturally.',
  'Watch one video of their favourite creator with them and ask one genuine question about it.',
  'none',
  false,
  205
),
(
  'builder',
  'Asking for their own phone',
  'Your child asks for their own phone, often because friends have one.',
  'That is a big step, and I am happy to think about it properly with you. A phone is a tool, not a prize, so let us talk about what you would actually use it for and what would help us both feel okay about it.',
  '"When you are older." A vague answer with no path forward just teaches them to keep nagging.',
  'A phone is a gateway to an open social world, and the impulse-control systems that manage that are years from mature at this age. Treating the request as a real conversation, rather than a yes or no, models thoughtful decision making. Linking it to need rather than status helps your child reason about it too.',
  'Ask your child to list three things they would use a phone for. Discuss whether each one truly needs a phone.',
  'none',
  false,
  206
),
(
  'builder',
  'Saw something unsuitable at a friend''s house',
  'Your child saw something on a screen at a friend''s house that worried or confused them.',
  'Thank you for telling me. You are not in any trouble at all. Things can pop up that feel strange or scary, and it is always okay to come to me about them. What did you see, and how did it make you feel?',
  '"You are not going to that house again." Punishing the messenger guarantees they hide the next thing.',
  'A child who is praised for disclosing learns that you are a safe place for hard information. Reacting with alarm or blame teaches them that honesty brings trouble, so they go quiet. Naming that they are not in trouble lowers the fear response and lets them actually tell you what happened.',
  'Tell your child tonight that they will never be in trouble for telling you about something they saw. Say it plainly.',
  'none',
  false,
  207
),
(
  'builder',
  'A stranger messaged them in a game',
  'Someone your child does not know sent them a message inside a game.',
  'You did the right thing showing me. Most people are fine, but we cannot tell who is who online, so the rule is simple: we do not reply to people we have not met in real life, and we tell each other. Let us look at it together.',
  '"Why were you even talking to strangers?" Blame makes them feel caught and they will stop reporting it.',
  'Children this age cannot reliably judge who is safe online because the cues they rely on in person are missing. A fixed rule removes the need for them to assess each stranger in the moment. Praising the report, rather than questioning their behaviour, makes telling you the automatic response.',
  'Practise with your child what to do if a stranger messages them: do not reply, come and show you.',
  'none',
  false,
  208
),
(
  'builder',
  'Wanting to spend real money on skins',
  'Your child wants to spend real money on skins, loot boxes, or in-game items.',
  'I get why you want it, those items look brilliant. Here is the thing: these games are built to make spending feel urgent, and some of it works like gambling. Let us set a small budget you control, so you decide on purpose rather than in the heat of the moment.',
  '"It is a waste of money, no." It ends the lesson before they learn how the spending traps actually work.',
  'Loot boxes use the same variable reward pattern as slot machines, which the developing brain finds especially hard to resist. A fixed budget moves the choice from impulse to plan and builds early financial judgement. Explaining the design, rather than just refusing, gives your child a defence they can use for years.',
  'Agree a small fixed monthly amount for in-game spending and let your child decide how to use it.',
  'none',
  false,
  209
),
(
  'builder',
  'The nightly screen-time negotiation',
  'Every evening turns into a negotiation about how much longer your child can stay on a screen.',
  'I do not enjoy the nightly haggle and I do not think you do either. Let us agree the screen time once, together, and then it is settled. When it is fixed in advance, neither of us has to argue about it every night.',
  '"Stop pushing your luck or you lose it all." Threats raise the stakes and make tomorrow night worse.',
  'Decision fatigue makes repeated nightly negotiations exhausting for everyone and erodes the boundary over time. A rule agreed in advance removes the moment-by-moment bargaining and gives your child predictability, which lowers conflict. Involving them in setting it raises the chance they will keep to it.',
  'Sit down together and agree a clear screen-time amount for school nights. Write it somewhere you both can see.',
  'none',
  false,
  210
),
(
  'builder',
  'Homework versus games',
  'Games are winning the battle against homework and getting your child to start is a daily struggle.',
  'Games are built to grab your attention, and homework is not, so it makes sense that one feels easier to start. Let us agree the order: schoolwork first, then the game is yours with no nagging from me. That way the fun is something to look forward to, not something I have to take away.',
  '"No games until I see straight As." Linking play to grades turns every result into a fight.',
  'Games deliver fast, reliable rewards while homework delivers slow, uncertain ones, so the brain naturally prefers the game. Putting effort before reward uses the game as a motivator rather than a battleground. Removing the nagging once the work is done makes the deal feel fair and keeps you out of the policing role.',
  'Agree the homework-then-game order with your child and commit to not nagging once they start the work.',
  'none',
  false,
  211
),
(
  'builder',
  'Comparing themselves to friends online',
  'Your child seems anxious or down after comparing what they have or do with friends they see online.',
  'It is easy to feel behind when you only see everyone''s best bits. What people post is the highlight, not the whole story. Tell me what you have been comparing, and let us look at it honestly together.',
  '"Do not be silly, you have loads." Brushing it off tells them their worry is daft and they will hide it.',
  'Children this age increasingly measure themselves against peers, and online feeds show curated highlights that no real life can match. Naming the gap between the highlight and the whole story gives them a tool to question what they see. Dismissing the feeling leaves the comparison running silently underneath.',
  'Ask your child what they have felt left behind by lately. Just listen and name how common that feeling is.',
  'none',
  false,
  212
),
(
  'builder',
  'Setting a family technology agreement',
  'You want to set shared rules about devices that apply to the whole family, not just your child.',
  'Let us make a family agreement about screens, and it includes me too. We will write down a few simple rules we all keep, like no phones at the table. If I break one, you can call me on it.',
  '"These are the rules, learn them." Rules handed down without buy-in feel like control and invite rebellion.',
  'Children follow what is modelled far more than what is instructed, so rules that include the adults carry real weight. Building the agreement together gives your child ownership, which raises the chance they will keep to it. A shared standard also removes the sense that screens are a battle between you and them.',
  'Write three simple device rules together that apply to every person in the house, adults included.',
  'none',
  false,
  213
),
(
  'builder',
  'Witnessing someone being cyberbullied',
  'Your child saw someone being picked on in a group chat or game and is not sure what to do.',
  'It takes courage to even notice that and feel uneasy about it. You do not have to fix it alone. You can refuse to join in, you can message the person privately to check they are okay, and you can tell me or a teacher. Which of those feels possible for you?',
  '"Stay out of it, it is not your problem." It teaches them that looking away is the safe choice.',
  'Bystanders shape whether cruelty spreads or stops, and children this age are forming their sense of fairness and courage. Offering several small, safe actions makes helping feel possible rather than overwhelming. Telling them to stay out of it trains the habit of disengaging, which is hard to undo later.',
  'Talk through one small thing your child could do if they see someone being picked on online.',
  'none',
  false,
  214
),
(
  'builder',
  'The everyone has it argument',
  'Your child argues that everyone has a particular game, app, or device, so they should too.',
  'You might be right that lots of friends have it. Everyone having something does not automatically make it right for our family, but it does tell me it matters to you. Let us look at it on its own merits, just you and me.',
  '"I do not care what everyone else has." It dismisses a real social pressure they are genuinely feeling.',
  'The pull to match the group is strong at this age and is a normal part of fitting in, not manipulation. Acknowledging the pressure as real, while still deciding on your own terms, models how to hold a value under social pressure. Flat dismissal teaches them that you do not take their world seriously.',
  'Ask your child why this particular thing matters to them, beyond the fact that others have it.',
  'none',
  false,
  215
),
(
  'builder',
  'Devices and sleep',
  'Screens are creeping into the bedroom and your child is harder to settle and wake.',
  'Sleep is when your brain sorts out everything from the day, and screens make it harder to switch off. Let us agree that devices go to bed in the kitchen, not your room. I will charge mine there too, so we are doing it together.',
  '"Give it here, no screens in bed." Confiscation framing makes it a punishment instead of a shared habit.',
  'Screen light and the alertness games create both delay the wind-down the brain needs for sleep. Keeping devices out of the bedroom removes the temptation rather than relying on willpower at the moment they are most tired. Charging yours alongside theirs turns a rule into a family habit, which holds far better.',
  'Set up one charging spot outside the bedrooms tonight and put your own phone there too.',
  'none',
  false,
  216
),
(
  'builder',
  'Early body image messages from media',
  'Your child is picking up messages from media about how bodies should look, and starting to repeat them.',
  'I noticed what you said about how someone looks. A lot of what we see on screens is edited, filtered, or chosen to sell something. Bodies in real life come in every shape, and that is normal. What made you think about it?',
  '"Do not say things like that." Shutting it down stops the comment but not the belief underneath.',
  'Body image attitudes start forming early, and media presents a narrow, often altered ideal as if it were normal. Naming that images are edited gives your child a lens to question what they see rather than absorb it. Closing the conversation leaves the belief in place and signals that the topic is off limits with you.',
  'Point out one edited or filtered image with your child and talk about how it differs from real life.',
  'none',
  false,
  217
);
