-- Guided Childhood: Explorer stage scripts (ages 11 to 13). Run after seed.sql.
insert into public.scripts
  (stage_id, title, situation, say_this, not_this, why_it_works, tonight, law_flag, is_free, sort_order)
values
(
  'explorer',
  'The first serious social media request',
  'Your 11, 12, or 13 year old asks, seriously and repeatedly, to join Instagram, TikTok, or Snapchat because everyone in their year is on it.',
  'I can hear that this matters to you, and being left out of where your friends are is a real thing, not a small thing. I do not want to give you a yes or a no in the next ten seconds. I want us to actually look at it together first and decide properly.',
  'No. You are far too young and that is the end of it.',
  'A flat refusal at this age does not stop access, it moves it out of your sight onto a friend''s phone. The adolescent brain is wired to prioritise peer belonging, so the social cost of exclusion is felt as genuine threat. Slowing the decision down, rather than slamming it shut, keeps you in the room for every choice that follows.',
  'Tonight, ask them which platform matters most and why. Just listen. Do not decide anything yet.',
  'partial_ban',
  false,
  301
),
(
  'explorer',
  'Explaining how the algorithm decides what they see',
  'Your child believes their feed simply shows them what is popular or what their friends like, and has never questioned how it is chosen.',
  'Here is something most adults do not even know. Nobody at the company chose what is on your feed. A system watched what made you pause, and now it shows you more of that, on purpose, to keep you there longer. That is worth understanding, because once you see it you can see past it.',
  'It is all fake and designed to manipulate you, so do not believe any of it.',
  'Naming the mechanism gives a young person genuine power rather than fear. The developing prefrontal cortex is building the capacity for abstract reasoning at this stage, so they are newly able to grasp how a system optimises for attention. Understanding the design is what lets them resist it, far more than being warned that it is bad.',
  'Tonight, open your own feed and ask them to guess why each of the first five posts was chosen for you.',
  'none',
  false,
  302
),
(
  'explorer',
  'Walking through their feed together',
  'You want to understand what your child actually sees and experiences when they scroll, rather than guessing or assuming the worst.',
  'Would you show me round your feed for ten minutes. I am not checking up on you and I am not going to comment on every single thing. I genuinely want to see what it is like to be in there, because I cannot understand it from the outside.',
  'Hand me your phone, I want to see exactly what you have been looking at.',
  'There is a difference between being invited in and being inspected, and adolescents are acutely sensitive to which one is happening. Heightened social awareness means they read your intent before they read your words. Curiosity opens the feed to you. Surveillance closes it, and teaches them to keep a cleaner version for you and a real one for themselves.',
  'Tonight, ask for a guided tour, not an inspection. Let them be the expert for once.',
  'none',
  false,
  303
),
(
  'explorer',
  'Influencers and body image',
  'Your child is following accounts that present highly edited or idealised bodies, and is starting to compare themselves to them.',
  'A lot of what you are seeing has been lit, posed, filtered, and chosen out of hundreds of attempts. I am not saying that to be a downer. I am saying it because your body is changing fast right now, and it is unfair to measure a changing real body against a finished, edited image.',
  'You do not need to look like them, just stop following accounts that make you feel bad.',
  'At this stage the body is changing rapidly and self-image is forming around social comparison, which adolescents are biologically primed to do. Pointing out the construction behind the image, calmly and without panic, restores a sense of proportion. Telling them simply to unfollow skips the understanding that makes the choice stick.',
  'Tonight, find one before and after editing video together and just notice the gap. No lecture needed.',
  'none',
  false,
  304
),
(
  'explorer',
  'Setting up a first smartphone',
  'Your child is getting their own smartphone for the first time and you are deciding together how it will work.',
  'This is your phone now, and I want it to actually be yours. So let us set it up together this once. We will turn off the bits designed to hook you, agree where it sleeps at night, and write down what we both expect. Then it is yours to look after.',
  'There are going to be a lot of rules and I will be checking it whenever I want.',
  'The first setup sets the tone for years, and doing it as a shared project rather than a handover with conditions builds ownership. The adolescent brain responds far better to autonomy framed with structure than to control. Notifications and infinite feeds exploit dopamine driven novelty seeking, so dialling those down at the start is the single most useful thing you can do.',
  'Tonight, turn off non-essential notifications together and agree where the phone charges overnight.',
  'none',
  false,
  305
),
(
  'explorer',
  'Being left out of a group chat',
  'Your child discovers they have been removed from, or deliberately left out of, a group chat and is hurt by it.',
  'That really stings, and it is meant to. Being shut out of where your friends are talking is one of the most painful things at your age, and I am not going to pretend it is no big deal. I am here. Do you want to talk about what happened or just sit with it for a bit.',
  'It is only a group chat, just ignore them and find better friends.',
  'Social exclusion activates the same brain regions as physical pain, and at this age the wiring that makes belonging feel urgent is at its peak. Minimising the hurt teaches them you do not understand the stakes, so they stop bringing things to you. Naming the pain as real is what keeps the door open.',
  'Tonight, validate the feeling before offering any solution. Sometimes being heard is the whole repair.',
  'none',
  false,
  306
),
(
  'explorer',
  'Late-night scrolling and sleep',
  'You realise your child is scrolling late into the night and is exhausted, foggy, or short-tempered in the mornings.',
  'I am not raising this to take anything away. I am raising it because your sleep is taking a hit, and at your age sleep is doing huge work on your mood and your brain. Let us sort out how the phone can rest somewhere at night so you actually get that sleep.',
  'You are on that thing all night, no wonder you are a nightmare in the mornings.',
  'Adolescent sleep need is high and their body clock naturally shifts later, so a glowing, endlessly novel feed at bedtime is working directly against their biology. Sleep loss at this stage feeds low mood and poor focus. Framing it as protecting their sleep, not policing their phone, keeps it a shared problem rather than a battle.',
  'Tonight, agree a charging spot outside the bedroom and offer a cheap alarm clock so the phone has no excuse to stay.',
  'none',
  false,
  307
),
(
  'explorer',
  'Comparison and dipping self-esteem',
  'Your child seems flatter and more self-critical lately, often after time on their phone, comparing their life to what others post.',
  'I have noticed you have seemed a bit down on yourself. I want to say one thing and then drop it. You are comparing your whole messy inside to everyone else''s best ten seconds. That is not a fair fight, and it is not the truth about you.',
  'Stop comparing yourself to other people, it is pathetic and a waste of time.',
  'Identity is actively forming at this age, and social media offers an endless stream of curated highlights to measure against, which the comparison wired adolescent brain finds hard to resist. Self-esteem dips are common and usually not permanent. Naming the unfair comparison gently, without shaming the feeling, protects the relationship and the self-worth at once.',
  'Tonight, tell them one specific thing you genuinely admire about who they are, not how they look.',
  'none',
  false,
  308
),
(
  'explorer',
  'Worry about too much gaming',
  'You are concerned your child is spending too long gaming and struggling to stop when they say they will.',
  'I want to get this right rather than just nag you. Games are built by very clever people to be hard to put down, so the struggle to stop is not a flaw in you. Let us work out together what a good amount looks like, and what would actually help you stop when you mean to.',
  'You are addicted to that game, you need to get a life and go outside.',
  'Games are engineered around variable rewards that drive the dopamine system, and the adolescent brain, with its still maturing self-control, finds these especially gripping. Calling it addiction or laziness shames a normal response to good engineering design. Treating stopping as a shared design problem teaches a skill they will use for life.',
  'Tonight, ask them to show you one trick the game uses to keep them playing. Be curious, not cross.',
  'none',
  false,
  309
),
(
  'explorer',
  'Online friends they have never met in person',
  'Your child talks about friends they have made online, through games or apps, whom they have never met face to face.',
  'I am genuinely glad you have people you click with, and online friendships can be real and good. I am not going to tell you they are not real friends. What I do want is to understand who they are with you, because not everyone online is who they say, and that is just worth us keeping our eyes open about together.',
  'You have no idea who that person really is, stop talking to strangers online.',
  'For this generation online friendships are genuine social bonds, and dismissing them outright tells your child you do not understand their world. At the same time, the adolescent drive toward connection can outrun their still developing judgement about risk. Respecting the friendship while staying involved is what keeps them telling you the truth about it.',
  'Tonight, ask them to tell you about one online friend the way they would a friend from school. Stay interested.',
  'none',
  false,
  310
),
(
  'explorer',
  'A first calm conversation about nudes and pressure',
  'Your child is at the age where the topic of being asked to send a photo, or seeing one shared, may come up, and you want to have a calm first conversation before it does.',
  'I want to talk about something a bit awkward, calmly, before it ever comes up. Sometimes people get pressured to send photos of themselves. If anyone ever asks you, the answer is always no, and you will never be in trouble with me for telling me it happened. That door is always open.',
  'If you ever send a photo like that you will be in serious trouble, do you understand me.',
  'Leading with threat guarantees they will hide it if it ever happens, exactly when they most need an adult. Peer pressure carries enormous weight at this age, and the impulse to please can outpace the still developing brakes of the prefrontal cortex. A calm, blame free conversation in advance makes you the person they come to, rather than the person they fear.',
  'Tonight, plant one sentence: whatever happens, you will never be in trouble for telling me. Then leave it there.',
  'none',
  false,
  311
),
(
  'explorer',
  'Negotiating more screen autonomy',
  'Your child is pushing for more freedom over their own screen time and resents rules they feel are babyish.',
  'You are growing up and it makes sense that you want more say over your own time. I am up for that. Freedom and trust go together though, so let us agree what more freedom looks like, and how we both know it is going well. If it works, it grows.',
  'You get freedom when you earn it, and right now you have not earned anything.',
  'Autonomy is the central developmental task of adolescence, and rules that feel babyish breed exactly the rebellion they are meant to prevent. Granting expanding freedom tied to visible responsibility works with the developing brain''s need for independence rather than against it. Negotiation also models the very judgement you want them to build.',
  'Tonight, agree one specific freedom they gain this month and what keeps it. Write it down together.',
  'none',
  false,
  312
),
(
  'explorer',
  'The link between mood and the phone',
  'You have noticed your child often comes off their phone in a worse mood, but they have not made the connection themselves.',
  'I have noticed something and I am curious whether you have too. You often seem a bit flatter after a long scroll than before it. I am not saying give it up. I just wonder if it is worth us both noticing how different apps actually leave you feeling.',
  'That phone is making you miserable, anyone can see it, so just put it down.',
  'Self-awareness about emotional triggers is a skill that is only beginning to develop at this age, and a feed designed to maximise engagement is not designed to leave anyone feeling good. Inviting them to notice the pattern themselves builds a lasting internal compass. Telling them how they feel just provokes denial and shuts the noticing down.',
  'Tonight, ask them which app leaves them feeling best and which leaves them worst. Let the answer surprise you both.',
  'none',
  false,
  313
),
(
  'explorer',
  'A secret or second account',
  'You have discovered your child has a second, hidden account that you did not know about.',
  'I found out there is another account, and my honest first feeling was hurt. But before I get into that, I want to understand why. Most people your age have one for a reason that makes sense to them. Help me get it, and let us talk about how we move forward.',
  'A secret account, so you have been lying to me this whole time. I cannot trust you at all now.',
  'Hidden accounts are extremely common at this age and usually reflect a healthy drive for a private space away from adult and family eyes, not deception for its own sake. Identity formation needs room to experiment. Reacting with betrayal confirms that honesty leads to punishment, while seeking the reason keeps the relationship, and your influence, intact.',
  'Tonight, lead with curiosity about the why before any consequence. Understand it before you judge it.',
  'none',
  false,
  314
),
(
  'explorer',
  'Doomscrolling distressing news',
  'Your child has been scrolling through frightening or upsetting news and world events and seems anxious or overwhelmed by it.',
  'It looks like a lot of heavy stuff has been coming up on your feed, and it is genuinely hard to take in that much at once. It is good to care about the world. It is also fine to put it down for a bit. You are allowed to look after yourself and still be someone who cares.',
  'Stop reading the news if it upsets you, there is nothing you can do about any of it anyway.',
  'The feed surfaces alarming content because it captures attention, and the still developing brain has not yet built strong filters for managing a constant stream of distant threat. The result is anxiety without any outlet for action. Permitting them to care and to step back at the same time teaches sustainable engagement, rather than either numbness or overwhelm.',
  'Tonight, help them turn the feeling into one small real action, then agree it is okay to step away.',
  'none',
  false,
  315
),
(
  'explorer',
  'Wanting to become a creator or go viral',
  'Your child dreams of becoming a creator, getting followers, or going viral, and talks about it as a real goal.',
  'I love that you make things and want people to see them. That is brilliant. Let us make this about what you create, not just the numbers. The likes are designed to come and go and they will mess with your head if you let them be the point. The work you are proud of, that lasts.',
  'You are not going to become famous on the internet, focus on something real instead.',
  'The desire for status and recognition peaks in adolescence, and platforms convert that into chasing metrics that trigger dopamine in unpredictable bursts, which is hard on a developing reward system. Dismissing the dream loses their trust. Redirecting it toward craft and pride, rather than the volatile scoreboard of likes, protects their sense of worth while honouring the ambition.',
  'Tonight, ask to see something they have made and respond to the work itself, not the view count.',
  'none',
  false,
  316
),
(
  'explorer',
  'Privacy and their digital footprint',
  'Your child shares freely online and has not yet thought about how permanent and public their digital trail is.',
  'Here is something the apps will never tell you. What you post does not really disappear, and a version of it can follow you for years. I am not trying to scare you. I want you to be the one in charge of what is out there about you, instead of leaving that to chance.',
  'You are putting your whole life online and one day it is going to come back to bite you.',
  'Adolescents live intensely in the present, and the part of the brain that weighs long term consequences is still maturing, so the permanence of a post is genuinely hard to feel. Framing privacy as power and control, rather than as a warning about future regret, fits the developmental wish for autonomy and is far more likely to change behaviour.',
  'Tonight, search their name together and check their privacy settings as a shared project, with no judgement.',
  'none',
  false,
  317
);
