-- Guided Childhood: Foundation stage scripts (ages 4 to 7). Run after seed.sql.
insert into public.scripts
  (stage_id, title, situation, say_this, not_this, why_it_works, tonight, law_flag, is_free, sort_order)
values
(
  'foundation',
  'YouTube autoplay rabbit hole',
  'You said yes to one video and twenty minutes later they are deep into something you never chose, eyes glazed, asking for just one more.',
  'I can see the screen keeps choosing for you. That is its job, not yours. Let us pick the next one together, and then we will be done.',
  '"Right, that is it, screen off now." Yanking it away mid-video without warning triggers the meltdown you are trying to avoid.',
  'Autoplay is built to remove the natural stopping point. Each new video delivers a small hit of dopamine, and a young brain has almost no braking system to say enough. You are not fighting your child, you are fighting a design choice. Bringing the choosing back to a person restores the pause the platform removed.',
  'Open the settings on your tablet or TV app and turn autoplay off tonight. One toggle does more than ten reminders.',
  'none',
  false,
  101
),
(
  'foundation',
  'First time on a new app',
  'Your child has been given a new app or game and wants to dive straight in on their own.',
  'This one is new to both of us. Let us explore it together first, then I will know it is a good fit for you.',
  '"Fine, just go and play it." Handing over something unknown means the app sets the rules before you do.',
  'Sitting beside your child for a first go is co-regulation in action. You become the calm reference point as they meet something exciting and unfamiliar. It also lets you spot adverts, chat features, or pressure to spend before they do. The message that lands is simple: new things are explored with someone you trust.',
  'Before bed, agree that any brand new app gets a together go first. Try the next one side by side this week.',
  'none',
  false,
  102
),
(
  'foundation',
  'Screens at a restaurant',
  'You are out for a meal or stuck in a waiting room, and the temptation is to hand over the phone to keep the peace.',
  'It is a long wait, is it not. Let us see what game we can make up with just us two, and the screen can be our backup if we need it.',
  '"Here, take my phone and be quiet." The screen becomes the only tool your child has for boredom, every single time.',
  'Boredom is where a young brain learns to generate its own ideas. If a screen arrives the moment things go flat, that muscle never gets used. You do not have to ban the phone, you just want it to be the second option, not the first. Waiting together, even badly, builds the patience the screen would have replaced.',
  'Put two small things in your bag tonight, a pencil and paper or a tiny toy, so the phone is not your only rescue tomorrow.',
  'none',
  false,
  103
),
(
  'foundation',
  'Stumbling on something scary',
  'Your child has seen something upsetting or frightening on a screen, and they are shaken or will not settle.',
  'That looked scary, and it is okay that it gave you a wobbly feeling. You are safe here with me. Tell me what you saw and we will sort it out together.',
  '"It was not even real, do not be silly." Dismissing the fear teaches them not to come to you next time.',
  'A young child cannot reliably tell the real from the pretend, so the fear response is genuine. Your calm presence is what brings their nervous system back down, a process called co-regulation. By naming the feeling and staying steady, you become the safe place they return to. That trust is what makes them tell you when something worse appears later.',
  'Tonight, agree a simple word or signal your child can use to tell you a screen has shown them something they did not like.',
  'none',
  false,
  104
),
(
  'foundation',
  'The buy this tantrum',
  'A game or app is pushing your child to buy coins, characters, or extras, and the no has turned into tears.',
  'The game is trying really hard to get us to spend money. That is a clever trick, not a real need. We are not buying it, and I know that feels unfair right now.',
  '"Stop crying and I will get you one thing." Giving in once teaches the tantrum that it works.',
  'These prompts are engineered to feel urgent to a brain that cannot yet weigh long term against right now. Your child is not being greedy, they are responding exactly as the design intends. Naming the trick out loud hands them a thought they can use against it. The calm, steady no is what builds the tolerance for disappointment they will need for years.',
  'Turn on purchase confirmation or a password on your app store tonight so no spend can happen by accident.',
  'none',
  false,
  105
),
(
  'foundation',
  'Different rules at grandparents',
  'Screen time runs looser at the grandparents house, and your child has noticed the rules change when they visit.',
  'Grandma and Grandpa do things their way in their house, and that is lovely. Our family has our own way too, and we pick it back up when we get home.',
  '"They let you do anything, it is ruining everything." Turning it into a conflict puts your child in the middle of the adults.',
  'Young children can hold the idea that different places have different rules, the same way nursery and home differ. The consistency that matters is yours at home, not perfect agreement everywhere. Framing it warmly avoids making your child feel they must choose a side. A quiet word with the grandparents about one or two non-negotiables does more than a public rule.',
  'Tonight, decide your one true non-negotiable for visits, and message it kindly to the grandparents before the next stay.',
  'none',
  false,
  106
),
(
  'foundation',
  'My friend gets more',
  'Your child has come home insisting a friend is allowed far more screen time, and it is not fair.',
  'It sounds like that does feel unfair. Different families make different choices, and our choice is the one that is right for you. I am always happy to hear why you want more.',
  '"I do not care what they are allowed." Shutting it down fast tells your child their feelings are not worth hearing.',
  'Comparison is how children learn where the boundaries of their world sit, so the protest is healthy, not defiant. Acknowledging the feeling without caving keeps the boundary firm and the relationship warm. You are modelling that families can differ without one being wrong. Over time this builds a child who can hold their own line when friends do things differently.',
  'Tonight, let your child finish telling you why they want more, then thank them for explaining without changing the rule.',
  'none',
  false,
  107
),
(
  'foundation',
  'Screens before school',
  'A quick show before school has turned mornings into a battle, with screen time bleeding into getting ready.',
  'Mornings work better when our brains wake up slowly, so screens are for after school now. Let us find a different way to start the day together.',
  '"You can watch but only if you are dressed in five minutes." Bargaining keeps the screen as the prize and the pressure on.',
  'A screen first thing floods a barely awake brain with fast stimulation, which makes the slow tasks of getting ready feel even duller. Removing it stops the morning becoming a negotiation. A young child copes far better with a clear, calm rule than a moving target. Replacing the show with a small shared routine gives the same comfort without the cost.',
  'Tonight, pick one simple morning anchor, a song, a stretch, or breakfast chat, to take the screens place tomorrow.',
  'none',
  false,
  108
),
(
  'foundation',
  'Screen as a reward',
  'You have started using screen time to get good behaviour, and now everything has become a negotiation for screens.',
  'I want you to tidy up because it helps our family, not to earn a screen. We can still have screen time later, and it is not a prize for being good.',
  '"If you are good you can have the tablet." This makes the screen the most valuable thing in the house.',
  'When a screen becomes the reward, its value climbs every time you use it as a bribe, and ordinary cooperation fades without it. You also tie a calm activity to performance, which raises the stakes of every ask. Separating the two keeps screen time ordinary rather than precious. Helping because it matters to the family builds a stronger motivation than any prize.',
  'Tonight, name one thing your child does just because it helps, and thank them for it without mentioning screens.',
  'none',
  false,
  109
),
(
  'foundation',
  'First video call with a relative',
  'Your child is about to video call a grandparent or relative, and may be shy, restless, or unsure what to do.',
  'Granny is going to pop up on the screen and she cannot wait to see you. You can show her something or just say hello, whatever feels good.',
  '"Sit still and talk properly to your nan." Forcing the performance makes the call something to dread.',
  'A video call is a strange middle ground for a young child, a real person who is not really there, which can feel oddly flat. Giving them something to show turns the call from a test into a shared activity. Low pressure keeps the connection warm rather than awkward. These early calls build the idea that screens can carry real relationships, not just entertainment.',
  'Tonight, help your child choose one thing to show on the next call, a drawing, a toy, or a new trick.',
  'none',
  false,
  110
),
(
  'foundation',
  'Obsessed with one show',
  'Your child wants the same character or show on a loop, and any other suggestion is met with a flat refusal.',
  'You really love this one, do you not. It feels good to watch something you know. Let us watch a bit, and then I have something new I think you will like too.',
  '"You watch this every single day, I am sick of it." Mocking the obsession shames a need for comfort and predictability.',
  'Repetition is genuinely soothing to a young brain, because knowing what comes next lowers anxiety and feels safe. The favourite show is doing a real job for them. You do not need to crush the love, just gently widen the world around it. Honouring the comfort while introducing the new keeps your child open rather than dug in.',
  'Tonight, watch the favourite without complaint, then offer one new thing right after while they are relaxed.',
  'none',
  false,
  111
),
(
  'foundation',
  'Adverts aimed at children',
  'An app or video is firing adverts at your young child, and they have started asking for everything they see.',
  'That was an advert. Its whole job is to make you want something. Wanting it is normal, but we do not have to buy what the advert tells us to.',
  '"Ignore it, it is just an advert." Without explanation, the pull of the advert still does its quiet work.',
  'Children under about seven cannot reliably tell an advert from the programme, so the persuasion lands unfiltered. Naming the advert as a thing with a job gives your child a frame they can spot it through next time. You are building early media literacy, one of the strongest protections there is. The aim is not to stop the wanting but to make the trick visible.',
  'Tonight, play spot the advert during a show, and let your child point them out before you do.',
  'none',
  false,
  112
),
(
  'foundation',
  'Devices in the bedroom',
  'Your child wants to take a tablet or screen into their bedroom, especially around bedtime.',
  'Screens live downstairs at night, even mine. Bedrooms are for resting and sleeping. We can have screen time together earlier instead.',
  '"Just this once you can take it up." One exception quietly becomes the new normal.',
  'The bedroom is where sleep is learned, and screens disrupt it twice, through bright light that delays sleepiness and through content that keeps the brain switched on. Setting the rule early, before it is a habit, makes it far easier to keep. Including your own phone in the rule removes the do as I say problem. A screen free bedroom is one of the simplest, highest value boundaries you can set now.',
  'Tonight, set up one charging spot downstairs for the whole family, and put your own phone there too.',
  'none',
  false,
  113
),
(
  'foundation',
  'Family posting photos online',
  'A relative regularly posts photos of your child online, and you are uneasy about it but unsure how to raise it.',
  'We love that you adore the photos. We have decided to keep theirs off public profiles for now. Send them to us any time, just not to the wider world.',
  '"It is fine, do not make a fuss." Staying quiet to avoid awkwardness hands your childs privacy to someone else.',
  'Your child cannot consent to a public footprint that may follow them for years, which is why the choice sits with you for now. Framing it as a family decision rather than a complaint keeps relationships intact. You are modelling that consent and privacy matter, even within a loving family. Raising it early, before patterns set, is far easier than unpicking it later.',
  'Tonight, agree your familys photo rule between the two parents, then share it warmly with relatives as a settled decision.',
  'none',
  false,
  114
),
(
  'foundation',
  'Meltdown moving to dinner',
  'Calling your child off a screen to come to the table tips them straight into a meltdown, every time.',
  'I know it is really hard to stop when you are having fun. Your brain wants to keep going. Two more minutes, then we save it and come to dinner together.',
  '"Dinner is ready now, screen off, come on." A sudden stop gives the brain no time to switch tracks.',
  'Stopping a screen drops dopamine sharply, and a young brain feels that as a real loss, not a tantrum for effect. The meltdown is a nervous system reaction to an abrupt change, not defiance. A short, warned bridge gives the brain time to shift gear before the screen goes off. Naming the difficulty and counting it down together turns the cliff edge into a slope.',
  'Tonight, give a clear two-minute warning before dinner, and watch whether the landing is softer.',
  'none',
  false,
  115
),
(
  'foundation',
  'Learning versus entertainment',
  'You are unsure how to handle the difference between screen time that teaches and screen time that just entertains.',
  'Some screen things help your brain grow, like the ones where you make or solve or build. Others are just for fun, and a bit of fun is fine too. Let us notice which is which.',
  '"As long as it is educational it does not count." Treating learning apps as unlimited misses that all screens still need balance.',
  'Not all screen time is equal, but no screen replaces the messy, hands on play that grows a young brain most. Even good learning apps benefit from limits, because the body and the senses learn things a screen cannot teach. Helping your child notice the difference builds judgement they will use for life. The goal is a balanced diet of screens, not a free pass for the educational ones.',
  'Tonight, sort two of your childs apps together into making something or just watching, out loud.',
  'none',
  false,
  116
),
(
  'foundation',
  'The game their friends play',
  'Your child has asked, for the first time, to play a game because all of their friends are playing it.',
  'I can tell this one really matters because your friends love it. Let me have a proper look at it first, and then we will decide together if it is right for you.',
  '"No, that game is for big kids." A flat no with no look teaches your child to stop asking and start hiding.',
  'Wanting to belong is one of the strongest drives at this age, so this request is about friendship as much as the game. Taking it seriously, rather than dismissing it, keeps your child bringing these asks to you. Checking the game yourself models the very judgement you want them to grow. Whether the answer is yes or not yet, the open conversation is the real win.',
  'Tonight, find out the name of the game and spend ten minutes looking it up before you decide anything.',
  'none',
  false,
  117
);
