-- Guided Childhood: Shaper stage scripts (ages 13 to 15). Run after seed.sql.
insert into public.scripts
  (stage_id, title, situation, say_this, not_this, why_it_works, tonight, law_flag, is_free, sort_order)
values
(
  'shaper',
  'Something has gone wrong and they are scared to tell you',
  'You sense your teenager is carrying something heavy that happened online, but they are afraid of how you will react.',
  'Whatever it is, you are not in trouble for telling me. I would rather know and help than have you carry it alone. There is almost nothing you could say that we cannot sort out together. Take your time.',
  '"You can tell me anything, but you had better not have done something stupid." The threat cancels out the invitation and guarantees silence.',
  'At this age the threat-detection system is highly active while the brakes of the prefrontal cortex are still maturing, so fear of your reaction can outweigh the need for help. Leading with safety, not consequences, lowers that threat response and lets them think clearly. A teenager who believes coming to you is safe will come to you sooner next time, which is when problems are still small.',
  'Say out loud, with no problem on the table, that they will never be in trouble simply for telling you something. Plant it before they need it.',
  'none',
  false,
  401
),
(
  'shaper',
  'Heavy social media use and their mood',
  'You have noticed your teenager seems flatter or more irritable, and it tracks with long stretches on social media.',
  'I have noticed you seem a bit low lately, and I am not blaming the phone. I just want to understand how you are feeling. Can we talk about what is going on for you, on the apps and off them?',
  '"That phone is making you miserable, give it here." It treats the device as the whole cause and shuts down the conversation you actually need.',
  'Heavy passive scrolling is linked with lower mood in some teenagers, though the picture is complex and the phone is rarely the only factor. Leading with curiosity rather than blame keeps them talking, which is how you find the real driver. If low mood persists for more than a couple of weeks, affects sleep or appetite, or worries you, it is worth speaking to your GP or a mental health professional. You do not have to diagnose this alone.',
  'Ask one open question about how they have been feeling lately, and listen without mentioning the phone first.',
  'none',
  false,
  402
),
(
  'shaper',
  'Curious or accidental exposure to pornography',
  'You have learned your teenager has come across pornography, whether by accident, by curiosity, or sent by someone.',
  'I am not angry, and you are not in trouble. Being curious about sex and bodies is completely normal at your age. The thing is, a lot of what is online is not realistic and not how real relationships work, so I want us to be able to talk about it honestly.',
  '"That is disgusting, I never want to hear about you looking at that again." Shame teaches them to hide it and leaves the false picture uncorrected.',
  'Sexual curiosity is a normal part of adolescent development, and most teenagers will encounter pornography. Responding with shame drives the behaviour underground and removes your chance to provide context. Calm conversation lets you separate fantasy from real intimacy, consent, and respect. If the content was extreme, involved coercion, or you are worried about its effect, professional support through your GP or a counsellor is a sensible step.',
  'Decide your own calm opening line in advance, so that if this comes up you respond from a steady place rather than shock.',
  'none',
  false,
  403
),
(
  'shaper',
  'Extreme or radicalising content',
  'Your teenager is repeating extreme views or has been drawn into content that pulls them toward an us-and-them way of seeing the world.',
  'I have heard you say a few things lately that I want to understand better. I am not going to tell you what to think. I do want to know where these ideas are coming from and to think them through with you. Walk me through it.',
  '"That is poison and I forbid you from watching it." Forbidding it confirms the narrative that you are the enemy and they are being silenced.',
  'Adolescents are wired to seek identity, belonging, and certainty, which is exactly what radicalising content offers. Banning it can deepen the appeal and confirm the grievance the content feeds on. Staying curious and reasoning together keeps you inside their thinking, where you can introduce doubt and complexity. If you see fixation, secrecy, or talk of harm, contact your school safeguarding lead or local support services without delay.',
  'Ask them to explain one idea they have picked up, and stay genuinely curious rather than correcting.',
  'none',
  false,
  404
),
(
  'shaper',
  'Self-harm content in their feed',
  'Self-harm or other unhealthy content has started surfacing in your teenager''s feed, whether they sought it out or it was served to them.',
  'I have seen that some heavy stuff is showing up on your feed. I am not cross with you. I want to make sure you are okay, and I want to understand whether you are looking for this or it is just finding you. Either way, we are in this together.',
  '"I am deleting all your apps right now." A sudden cut-off can feel like punishment for struggling and may stop them telling you anything real.',
  'Recommendation algorithms can amplify distressing content once a teenager engages with it, deepening a low mood loop. Approaching with concern rather than punishment keeps them talking and lets you judge how serious things are. Self-harm content can normalise harmful behaviour, so it matters that they have a trusted adult, not an algorithm, to turn to. If you have any worry that your child is hurting themselves or thinking about it, contact your GP or a mental health professional promptly. You do not need to wait for certainty.',
  'Sit with them and look at how to mute or report this kind of content, so they feel some control over what reaches them.',
  'none',
  false,
  405
),
(
  'shaper',
  'Pressure, consent, and healthy relationships online',
  'Your teenager is navigating early romantic or sexual interest online, including pressure to send photos or do things they are unsure about.',
  'Anyone who really cares about you will never pressure you, and will always take a no without sulking or punishing you. Your body and your choices are yours. If anyone pushes, that tells you something about them, not about you. And you can always come to me.',
  '"Do not ever send pictures or you will ruin your life." Fear-based warnings make them too ashamed to come to you if something has already happened.',
  'Adolescents are highly sensitive to peer approval, which can make it hard to hold a boundary in the moment. Naming consent and pressure in advance gives them words and permission to refuse before they are tested. Framing it around respect rather than catastrophe keeps the door open if a mistake has already been made. If an image has been shared or they are being coerced, report it and seek support, including the police or a specialist service, rather than handling it alone.',
  'Tell them plainly that real care never comes with pressure, so they have the standard in their head before they need it.',
  'none',
  false,
  406
),
(
  'shaper',
  'Holding oversight while they grow independent',
  'Your teenager is asking for more privacy and less monitoring, and you are unsure how much to loosen the reins.',
  'You are getting older and you have earned more privacy. I am not trying to spy on you. My job is shifting from watching to trusting, and the way we keep that trust is honesty both ways. Let us agree what stays private and what I still need to know.',
  '"As long as you live here, I read everything on your phone." Total surveillance at this age breeds resentment and teaches them to hide better.',
  'Autonomy is a core developmental need in adolescence, and granting it in step with maturity supports healthy identity and self-regulation. Heavy-handed monitoring tends to push risky behaviour out of sight rather than reduce it. Shifting from control to negotiated trust keeps you informed of the things that matter most: safety, wellbeing, and who they are talking to. The aim is a teenager who chooses to tell you, not one who has been caught.',
  'Agree one thing you will stop checking and one thing you still need to know about, and say both out loud.',
  'none',
  false,
  407
),
(
  'shaper',
  'Gambling mechanics and loot boxes',
  'Your teenager is spending real or in-game money on loot boxes, skins, or other chance-based rewards in games.',
  'I want to show you something about how these games make money. Those boxes are built to feel like a win even when you lose, the same way a slot machine works. That does not make you daft for enjoying it. It means the design is clever, and I want you to see the trick.',
  '"You are wasting money on rubbish, no more." Banning it without explaining the mechanic leaves the susceptibility in place for the next time.',
  'Loot boxes use variable-ratio rewards, the same reinforcement schedule that makes gambling so compelling, and the adolescent reward system is especially responsive to it. Explaining the mechanism builds genuine resistance, because they learn to recognise the pattern rather than just obey a rule. Teenagers respect being treated as capable of understanding the trick. If spending becomes secretive, distressing, or hard to stop, that is worth taking seriously and may warrant professional support.',
  'Watch a short clip together explaining how loot boxes are designed, and ask them what they notice.',
  'none',
  false,
  408
),
(
  'shaper',
  'Pressure to perform as a creator',
  'Your teenager is posting content and is increasingly anxious about views, likes, followers, or going viral.',
  'I love that you make things. I want to check in on how it feels, not just how it performs. The numbers are not a measure of you. On the days the post does badly, you are exactly the same person you were the day before. Tell me how it has been.',
  '"It is just a silly app, stop caring what strangers think." It dismisses something that feels significant to them and ends the conversation.',
  'Adolescents are acutely tuned to social feedback, and likes and follower counts deliver that feedback in a fast, quantified, and public form. Tying self-worth to metrics can fuel anxiety and a fragile sense of identity. Separating who they are from how a post performs protects self-esteem while still honouring their creativity. If the pressure is causing real distress or compulsive checking, it is worth talking it through with a counsellor.',
  'Ask how creating actually feels day to day, and listen for whether it is bringing joy or just pressure.',
  'none',
  false,
  409
),
(
  'shaper',
  'Chronic sleep loss from devices',
  'Your teenager is regularly up late on their phone and is exhausted, struggling to wake, or running on empty.',
  'You are shattered, and your body genuinely needs more sleep than mine does right now. This is not me being strict for the sake of it. Let us solve the sleep problem together, because everything else gets harder when you are running on empty. What would actually help?',
  '"Phone off at nine, no argument." The flat rule invites a nightly battle and ignores that they need to own the solution to keep it.',
  'Adolescent body clocks shift later, so teenagers are biologically wired to feel awake at night, and screens plus notifications make settling harder. Sustained sleep loss affects mood, concentration, and mental health, all of which are already under strain at this age. Solving it with them rather than imposing it increases the chance the habit sticks, because autonomy supports follow-through. A consistent wind-down and the phone charging outside the room are the highest-impact changes.',
  'Ask them what they think would help them wind down, and build the plan around their answer.',
  'none',
  false,
  410
),
(
  'shaper',
  'Comparison and anxiety',
  'Your teenager seems to measure themselves against the lives, bodies, and successes they see online, and it is feeding anxiety.',
  'What you see on those feeds is the highlight reel, carefully chosen and often edited. You are comparing your whole messy inside to everyone else''s best outside. That is not a fair fight, and it would make anyone feel rotten. You are not falling behind.',
  '"Just stop comparing yourself, it is pointless." Telling them to stop a feeling they cannot control only adds the failure of not managing it.',
  'The adolescent brain is primed for social comparison as part of working out where they fit, and curated feeds supply an endless stream of upward comparisons. This can quietly erode self-esteem and feed anxiety. Naming the highlight-reel effect gives them a frame to question what they see rather than absorb it as truth. If anxiety is persistent or interfering with daily life, a GP or counsellor can help, and seeking that support is a sign of good parenting, not failure.',
  'Look at one polished post together and talk about what was likely cropped, staged, or left out.',
  'none',
  false,
  411
),
(
  'shaper',
  'Supporting a friend in crisis online',
  'Your teenager has a friend who is in distress online, perhaps talking about self-harm or feeling unsafe, and is carrying that weight alone.',
  'It says a lot about you that your friend trusts you. That is a heavy thing to hold by yourself, and you are not meant to carry it alone. Helping a friend in real trouble sometimes means telling a trusted adult, even if they asked you not to. That is not betrayal. That is keeping them safe.',
  '"That is not your problem, just block them and stay out of it." It abandons a frightened friend and teaches your child to look away from someone in need.',
  'Teenagers often become the first point of contact when a peer is struggling, and they can feel torn between loyalty and a promise of secrecy. Carrying that responsibility alone is a real burden and can affect their own wellbeing. Helping them understand when a secret must be shared to keep someone safe protects both the friend and your child. Make sure they know the relevant resources, such as a school counsellor, a GP, or a crisis line, and that adults exist to take this weight from them.',
  'Tell them clearly that a secret which could keep someone safe is one they are allowed to share with you.',
  'none',
  false,
  412
),
(
  'shaper',
  'Location sharing and personal safety',
  'Your teenager shares their location through apps, posts, or with friends, and may not have thought through who can see it.',
  'I am not worried about most of the people you share with. I want you to think about the edges. Who exactly can see where you are, and could that map be seen by someone you do not actually know? Let us go through the settings together so you are the one deciding.',
  '"Turn off all location sharing, it is dangerous." A blanket ban skips teaching the judgement they will rely on once you are not checking.',
  'Adolescents tend to focus on the immediate social benefit of sharing and underweight low-probability risks, partly because the brain''s reward system outpaces its risk-assessment system at this age. Helping them think through who can actually see their location builds lasting judgement rather than dependence on your rules. Putting them in charge of the settings respects their autonomy while raising their awareness. The goal is a teenager who shares deliberately, not by default.',
  'Go through their location settings together and have them decide who stays on and who comes off.',
  'none',
  false,
  413
),
(
  'shaper',
  'Their digital footprint and future',
  'Your teenager is posting freely without much thought for how it might look to a future employer, college, or their older self.',
  'What you post tends to stick around longer than the moment it was made for. I am not saying live in fear of it. I am saying post like a version of you in five years is reading it, because one day they will be. Would future you be glad this is out there?',
  '"One stupid post will ruin your whole life." Catastrophising makes them tune you out rather than think it through.',
  'Adolescents are wired to prioritise the immediate and social over the distant and abstract, so the long-term cost of a post is hard to feel in the moment. Offering a simple, concrete frame, picturing their future self, helps the still-developing prefrontal cortex weigh consequences without inducing paralysing fear. Treating them as capable of foresight tends to draw out more careful behaviour than threats do. The aim is thoughtful posting, not anxious silence.',
  'Ask them to pause before one post and consider whether they would be happy for future them to find it.',
  'none',
  false,
  414
),
(
  'shaper',
  'Standing firm against group pressure',
  'Your teenager is being pushed by a group chat or friends to join in on something they are uneasy about, like piling on someone or sharing a photo.',
  'It is genuinely hard to be the one who says no when everyone else is in. That takes more guts than going along with it. You are allowed to step back, stay quiet, or say it is not for you. If you need a way out, you can always blame me. Say your dad would lose it.',
  '"Just say no, it is simple." It is not simple under that much pressure, and saying so leaves them without a usable strategy.',
  'Peer influence peaks in adolescence, and the presence of peers measurably increases risk-taking by amping up the brain''s reward response. Acknowledging how hard it is to resist, rather than pretending it is easy, validates their real experience and keeps them listening. Giving them a concrete exit, including permission to blame you, hands them a workable tool for the moment of pressure. A teenager with a ready-made out is far more likely to use it.',
  'Offer yourself as the ready-made excuse, so they have a face-saving way out of group pressure.',
  'none',
  false,
  415
),
(
  'shaper',
  'Spotting misinformation and manipulation',
  'Your teenager shares or believes things they have seen online without checking whether they are true or who is behind them.',
  'A lot of what goes viral is designed to make you feel something fast, usually angry or scared, because strong feelings get shared. Before you pass something on, it is worth a pause: who made this, what do they want me to do, and is it actually true? You are smart enough to spot the play.',
  '"Do not believe anything you read online." Blanket cynicism is as useless as blanket trust and gives them no way to tell the two apart.',
  'Adolescents are developing critical reasoning but are also drawn to emotionally charged, identity-affirming content, which is exactly what manipulative material exploits. Teaching a few quick questions about source and intent builds media literacy they can apply themselves, which is far more durable than a rule. Framing them as capable of seeing the manipulation appeals to their growing desire for autonomy and respect. The goal is a discerning teenager, not a cynical or a credulous one.',
  'Take one thing they shared recently and work through together who made it and why.',
  'none',
  false,
  416
),
(
  'shaper',
  'Renegotiating the phone-free bedroom',
  'Your teenager is pushing back on the phone staying out of the bedroom at night, arguing they are old enough to manage it.',
  'You are older now, so let us talk about this properly rather than me just laying down the law. The reason is not trust, it is sleep. Your phone in arm''s reach at night makes good sleep almost impossible for anyone, me included. Let us find a version of this that works for you.',
  '"The rule is the rule, you are not special." Refusing to revisit a rule they have outgrown invites them to break it the moment you are not looking.',
  'As teenagers mature, rules imposed without negotiation lose their force, because autonomy is the developmental priority. The science on sleep, however, does not change: a phone in the bedroom disrupts sleep through notifications, late-night use, and the pull to check. Reopening the conversation respectfully, while holding the principle, models how to keep a sound boundary while honouring their growing independence. A charging spot just outside the room is a common compromise that keeps the principle intact.',
  'Sit down and renegotiate the bedroom phone rule together, holding the sleep principle while updating the detail.',
  'none',
  false,
  417
);
